slint-ui/slint

examples/printerdemo/ui/copy_page.60, examples/printerdemo/ui/scan_page.60, examples/printerdemo/ui/usb_page.60
Just a bit of polish. The functionality is already implemented, so use
it;-)
=> Printerdemo: Do not allow 0 copies

sixtyfps_compiler/builtins.60, sixtyfps_compiler/expression_tree.rs, sixtyfps_compiler/generator.rs, sixtyfps_compiler/generator/cpp.rs, sixtyfps_compiler/generator/rust.rs, sixtyfps_compiler/langtype.rs, sixtyfps_compiler/lib.rs, sixtyfps_compiler/load_builtins.rs, sixtyfps_compiler/namedreference.rs, sixtyfps_compiler/object_tree.rs, sixtyfps_compiler/passes/binding_analysis.rs, sixtyfps_compiler/passes/check_public_api.rs, sixtyfps_compiler/passes/flickable.rs, sixtyfps_compiler/passes/inlining.rs, sixtyfps_compiler/passes/move_declarations.rs, sixtyfps_compiler/passes/remove_aliases.rs, sixtyfps_compiler/passes/repeater_component.rs, sixtyfps_compiler/passes/resolving.rs, sixtyfps_compiler/tests/syntax/lookup/two_way_binding.60, sixtyfps_compiler/typeregister.rs, sixtyfps_runtime/interpreter/dynamic_component.rs, sixtyfps_runtime/interpreter/global_component.rs, tests/cases/bindings/change_sub_property.60, tests/cases/globals/global_binding_const.60
By using Property::set  instead of Property::set_binding for bindings with constant values.
=> Optimisation of constant bindings

sixtyfps_runtime/rendering_backends/qt/lib.rs, sixtyfps_runtime/rendering_backends/qt/qt_window.rs
Use QGraphicsBlurEffect as public API to take the blur into account
=> Improved rendering of drop shadow for Qt

api/sixtyfps-cpp/include/sixtyfps.h, sixtyfps_compiler/expression_tree.rs, sixtyfps_compiler/generator/cpp.rs, sixtyfps_compiler/generator/rust.rs, sixtyfps_compiler/layout.rs, sixtyfps_compiler/object_tree.rs, sixtyfps_compiler/passes/binding_analysis.rs, sixtyfps_compiler/passes/default_geometry.rs, sixtyfps_compiler/passes/lower_layout.rs, sixtyfps_compiler/passes/materialize_fake_properties.rs, sixtyfps_compiler/tests/syntax/analysis/binding_loop_layout.60, sixtyfps_runtime/corelib/component.rs, sixtyfps_runtime/corelib/items.rs, sixtyfps_runtime/corelib/items/image.rs, sixtyfps_runtime/corelib/items/text.rs, sixtyfps_runtime/corelib/layout.rs, sixtyfps_runtime/corelib/model.rs, sixtyfps_runtime/interpreter/api.rs, sixtyfps_runtime/interpreter/dynamic_component.rs, sixtyfps_runtime/interpreter/eval.rs, sixtyfps_runtime/interpreter/eval_layout.rs, sixtyfps_runtime/rendering_backends/gl/graphics_window.rs, sixtyfps_runtime/rendering_backends/qt/qt_window.rs, sixtyfps_runtime/rendering_backends/qt/widgets.rs, tests/cases/layout/box_precentages.60, tests/cases/layout/issue_160_box_min_max.60
So that we can do 'height for width' later.
This implement the interpreter and the rust code, but the C++ is not done yet.
=> split vertical and horizontal pass in layouts

CHANGELOG.md, docs/layouting.md, docs/widgets.md, examples/7gui/booker.60, examples/7gui/circledraw.60, examples/7gui/counter.60, examples/7gui/crud.60, examples/7gui/tempconv.60, examples/7gui/timer.60, examples/gallery/gallery.60, examples/todo/ui/todo.60, sixtyfps_compiler/layout.rs, sixtyfps_compiler/lib.rs, sixtyfps_compiler/passes/lower_layout.rs, sixtyfps_compiler/widgets/native/sixtyfps_widgets.60, sixtyfps_compiler/widgets/ugly/sixtyfps_widgets.60
and add Box widgets that have proper defaults
Closes #200
=> Layout: Make the default padding and spacing 0

api/sixtyfps-node/native/js_model.rs, api/sixtyfps-node/native/lib.rs, api/sixtyfps-rs/sixtyfps-build/lib.rs, docs/tutorial/cpp/src/CMakeLists.txt, helper_crates/vtable/macro/macro.rs, sixtyfps_compiler/generator/cpp.rs, sixtyfps_compiler/generator/rust.rs, sixtyfps_compiler/literals.rs, sixtyfps_compiler/namedreference.rs, sixtyfps_compiler/passes/binding_analysis.rs, sixtyfps_compiler/passes/lower_popups.rs, sixtyfps_compiler/passes/resolving.rs, sixtyfps_compiler/tests/syntax_tests.rs, sixtyfps_runtime/corelib/item_tree.rs, sixtyfps_runtime/interpreter/dynamic_component.rs, sixtyfps_runtime/interpreter/eval.rs, sixtyfps_runtime/rendering_backends/gl/fonts.rs
Just an attempt to clean out the list of issues I see when I open 60fps :-)
Sorry, the patch names are not too descriptive.
I find the Code Spell Checker very helpful while coding.
=> Just typos in code

cspell.json, helper_crates/const-field-offset/macro/macro.rs, sixtyfps_runtime/corelib/graphics/color.rs, tools/fmt/main.rs
Sorry for all the boring busywork I keep pushing! It is mind-numbing, which helps me relax:-)
Anyway: More spelling fixes...
=> More spelling fixes

sixtyfps_runtime/corelib_macros/lib.rs, tests/driver/rust/build.rs
Tackle some simple clippy warnings
=> clippy warnings

sixtyfps_runtime/corelib/input.rs
This code abuses a loop for flow control. Split this out into a separate
function instead, using a custom enum to transfer the information back.
This is necessary since we need to transfer ownership of the
mouse_input_state back to the caller.
This change should not cause a behavior change.
=> Janitor: Fix clippy error about a loop that never loops

sixtyfps_compiler/passes/binding_analysis.rs, sixtyfps_compiler/passes/check_public_api.rs, sixtyfps_compiler/passes/flickable.rs, sixtyfps_compiler/passes/transform_and_opacity.rs, sixtyfps_compiler/typeregister.rs, sixtyfps_runtime/corelib/model.rs, sixtyfps_runtime/corelib/properties.rs
These are probably uncontroversial...
=> Some more clippy fixes

CHANGELOG.md, api/sixtyfps-cpp/include/sixtyfps_interpreter.h, api/sixtyfps-cpp/tests/interpreter.cpp, sixtyfps_runtime/interpreter/api.rs, sixtyfps_runtime/interpreter/ffi.rs
=> C++: Expose conversion betwen `Value` and `Image`

tools/figma_import/Cargo.toml, tools/figma_import/src/figmatypes.rs, tools/figma_import/src/main.rs
The Figma importer was not compiling. Fix it.
=> Fix figma importer

CHANGELOG.md, docs/builtin_elements.md, sixtyfps_compiler/builtins.60, sixtyfps_compiler/passes.rs, sixtyfps_compiler/passes/clip.rs, sixtyfps_compiler/passes/materialize_fake_properties.rs, sixtyfps_compiler/passes/transform_and_opacity.rs, sixtyfps_compiler/passes/visible.rs, sixtyfps_compiler/tests/syntax/basic/clip.60, sixtyfps_runtime/corelib/items.rs, tests/cases/examples/rectangle_clip.60, tests/cases/input/clip_mouse.60, tests/cases/input/visible_mouse.60
This is done by adding an empty Clip Item in the item tree, and clipping it when the visible property is false
Closes #141
=> Implement the visible property

api/sixtyfps-rs/lib.rs, sixtyfps_compiler/generator/rust.rs
The binding setup functions (set_binding, set_animated_binding, etc.)
are taking the binding basically as an `impl Fn() -> T`, which means
each call site creates a new copy. The bodies of these can be quite big.
Since most of our uses follow the pattern of just capturing the
samereduce the number of copies needed parameter, we can reduce the
number of copies needed by providing wrappers.
With rustc 1.54.0 on my mbp and debug, the build time of
touch ../ui/printerdemo.60
cargo rustc
goes from 1m:15s down to 42s, and total llvm lines goes from
2079842 down to 1134237.
=> Rust: Speed up compilation times of generated code

CHANGELOG.md, docs/widgets.md, sixtyfps_compiler/builtins.60, sixtyfps_compiler/widgets/ugly/sixtyfps_widgets.60, sixtyfps_runtime/rendering_backends/qt/widgets.rs
=> Add a `changed` callback to `Slider`

sixtyfps_runtime/rendering_backends/qt/qt_window.rs
We calculate the cursor position as byte offset in the utf-8 encoded string,
while Qt expects an index in the utf-16 encoded QString.
When those differ, the cursor is rendered at the wrong location.
Fixes #363
=> Fix cursor rendering with the Qt backend for non-ascii text

sixtyfps_compiler/expression_tree.rs, sixtyfps_compiler/generator/cpp.rs, sixtyfps_compiler/generator/rust.rs, sixtyfps_compiler/passes/embed_resources.rs, sixtyfps_runtime/corelib/graphics/image.rs, sixtyfps_runtime/interpreter/eval.rs, sixtyfps_runtime/rendering_backends/gl/images.rs, sixtyfps_runtime/rendering_backends/qt/qt_window.rs, sixtyfps_runtime/rendering_backends/testing/lib.rs
This is usefull for the detection of SVG
=> For embedded data, store the extension in the binary

CHANGELOG.md, docs/widgets.md, examples/gallery/gallery.60, sixtyfps_compiler/builtins.60, sixtyfps_compiler/passes.rs, sixtyfps_compiler/passes/default_geometry.rs, sixtyfps_compiler/passes/lower_popups.rs, sixtyfps_compiler/passes/lower_tabwidget.rs, sixtyfps_compiler/tests/syntax/elements/tabwidget.60, sixtyfps_compiler/tests/syntax/elements/tabwidget2.60, sixtyfps_compiler/widgets/native/sixtyfps_widgets.60, sixtyfps_compiler/widgets/ugly/sixtyfps_widgets.60, sixtyfps_runtime/interpreter/dynamic_component.rs, sixtyfps_runtime/rendering_backends/qt/lib.rs, sixtyfps_runtime/rendering_backends/qt/widgets.rs, tests/cases/elements/tabwidget.60, xtask/src/cbindgen.rs
Closes #356 
https://user-images.githubusercontent.com/959326/128503270-ab5a9f00-6600-4419-b574-20cacf3cb486.mp4
=> Add TabWidget

api/sixtyfps-cpp/include/sixtyfps.h, sixtyfps_runtime/corelib/model.rs, sixtyfps_runtime/interpreter/value_model.rs
... and improve the documentation of Model
=> Print an warning in stderr when modifying read-only model

sixtyfps_runtime/corelib/window.rs, sixtyfps_runtime/rendering_backends/gl/event_loop.rs, sixtyfps_runtime/rendering_backends/gl/graphics_window.rs, sixtyfps_runtime/rendering_backends/gl/lib.rs, sixtyfps_runtime/rendering_backends/qt/qt_window.rs, sixtyfps_runtime/rendering_backends/testing/lib.rs
I need to do more testing (results are looking okay at first glance), but code wise I think that this is ready for review.
=> Window abstraction cleanups

CHANGELOG.md, api/sixtyfps-cpp/include/sixtyfps.h, api/sixtyfps-cpp/tests/eventloop.cpp
A blocking version of invoke_from_event_loop
=> C++: add blocking_invoke_from_event_loop

sixtyfps_compiler/typeloader.rs, sixtyfps_compiler/widgets/common/common.60, sixtyfps_compiler/widgets/fluent/sixtyfps_widgets.60, sixtyfps_compiler/widgets/native/sixtyfps_widgets.60, sixtyfps_compiler/widgets/ugly/sixtyfps_widgets.60
So that we can share some code accross styles
=> Refactor the way the builtin files are loaded

CHANGELOG.md, sixtyfps_runtime/corelib/items.rs, sixtyfps_runtime/rendering_backends/qt/qt_widgets/button.rs, sixtyfps_runtime/rendering_backends/qt/qt_widgets/checkbox.rs
=> Only emit click when clicking and releasing the mouse within the TouchArea

sixtyfps_runtime/rendering_backends/gl/graphics_window.rs
This fixes the panic when using auto-reload with the viewer and the GL backend
=> Improve borrow granularity

sixtyfps_runtime/rendering_backends/gl/graphics_window.rs
Use std::cell:Ref/RefMut to reduce the indentation and make it easier to
see where the borrow occurs.
=> GL backend: clean up of window map state handling

sixtyfps_compiler/object_tree.rs, sixtyfps_compiler/tests/syntax/basic/type_declaration.60, tests/cases/globals/global_callback.60
It's already working, we just need to remove the error handling :-)
Fixes #467
=> Allow global singletons to have default callback handlers

examples/gallery/gallery.60
to something that might make more sense to read :-)
=> gallery: Change the text of the textedit example

api/sixtyfps-cpp/include/sixtyfps_interpreter.h, api/sixtyfps-cpp/tests/interpreter.cpp, sixtyfps_compiler/object_tree.rs, sixtyfps_compiler/typeloader.rs, sixtyfps_runtime/interpreter/api.rs, sixtyfps_runtime/interpreter/dynamic_component.rs, sixtyfps_runtime/interpreter/ffi.rs, sixtyfps_runtime/interpreter/global_component.rs
=> Add support for querying globals in the Rust/C++ interpreter API

.github/workflows/ci.yaml
The new version promises improved diagnostics (log files) and security
fixes.
=> Bump run-cmake Github Action version in the CI

sixtyfps_runtime/interpreter/api.rs, sixtyfps_runtime/interpreter/eval.rs
=> Interpreter: add type checking for declared properties

CHANGELOG.md, tools/viewer/Cargo.toml, tools/viewer/main.rs
=> Viewer: add ability to load and save property values from/to json

docs/builtin_elements.md, sixtyfps_compiler/passes/lower_layout.rs, sixtyfps_compiler/passes/move_declarations.rs, sixtyfps_compiler/tests/syntax/basic/dialog.60, tests/cases/elements/dialog.60, tools/viewer/main.rs
And make the viewer listen to them and set them to automatically close dialogs
=> Dialog: automatically add clicked callback for the standard button

.github/workflows/ci.yaml
=> Try to optimize CI cache

CHANGELOG.md, docs/builtin_elements.md, sixtyfps_compiler/builtins.60, sixtyfps_compiler/widgets/fluent/sixtyfps_widgets.60, sixtyfps_compiler/widgets/fluent/sixtyfps_widgets_impl.60, sixtyfps_runtime/corelib/items.rs
=> Add callback to TouchArea and use it to fix the Slider and Scroll Bar

CHANGELOG.md, api/sixtyfps-cpp/cbindgen.rs, api/sixtyfps-cpp/include/sixtyfps.h, docs/builtin_elements.md, sixtyfps_compiler/builtins.60, sixtyfps_compiler/typeregister.rs, sixtyfps_compiler/widgets/fluent/sixtyfps_widgets.60, sixtyfps_compiler/widgets/fluent/sixtyfps_widgets_impl.60, sixtyfps_runtime/corelib/flickable.rs, sixtyfps_runtime/corelib/input.rs, sixtyfps_runtime/corelib/items.rs, sixtyfps_runtime/corelib/items/text.rs, sixtyfps_runtime/corelib/rtti.rs, sixtyfps_runtime/corelib/tests.rs, sixtyfps_runtime/corelib/window.rs, sixtyfps_runtime/interpreter/api.rs, sixtyfps_runtime/interpreter/dynamic_component.rs, sixtyfps_runtime/rendering_backends/gl/event_loop.rs, sixtyfps_runtime/rendering_backends/qt/qt_widgets/slider.rs, sixtyfps_runtime/rendering_backends/qt/qt_window.rs, tests/cases/elements/toucharea.60
... instead of `pressed-changed`
This allows to dee what mouse button was pressed.
Closes #535
=> TouchArea: add the `pointer-event` callback

sixtyfps_runtime/rendering_backends/gl/fonts.rs
The database is not empty, as the changed expect() suggests, but instead
it just means that the family could not be found. This can happen for
example with something like this:
export App := Window {
Text {
text: "Ok";
font-family: "Non-existent";
}
}
or it can also happen when loading the printer demo in the online
editor, where a custom font is supposed to be available but that's not
implemented for wasm builds.
So instead of panicing, fall back to querying for a last-resort
sans-serif family.
For Linux, we register fontconfig's choice for sans-serif, otherwise
fontdb has defaults for macOS and Windows, and for wasm we register our
copy of DejaVu. So that cannot really fail....
=> Fix panic with GL backend when using non-existent font families

api/sixtyfps-cpp/docs/cmake.md
Hello. Bulding any library from the source code is quit difficult. You should have compiler and time.
So I suppose to swap paragraphs `Building from Sources` and `Binary packages`
=> [DOCS] Update cmake.md

sixtyfps_compiler/generator.rs, sixtyfps_compiler/generator/cpp.rs, sixtyfps_compiler/passes/generate_item_indices.rs
Use a trait instead of two functions
The idea is that it would allow to share more code with the other frontend, but in fact, i'm not sure if that's the case.
=> Refactor the build_item_tree

sixtyfps_runtime/rendering_backends/gl/graphics_window.rs
This pull request fix the issue [#554](https://github.com/sixtyfpsui/sixtyfps/issues/554)
=> Fix the maximization button with a fixed inner size

api/sixtyfps-cpp/CMakeLists.txt, api/sixtyfps-cpp/cmake/SixtyFPSConfig.cmake.in, api/sixtyfps-cpp/cmake/SixtyFPSMacro.cmake, tools/compiler/main.rs
=> cmake: have the style as a cmake cache variable

sixtyfps_runtime/rendering_backends/qt/lib.rs, sixtyfps_runtime/rendering_backends/qt/qt_widgets.rs, sixtyfps_runtime/rendering_backends/qt/qt_window.rs
Otherwise Qt won't set the hidpi mode on windows, for example
=> Qt backend: don't set Qt::AA_PluginApplication when using the backend

.github/workflows/ci.yaml, api/sixtyfps-cpp/CMakeLists.txt, scripts/prepare_binary_package.sh
Note that this also change the path names to "licenses" in the viewer package
=> Put the licenses in the C++ binary package

sixtyfps_runtime/corelib/Cargo.toml, sixtyfps_runtime/corelib/model.rs, sixtyfps_runtime/corelib/properties.rs, sixtyfps_runtime/interpreter/value_model.rs
=> Refactor Repeater model tracking

helper_crates/vtable/CHANGELOG.md, helper_crates/vtable/Cargo.toml, helper_crates/vtable/src/vrc.rs
Port away from owning_ref, which doesn't support no_std, use a raw pointer instead.
=> Add support for no_std to VRcMapped and VWeakMapped and use atomic-polyfill

sixtyfps_runtime/corelib/Cargo.toml, sixtyfps_runtime/corelib/graphics/brush.rs, sixtyfps_runtime/corelib/graphics/color.rs, sixtyfps_runtime/corelib/items/text.rs, sixtyfps_runtime/corelib/model.rs
Use num_traits and libm instead.
=> Make floating point operations compile with no_std

api/sixtyfps-rs/Cargo.toml, api/sixtyfps-rs/lib.rs, sixtyfps_compiler/generator/rust.rs
There are still a couple of issues, like `register_font_from_memory`
=> Start making the generated code work with no_std

api/sixtyfps-cpp/tests/datastructures.cpp, sixtyfps_runtime/corelib/Cargo.toml, sixtyfps_runtime/corelib/sharedvector.rs, sixtyfps_runtime/corelib/string.rs
Get rid of the triomphe dependency
=> Use SharedVector internally in SharedString

sixtyfps_runtime/rendering_backends/gl/event_loop.rs, sixtyfps_runtime/rendering_backends/gl/glwindow.rs
SIXTYFPS_SCALE_FACTOR override the scale factor at runtime
=> GL backend: allow to override scale factor with an env variable

sixtyfps_compiler/passes.rs, sixtyfps_compiler/tests/syntax/analysis/binding_loop_self.60
=> Fix panic when compiling a property that references itself

sixtyfps_runtime/corelib/graphics.rs, sixtyfps_runtime/corelib/graphics/fps_counter.rs, sixtyfps_runtime/corelib/item_rendering.rs, sixtyfps_runtime/rendering_backends/gl/glwindow.rs, sixtyfps_runtime/rendering_backends/gl/lib.rs, sixtyfps_runtime/rendering_backends/mcu/renderer.rs, sixtyfps_runtime/rendering_backends/qt/qt_window.rs
It can be activated using `SIXTYFPS_DEBUG_PERFORMANCE=1`
=> Add a simple frames per second counter to the GL and Qt backend

api/sixtyfps-rs/lib.rs
* Improve headings and linkage
* Replace "you can use XXX to YYY" with "Use XXX to YYY"
* In the limitation about exported components, link to the tracking
issue.
=> Some polish to the Rust crate docs

sixtyfps_compiler/generator.rs, tests/cases/crashes/subsubcomponent.60, tests/cases/crashes/subsubcomponent2.60
=> Fix wrong count of sub components in the item tree

sixtyfps_runtime/rendering_backends/gl/glwindow.rs
Make sure to make the GL context is current before destroying the femtovg canvas.
The drop implementation of the canvas will call functions to delete GL resources such as textures, FBOs, etc.
and for that to work reliably the context must be current.
=> Improve robustness of unmapping windows with the GL backend

api/sixtyfps-rs/sixtyfps-build/lib.rs, api/sixtyfps-rs/sixtyfps-macros/lib.rs, sixtyfps_compiler/generator.rs, sixtyfps_compiler/generator/rust.rs
Return an empty token stream in case the document was empty.
=> Fix CI and simplify Rust generator API

sixtyfps_compiler/generator/rust.rs
Re-apply commit f7248a486349204f52c9a8fb78ff6e48a19c3a5e to the updated code generator.
This fixes running the gallery on Windows in debug builds with the fluent style.
=> Fix stack usage on Windows with Rust debug builds

sixtyfps_runtime/rendering_backends/qt/qt_window.rs
This helps to diagnose when an image format plugin is missing in Qt.
=> qt backend: provide a warning message when we fail to load an image

sixtyfps_compiler/namedreference.rs, sixtyfps_compiler/passes/binding_analysis.rs, sixtyfps_compiler/tests/syntax/analysis/binding_loop_layout.60, sixtyfps_compiler/tests/syntax/analysis/binding_loop_layout2.60, tests/cases/layout/text_no_wrap.60
This should fix the failure in chiptrack
=> Only consider that the height of a Text depends of its width of `wrap` is set.

api/sixtyfps-cpp/include/sixtyfps_pathdata.h, docs/builtin_elements.md, sixtyfps_compiler/expression_tree.rs, sixtyfps_compiler/generator/rust.rs, sixtyfps_compiler/llr/lower_expression.rs, sixtyfps_compiler/passes/compile_paths.rs, sixtyfps_compiler/tests/syntax/basic/svg_path.60, sixtyfps_runtime/corelib/Cargo.toml, sixtyfps_runtime/corelib/graphics/path.rs, sixtyfps_runtime/interpreter/eval.rs, tests/cases/examples/hello.60
This was requested a few days ago in the chat and might also present an alternative for #754
=> Make it possible to use a string binding for Path commands

CHANGELOG.md, api/sixtyfps-rs/docs.rs, api/sixtyfps-rs/lib.rs, api/sixtyfps-rs/migration.md, sixtyfps_runtime/interpreter/lib.rs, sixtyfps_runtime/interpreter/migration.rs
=> Some changes to the migration docs

api/sixtyfps-cpp/include/sixtyfps.h, sixtyfps_compiler/generator/cpp.rs, tests/cases/models/array.60
The C++ code did not compile because it couldn't deduce the template parameter
properly. Since the lambda became a bit big to be placed in one small string,
I moved it into a real function in the header
Example of error:   (sorry for the long lines :-))
```
tmp/.tmpE42a4c.cpp: In member function 'void TestCase::init(const TestCase*, sixtyfps::cbindgen_private::ComponentWeak, uintptr_t, uintptr_t)':
/tmp/.tmpE42a4c.cpp:67:238: error: no match for call to '(TestCase::init(const TestCase*, sixtyfps::cbindgen_private::ComponentWeak, uintptr_t, uintptr_t)::<lambda(const std::shared_ptr<sixtyfps::Model<ModelData> >&, const auto:24&)>) (std::shared_ptr<sixtyfps::private_api::ArrayModel<2, sixtyfps::SharedString> >, int)'
67 |     self->root_window_1_hello_world.set([&]<typename D>(const …
```
=> Test (and fix) using [] on a temporary array

api/sixtyfps-rs/lib.rs
Fixes a typo, improves readability.
=> Docs: Fix typo

.reuse/dep5, LICENSES/LGPL-3.0-only.txt, LICENSES/OFL-1.1.txt, examples/printerdemo/ui/images/README.txt, examples/printerdemo_old/ui/images/README.txt
This is _almost_ complete: There are still some icons and one image uncovered as of now.
=> Add files to make individual crates reuse compliant

internal/compiler/object_tree.rs, internal/compiler/passes.rs, internal/compiler/passes/move_declarations.rs, internal/compiler/passes/optimize_useless_rectangles.rs, internal/compiler/passes/transform_and_opacity.rs, tests/cases/layout/opacity_in_layout.60
Fixes #915
See commit messages for details
=> Fix sizing of image with opacity in for with layout

CHANGELOG.md, api/cpp/CMakeLists.txt, api/cpp/Cargo.toml, api/cpp/docs/cmake.md, api/cpp/docs/cpp_migration.md, api/rs/slint/Cargo.toml, api/rs/slint/migration.md, internal/backends/selector/Cargo.toml, internal/interpreter/Cargo.toml, internal/interpreter/migration.rs, tools/lsp/Cargo.toml, tools/viewer/Cargo.toml
* Enable wayland by default; rename `backend-gl` to `backend-gl-all`
* Rename `x11` and `wayland` to `backend-gl-x11`/`backend-gl-wayland`
=> Rework GL backend features

internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/llr.rs, internal/compiler/llr/expression.rs, internal/compiler/llr/item_tree.rs, internal/compiler/llr/lower_to_item_tree.rs, internal/compiler/llr/optim_passes/inline_simple_expressions.rs, internal/compiler/llr/pretty_print.rs, internal/compiler/passes/check_public_api.rs
(see individual commits for more info)
=> Inline the property access on the LLR

internal/compiler/generator.rs, internal/compiler/generator/rust.rs, internal/core/animations.rs, internal/core/model.rs, internal/core/properties.rs, internal/core/window.rs
The second commit is actually an optimization in which we miss to mark as const a few properties.
=> Add debug_name to more properties

internal/backends/mcu/lib.rs, internal/backends/mcu/pico_st7789.rs, internal/backends/mcu/profiler.rs, internal/backends/mcu/renderer.rs, internal/backends/mcu/terminal.rs
Profile different stages behind a debug_performance cfg and feed the result into debug_log!
=> profile mcu renderer

internal/backends/qt/qt_widgets/button.rs, internal/backends/qt/qt_widgets/checkbox.rs, internal/backends/qt/qt_widgets/combobox.rs, internal/backends/qt/qt_widgets/groupbox.rs, internal/backends/qt/qt_widgets/lineedit.rs, internal/backends/qt/qt_widgets/listviewitem.rs, internal/backends/qt/qt_widgets/scrollview.rs, internal/backends/qt/qt_widgets/slider.rs, internal/backends/qt/qt_widgets/spinbox.rs, internal/backends/qt/qt_widgets/tabwidget.rs, internal/core/input.rs, internal/core/items.rs, internal/core/items/image.rs, internal/core/items/path.rs, internal/core/items/text.rs
... and have all widgets Accept/Ignore focus_events.
=> Introduce a FocusEventResult enum

CHANGELOG.md, internal/backends/gl/event_loop.rs, internal/backends/qt/qt_window.rs
=> Send a MouseExit event when the mouse leaves the window

CHANGELOG.md, docs/widgets.md, internal/backends/gl/glwindow.rs, internal/backends/gl/lib.rs, internal/backends/qt/qt_window.rs, internal/compiler/widgets/common/common.slint, internal/compiler/widgets/fluent/std-widgets.slint, internal/compiler/widgets/native/std-widgets.slint, internal/compiler/widgets/ugly/std-widgets.slint
Do the task from https://github.com/slint-ui/slint/pull/997#issuecomment-1057006097
(Completes #882)
=> Polishing of the password input

internal/core/item_rendering.rs, internal/core/model.rs, internal/core/properties.rs
... by not registering dependency when computing dirty regions
=> Save a bunch of property dependency

.github/workflows/ci.yaml, Cargo.toml, examples/printerdemo_mcu/Cargo.toml, examples/printerdemo_mcu/build.rs, examples/printerdemo_mcu/main.rs, examples/printerdemo_mcu/ui/README, examples/printerdemo_mcu/ui/common.slint, examples/printerdemo_mcu/ui/copy_page.slint, examples/printerdemo_mcu/ui/fonts, examples/printerdemo_mcu/ui/home_page.slint, examples/printerdemo_mcu/ui/images, examples/printerdemo_mcu/ui/ink_page.slint, examples/printerdemo_mcu/ui/print_page.slint, examples/printerdemo_mcu/ui/printer_queue.slint, examples/printerdemo_mcu/ui/printerdemo.slint, examples/printerdemo_mcu/ui/scan_page.slint, examples/printerdemo_mcu/ui/settings_page.slint, examples/printerdemo_mcu/ui/usb_page.slint
This is basically the already modified printer demo from the wip/mcu
branch but separate.
=> Fork the printer demo for adjusting to the MCU

internal/backends/mcu/renderer.rs, internal/backends/mcu/renderer/draw_functions.rs
I think it makes sense to move that code in a different file.
=> MCU renderer: refactor the drawing code in its own module

internal/compiler/object_tree.rs, internal/compiler/tests/syntax/basic/item_as_property.slint
=> Properly error out when element type are used within composite types

docs/tutorial/rust/src/getting_started.md, docs/tutorial/rust/src/main_tiles_from_rust.rs
contains some fixes and improvements for the rust tutorial.
=> Rust Tutorial improvements for 0.2.1

.github/workflows/ci.yaml, examples/printerdemo_mcu/Cargo.toml, examples/printerdemo_mcu/README.md, examples/printerdemo_mcu/main.rs, internal/backends/mcu/Cargo.toml, internal/backends/mcu/README.md, internal/backends/mcu/lib.rs, internal/backends/mcu/pico_st7789.rs, internal/backends/mcu/simulator.rs, internal/core-macros/lib.rs
- Attempt to unify a bit the features so we have less #[cfg] in the demo
- Add a README
- Test in the CI
=> MCU cleanup

internal/backends/mcu/renderer.rs
Do all the things in-place so we do not need to allocate
The "line preocessing" is down from 22ms per frame to 7ms
=> MCU renderer: optimize the line processing step

internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/core/component.rs, internal/interpreter/dynamic_component.rs
... and use it internally, mostly to be sure the data is actually passed around correctly.
=> Add `get_item_tree` function to Component VTable

internal/core/item_rendering.rs
Instead of using the generic visitor, call `visit_children_item` directly on the Component.
This way we avoid the RefCell for the renderer and this will make it
easier to introduce items that decide to render the children themselves, with
their own property tracker.
=> Simplify item rendering loop

internal/backends/mcu/lengths.rs, internal/backends/mcu/renderer.rs, internal/backends/mcu/renderer/draw_functions.rs
- Fix border radius bigger than the item
- fix artifact when drawing clipped border rectangle
- implement image-fit
Also Implement the length traits with generics
=> MCU renderer fixes

internal/core/model.rs
Closes #1045.
~~Incomplete; hasn't been fully tested. I'm working on testing with my project to see if it can at least remove the entire list successfully.~~
Edit: Has been tested; seems to work without crashing.
=> Add `VecModel::replace` and `VecModel::replace_cloned`

api/cpp/cbindgen.rs, api/cpp/include/slint.h, examples/todo/cpp/main.cpp, examples/todo/ui/todo.slint, internal/compiler/layout.rs, internal/core/api.rs, internal/core/window.rs
Also adjust the Todo example to be a bit prettier
=> implements on_close_requested  in C++

docs/tutorial/cpp/src/conclusion.md, docs/tutorial/rust/src/conclusion.md
Based on the reddit feedback, add links to the API docs and restructure
the list a little.
=> Re-organize the last page of the tutorial

internal/backends/gl/glwindow.rs, internal/backends/mcu/lib.rs, internal/backends/mcu/simulator.rs, internal/backends/qt/qt_window.rs, internal/backends/testing/lib.rs, internal/core/items/text.rs, internal/core/window.rs
this is the same as #1104 but cleaned up.
=> text_input_cursor_rect_for_byte_offset

internal/compiler/expression_tree.rs, tests/cases/types/array.slint
=> Fix conversion of struct with array of literals

.github/workflows/ci.yaml, .github/workflows/cpp_package.yaml, .github/workflows/slint_tool_binary.yaml
https://github.com/jurplel/install-qt-action/issues/142
=> CI: prospective fix for the current faillure

internal/core/items.rs
Reuse step_into_node over redoing almost the same code again.
=> Make tree-walking code DRY-er

.reuse/dep5, editor/README.md, editor/tree-sitter-slint/binding.gyp, editor/tree-sitter-slint/grammar.js, editor/tree-sitter-slint/queries/highlights.scm, editor/tree-sitter-slint/queries/indents.scm, xtask/src/license_headers_check.rs
This integrates the customizable parts of the Tree Sitter parser for Slint into the main Slint repo
=> Integrate Slint Tree Sitter code

internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs
=> Fix parent index of repeated compoonents

internal/backends/gl/lib.rs
When blitting a rectangular texture, we can disable the anti-aliasing on the edges
that femtovg applies by default. That avoids an extra triangle strip for
this stroke to apply anti-aliasing.
=> GL backend: avoid stroke when blitting textures

api/cpp/docs/index.rst, docs/langref.md, docs/resources/slint-docs-highlight.html, docs/resources/slint-docs-preview.html, tests/doctests/build.rs
TODO:
- ~~[ ] Fix crash with the previews that makes them unusable~~ (postponed)
=> doc preview and highlighting fixes

api/cpp/docs/index.rst, api/rs/slint/docs.rs, api/rs/slint/lib.rs, docs/recipes/button_native.slint, docs/recipes/recipes.md, docs/resources/slint-docs-preview.html
This is the beginning of a page to collect common things users need to
do, in a format that they can copy & paste into their application code.
There's a lot more that could be done though.
=> Start a page with examples and recipes

internal/backends/gl/glwindow.rs, internal/backends/qt/qt_window.rs
Instead of 0.
(But passing a negative y coordinate should return 0)
=> text_input_byte_offset_for_position: clicking past the end should return the last position

internal/backends/gl/fonts.rs
IDWriteFontFallback::MapCharacters only returns one single font that tries to cover
as much of the input string as possible. We need to continue processing the remaining parts of the text,
in order to get a complete list for all fonts we need.
Fixes #1139
=> Fix font fallback determination on Windows with the GL backend

internal/backends/qt/qt_widgets/button.rs, internal/backends/qt/qt_widgets/checkbox.rs
This adds focus handling to Qt's native Button and Checkbox.
Unlike the fluent version: This does not break API!
=> Qt widget focus

internal/backends/mcu/lib.rs, internal/backends/mcu/simulator.rs
Implement popups as inline components. The dirty region handling however
is still missing when closing a popup.
=> mcu: Implement popup window

tests/driver/cpp/cppdriver.rs
Don't rely on `cargo test`  setting the library search path environment for the dynamic linker.
As per https://doc.rust-lang.org/cargo/reference/environment-variables.html#dynamic-library-paths
PATH/LD_LIBRARY_PATH/etc. are set to include `target/debug` and "deps",
but this is documented to be a legacy feature.
=> Ensure the C++ test binaries find the right libslint_cpp

internal/backends/qt/lib.rs, internal/backends/qt/qt_widgets/tabwidget.rs, internal/compiler/builtins.slint, internal/compiler/llr/expression.rs, internal/compiler/passes/lower_tabwidget.rs, internal/compiler/widgets/fluent/std-widgets.slint, internal/compiler/widgets/native/std-widgets.slint
Implement Tab focus for TabBar in fluent style and make all the other styles aware of the changes involved.
=> Widget focus tab

CHANGELOG.md, api/cpp/include/slint.h, internal/compiler/generator/rust.rs, internal/core/model.rs, internal/core/properties.rs
=> Add a Model::row_data_tracked function

docs/recipes/recipes.md
cc: https://github.com/slint-ui/slint/pull/1090#issuecomment-1102849683
=> Recipes: Slider and Tabs

internal/core/item_tree.rs
This lead to e.g. forward tab focus not working in image-sieve once some images are loaded.
=> Fix forward focus tree traversal bug

internal/core/model.rs, tests/cases/models/write_to_model.slint
Because their index property needs to be updated
=> Model: When items are inserted, sets the components after that as dirty

internal/compiler/llr/optim_passes/inline_expressions.rs, internal/core/textlayout.rs
I ran clippy over the codebase in preparation for a release and fixed the one error and the warnings where the suggested change was claimed to be clean er and faster.
I left the rest alone for now:-)
=> Clippy 0 2 3

CHANGELOG.md, api/rs/slint/lib.rs, internal/compiler/generator/rust.rs, internal/core/model.rs
The tests pass but I'm not sure if it is accessible from the api.
=> Move row_data_tracked to ModelExt trait

CHANGELOG.md, internal/compiler/passes/resolving.rs, tests/cases/types/brush.slint
=> Fix conversion from brush to color in the ternary operator

internal/compiler/llr/optim_passes/count_property_use.rs, internal/compiler/passes/binding_analysis.rs, internal/compiler/widgets/native/std-widgets.slint, tests/cases/accessibility/materialized.slint
=> Accessibility: fix wrong optimization of properties, and make anotate some native widgets

examples/7guis/Cargo.toml, examples/7guis/timer.rs, examples/7guis/timer.slint
It uses Timer now instead of the animation hack.
=> improve the 7guis timer example

examples/7guis/crud.slint, examples/7guis/tempconv.slint, examples/7guis/timer.slint
It just makes things line up so that the screenshots are nicer.
=> Some alignment improvements for 7guis examples

docs/builtin_elements.md, internal/backends/qt/Cargo.toml, internal/backends/qt/qt_accessible.rs, internal/common/enums.rs, internal/compiler/widgets/fluent/std-widgets-impl.slint, internal/compiler/widgets/fluent/std-widgets.slint, internal/core/accessibility.rs
* Follow up on last PR
* Make Button and tab widget accessible in the fluent style
=> Improve accessibility support a bit

internal/compiler/widgets/fluent/std-widgets-impl.slint
=> ScrollBar background is now Palette.white

CHANGELOG.md, api/cpp/cbindgen.rs, api/cpp/include/slint_brush.h, docs/langref.md, internal/backends/gl/glrenderer.rs, internal/backends/qt/qt_window.rs, internal/compiler/expression_tree.rs, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/llr/expression.rs, internal/compiler/llr/lower_expression.rs, internal/compiler/llr/optim_passes/inline_expressions.rs, internal/compiler/llr/pretty_print.rs, internal/compiler/parser.rs, internal/compiler/parser/expressions.rs, internal/compiler/passes/resolving.rs, internal/compiler/tests/syntax/basic/radial-gradient.slint, internal/core/graphics/brush.rs, internal/interpreter/eval.rs, tests/cases/types/brush.slint, tools/lsp/semantic_tokens.rs
Only the circle is implemented so far.
Part of #263
=> Implements `@radial-gradient(circle, ...)`

examples/7guis/README.md, examples/README.md
I guess you want to move the images to the server. Those are just here for the Draft.
=> Add 7guis Readme

api/rs/build/lib.rs, docs/tutorial/rust/src/main_tiles_from_rust.rs, internal/backends/gl/glrenderer.rs, internal/backends/gl/glwindow.rs, internal/backends/gl/stylemetrics.rs, internal/backends/qt/build.rs, internal/backends/qt/qt_widgets/stylemetrics.rs, internal/backends/qt/qt_window.rs, internal/compiler/generator/cpp.rs, internal/compiler/llr/optim_passes/count_property_use.rs, internal/compiler/llr/optim_passes/inline_expressions.rs, internal/compiler/llr/pretty_print.rs, internal/compiler/object_tree.rs, internal/compiler/passes/collect_globals.rs, internal/core/input.rs, internal/core/item_rendering.rs, internal/core/item_tree.rs, internal/core/model/adapters.rs, internal/core/window.rs, internal/interpreter/api.rs, tests/driver/interpreter/interpreter.rs, tools/fmt/main.rs, tools/syntax_updater/from_0_1_0.rs
Fixes to clippy warnings, nothing controversial.
=> Clippy fixes

api/rs/slint/Cargo.toml, api/rs/slint/lib.rs, internal/compiler/generator/rust.rs
=> Add support for the `log` crate

internal/compiler/passes/deduplicate_property_read.rs, tests/cases/crashes/issue1271_set_in_if.slint
=> deduplicate_property_read: bail out if there is a write

editor/vscode/src/browser.ts
Start working on a preview for the web extension in a tab
Todo:
https://user-images.githubusercontent.com/959326/172907457-8bc440e5-5498-460e-9080-f4ec8fce1583.mp4
=> vscode web extension: Preview WIP

internal/backends/mcu/stm32h735g.rs
This requires us to flash the cache before swapping the frame buffer pointer.
With slide puzzle span drawing with image tiles goes from ~100ms down to ~50ms,
and theme switching between simple and berlin from ~140ms to ~72ms.
This is with the line renderer.
=> Enable the data cache for stm32h7

Cargo.toml, internal/backends/mcu/Cargo.toml, internal/backends/mcu/lib.rs, internal/backends/mcu/pico_st7789.rs, internal/backends/mcu/simulator.rs, internal/backends/mcu/stm32h735g.rs, internal/core/swrenderer.rs
This makes the screen refreshing must faster.
I'm not sure what to do about this PR since it needs a specific fork of the rp2040 crate. (a rebase of https://github.com/rp-rs/rp-hal/pull/209)
=> rp2040 backend: use DMA to send pixels to the screen via SPI

examples/printerdemo_mcu/ui/common.slint
The checkmark looks poor, replace it with a simple rectangle:-)
This is what that looks like:
=> printerdemo_mcu: Preffify checkboxes

api/cpp/include/slint.h, api/rs/slint/lib.rs, internal/backends/gl/glwindow.rs, internal/backends/mcu/lib.rs, internal/backends/mcu/simulator.rs, internal/backends/qt/qt_accessible.rs, internal/backends/qt/qt_window.rs, internal/backends/testing/lib.rs, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/core/component.rs, internal/core/item_rendering.rs, internal/core/lib.rs, internal/core/window.rs, internal/interpreter/dynamic_component.rs
This makes accessibility useful:-)
=> Dynamic a11y: Update the tree of objects exposed to accessibility backend

CHANGELOG.md, api/rs/slint/lib.rs, docs/langref.md, internal/compiler/builtin_macros.rs, internal/compiler/expression_tree.rs, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/llr/optim_passes/inline_expressions.rs, internal/compiler/lookup.rs, internal/core/properties.rs, internal/interpreter/eval.rs, tests/cases/expr/animation_tick.slint, tests/cases/expr/mod.slint
Low level primitive allowing to build always running animations
=> Add `animation-tick()` builtin function

internal/core/model.rs, tests/cases/elements/listview_click_open.slint
The test test one particular case where we want to expand an item to
the size of the listview when clicking
=> Fixt listview jumping when scrolling and element have different size

internal/backends/gl/glwindow.rs, internal/backends/mcu/lib.rs, internal/backends/mcu/simulator.rs, internal/backends/qt/qt_window.rs, internal/backends/testing/lib.rs, internal/core/window.rs
When the popup is implemented as an overlay on the window, no need
for the backend to do anything
=> Simplify PopupWindow handling

tools/online_editor/index.ts
- Use a HorizontalBox instead of manual layout
- Don't import random widgets
- remove comments about 'px' that ends up in all reproduced testcase :-)
=> Online editor: change the default snippet

internal/backends/gl/glwindow.rs, internal/backends/gl/lib.rs, internal/backends/gl/renderer/femtovg.rs, internal/backends/gl/renderer/femtovg/itemrenderer.rs
This separates the FemtoVG renderer more from winit related code.
=> More winit cleanups

api/cpp/include/slint.h, api/cpp/lib.rs, api/rs/slint/lib.rs, internal/backends/gl/lib.rs, internal/backends/gl/renderer/femtovg.rs, internal/backends/mcu/lib.rs, internal/backends/mcu/simulator.rs, internal/backends/qt/lib.rs, internal/backends/qt/qt_window.rs, internal/backends/testing/lib.rs, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/core/backend.rs, internal/core/renderer.rs, internal/core/swrenderer.rs, internal/interpreter/eval.rs, internal/interpreter/lib.rs
=> Move the fonts out of the Backend trait

internal/core/swrenderer.rs
If we want to use the software renderer as a drop in replacement
for the GL renderer, we need to be able to render all images
without the compiler having to pre-render the textures
This was tested by hacking the compiler not to render the texture
with the mcu simulator
=> Sotfware renderer: Add support for ImageInner::EmbeddedImage

internal/backends/selector/lib.rs, internal/backends/winit/glwindow.rs, internal/backends/winit/lib.rs, internal/backends/winit/renderer/femtovg.rs
Make GLWindow generic over the renderer and canvas
=> Make it possible to have multiple renderers in the winit crate

.github/workflows/ci.yaml
=> Prospective fix for disk space issues in the CI on Windows

api/cpp/CMakeLists.txt
This requires a creative workaround :-)
=> Fix Skia cross-build when using CMake

internal/backends/winit/glwindow.rs, internal/backends/winit/lib.rs, internal/backends/winit/renderer/femtovg.rs, internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/skia/opengl_surface.rs
Clean up the shutdown logic and the OpenGL setup with Skia.
=> winit: more cleanups

internal/backends/winit/Cargo.toml, internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/skia/metal_surface.rs, internal/backends/winit/renderer/skia/opengl_surface.rs
=> Add support for rendering with Skia and Metal on macOS

internal/backends/winit/Cargo.toml, internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/skia/d3d_surface.rs, internal/backends/winit/renderer/skia/metal_surface.rs, internal/backends/winit/renderer/skia/opengl_surface.rs
=> Add support for rendering with Skia and Direct3D on Windows

.github/workflows/build_docs.yaml
... in hope for a newer clang-format (> v11)
=> Upgrade the docs build to Ubuntu 22.04

internal/backends/mcu/pico_st7789.rs
Backend will end up in the public API, and having a port to the current trait helps to see what the public API looks like.
Note that what is lost in this port is the perf counter. It would be nice to find a way to have the perf counter in core, somehow.
=> MCU: port the PICO code to use the Backend trait directly

internal/core/input.rs
alternative to 49ea24c44a6ff2b00f007c5165d479bc3a28ddca
=> seperate text deletion code with move_mod

internal/backends/mcu/lib.rs, internal/backends/mcu/pico_st7789.rs, internal/backends/qt/qt_window.rs, internal/backends/winit/Cargo.toml, internal/backends/winit/event_loop.rs, internal/core/api.rs, internal/core/backend.rs, internal/core/timers.rs
=> Backend API: timer  functions

api/rs/slint/Cargo.toml, internal/backends/selector/Cargo.toml, internal/backends/selector/lib.rs, internal/backends/winit/Cargo.toml, internal/backends/winit/glwindow.rs, internal/backends/winit/lib.rs, internal/backends/winit/renderer/femtovg.rs, internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/sw.rs, internal/core/swrenderer/draw_functions.rs
Currently, you still need to pass some env variable at build time so it
embeds the font.
=> Add a feature to use the sofware renderer with the winit backend

internal/core/textlayout/linebreaker.rs
Because a single glyph wouldn't fit on a line, it would loop forever
=> swrenderer textlayout: fix panic when max_with is 0

api/rs/build/lib.rs
It would insert newline after the `}`  and break the build
=> slint-build: fix code formater in presence of `'\u{..}'`

api/cpp/lib.rs, api/rs/slint/lib.rs, internal/backends/mcu/lib.rs, internal/backends/mcu/pico_st7789.rs, internal/backends/qt/lib.rs, internal/backends/qt/qt_window.rs, internal/backends/selector/lib.rs, internal/backends/testing/lib.rs, internal/backends/winit/event_loop.rs, internal/backends/winit/lib.rs, internal/core/animations.rs, internal/core/api.rs, internal/core/graphics/image/htmlimage.rs, internal/core/items/text.rs, internal/core/lib.rs, internal/core/platform.rs, internal/interpreter/api.rs, tools/lsp/preview.rs
and the Backend trait into PlatfromAbstraction trait
=> Rename backend module to platform

tools/online_editor/index.html
Update bootstrap to stop warning about missing jquery.
=> online_editor: Update bootstrap

tools/lsp/server_loop.rs
=> LSP: display the Element tree in the Outline

internal/core/timers.rs
The change of `CallbackVariant::invoke` (from consuming to mutating) is not really necessary. I made it during my search for a working fix. Please feel free to kill it, or let me know and I'll do it and update the PR.
I have installed `pre-commit` as per the Contributing Guidelines, but the cspell hook complained about the unknown word 'singleshot', so I ended up disabling pre-commit. It was the only error detected by pre-commit, and it pertains to the part of the code I didn't touch (the C function name `slint_timer_singleshot`).
Fixes #1532
=> Fix #1532: Timer::{start,stop} in the timer's own callback

internal/backends/winit/renderer/sw.rs
The render function of the swrendrer already call that.
=> winit with swrenderer: don't call `window.draw_contents` twice.

examples/mcu-board-support/pico_st7789.rs, examples/mcu-board-support/stm32h735g.rs, internal/backends/winit/renderer/sw.rs, internal/core/swrenderer.rs
=> swrenderer: Move the DirtyTracking enum into a const generic

internal/backends/winit/Cargo.toml, internal/backends/winit/glwindow.rs, tools/online_editor/src/index.ts
I took your initial commit and added another workaround on top. That one has an elaborate commit message that I hope makes sense :)
=> Fix preview not updating in the online editor

.github/workflows/ci.yaml, helper_crates/const-field-offset/macro/Cargo.toml, internal/core/swrenderer.rs, tests/driver/rust/build.rs
We already build with that flag. I think this could in fact make the
test faster to build
=> CI: pass --all-features to cargo test

examples/mcu-board-support/pico_st7789.rs, examples/mcu-board-support/stm32h735g.rs, internal/backends/winit/renderer/sw.rs, internal/core/swrenderer.rs
=> Remove the use of euclid types from the software renderer public API

tools/lsp/server_loop.rs
Very basic tests for the LSP:-)
=> lsp: Add some basic tests

.github/workflows/build_docs.yaml, .github/workflows/ci.yaml, internal/core/input.rs, internal/core/item_rendering.rs, internal/core/platform.rs, internal/core/string.rs
And add a test in the CI that checks for warnings in the internal
crates
(Also changed --exlcude in the test to be matching the one from build,
since c++ test are tested separately)
=> Fixup some documentaion links

api/node/native/lib.rs, examples/mcu-board-support/Cargo.toml, examples/mcu-board-support/pico_st7789.rs, examples/mcu-board-support/stm32h735g.rs, internal/backends/qt/qt_widgets.rs, internal/backends/qt/qt_widgets/slider.rs, internal/backends/qt/qt_window.rs, internal/backends/testing/lib.rs, internal/backends/winit/event_loop.rs, internal/backends/winit/glwindow.rs, internal/backends/winit/renderer/femtovg.rs, internal/backends/winit/renderer/femtovg/fonts.rs, internal/backends/winit/renderer/femtovg/images.rs, internal/backends/winit/renderer/femtovg/itemrenderer.rs, internal/backends/winit/renderer/skia/itemrenderer.rs, internal/core/api.rs, internal/core/input.rs, internal/core/items/flickable.rs, internal/core/items/text.rs, internal/core/window.rs, tests/cases/elements/flickable.slint, tests/cases/elements/flickable3.slint
=> Remove the use of euclid from the Window API

examples/mcu-board-support/Cargo.toml, examples/mcu-board-support/README.md, examples/mcu-board-support/esp32_s2_kaluga_1.rs, examples/mcu-board-support/esp32_s2_kaluga_1/cargo-config.toml, examples/mcu-board-support/lib.rs
As you can see in the picture, there seems to be some problem to position images, for some reason. I have a suspicion that it is because of some bad floating point computation somewhere, with that architecture..
=> Support for the esp32-s2-kaluga-1 board

internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/skia/d3d_surface.rs, internal/backends/winit/renderer/skia/metal_surface.rs, internal/backends/winit/renderer/skia/opengl_surface.rs
Include the number of bits per pixel in the existing output
=> Add debug info about the Skia back buffer color depths

api/rs/slint/docs.rs, api/rs/slint/lib.rs, api/rs/slint/private_unstable_api.rs, internal/compiler/generator/rust.rs, tests/cases/focus/event_propagation.slint, tests/cases/text/cursor_move.slint, tests/cases/text/cursor_move_grapheme.slint, tests/cases/text/cut.slint, tests/cases/text/select_all.slint, tests/cases/text/surrogate_cursor.slint
Also move the module in its own file
=> Rename slint::internal to slint::unstable_private_api and move re_exports into it

CHANGELOG.md, internal/core/model.rs, tests/cases/crashes/layout_deleted_item.slint
=> Make VecModel::remove() return the removed value like Vec

internal/backends/winit/glwindow.rs
In previous version, we were setting the constraint with wasm after
the window was shown, but this is no longer the case because we delay
the window creation by an iteration of the event loop.
Now should apply the constraint before showing the window.
But on wasm, we also must manually enforce these constraint because the
size given to the WindowBuilder is not applied
=> winit: Enforce the min/max size in the WindowBuilder and set size again for wasm

internal/core/platform.rs
=> Provide an error enum for the error case of `slint::platform::set_platform`

internal/backends/winit/lib.rs, internal/core/swrenderer.rs
=> swrenderer: Rename BUFFER_COUNT to MAX_BUFFER_AGE

api/cpp/Cargo.toml, api/rs/slint/Cargo.toml, api/rs/slint/lib.rs, api/wasm-interpreter/Cargo.toml, docs/mcu.md, examples/mcu-board-support/Cargo.toml, examples/printerdemo_mcu/Cargo.toml, internal/core/Cargo.toml, internal/interpreter/Cargo.toml, internal/interpreter/lib.rs, tests/driver/interpreter/Cargo.toml, tests/driver/rust/Cargo.toml, tools/lsp/Cargo.toml, tools/viewer/Cargo.toml
But keep a compat-0-2-0 fome compatibility anyway
=> Rename the compat-0-2-0 feature to compat-0.3.0

api/rs/slint/lib.rs, internal/core/platform.rs, internal/core/window.rs
Here's a first run over the API docs in the platform module.
=> Platform doc fixes

internal/backends/winit/event_loop.rs, internal/backends/winit/glwindow.rs
Also simplify the code that sets the property to the builder
=> winit: Set the icon from the builder

tools/online_editor/src/welcome_widget.ts
Mark the Welcome page in the online editor as closable.
=> online_editor: Mark Welcome widget as closable

tools/online_editor/src/preview_widget.ts
Make the online editor preview default to something bigger!
=> online_editor: Make preview bigger by default

internal/backends/qt/qt_window.rs, internal/backends/testing/lib.rs, internal/backends/winit/glwindow.rs, internal/core/api.rs, internal/core/window.rs
=> Rename `RequestedSize` to `WindowSize` and `RequestedPosition` to `WindowPosition`

internal/interpreter/dynamic_component.rs
We need the pointer that's in the VRc used when registering the items in the cache.
=> interpreter: Fix unregister_component called with the wrong pointer

internal/core/input.rs, internal/core/item_tree.rs
Just make a single recursive function, it is easier to read than using the visitor helper with a post and pre visit.
Also remove that function that visits with a post and pre visit as it is no longer used
=> Refactor the mouse handling

.github/actions/setup-rust/action.yaml, .github/workflows/build_docs.yaml, .github/workflows/ci.yaml, .github/workflows/cpp_package.yaml, .github/workflows/crater.yaml, .github/workflows/embedded_build.yaml, .github/workflows/nightly_snapshot.yaml, .github/workflows/slint_tool_binary.yaml, .github/workflows/wasm_demos.yaml, .github/workflows/wasm_editor_and_interpreter.yaml
* Run shared workflows from the current branch, not from master
* Make sure OS names are lowercase as specified by github
* Create and use a custom action to set up rust for us and use that throughout the workflows
=> ci: Clean up our CI setup a bit

tools/online_editor/src/editor_widget.ts, tools/online_editor/src/preview_widget.ts
Small fixes for the online editor.
Mostly to disentangle this from the "add test PR" I want to send ASAP.
=> Online editor fixes

.github/actions/test-online-editor/action.yaml, .github/workflows/nightly_snapshot.yaml, .github/workflows/wasm_editor_and_interpreter.yaml, tools/online_editor/cypress.config.ts, tools/online_editor/cypress/e2e/smoke_test.cy.ts, tools/online_editor/cypress/plugins/index.ts, tools/online_editor/cypress/support/commands.ts, tools/online_editor/cypress/support/e2e.ts, tools/online_editor/cypress/tsconfig.json, tools/online_editor/package.json, tools/online_editor/src/tsconfig.json, tools/online_editor/src/worker/tsconfig.json, tools/online_editor/src/worker/types.ts
Add cypress-based smoke test for the online editor and fix the fallout from all the new dependencies showing up :-)
=> Online editor smoke test

internal/backends/winit/Cargo.toml, internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/skia/itemrenderer.rs, internal/backends/winit/renderer/skia/textlayout.rs
Fix rendering of the text cursor at the end of text and in empty text inputs, and implement support for text selections.
=> Skia: Improve text handling

tools/lsp/properties.rs, tools/lsp/server_loop.rs
* Better error reporting -- a necessity when trying to make something new talk to the LSP!
* More and better information on where properties are defined
=> Lsp: Improve queryProperties results

CHANGELOG.md, api/cpp/include/slint.h, api/cpp/tests/models.cpp
This matches the MapModel in the Rust API.
=> Add a C++ Map Model class

tools/lsp/properties.rs
When querying properties we walk down the tree of types from the current elements type down through the base types.
We can see the same element several times that way as it may get assigned values on the way down to the definition. So de-duplicate properties in the result and return only the deepest as that is where the property got defined.
=> lsp: Deduplicate result of `queryProperties`

tools/online_editor/src/editor_widget.ts, tools/online_editor/src/index.ts, tools/online_editor/src/worker/lsp_worker.ts
This was lost when moving the code out of index.ts into editor_widget.ts.
=> online_editor: Add back suppoort for LSP asking for file contents

internal/backends/qt/qt_window.rs, internal/backends/testing/lib.rs, internal/backends/winit/renderer/femtovg.rs, internal/backends/winit/renderer/femtovg/fonts.rs, internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/skia/itemrenderer.rs, internal/backends/winit/renderer/skia/textlayout.rs, internal/core/graphics.rs, internal/core/items/text.rs, internal/core/renderer.rs, internal/core/software_renderer.rs, internal/core/software_renderer/fonts.rs
It doesn't have to be generic as mostly the frontend code creates it with logical lengths.
=> Simplify FontRequest

internal/backends/qt/qt_window.rs, internal/backends/winit/renderer/femtovg/itemrenderer.rs, internal/backends/winit/renderer/skia/itemrenderer.rs, internal/core/item_rendering.rs, internal/core/items.rs, internal/core/lengths.rs, internal/core/software_renderer.rs
This simplifes call sites and implementations.
=> Use a vector for ItemRenderer::translate

internal/backends/qt/qt_accessible.rs, internal/backends/qt/qt_widgets/button.rs, internal/backends/qt/qt_widgets/checkbox.rs, internal/backends/qt/qt_widgets/combobox.rs, internal/backends/qt/qt_widgets/groupbox.rs, internal/backends/qt/qt_widgets/lineedit.rs, internal/backends/qt/qt_widgets/listviewitem.rs, internal/backends/qt/qt_widgets/scrollview.rs, internal/backends/qt/qt_widgets/slider.rs, internal/backends/qt/qt_widgets/spinbox.rs, internal/backends/qt/qt_widgets/tabwidget.rs, internal/backends/qt/qt_window.rs, internal/backends/winit/event_loop.rs, internal/backends/winit/glwindow.rs, internal/backends/winit/renderer/femtovg/itemrenderer.rs, internal/backends/winit/renderer/skia/itemrenderer.rs, internal/backends/winit/renderer/skia/textlayout.rs, internal/backends/winit/wasm_input_helper.rs, internal/compiler/builtins.slint, internal/compiler/widgets/common/common.slint, internal/core/input.rs, internal/core/item_tree.rs, internal/core/items.rs, internal/core/items/flickable.rs, internal/core/items/image.rs, internal/core/items/path.rs, internal/core/items/text.rs, internal/core/tests.rs, internal/core/window.rs
This partially addresses #1706
=> Initial Input Method Support for Winit

internal/backends/winit/wasm_input_helper.rs
Pros: the composition shows up as selected
Cons: te cursor is shown at the begining of the preselection, and clicking on the field commit the selection at the wrong place
=> wasm: Use the composition API

.github/actions/install-nodejs/action.yaml
Update NodeJS in our CI to version 16.
That should work for our code and is still in support (unlike version 12).
=> Update node version to 16

tools/online_editor/src/index.ts
Now that we have explicit dark/light variants of the fluent style, it makes sense to have a drop-down menu.
=> online editor: Add support for selecting the style

internal/backends/selector/lib.rs
`SLINT_BACKEND="winit"` wouldn't work. So make `winit` and `femtovg` be possible value for the backend string
=> Fix parsing the SLINT_BACKEND string

api/rs/slint/Cargo.toml, internal/interpreter/Cargo.toml
Should've done that for 0.3.1, but better late than never :)
=> doc: Remove the experimental tag from the Skia renderer

tools/lsp/wasm_main.rs
Use a JSON friendly representation that uses JS object instead of ES maps, as the latter appear to confuse at least the monaco lsp integration.
=> Fix serialization of LSP types into wasm

api/cpp/CMakeLists.txt, api/cpp/cmake/SlintConfig.cmake.in
Update Corrosion to v0.3-beta.
Works locally, hopefully also in your CI.
=> Update corrosion to v0.3.0

.github/workflows/wasm_demos.yaml, examples/gallery/Cargo.toml, examples/gallery/index.html
Add a selection drop down to the gallery  `index.html` and build the gallery in the ci for the different styles.
=> Add style selection to gallery

internal/core/properties.rs
This can be reproduced with this example:
```
import { TabWidget } from "std-widgets.slint";
App := Window {
preferred-width: 700px;
preferred-height: 500px;
HorizontalLayout {
side-bar := TouchArea {
property <int> current-item: 1;
clicked => { current-item =  current-item == 0 ? 1 : 0 ; }
}
if(side-bar.current-item == 0) :  TabWidget {  }
}
}
```
With the native style. (click on the window, then resize) This will result in a stack overflow, because we have a cycle in the dependency graph and they are marked dirty forever. The NativeTabWidget will create two way binding internally. And it will be crated as a result of the layout cache property because that's when the model will be evaluated and created.  This will inatvertently create a dependency between the layout cache property, and …
=> Properties: fix extra dependency when making a two way binding

internal/compiler/widgets/material-base/md.slint, internal/compiler/widgets/material-base/widget-slider.slint
Update the colors for the slider background for a better contrast.
=> Make material light slider background more visible

internal/compiler/generator/rust.rs, tests/cases/issues/issue_1837_percent_comparison.slint
=> Fix rust code generation when comparing percentages

editors/vscode/package.json, editors/vscode/src/browser-lsp-worker.ts, editors/vscode/src/browser.ts, editors/vscode/src/extension.ts, tools/lsp/main.rs, tools/lsp/preview.rs, tools/lsp/server_loop.rs, tools/lsp/wasm_main.rs, tools/online_editor/src/worker/lsp_worker.ts
=> LSP: add a setting to change the style and the include paths

examples/gallery/ui/pages/text_edit_page.slint, internal/compiler/widgets/material-base/widget-button.slint, internal/compiler/widgets/material-base/widget-scrollview.slint, internal/compiler/widgets/material-base/widget-slider.slint
* Fixed: the initial Text of md TextEdit was not displayed
=> Fixed: md TextEdit text not displayed

internal/core/software_renderer.rs
* Software renderer: Apply opacity settings on rectangle drawing and rectangle with border
=> swr: apply opacity on rect and rect with

editors/vscode/src/common.ts, editors/vscode/src/propertiesView.ts, tools/lsp/properties.rs, tools/lsp/server_loop.rs, tools/lsp/util.rs, tools/online_editor/src/lsp_integration.ts
- avoid annoying error messages all the time when edditing rust files
- fix editing of properties
=> Few fixes with vscode and properties

internal/compiler/widgets/material-base/comp-state-layer.slint, internal/compiler/widgets/material-base/md.slint, internal/compiler/widgets/material-base/widget-button.slint, internal/compiler/widgets/material-base/widget-item.slint
* Add `StateLayer` component
* Add `Ripple` component (used by StateLayer)
* use `StateLayer` in material `Button`
* use `StateLayer` in material `Item`
=> md: add ripple effect

docs/widgets.md
=> Add more docs about selecting the style with the lsp, vs code and slint viewer

docs/recipes/recipes.md
Since it seems this is a commonly requested feature, even if not possible easily builtin, we can already provide a workaround.
Maybe this shouldn't be in the recipes, but just in a comment of the issue in the issue tracker?
=> Recipes: Translation example

CHANGELOG.md
- re-order the ChangedSection by "impact"
- Add missing periods.
- For the element highlight, explain when a highlight is shown.
- Elaborate on some entries.
=> doc: Some edits to the ChangeLog

tools/lsp/server_loop.rs
=> LSP: don't querty configuration if the client don't advertize we can do it

internal/backends/winit/Cargo.toml, internal/backends/winit/glwindow.rs
Use a dedicated cell and clean up the comments.
=> Try to clean up the workaround for the window resizing bug on Windows

internal/backends/winit/glwindow.rs
We need to check the original size of the canvas before winit override it
The previous code didn't work for two reason
- It was done after winit had reset the size of the canvas to the default size
- It just calls set_inner_size on the winit Window, which is not what we want, we want to call the api::Window::set_size function so it can keep all different sizes in sync
This removes the code that tries to react to the canvas change. This hasn't been working since SixtyFPS 0.1.1
=> Fix winit not taking the original size of the canvas into account

docs/recipes/recipes.md
Add a recipe as example how to work with breakpoints and how to add a responsive SideBar.
=> add recipe for responsive sidebar

internal/renderers/skia/opengl_surface.rs
Commit 01d2efce4e4e00298d27216a540a5cef186e1295 ended up creating our OpenGLSurface type with the GL context not current, and right after that SkiaRenderer would invoke the RenderingSetup callback, which expects a current context.
Solve this by simplifying the context handling in the OpenGLSurface in the Skia renderer: The main purpose of glutin's NotCurrentContext appears to be the ability to send it across threads, which we don't need. Therefore always store a PossiblyCurrent and use the context's own interior mutability to make it current if needed.
=> Fix opengl underlay example not running with Skia OpenGL renderer

CHANGELOG.md, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/llr/optim_passes/count_property_use.rs, tests/cases/callbacks/functions.slint
This doesn't implement any support for the interpreter yet
CC: #2012
=> Implement calling public functions from native code

internal/compiler/expression_tree.rs, internal/compiler/tests/syntax/lookup/conversion.slint, tests/cases/types/array.slint
=> Fix conversions of array literal containing struct with array literal

api/cpp/include/slint_interpreter.h, api/cpp/tests/interpreter.cpp, api/node/native/lib.rs, internal/interpreter/api.rs, internal/interpreter/dynamic_component.rs, internal/interpreter/eval.rs, internal/interpreter/ffi.rs, internal/interpreter/global_component.rs
Deprecate the invoke_callback one
CC: #2012
=> interpreter: support calling function with the invoke function

Cargo.toml, internal/backends/winit/Cargo.toml, internal/backends/winit/renderer/sw.rs
* Bump soft-buffer version 0.2
* patch is no longer needed
=> bump soft-buffer to 0.2

internal/compiler/widgets/common/common.slint, internal/compiler/widgets/common/standardbutton.slint, internal/compiler/widgets/fluent-base/std-widgets-impl.slint, internal/compiler/widgets/fluent-base/std-widgets.slint, internal/compiler/widgets/fluent-dark/color-scheme.slint, internal/compiler/widgets/fluent-light/color-scheme.slint, internal/compiler/widgets/fluent/color-scheme.slint, internal/compiler/widgets/material-base/comp-state-layer.slint, internal/compiler/widgets/material-base/layouts.slint, internal/compiler/widgets/material-base/md.slint, internal/compiler/widgets/material-base/std-widgets-impl.slint, internal/compiler/widgets/material-base/widget-button.slint, internal/compiler/widgets/material-base/widget-checkbox.slint, internal/compiler/widgets/material-base/widget-combobox.slint, internal/compiler/widgets/material-base/widget-groupbox.slint, internal/compiler/widgets/material-base/widget-item.slint, internal/compiler/widgets/material-base/widget-lineedit.slint, internal/compiler/widgets/material-base/widget-listview.slint, internal/compiler/widgets/material-base/widget-scrollview.slint, internal/compiler/widgets/material-base/widget-slider.slint, internal/compiler/widgets/material-base/widget-spinbox.slint, internal/compiler/widgets/material-base/widget-tabwidget.slint, internal/compiler/widgets/material-dark/color-scheme.slint, internal/compiler/widgets/material-light/color-scheme.slint, internal/compiler/widgets/material/color-scheme.slint, internal/compiler/widgets/native/std-widgets-impl.slint, internal/compiler/widgets/native/std-widgets.slint
This is commit is just the output of running the syntax updater on the files in the internal/compiler/widgets directory.
No extra manual steps were done.
Note: In order to run the updater, I did a hack so that the updater wouldn't choke on internal item used by the styles by commenting out the check in ElementType::lookup_type_for_child_element
=> Run the syntax_updater on our widgets

internal/renderers/skia/Cargo.toml, internal/renderers/skia/itemrenderer.rs, internal/renderers/skia/textlayout.rs
This includes additional cross-compilation build fixes that will allow removing patches from the Yocto recipes.
=> janitor: bump Rust Skia bindings to the latest release

internal/renderers/skia/itemrenderer.rs, internal/renderers/skia/lib.rs
* Fix incorrect path offset being applied in logical coordinates
* Cache Skia path objects as recommended upstream
=> skia: Path rendering fixes

CHANGELOG.md, internal/compiler/generator/rust.rs, internal/compiler/passes/default_geometry.rs, internal/compiler/passes/lower_shadows.rs, tests/cases/layout/issue_783_constraint_from_children.slint
Closes #783
Technically a breaking change. But I couldn't notice any breakage in our example.
=> Layouting: forward the implicit constraint from the children to the parent

internal/backends/winit/event_loop.rs, internal/backends/winit/glwindow.rs
(at least the swrenderer part)
=> Compile the winit backend's with `RUSTFLAGS='--cfg slint_int_coord'`

tools/updater/README.md, tools/updater/main.rs
Polish the readme a little, use sentences for the argument help and add a plural to the declarations option.
=> doc: polish for the slint updater

CHANGELOG.md, docs/langref.md, docs/layouting.md, internal/compiler/passes/default_geometry.rs, tests/cases/layout/issue_783_constraint_from_children.slint
=> Only apply the constraint to the parent with the new syntax

tools/lsp/server_loop.rs
Basically same as e88b07997f9a4f228fcec245bd7694815d7ee910 but in the set_binding_command function.
(made the code more similar to remove_binding_command, I think the two function should be merged in the future)
This fix editing binding within the root component when it inherits from something.
=> LSP: Fix calculation of element position

examples/carousel/rust/index.html, examples/gallery/index.html, examples/printerdemo/rust/index.html, examples/printerdemo_old/rust/index.html, examples/slide_puzzle/index.html, examples/todo/rust/index.html, tools/online_editor/src/editor_widget.ts
that loads the demo based on the current version of the editor
=> Online code editor: add a "load_demo" url argument

CHANGELOG.md, api/cpp/cbindgen.rs, api/cpp/tests/manual/platform_qt/main.cpp, docs/builtin_enums.md, internal/backends/qt/qt_window.rs, internal/backends/winit/event_loop.rs, internal/common/enums.rs, internal/core/items.rs, tests/cases/elements/toucharea.slint, tools/updater/main.rs, tools/updater/transforms/renames.rs, xtask/src/enumdocs.rs
And mark the enum non_exhaustive
closes #1903
=> Rename PointerEventButton::None to PointerEventButton::Other

internal/backends/winit/Cargo.toml, internal/backends/winit/renderer/femtovg.rs, internal/backends/winit/renderer/femtovg/fonts.rs, internal/backends/winit/renderer/femtovg/itemrenderer.rs
Not big changes, just API and Cargo feature cleanups
=> Update to FemtoVG 4.0

tests/screenshots/testing.rs
Test what when we do a screenshot for a region of the image, it gives the right result. (Otherwise we might see flickering arounf the clipped region)
=> Screenshot test: test partial rendering

CHANGELOG.md, internal/backends/qt/qt_window.rs, internal/core/graphics/image.rs, internal/core/software_renderer.rs, internal/interpreter/ffi.rs, internal/renderers/skia/cached_image.rs, tests/screenshots/testing.rs
=> Remove slint::Image::stride()

internal/backends/qt/lib.rs, internal/backends/testing/lib.rs, internal/backends/winit/event_loop.rs, internal/backends/winit/lib.rs, internal/core/items/text.rs, internal/core/platform.rs
=> Add primary keyboard support on unix (selection copy, middle click paste)

examples/energy_mng/ui/components/state_layer.slint, examples/energy_mng/ui/main_window.slint, examples/energy_mng/ui/pages/overview.slint, examples/energy_mng/ui/pages/page.slint, examples/energy_mng/ui/pages/pages.slint, examples/energy_mng/ui/theme.slint, examples/energy_mng/ui/widgets/group_box.slint, examples/energy_mng/ui/widgets/menu.slint, examples/energy_mng/ui/widgets/navigation.slint, examples/energy_mng/ui/widgets/value_display.slint, examples/energy_mng/ui/widgets/widgets.slint
* Overview page
* ValueDisplay widget
* GroupBox widget
=> energy_mng: overview

internal/backends/winit/Cargo.toml, internal/backends/winit/renderer/femtovg/glcontext.rs, internal/renderers/skia/Cargo.toml, internal/renderers/skia/opengl_surface.rs
Explicitly instruct glutin to fall back to GLX if possible.
cc #2162
=> Prospective fix for Linux systems that don't support EGL with X11

.github/workflows/ci.yaml, examples/7guis/booker.slint, internal/compiler/tests/syntax/lookup/issue_1461.slint, internal/compiler/widgets/fluent-base/std-widgets-base.slint, internal/compiler/widgets/fluent-base/std-widgets-impl.slint, internal/compiler/widgets/fluent-base/widget-table-view.slint
Don't make our widgets inherit element that we didn't want to expose in the API
The other styles will be synchronized with later
=> Fluent style: cleanup unwanted properties

examples/energy_mng/ui/main_window.slint, examples/energy_mng/ui/pages/pages.slint, examples/energy_mng/ui/pages/usage.slint, examples/energy_mng/ui/theme.slint, examples/energy_mng/ui/widgets/bar_chart.slint, examples/energy_mng/ui/widgets/value_display.slint, examples/energy_mng/ui/widgets/widgets.slint
* Usage page
* BarChart widget
=> energy_mng demo: usage

internal/core/input.rs, internal/core/items/text.rs, internal/core/window.rs, tests/cases/text/select_double_click.slint
=> TextInput: implement double-click and drag

CHANGELOG.md, api/cpp/include/slint.h, api/cpp/include/slint_interpreter.h, api/cpp/include/slint_testing.h, api/cpp/tests/models.cpp, examples/printerdemo/cpp/main.cpp, examples/printerdemo/cpp_interpreted/main.cpp, examples/printerdemo_old/cpp/main.cpp, internal/compiler/generator/cpp.rs
=> C++: use size_t everywhere as index in our models

internal/backends/winit/renderer/femtovg/glcontext.rs, internal/renderers/skia/opengl_surface.rs
Avoid unwrap in the display/context selection try function.
=> Prospective fix for preview panicing on Linux v2

internal/compiler/lookup.rs, internal/compiler/passes/resolving.rs, internal/compiler/tests/syntax/lookup/two_way_binding_model.slint
=> Improve error message when trying to create a two-way binding to model data

.github/workflows/ci.yaml, examples/printerdemo_old/ui/fax_page.slint, internal/backends/qt/qt_widgets/combobox.rs, internal/compiler/builtins.slint, internal/compiler/tests/consistent_styles.rs, internal/compiler/widgets/common/standardbutton.slint, internal/compiler/widgets/fluent-base/std-widgets-impl.slint, internal/compiler/widgets/material-base/std-widgets-impl.slint, internal/compiler/widgets/material-base/widget-button.slint, internal/compiler/widgets/material-base/widget-checkbox.slint, internal/compiler/widgets/material-base/widget-combobox.slint, internal/compiler/widgets/material-base/widget-groupbox.slint, internal/compiler/widgets/material-base/widget-lineedit.slint, internal/compiler/widgets/material-base/widget-scrollview.slint, internal/compiler/widgets/material-base/widget-slider.slint, internal/compiler/widgets/material-base/widget-spinbox.slint, internal/compiler/widgets/material-base/widget-table-view.slint, internal/compiler/widgets/material-base/widget-tabwidget.slint, internal/compiler/widgets/native/std-widgets-impl.slint, internal/compiler/widgets/native/std-widgets.slint
=> Harmonize styles & Add a test that styles are in sync

examples/energy_mng/ui/main_window.slint, examples/energy_mng/ui/pages/balance.slint, examples/energy_mng/ui/pages/overview.slint, examples/energy_mng/ui/pages/page.slint, examples/energy_mng/ui/pages/pages.slint, examples/energy_mng/ui/pages/usage.slint, examples/energy_mng/ui/pages/weather.slint, examples/energy_mng/ui/theme.slint, examples/energy_mng/ui/widgets/balance_chart.slint, examples/energy_mng/ui/widgets/bar_chart.slint, examples/energy_mng/ui/widgets/chart_axis.slint, examples/energy_mng/ui/widgets/chart_pattern.slint, examples/energy_mng/ui/widgets/group_box.slint, examples/energy_mng/ui/widgets/navigation.slint, examples/energy_mng/ui/widgets/widgets.slint
* Balance Chart
* Balance page
=> balance chart, balance page

CHANGELOG.md, api/cpp/Cargo.toml, api/rs/slint/Cargo.toml, api/rs/slint/lib.rs, api/rs/slint/mcu.md, api/wasm-interpreter/Cargo.toml, examples/carousel/rust/Cargo.toml, examples/energy_mng/Cargo.toml, examples/mcu-board-support/Cargo.toml, examples/printerdemo_mcu/Cargo.toml, internal/core/Cargo.toml, internal/interpreter/Cargo.toml, internal/interpreter/lib.rs, tests/driver/interpreter/Cargo.toml, tests/driver/rust/Cargo.toml, tests/screenshots/Cargo.toml, tools/lsp/Cargo.toml, tools/viewer/Cargo.toml
And remove the compat-0-2-0 and compat-0-3-0 features
=> Change the name of the compat feature

internal/core/items/flickable.rs, tests/cases/elements/flickable.slint
=> Flickable: Shift + mouse scroll invert scroll direction

CHANGELOG.md, docs/langref/src/widgets.md, internal/compiler/widgets/fluent-base/std-widgets-base.slint, internal/compiler/widgets/material-base/widget-listview.slint, internal/compiler/widgets/native/std-widgets.slint
* Bring selected item on `StandardListView` into view by arrow keys and click
* works for native, material and fluent
Fixes #2209
=> std-list-view: bring selected into view

internal/backends/winit/event_loop.rs
Use a truly silent no-op clipboard context.
=> Silence debug output on macOS and Windows when selecting text

internal/backends/winit/glwindow.rs
=> Fix panic when minimizing window on Windows with winit

api/cpp/CMakeLists.txt
=> Bump corrosion

internal/compiler/generator/cpp.rs
This requires adding more friends to the component root
Fixes: #2169
=> C++: Don't make the `global_*` member public

tests/screenshots/testing.rs
I get a warning building this file with nightly and we deny wanrings in it, so the build stops.
Fix the warning, and fix a typo while at it.
=> Fix compile fail with nightly

examples/energy-monitor/build.rs, examples/energy-monitor/src/main.rs, examples/energy-monitor/ui/big_main.slint, examples/energy-monitor/ui/main.slint, examples/energy-monitor/ui/small_main.slint
* Switch between big and small size layout
* mid size is prepared but will be added in a separate PR
=> energy-monitor: responsive view switch

docs/language/src/builtins/elements.md
Incorrect wording, likely due to copy&paste
=> Fix TouchArea doc

examples/printerdemo_mcu/ui/settings_page.slint
Align header and body in the right pane on settings page
=> printerdemo_mcu: Fix layout

examples/energy-monitor/ui/big_main.slint, examples/energy-monitor/ui/blocks/blocks.slint, examples/energy-monitor/ui/blocks/header.slint, examples/energy-monitor/ui/main.slint, examples/energy-monitor/ui/mid_main.slint, examples/energy-monitor/ui/pages/menu_page/menu_page.slint, examples/energy-monitor/ui/small_main.slint, examples/energy-monitor/ui/theme.slint, examples/energy-monitor/ui/widgets/menu.slint, examples/energy-monitor/ui/widgets/page_scroll_view.slint, examples/energy-monitor/ui/widgets/widgets.slint
* implement mid size view for the energy monitor demo
=> energy-monitor: mid size

examples/energy-monitor/ui/mid_main.slint, examples/energy-monitor/ui/widgets/page_scroll_view.slint
* mid-size: Use menu navigation to bring page into view
* mid-size: Animate horizontal scrolling
=> energy-monitor: polish mid size view

examples/energy-monitor/src/controllers/weather.rs, examples/energy-monitor/src/main.rs, examples/energy-monitor/ui/blocks/kiosk_overlay.slint, examples/energy-monitor/ui/desktop_window.slint, examples/energy-monitor/ui/mid_main.slint, examples/energy-monitor/ui/pages/menu_page/menu_overview.slint, examples/energy-monitor/ui/pages/menu_page/menu_page.slint, examples/energy-monitor/ui/pages/menu_page/settings.slint, examples/energy-monitor/ui/small_main.slint, examples/energy-monitor/ui/widgets/menu.slint, examples/energy-monitor/ui/widgets/switch.slint
* Can be enabled in settings
* Ca be disabled by click on overlay
=> em: kiosk mode

internal/backends/winit/renderer/femtovg/itemrenderer.rs
This is reproducible in the energy monitor when scrolling down in the settings page.
In the helper function to colorize an image, we did not expect brush_to_paint() to fail. The condition of a transparent colorize color was handled earlier, but it turns out that brush_to_paint() also checked the global state as an optimization.
This optimization is wrong, as the cached colorized image should not depend on the untracked global transparency.
So this patch adds a graceful handling of brush_to_paint returning None for defensive measures, but also moves the early return on an global transparent alpha to the call sites where it makes sense.
=> femtovg: Fix panic when rendering colorized image with transparent global alpha

examples/energy-monitor/ui/pages/menu_page/menu_page.slint, examples/energy-monitor/ui/small_main.slint, examples/energy-monitor/ui/widgets/menu.slint, examples/energy-monitor/ui/widgets/navigation.slint, examples/energy-monitor/ui/widgets/pagination.slint
* Memory optimization on page navigation and in menu
* Make click area to open menu button bigger
* Makes navigation faster
* Still redraw issues on mcu
=> em: memory and menu open optimization

internal/renderers/skia/itemrenderer.rs
Enable anti-aliasing, just like with FemtoVG and Qt.
=> Skia: Improve quality of rounded rect rendering

internal/core/item_rendering.rs
... as well as opacity
When an item change its geometry or clipping, one really must also refresh all the children, even the ones outside of the item.
And if the position of the parent changes, the old offset must still be used to compute the geometry
This change also add the clip to the dirty region so we don't need to draw so much for clipped items
=> Partial renderer: take in account change in clipping and parent geometry

examples/mcu-board-support/pico_st7789.rs
So that the init_clocks_and_plls call which initialize the CPU frequency is called before the Window initialization. This speeds up the boot sequence a lot.
Since this involve types that cannot easily be named, keep everything as generic types.
=> rp-pico: Move the initialization code to init()

internal/compiler/widgets/fluent-base/std-widgets-impl.slint, internal/compiler/widgets/material-base/widget-scrollview.slint
* Fix for #2347 
* add min width/height to scroll bar (fluent and material)
=> scroll-view: add min width/height vor scorll bar

examples/gallery/main.rs, internal/compiler/generator/rust.rs, internal/core/model.rs, internal/interpreter/api.rs
=> Mark StandardListViewItem as `#[non_exhaustive]`

api/cpp/cbindgen.rs, api/cpp/include/slint_image.h, api/cpp/include/slint_platform.h, api/cpp/include/slint_sharedvector.h, api/cpp/tests/datastructures.cpp, internal/core/graphics/image.rs
Issue #616
This commit don't contains pre-multiplied argb
=> C++: implement creation of image from raw data

internal/compiler/object_tree.rs, internal/compiler/tests/syntax/elements/listview.slint
=> compiler: turn a warning into an error

.gitignore, api/cpp/docs/.gitignore, api/cpp/docs/Pipfile, api/cpp/docs/conf.py, docs/language/.gitignore, docs/language/Pipfile, docs/language/conf.py, docs/language/index.rst
- refresh copyright
- link to slint-ui.com
- add footer icons
=> Slint docs style cleanups

api/rs/macros/lib.rs, api/rs/slint/tests/simple_macro.rs, examples/7guis/circledraw.slint, examples/7guis/crud.slint, examples/7guis/timer.slint, helper_crates/const-field-offset/macro/macro.rs, internal/compiler/diagnostics.rs, tests/doctests/build.rs, tests/driver/rust/build.rs
This is how it looks in the console:
=> Report warnings from the `slint!` macro

docs/language/src/concepts/layouting.md, internal/compiler/builtins.slint, internal/compiler/object_tree.rs, internal/compiler/passes/const_propagation.rs, internal/compiler/passes/default_geometry.rs, internal/compiler/passes/ensure_window.rs, internal/compiler/passes/inlining.rs, internal/compiler/passes/lower_layout.rs, internal/compiler/passes/repeater_component.rs, internal/compiler/passes/resolving.rs, internal/compiler/tests/syntax/analysis/binding_loop_layout4.slint, internal/compiler/tests/syntax/basic/percent.slint, internal/compiler/tests/syntax/lookup/conversion.slint, internal/compiler/widgets/fluent-base/std-widgets-impl.slint, internal/compiler/widgets/material-base/widget-scrollview.slint, internal/compiler/widgets/native/std-widgets-impl.slint, internal/core/items.rs, internal/core/items/path.rs, internal/core/layout.rs, tests/cases/bindings/change_sub_property_indirection_issue2185.slint, tests/cases/layout/default_fill.slint
=> layouting: Change the default behavior of widgets when not in a layout:  they should have the size of their preferred size

internal/backends/qt/qt_widgets.rs, internal/backends/qt/qt_window.rs, internal/core/item_rendering.rs, internal/core/software_renderer.rs, internal/renderers/femtovg/itemrenderer.rs, internal/renderers/skia/itemrenderer.rs
=> Fix software renderer with native style

api/cpp/platform.rs, api/rs/slint/tests/partial_renderer.rs, internal/core/software_renderer.rs
Also add a test for partial rendering
Closes #2389
=> software_renderer: return the modified region from the render call

internal/compiler/passes/embed_glyphs.rs, internal/compiler/passes/embed_images.rs, internal/compiler/tests/syntax/basic/image.slint
Final touch for #2024
Closes #2024
=> Turn more error into warnings

Cargo.toml, internal/compiler/Cargo.toml, internal/compiler/embedded_resources.rs, internal/compiler/passes/embed_glyphs.rs, internal/compiler/passes/embed_images.rs, internal/core/Cargo.toml, internal/core/graphics/image/svg.rs, internal/core/software_renderer/fonts/systemfonts.rs, internal/core/textlayout/shaping.rs
Don't import all the dependent crate, use the re-export
And use a workspace dependency
=> Update resvg and fontdb dependency

examples/energy-monitor/ui/mid_main.slint, examples/energy-monitor/ui/pages/balance.slint, examples/energy-monitor/ui/pages/overview.slint, examples/energy-monitor/ui/pages/usage.slint, examples/energy-monitor/ui/pages/weather.slint, examples/energy-monitor/ui/theme.slint, examples/energy-monitor/ui/widgets/balance_chart.slint, examples/energy-monitor/ui/widgets/bar_chart.slint, examples/energy-monitor/ui/widgets/bar_tiles.slint, examples/energy-monitor/ui/widgets/chart_pattern.slint, examples/energy-monitor/ui/widgets/page_scroll_view.slint
* small size: animate bars
* mid size: open tiles on click
=> em: after ew update

examples/energy-monitor/ui/desktop_window.slint
The design is unfortunately not complete yet.
=> Energy Monitor: Disable the desktop view

docs/site/index.html
=> Improvements to the doc landing page

api/node/README.md, api/node/cover.md, docs/building.md, docs/tutorial/node/src/getting_started.md
=> Nodejs: add some documentation of the dependencies

internal/compiler/typeloader.rs
In the online editor (aka Slintpad), loading of many files can be really slow because the files are getting loaded sequentially
In order to load files in parallel, we need to change the
```rust
for _ in dependencies {
load_file(....).await;
}
```
into something that will wait over a vector of boxed future.
The problem is that we can't borrow mutably the same state across different futures, so we need to refactor a bit to use RefCell.
Also we need to change the way we detect recursion because 
With this change, loading the enery-monitor is taking a couple of seconds instead of half a minute
=> Typeloader: Load files in parallel with wasm

api/cpp/README.md, api/cpp/docs/cmake.md, api/cpp/docs/getting_started.md, docs/tutorial/cpp/src/getting_started.md
Add some comment explaining the release branches into the cmake examples we have.
=> docs: Document release tags for use in cmake

tools/fmt/Cargo.toml, tools/fmt/fmt.rs, tools/fmt/lib.rs, tools/fmt/writer.rs
make it can be a crate, then it can be used in lsp
Then it can be easy for you to Realize lsp format
=> feat: move fmt tool to a crate

CHANGELOG.md, api/cpp/cbindgen.rs, api/cpp/include/slint.h, docs/language/index.rst, docs/language/src/builtins/globals.md, internal/compiler/builtins.slint, internal/compiler/expression_tree.rs, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/llr/optim_passes/inline_expressions.rs, internal/compiler/passes.rs, internal/compiler/passes/focus_item.rs, internal/compiler/passes/lower_text_input_interface.rs, internal/core/items/text.rs, internal/core/window.rs, internal/interpreter/eval.rs, tests/cases/focus/text-input-focused.slint
For the virtual keyboard, as a replacement for the API being added in #2490
=> Added TextInputInterface.text-input-focused

internal/core/software_renderer.rs
For software renderer text is now displayed also for text input elements. Display of text cursor and selection will be part of a following PR.
=> swr: display text on text input

tools/fmt/fmt.rs
While using slint, I got annoyed by slint-fmt breaking on stuff like
```
A := B {
for c in root.d: T {
e: c.attr;
}
}
```
or an array like this not being space-formatted.
```
[1,2,3]
```
I added some changes to format these properly. See the tests to get an idea of what's happening.
---
I do have two questions if you will:
1. There is nothing like `SyntaxKind::In` - if in the `for c in root.d` I want to match the `in` part, I just use a general `SyntaxKind::Identifier`. If we have things like `SyntaxKind::LBracket` or `SyntaxKind::Comma` - can't we have also the `SyntaxKind::In` ? if yes, where should I look into that?
2. I don't properly format the for loop with index yet, eg.
```
for number [index] in [1, 2, 3]: C {
d: number * index;
}
```
has a space before `[index]`.
The reason being …
=> [slint-fmt] - Add formatting of for loops and arrays

.github/workflows/ci.yaml, tools/fmt/fmt.rs
=> Formatter: Fix remaining issue so that it doesn't introduce syntax errors

internal/compiler/lookup.rs, internal/compiler/passes/resolving.rs, internal/compiler/tests/syntax/lookup/recover_id_lookup.slint
=> Compiler: hint when an id has the same name as a property or enum value

internal/core/software_renderer/fonts/systemfonts.rs
Load system fonts for Redox OS
=> load system fonts for redox

internal/core/graphics/image.rs
=> Docs: Image and threads

docs/language/src/builtins/elements.md
=> Docs: Document that opacity uses layers

api/rs/slint/Cargo.toml, internal/interpreter/Cargo.toml
=> Docs: document that the renderer-winit-* feature must be used with winit features

internal/core/timers.rs
=> Document that timers stop on drop

internal/compiler/passes/focus_item.rs, internal/compiler/passes/inlining.rs, internal/compiler/tests/syntax/focus/initial_focus_non_input.slint, tests/cases/focus/initial_focus_through_component.slint
Fixes https://github.com/slint-ui/slint/issues/2622
=> Fix focussing element whose base is focusable

docs/language/index.rst
Minor fixes to start creating pathways from the Getting Started topics for SlintPad, Designers, and Software Engineers.
=> Update the Getting Started section

README.md
I added a new project of mine (Tetris) to the "Made with Slint" section
=> Added Tetris made with slint

internal/compiler/passes/resolving.rs, internal/compiler/tests/syntax/expressions/unary_op.slint
=> Proper error when wrong type used in an unary operation

docs/language/src/reference/legacy_syntax.md
=> Fix a typo

.github/actions/setup-rust/action.yaml, CHANGELOG.md, api/cpp/CMakeLists.txt, api/cpp/Cargo.toml, api/rs/slint/Cargo.toml, internal/backends/selector/Cargo.toml, internal/backends/winit/Cargo.toml, internal/backends/winit/build.rs, internal/backends/winit/lib.rs, internal/interpreter/Cargo.toml, internal/renderers/skia/Cargo.toml, internal/renderers/skia/build.rs, internal/renderers/skia/lib.rs, internal/renderers/skia/vulkan_surface.rs, tools/lsp/Cargo.toml, tools/viewer/Cargo.toml
=> Initial support for rendering with Skia and Vulkan

internal/core/software_renderer.rs, internal/core/textlayout.rs, internal/core/textlayout/fragments.rs, internal/core/textlayout/linebreaker.rs
* software renderer: implement `text_input_cursor_rect_for_byte_offset`
* add `cursor_pos_for_byte_offset` for `TextParagraphLayout` by Simon
* software renderer: display text cursor
=> swr text cursor

internal/compiler/typeloader.rs
Because we `return None` in case of error before we remove the file from `currently_loading` we would then await forever next time we try to load that file.
This will cause a deadlock that can be causing #2709
=> Typeloader: In case of load error, don't keep invalid files as currently loading

internal/backends/winit/winitwindowadapter.rs
Otherwise we have the bug that setting the maximum and minimum constraint, that happens before show(), would use the wrong scale factor
=> Winit: set the Window scale factor once we got the winit::Window

.github/workflows/nightly_snapshot.yaml, .github/workflows/wasm_demos.yaml, .github/workflows/wasm_editor_and_interpreter.yaml, internal/backends/winit/Cargo.toml, internal/backends/winit/wasm_input_helper.rs, internal/core/input.rs, internal/core/items/text.rs
The PR #2703 wasn't complete and didn't work in practice because the clipboard is always None.
Using the clipboard event data works
=> Wasm: Fixup Copy/paste

internal/compiler/widgets/material-base/md.slint, internal/compiler/widgets/material-base/std-widgets-impl.slint, internal/compiler/widgets/material-base/widget-groupbox.slint
Some visual tweaks on the md `GroupBox`. Inspired by the flutter md 3 gallery.
=> material: improve groupbox visual

CHANGELOG.md, internal/core/input.rs, tests/cases/elements/flickable.slint, tests/cases/issues/issue_2717_has-hover.slint
=> Properly send exit event when two TouchArea are on top of eachother

internal/backends/winit/winitwindowadapter.rs
This was accidentally removed in 7df902b53cc10de5874e579185a1fc2221a81300
cc #2775
=> winit: Fix fullscreen support

internal/renderers/femtovg/Cargo.toml, internal/renderers/femtovg/itemrenderer.rs
The latest release uses interior mutability for the Path caching.
=> Bump FemtoVG

docs/language/src/concepts/fonts.md
96aeffa added support for importing .otf files
=> docs(fonts): mention OpenType support

CHANGELOG.md, api/rs/slint/private_unstable_api.rs, docs/language/src/builtins/elements.md, internal/compiler/builtins.slint, internal/compiler/expression_tree.rs, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/llr/optim_passes/inline_expressions.rs, internal/compiler/passes.rs, internal/compiler/passes/binding_analysis.rs, internal/compiler/passes/lower_absolute_coordinates.rs, internal/compiler/tests/syntax/analysis/binding_loop_mappointtowindow.slint, internal/compiler/typeregister.rs, internal/core/items.rs, internal/interpreter/eval.rs, tests/cases/absolute_coords.slint
=> Add support for absolute-x and absolute-y properties on any element

CHANGELOG.md, examples/printerdemo/rust/main.rs, examples/printerdemo_mcu/main.rs, internal/core/model.rs, internal/interpreter/api.rs
=> Add convenience implementations of From for ModelRc from slices and arrays

CHANGELOG.md, docs/language/src/builtins/widgets.md, internal/compiler/widgets/fluent-base/widget-table-view.slint, internal/compiler/widgets/material-base/widget-table-view.slint, internal/compiler/widgets/native/std-widgets.slint
=> Added `current-row` to `StandardTableView`

api/cpp/CMakeLists.txt, api/cpp/Cargo.toml, docs/language/src/concepts/translations.md, tools/viewer/Cargo.toml, tools/viewer/main.rs
Can cause problem when compiling on windows or mac
=> Translations: disable gettext by default for C++ and the viewer

.github/workflows/translations.yaml, examples/printerdemo/ui/copy_page.slint, examples/printerdemo/ui/home_page.slint, examples/printerdemo/ui/ink_page.slint, examples/printerdemo/ui/print_page.slint, examples/printerdemo/ui/printer_queue.slint, examples/printerdemo/ui/printerdemo.slint, examples/printerdemo/ui/scan_page.slint, examples/printerdemo/ui/settings_page.slint, examples/printerdemo/ui/usb_page.slint
(doesn't include the native code, only .slint)
=> Printer demo: wraps strings in `@tr()`

tools/lsp/server_loop.rs
It only suggest the transformation for string that are directly within an expression, so that's only string literals. (Not import, not image macro, not already translated strings)
Drive by fix: fix the code action for showing the preview that was broken because confusion between path and URL
=> LSP: code action for wrapping a string in `@tr()`

CHANGELOG.md, api/cpp/docs/types.md, api/rs/slint/lib.rs, docs/language/src/builtins/enums.md, docs/language/src/reference/types.md, editors/kate/slint.ksyntaxhighlighter.xml, editors/sublime/Slint.sublime-syntax, editors/tree-sitter-slint/grammar.js, editors/vscode/slint.tmLanguage.json, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/langtype.rs, internal/compiler/object_tree.rs, internal/compiler/parser.rs, internal/compiler/parser/document.rs, internal/compiler/parser/type.rs, internal/compiler/passes.rs, internal/compiler/passes/collect_structs_and_enums.rs, internal/compiler/tests/syntax/basic/enums.slint, internal/compiler/typeregister.rs, internal/interpreter/dynamic_component.rs, tests/cases/imports/external_structs.slint, tests/cases/types/enums.slint, tests/helper_components/export_structs.slint, tools/lsp/goto.rs, tools/lsp/semantic_tokens.rs, tools/lsp/server_loop.rs, xtask/src/enumdocs.rs
Closes https://github.com/slint-ui/slint/issues/150
=> Support for declaring enums in slint

api/node/native/lib.rs, internal/backends/qt/qt_window.rs, internal/backends/testing/lib.rs, internal/backends/winit/winitwindowadapter.rs, internal/core/api.rs, internal/core/window.rs
Not sure if that makes so much sense but that's what we discussed in the last API meeting
=> Change the return type of WindowAdapterSealed::position to be an Optional

CHANGELOG.md, api/rs/slint/tests/spawn_local.rs, internal/core/api.rs, internal/core/future.rs, internal/core/lib.rs, tools/lsp/preview.rs, tools/viewer/main.rs
=> Implement a way to run future on the slint event loop

editors/README.md
Unfortunately the plugin is not maintained anymore and no longer works. It's archived repo is here:
https://github.com/gtache/intellij-lsp
There is a fork from it, which can be used for bootstrapping a new plugin here:
https://github.com/ballerina-platform/lsp4intellij
Other than that JetBrains baked in support for LSP in their upcoming Fleet IDE, which is in Public Preview, but there's no documentation how to make custom toolchains for it yet. They seem to use an external LSP with rust-analyzer, so it should be possible in the future.
=> Update README.md with more tested JetBrains IDEs

docs/language/src/builtins/widgets.md
=> Separate GroupBox and GridBox

docs/language/src/builtins/widgets.md, examples/gallery/ui/pages/controls_page.slint, internal/backends/qt/qt_widgets/progress_indicator.rs, internal/compiler/builtins.slint, internal/compiler/widgets/fluent-base/progressindicator.slint, internal/compiler/widgets/material-base/widget-progress-indicator.slint
* Changes API according to API review
* Removed `maximum` and `minimum`
* `progress` is now a percentage value
=> Refactor ProgressIndicator api according to api review.

internal/backends/qt/qt_widgets/progress_indicator.rs, internal/compiler/widgets/native/std-widgets.slint
- LineEdit: use same min size as the other styles
- Fix indeterminate ProgressIndicator
=> Small bugfixes in native style:

internal/compiler/widgets/fluent-base/combobox.slint, internal/compiler/widgets/fluent-base/components.slint, internal/compiler/widgets/fluent-base/slider.slint, internal/compiler/widgets/fluent-base/std-widgets-base.slint, internal/compiler/widgets/fluent-base/styling.slint, internal/compiler/widgets/fluent-base/tableview.slint, internal/compiler/widgets/fluent-base/textedit.slint
* StandardTableView: Fixed column header hover effect
* StandardTableView: Added alternative row background
* TextEdit: Polish to look more like the design
* ComboBox: Fix icon position
* Slider: Added missing brush to the thumb border
=> Polish fluent design refresh

internal/backends/winit/winitwindowadapter.rs
So that subsequent call to Window::size() return the same value
Should fix flickering of window size at startup
=> winit: cache the size returned by inner_size

internal/backends/winit/accesskit.rs, internal/core/item_rendering.rs, internal/core/item_tree.rs
=> micro-optim ItemRc::component() returns a ref instead of cloning

internal/compiler/layout.rs, internal/compiler/object_tree.rs, internal/compiler/passes/default_geometry.rs, internal/compiler/passes/lower_layout.rs, tests/cases/layout/special_default_geometry.slint, tests/cases/layout/text_preferred_size.slint
=> Fix default geometry of items with `inject_element_as_repeated_element`

internal/compiler/generator/rust.rs
A small suggestion to help reduce the size of rust generated files.
using `use slint::private_unstable_api::re_exports as sp;` should allow to safely qualify everything while keeping things shorter.
For the `todo` example:
- before 1_050_650 octets for 24_012 formatted lines
- after 934_049 octets for 23_032 formatted lines
This also makes the generated code more readable if needed.
=> reduce rust generated file size

docs/language/src/recipes/recipes.md
=> Added splitter to responsive recipe

internal/backends/winit/accesskit.rs
We need to make sure to replace the dummy tree from #3046 with a real tree.
=> Fix accessibility tree on Linux when UI has no repeaters

api/cpp/include/slint_platform.h, api/cpp/platform.rs, api/cpp/tests/CMakeLists.txt, api/cpp/tests/platform_eventloop.cpp
(This wasn't really tested yet)
=> C++ experimental platform event loop

CHANGELOG.md, internal/compiler/widgets/fluent-base/combobox.slint
=> Fixed enabled in fluent ComboBox

internal/core/timers.rs
Add set_interval function to Timer, which could change the interval of timer without re-invoking a start function.
fix #3128
=> Add set_interval function to Timer

internal/compiler/parser/type.rs, internal/compiler/tests/syntax/parse_error/struct.slint
Reported there: https://chat.slint.dev/public/pl/6y3ekgw8xt8f7fu8e7aojtwada
=> Better error when using ';' instead of ',' when declaring struct

tools/lsp/completion.rs
Use default values, choices and nested replacements where those make sense. Use `$0` to place the cursor once done and add some line breaking.
Remove the transitions (not mentioned in the docs anymore) snippet, add a `when` snippet for use in states.
=> LSP: Polish snippets

api/cpp/include/slint_platform.h, api/cpp/platform.rs, api/cpp/tests/platform_eventloop.cpp
Also add an assert in the run() function
=> C++: rename PlatformEvent to Platform::Task

api/cpp/include/slint_platform.h, api/cpp/platform.rs, api/cpp/tests/manual/platform_native/windowadapter_win.h, api/cpp/tests/manual/platform_qt/main.cpp, internal/backends/winit/lib.rs, internal/backends/winit/renderer/femtovg.rs, internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/sw.rs, internal/backends/winit/winitwindowadapter.rs, internal/renderers/femtovg/lib.rs, internal/renderers/skia/lib.rs
Fold show() into the first time render() is invoked, and hide() into the Drop implementation.
=> Simplify FemtoVG and Skia renderer API

internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, tests/cases/absolute_coords.slint
=> Compiler: Fix `access_item_rc` in the generator for complex path

CHANGELOG.md, api/cpp/include/slint_platform.h, api/cpp/platform.rs, api/cpp/tests/manual/platform_native/windowadapter_win.h, api/cpp/tests/manual/platform_qt/main.cpp, api/node/native/lib.rs, internal/backends/qt/qt_window.rs, internal/backends/testing/lib.rs, internal/backends/winit/event_loop.rs, internal/backends/winit/winitwindowadapter.rs, internal/core/window.rs, internal/interpreter/ffi.rs
This makes for a smaller interface.
=> Replace show()/hide() in the WindowAdapter with set_visible(bool)

CHANGELOG.md, docs/language/src/builtins/widgets.md, internal/compiler/widgets/fluent-base/components.slint, internal/compiler/widgets/fluent-base/listview.slint, internal/compiler/widgets/material-base/components.slint, internal/compiler/widgets/material-base/listview.slint, internal/compiler/widgets/native/std-widgets.slint
* Similar to `StandardTableView`-`row-pointer-event`.
=> Added item-pointer-event to StdListView

api/cpp/build.rs, api/cpp/cbindgen.rs
So that there shouldn't be more copy-paste mistakes
=> C++: use a macro to define the `EnabledFeatures` struct

internal/backends/winit/accesskit.rs, internal/backends/winit/wasm_input_helper.rs, internal/compiler/typeloader.rs, internal/core/input.rs, internal/core/window.rs, internal/interpreter/eval.rs, internal/interpreter/highlight.rs, tools/lsp/preview.rs, xtask/src/license_headers_check.rs
Nightly now supports it and thus `cargo +nightly fmt` yields a difference.
=> Fix let-else formatting

api/cpp/cbindgen.rs, internal/backends/linuxkms/Cargo.toml, internal/backends/linuxkms/calloop_backend.rs, internal/backends/linuxkms/calloop_backend/input.rs, internal/backends/qt/qt_window.rs, internal/backends/winit/event_loop.rs, internal/backends/winit/wasm_input_helper.rs, internal/common/key_codes.rs, internal/compiler/lookup.rs, internal/core/input.rs
Unfortunately, this is currently not mapped to the right keyboard layout
Also keep the mouse clamped in the visible area.
And make it start in the middle of the screen.
=> linuxkms: Implement keyboard input and clamp the mouse

internal/backends/qt/qt_widgets.rs, internal/backends/qt/qt_window.rs
Fixes https://github.com/slint-ui/slint/issues/3193
=> Qt backend: throttle updates and fix native style animation

CHANGELOG.md, api/cpp/cbindgen.rs, api/cpp/include/slint_image.h, api/rs/slint/lib.rs, examples/opengl_texture/main.rs, internal/core/graphics/image.rs, internal/renderers/femtovg/images.rs, internal/renderers/skia/cached_image.rs
=> Add support for flipping borrowed OpenGL textures vertically

api/napi/__test__/js_value_conversion.spec.ts
- cover when properties are missing
- verify that excess properties are ignored
=> napi: add more tests for js object -> structure conversion

api/napi/__test__/js_value_conversion.spec.ts, api/napi/src/interpreter/value.rs
Accept any object that has the ImageData shape
cc #2474
=> napi: Fix calling setProperty on image properties with external image data

.github/workflows/ci.yaml, api/napi/__test__/js_value_conversion.spec.ts, api/napi/src/types/image_data.rs
=> Remove image data constructor to fix release build

internal/compiler/passes/resolving.rs, internal/compiler/tests/syntax/basic/linear-gradient.slint
=> Fix panic when parsing invalid gradiant

internal/backends/winit/winitwindowadapter.rs
Only call set_window_level if the value changes.
Fixes #3280
=> Fix window always coming to the front on Ubuntu 20.04 when window properties change

api/rs/slint/Cargo.toml
=> Add a serde feature to Slint

editors/README.md, tools/lsp/completion.rs, tools/lsp/properties.rs, tools/lsp/util.rs
This PR is to close https://github.com/slint-ui/slint/issues/3237
For part of code change, please see comments inline for better understanding.
The change was tested on Windows 11 + Sublime Text 4 (Build 4152)
=> Auto complete for animate block

api/cpp/esp-idf/slint/README.md
=> First draft for new getting-started instructions for the ESP-IDF component

internal/interpreter/api.rs
=> Document how SetPropertyError::WrongType can be produced when assigning structs

api/cpp/include/slint-platform.h, api/cpp/platform.rs
- make sure the Platform::Clipboard type is properly documented
- Use the actual enum in the interface (even though it is #[non_exhaustive] so we need to slience a warning)
CC: #3265
=> C++: polish the clipboard patch

api/cpp/include/slint-platform.h, api/cpp/platform.rs, examples/cpp/platform_qt/main.cpp, internal/core/api.rs, internal/core/graphics.rs
=> Add support for set_position(), position(), and set_physical_size() to the C++ WindowAdapter

internal/backends/linuxkms/display/egldisplay.rs, internal/backends/linuxkms/lib.rs, internal/backends/linuxkms/renderer/femtovg.rs, internal/backends/winit/renderer/femtovg/glcontext.rs, internal/core/api.rs, internal/renderers/femtovg/lib.rs
It was Send before, so try to keep it Send with the new Boxed dyn error, too.
=> Fix PlatformError compatibility

tools/lsp/language/properties.rs
When determining the indentation of an element, walk back to a whitespace token that contains a line break. A whitespace token immediately before the element may not present its indentation in case the element is assigned to a name, for example.
```qml
export component Foo {
bar := Text { } // <== " " vs. "    "
}
```
Before:
https://github.com/slint-ui/slint/assets/140617/6588fd20-bfbe-4a20-99c0-e85ae5f7c074
After:
https://github.com/slint-ui/slint/assets/140617/0cf50f6a-5f50-4497-ae79-e27dd45107d7
=> lsp: fix find_element_indent() for named elements

internal/compiler/expression_tree.rs, tests/cases/types/structs2.slint
Fixes https://github.com/slint-ui/slint/issues/2765
=> Compiler: fix conversion from unnamed to named struct 

.github/workflows/ci.yaml, api/cpp/CMakeLists.txt, internal/renderers/skia/Cargo.toml, internal/renderers/skia/d3d_surface.rs
=> Update Skia and re-enable Windows CI builds

internal/compiler/widgets/cupertino-base/button.slint, internal/compiler/widgets/cupertino-base/checkbox.slint, internal/compiler/widgets/cupertino-base/combobox.slint, internal/compiler/widgets/cupertino-base/components.slint, internal/compiler/widgets/cupertino-base/groupbox.slint, internal/compiler/widgets/cupertino-base/lineedit.slint, internal/compiler/widgets/cupertino-base/listview.slint, internal/compiler/widgets/cupertino-base/progressindicator.slint, internal/compiler/widgets/cupertino-base/scrollview.slint, internal/compiler/widgets/cupertino-base/slider.slint, internal/compiler/widgets/cupertino-base/spinbox.slint, internal/compiler/widgets/cupertino-base/std-widgets-impl.slint, internal/compiler/widgets/cupertino-base/styling.slint, internal/compiler/widgets/cupertino-base/switch.slint, internal/compiler/widgets/cupertino-base/tableview.slint, internal/compiler/widgets/cupertino-base/tabwidget.slint, internal/compiler/widgets/cupertino-base/textedit.slint, internal/compiler/widgets/material-base/listview.slint
* Cleanup of the style
* Add missing state visuals for widgets
* After this PR we need to find a way to handle icons, at the moment material style icons are used
=> Finish state visuals of cupertino style.

internal/compiler/typeloader.rs
The problem is that the file stays in the `currently_loading` hashmap and therefore we thinkg we need to await for the result, while it is not actually loading
Regression since f1f5a86d0d75e139baff413b2079d6545369c0d9
Fixes #3468
=> compiler: Fix loading the same file twice would result in infinite pending state

internal/backends/qt/qt_widgets.rs
Example Breeze do that.
Fixes #3482
=> qt style: Fix animation when the QStyle uses update() on the widget

CHANGELOG.md, internal/backends/winit/renderer/femtovg/glcontext.rs, internal/renderers/skia/opengl_surface.rs
=> Default to vsync for OpenGL rendering

internal/compiler/llr/lower_expression.rs, tests/cases/elements/popupwindow_close.slint
=> Fix compiler panic with popup.closes

internal/compiler/generator/rust.rs, tests/cases/callbacks/functions.slint, tests/cases/callbacks/init.slint, tests/cases/globals/global_accessor_api.slint, tests/cases/globals/global_alias.slint, tests/cases/models/delete_from_clicked.slint, tests/driver/rust/main.rs
=> Fix compilation of the generated code with `deny(rust_2018_idioms)`

CHANGELOG.md, internal/backends/qt/qt_widgets.rs, internal/backends/qt/qt_widgets/listviewitem.rs, internal/backends/qt/qt_widgets/tableheadersection.rs
=> Qt style: Fix GroupBox not being clipped

api/napi/.gitignore, api/napi/__test__/js_value_conversion.spec.ts, api/napi/__test__/types.spec.ts, api/napi/index.d.ts, api/napi/index.ts, api/napi/package.json, api/napi/src/interpreter/component_instance.rs, api/napi/src/interpreter/value.rs, api/napi/src/types/model.rs
* Added Model interface
* Added ModelPeer interface
* Set models from js array
* Added ArrayModel
* Set model from js
=> Added Model implementation for napi

api/cpp/CMakeLists.txt, api/rs/build/lib.rs, api/rs/macros/lib.rs, internal/backends/selector/Cargo.toml, internal/backends/selector/build.rs, internal/common/lib.rs, internal/compiler/typeloader.rs
=> Change alias to the native style depending on the platform

api/napi/__test__/api.spec.ts, api/napi/__test__/compiler.spec.ts, api/napi/__test__/resources/error.slint, api/napi/__test__/resources/test.slint, api/napi/index.ts, examples/todo/napi/README, examples/todo/napi/main.js, examples/todo/napi/package.json
* With this PR it is possible to run the todo example with napi
* This is PR is draft because expect discussions ;-)
* PR #3544 should be merged first
=> Create components from a slint file for napi

internal/compiler/generator/cpp.rs
Warning looks like that
```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.35.32215\include\tuple(144,47): warning C4244: 'initializing': conversion from '_Ty' to '_Ty', possible loss of data [D:\a\slint\cppbuild\examples\virtual_keyboard\cpp\virtual_keyboard.vcxproj]
with
[
_Ty=int
]
and
[
_Ty=float
]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.35.32215\include\tuple(239): message : see reference to function template instantiation 'std::_Tuple_val<_This>::_Tuple_val<_Ty>(_Other &&)' being compiled [D:\a\slint\cppbuild\examples\virtual_keyboard\cpp\virtual_keyboard.vcxproj]
with
[
_This=float,
_Ty=int,
_Other=int
]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.35.32215\include\tuple(239,81): message : see …
```
=> Proscpective fix for MSVC warnings

docs/reference/src/language/syntax/animations.md
It can be confusing otherwise, see #3494
=> Docs: reference animation-tick from the animation page

CHANGELOG.md, docs/reference/src/language/syntax/functions.md, examples/printerdemo/ui/printer_queue.slint, internal/compiler/langtype.rs, internal/compiler/object_tree.rs, internal/compiler/parser/element.rs, internal/compiler/passes/resolving.rs, internal/compiler/tests/syntax/functions/function_double_qualified.slint, internal/compiler/tests/syntax/functions/functions.slint, internal/compiler/tests/syntax/functions/functions_call.slint, internal/compiler/tests/syntax/functions/functions_purity.slint, internal/compiler/typeregister.rs
Protected function can only be called from the direct base
Issue #3636
=> Add support for protected functions

internal/compiler/widgets/common/combobox-base.slint, internal/compiler/widgets/cupertino-base/combobox.slint, internal/compiler/widgets/fluent-base/combobox.slint, internal/compiler/widgets/material-base/combobox.slint, internal/compiler/widgets/qt/std-widgets.slint
=> Introduce ComboboxBase and in/decrement selection by scroll event

internal/compiler/passes/const_propagation.rs
We see that a lot in the fluent style. For example:
```
font-size: Typography.body.font-size;
```
Where Typography.body is a contant expression define as
```
out property <TextStyle> body: {
font-size: 14 * 0.0769rem,
font-weight: regular-font-weight
};
```
But because this first converts from an annonymous tuple struct to a named struct, the const propagation used to be confused. Now with this patch it is properly simplified
Before this change
cargo run -p slint-compiler -- examples/printerdemo_mcu/ui/printerdemo.slint -f rust | rustfmt | wc
38643   84506 1925846
cargo run -p slint-compiler -- examples/gallery/gallery.slint -f rust | rustfmt | wc
103210  224427 5291034
After this change
cargo run -p slint-compiler -- examples/printerdemo_mcu/ui/printerdemo.slint -f rust | rustfmt | wc …
=> compiler: Simplify struct access expression of constants after struct cast

CHANGELOG.md, internal/backends/qt/qt_widgets/spinbox.rs, internal/compiler/widgets/common/spinbox-base.slint, internal/compiler/widgets/cupertino-base/spinbox.slint, internal/compiler/widgets/fluent-base/spinbox.slint, internal/compiler/widgets/material-base/spinbox.slint
* Fixes #1465
* Fixes text not displayed for material `SpinBox`
=> Added SpinBoxBase, use scroll-event to change value.

Cargo.toml, internal/compiler/Cargo.toml, tests/driver/interpreter/Cargo.toml, tools/tr-extractor/Cargo.toml
Suggested in https://github.com/slint-ui/slint/pull/3651#discussion_r1358115061.
=> Janitor: add itertools as a workspace dependency

internal/interpreter/dynamic_item_tree.rs
The interpreter knows whether we have Qt or not, but its logic was not adapted to the recent change of default.
=> interpreter: fix default style selection

internal/backends/qt/qt_widgets/scrollview.rs, internal/compiler/widgets/cupertino-base/scrollview.slint, internal/compiler/widgets/fluent-base/scrollview.slint, internal/compiler/widgets/material-base/scrollview.slint
=> Update scroll offset on ScrollView on ScrollBar scroll-event

internal/compiler/passes/infer_aliases_types.rs, internal/compiler/tests/syntax/imports/bug_3674_alias-from-broken-import.slint, internal/compiler/tests/typeloader/incpath/bug_3674_alias_from_invalid_import.slint
=> Fix compiler panic when trying to resolve aliases in invalid import

internal/backends/linuxkms/calloop_backend/input.rs
This has two benefits:
- It improves start-up time for device that are touch-only because the xkb parsing is delayed until a keyboard is attached and key is pressed
- It fixes #3678 by working around the situation where xkb would crash if the xkbcommon data files (in /usr/share/X11/xkb) aren't there. Sadly, no error is reported in that case (that we could handle), instead just crashes.
=> linuxkms: Initialize xkb lazily

tools/lsp/main.rs
The "LanguageServer" thread (New name also given in that commit) is blocked while waiting for the io threads because the preview keeps a ServerNotifier in its content cache.
We first need to tell the preview to quit before waiting on these threads.
=> Fix LSP not quiting when it shows a preview

CHANGELOG.md, docs/reference/src/language/builtins/elements.md, internal/compiler/builtins.slint, internal/core/items.rs, tests/cases/focus/focus_callbacks.slint, tests/cases/focus/focus_change_event.slint
```slint
FocusScope {
focus-changed-event => {
debug("Focus has changed");
}
}
```
=> Added focus-changed-event callback to FocusScope

api/napi/.gitignore, api/napi/__test__/api.spec.ts, api/napi/cover.md, api/napi/index.ts, api/napi/package.json, api/napi/src/interpreter.rs, api/napi/src/interpreter/diagnostic.rs, api/napi/src/interpreter/window.rs, api/napi/src/types/brush.rs, api/napi/src/types/image_data.rs, api/napi/src/types/point.rs, api/napi/src/types/size.rs
* Add missing documentation
* Generate documentation with typedoc
=> napi documentation

tools/lsp/language/completion.rs
Fixes the second issue mentioned in #3714: if the completion point is already followed by a "{", don't insert an additional "{}".
=> LSP: don't insert extra braces for "Wrap in element" auto-completions

Cargo.toml, internal/backends/winit/Cargo.toml, internal/renderers/skia/Cargo.toml
Only pull in wayland or x11 and skip kms for now.
=> Reduce softbuffer features

internal/compiler/passes/lower_layout.rs, internal/compiler/tests/syntax/layout/if_in_grid_row.slint
=> Compiler: Don't panic when a Row is repeated in a GridLayout

internal/compiler/object_tree.rs, internal/compiler/passes/ensure_window.rs, internal/compiler/passes/inlining.rs, internal/compiler/passes/lower_layout.rs, internal/compiler/passes/repeater_component.rs, internal/interpreter/highlight.rs
Preview the Layout in red and normal elements in blue
=> Add layout information to the Element

Cargo.toml, internal/backends/linuxkms/Cargo.toml, internal/backends/winit/Cargo.toml, internal/backends/winit/renderer/femtovg/glcontext.rs, internal/renderers/skia/Cargo.toml, internal/renderers/skia/opengl_surface.rs
Disable transparency support to work around https://github.com/rust-windowing/glutin/issues/1640
=> Make GL rendering work again on macOS

internal/compiler/widgets/fluent-base/styling.slint
I noticed that the fluent light scrollbars are barley visible.
=> Make fluent light scroll bars more visible

internal/backends/winit/lib.rs, internal/backends/winit/renderer/skia.rs, internal/renderers/skia/Cargo.toml, internal/renderers/skia/build.rs, internal/renderers/skia/lib.rs
softbuff doen't compile on android
=> Skia: disable skia software renderer for android

docs/reference/src/advanced/backends_and_renderers.md
Related discussion: https://github.com/slint-ui/slint/discussions/3782
=> Document the limitations of the software renderer

internal/core/window.rs, tests/cases/elements/popupwindow_close.slint
=> Don't close embedded popups when clicking outside and click-on-close:false is set

api/node/README.md, api/node/__test__/js_value_conversion.spec.ts, api/node/__test__/types.spec.ts, api/node/cover.md, api/node/index.ts, api/node/src/interpreter/value.rs, api/node/src/interpreter/window.rs, api/node/src/types/brush.rs, api/node/src/types/image_data.rs, api/node/src/types/point.rs, api/node/src/types/size.rs
=> node: export classes use interfaces for setters

CHANGELOG.md, api/cpp/include/slint.h, internal/core/model.rs, internal/core/model/adapters.rs, internal/core/model/model_peer.rs, internal/interpreter/value_model.rs, tests/cases/models/write_to_model_listview.slint
=> Models: fix writing data doesn't update ListView model data property

api/cpp/cbindgen.rs, api/cpp/include/slint_window.h, internal/backends/android-activity/lib.rs, internal/backends/qt/qt_window.rs, internal/backends/winit/event_loop.rs, internal/backends/winit/wasm_input_helper.rs, internal/backends/winit/winitwindowadapter.rs, internal/common/builtin_structs.rs, internal/core/api.rs, internal/core/input.rs, internal/core/items/text.rs, internal/core/window.rs, tests/cases/focus/focus_change.slint
Steps towards https://github.com/slint-ui/slint/issues/3811 but doesn't add anything public yet.
=> Refactor and improve input methods

api/rs/slint/Cargo.toml, api/rs/slint/lib.rs
Causes compilation problem with default features otherwise
And doesn't work anyway
=> Disable FemtoVG on Android

api/node/cover.md, api/node/index.ts
This covers a bit more in the intro, concepts, and type mappings.
=> Some Node.js doc improvements

api/node/__test__/js_value_conversion.spec.ts, api/node/__test__/types.spec.ts, api/node/cover.md, api/node/index.ts
=> moved slint classes to private_api

tools/lsp/main.rs, tools/lsp/preview/ui.rs, tools/lsp/ui/main.slint
=> LSP  Preview: add a `--fullscreen` command arg

xtask/src/license_headers_check.rs
otherwise can't be uploaded to crates.io
And we have to do last minute patchup like 0b70cbc9a9e2add6841c43adfe99a8436716791c
=> xtask: Check that dev dependencies don't have a version

Cargo.toml, examples/opengl_texture/Cargo.toml, examples/opengl_underlay/Cargo.toml, internal/common/Cargo.toml, internal/core/Cargo.toml, internal/renderers/femtovg/Cargo.toml, internal/renderers/skia/Cargo.toml
The memmap and fontconfig features are enabled by default.
=> Bump fontdb version

internal/compiler/widgets/fluent-base/scrollview.slint
=> fluent: fixed scrollbar width / height

internal/core/software_renderer/draw_functions.rs
Do the match on the format before the loop
=> swrenderer: Optimize image rendering

tools/lsp/language.rs
Empty symbol names causes error in vscode
Fix #3979
Also fix the ranges of enums
=> LSP: don't expose symbols with empty names

internal/core/software_renderer.rs
Fixes #4022, I'm not sure if there are other edge cases so I've put the PR.
I've put the PR as a draft since it's not fully tested and there might be other edge cases since I'm not familar with the internals.
It's more to show more concretely the underlying issue of #4022.
=> fix: compare current line with dirty region

internal/backends/winit/winitwindowadapter.rs
Try to fix the issue https://github.com/slint-ui/slint/issues/3911.
In 1.3.0, the function "adjust_window_size_to_satisfy_constraints" is deleted.
I guess that, in Winit 0.29.x, the window will automatically resize, but, at least, it doesn't work on Windows.
So, I try to add this function back.
=> Fix the window doesn't automatically resize.

internal/compiler/widgets/common/combobox-base.slint
=> combobox fix mouse wheel selection direction

CHANGELOG.md, docs/reference/src/language/widgets/button.md, examples/gallery/ui/pages/controls_page.slint, internal/backends/qt/qt_widgets/button.rs, internal/compiler/builtins.slint, internal/compiler/widgets/cupertino-base/button.slint, internal/compiler/widgets/fluent-base/button.slint, internal/compiler/widgets/material-base/button.slint, internal/compiler/widgets/qt/button.slint
Fixes #4150 
@ogoffart what is the beset way to colorize a `QIcon` I found only that there is a state property. Is it possible?
=> Added colorize-icon to Button

internal/backends/qt/qt_widgets/button.rs
=> Implement `colorize-icon` for `NativeButton`

tools/tr-extractor/main.rs
=> slint-tr-extractor: fix plural form

internal/compiler/namedreference.rs, tests/cases/issues/issue_4241_alias-const.slint
=> Fix property wrongly considered as const if it is modified through an alias

.github/workflows/build_docs.yaml, internal/backends/android-activity/README.md, internal/backends/android-activity/lib.rs
This will show in a "hidden" crate that can be linked to from the readme
=> CI: Documentation for i-slint-backend-android-activity

api/cpp/platform.rs, internal/backends/android-activity/lib.rs, internal/backends/winit/lib.rs, internal/backends/winit/renderer/femtovg.rs, internal/backends/winit/renderer/femtovg/glcontext.rs, internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/sw.rs, internal/backends/winit/winitwindowadapter.rs, internal/renderers/skia/d3d_surface.rs, internal/renderers/skia/lib.rs, internal/renderers/skia/metal_surface.rs, internal/renderers/skia/opengl_surface.rs, internal/renderers/skia/software_surface.rs, internal/renderers/skia/vulkan_surface.rs
Use winit's pre_present_notify() API to allow for the compositor to throttle rendering.
Fixes #4200
cc #1695
=> Add support for frame throttling on Wayland

internal/backends/linuxkms/display/egldisplay.rs, internal/backends/linuxkms/renderer/femtovg.rs
Remove the hack of calling present() from our swap_buffers() forwarder (and let it really only forward), and instead call it explicitly through the shared egl_display member. The way we can pass along the callback instead of storing it separately.
=> LinuxKMS: Clean up internal page flip callback API

internal/core/model.rs
=> ListView: ensure that we track change to the model

internal/backends/qt/lib.rs, internal/backends/qt/qt_widgets.rs, internal/backends/winit/event_loop.rs, internal/backends/winit/lib.rs, internal/backends/winit/winitwindowadapter.rs, internal/core/animations.rs, internal/core/future.rs, internal/core/input.rs, internal/core/items.rs, internal/core/items/text.rs, internal/core/lib.rs, internal/core/platform.rs, internal/core/tests.rs, internal/core/window.rs
Some small steps towards #4294 and #1499
=> Refactor the way the Platform and the quit behavior

.github/workflows/ci.yaml
In response to https://github.com/actions/runner-images/issues/8952
=> Prospective fix for Android builds

docs/reference/src/language/builtins/namespaces.md, internal/backends/winit/event_loop.rs, internal/common/key_codes.rs
=> feat: Add Key.Space to Key namespace.

.github/workflows/ci.yaml, examples/printerdemo/rust/Cargo.toml, examples/printerdemo/rust/main.rs
=> add printerdemo for android

CHANGELOG.md, api/cpp/include/slint-interpreter.h, api/cpp/include/slint.h, api/cpp/lib.rs, api/cpp/tests/platform_eventloop.cpp, api/cpp/tests/test.slint, api/rs/slint/lib.rs, internal/core/platform.rs, internal/core/window.rs, tools/lsp/preview/native.rs
=> Introduce slint::run_event_loop_until_quit

internal/backends/linuxkms/calloop_backend.rs
The event loop roughly loops like this:
loop {
update_timers_and_animations();
render();
sleep_or_dispatch_events();
}
sleep_or_dispatch_events() will wake up when we receive a queued callback from invoke_from_event_loop, and we would run the callback right away. If that callback sets animated properties, the start time for animations would be incorrect, as we haven't called update_timers_and_animations() yet.
So instead, let's keep track of any received callbacks per sleep cycle, update the animation tick, and then invoke the callbacks.
=> LinuxKMS: Fix animations using the wrong start time when invoked from invoke_from_event_loop

examples/printerdemo_old/ui/common.slint, examples/printerdemo_old/ui/printerdemo.slint
=> Fixes background on printerdemo_old

internal/compiler/widgets/common/slider-base.slint, internal/compiler/widgets/cosmic-base/slider.slint, internal/compiler/widgets/cupertino-base/slider.slint, internal/compiler/widgets/fluent-base/slider.slint, internal/compiler/widgets/material-base/slider.slint
This is also a preparation for #4233
Cannot be used in the qt style because of the native slider base element where the click / touch interaction is handles for the qt style Slider.
=> Added SliderBase and use it in non qt styles.

internal/common/builtin_structs.rs
Match the implementation :-)
Fixes #4335
=> Fix documentation of the keyboard modifiers

internal/backends/android-activity/build.rs, internal/backends/android-activity/java/SlintAndroidJavaHelper.java, internal/backends/android-activity/lib.rs, xtask/src/license_headers_check.rs
So that we can use text prediction and other input method features
This introduce a way to bundle .java code into the slint library: the code is compiled into bytecode by the build.rs and then loaded at runtime.
=> Android: keyboard interaction in java

api/rs/slint/lib.rs, internal/core/Cargo.toml, internal/core/future.rs
Discussed in https://github.com/slint-ui/slint/discussions/4377
=> Docs: explain how to use tokio futures

CHANGELOG.md, internal/compiler/widgets/common/slider-base.slint, internal/compiler/widgets/cosmic-base/slider.slint, internal/compiler/widgets/cupertino-base/slider.slint, internal/compiler/widgets/fluent-base/slider.slint, internal/compiler/widgets/material-base/slider.slint
Fixes #4233 
This also changes the behavior of `Slider`. Mouse-Left/Touch down on the bar outside the thumb adjust the value on the mouse position. Drag move only starts if the pointer is inside the thumb.
=> Change slider value on mouse up on bar

api/cpp/include/slint.h, api/rs/macros/lib.rs, api/rs/slint/private_unstable_api.rs, internal/common/builtin_structs.rs, internal/compiler/generator/rust.rs, internal/compiler/layout.rs, internal/compiler/llr/lower_expression.rs, internal/compiler/passes/compile_paths.rs
=> Rust codegen: fix compile if slint names maatches internal names

examples/gallery/Cargo.toml, examples/gallery/index.html
=> Fixed style selection in wasm gallery

internal/compiler/pathutils.rs, tools/lsp/preview.rs, tools/lsp/wasm_main.rs
Because it wouldn't take the files from the cache
=> Fix (native) preview not taking account change in other fiels than the main file

.github/workflows/cpp_package.yaml, .github/workflows/nightly_snapshot.yaml, .github/workflows/publish_npm_package.yaml, .github/workflows/slint_tool_binary.yaml, api/node/Cargo.toml
Use the same features as for the the lsp.
=> Node.js: Refine features for binary npm packages

tools/lsp/ui/draw-area.slint, tools/lsp/ui/resizer.slint
=> lsp: Use alternate background on drawing rect and set border on resizer

api/rs/slint/tests/spawn_local.rs, internal/backends/testing/lib.rs, internal/core/animations.rs, internal/core/context.rs, internal/core/future.rs, internal/core/input.rs, internal/core/items/text.rs, internal/core/lib.rs, internal/core/platform.rs, internal/core/tests.rs, internal/core/window.rs
I'm looking for a way which would allow for UI testing in different threads, and for that we need to extend the SlintContext.
This is still incomplete, and what's missing is the ability to create a Slint component with a given context.
CC #4294
=> Some more progress on SlintContext

CHANGELOG.md, api/node/__test__/eventloop.spec.mts, api/node/index.ts, api/node/src/lib.rs
=> Added runEventLoopUntilQuit for node

internal/core/graphics/brush.rs
=> Fix gradiant drawing

internal/core/graphics/brush.rs
=> Fix 90deg gradients

examples/gallery/index.html
=> Gallery demo: Pick the default style based on the user agent
