sixtyfps_compiler/passes/resolving.rs
Move typo expresion to expression
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>
=> Fix typo in sixtyfps_compiler/passes/resolving

sixtyfps_compiler/parser.rs, sixtyfps_compiler/parser/document.rs, sixtyfps_compiler/parser/expressions.rs, sixtyfps_compiler/parser/statements.rs
The actual `peek` and `nth` functions of `Parser` are a bit trick, both should return the same object since they are an index based access (`peek` == `nth(0)` IMO).
The PR changes `nth` to return `Token` (like the `peek` function) and also adds the `kind` function of `Token` to allows access of the `kind` property. The final result is a much more flexible API, where the user will be able to access `nth` `Token` object and `SyntaxKind` property, otherwise it's only possible to access the current `Token` and the `nth` `SyntaxKind`.
PS: This change is helping me a lot to develop/debug some functionalities since `Token` also derives `Debug`.
=> Improve parser API

.github/workflows/rust.yaml, api/sixtyfps-cpp/cmake/CMakeLists.txt, api/sixtyfps-cpp/docs/conf.py, xtask/src/cppdocs.rs, xtask/src/license_headers_check.rs, xtask/src/main.rs
Tear it out of the CMakeLists.txt and instead run it via
cargo xtask cppdocs
This allows the build_and_test step in the CI to only run cmake for the
library/header related bits and the docs_and_demos step to only generate
docs and not require a full host build of the library (as cargo xtask
cmake would otherwise do).
=> Make C++ documentation generation an xtask

xtask/Cargo.toml, xtask/src/license_headers_check.rs
Switch back to toml_edit for the Cargo.toml check, as that makes it easy
to also apply fixes -- the formatting is preserved.
This also removes the indirect serde_derive dependency that may be
causing problems on macOS sometimes.
Also, now that the cargo test doesn't trigger a build anymore, the use
of toml_edit here should not cause the problem mentioned in commit
ab89fcb69a78023afea368ebb0f1161cd40f43a0 anymore -- fingers crossed.
=> Rework Cargo.toml license checking

.github/workflows/ci.yaml
With a cold cache, neon-sys will be compiled as a dependency of the
nodejs buildings, which in turn will install node-gyp and run it to
build its bindings. On Windows, linkage against the nodejs import
library is needed for the correct symbol ordinals from nodejs.dll.
node-gyp takes care of downloading the header files and import library
into %HOMEPATH%\AppData\Local\node-gyp\Cache\<version>.
In a warm cache scenario, neon-sys is not rebuilt, node-gyp is not run
and the node.lib import library is not installed.
However neon-sys also propagates the path to node.lib (and the import
lib name) by parsing the node-gyp output, saving it to an environment
variable, exporting that via links=neon to neon-build and then
neon-build persists it into files its out directory. Finally we call …
=> Fix build on Windows with warm cache

.github/workflows/ci.yaml
I give up, the build failures on macOS due to the cache seem resistant to workarounds such as pinning or disabling the manual cache cleaning.
In addition one of the failures in the CI check for this PR surfaced the issue that the node-gyp cache may not be populated fully, so this also includes a commit to ensure that it is populated.
=> Fix cache build issues on macOS

examples/memory/memory.60
Using row and column count properties improves the readability, extensibility, and maintainability by removing the magic numbers for the other calculated properties. Previously, it took me some time to understand what these numbers represented and this change should remove this difficulty.
As this is a non-breaking refactor, the game still appears the same:
=> Update memory example to use row and column count properties

sixtyfps_compiler/widgets/ugly/sixtyfps_widgets.60
Currently, Printer Demo allows you to print -1 copies. This is a fix.
=> Add minimum to SpinBox

CHANGELOG.md, Cargo.toml, docs/builtin_elements.md, examples/iot-dashboard/iot-dashboard.60, examples/slide_puzzle/slide_puzzle.60, sixtyfps_compiler/builtins.60, sixtyfps_compiler/typeregister.rs, sixtyfps_runtime/corelib/Cargo.toml, sixtyfps_runtime/rendering_backends/gl/Cargo.toml, sixtyfps_runtime/rendering_backends/gl/images.rs, sixtyfps_runtime/rendering_backends/gl/lib.rs, tests/cases/examples/box_shadow_use.60, tools/syntax_updater/from_0_0_6.rs
This replaces the box gradient with a new implementation that
behaves like the HTML Canvas element, by applying a gaussian
blur to the alpha of the rectangle to shadow.
The drop-shadow-blur property is changed to be now just a "level", like
the HTML Canvas shadowBlur property, which is defined to be half of the
standard deviation of the gaussian blur to be applied.
=> GL backend: new box drop shadow implementation

sixtyfps_runtime/rendering_backends/gl/graphics_window.rs
This issue is not quite specific to the gallery, a simpler test case is
this:
```
App := Window {
preferred-width: 500px;
preferred-height: 750px;
HorizontalLayout {
Rectangle {
background: blue;
}
}
}
```
As there is no fixed width/height set, the size is calculated by layout and
apply_window_properties() sets the inner size correctly on the winit window.
However the width/height properties on the root Window item are not set, remain
zero and thus lead to incorrect rendering. They are not set because they are
identical with what window.inner_size() reports - we assume no change and that
they are in sync.
The bug however is in the creation phase, when we decide on an initial size to
pass to the window_builder, we should also set those on the root item. This is
where window.inner_size() …
=> Fix initial rendering of widget gallery with GL backend

sixtyfps_runtime/corelib/graphics.rs, sixtyfps_runtime/corelib/items/text.rs, sixtyfps_runtime/rendering_backends/gl/fonts.rs, sixtyfps_runtime/rendering_backends/qt/qt_window.rs, sixtyfps_runtime/rendering_backends/testing/lib.rs, tests/cases/layout/text_preferred_size.60
When a Text element has wrapping enabled, it should not have zero
minimum size. Otherwise the layout will give it a height of zero in the
layout in the test case and that'll make the text disappear. There are
different options but this patch goes for minimum height as if no
wrapping was enabled (so at least one line plus forced line breaks).
Fixes #246
=> Fix disappearing text in vertical layouts with word-wrap and alignment

api/sixtyfps-cpp/include/sixtyfps_image.h, api/sixtyfps-cpp/tests/datastructures.cpp, sixtyfps_runtime/corelib/backend.rs, sixtyfps_runtime/corelib/graphics.rs, sixtyfps_runtime/corelib/graphics/image.rs, sixtyfps_runtime/corelib/items/image.rs, sixtyfps_runtime/corelib/lib.rs, sixtyfps_runtime/corelib/window.rs, sixtyfps_runtime/rendering_backends/gl/graphics_window.rs, sixtyfps_runtime/rendering_backends/gl/images.rs, sixtyfps_runtime/rendering_backends/gl/lib.rs, sixtyfps_runtime/rendering_backends/qt/lib.rs, sixtyfps_runtime/rendering_backends/qt/qt_window.rs, sixtyfps_runtime/rendering_backends/testing/lib.rs, xtask/src/cbindgen.rs
This requires the image size query to be window independent and go
through the backend instead.
This implies minor changes for the Qt backend and bigger ones for the GL
backend:
* There exists now a thread-local IMAGE_CACHE, which is used by the
backend's image_size() function as well as by the renderer for
loading CPU side images.
* The image remain as decoded images in there (including SVG tree)
and the window now has a texture_cache, which holds CachedImage
with ImageData::Texture.
* Rendering an image item therefore fetches the CPU side image,
calls upload_to_gpu() on it, which creates a new Rc<CachedImage>
and that's stored in the texture_cache.
* The texture cache continues to be pruned when hiding the window.
=> Add Image::size()

sixtyfps_runtime/interpreter/dynamic_component.rs
Binding expressions may end up calling sixtyfps::Image:size(), which
requires a graphics backend to be set.
The wasm interpreter code path circumvented the sixtyfps_corelib::backend::instance_or_init
call and went straight to the GL backend.
This patch re-introduces the usual routing through the default backend.
=> Fix panic in preview.html when loading images

sixtyfps_runtime/rendering_backends/gl/lib.rs, sixtyfps_runtime/rendering_backends/qt/qt_window.rs
In this case, the last line will have elipsis on the last line
when no more line can be printed
Note that the behavior is different with the Qt backend
=> GL backend: elide Text also when word-wrapping

sixtyfps_compiler/passes/remove_aliases.rs
Clippy says this code is fishy: This is dropping a reference, which does nothing.
So this code should be strictly identical to what has been there before. I am not sure this is what you intended to have though!
=> Dropping a reference does nothing

sixtyfps_compiler/passes/resolving.rs
In this case this feels at controversial, but in general I find this
clippy lint pretty helpful: It has caught several copy-paste errors
before.
No behavior change is intended with this patch.
=> Janitor: Fix clippy::if_same_then_else error

api/sixtyfps-rs/sixtyfps-macros/lib.rs, helper_crates/const-field-offset/src/lib.rs, sixtyfps_compiler/generator/cpp.rs
Mark up some special words in documents (like C++ lingo in rust files).
=> Janitor: CSpell fixes

sixtyfps_runtime/corelib/graphics/color.rs
This is a code change, but it should not change behavior.
=> Janitor: Fix clippy error about f32 comparison

sixtyfps_compiler/expression_tree.rs, sixtyfps_compiler/generator/rust.rs, sixtyfps_compiler/langtype.rs, sixtyfps_compiler/layout.rs, sixtyfps_compiler/lib.rs, sixtyfps_compiler/lookup.rs, sixtyfps_compiler/object_tree.rs, sixtyfps_compiler/parser.rs, sixtyfps_compiler/passes/apply_default_properties_from_style.rs, sixtyfps_compiler/passes/binding_analysis.rs, sixtyfps_compiler/passes/clip.rs, sixtyfps_compiler/passes/collect_globals.rs, sixtyfps_compiler/passes/collect_structs.rs, sixtyfps_compiler/passes/deduplicate_property_read.rs, sixtyfps_compiler/passes/flickable.rs, sixtyfps_compiler/passes/generate_item_indices.rs, sixtyfps_compiler/passes/inlining.rs, sixtyfps_compiler/passes/lower_layout.rs, sixtyfps_compiler/passes/lower_shadows.rs, sixtyfps_compiler/passes/remove_aliases.rs, sixtyfps_compiler/passes/repeater_component.rs, sixtyfps_compiler/passes/resolve_native_classes.rs, sixtyfps_compiler/passes/transform_and_opacity.rs, sixtyfps_compiler/passes/z_order.rs, sixtyfps_compiler/typeloader.rs, sixtyfps_runtime/corelib/graphics/image.rs, sixtyfps_runtime/corelib/window.rs
This is a big one touching a lot of files, removing some stray `&` all over the place.
=> Janitor: Remove unnecessary `&`

api/sixtyfps-node/native/lib.rs, api/sixtyfps-rs/sixtyfps-build/lib.rs, api/sixtyfps-wasm-interpreter/src/lib.rs, sixtyfps_runtime/interpreter/api.rs, sixtyfps_runtime/interpreter/ffi.rs, sixtyfps_runtime/interpreter/lib.rs, sixtyfps_runtime/interpreter/tests.rs, tests/doctests/main.rs, tests/driver/interpreter/interpreter.rs, tools/lsp/preview.rs, tools/viewer/main.rs
The detault trait impl instead of `new()` patch separated out of the latest janitor patch set.
=> Use `impl Default` instead of `new()` constructors

sixtyfps_runtime/rendering_backends/gl/Cargo.toml
It's not needed and this would fix #315
=> Remove the freetype dependency on Windows and macOS

sixtyfps_compiler/generator/rust.rs
On Windows the default stack size is less than on Linux/macOS and
therefore an issues surfaces that is however operating system agnostic:
Due to inlining we generate quite big inner components with many fields.
Their field offsets are accumulated in the separate FIELD_OFFSETS
struct. The access pattern typically looks like this:
Self::FIELD_OFFSETS.some_field.apply_pin(...)
This is destructed into at least two smaller operations, fetching
some_field and then calling apply_pin with that field as self parameter.
In Rust debug builds the first operation, unfortunately, ends up making
a full copy of Self::FIELD_OFFSETS into a temporary variable on the
stack. Unfortunately also that stack space isn't reused, so every access
results in a new stack allocation to hold all of the FIELD_OFFSETS …
=> Fix stack overflow with Rust generated code in debug builds on Windows

CHANGELOG.md, sixtyfps_runtime/corelib/items/text.rs, tests/cases/text/text_change.60
When replacing the text, it may happen that the cursor position becomes outdated.
As per #331 we should make sure that this is handled also on an API level,
but this patch at least avoids the panic triggered by using editing.
=> Fix panic when editing text after programmatically replacing it

docs/development.md
The link to the blog post previously pointed to the root of the repo's docs folder.
=> updated erroneous link

CHANGELOG.md, api/sixtyfps-node/native/js_model.rs, sixtyfps_runtime/corelib/model.rs, sixtyfps_runtime/interpreter/value_model.rs
This should help to get back the original model from the component.
For example, it will remove the need in this hack to use a thread local 
https://github.com/sixtyfpsui/cargo-ui/blob/cefb0b2bca658290c0b27d9cff48e365c3dfbebc/src/main.rs#L101
because we can just get the model back from the component and downcast it to the right value.
=> Add a as_any to the Model trait to allow getting a reference to the original model

sixtyfps_runtime/rendering_backends/gl/graphics_window.rs, sixtyfps_runtime/rendering_backends/gl/images.rs
I had to change a bit  the internal image API to avoid copying too much.
=> GL backend: Use the cache for the Window icon

sixtyfps_compiler/builtins.60, sixtyfps_runtime/corelib/items.rs, sixtyfps_runtime/corelib/window.rs, sixtyfps_runtime/interpreter/dynamic_component.rs, sixtyfps_runtime/rendering_backends/gl/graphics_window.rs, sixtyfps_runtime/rendering_backends/qt/qt_window.rs, sixtyfps_runtime/rendering_backends/testing/lib.rs, xtask/src/cbindgen.rs
If we were to add `sixtyfps::window::Window` to the re_exports, then
this clashes. We might rename the former, but this is a cleaner naming
in any case.
Relates to #333
=> Rename the implementation of the `Window` item to `WindowItem`

api/sixtyfps-cpp/lib.rs, api/sixtyfps-rs/lib.rs, sixtyfps_compiler/generator/rust.rs, sixtyfps_runtime/corelib/backend.rs, sixtyfps_runtime/corelib/items.rs, sixtyfps_runtime/corelib/items/text.rs, sixtyfps_runtime/corelib/tests.rs, sixtyfps_runtime/corelib/window.rs, sixtyfps_runtime/interpreter/api.rs, sixtyfps_runtime/interpreter/dynamic_component.rs, sixtyfps_runtime/interpreter/eval.rs, sixtyfps_runtime/interpreter/eval_layout.rs, sixtyfps_runtime/interpreter/ffi.rs, sixtyfps_runtime/rendering_backends/gl/graphics_window.rs, sixtyfps_runtime/rendering_backends/gl/lib.rs, sixtyfps_runtime/rendering_backends/qt/lib.rs, sixtyfps_runtime/rendering_backends/qt/qt_window.rs, sixtyfps_runtime/rendering_backends/testing/lib.rs
This reduces the API surface of ComponentWindow, so that we can rename it to `sixtyfps::Window` for example.
=> window api cleanup

sixtyfps_runtime/rendering_backends/qt/qt_window.rs
Sorry, I broke the float comparison fix earlier. I only noticed when going over the patch again once you had spotted the same issue in a different place already (and fixed it there before merging).
Amends 02bdcbf6fffa38a822ecebcc84e16ad1be92c46e
=> Fix float comparison in qt_window.rs

CHANGELOG.md, api/sixtyfps-cpp/docs/types.md, api/sixtyfps-cpp/tests/interpreter.cpp, api/sixtyfps-node/README.md, api/sixtyfps-rs/lib.rs, sixtyfps_compiler/expression_tree.rs, sixtyfps_compiler/langtype.rs, sixtyfps_compiler/object_tree.rs, sixtyfps_compiler/tests/syntax/basic/arithmetic_op.60, tests/cases/types/angles.60
One of the commit fix the angle conversion.
The other sets of commit make public than angle and duration in the public API.
Rationale for making the duration public is that we document that it is converted to i64 and that it is the number of millisecond
An argument against making it public is that one would want to use some Rust or C++ duration type instead.
Similarly, should we make angle properties public?
=> Fix angles conversion and allow angle and duration in the public API

CHANGELOG.md, api/sixtyfps-rs/sixtyfps-build/lib.rs, api/sixtyfps-rs/sixtyfps-macros/build.rs, api/sixtyfps-rs/sixtyfps-macros/lib.rs, sixtyfps_runtime/rendering_backends/default/build.rs, sixtyfps_runtime/rendering_backends/qt/Cargo.toml, sixtyfps_runtime/rendering_backends/qt/build.rs
This requires some gymnastics to get right as the information
need to be passed to the compiler despite having no direct dependency
between the compiler and the runtime or backends.
So use a file in the build directory to tell the default style
cc: #83
=> Rust: defaults to the `native` style when Qt is available

sixtyfps_compiler/passes/lower_layout.rs, sixtyfps_compiler/tests/syntax/layout/if_in_grid.60
An early error is better than a build error at compile time of generated code.
Fixes #349
=> Produce an error message when using if or for in grid layouts

api/sixtyfps-rs/lib.rs, sixtyfps_compiler/generator/rust.rs
Further build on b3529d1b75b9e8f970ecc17e16037d80e11385be and move the
strong/weak reference dance into the API crate out of the generated
code.
Saves ~21k llvm lines on the printer demo (debug).
It's also possible to move the as_pin_ref() bit, but that didn't
really give any savings overall.
=> Another minor reduction in generated code

sixtyfps_runtime/corelib/Cargo.toml, sixtyfps_runtime/corelib/items/text.rs, sixtyfps_runtime/rendering_backends/gl/lib.rs, tests/cases/text/cursor_move_grapheme.60
The cursor navigation left/right (and subsequently text selection) needs
to respect grapheme boundaries. Since we already depend on the
unicode-segmentation crate through femtovg, we might as well use the
functionality for determining grapheme boundaries from there.
The only place where the cursor navigation is allowed to break that is
when using backspace, as that allows the user to break glyph clusters.
Along the same lines, this merge request also includes a fix for rendering text
selections when using combining characters, where the shaper may use
one glyph to represent multiple characters and therefore our attempt to finding
a glyph for the selection end may fail.
=> Fix cursor navigation and text selection rendering when using combining characters

docs/builtin_elements.md
This makes the example a bit more useful out of the box,
at least to let the user know that this property exists.
=> Mention forward-focus in the FocusScope example

sixtyfps_compiler/expression_tree.rs, sixtyfps_compiler/object_tree.rs, sixtyfps_compiler/passes/apply_default_properties_from_style.rs, sixtyfps_compiler/passes/default_geometry.rs, sixtyfps_compiler/passes/move_declarations.rs, tests/cases/bindings/animated_default_geometry.60
When an element gets its width and height from the parent through an implicit 100% binding,
those bindings were missing when an animation was pre-defined.
The provided new-type wrapper offers a function to deal with replacing just
binding expression, instead of the
expression *and* the animation.
Fixes #376
=> Fix disappearing elements with implicit width/height

sixtyfps_compiler/generator/rust.rs
When setting a constant, we only need to use a closure for the
expression if it contains a return statement.
This saves about ~14000 llvm lines for a debug build of the printer
demo.
=> Minor reduction in generated Rust code (llvm lines)

api/sixtyfps-cpp/docs/generated_code.md, api/sixtyfps-cpp/include/sixtyfps.h, api/sixtyfps-cpp/include/sixtyfps_interpreter.h, api/sixtyfps-cpp/include/sixtyfps_testing.h, api/sixtyfps-cpp/include/vtable.h, api/sixtyfps-node/lib/index.ts, api/sixtyfps-node/native/lib.rs, api/sixtyfps-rs/docs.rs, api/sixtyfps-rs/lib.rs, cspell.json, sixtyfps_compiler/generator/cpp.rs, sixtyfps_compiler/generator/rust.rs, sixtyfps_runtime/corelib/items.rs, sixtyfps_runtime/corelib/items/text.rs, sixtyfps_runtime/corelib/tests.rs, sixtyfps_runtime/corelib/window.rs, sixtyfps_runtime/interpreter/api.rs, sixtyfps_runtime/interpreter/dynamic_component.rs, sixtyfps_runtime/interpreter/eval.rs, sixtyfps_runtime/interpreter/eval_layout.rs, sixtyfps_runtime/interpreter/ffi.rs, sixtyfps_runtime/rendering_backends/qt/qt_window.rs, tests/cases/types/length.60, tools/lsp/preview.rs, tools/viewer/main.rs
The generated component now provides access to a Window type
via the window() accessor function.
This is part of #333
=> Start a new sixtyfps::Window API for Rust, C++, the interpreters and JS

CHANGELOG.md, sixtyfps_runtime/corelib/sharedvector.rs
* In capacity_for_grow, don't compare the number of elements
(current_cap) with the size of an element in bytes.
That fixes the capacity not growing.
* When re-allocating due to growth and copying elements from the old
inner to the new inner, make sure to copy all old elements from the beginning,
not only the last element repeatedly.
=> Fix SharedVector creation from iterators with default size hints

.github/workflows/ci.yaml, sixtyfps_runtime/corelib/Cargo.toml
Use the external docs rustdoc feature to link to the rgb docs on docs.rs.
=> Fix links to rgb crate in the sixtyfps.io hosted online docs

docs/tutorial/rust/src/running_in_a_browser.md
in the section to run the tutorial in the browser with wasm, the <html> opening tag is missing for the stub webpage
=> add missing opening html tag in the rust tutorial

sixtyfps_compiler/expression_tree.rs, sixtyfps_compiler/generator/cpp.rs, sixtyfps_compiler/generator/rust.rs, sixtyfps_compiler/passes/repeater_component.rs, tests/cases/crashes/issue_422_enclosing_component.60
When trying to reference an instance of a repeated item, for use with
ItemRc or VRef<Item>, the item_index (or id) of the ElementRc is not
directly what we want.
For the Rust and C++ code generators, the self/_self already refers
correctly to the repeated instance, but item_index must be zero to refer
to the root.
For the interpreter the self equivalent is the
local_context.component_instance is already the repeated instance that
we can use, and we're just looking for the root element of that, in
order to create the ItemRc/VRef.
Fixes #422
=> Fix panic when calling focus() on a repeated element

sixtyfps_compiler/expression_tree.rs, sixtyfps_compiler/generator.rs, sixtyfps_compiler/generator/cpp.rs, sixtyfps_compiler/generator/rust.rs, sixtyfps_compiler/object_tree.rs, sixtyfps_compiler/passes/binding_analysis.rs, sixtyfps_compiler/passes/clip.rs, sixtyfps_compiler/passes/deduplicate_property_read.rs, sixtyfps_compiler/passes/ensure_window.rs, sixtyfps_compiler/passes/flickable.rs, sixtyfps_compiler/passes/infer_aliases_types.rs, sixtyfps_compiler/passes/inlining.rs, sixtyfps_compiler/passes/lower_states.rs, sixtyfps_compiler/passes/lower_tabwidget.rs, sixtyfps_compiler/passes/materialize_fake_properties.rs, sixtyfps_compiler/passes/remove_aliases.rs, sixtyfps_compiler/passes/resolving.rs, sixtyfps_compiler/passes/transform_and_opacity.rs, sixtyfps_runtime/interpreter/dynamic_component.rs, sixtyfps_runtime/interpreter/eval.rs
Don't put them in a fake expression.
This simplifies a bit the expression handling, and will make
possible to fix analysis that needs a vew into the aliases
=> Refactor the way the two-ways biding are represented internaly

CHANGELOG.md, docs/builtin_elements.md, sixtyfps_compiler/builtins.60, sixtyfps_compiler/passes/apply_default_properties_from_style.rs, sixtyfps_compiler/widgets/fluent/sixtyfps_widgets.60, sixtyfps_compiler/widgets/ugly/sixtyfps_widgets.60, sixtyfps_runtime/rendering_backends/qt/qt_widgets.rs
We apply a default window background from the palette to all `Window`
elements, and likewise we need to apply the default text color to Text
elements to ensure a readable contrast.
=> Fix default text color when using Qt/native style in dark mode on macOS

sixtyfps_runtime/rendering_backends/gl/event_loop.rs, sixtyfps_runtime/rendering_backends/gl/graphics_window.rs, sixtyfps_runtime/rendering_backends/qt/qt_window.rs
Under these windowing systems, we receive a QString text from Qt that
contains a terminal control character (like \u{3} for ctrl+c). We
decided to supply the character for the key (for example 'c' for Ctrl+C)
to the application, so activate the conversion from the key code when
control characters are present.
With winit, we receive first a key down input event with the virtual key
code (for example C for Ctrl+C), followed by a ReceivedCharacter event
with a terminal control character. We choose to ignore that and instead
take the previously received key code and try to use that instead.
Fixes #441
=> Fix key events the control modifier on Windows, X11 and Wayland

sixtyfps_compiler/generator/cpp.rs, sixtyfps_compiler/generator/rust.rs, sixtyfps_compiler/object_tree.rs, sixtyfps_compiler/passes.rs, sixtyfps_compiler/passes/check_public_api.rs, sixtyfps_compiler/passes/unique_id.rs, sixtyfps_runtime/interpreter/api.rs, sixtyfps_runtime/interpreter/dynamic_component.rs, sixtyfps_runtime/interpreter/global_component.rs, tests/cases/globals/global_alias.60
When exporting an global multiple times under different names, make sure
that they alias in the generated code.
As a consequence, the compiler maintains the original unique name and in
Rust and C++ makes only the exported names public. In the interpreter
the internal name is theoretically still accessible from the outside.
=> Add support for global aliases

sixtyfps_runtime/rendering_backends/gl/graphics_window.rs, sixtyfps_runtime/rendering_backends/gl/images.rs, sixtyfps_runtime/rendering_backends/gl/lib.rs
Remove GLRenderer and GLRendererData. Most of the fields fold nicely
into the MappedWindow.
=> Clean up GL backend code

sixtyfps_runtime/rendering_backends/gl/fonts.rs, sixtyfps_runtime/rendering_backends/gl/graphics_window.rs, sixtyfps_runtime/rendering_backends/gl/lib.rs
We can use the non-canvas bound TextContext and need the canvas only
in the closure when painting.
=> Internal cleanup: Remove canvas dependency from text layout code

CHANGELOG.md, Cargo.toml, docs/builtin_elements.md, sixtyfps_compiler/builtins.60, sixtyfps_compiler/typeregister.rs, sixtyfps_runtime/corelib/items/image.rs, sixtyfps_runtime/corelib/rtti.rs, sixtyfps_runtime/interpreter/api.rs, sixtyfps_runtime/rendering_backends/gl/images.rs, sixtyfps_runtime/rendering_backends/gl/lib.rs, tests/cases/examples/image_rendering.60
Like CSS image-rendering it has "smooth" and "pixelated" options. Only OpenGL has been tested right now, have not tested WASM or Qt. Right now the first instance of a `@image-url()` will set the scaling for that specific image. The same image used from memory on the otherhand can all have a different scaling property.
Still need to update documentation, but I wanted to get other backends working, possibly fix the image-url issue, and ask if there is a better way to implement this first.
=> Add image-scaling property to Images to control how they are scaled

api/sixtyfps-node/native/Cargo.toml, api/sixtyfps-node/native/lib.rs, sixtyfps_runtime/interpreter/Cargo.toml, sixtyfps_runtime/interpreter/tests.rs, tests/driver/nodejs/Cargo.toml, tests/driver/nodejs/nodejs.rs
In the CI we set SIXTYFPS_NO_QT=1 and this change removes the testing
backend from the nodejs tests, in order to fix #419 .
=> Use the GL backend in the CI for node tests

docs/langref.md, sixtyfps_compiler/parser/element.rs, sixtyfps_compiler/tests/syntax/lookup/if.60, sixtyfps_compiler/tests/syntax/parse_error/if0.60, sixtyfps_compiler/tests/syntax/parse_error/if1.60, sixtyfps_compiler/tests/syntax/parse_error/if3.60, sixtyfps_compiler/tests/syntax/parse_error/if4.60
closes #466
Note: this does not change the `if` expression
=> Parser: make the parentheses around `if` element optional

sixtyfps_compiler/widgets/common/common.60
A simple demonstrative test-case like
```
export App := Window {
VerticalBox {
LineEdit {
placeholder-text: "Enter your name here";
}
Button {
text: "Submit";
}
}
}
```
would not be wide enough - the place holder text would not be visible.
=> Fix minimum size of line edit with placeholder text

api/sixtyfps-cpp/include/sixtyfps.h, sixtyfps_compiler/generator/cpp.rs, sixtyfps_compiler/generator/rust.rs, sixtyfps_runtime/corelib/layout.rs, tests/cases/crashes/layout_deleted_item.60
This can be reproduced by deleting the last item of the printer queue in the
printer demo.
It is a regression showing up because we now emit the MouseExit event after
the mouse grab as released.
The problem is that we upgrade the weak item, and call geometry() on it.
Calling geometry will re-evaluate the layout cache which will re-evaluate
the model which will result in the component being removed and the cache
entry having less item than expected.
It is ok to simply return 0. for these layout location since the item will
disapear anyway.
=> Fix panic when trying to access layout cache of destroyed items

api/sixtyfps-cpp/CMakeLists.txt, api/sixtyfps-cpp/Cargo.toml, sixtyfps_runtime/interpreter/Cargo.toml, sixtyfps_runtime/rendering_backends/default/Cargo.toml
Even if SIXTYFPS_BACKEND_GL is set to OFF, we would default to enabling
X11, which translates to enabling the x11 feature, which in turn
implicitly activates the GL backend. In addition, the interpreter Rust
API crate also enables the GL backend in its defeaults.
In order to make it possible to turn off the GL backend, three changes are necessary:
* The default backend no more selects a default :-). Instead the Rust
API crate, Rust interpreter API crate and the CMake project define
the same features and defaults.
* The C++ crate depends on the interpreter without its defaults (which enable GL)
* In CMake the X11 and Wayland features become dependent options, that
are only show in the CMake configure UI if the GL backend is enabled.
This way a GL-disabled build won't also pass --features …
=> Make it possible to disable the GL backend in the CMake build

CHANGELOG.md, sixtyfps_compiler/diagnostics.rs, sixtyfps_runtime/interpreter/api.rs, tools/compiler/main.rs, tools/viewer/main.rs
=> Allow the sixtyfps-compiler and sixtyfps-viewer to read from stdin

docs/builtin_elements.md, tools/lsp/sublime/SixtyFPS.sublime-syntax
Also includes a minor doc fix.
=> LSP Sublime Text: Fix '%YAML indicator is required'

.gitignore, CHANGELOG.md, CMakeLists.txt, api/sixtyfps-cpp/CMakeLists.txt, api/sixtyfps-cpp/Cargo.toml, api/sixtyfps-cpp/README.md, api/sixtyfps-cpp/build.rs, api/sixtyfps-cpp/cbindgen.rs, api/sixtyfps-cpp/docs/cmake.md, api/sixtyfps-cpp/docs/getting_started.md, docs/building.md, docs/tutorial/cpp/src/getting_started.md, examples/memory/CMakeLists.txt, tests/driver/cpp/Cargo.toml, tests/driver/cpp/build.rs, xtask/Cargo.toml, xtask/src/main.rs
This first bumps the cmake version and then moves the cbindgen xtask into sixtyfps-cpp's build.rs.
The CMake bump could - in theory - be omitted, but short of the ability to forward environment variables to the corrosion build, we would have to generate header files in the source directory, which is also a kind of boo-boo :)
=> Rewrite build system part of C++ header file generation

sixtyfps_runtime/rendering_backends/gl/Cargo.toml, sixtyfps_runtime/rendering_backends/gl/fonts.rs
This version doesn't require the change to fontdb yet, but uses the new
femtovg API to allow feeding in shared (mmapped) font data. On macOS
this saves 4-5 MB of ram just for the gallery, on my default Ubuntu it's
roughly ~40MB.
=> Initial support for mmapping fonts directly into femtovg

sixtyfps_runtime/rendering_backends/gl/Cargo.toml, sixtyfps_runtime/rendering_backends/gl/lib.rs
We default to querying GlLatest from glutin, which might run into a code
path in glutin's `bind_and_get_api` in `egl/mod.rs` that will return
None as version and pass that to `choose_fbconfig`. That function will
panic with unimplemented() if the bound API is GLES, because we need to
know which version of GLES. The bound API in turn might be GLES if
desktop GL is not supported.
To accomodate for this situation, this patch changes the GL context
creation logic to first try explicitly GLES 2.0 and then fall back to
the GlLatest variants.
In addition this pulls in a newer version of femtovg to fix FBO
rendering with stencil with GLES 2.0.
=> Fix support for OpenGL ES 2.0

sixtyfps_compiler/passes/lower_layout.rs, sixtyfps_compiler/tests/syntax/basic/dialog.60, sixtyfps_compiler/tests/syntax/basic/dialog2.60
Replace "should" with "must"/"can only" to emphasize that this is an error.
=> Tweak dialog error messages

sixtyfps_runtime/rendering_backends/gl/Cargo.toml, sixtyfps_runtime/rendering_backends/gl/fonts.rs, sixtyfps_runtime/rendering_backends/gl/svg.rs
It works with the Qt backend, and it should work with the GL backend as
well. usvg supports it, uses the same underlying shaper and the API even
allows sharing the font database.
=> GL backend: Fix rendering of SVGs with text inside

sixtyfps_runtime/corelib/backend.rs, sixtyfps_runtime/rendering_backends/gl/Cargo.toml, sixtyfps_runtime/rendering_backends/gl/fonts.rs, sixtyfps_runtime/rendering_backends/gl/lib.rs, sixtyfps_runtime/rendering_backends/qt/lib.rs, sixtyfps_runtime/rendering_backends/testing/lib.rs
Use the new fontdb API:
* When registering embedded fonts, we don't need to make a copy of the
embedded font data anymore.
* We don't have to mmap the font files ourselves anymore, fontdb can
do this now for us.
=> Further speed up font handling in the GL backend

CHANGELOG.md, sixtyfps_runtime/corelib/backend.rs, sixtyfps_runtime/rendering_backends/gl/event_loop.rs
When processing window specific events, or generally when accessing
the ALL_WINDOWS refcell, keep the time for borrow to an absolute
miniumum. That way any subsequent method calls may further acquire the
refcell.
This patch re-organizes the entire deeply nested window event handling
in a function with slightly less indentation.
Fixes a panic when calling hide on a Window from within a callback
handler.
Fixes #539
=> Fix granularity of run-time borrows in GL backend window handling

CHANGELOG.md, sixtyfps_compiler/passes/check_expressions.rs, sixtyfps_compiler/passes/resolving.rs, sixtyfps_compiler/tests/syntax/lookup/callback_not_called.60, sixtyfps_compiler/tests/syntax/lookup/signal_arg.60
While before it was silently ignored or caused error in the generated code.
Fixes #542
=> Hard error when not calling a callback

.github/workflows/ci.yaml, api/sixtyfps-cpp/include/sixtyfps.h, api/sixtyfps-cpp/include/sixtyfps_image.h, api/sixtyfps-cpp/lib.rs, sixtyfps_compiler/generator/cpp.rs
This allows compiling with SIXTYFPS_EMBED_RESOURCES=true and
images/fonts are embedded as inline variables.
Generated data is emitted into the header file as
inline uint8_t sfps_embedded_resources_123[789] = {
0x1, 0x2, 0x3,
};
=> Add support for embedding data in generated C++ code

tools/viewer/main.rs
The options in sixtyfps-viewer --help used to look like this:
```
OPTIONS:
--backend <backend>                         The rendering backend [default: ]
-I <include path for other .60 files>...
--load-data <load data file>                Load properties from a json file ('-' for stdin)
--save-data <save data file>                Store properties values in a json file at exit ('-' for stdout)
--style <style name>                        The style name ('native', 'fluent', or 'ugly') [default: ]
```
This patch removes the useless "[default: ]" part. These are options,
so even without this text it should be very obvious that the `--style`
and the `--backend` parameters are indeed optional.
=> viewer: Prettify help output

sixtyfps_compiler/generator.rs, sixtyfps_compiler/generator/cpp.rs, sixtyfps_compiler/object_tree.rs, sixtyfps_compiler/passes/generate_item_indices.rs, tests/cases/subcomponents/repeaters.60
For the following reduced test-case the order in how the dynamic nodes
in the item tree were generated (and dyn indices assigned) differed from
the way the visit_dynamic_children slots were generated:
```
Blah := Rectangle {
for x in 1: Text {
text: "Should be on the right";
}
}
MainWindow := Window {
width: 772px;
height: 504px;
Text {
if (false): TouchArea {
}
}
Blah {
x: 200px;
}
}
```
The item tree node was constructed using build_item_tree, which
basically assigned dyn index 0 to the "repater" for the touch area
and "1" to the one for the repeater inside the sub-component.
Afterwards we traversed the element tree - without descending into the
sub-components - to generate the fields and the dispatch in in the
dynamic visitor. Here a subtle order would result in a mismatch of
indices: …
=> Fix the C++ printer demo with disabled inline

api/sixtyfps-cpp/CMakeLists.txt
Let cmake perform the version check. FindRust.cmake already uses VERSION_VAR
and therefore is versioned.
cc #622
=> Check the Rust version when using corrosion

api/sixtyfps-rs/README.md
Another option would be to spell out an entire policy, like this](https://github.com/BurntSushi/byteorder/commit/663358f9d29bddadc1a8e84290ec96925f2cb851). 
I'm fine with just the version, but happy to adjust this merge requests to include policy text like that if that's preferred.
=> Document MSRV in the crate README

sixtyfps_runtime/corelib/input.rs, sixtyfps_runtime/rendering_backends/gl/event_loop.rs
Treating the Tab key as text disallows handling Shift-Tab because
the shift modifier will not be passed down. This patch makes the
handling of Tab analogous to Escape, Return and other non-text
keycodes.
=> Allow handling Shift-Tab

sixtyfps_runtime/rendering_backends/qt/build.rs
Without doing this, I got this error when compiling "backend-qt":
```
lib.rs(257): warning C4458: declaration of 'fnbox' hides class member
lib.rs(241): note: see declaration of 'EventHolder::fnbox'
qt_widgets\listviewitem.rs(108): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the filein Unicode format to prevent data loss
qt_window.rs(526): error C2001: newline in constant
qt_window.rs(527): error C2146: syntax error: missing ')' before identifier 'elided'
qt_window.rs(527): error C2146: syntax error: missing ';' before identifier 'elided'
exit code: 2
```
Because there is a `QStringView(u"…")` in "qt_window.rs", in Microsoft [documents](https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-chara …
=> Make sure MSVC is using utf-8, so that compiling `u"string"` won't cause error on other codepage.

sixtyfps_compiler/parser/expressions.rs
Just remove the variant with the unserscore: Using it triggers a debug_assert down
the line, so it does not seem to be used in the wild:-)
=> compilerlib: Fix an assert triggered by linear_gradient

api/sixtyfps-cpp/CMakeLists.txt
We bundle Qt and Qt needs the VC runtime DLLs. There are two options:
Find and locate vcredist.exe, include it in the NSIS installer and run
it. Alternatively, a cmake module exists to locates the DLLs and
install them.
This patch uses the latter option, for simplicity. When upstream ticket
https://gitlab.kitware.com/cmake/cmake/-/issues/17725 is implemented, we
could switch to the first option.
Note: This might include a few DLLs that Qt probably doesn't
need.
=> Include the VS runtime dlls in the binary package

docs/tutorial/rust/src/memory_tile.md
Fixes #665 
Update the rust memory-tile tutorial to reflect where @image-url looks for files to be relative to the same folder as the .60 file
=> Fix the description of where @image-url looks for files

sixtyfps_compiler/generator/rust.rs
After commit becb4574c12cbabfe282983e256e52253fe79999 we'll
make sure not to set the plugin application attribute when initializing
the Qt backend. Unfortunately in the generated struct the NativeStyleMetrics field
is placed and initialized before the m_window. The Default::default() impl
calls `ensure_initialized()` with `from_qt_backend = false` because we don't
know what backend is being used. Since due to the ordering this is the first
call to `ensure_initialized()`, we'll end up setting the plugin application
attribute.
This patch fixes that by ensuring that the m_window field always comes first,
which is initialized with a call into the run-time library, which in turn
delegates to the backend. That'll be the Qt backend and we'll initialize
the application object correctly.
=> Fix text rendered blurry when using Qt

sixtyfps_compiler/generator/cpp.rs, sixtyfps_compiler/generator/rust.rs, tests/cases/imports/duplicated_name.60
This is a regression because of non-inlining discovered by the new "crater" test
=> Rename the sub component id to avoid error in the generated code with duplicated names

sixtyfps_compiler/layout.rs, tests/cases/layout/override_from_parent.60
We were comparing the priorities of different component, which does
not make sense
This is a regression found with the crater run
=> Fix regression when overriding the with of a Component that specifies limits

sixtyfps_runtime/corelib/Cargo.toml, sixtyfps_runtime/corelib/animations.rs, sixtyfps_runtime/corelib/backend.rs, sixtyfps_runtime/corelib/flickable.rs, sixtyfps_runtime/corelib/tests.rs, sixtyfps_runtime/corelib/timers.rs, sixtyfps_runtime/rendering_backends/gl/event_loop.rs, sixtyfps_runtime/rendering_backends/qt/qt_window.rs
When building with no_std, the backend can seed the Instant wrapper and
provide updates to it.
=> Make it possible to delegate the timer handling to the backend

sixtyfps_compiler/generator.rs, sixtyfps_compiler/generator/rust.rs, sixtyfps_compiler/langtype.rs, sixtyfps_compiler/load_builtins.rs, sixtyfps_compiler/namedreference.rs, sixtyfps_compiler/passes/flickable.rs, sixtyfps_compiler/passes/repeater_component.rs, sixtyfps_compiler/passes/resolve_native_classes.rs, sixtyfps_runtime/corelib/properties.rs
The first commit adds some debug facilities to the properties to aid debugging and benchmarking
This show that this patch reduces a lot the number of dependency nodes by not having them for property we know are constant.
=> Mark constant properties as not needing dependency nodes when accessed

docs/builtin_elements.md, docs/widgets.md
Include documentation about needing to manually set the viewport-width and viewport-height when using a for loop.
I also added some more general documentation to `Flickable` but it likely needs to be edited as my explanation was a bit wordy. 
Are there other points in the documentation that need this same explanation or is this sufficient?
=> Update Flickable and ScrollView docs

sixtyfps_compiler/generator/rust.rs, sixtyfps_runtime/interpreter/eval.rs, tests/cases/globals/alias_to_global.60
two problems
- For the interpreter, properly handle the case of an alias to a global
- For the rust generator, we can't return a reference to a property held
in a global, so we must 'inline' the get_xx funciton on sub-components
=> Fix issues related to alias to globals

CHANGELOG.md, docs/langref.md, sixtyfps_compiler/lookup.rs, sixtyfps_compiler/passes/resolving.rs, sixtyfps_compiler/tests/syntax/lookup/color.60, tests/cases/expr/math.60, tests/cases/expr/minmax.60, tests/cases/types/color.60, tools/lsp/completion.rs, tools/lsp/goto.rs
This fully closes https://github.com/sixtyfpsui/sixtyfps/issues/53  (although it said `Color.` instead of `Colors.`)
=> Introduce builtin namespaces for the Colors and Math functions

CHANGELOG.md, docs/builtin_elements.md, sixtyfps_compiler/lookup.rs, sixtyfps_compiler/lookup/key_codes.rs, sixtyfps_compiler/widgets/fluent/sixtyfps_widgets.60, sixtyfps_compiler/widgets/native/sixtyfps_widgets.60, sixtyfps_runtime/corelib/input.rs, sixtyfps_runtime/corelib/input/key_codes.rs, sixtyfps_runtime/corelib/items/text.rs, sixtyfps_runtime/rendering_backends/gl/event_loop.rs, sixtyfps_runtime/rendering_backends/gl/key_codes.rs, sixtyfps_runtime/rendering_backends/mcu/simulator/key_codes.rs, sixtyfps_runtime/rendering_backends/qt/qt_window.rs, sixtyfps_runtime/rendering_backends/qt/qt_window/key_codes.rs, tests/cases/examples/key_press.60, tests/cases/text/cursor_move.60, tests/cases/text/cursor_move_grapheme.60, tests/cases/text/cut.60, tests/cases/text/surrogate_cursor.60, tests/cases/text/text_change.60
Closes #170
- centralize the list of keys in one file
- add the ability to name the keys in the .60 files via `Keys`
- As a test case, add support for up and down keys in the StandardListView
Note: 
* I opted for a CamelCase key name in the Keys namespace because that's the same casing as what's used there: https://www.w3.org/TR/uievents-key/#named-key-attribute-values
Should we instead use the snake case: `Keys.left-arrow`  instead of `Keys.LeftArrow` ?
* Thinking about it, the use of key code might be a problem if someone wants to print these text. Some replacement character will be used. We don't even have a is_printable API, or a way to say that a given code should not be used as text. (The code for the line edit hardcode the private range as an exclusion)
=> Add support for additional non-printable keys

sixtyfps_runtime/corelib/graphics/image.rs, sixtyfps_runtime/rendering_backends/gl/glwindow.rs, sixtyfps_runtime/rendering_backends/gl/images.rs, sixtyfps_runtime/rendering_backends/gl/lib.rs
This refactors the image handling a little in the GL renderer a bit and fixes the cache invalidation when rendering SVGs where the target scaled size depends on the scale factor.
cc #734
=> GL backend: image svg cache fix

sixtyfps_runtime/rendering_backends/gl/lib.rs
If it's called on top of the an event processed on the event loop,
it might be that GLOBAL_PROXY is already borrowed further down
the stack.
=> wasm32: Fix reentrancy issues with invoke_from_event_loop

sixtyfps_runtime/rendering_backends/gl/event_loop.rs, sixtyfps_runtime/rendering_backends/gl/lib.rs
This fixes an issue with invoke_from_event_loop not always working in WASM when called from outside the event loop and streamlines the code a little bit.
Not entirely sure that this will fix the doc example issue as well - the mouse handlers would go through the loop I think - but I haven't been able to test it.
=> wasm event proxy fixes

sixtyfps_compiler/object_tree.rs, sixtyfps_compiler/passes.rs, sixtyfps_compiler/passes/lower_shadows.rs
The opacity on a rectangle should be applied before the shadow, so that it has
a visible effect.
This is a partial fix for #714 but needs also #725 to be entirely visually correct.
=> Fix opacity property not affecting the shadow color

api/sixtyfps-cpp/docs/index.rst, api/sixtyfps-rs/docs.rs, api/sixtyfps-rs/lib.rs, docs/debugging_techniques.md
This is listed under the reference ("how to") and explains `SIXTYFPS_SLOW_ANIMATIONS`, SIXTYFPS_DEBUG_PERFORMANCE` as well as `SIXTYFPS_SCALE_FACTOR`.
=> Add a debugging techniques page to the C++ and Rust documentation

tools/lsp/README.md
Copying & pasting the JSON should just work now without the user
needing to edit the hardcoded path.
=> docs: fix Kate LSP JSON, add Windows support

sixtyfps_compiler/passes/optimize_useless_rectangles.rs
Replace with !x.any(f) (as suggested by clippy).
This is not trivial enough to push without review :-)
=> janitor: Canonicalize a x.filter(f).next().is_none() sequence

.github/workflows/ci.yaml, Cargo.toml, sixtyfps_runtime/corelib/Cargo.toml, sixtyfps_runtime/corelib/lib.rs, sixtyfps_runtime/corelib/tests.rs, sixtyfps_runtime/rendering_backends/default/Cargo.toml, sixtyfps_runtime/rendering_backends/mcu/Cargo.toml, sixtyfps_runtime/rendering_backends/mcu/lib.rs, sixtyfps_runtime/rendering_backends/mcu/pico_st7789.rs, sixtyfps_runtime/rendering_backends/mcu/renderer.rs, sixtyfps_runtime/rendering_backends/mcu/simulator.rs
This cherry-picks (and squashes) the backend specific changes from the MCU branch.
One of the main option questions is if the linker flags integration is the correct approach here or not. I remember that we agreed to eliminate the mcu-build crate, but I don't recall if we said that the mcu backend would write some json file or if we add the device specific flags to the sixtyfps-build crate.
=> MCU backend updates

api/sixtyfps-cpp/include/sixtyfps.h, api/sixtyfps-cpp/tests/eventloop.cpp, sixtyfps_runtime/corelib/timers.rs
With this patch it matches the Rust API, with start(), restart(), running() and
a default constructor.
=> Complete the C++ Timer API

CHANGELOG.md, api/sixtyfps-cpp/include/sixtyfps.h, api/sixtyfps-cpp/tests/eventloop.cpp, sixtyfps_runtime/corelib/timers.rs
Allow calling restart() on a repeated timer if it has been previously stopped.
=> Fix the Rust/C++ Timer API to be more convenient to use

sixtyfps_compiler/passes/compile_paths.rs, sixtyfps_compiler/tests/syntax/basic/path_for.60
Instead, produce a diagnostic message.
cc #754
=> Don't panic in the compiler when encountering a Path element with for-in

api/sixtyfps-cpp/include/sixtyfps.h, sixtyfps_compiler/generator/cpp.rs, sixtyfps_runtime/corelib/item_tree.rs
The indexes stored in `VisitChildrenResult` are unsigned. We have 64
bits to store two values and we need to have one special value as a flag.
So accept any index `< u32::MAX` instead of `< i32::MAX`, which should
allow for more data to be visited;-)
I added the breaking change label, as this does change the interface we expose in a subtle way.
=> Allow for bigger indices in VisitChildrenResult

CMakeLists.txt
Our code uses some C++ 17 extensions, so document that in the
CMakeLists.txt file.
=> CMake: Require C++ 17

api/sixtyfps-rs/lib.rs, api/sixtyfps-rs/sixtyfps-build/lib.rs, sixtyfps_compiler/diagnostics.rs, sixtyfps_compiler/expression_tree.rs, sixtyfps_compiler/generator.rs, sixtyfps_compiler/passes/resolving.rs, sixtyfps_runtime/corelib/backend.rs, sixtyfps_runtime/corelib/graphics.rs, sixtyfps_runtime/corelib/graphics/color.rs, sixtyfps_runtime/corelib/layout.rs, sixtyfps_runtime/corelib/properties.rs, sixtyfps_runtime/corelib/string.rs, sixtyfps_runtime/interpreter/api.rs, sixtyfps_runtime/interpreter/dynamic_component.rs, sixtyfps_runtime/rendering_backends/mcu/renderer.rs, sixtyfps_runtime/rendering_backends/qt/qt_window.rs
Based on earlier experience: These patches might not be uncontroversial, so I am putting them here for review:-)
1. The first one annotates some more functions with the #[must_use] directive. That is visual noise, but I find it rather worthwhile anyway.
2. The second one allows `clippy::transmute_num_to_bytes` in places where the `cpp` macro is used. That silences some warnings, but again at the price of some clutter.
3. The third removes some `return`s that `clippy` claims are redundant. I like that it removes the warning messages, but in some places I think the return has at least some aesthetic value.
Any opinions?
=> More clippy fixes

sixtyfps_runtime/rendering_backends/gl/fonts.rs
That adds visibility to additional fontdb::Source variants,
which however are not reachable for us.
cc #826
=> Fix wasm build when fontdb has file system features enabled

api/sixtyfps-rs/lib.rs
Our web site and READMEs direct to our Rust API crate, which makes sense as it provides
fundamental traits and types. However as pointed out in
#811 we should advertise the existence of the interpreter API.
Ideally we'd link to the crate documentation that
(1) perfect matches the version number
(2) uses sixtyfps.io for our built docs and docs.rs for the published crates
I could not find a way to do this (not without making the crate a dependency and adding features), so
this patch is a compromise that I've seen used in other
crates.
=> Link to the sixtyfps interpreter crate from the Rust API crate

CHANGELOG.md, docs/langref.md, sixtyfps_compiler/builtins.60, sixtyfps_runtime/corelib/items.rs, sixtyfps_runtime/corelib/properties.rs, tests/cases/properties/delayed_transitions.60
This is a very non-intrusive implementation of a `delay` property on `PropertyAnimation`.
This version will only add a `delay` before the first animation. In the presence of `loop-count`, these other animations will not be delayed.
=> Add `delay` property to `PropertyAnimation`

api/sixtyfps-cpp/cbindgen.rs
IntoIter::new is deprecated and the rust compiler asks to use .iter()
instead.
Let's see how CI likes that: Not sure this is already supported on the oldest rust compiler we need to support:-)
=> Fix warning in C++ bindgen code

sixtyfps_compiler/parser.rs, sixtyfps_compiler/parser/expressions.rs, sixtyfps_compiler/passes/resolving.rs, tests/cases/types/object.60, tests/cases/types/string_to_float.60
Before we would only allow `foo.bar` where `foo` was an identifier.
Now we also allow more complex expression such as `"foo".bar` or `(123 + foo).bar`
(in the parser)
In particular, this will allow to get the member of objects returned by functions
or, in the future, part of arrays
=> Parser: allow `.` to access member after any expression

CHANGELOG.md, api/sixtyfps-cpp/include/sixtyfps.h, api/sixtyfps-cpp/tests/datastructures.cpp, docs/langref.md, sixtyfps_compiler/expression_tree.rs, sixtyfps_compiler/generator/cpp.rs, sixtyfps_compiler/generator/rust.rs, sixtyfps_compiler/langtype.rs, sixtyfps_compiler/llr/expression.rs, sixtyfps_compiler/llr/lower_expression.rs, sixtyfps_compiler/parser.rs, sixtyfps_compiler/parser/expressions.rs, sixtyfps_compiler/passes/resolving.rs, sixtyfps_compiler/tests/syntax/lookup/array_index.60, sixtyfps_runtime/corelib/model.rs, sixtyfps_runtime/interpreter/eval.rs, sixtyfps_runtime/interpreter/value_model.rs, tests/cases/models/array.60, tests/cases/models/write_to_model.60
This is based on #605 and adds support for array index expressions for writing as well as change tracking for property bindings.
=> Add support tracked array data access by index

sixtyfps_compiler/expression_tree.rs, sixtyfps_compiler/passes/binding_analysis.rs, sixtyfps_compiler/tests/syntax/analysis/binding_loop2.60, sixtyfps_compiler/tests/syntax/analysis/binding_loop_issue_772.60
The original binding analysis code was considering that all the sub components
were inlined. But when this is not the case, we need to re-analyze each
sub component within their parent.
We also need to take care of reverse aliases
Will cause a .60 compile time binding loop error instead of a
runtime recursion panic in code like issue #772
=> Fixes loop detection involving sub components and two ways binding

sixtyfps_compiler/generator/cpp.rs
After generating the root component's item tree, with all public fields,
hide all variables and functions, with three exceptions.
All meanwhile added declarations for sub-components (such as popups, child repeaters)
still get access through friendship.
=> cpp generator: reduce surface of public C++ API

docs/langref.md, sixtyfps_compiler/object_tree.rs, sixtyfps_compiler/tests/syntax/imports/font.60
... and produce diagnostics.
That way in later phases we don't need to check again.
=> Verify the existence of imported custom fonts

sixtyfps_compiler/object_tree.rs
Commit fa1ac9884d0fdc20acc1ed39f20ea010de8b069d introduced an early check for the existence
of the specified font files. However we should only do that for local files for now.
=> Prospective fix for the printer demo not loading in the online editor

CHANGELOG.md, api/sixtyfps-cpp/docs/cpp_migration.md, api/sixtyfps-cpp/docs/index.rst
Once we have a Rust incompatible change we can change the sentencen in the ChangeLog to link to the Rust guide, too.
=> Start a migration guide for C++ API for 0.2.0

CHANGELOG.md, api/sixtyfps-cpp/include/sixtyfps_interpreter.h, api/sixtyfps-node/native/js_model.rs, api/sixtyfps-node/native/lib.rs, sixtyfps_runtime/corelib/model.rs, sixtyfps_runtime/interpreter/api.rs, sixtyfps_runtime/interpreter/eval.rs, sixtyfps_runtime/interpreter/ffi.rs, tests/cases/models/model.60, tests/cases/models/write_to_model.60
A model property such as
property <[Foo]> model: [ ... ];
would create a VecModel in Rust and C++, which in turn can be written to
with an array index expression in .60. If the same .60 code was running
in the interpreter, a Value::Array would be created instead. We don't
support writing into Value::Array by index because we don't have
tracking in place for that, to update dependent bindings.
To fix this inconsistency, this patch changes the interpreter to
allocate a mutable VecModel as well.
=> Enable write access to models initialized from arrays in the interpreter

api/sixtyfps-rs/lib.rs
... by taking &self instead of self
cc #431
=> Make `sixtyfps::Weak<T>::upgrade_in_event_loop` easier to use

CHANGELOG.md, api/sixtyfps-node/native/lib.rs, api/sixtyfps-rs/lib.rs, api/sixtyfps-rs/migration.md, docs/tutorial/rust/src/main_game_logic_in_rust.rs, docs/tutorial/rust/src/main_tiles_from_rust.rs, examples/imagefilter/main.rs, examples/memory/main.rs, examples/printerdemo/rust/main.rs, examples/slide_puzzle/main.rs, examples/todo/rust/main.rs, sixtyfps_compiler/generator/rust.rs, sixtyfps_runtime/corelib/model.rs, sixtyfps_runtime/interpreter/api.rs, sixtyfps_runtime/interpreter/dynamic_component.rs, sixtyfps_runtime/interpreter/eval.rs, sixtyfps_runtime/interpreter/ffi.rs, tests/cases/crashes/layout_deleted_item.60, tests/cases/models/array.60, tests/cases/models/model.60, tests/cases/models/write_to_model.60, tools/viewer/main.rs
It is now safe to replace the manual implementation with the derived
implementation, so do that.
This is a continuation of #311, which I accidentally closed when I deleted the branch.
=> Merge `Rc::ptr_eq` on traits use into a SharedModel

sixtyfps_runtime/corelib/model.rs
The contents is not longer accessible, so there is no need for deref and
deref_mut.
@ogoffart pointed that out in the commit that introduced the ModelRc.
=> ModelRc: Remove some more unnecessary derives

api/sixtyfps-rs/sixtyfps-build/lib.rs, sixtyfps_compiler/diagnostics.rs, sixtyfps_runtime/corelib/timers.rs, sixtyfps_runtime/interpreter/api.rs, sixtyfps_runtime/interpreter/ffi.rs, tools/lsp/util.rs
This allows adding new variants in minor releases without breaking
source compatibility.
cc #431
=> Mark some enums that end up in the public Rust API as non_exhaustive

CHANGELOG.md, api/sixtyfps-node/native/lib.rs, api/sixtyfps-rs/migration.md, docs/tutorial/rust/src/main_game_logic_in_rust.rs, docs/tutorial/rust/src/main_tiles_from_rust.rs, examples/imagefilter/main.rs, examples/memory/main.rs, examples/printerdemo/rust/main.rs, examples/slide_puzzle/main.rs, examples/todo/rust/main.rs, sixtyfps_compiler/generator/rust.rs, sixtyfps_runtime/corelib/model.rs, sixtyfps_runtime/interpreter/api.rs, sixtyfps_runtime/interpreter/dynamic_component.rs, sixtyfps_runtime/interpreter/eval.rs, sixtyfps_runtime/interpreter/ffi.rs, tests/cases/crashes/layout_deleted_item.60, tests/cases/models/array.60, tests/cases/models/model.60, tests/cases/models/write_to_model.60, tools/viewer/main.rs
- ModelRc::new constructs a ModelRc from a impl Model
- ModelRc::form constructs a ModelRc from a `Rc<dyn Model>` or `Rc<impl Model>`
=> Change what is accepted by ModelRc::new and ModelRc::from

api/sixtyfps-cpp/cbindgen.rs, api/sixtyfps-cpp/include/sixtyfps_image.h, internal/core/graphics.rs
Remove the duplicated definition of the IntSize struct and instead
generate it via cbindgen into the public API.
=> Remove a doxygen #ifdef

api/sixtyfps-cpp/Cargo.toml, api/sixtyfps-rs/Cargo.toml, api/sixtyfps-rs/lib.rs, api/sixtyfps-rs/sixtyfps-build/Cargo.toml, api/sixtyfps-rs/sixtyfps-build/lib.rs, internal/interpreter/Cargo.toml, internal/interpreter/lib.rs, tests/driver/interpreter/Cargo.toml, tools/lsp/Cargo.toml, tools/viewer/Cargo.toml
We want to be able to put existing functionality behind a feature flag while keeping
the semver compatibility.
This is only possible if that new feature flag is enabled by default, but this is not
working if the users have done `default-features = false` in their Cargo.toml.
So we add new `compat-x-y-z` feature that is mandatory to have and which is
enforced with a `compile_error!`
Now, users that whishes to not have the default features must enable it explicitly.
Say we want only x11 but not qt and wayland, the user will do
```toml
sixtyfps = { version = "0.2", default-features = false, features = ["x11", "compat-0-2-0"] }
```
Now, imagine that in the version 0.2.3, we put the SVG support behind a feature flag.
we will do this in out Cargo.toml:
```toml
[features]
default = …
```
=> Add compatibility feature to our public crates

internal/backends/testing/lib.rs, internal/compiler/generator.rs, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/llr/expression.rs, internal/compiler/llr/lower_expression.rs, internal/compiler/llr/lower_to_item_tree.rs, internal/compiler/passes/binding_analysis.rs, internal/compiler/passes/compile_paths.rs, internal/core/graphics/image.rs, internal/interpreter/eval.rs
Nothing interesting, I mostly want to let CI run over it.
Afterwards we have some more warnings about functions with too many arguments, the cpp transmute thing that I should fix upstream, some complex types. But apart from those we are almost clippy clean after this set of patches and #794.
=> Semi-automatic clippy fixes

docs/langref.md, internal/compiler/builtins.60, internal/compiler/llr/lower_expression.rs, internal/compiler/object_tree.rs, internal/core/items.rs, internal/core/properties.rs, tests/cases/layout/path_offset.60, tools/syntax_updater/from_0_1_0.rs, tools/syntax_updater/main.rs
We used to run `n+1` times instead, which seems wrong to me. It is also
not how the similar property in CSS is documented to work.
As a side-effect of this change, the animation will no longer play when
overshooting the playback interval.
=> PropertyAnimation: Make `loop-count: n` run animations n times

.github/workflows/nightly_snapshot.yaml, .github/workflows/wasm_demos.yaml, CHANGELOG.md, Cargo.toml, api/cpp/cbindgen.rs, api/cpp/include/sixtyfps.h, cmake/FindOpenGLES2.cmake, examples/CMakeLists.txt, examples/README.md, examples/opengl_underlay/CMakeLists.txt, examples/opengl_underlay/Cargo.toml, examples/opengl_underlay/README.md, examples/opengl_underlay/build.rs, examples/opengl_underlay/index.html, examples/opengl_underlay/main.cpp, examples/opengl_underlay/main.rs, examples/opengl_underlay/scene.60, internal/backends/gl/glcontext.rs, internal/backends/gl/glwindow.rs, internal/backends/mcu/lib.rs, internal/backends/mcu/simulator.rs, internal/core/api.rs, internal/core/window.rs
This is the initial merge request for supporting underlay and overlay rendering in Rust and C++.
There are a few caveats:
* Explicit backend and native style selection needs to be implemented for Rust and C++.
* For C++ I think the style could simply be a string target property and we call back to the "default" (which is not configurable right now, but that's a separate issue).
* For Rust and C++ we need the ability to select a backend. This could be a "one-time" function `mod sixtyfps { pub fn set_backend(name: &'str) -> std::result::Result<(), String>; `
* There's a hack in the `request_redraw()` API :-(
* The first change in the series adds support for alpha in the Window surface, so in the most extreme case you can write `background: transparent;` on a `Window` and it'll make the …
=> Custom rendering API

internal/compiler/generator/rust.rs, tests/cases/callbacks/handler.60, tests/cases/callbacks/return_value.60
If a callback returning voids ends in a statement that returns something,
we would have an error in the rust generated code as we end our function
with an expression that is not `()`
=> Rust generator: Fix compilation returning from void callbacks

api/cpp/cbindgen.rs, api/cpp/include/sixtyfps.h, examples/opengl_underlay/main.cpp, internal/core/window.rs
Add the graphics state enum to the callback, too. When we add support for different backends,
it would be nice if it didn't require an API change.
It's duplicated from Rust
because it doesn't provide values. The WebLG one doesn't make sense for C++ and
the proc address closure isn't ffi safe.
(It could be manually bridged thought)
=> Minor fixup to the C++ rendering notifier API

internal/core/api.rs
The winit event loop needs a similar Poll nudge as for wasm in order for request_redraw() to work :-(
=> Fix GL example not updating on Windows

api/cpp/cbindgen.rs, api/cpp/include/slint_image.h, api/cpp/include/slint_size.h, internal/core/graphics.rs
Fixes #909
Since we declare the struct in C++, we don't need to declare it in
rust for cbindgen anymore, as long as we expose the Size2D type from
euclid to the cbindgen_private namespace
=> C++: drops IntSize in favor of Size<T>

internal/backends/gl/images.rs
It appears that HTMLImageElement is not guaranteed to provide a texture with pre-multiplied alpha. Let's limit this assumption to
SVGs.
=> Fix rendering of png images with alpha in the online editor

api/wasm-interpreter/src/lib.rs, docs/resources/slint-docs-preview.html
Only the last shown preview was interactive. This was because we started the winit event loop for each preview,
which kind of invalidates the previous instance in winit.
Instead, create all components, call show() on each instance to register the window with winit
and spin the event loop with its exception magic only once.
=> Fix non-interactive doc preview

FAQ.md
The question "Is that name not going to be obsolete soon?" was removed from the FAQ previously. However, the link to that question in the table of contents was not removed. This PR removes that dangling link.
=> Remove broken link from FAQ.md

tools/fmt/README.md, tools/fmt/fmt.rs, tools/fmt/main.rs, tools/fmt/writer.rs
Closes #898 
Sorry it took a while - but i needed to learn more than anticipated :)
Changes in this PR:
- **unrelated to fmt** - I own an M1 Mac and the builds of most of the creates were failing for me unless I updated neon. I am not sure about the impact on this on the rest of the project though. Let me know if it breaks something and I'll remove the commit.
- Adds tests to fmt, with some basic examples
- Fixes the original issue from #898 as well as some things about BinaryExpression/Expression formatting
- Some code cleanup
- Adds a README with a tutorial on how to get this running in your vscode
Overall fmt is still far form perfect but I see this as a step in a good direction.
btw sorry if some of my changes still refer to the old name, you literally renamed 3 hours ago 😅
=> fmt tool improvements

internal/backends/gl/event_loop.rs
When "combining" information from winit's ReceiveCharacter and
KeyboardInput events, then do not create a second KeyPress event
when the KeyboardInput contained a control character.
This makes us not send duplicate events for `Tab`, but leaves the
handling for e.g. `Ctrl-C` unchanged.
=> Send less key events from the GL backend

internal/compiler/Cargo.toml, internal/compiler/passes/embed_glyphs.rs, internal/compiler/passes/embed_glyphs/fontconfig.rs
Copy the fontconfig code from the GL backend to find out what the font for "sans-serif" is, in case we need a fallback.
=> Fix glyph embedding on Linux

internal/backends/qt/Cargo.toml, internal/backends/qt/build.rs
It now expose the flag via env variable, and allow to report
the reason why Qt was not found
=> Upgrade qttypes

api/cpp/cbindgen.rs, api/cpp/include/slint.h, internal/backends/qt/qt_widgets/stylemetrics.rs, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/llr/item_tree.rs, internal/compiler/llr/optim_passes/inline_expressions.rs, internal/compiler/passes/collect_globals.rs, internal/compiler/widgets/fluent/std-widgets-impl.slint, internal/compiler/widgets/ugly/std-widgets-impl.slint, internal/interpreter/dynamic_component.rs, internal/interpreter/eval.rs, internal/interpreter/eval_layout.rs, internal/interpreter/global_component.rs, tests/cases/globals/global_depends_on_global.slint
- We need to make sure that the initialization of global is in the right order.
- In C++ and rust, we need to add accessor to the global component
- There can be `PropertyReference::Global` in binding of globals
- The interpreter globals need to hold references to the global they may depend on
Fixes #175
=> Support for referring to other globals from globals

api/cpp/CMakeLists.txt, api/cpp/cbindgen.rs, api/cpp/include/slint.h, internal/backends/gl/Cargo.toml, internal/backends/gl/lib.rs, internal/backends/gl/stylemetrics.rs, internal/backends/mcu/lib.rs, internal/backends/qt/lib.rs, internal/backends/qt/qt_widgets/stylemetrics.rs, internal/backends/selector/build.rs, internal/backends/selector/lib.rs, internal/compiler/builtins.slint, internal/compiler/widgets/common/common.slint
On GL, this uses the [`dark-light` crate](https://crates.io/crates/dark-light). On Qt, it checks whether the window background color's average is < 128.
On GL, this currently does not detect changes after the application is opened. This is blocked on [this PR for `dark-light`](https://github.com/frewsxcv/rust-dark-light/pull/10).
This is a re-do of #982, this time on a separate branch.
=> Add NativeStyleMetrics.dark-style property, supported by both backends

api/cpp/CMakeLists.txt, api/cpp/Cargo.toml, internal/backends/gl/Cargo.toml, internal/backends/gl/stylemetrics.rs, internal/backends/qt/Cargo.toml, internal/backends/qt/lib.rs, internal/backends/qt/qt_widgets.rs, internal/backends/selector/Cargo.toml, internal/interpreter/Cargo.toml
Only the interpreter needs the rtti generated code.
* Since `SlintElement` emits `#[cfg(feature = "rtti")]` tokens, each
crate using `SlintElement` needs to have an `rtti` feature.
* The selector gets backend specific rtti selection features, in order
for the interpreter to enable them.
=> Build the backends without rtti unless needed

CHANGELOG.md, api/cpp/cbindgen.rs, docs/builtin_elements.md, internal/backends/gl/lib.rs, internal/backends/qt/qt_widgets/lineedit.rs, internal/backends/qt/qt_window.rs, internal/compiler/builtins.slint, internal/compiler/typeregister.rs, internal/core/items/text.rs, internal/core/rtti.rs, internal/interpreter/api.rs, internal/interpreter/dynamic_component.rs, tests/cases/text/input_type.slint
Fixes #882 
This adds the option to replace characters in an input field with another character that defaults to "*".
=> Add an InputType enum to allow password fields

api/rs/build/Cargo.toml, api/rs/build/lib.rs, examples/printerdemo/rust/build.rs, internal/backends/mcu/Cargo.toml, internal/backends/mcu/build.rs, internal/backends/mcu/pico_st7789/board_config.toml, internal/backends/mcu/pico_st7789/memory.x, xtask/src/license_headers_check.rs
Let the mcu backend provide the link flags via I_DEP_* and the
Slint-build crate now offers a function to allow printing Slint-specific
rustc flags.
=> Add MCU board config setup

internal/compiler/object_tree.rs, internal/compiler/passes/ensure_window.rs, internal/compiler/passes/inlining.rs, internal/compiler/passes/repeater_component.rs, tests/cases/bindings/issue_1026_opacity_alias.slint
The problem is that if some bindings are coming from already inlined elements
they should have a higher priority field, so that whenmerging the two way
binding, we keep the least deep value
Fixes: #1026
=> Properly compute the binding priority in case of several level of inlining

internal/backends/qt/qt_widgets/lineedit.rs
just a little bug i found when testing the examples.
=> Don't draw lineEdit's focus ring if it is not enabled

tools/compiler/Cargo.toml, tools/compiler/main.rs, tools/figma_import/Cargo.toml, tools/figma_import/src/main.rs, tools/fmt/Cargo.toml, tools/fmt/main.rs, tools/lsp/Cargo.toml, tools/lsp/main.rs, tools/syntax_updater/Cargo.toml, tools/syntax_updater/main.rs, tools/viewer/Cargo.toml, tools/viewer/main.rs, xtask/Cargo.toml, xtask/src/main.rs
Make clap generate `--version`, and make it add more informtaion from
Cargo.toml available in `--help`.
Old output:
```
slint-lsp 
USAGE:
slint-lsp [OPTIONS]
OPTIONS:
--backend <backend>                                 The backend used for the preview ('GL' or 'Qt') [default: ]
-h, --help                                              Print help information
-I <Add include paths for the import statements>        
--style <style name>                                The style name for the preview ('native', 'fluent' or 'ugly') [default: ]
```
New output:
```
slint-lsp 0.2.2
Slint Developers <info@slint-ui.com>
A language server protocol implementation for slint.
USAGE:
slint-lsp [OPTIONS]
OPTIONS:
--backend <backend>                                 The backend used for the preview ('GL' or …
```
=> Janitor: Clap update + basic functionality addition to all binaries

CHANGELOG.md, internal/core/model.rs
this makes it possible to create a model for StandardListView like this:
```rust
Rc::new(slint::VecModel::<slint::StandardListViewItem>::from(vec![
"Emil, Hans".into(),
"Mustermann, Max".into(),
"Tisch, Roman".into(),
]));
```
push works like this:
```rust
let new_entry = "bla".to_string();
model.push(new_entry.into());
```
=> add From<&str> and From<String> to StandardListViewItem

internal/compiler/widgets/fluent/std-widgets.slint, internal/compiler/widgets/native/std-widgets.slint
This is the implementation of @ogoffart 's idea to reset `StandardListView`'s `current-item` to the last item or -1 if it is out of bounds.
It is a simple hack and causes problems if the current-item is set from code, but it was easy to do and is better than no reset at all.
=> reset StandardListView's current-item if it is out of bounds

api/cpp/cmake/SlintConfig.cmake.in
Do not break building against slint using CMake from C++ when no
CMAKE_BUILD_TYPE was set when building Slint.
This just makes sure the build type is properly quoted, which makes sure
we keep a (empty) string token where CMake expects one.
Fixes: #1065
=> cmake: Do not break when slint is build with empty CMAKE_BUILD_TYPE

internal/backends/gl/glwindow.rs, internal/backends/gl/lib.rs, internal/backends/qt/qt_widgets.rs, internal/core/item_rendering.rs, internal/core/items.rs, internal/core/items/image.rs, internal/core/items/path.rs, internal/core/items/text.rs
Persist the layer image we render the sub-tree for non-rectangular clips into.
Upsides:
* This avoids repeated allocation and deletion of the layer textures
* Unless the sub-tree changes, this speeds up complex scenes
Downsides:
* This makes lazy clipping as proposed in #1053 impossible (or maybe just very hard?)
* This increase the GPU memory consumption for every non-rectangular clip
=> Change non-rectangular clip implementation in the GL backend

internal/backends/gl/images.rs, internal/backends/gl/lib.rs, internal/backends/qt/qt_window.rs, internal/core/item_rendering.rs, internal/core/items.rs, tests/manual/opacity_inheritance.slint
Use layers in the GL and Qt backend for rendering the opacity element, to apply it evenly.
Closes #725
=> Opacity layers

CHANGELOG.md, api/cpp/cbindgen.rs, docs/builtin_elements.md, internal/backends/gl/lib.rs, internal/backends/qt/qt_window.rs, internal/compiler/builtins.slint, internal/compiler/passes.rs, internal/compiler/passes/lower_property_to_element.rs, internal/compiler/typeregister.rs, internal/core/item_rendering.rs, internal/core/items.rs, internal/interpreter/dynamic_component.rs, tests/cases/layer.slint
This is the last part of #1058 that adds new API to provide a hint to the renderer to cache an element and its sub-tree.
Open questions:
- ~~[ ] Should this change set also implement an optimisation to omit the `Layer` element injection if the value of the property is a constant `false`?~~
- ~~[ ] `cache: true;`~~
- ~~[ ] `cache-hint: true;`~~
- ~~[ ] `rendering-cache-hint: true;`~~
=> layer hint

CHANGELOG.md, internal/backends/gl/Cargo.toml, internal/backends/gl/event_loop.rs, internal/backends/gl/glwindow.rs, internal/backends/gl/lib.rs, internal/backends/gl/wasm_input_helper.rs, internal/core/Cargo.toml, internal/core/items/text.rs, internal/core/window.rs
cc #215
Handle Input event from the input directly instead of going through winit
for the TextInput.
Note that this doesn't handle the composition event well, so the text is
only considered written when it is accepted
=> Wasm GL backend: use a `<input>` element so it show the keyboard on mobile

internal/backends/gl/event_loop.rs
When a second canvas is visible, only animations in the first canvas
resulted in updates and visible animation.  An animation in the second
canvas wouldn't result in repaints.
When we start an animation, we request a redraw on all windows and
return with `ControlFlow::Poll` to winit.
Winit then schedules an animation frame request, and in the callback the
redraw request events are delivered. For the first window we call
`update_animations()`, a new tick is detected (different than the
previous one) and animated properties are dirty and yield new windows.
Then right away we get called again with a redraw request for the second
window. update_animations() determines that the instant::now() is the
same, and has_animations() returns false. So at the end of the event
handler we return fail to …
=> Fix animations not running in secondary windows with wasm

helper_crates/vtable/macro/macro.rs
Quieten a warning when setting up a very simple static vtable without drop and such.
=> vtable: Quieten possible warning about unused unsafe

internal/core/items/text.rs
This adds up and down cursor movement to TextInput.
It uses `PlatformWindow`'s `text_input_position_for_byte_offset()` and `text_input_byte_offset_for_position()` functions.
Because of a bug in `text_input_byte_offset_for_position()` it returns to the top when pressing down on last line.
=> Add up and down cursor movement to TextInput

internal/backends/gl/lib.rs, internal/backends/qt/qt_window.rs
More could be done towards this, but after literally seeing `opacity: 1;` in
.slint files, this seems worth doing.
=> Don't create layers for opacity if it's not needed

api/rs/build/lib.rs, internal/backends/mcu/README.md, internal/backends/mcu/build.rs, internal/compiler/lib.rs, internal/compiler/passes.rs, internal/compiler/passes/embed_glyphs.rs, internal/compiler/passes/embed_images.rs
... using metadata from the build script
Saves two environment variable that we don't have to pass
=> MCU build system: pass information about embedding images and glyph to the compiler

internal/backends/gl/glwindow.rs, internal/backends/qt/qt_window.rs, internal/core/graphics/fps_counter.rs
After commit 575665994aa348abec097178f3cc0b57333c110e we need to explictly schedule a repaint,
so that we draw and call `measure_frame_rendered`.
=> Fix the frame per second counter when using refresh_full_speed

internal/backends/gl/wasm_input_helper.rs
Since we don't have yet support for IME in Slint, simulate that by inserting
the text anyway, and rollback using backspaces.
=> Wasm: Hack to get input working despite composition

internal/core/input.rs, internal/core/items/text.rs
This PR adds the Shortcut abstraction that we talked about in #1110
Right now the Shortcuts are separated into `TextShortcut`s in text.rs and `Shortcut`s in input.rs.
Both are implemented on `KeyEvent`.
=> Add TextShortcut and Shortcut and use them in TextInput

internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/object_tree.rs, internal/compiler/passes.rs, internal/compiler/passes/ensure_window.rs, internal/compiler/passes/inlining.rs, internal/compiler/passes/lower_popups.rs, internal/compiler/passes/optimize_useless_rectangles.rs, internal/compiler/passes/repeater_component.rs, tests/cases/crashes/issue1113_popup_in_repeater.slint
* Make sure that the compiler don't panic if the parent of a PopupWindow
is optimized (by not optiizing such element)
* Ensure that we can call popup.show() from within a deeper repeater
* Ensure that the parent element of the popup is the right one in case of
repeater (and not the node in the parent component)
This partially revert ad5991f8fad9936016ce77c103f41f1fd93fa53d and
6c7a7aed0e1a0fedd0a7164dc21d5be2255f61d5 because we must do the lower_popup
adter the repeater pass, because otherwise the parent element of the
created component for the PopupWindow might be wrong and it is not easy to
adjust (we would have to make Component::parent_element a RefCell or duplicate
it again.
Fixes #1132
=> Fix a bunch more issue with PopupWindow

CHANGELOG.md, docs/resources/slint-docs-preview.html, editor/vscode/src/extension.ts, internal/backends/gl/event_loop.rs, internal/backends/qt/qt_window.rs
Eg, in the viewer or in the preview.
The preferred size is still set as the size when the window is first open
Also make sure the preview in the docs have sensible default and not the winit default that is way too big
=> Keep the existing size re-using a window 

internal/core/input.rs, internal/core/items/text.rs, tests/cases/text/cursor_move.slint
Until now this contains move to start and end of line or paragraph.
It also corrects Home and End behavior.
Moving to the start or end of the line still doesn't work properly, because of the buggy `text_input_byte_offset_for_position` function.
=> Text shortcuts

internal/core/item_focus.rs, internal/core/items.rs
The implementation never properly stepped out of repeaters, so it went
into a loop when a repeater was below a node without siblings. This in
turn led to the window aborting the focus item search. So the focus
never moved forward.
Add a test to make sure this stays fixed.
=> Fix forward tabbing through items

helper_crates/vtable/src/vrc.rs, internal/core/items.rs
Implement `core::fmt::Debug` for VRc and ItemRc.
This makes it so much easier to poke at problems with the ItemRcs.
=> `Debug` for ItemRc

internal/backends/gl/Cargo.toml, internal/backends/gl/fonts.rs
Use directwrite APIs directly to determine the font fallbacks for a given piece of text.
=> Remove font-kit dependency on Windows

internal/backends/gl/lib.rs
If the global opacity is zero, we don't need to paint rectangles, etc.
This shortcut is a compromise between opting out much later on femtovg
level and too early before querying properties of the rectangle.  We
still want to do the latter as somebody might depend on that.
=> GL backend: add shortcut for zero opacity

internal/backends/mcu/README.md, internal/compiler/passes.rs, internal/compiler/passes/const_propagation.rs, internal/compiler/passes/embed_glyphs.rs
Remove the need to specify SLINT_FONT_SIZES if we can determine the font sizes used from constants in the .slint code.
=> mcu: determine font sizes from .slint code if possible

internal/backends/mcu/lib.rs, internal/backends/mcu/renderer.rs, internal/backends/mcu/simulator.rs, internal/core/item_rendering.rs, internal/core/window.rs
When closing a popup, notify the platform window, so that the mcu
backend can remember that region and start the dirty region with it.
Also, free all the rendering cache items of deleted items, to avoid accidental re-use
when re-opening a popup.
=> mcu: fix popups not visibly closing

internal/backends/gl/event_loop.rs
Work around https://github.com/rust-windowing/winit/issues/1996 by tracking
touch positions ourselves
=> Fix touch position reported on touch release with wayland

.github/workflows/ci.yaml, api/cpp/cbindgen.rs, api/rs/slint/lib.rs, internal/backends/gl/event_loop.rs, internal/backends/gl/glwindow.rs, internal/backends/mcu/fonts.rs, internal/backends/mcu/lengths.rs, internal/backends/mcu/lib.rs, internal/backends/mcu/pico_st7789.rs, internal/backends/mcu/renderer.rs, internal/backends/mcu/simulator.rs, internal/compiler/generator/rust.rs, internal/core/flickable.rs, internal/core/graphics.rs, internal/core/graphics/brush.rs, internal/core/graphics/path.rs, internal/core/input.rs, internal/core/item_rendering.rs, internal/core/item_tree.rs, internal/core/items.rs, internal/core/items/image.rs, internal/core/items/path.rs, internal/core/items/text.rs, internal/core/layout.rs, internal/core/lib.rs, internal/core/model.rs, internal/core/tests.rs, internal/core/window.rs
The prepare scene time for the scene that changes to the night mode in the printerdemo_mcu goes from 60ms to 50ms
=> corelib: allow to use i32 for coordinate instead of f32

internal/compiler/builtins.slint, internal/compiler/widgets/fluent/std-widgets-impl.slint, internal/compiler/widgets/fluent/std-widgets.slint, internal/core/items.rs, tests/cases/focus/keyboard_focus.slint
We expose less functionality this way:-)
Allow for a bool to enable/disable focus delivery.
... and handle space/return keys to click() it!
=> Widget focus

docs/langref.md
Remove the explanation of using two-way bindings to expose globals.
While that still works of course, we don't need to mention it as the first example.
Instead provide inline examples with Rust and C++ how to access the globals directly.
The snippets will be hidden/shown by future markup, for now both are visible.
=> Rework the global singleton section in the language reference

internal/core/properties.rs, tests/cases/bindings/multiple_two_way.slint
When resetting the binding, we need to mark dependent property as dirty.
It just hapenned that the current implementation always set all bindings
before starting to query the properties, so this problem was not seen
before. But there is an exception when setting the two_way bindings,
then we may set the binding after the property was querried because
setting a two way binding actually queries the property
=> Property system: setting a binding must mark all dependent property as dirty

api/cpp/CMakeLists.txt, api/cpp/Cargo.toml, api/cpp/cbindgen.rs, api/cpp/include/slint_pathdata.h, internal/common/enums.rs, internal/common/key_codes.rs, internal/common/lib.rs, internal/compiler/generator/cpp.rs, internal/compiler/llr/lower_expression.rs, internal/compiler/passes/compile_paths.rs, internal/compiler/typeregister.rs, internal/core/graphics/path.rs, internal/core/input.rs, internal/core/items.rs, internal/core/items/image.rs, internal/core/items/path.rs, internal/core/items/text.rs, internal/core/layout.rs, internal/core/rtti.rs, internal/core/tests.rs, internal/core/window.rs, internal/interpreter/Cargo.toml, internal/interpreter/api.rs, internal/interpreter/dynamic_component.rs, internal/interpreter/eval_layout.rs, tests/cases/elements/toucharea.slint, xtask/Cargo.toml
This avoid repeating the enums both in the compiler and in
the runtime library, and register them in a bunch of other places.
So it should be easier to add enums and enum values
Since cbindgen doesn't see through the macro, generate the enum
manually
PROS: 
- Enums are declared in one place
CONS:
- Macro makes things more complex to understand, in particular rust-analyzer jump-to-definition
jump to the macro instead of the enum itself.
=> Declare .slint enum in one place in i-slint-common

internal/backends/gl/stylemetrics.rs, internal/backends/qt/qt_widgets/stylemetrics.rs, internal/backends/qt/qt_widgets/tabwidget.rs, internal/compiler/builtins.slint, internal/compiler/widgets/native/std-widgets.slint
Focus the tabs straight away when pressing cursor left/right keys.
=> native: Implement keyboard focus support in Tab widget

docs/resources/slint-docs-preview.html
Not entierly happy on the look/location of the link
=> Documentation: add a edit link to .slint snippet that open the code editor

internal/compiler/builtins.slint, internal/compiler/widgets/fluent/std-widgets-impl.slint, internal/compiler/widgets/fluent/std-widgets.slint, internal/compiler/widgets/native/std-widgets.slint
Set width of FocusScopes to 0px (where possible) to avoid it setting focus on click.
=> Focus width0

internal/compiler/widgets/fluent/std-widgets.slint, internal/core/window.rs
Do not send keyboard events to invisible widgets, reset the keyboard
focus instead.
That fixes #798 again with a bit less of a work-around. To properly fix
this we will need to make the tab widget (and probably others) more
intelligent though.
=> Focus: Do not send keyboard event to invisible widgets

internal/backends/gl/event_loop.rs, internal/backends/gl/glwindow.rs, internal/backends/gl/wasm_input_helper.rs
The situation differs depending if the widget show the virtual keyboard or not:
For widget that don't show the virtual keyboard, we rely on the winit events,
but for some reason we don't recieve WindowEvent::ModifiersChanged events with
wasm. Since the event handling in winit is about to be rewriten, I did not
bother reporting the bug upstream, but just work around by using the deprecated
API. So that way shift + tab will no longer be understood as just tab.
For widget using the virtual keyboard, then the event handling is in
wasm_input_helper.rs.  There is a couple of issues:
- We must map shift+tab to backtab.
- We need to prevent the default events to trigger, so that tab and other
shortcuts don't take effect on the browser. Winit already inhibit these
events so we must do the same …
=> wasm: fix tab and back tab

api/cpp/include/slint.h, api/rs/slint/lib.rs, internal/common/enums.rs, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/llr/item_tree.rs, internal/compiler/llr/lower_to_item_tree.rs, internal/compiler/object_tree.rs, internal/compiler/passes.rs, internal/compiler/passes/ensure_window.rs, internal/compiler/passes/inlining.rs, internal/compiler/passes/lower_accessibility.rs, internal/compiler/passes/repeater_component.rs, internal/compiler/typeregister.rs, internal/core/accessibility.rs, internal/core/component.rs, internal/core/item_focus.rs, internal/core/item_tree.rs, internal/core/lib.rs, internal/interpreter/dynamic_component.rs, tests/cases/accessibility/materialized.slint
This adds `accessible-*` property to every elements, and generate code so that the accessible properties can be queried from the component vtable with the item index.
This just start with one property, and more will be added later.
This hasn't be tested yet.
Note that this is a PR against an accessibility branch, not against master.
=> Start working on accessibility: The compiler part

internal/core/item_tree.rs, tests/cases/focus/keyboard_focus.slint
The parent_node function doesn't reset its argument if it is already
set while calling the function
=> Fix focus navigation involving repeater at the end of the chain

Cargo.toml, docs/building.md
Having to make sure the right version of npm is installed is a hassle
for people that just want to try out slint for the first time. The
proposed way to disable node support enables basically everything else,
which opens another can of worms when Windows tries to build MCU
support.
So do not build Node.JS as part of the default build anymore, but
document how to build it.
The CI should build with `--workspace` already, so there should be no
need to change the CI build.
=> Do not build node by default

examples/7guis/crud.rs, examples/7guis/crud.slint, internal/compiler/widgets/fluent/std-widgets.slint, internal/compiler/widgets/native/std-widgets.slint
This breaks the printer demo USB page, it makes it impossible to
change the current item.
That's because the printer demo do `current-item: 1;` to preselect the cat.
But that breaks the property binding that makes current-item follow the
actual-current-item.
* Revert "move actual-current-item to FocusScope"
This reverts commit 8240531e6ef4f706d86dbb41802856e7a631ccc1.
* Revert "reset StandardListView's current-item if it is out of bounds"
This reverts commit 9d18882f9da026ef58871facaf25894608027208.
=> Revert #1049

internal/backends/qt/qt_window.rs
Fixes the todo example not exiting when clicking on "yes" in
the close popup
cc #1212
=> Qt: quit the application when calling hide() on the last window

internal/backends/qt/qt_window.rs
Windows sends a mouse release event after the close event when running
on windows. This confuses our hack to close popups!
So hack around the problem by ignoring any mouse button release event
that does not follow a mouse button press event. I hope this will
not couse too many side effects.
Fixes: #1211
=> Hack to make Qt not close newly opened popups when running on Windows

internal/backends/gl/event_loop.rs, internal/backends/gl/glwindow.rs
This makes the Application quit, when the windows are hidden programmatically.
Fixes #1220
=> GL Backend: Make window.hide() respect the set EventLoopQuitBehavior

README.md, cspell.json
Add a "Quick Start" early on pointing to the Web demos and build
instructions.
Mention recipes and other docs first, then point to the API docs. I am
pretty sure most users will stop reading once they find the links to the
APIs:-)
=> Imporve README-md

internal/core/model.rs, internal/core/model/model_peer.rs
Contain the unsafe code in a smaller module.
Add an abstraction to make it easier to create change listener other
than the repeater.
=> Refactor the Model tracking in a module

CHANGELOG.md, internal/backends/qt/qt_widgets.rs, internal/backends/qt/qt_widgets/button.rs, internal/backends/qt/qt_widgets/checkbox.rs, internal/backends/qt/qt_widgets/combobox.rs, internal/backends/qt/qt_widgets/groupbox.rs, internal/backends/qt/qt_widgets/lineedit.rs, internal/backends/qt/qt_widgets/listviewitem.rs, internal/backends/qt/qt_widgets/scrollview.rs, internal/backends/qt/qt_widgets/slider.rs, internal/backends/qt/qt_widgets/spinbox.rs, internal/backends/qt/qt_widgets/tabwidget.rs, internal/backends/qt/qt_window.rs
Because QPainter can't be relocated.
Fixes #1230
=> Qt: do not wrap QPainter directly, but use a unique_ptr instead

CHANGELOG.md, internal/compiler/object_tree.rs, tests/cases/crashes/issue_1233_listview_const_shadow.slint
We steal the bindings for the geometry from the containing element,
so we should also take the analysis.
Fixes #1233
=> Fix BoxShadow property incorrectly considered const

examples/bash/README.md
Just a drive by docs typo fix.
=> Fix typo in bash example README

internal/core/item_tree.rs, tests/cases/focus/keyboard_focus2.slint
Empty components were not properly handled when looking for the next item to focus on. This caused e.g. the "Install" page to never get focus in cargo-ui.
This PR adds a test based on the cargo-ui interface and fixes that issue.
=> Fix focus of next item with empty components

CHANGELOG.md, internal/backends/qt/qt_widgets/combobox.rs
Bug introduced by https://github.com/slint-ui/slint/pull/1231
=> Native style: Fix crash when opening a combobox

docs/builtin_elements.md, internal/compiler/builtins.slint, internal/compiler/llr/lower_to_item_tree.rs, internal/compiler/typeregister.rs, internal/compiler/widgets/native/std-widgets.slint, internal/core/accessibility.rs, internal/interpreter/dynamic_component.rs, tests/cases/accessibility/materialized.slint
Currently, bool property are mapped to string property at runtime because
we'll avoid to extand the vtable for now, we'll consider that later
=> Accessibility: support for bool property

CHANGELOG.md, internal/backends/gl/event_loop.rs
Otherwise the timing code might think at the time of an event (eg key press)
that the starting point of an animation that starts in this event is
earlier in time than it really is. Causing the animation to appear as it
had started earlier or literaly be finished before it starts.
Fixes #1255
=> GL backend: process timing event before processing input events

internal/backends/qt/lib.rs, internal/backends/qt/qt_accessible.rs, internal/backends/qt/qt_window.rs, internal/compiler/widgets/fluent/std-widgets.slint, internal/core/accessibility.rs, internal/core/item_tree.rs
This change reports the `accessible-*` properties that are supported by
the Slint compiler to Qt's accessibility framework.
This gets Slint very basic support for screen readers and similar
technology in a cross-platform manner.
=> Implement basic support for accessibility

internal/interpreter/api.rs
Converted TryInto into TryFrom as discussed in #1258.
I also left the examples using `try_into` as is, without switching to the `T::try_from()` syntax, since they are still valid.
I used a container (podman) to build and test this, just for reference here's the commands:
```
$ podman run -it --rm -w/workspace -v$PWD:/workspace docker.io/rust:1.60.0-bullseye
```
=> Replaced TryInto with TryFrom in slint_interpreter::Value

.github/workflows/ci.yaml, CHANGELOG.md, examples/7guis/Cargo.toml, examples/7guis/cells.rs, examples/7guis/cells.slint, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, tests/cases/expr/string_concatenation.slint, tests/cases/models/array.slint, tests/cases/models/model_in_struct.slint, tests/cases/models/write_to_model_sub_component.slint, tests/cases/types/structs2.slint
I think that's more or less what is required by https://eugenkiss.github.io/7guis/tasks#cells
Some notes:
- The line edit aprears on click instead of double click since we don't yet have double click events in slint
-  the parsing is evaluated once the user edits the text instead of "finish editing" because we don't have this concept in slint yet.
- The dependency tracking was re-implmented. Would have been nice to be able to re-use the `properties` if it was exposed in public API.  That said, that would panic on cycles instead of returning some random value like we do now.
I've had to use Model of Model. Mapping from a big vector in more row model is not currently possible because one cannot implement a filter model ourselves, as the ModelChangeListenerContainer is not public.
But well, …
=> 7guis example: add logic to the cells

.github/workflows/build_docs.yaml, api/cpp/docs/language.rst, api/rs/slint/docs.rs, api/rs/slint/lib.rs, docs/builtin_elements.md, docs/builtin_enums.md, docs/widgets.md, internal/common/enums.rs, xtask/src/enumdocs.rs, xtask/src/main.rs
So that makes it harder to forget to update the docs
Note that the new builtin_enums.md does not contain a `### Values`
section header anymore. Also some enum where documented with the full
enum value (such as `TextHorizontalAlignment.left`) while now this
is omitted
The CI should fail if one forget to run `cargo xtask enumdocs` after
adding an enum or changing the docs
=> Generate the enum documentation based of the common/enums.rs

internal/compiler/passes/optimize_useless_rectangles.rs, tests/cases/crashes/issue1267_opacity_in_layout.slint
Normally, child of layout don't get optimized anyway because
the layout sets their `x` and `y` prop, preventing the optimization.
But if the rectangle has an opacity, its `x` and `y` property are
stolen by the opacity element, and then it can get optimized anyway
Fixes #1267
=> Fix compiler panic when optimizing child of layout

internal/backends/gl/event_loop.rs, internal/backends/gl/lib.rs
The previous approach of calling send_event on a timer has the disadvantage
or re-entering the event loop for every queued event. Any requested redraw
after one of those events will end up actually drawing, even if that frame could be
replaced by the next event's redraw without being shown to the user.
winit also doesn't expose publicly its web Runner send_events method that would
allow us to queue the events outside and pass them all together.
We can however queue the events inside winit by putting the event loop in
ControlFlow::Poll mode so that winit batches them itself.
This has the side effect of processing and painting those events using
requestAnimationFrame.
To achieve this we take advantage of winit processing send_event calls
synchronously, possibly while on a native event …
=> wasm: Prevent wasted redraws with multiple post_events

api/rs/build/lib.rs, internal/compiler/lib.rs, internal/compiler/passes.rs
No need to generate the code that expose the accessible property when we
target MCU, because they are dead code anyway on that platform
=> Accessibility: don't expose the properties with the MCU backend

tools/viewer/Cargo.toml, tools/viewer/main.rs
This makes it possible to see the output from the log facade in any
crates that Slint uses, using the RUST_LOG environment variable..
=> Enable the simple env logger on slint-viewer

internal/core/input.rs, internal/core/items/flickable.rs, tests/cases/elements/flickable3.slint
This is more of an POC of a fix to #1107. Basically the main idea here is to make sure that mouse events are handled as usual by child items in case of a mouse scroll event on a flickable, so they are part of the previous mouse grabber stack which is required to be included in the exit event dispatching. This works for the case shown on the video at the bottom (mouse leave) but I think it's not the most complete solution here. Probably a better solution would be to convert the scroll event to a move event as this would be more correct for the child items. I also had to move the call to `send_exit_events` after the actual event handling to be able to catch the updated scroll position in the frame it was changed and not 1 frame later. While this wasn't a huge issue when scrolling slowly, …
=> Fix mouse exit events not triggered by scrolling a Flickable

internal/backends/mcu/lib.rs, internal/backends/mcu/profiler.rs, internal/backends/mcu/renderer.rs, internal/backends/mcu/simulator.rs
The LineRenderer is going to be a public type which can be used
by the MCU board support to draw.
Right now, it is used by the old code
=> MCU: Refactor the renderer in a LineRenderer

api/cpp/include/slint_interpreter.h, api/cpp/include/vtable.h, helper_crates/vtable/src/lib.rs, internal/interpreter/ffi.rs
- Use `NonNull` so `Option<VBox<X>>` can be represented with null pointer
- Call the `drop` function from the C++ destructor.
=> vtable: Make VBox compatible with C++

tools/online_editor/index.html
This link works on the slint web site, but not when run locally. We do
not expect this to have users outside of the Slint site, so we are
willing to accept this limitation.
Please open a bug report if you indeed use the online editor elsewhere
and are bothered by the link.
=> Online editor: Add link to Slint language reference

internal/backends/mcu/renderer.rs
The slide puzzle makes use of the source-clip-* properties and that unveiled three issues:
* For the scale factor from image space to physical pixel space (sx/sy),
use the source clip size, as we're only drawing those
pixels. That means that the call sites of draw_image_impl need to pass the
correct original image size if there is no source clip.
* Similarly, the scaled_clip is in image coordinates, but needs to be relative to the source-clip-x/y
* The geometry for the target rectangle on screen
must originate at (0, 0) so that the apllication of
sx/sy only changes the size.
=> Fix rendering of source clipped images with the MCU renderer

internal/compiler/diagnostics.rs, tools/lsp/server_loop.rs
Otherwise it doesn't work with the web extension. And the file must anyway be in the cache
=> LSP: fetch the file content from cache instead of from disk to compute the line number

editor/vscode/package.json, tools/lsp/Cargo.toml, tools/lsp/main.rs, tools/lsp/server_loop.rs, tools/lsp/util.rs
So it can be disabled when building the web extension, and remove lots of dependencies.
This reduce the wasm size from 6M to 2M
=> LSP: make the preview feature optional

internal/backends/mcu/Cargo.toml, internal/backends/mcu/lib.rs, internal/backends/mcu/simulator.rs, internal/core/Cargo.toml, internal/core/lengths.rs, internal/core/lib.rs, internal/core/swrenderer.rs, internal/core/swrenderer/draw_functions.rs, internal/core/swrenderer/fonts.rs
Move the MCU renderer in the feature-gated swrenderer module in core. 
This also moves the lengths module to core, and it is not feature gated. I think we can make use of it for the text_layout and other stuff.
=> Move the software renderer to core

docs/builtin_elements.md, docs/widgets.md, internal/backends/gl/glrenderer.rs, internal/backends/qt/qt_window.rs, internal/compiler/builtins.slint, internal/compiler/widgets/common/common.slint, internal/compiler/widgets/fluent/std-widgets.slint, internal/compiler/widgets/native/std-widgets.slint, internal/core/items/text.rs
This adds read only TextInput and its derivatives (TextEdit and LineEdit) and propagate horizontal-alignment property from TextInput to TextEdit and LineEdit
Also cursor is hidden in read only mode but focus is still enabled like qt QLineEdit and QTextEdit
=> Add read only TextInput and propagate horizontal-alignment property from TextInput to TextEdit and LineEdit

internal/backends/mcu/lib.rs, internal/backends/mcu/simulator.rs, internal/core/item_rendering.rs, internal/core/swrenderer.rs
When using repeaters - like in the slide puzzle - and during renderer a component
gets deleted, we call free_graphics_resources and try to free
the dirty rectangle list in the partial renderer cache. At that point the cache is
already mutably borrowed, which causes a panic.
As remedy, apply the mutable borrow more fine grained and not right when calling
render().
=> Fix panic about multiple mutable borrows with the software renderer

internal/backends/mcu/stm32h735g.rs
Up to 400 Mhz seems to work. Also fixed assert to match the octospi controller for the hyperram (1 instead of 2).
I get asserts in the stm32h7 crate above that, although https://www.st.com/resource/en/datasheet/stm32h735ag.pdf says the CPU can go up to 550Mhz.
=> Bump system clock frequence on stm32h735

internal/backends/mcu/Cargo.toml
The ft5336 crate enforced the panic-semihosting for no apparent reason,
but this is fixed upstream now.
=> Enable panic-probe by default for stm32

internal/backends/mcu/lib.rs, internal/backends/mcu/pico_st7789.rs, internal/core/lib.rs
This makes the the Raspberry Pi Pico sleep when nothing happens and wake it with interrupts/events.
I cannot compare the performance to the previous code since I only own one pico with the display.
Perhaps you can check it for (visible) performance/responsiveness regressions by comparing it side by side with the old polling code?
=> Make the Pico use interrupts and make it sleep

api/rs/build/Cargo.toml, api/rs/build/lib.rs
This fixes compilation of generated Rust code when token stream contains
single-quoted semicolon.
When using glyph embedding, we generate a character map where each code
point is a literal char.  When the font contains a semicolon and we
generate an entry for that, we write ';' and the CodeFormatter would
think the semicolon is the end of a statement and produce a newline.
That breaks the build of the generated code.
Replace the hand-written formatter with the use of the prettyplease
crate.
=> Use prettyplease crate to do the formatting

examples/printerdemo_mcu/ui/printerdemo.slint
React on presses, not press/release on the icons on the left side of the printerdemo_mcu. That feels more reactive to me:-)
=> Printerdemo_mcu: React on press, not release events

internal/backends/mcu/Cargo.toml, internal/backends/mcu/pico_st7789.rs, internal/backends/mcu/pico_st7789/display_interface_spi.rs
The display-interface-spi crate the not flush the internal fifo between the write
and the changes of the CS and DC pins, which result of changing these pins before
the screen recieve all the data over the spi and causes artifacts on the screen.
So re-implement the logic in our crate and use `transfer` instead of `write`
which flushes the fifo correctly.
=> mcu pico: fix the screen artifacts by re-implementing display-interface-spi

internal/core/textlayout/linebreaker.rs
When concatenating two fragment, we should account for the trailing whitespace
in the previous fragment in the total width.
This fixes the "l" of "Ink level" not beoing drawn properly in the printer
demo with the partial renderer if the Text item (which is too small as a result
of this bug) does not overlap the dirty region, but part of the text still
need to be drawn outside before it overflows
=> MCU: Fix width of the text not including whitespaces

internal/core/swrenderer.rs
This ensures that the partial renderer updates correctly and this also
fixes a panic in the printer demo on the stm32h7 when opening the format
combobox in the scan page:
We would attempt to render the word "JPEG" with a font size of 12 pixels.
The letter J has a height of 12 pixels, like the font ascender reported, but it's
y coordinate is negative.
That would also result in a negative text item relative origin for the glyph (target
rect in physical pixels),
which fails to convert to an usize and panics.
=> swrenderer: clip glyphs to the text element's geometry

editor/vscode/browser-language-server/browserServerMain.ts, editor/vscode/src/browser.ts, tools/lsp/server_loop.rs
- Reload the preview when the user do changes in the imported .slint files
- Integrate with our LSP so that we add the code lense / actions to allow to preview a component.
- Only use one winit eventloop instead of always restarting one.
cc #1336
=> Improvements to the vscode web extension preview

internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/llr/expression.rs, internal/compiler/llr/pretty_print.rs, internal/compiler/passes/const_propagation.rs, tests/cases/crashes/issue1327_inlined_state_property.slint
state info properties are special and cannot simply be inlined or set
(because we need to record the time it was changed and stuff)
So disable the optimization for now.
In fact, what could be done is to remove the state entirely if the state property
is constant. But that change is a bit more involved
This patch does:
- Don't inline const state property
- Don't generate a call to .set in the generated code
- Also allowed to debug the expression with a context from the generator
(added T generic parameter to the pretty printer)
Fix panic reported in https://github.com/slint-ui/slint/issues/1327#issuecomment-1151244049
=> Don't optimize const state property

internal/backends/gl/glrenderer.rs, internal/backends/gl/images.rs
In preparation for moving the image decoding and caching of decoded
image data into the core library, change the texture cache to be really
a cache of textures. Previously it cached Rc<CachedImage>, which could
have also been just a CPU side image. However this was "run-time"
asserted. Instead, with this patch it's an `Rc<Texture>` and that will
always be GPU side.
=> Clean up texture caching in the GL renderer

editors/vscode/package.json, editors/vscode/src/browser.ts
This also enable the `retainContextWhenHidden` which will make sure
the state of the preview (eg, the currently visible tab) is kept when
the preview tab is hidden.
=> vscode web extension: preserve the slint preview accross restart

internal/backends/gl/event_loop.rs, internal/backends/gl/glwindow.rs, internal/backends/mcu/simulator.rs
This fixes #1269.
It introduces a size property to WinitWindow, that in contrast to winit::Window::inner_size() represents the sizes that are actually already processed by slint's event handling.
The problem did occur since the inner_size() value was returning the latest window size even if a previous Resize event (resizing to an earlier size) was still being processed. This discrepancy caused the jittering.
=> Fix resize jitter bug on macOS with GL Backend

internal/backends/gl/fonts.rs
Fix a logic bug in the function to determine if we need to fall back to
other fonts or if the font we selected provides complete coverage.
In the common case where coverage is given, we start with some unknown
coverage (in old_uncovered_*) and end up with empty
remaining_required_*_coverage. That also happens to be less than
old_uncovered_*. Since that check came first, we always returned
"Improved", which meant we still built up the font fallback list, even
though we didn't need to. Fix the order of checks to avoid that.
=> GL backend: reduce memory allocations for text rendering

internal/backends/mcu/lib.rs, internal/backends/mcu/simulator.rs, internal/backends/mcu/stm32h735g.rs, internal/core/item_rendering.rs, internal/core/swrenderer.rs, internal/core/swrenderer/draw_functions.rs
It doesn't do line by line anymore, trying to avoid allocating memory for the scene
Note: currently, this is slower than the line by line renderer on STM32H735, need to investigate why.
=> swrenderer: Add a renderer that operate dirrectly onh the frame buffer

CHANGELOG.md, docs/builtin_elements.md, docs/widgets.md, examples/gallery/gallery.slint, internal/backends/qt/qt_accessible.rs, internal/backends/qt/qt_widgets/button.rs, internal/compiler/builtins.slint, internal/compiler/typeregister.rs, internal/compiler/widgets/fluent/std-widgets-impl.slint, internal/compiler/widgets/fluent/std-widgets.slint, internal/compiler/widgets/native/std-widgets.slint, internal/core/accessibility.rs, tests/cases/elements/togglebutton.slint
Add flags that enable the Button to be used as a Toggle, e.g. for use in toolbars or similar places.
=> Button: Implement support to make the Button a toggle

internal/compiler/generator/cpp.rs, internal/compiler/passes.rs, internal/compiler/passes/check_aliases.rs, internal/compiler/passes/lower_states.rs, internal/compiler/passes/lower_tabwidget.rs, internal/compiler/tests/syntax/lookup/two_way_binding_warning_compat.slint, internal/compiler/tests/syntax_tests.rs, internal/core/properties.rs, internal/interpreter/dynamic_component.rs, tests/cases/bindings/two_way_priority.slint, tests/driver/rust/build.rs
Because of issue #1394 and because the semantic are not properly defined
currently, we decided that future version of slint should always and only
take the binding from the right hand side, even if it has no bindings.
Since we can't change the behavior in 0.2, just add a warning instead for now.
The warning can be silenced by setting a default binding for the property on the rhs.
Ignoring the warning can still lead to panic (the one in #1394)
=> Add a warning when setting a two way binding for which the rhs does not declare a default value

internal/backends/gl/glrenderer.rs, internal/core/item_rendering.rs
Now that we store the layer textures as Rc<Texture>, before rendering a
layer we can take a clone of a possibly existing layer texture and if if
the layer's tracker is dirty, we can re-use the existing layer texture
if it's the same size.
This avoids unnecessary texture allocations.
=> GL backend: speed up updates to layer content

api/cpp/CMakeLists.txt, api/cpp/cmake/SlintConfig.cmake.in, api/cpp/cmake/SlintMacro.cmake
Keep the default if unset, otherwise use whatever SLINT_STYLE was passed
=> C++: don't force the SLINT_STYLE cmake variable

internal/backends/qt/qt_accessible.rs, internal/core/properties.rs, internal/core/window.rs
The handler is called whenever the properties it depends on becomes dirty,
not when it changes.
This has caused confusion before, so rename it
=> Rename PropertyChangeHandler to PropertyDirtyHandler

internal/compiler/widgets/common/common.slint, internal/compiler/widgets/fluent/std-widgets-impl.slint
The widget should not reach into the NativeStyleMetrics directly,
it should get the information from the StyleMetrics which return
the right value (which is not dark style, for the fluent style)
=> Fix the AboutSlint in fluent style with dark style desktop

internal/compiler/passes/binding_analysis.rs, internal/compiler/tests/syntax/analysis/binding_loop2.slint
This is the most basic loop and we wouldn't show a signal.
Turn out the comment was wrong and we do not seem to emit the error
twice for two ways binding to itself
Fixes #1407
=> Detect loop on the property itself

internal/backends/gl/glwindow.rs, internal/backends/mcu/lib.rs, internal/backends/qt/qt_window.rs, internal/backends/testing/lib.rs, internal/core/items/text.rs, internal/core/window.rs
Every backend will do something different with the string that needs to go into the clipboard.
Qt will convert it to a QString, copypasta to a String, in theory it could be written
directly to a socket.
Given that we don't know what the perfect representation on the backend side is, passing
a string slice avoids any immediate conversions.
=> Change `set_clipboard_set` to take a `&str` instead of a `String`

api/rs/slint/lib.rs, internal/backends/gl/event_loop.rs, internal/backends/gl/glwindow.rs, internal/backends/gl/lib.rs, internal/backends/gl/wasm_input_helper.rs, internal/backends/mcu/lib.rs, internal/backends/mcu/simulator.rs, internal/backends/qt/lib.rs, internal/backends/qt/qt_accessible.rs, internal/backends/qt/qt_window.rs, internal/backends/testing/lib.rs, internal/compiler/generator/rust.rs, internal/core/api.rs, internal/core/backend.rs, internal/core/graphics/rendering_metrics_collector.rs, internal/core/swrenderer.rs, internal/core/window.rs, internal/interpreter/api.rs, internal/interpreter/dynamic_component.rs
We already have `api::Window` and also the Window element (`WindowItem`) so rename the inner part to avoid confusion.
Also use the public window more in the interfaces.
=> Rename `i_slint_core::window::Window` into `WindowInner` and use the public Window in the interface

internal/backends/gl/event_loop.rs, internal/backends/gl/glwindow.rs, internal/backends/gl/renderer/femtovg.rs, internal/backends/mcu/simulator.rs
Just like the software renderer, query the background color when rendering
and use it as clear color.
In the simulator this was an unused field (because the sw renderer already does the right thing).
=> Clean up the background color handling in the GL backend

internal/backends/gl/event_loop.rs, internal/backends/gl/glwindow.rs, internal/backends/gl/lib.rs, internal/backends/mcu/Cargo.toml, internal/backends/mcu/lib.rs, internal/backends/qt/lib.rs, internal/backends/qt/qt_window.rs, internal/backends/testing/lib.rs, internal/core/backend.rs, internal/core/items/text.rs, internal/core/window.rs
Found a way to connect the clipboard to the wayland display through the winit event loop target.
=> Move the clipboard back from the Window to the Backend trait

internal/backends/mcu/lib.rs, internal/core/renderer.rs, internal/core/swrenderer.rs, internal/core/window.rs
This means we will query the size of the popup also for the GL backend
even if the backend don't need to be marked dirty, but that should be
alright.
=> Move the init_dirty_region dirrectly into the Renderer

.github/workflows/ci.yaml
After commit 894ee5aa9118d9eb72cb4c66907c8cf5c0242dc4 we weren't running the nodejs tests,
because we don't pass --workspace to cargo test.
This patch fixes that and also ends up running the other previously non-run unit
tests such as for the vtable crate.
=> Fix Node tests in the CI

internal/backends/qt/build.rs, internal/backends/qt/qt_widgets/groupbox.rs
Take the label into account when calculating layout info for the native groupbox.
This matches the layout produced by a native Qt application much better and fixes the gallery demo with native style:
The "Button (checkable)" GroupBox is much wider with this change -- much like a similar UI looks in Qt designer.
=> Qt groupbox minimum size fix

.github/workflows/ci.yaml, .github/workflows/cpp_package.yaml, .github/workflows/nightly_snapshot.yaml, .github/workflows/slint_tool_binary.yaml
This includes a newer version of Visual Studio.
This is needed for #1447.
Unfortunately this disables the NodeJS bindings build on Windows - see also #961.
=> Upgrade the CI to Github's windows-2022 image

internal/backends/qt/qt_window.rs, internal/backends/winit/renderer/femtovg/itemrenderer.rs, internal/core/item_rendering.rs, internal/core/items/path.rs, internal/core/swrenderer.rs
When the renderer does not re-implement visit_clip, we call combine_clip.
Then we're missing out on an optimization the GL renderer does: When the resulting clip region
is empty, we do not need to recurse into children for rendering.
That itself reduces the property dependency chain and avoids unnecessary
updates when invisible (clipped) children change properties.
=> Speed up rendering of clipped children

api/cpp/CMakeLists.txt, api/cpp/Cargo.toml, api/rs/slint/Cargo.toml, internal/backends/selector/Cargo.toml, internal/backends/selector/lib.rs, internal/backends/winit/Cargo.toml, internal/backends/winit/glwindow.rs, internal/backends/winit/lib.rs, internal/backends/winit/renderer/femtovg.rs, internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/skia/itemrenderer.rs, internal/backends/winit/renderer/skia/textlayout.rs, internal/interpreter/Cargo.toml, tools/lsp/Cargo.toml, tools/viewer/Cargo.toml
As part of #1445, this merges the initial Skia renderer into the winit backend. It's not enabled by default.
In the CI this is built on macOS, Windows and Linux, but as per #1445 there are some caveats left, feature and build system wise.
=> Merge initial Skia renderer

internal/backends/winit/renderer/skia/itemrenderer.rs
Colorization is typically implemented using an intermediate layer and since
usually it doesn't change so often, it's faster to cache the result in the existing SkImage cache
per Image item.
Coincidentally this also fixes #1448
=> Skia: Cache the result of colorizing an image

tools/lsp/main.rs, tools/lsp/server_loop.rs
Some small patches for the LSP to prepare for adding more commands to execute.
Especially the last one in nice to have: It reports errors in the command execution back to the client instead of killing the language server.
=> Lsp prepare

internal/backends/mcu/simulator.rs, internal/backends/winit/event_loop.rs, internal/backends/winit/glwindow.rs, internal/core/api.rs, internal/core/window.rs
… module
This field duplicates the winit window's inner size. It is set on a
WindowEvent::Resized(), after which
`winit::window::Window::inner_size()` returns the same value.
=> winit: Remove unused existing_size field

internal/backends/winit/event_loop.rs, internal/backends/winit/glwindow.rs, internal/backends/winit/lib.rs, internal/backends/winit/renderer/femtovg.rs, internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/skia/opengl_surface.rs
This merge request introduces a Surface abstraction behind which we can hide the OpenGL code and in the future Metal, Direct3D and Vulkan.
=> Separate the OpenGL specific Skia code from the generic Skia code

docs/tutorial/rust/src/creating_the_tiles_from_rust.md
=> Remove unnecessary character in tutorial

internal/backends/winit/event_loop.rs
Commit 0ee361d994dd8cb0be20c8b03cc9ae459a16ce4f regressed on
https://github.com/slint-ui/slint/issues/1269 as the inner_size()
returned at the time during event processing is already the future
value, that will change again when processing the resize event.
Instead of storing the last received value, process the event at the
appropriate MainEventsCleared stage.
=> winit: fix jitter on macos again when resizing windows

internal/compiler/builtins.slint, internal/compiler/passes.rs, internal/compiler/passes/lower_property_to_element.rs, internal/compiler/typeregister.rs, internal/core/items.rs
The rotation-angle/rotation-origin-x/y properties are lowered to an
injected Rotate element, that we already had.
This needs further fixes for transforming input events and an
implementation of rotation in Skia.
=> Revive support for rotation of elements

CHANGELOG.md, internal/core/input.rs, internal/core/items/text.rs, tests/cases/text/cursor_move.slint
=> Add missing shortcuts for delete word forward and backwards

api/node/native/lib.rs, helper_crates/vtable/macro/macro.rs, internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/skia/cached_image.rs, internal/backends/winit/renderer/skia/itemrenderer.rs, internal/core/Cargo.toml, internal/core/graphics/image.rs, internal/core/graphics/image/cache.rs, internal/core/graphics/image/htmlimage.rs, internal/core/graphics/image/svg.rs
Because re-generating the Skia image is slow and there is no point
storing both the image buffer and the SkiaImage in the cache as it
is basically the same information.
This speeds up the switching to the berlin theme in the slide_puzzle 
CC  #1445
=> Skia: Cache the Skia image in the core image cache

.github/workflows/wasm_editor_and_interpreter.yaml, .reuse/dep5, tools/online_editor/.eslintrc.yml, tools/online_editor/highlighting.ts, tools/online_editor/index.ts, tools/online_editor/monaco_worker.js, tools/online_editor/package.json, tools/online_editor/preview.ts, tools/online_editor/tsconfig.json, tools/online_editor/vite.config.js, xtask/src/license_headers_check.rs
Reformat the code and config files, set up linting, update typescript version, set up TS to find all the modules, enable `strict` mode in TS, fix all issues reported by tsc in strict mode, have a npm script to run `tsc --noemit` as recommended by vite.
I do not expect any of this to cause problems in CI as these changes.
=> Online editor: Cleanup TS setup

internal/compiler/passes/lower_states.rs, internal/compiler/tests/syntax/lookup/issue_1461.slint
Some binding can't be express with the current data structures because
they reference propertis within inner elements within a component.
The fix is a bit involved and the best is to have an error istead of a
panic, for now.
=> Workaround for issue #1461

internal/compiler/passes.rs, internal/compiler/passes/lower_property_to_element.rs
Instead of automatically mapping property bindings if the initial property has a `-` infix,
supply the list of all properties as a parameter.
=> Make the property to element lowering a little less magic

internal/compiler/generator/rust.rs
We use `const` for the embedded data, which doesn't guarantee a fixed location in memory.
For the image cache when embedding (encoded) image data, we rely on a fixed address.
I observed that in debug builds of the slide puzzle, the embedded data is not always
reported to be at the same address, presumably due to inlining. This makes
the theme switching a bit slower and the cache less efficient.
This patch fixes that by using static instead of const, to guarantee a fixed location in memory.
(This was not observed in release builds, but in theory it could happen there as well?)
=> Fix the image cache with rust generated code and debug builds

internal/backends/mcu/lib.rs, internal/backends/mcu/pico_st7789.rs, internal/backends/mcu/simulator.rs, internal/backends/mcu/stm32h735g.rs, internal/core/swrenderer.rs
Instead, put the dirty buffer handling from the previous frame directly
in the SoftwareRenderer
=> swrenderer: Remove the DirtyRegion from the API

.github/workflows/ci.yaml, .github/workflows/cpp_package.yaml, .github/workflows/slint_tool_binary.yaml
python3 -m pip install py7zr==0.16.1 failed with mysterious errors about package conflicts.
Upgrade to the version that the next version of the install-qt-action seems to
to going to use.
=> Prospective fix for failing install-qt-action in the CI on macOS

internal/backends/winit/lib.rs, internal/backends/winit/renderer/boxshadowcache.rs, internal/backends/winit/renderer/femtovg/itemrenderer.rs, internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/skia/itemrenderer.rs, internal/core/graphics/color.rs
When using box shadows in repeaters, we end up creating multiple
distinct textures of the drop shadow. That's a waste of precious texture
memory if they have the same properties.
Instead, when creating box shadows in a frame, see if they can be
re-used across images.  The texture still persistent in the image_cache,
via the explicitly shared skia_safe::Image and Rc<Texture>.
This works well when rendering repeated elements new top-down, but it's
not perfect.  For example if a bunch of repeated elements are in a
flickable, only a portion of them are visible and the view is scroll up,
then the top-down rendering will not find a cache hit for the newly
visible element with drop shadows. Yet this is simple enough to help
with sharing in many cases.
=> Skia/FemtoVG: implement re-use of box shadow textures

api/cpp/lib.rs, api/rs/slint/lib.rs, internal/backends/mcu/lib.rs, internal/backends/mcu/pico_st7789.rs, internal/backends/qt/lib.rs, internal/backends/selector/lib.rs, internal/backends/testing/lib.rs, internal/backends/winit/lib.rs, internal/core/animations.rs, internal/core/api.rs, internal/core/graphics/image/htmlimage.rs, internal/core/items/text.rs, internal/core/lib.rs, internal/core/platform.rs, internal/interpreter/api.rs, internal/interpreter/dynamic_component.rs, tools/lsp/preview.rs, tools/viewer/main.rs
This changes the way the platform abstraction is initialized
=> Make the PlatformAbstraction not Send using a EventLoopProxy trait

.github/workflows/nightly_snapshot.yaml
The base of `.` leads to assets importing other assets from
`./assets/...`.
So add a symlink to work around that issue. The proper fix is of course
to make vite generate the correct URLs.
=> Nightly: Work around relative base path in vite config

examples/mcu-board-support/pico_st7789.rs, examples/mcu-board-support/stm32h735g.rs, internal/backends/winit/renderer/sw.rs, internal/core/swrenderer.rs, internal/core/swrenderer/draw_functions.rs
Closes #1545
Not that `SoftwareRenderer::new()`  takes the Weak by value instead of
by reference, because coercing a reference to a `Weak` to a `&Weak<dyn>`
is not possible, while converting a Weak to a `Weak<dyn>` just works.
=> Sofware renderer: keep a Weak of the Window

internal/compiler/builtins.slint, internal/core/items.rs
For example
Image {
x: 150px;
y: 50px;
rotation-angle: 45deg;
}
will end up rendering as if x and y are zero. This is because during
the injection we "move" x and y to the Rotate
element as bindings, but due to the lack of built-in
x/y properties, dummy properties are materialized
and they are not applied for the regular per-item translation.
Add x/y to the Rotate element and then it works.
=> Fix element rotation when the element is translated

examples/mcu-board-support/pico_st7789.rs, examples/mcu-board-support/stm32h735g.rs, internal/core/platform.rs, internal/core/swrenderer.rs, internal/core/window.rs
This simplifies the implementation of the pico and STM, as they both
have the same PlatformWindow implementation, and is likely to be the
same for every MCU
=> Introduce MinimalSoftwareWindow

tools/online_editor/src/index.ts, tools/online_editor/src/proxy.ts
The LSP running in the web worker needs to access (virtual) files in the
editor. So it can send a request to the editor for files.
Handle such requests. Also make sure to provide the editor with the
correct URLs of open files so that the base URL to request additional
data with is correct.
Also do not error out when LSP and interpreter request the same file
concurrently.
=> online_editor: Implement custom "slint/load_file"

tools/online_editor/package.json
wasm-pack defaults to a release build, an explicit --dev is needed.
=> Fix debug build of wasm modules in the online editor

internal/backends/qt/lib.rs, internal/backends/winit/event_loop.rs, internal/backends/winit/lib.rs, internal/core/platform.rs, tools/lsp/preview.rs
For the winit backend, also make the function work after a call to run()
=> Rename set_event_loop_quit_on_last_window_closed to remove EventLoopQuitBehavior

internal/backends/winit/renderer/sw.rs, internal/core/swrenderer/draw_functions.rs
Closes #1540
(Went or Rgb8Pixel instead of color, because color can have alpha)
Also fix an overflow in the rgb565 pixel blending
=> Rgb565Pixel: remove color accessor, add conversion to Rgb8Pixel

tools/lsp/main.rs, tools/lsp/properties.rs, tools/lsp/server_loop.rs, tools/lsp/test.rs, tools/lsp/wasm_main.rs
Implment a command in the LSP that can be used to query all known
properties, where those are declared and defined.
With this information we should be able to provide an property editor in
IDEs.
----
This shows how the necessary information can be extracted in our LS implementation. I would appreciate feedback on that!
The output is still very much in flux: I think it has the interesting bits it needs now, but how to best present that information depends on work on the language server client side. E.g. it will probably make sense to return proper LSP types holding `url`, `line` and `column` offsets instead of `filename` and `offset`.
I should also not break filenames by turning them into strings, but considering that URLs are used to pass file names between LS client and server this might …
=> LSP: Implement a queryProperties command

api/rs/slint/Cargo.toml, examples/mcu-board-support/Cargo.toml, examples/mcu-board-support/pico_st7789.rs, examples/mcu-board-support/stm32h735g.rs, internal/core/Cargo.toml, internal/core/platform.rs, internal/core/tests.rs
This way we don't have to add defmt, esp32-println and others as features to corelib and the slint api crate
(which would also expose them as public dependencies),
but instead this can be simply delegated to the Platform trait.
=> Replace the built-in defmt debug logging to the platform trait

api/cpp/CMakeLists.txt, api/cpp/Cargo.toml, api/rs/slint/Cargo.toml, internal/backends/selector/Cargo.toml, internal/backends/winit/Cargo.toml, internal/backends/winit/build.rs, internal/backends/winit/glcontext.rs, internal/backends/winit/lib.rs, internal/backends/winit/renderer/skia.rs, internal/interpreter/Cargo.toml, tools/lsp/Cargo.toml, tools/viewer/Cargo.toml
When opting into the Skia renderer, we default to metal on macOS and D3D on Windows.
However if you want to develop a cross-platform application with Skia and
for example rely on OpenGL to be able to implement an OpenGL underlay or overlay,
then we need the ability to explicitly opt into skia's GL renderer.
cc #1445
=> Skia: Make it possible to explicitly select the OpenGL backend of Skia

internal/core/api.rs, internal/core/window.rs
- We must first set change the constraints before changing the size
otherwise the new size might not be in the old constraint and the
change might not take effect.
- We must update the WindowItem's size even if the size of the window
doesn't change. This happens when a component is set on a window that
that doesn't change it size (eg, preview) but for which we need to
set the geometry on the window
=> Try to fix the way the window is resized

internal/core/textlayout.rs, internal/core/textlayout/fragments.rs, internal/core/textlayout/glyphclusters.rs
The AboutSlint text has a forced linebreak in it, which becomes a box
glyph on MCUs when the font on the host system doesn't use an empty
glyph but a box glyph for \n.
This patch explicitly excludes glyph clusters from text fragments that
feed into lines that originate from one of the three valid separators:
ascii newline, unicode paragraph and unicode line separators.
=> Fix "glyph box" in AboutSlint when rendered on MCU

api/node/native/lib.rs, api/rs/slint/lib.rs, api/rs/slint/private_unstable_api.rs, internal/backends/qt/qt_accessible.rs, internal/backends/qt/qt_widgets.rs, internal/backends/qt/qt_widgets/spinbox.rs, internal/backends/qt/qt_widgets/tabwidget.rs, internal/backends/qt/qt_window.rs, internal/backends/winit/event_loop.rs, internal/backends/winit/glwindow.rs, internal/backends/winit/renderer/femtovg.rs, internal/backends/winit/renderer/femtovg/itemrenderer.rs, internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/skia/itemrenderer.rs, internal/backends/winit/wasm_input_helper.rs, internal/compiler/generator/rust.rs, internal/core/api.rs, internal/core/items.rs, internal/core/items/text.rs, internal/core/swrenderer.rs, internal/core/tests.rs, internal/core/window.rs, internal/interpreter/api.rs, internal/interpreter/dynamic_component.rs, internal/interpreter/eval.rs
The reversal of ownership removes the need for this glue.
cc #1502
=> Replace the internal `WindowHandleAccess` trait with a doc-hidden inner() function on Window

api/rs/slint/Cargo.toml
We do that by using the `dep:` trick in the Cargo.toml
=> Move the documentation of the `log` feature before the backends

api/wasm-interpreter/src/lib.rs, internal/backends/winit/glwindow.rs, tools/online_editor/index.html, tools/online_editor/src/index.ts
There's a memory leak that causes the created canvas elements not be
deleted.  I've tried a few thing such as explicitly hiding the window
(destroying the canvas element instance refs and gl resources we keep in
Rust), but it's not enough - somewhere there remains a circular
reference. Possibly between some of the closures installed in Rust and
DOM elements they are installed on as event handlers.
I also tried using the wasm-bindgen support for weak refs, but no luck.
So instead, to plug the leak, this patch introduces the re-use of the
HTML canvas element in a way that is similar to how the preview works in
vs code's live preview.
I verified that no GL resources or new canvas elements are leaked in
Chrome's heap profiler via snapshot comparison and filtering for the
corresponding DOM …
=> Fix console errors in the online editor about GL context losses after some editing

editors/vscode/src/browser.ts
Similar to commit d9efc95ddabc2b2027bf898ddb29513f8f9c844f, re-use the canvas element when updating the preview.
=> Fix duplicate and leaked canvas instances in the vs code web preview

internal/core/textlayout.rs, internal/core/textlayout/linebreak_simple.rs, internal/core/textlayout/shaping.rs
This change makes the test pass without the unicode feature.
Note that it is not possible to run the test without the unicode feature unless one changes the Cargo.toml, so I did that locally to run the tests
=> Fix software renderer line breaker without the unicode feature

internal/backends/winit/renderer/femtovg/fonts.rs, internal/backends/winit/renderer/femtovg/itemrenderer.rs
=> femtovg backend: fix the cursor position when the text ends with '\n'

internal/backends/qt/qt_window.rs, internal/backends/winit/glwindow.rs
We need to assign the width beofre computing the preferred height otherwise zero or very small value can be assumed and it will case the text engine return a huge preferred height.
Testcase:
```
export App := Window {
VerticalLayout {
padding: -10px;
Text {
text: "Lots of text with\nnewlines etc.\n lorem ipsum dolor sit amet";
wrap: word-wrap;
}
}
}
```
In particular, this fixes the gallery window size being too high when using the skia renderer, because when given a zero width, skia return a big size for the height, (contrary to the Qt backend that consider 0 as infinite, or the femtovg backend that will stop rendering once a line can't fit)
Replaces #1621
=> Fix the initial window size when the height depends on the width

internal/backends/winit/event_loop.rs
The regression happened when upgrading winit as they added support for IME
=> Winit: fix entering of character containing dead key

internal/interpreter/api.rs
Window::show calls apply_window_property, and that's not called if one dirrectly call the WindowAdapter::show
=> Intepreter: fix the window icon and title not being updated

internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/skia/itemrenderer.rs, internal/backends/winit/renderer/skia/textlayout.rs
Skia understands glyph offsets, not byte offsets, so the conversion must be made
=> Skia: fix the cursor computations

api/cpp/include/slint.h, api/cpp/include/slint_point.h, api/cpp/include/slint_size.h
They used to declared by `using` before, so they were too easy to convert into.
=> c++: Turn (Logical|Physical)(Size|Position)` into structs

.github/workflows/ci.yaml, examples/mcu-board-support/README.md, examples/printerdemo_mcu/Cargo.toml, examples/printerdemo_mcu/main.rs
- rename the mcu-simulator feature to just "simulator" (the mcu is redundent)
- Don't forward other feature than the simulator from the board support crate. (i don't want to have to forward all features from all examples)
- default to the simulator (doesn't compile without any feature otherwise, leads to error in rust-analyzer)
=> printerdemo_mcu: tweak the features

.github/workflows/ci.yaml
No need to test the versions in the 0.2 range since the updater has not changed much in that time.
=> github: Use slint 0.3.0 as basis to run updater_test

tools/lsp/Cargo.toml
We don't use it anyway when building on wasm.
A recent update of the textwrap crate to depends on the terminal_size crate which itself depends on the errno crate that doesn't build with wasm.
So this should fix the CI
=> Don't depend on `clap` in wasm build

internal/core/input.rs, internal/core/items/flickable.rs, internal/core/platform.rs, internal/core/tests.rs, internal/core/timers.rs, internal/core/window.rs, tests/cases/elements/flickable.slint
It was reported an annoying visual bug when flicking over a listview with item that has a special effect on pressed, that the items would show "pressed" for a brief instant.  This patch add a small delay before sending the press event to the children.
The FIXME in the test is not a regression. (This happens because we send Exited event to the children when flicking, despite the mouse is still in the area)
Added a update_timers_and_animations from slint_mock_elapsed_time so we don't have to call update_timers_and_animations ourselves in the test anymore to fire the timers (it was previously only touching the animation property)
=> Add a 100ms delay before forwarding the event in a Flickable

.github/actions/install-linux-dependencies/action.yaml, .github/actions/install-nodejs/action.yaml, .github/workflows/build_docs.yaml, .github/workflows/ci.yaml, .github/workflows/cpp_package.yaml, .github/workflows/crater.yaml, .github/workflows/nightly_snapshot.yaml, .github/workflows/wasm_editor_and_interpreter.yaml
Both were used in several places and might benefit from being configured in one central place.
The nodejs action will always install npm-gyp on Windows now. We only did that in one place before. I think that makes sense to do in case we ever need to build extra modules on windows. Not that we do many Node installs on windows in our CI in the first place:-)
=> GH Actions: Define an action to handle Linux package and nodejs installs

internal/compiler/passes/binding_analysis.rs, tests/cases/crashes/issue1659_combobox_in_tab.slint
in the funciton `visit_layout_items_dependencies` we were passing a NamedReference for a property that could have been in the base component type of an element, instead of in one of the element within the current visited component. This would result in wrong computation done later to find out the "element path" of the property. We then need to tell the visitor that the named reference is in a sub component. To do that, we need to visit a PropertyPath instead of just a NamedReference
Issue 1659 was showing one of the symptoms of this, which was an assert. But it could also result in wrong analysis (binding loop not detected when it should or vice versa)
Fixes #1659
=> Dependency analysis: properly visit layout properties

internal/backends/winit/event_loop.rs, internal/backends/winit/glcontext.rs
A resize of the HTML canvas element would trigger our own resize handler, which tried to do a special dance to trigger a redraw.
As it turns out, this breaks with current winit as the event loop target is gone, so calling with_window_target() panics.
See also commit 8b728df021cfe86830b3f45fe0c4fd707e9ea7cc
Instead, this patch reverts to the simpler method of calling invoke_from_event_loop, has workarounds for how to properly wake up the event loop and return poll. In there we can just call request_redraw() on the winit window directly to trigger a draw.
=> Fix panic in online editor when resizing the preview widget

tools/online_editor/src/preview_widget.ts
When called the first time, we would just throw an exception and never resolve the promise.
=> online editor: Make render() on the preview widget always succeed

tools/online_editor/src/preview_widget.ts
We can store the promise that wasm bindgen generates to initialize glue code and simply await on it as needed. Calling then() on a fullfilled promise will just resolve to the promise result.
=> online editor: simplify slint wasm bindgen glue initialization

tools/online_editor/src/editor_widget.ts, tools/online_editor/src/index.ts, tools/online_editor/src/lsp_integration.ts, tools/online_editor/src/properties_widget.ts, tools/online_editor/src/worker/lsp_worker.ts, tools/online_editor/styles/content.css
Add a simple widget showing the properties for the current Element.
=> online_editor: Add properties viewer

tools/online_editor/src/editor_widget.ts, tools/online_editor/src/index.ts, tools/online_editor/src/lsp_integration.ts, tools/online_editor/src/properties_widget.ts
* Use an alias for the signature of the property data notifier
* Replace the onQueryText interface from the editor and instead provide an object with the property data notifier. That way no second connection between editor and properties widget needs to be established, everything is provided in the one callback.
(This could also be simply a closure, instead of an interface implementation)
=> Clean up properties and editor widget dependencies

internal/backends/winit/renderer/skia/cached_image.rs, internal/backends/winit/renderer/skia/itemrenderer.rs
Suppose we render an SVG at 100px x 100px with a screen scale factor of 2. Consequently we should be rendering the SVG at 200phx x 200phx, not 100x100.
Do this by applying the scale factor, just like it is done in the femtovg renderer.
=> Skia: fix quality of SVG images when using scale factor

internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/skia/cached_image.rs, internal/backends/winit/renderer/skia/itemrenderer.rs, internal/backends/winit/renderer/skia/textlayout.rs, internal/core/lengths.rs, internal/core/software_renderer.rs, internal/core/software_renderer/draw_functions.rs, internal/core/software_renderer/fonts.rs
Reduce the changes of mixing up values between the two coordinate systems by using separate types, just like in the software renderer.
=> Skia: Use different types for physical and logical lengths

internal/core/platform.rs, internal/core/tests.rs, tools/lsp/Cargo.toml, tools/lsp/wasm_main.rs
Previously, any use of our internal debug_log!() macro would require a platform backend to be initialized. This was confusing when debugging something in the (headless) wasm lsp implementation and nothing showed up on the console.
Now if we can, we will always log. If a platform backend exists, we route through it, otherwise we can do the fallback ourselves.
=> Improve internal default logging behavior with std

tools/online_editor/src/editor_widget.ts, tools/online_editor/src/index.ts, tools/online_editor/src/preview_widget.ts, tools/online_editor/src/properties_widget.ts, tools/online_editor/src/welcome_widget.ts
Save the dock layout state into local storage and restore it on next start-up.
This shuffles all the code managing the panels around a bit: They all can get closed now and they can all be opened again via the menu. Their actual layout can also be saved (which will save it into the local browsers storage) and will then be restored on start.
That makes the online editor quite a bit more usable IMHO.
=> online_editor: Save/restore/reset dock layouts

docs/building.md, examples/plotter/Cargo.toml, internal/backends/winit/Cargo.toml, internal/backends/winit/build.rs, internal/backends/winit/renderer/femtovg/fonts/fontconfig.rs, internal/compiler/Cargo.toml, internal/compiler/build.rs, internal/compiler/passes/embed_glyphs/fontconfig.rs
to use `dlopen` for fontconfig instead of linking fontconfig at build time. This allows for easier cross compilation, which I am using to cross compile from x86_64-unknown-linux-gnu to aarch64-unknown-linux-gnu with [cross](https://github.com/cross-rs/cross):
Blocked by:
=> switch to yeslogic-fontconfig-sys from servo-fontconfig

tools/online_editor/src/editor_widget.ts, tools/online_editor/src/preview_widget.ts
Enable code navigation between open files.
E.g. go to definition for "Homepage" in the printer demo's main page does work now. It used to open a new tab with the source code in it before.
=> online_editor: Code navigation between files

internal/backends/qt/qt_window.rs
This adds initial support for using input methods on desktop platforms when using Qt.
Closes #1706
=> Initial input method support for the Qt backend

internal/compiler/passes/binding_analysis.rs, internal/compiler/tests/syntax/analysis/binding_loop_layout3.slint, tests/cases/crashes/alias_in_if.slint
Given an element in a layout, we must visit the properties in the repeated component, not the dummy repeated element.
The panic is a regression since e7506e0d2a14285a246f73cbb1ec4b282ce20421, but the missing binding loop detection was there before
=> Fix panic when doing binding analysis of properties in repeater in layout

internal/compiler/passes/focus_item.rs, internal/compiler/tests/syntax/focus/focus_invalid.slint
Caused a crash of the LSP when having invalid element in the forward-focus property
=> Fix panic when the forward-focus expression is invalid

internal/backends/winit/renderer/femtovg/images.rs, internal/backends/winit/renderer/femtovg/itemrenderer.rs, internal/core/graphics/image.rs, internal/core/graphics/image/htmlimage.rs
SVGs are rendered using HTML image elements, that are converted to textures. The size of the texture defaults to the SVGs viewbox, which may be small - despite it being possible to render the SVG at a higher resolution with great quality.
Similar to the native code path, this patch also uses the target image size and propagates it to the DOM HTML image element to instruct the browser to render the SVG at a higher resolution.
=> Fix quality of SVG rendering in the online editor

internal/backends/qt/qt_widgets/stylemetrics.rs, internal/compiler/widgets/fluent/std-widgets-impl.slint
This is computed via the fluent theme designer by swapping text and background.
=> Add a dark theme for the fluent style

internal/compiler/passes/collect_structs.rs, tests/cases/types/structs2.slint
Prevent compilation error in the generated code when dealing with empty array expression of a given type, which is otherwise optimized out
Fixes #1733
=> collect_structs: Also visit the type of array expression

examples/carousel/rust/Cargo.toml, examples/carousel/rust/build.rs, examples/carousel/rust/main.rs
then we just enable the support for the pico with --features=mcu-board-support/pico-st7789
=> carousel: use "mcu-board-support" as feature name, so it is easier to use

tools/lsp/Cargo.toml, tools/lsp/properties.rs, tools/lsp/server_loop.rs, tools/lsp/util.rs, tools/online_editor/src/editor_widget.ts, tools/online_editor/src/lsp_integration.ts
Use the zero-line based lsp range/position types for the QueryProperties lsp command results and convert them to monaco editor ranges for correct text extraction.
=> Online editor: Fix binding expression text shown in the properties view

internal/compiler/langtype.rs, internal/compiler/object_tree.rs, internal/compiler/typeregister.rs, tools/lsp/properties.rs, tools/lsp/server_loop.rs
Group property from the base class they are defined, and for built in property, group them by category.
Also filter callback and other reserved properties that are not valid for some elements.
Other fixes: 
- We should try to keep bindings in the Element even if the base type  is invalid
- Fix querying the element at a position in case it is not in the last component of a file
=> lsp: Group and sort properties in the property extension call

internal/backends/qt/qt_window.rs, internal/backends/winit/renderer/femtovg/itemrenderer.rs, internal/backends/winit/renderer/skia/cached_image.rs, internal/backends/winit/renderer/skia/itemrenderer.rs, internal/core/graphics/image.rs, internal/core/graphics/image/htmlimage.rs, internal/core/graphics/image/svg.rs, internal/core/software_renderer.rs
- On the web, to return the image size, we need to use the natural size of the image, and not its dom size, as the later get modified since commit  b727aba4a001bea195ea69a536dbf4d668ac46f7
- The target size did not take in account the image fit, that's because former version of resvg could only render by respecting the aspect ratio. But since the web don't have this limitation, we now need to take it into account. And new version of resvg can also scale with any aspect ratio
=> Fix the rendering size of svg

internal/backends/winit/Cargo.toml, internal/compiler/Cargo.toml, internal/core/Cargo.toml
Bump fontdb, foreign-types (used for skia/metal), ttf-parser and winit.
=> janitor: Bump various dependencies

internal/backends/winit/renderer/femtovg/itemrenderer.rs
Otherwise computing the fit_size will lead to NaN and then panic.
The size is empty in the wasm case when loading an html image and it isn't loaded yet. We will be called again because the htmlimage has an internal property that will be changed when it is loaded
=> femtovg renderer: don't draw svg if they are empty

tools/online_editor/src/editor_widget.ts
Until the online editor supports a dark color scheme, also default to the light fluent style, so that by default on a dark color scheme system the hello world example doesn't look out of place.
=> Default to the light fluent style in the online editor

internal/core/items/flickable.rs, tests/cases/elements/flickable_in_flickable.slint
This is a regression caused by the introduced delay
=> Fix flickable in flickable

.github/workflows/ci.yaml, internal/backends/qt/qt_window.rs, internal/compiler/builtins.slint, internal/core/items/text.rs, tests/cases/text/cursor_move.slint, tests/cases/text/cursor_move_grapheme.slint, tests/cases/text/cut.slint, tests/cases/text/select_all.slint, tests/cases/text/surrogate_cursor.slint, tests/cases/text/text_change.slint
Olivier found the following steps that reproduce the crash with Skia:
1. Open the gallery and select the "Text Edit" tab.
2. In the first text edit widget, select the first three letters.
3. Click into the second text edit (while the first one shows the selected text)
4. At the beginning of the text, insert the letter "ù" a few times.
This sequence would result in the cursor_position property get out of sync.  Since it represents a byte offset in the utf-8 text, it would point straight into a utf-8 sequence, resulting in a panic when the renderer would try to create a slice of the selected text.
As a remedy, this patch renames the cursor_position and anchor_position properties and provides wrapper getter accessors for use within the TextInput to safely bound the stored offset.
Eventually …
=> Fix crash when editing text that's rendered using the Skia renderer

internal/compiler/lookup.rs, internal/compiler/tests/syntax/lookup/property.slint, internal/compiler/widgets/fluent/color-scheme.slint
That's a more idiomatic API - the compiler can map the lookup straight to a function call.
=> Make SlintInternal.dark-color-scheme a property instead of a function

internal/compiler/langtype.rs, internal/compiler/tests/syntax/new_syntax/new_component.slint
For compatibility reason, this is also allowed when inheriting
=> New syntax: Only allow children if the component has @children

CHANGELOG.md, internal/backends/qt/qt_window.rs, internal/backends/winit/glwindow.rs, internal/core/api.rs, internal/core/window.rs
related to #325 
Adds `Window::is_visible` to the Rust API (need some pointers for adding them to C++ and JS as im not very familiar)
> Allow developers to specify a callback in C++/Rust/JS that's invoked when the visibility changes.
I couldn't quite figure out how to do this, some pointers would be nice if this is necessary. 
Please let me know how and what tests are to be added.
Since, this only supports `backend-gl-all` and `backend-qt` should i keep them only under these features?
=> api: add `Window::is_visible` for `gl-all` and `qt` backends

internal/compiler/object_tree.rs, internal/compiler/tests/syntax/basic/children_placeholder.slint
It leads to compiler panic, or errors in the generated code.
=> Forbid usage of @children in repeated or conditional element

editors/kate/slint.ksyntaxhighlighter.xml, editors/sublime/Slint.sublime-syntax, editors/vscode/slint.tmLanguage.json, internal/compiler/object_tree.rs, internal/compiler/parser/element.rs, internal/compiler/tests/syntax/new_syntax/input_output.slint, internal/compiler/tests/syntax/new_syntax/input_output2.slint, tools/syntax_updater/experiments/input_output_properties.rs
`inout` and `input` are too similar, so use a longer form for `inout`
CC https://github.com/slint-ui/slint/issues/191#issuecomment-1296176978
=> Rename `inout` property to `input output`

internal/compiler/widgets/material-base/md.slint, internal/compiler/widgets/material-base/widget-groupbox.slint
This is consistent with the use of `px` for the sizes and matches the expected conversion to css pixels.
=> material design style: Replace remaining uses of pt with px

internal/backends/qt/qt_window.rs, internal/core/window.rs
This removes another place where we erased logical vs. physical type information.
=> Use logical coordinate types for internal popup handling

.github/workflows/ci.yaml
Python recently was updated to 3.11 and the build of the node binding is now failing.
(Apparently still using a quite old version of node-gyp, because this was fixed in `https://github.com/nodejs/node-gyp/issues/2219`)
```
File "/home/runner/work/slint/slint/target/debug/build/neon-sys-4b140f4af6e7aeb3/out/native/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 239, in LoadOneBuildFile
build_file_contents = open(build_file_path, "rU").read()
^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU' while trying to load binding.gyp
```
=> CI: prospective fix of the build by setting the Python version

internal/compiler/widgets/material-base/widget-checkbox.slint, internal/compiler/widgets/material-base/widget-groupbox.slint, internal/compiler/widgets/material-base/widget-spinbox.slint
* Now it's also possible to toggle  `checked` by click on the text of the `CheckBox` similar to fluent design
* `GroupBox` now respect the minimum width of the title, to avoid elision
* Adopt #1795 on md `SpinBox`
=> md: adjust GroupBox, CheckBox and SpinBox

editors/vscode/esbuild.js, editors/vscode/package.json, editors/vscode/src/browser.ts, editors/vscode/src/common.ts, editors/vscode/src/extension.ts, editors/vscode/src/propertiesView.ts, editors/vscode/tsconfig.json, tools/online_editor/src/editor_widget.ts, tools/online_editor/src/lsp_integration.ts, tools/online_editor/src/properties_widget.ts, tools/online_editor/src/shared/properties.ts, tools/online_editor/src/tsconfig.json
Some refactoring will be required later because the current interface is a bit awkward, especially the `BindingTextProvider` because the webview can't easily access the text editor as it can only communicate to the extension with messages.
But this get the thing done.
=> Properties view for the vscode extension

internal/backends/qt/qt_widgets/stylemetrics.rs, internal/backends/qt/qt_window.rs, internal/backends/winit/glwindow.rs, internal/backends/winit/lib.rs, internal/backends/winit/renderer/femtovg.rs, internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/sw.rs, internal/compiler/builtins.slint, internal/compiler/passes/apply_default_properties_from_style.rs, internal/core/software_renderer.rs, internal/core/software_renderer/fonts.rs, internal/core/window.rs
Permit the style metrics to provide a `default-font-size` and bind that
to the `Window` if set. If not provided, then the backend can set a
`default-font-size`. By ensuring that the value is non-zero at run-time,
we can later introduce a rem unit that can act as factor relative to
this non-zero font size.
=> Always set `Window.default-font-size`

internal/interpreter/api.rs
This is not meant to be public API.
=> doc: hide the testing module from slint::interpreter

internal/core/software_renderer.rs
There was an error drawing the window background in the software renderer because of a wrong check.
=> Fix temporary regression of window background not being drawn with the software renderer

api/rs/build/Cargo.toml, internal/compiler/Cargo.toml, internal/compiler/embedded_resources.rs, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/lib.rs, internal/compiler/passes.rs, internal/compiler/passes/embed_images.rs
Limit the dependency tree of things like the interpreter or the C++ compiler that doesn't support it anyway.
It is still enabled inconditionally in slint-build though
=> Compiler: move the image and font embedding behind a software-renderer flag

CHANGELOG.md, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/llr/item_tree.rs, internal/compiler/llr/lower_to_item_tree.rs, internal/compiler/llr/optim_passes/count_property_use.rs, internal/compiler/object_tree.rs, internal/compiler/passes/check_public_api.rs, internal/interpreter/api.rs
Also make it an error to change the value from the interpreter
=> Don't generate setter for output properties

examples/gallery/index.html
If you switched from fluent to material in the gallery wasm variant then by hovering with the mouse over the gallery the fluent gallery shines through. Now the old canvas will be removed by them switch and the old window will be destroyed.
=> Fix: unload old window in wasm gallery now correctly

internal/compiler/passes/visible.rs, tests/cases/issues/issue_1846_visibility_in_for.slint
The `inject_element_as_repeated_element` will create width and height binding that we should not have.
Fixes #1846
=> Make sure that the Clip element created for a visible binding has an empty size

internal/compiler/Cargo.toml, internal/compiler/tests/syntax_tests.rs
Use rayon to run the compiler syntax tests in parallel. On my machine that reduces the time from 11 seconds to 1.5 seconds.
=> Speed up compiler syntax tests

internal/compiler/passes/remove_aliases.rs, tests/cases/bindings/two_way_deep.slint
Fixes the bug that caused the TextEdit in the gallery to sometimes be empty.
Generated default value without any priority means it should not be taken against a real binding if set
=> remove alias pass: make sure to keep priority correctly

CHANGELOG.md, internal/compiler/object_tree.rs, internal/compiler/tests/syntax/basic/item_as_property.slint, internal/compiler/tests/syntax/basic/signal.slint
A duplicated callback would silently overwrite the previous declaration, which is counter-intuitive.
=> Disallow callback overrides and duplicated callback declarations

internal/backends/qt/qt_window.rs, internal/backends/winit/event_loop.rs, internal/backends/winit/wasm_input_helper.rs, internal/core/tests.rs
This can be done for key press and release events, for composition we need to extend the API first.
=> internal: Replace calls to the internal process_key_input with the public dispatch_event API

CHANGELOG.md, api/cpp/include/slint.h, docs/langref.md, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/llr/lower_to_item_tree.rs, internal/compiler/object_tree.rs, internal/compiler/passes.rs, internal/compiler/passes/collect_custom_fonts.rs, internal/compiler/passes/collect_init_code.rs, internal/compiler/passes/embed_glyphs.rs, internal/compiler/passes/focus_item.rs, internal/compiler/passes/inlining.rs, internal/compiler/passes/move_declarations.rs, internal/compiler/tests/syntax/basic/signal.slint, internal/compiler/tests/syntax/callbacks/init.slint, internal/compiler/typeregister.rs, internal/core/model.rs, internal/interpreter/dynamic_component.rs, tests/cases/callbacks/init.slint
This enables imperative code to be run. To be used sparingly :-)
=> Add support for invoking an init callback on component and element construction

examples/mcu-board-support/Cargo.toml, examples/mcu-board-support/README.md, examples/mcu-board-support/esp32_s3_box.rs, examples/mcu-board-support/esp32_s3_box/cargo-config.toml, examples/mcu-board-support/lib.rs
This is a work-in-progress port of support for the ESP32-S3-Box MCU for the mcu-board-support crate, based on the S2-Kaluga implementation. It only supports screen output, but no touch or button input yet.
=> Add work-in-progress support for the ESP32-S3-Box

internal/compiler/object_tree.rs, internal/compiler/parser/document.rs, internal/compiler/tests/syntax/imports/import_error2.slint, internal/compiler/tests/syntax/imports/import_parse_error4.slint, internal/compiler/tests/syntax/imports/import_parse_error5.slint, internal/compiler/typeloader.rs, tests/cases/imports/import_multi.slint
Importing multiple types from the same file with multiple import statements would produce an error, while this should work:
```
import { SomeType } from "somefile.slint";
import { AnotherType } from "somefile.slint";
```
=> Fix support for multiple import statements from the same path

CHANGELOG.md, docs/langref.md, internal/compiler/parser/element.rs
But it still defaults to `in-out`
=> Document and enable the in / out keywords with the old component syntax

CHANGELOG.md, docs/langref.md, docs/recipes/recipes.md, examples/printerdemo/ui/ink_page.slint, examples/printerdemo/ui/printer_queue.slint, examples/printerdemo_mcu/ui/ink_page.slint, examples/printerdemo_mcu/ui/printer_queue.slint, examples/slide_puzzle/slide_puzzle.slint, internal/compiler/object_tree.rs, internal/compiler/parser.rs, internal/compiler/parser/element.rs, internal/compiler/passes/lower_states.rs, internal/compiler/tests/syntax/basic/states_transitions.slint, tools/syntax_updater/experiments/transitions.rs, tools/syntax_updater/main.rs
CC: #1850
The current implementation enable this regardless of the new and old syntax, and try to move away from the old way of declaring transition.
Should we deprecate the old transitions syntax?  IMHO not right now as it would just cause churn before we move to the new syntax.
Should we forbid the old transitions syntax with the new syntax? IMHO yes.
=> Transitions can now be declared within the states

.github/workflows/ci.yaml, examples/fancy_demo/main.slint, tests/driver/interpreter/main.rs
Commit 53090ab489bd718d4f1f3f6ea9ec3a73588d9a5d forbid the use of
`@children` in repeater and conditional elements because it can cause
problem in the cases where the element is referenced (which is not the
case in the fancy demo)
We could try to still allow this case, but it is easier to just fix the
demo.
=> Fix the fancy demo because of its use of `@children`

internal/compiler/widgets/common/common.slint, internal/compiler/widgets/material-base/widget-lineedit.slint
Don't draw the placeholder if the TextInput element has the focus.
=> Fix placeholder text rendered on top of cursor when empty LineEdit is focused

internal/common/key_codes.rs, tests/cases/text/control_keys_input.slint, tests/cases/text/keyboard_modifiers.slint
This was a regression from 61c39b5fa18c7ad352b7279d1cc1f20841d9327f. We
now send key events also for keys that change the modifier state. Our
existing encoding uses characters in the control character category, so
the existing code in TextInput ignores them correctly. However for meta
we were using LATIN SMALL LETTER A WITH GRAVE, which is not CC category.
Deviate from the Mozilla encoding here, as there's little value to it
and there's much value to not showing the character and using the same
existing code for exclusion.
=> Fix use the meta key causing characters to appear in TextInput elements

internal/compiler/passes/apply_default_properties_from_style.rs, internal/compiler/widgets/material-base/md.slint, internal/compiler/widgets/material-base/std-widgets-impl.slint, internal/compiler/widgets/material-base/widget-lineedit.slint
Allow the style to override the font, use "Robot" as general font family for Material Design, and use it in the widgets gallery.
=> Fix application of Material Design's default font

examples/gallery/CMakeLists.txt, tools/compiler/main.rs
Use `/bigobj` with the gallery (as with the other demos) and fix ninja dependency file generation to exclude built-in image resource paths.
=> janitor: Fix C++ Windows build with Ninja

docs/langref.md
Elaborate on the order of invocation and state of properties with regards to initialized bindings.
=> Improve docs for the `init` callback

CHANGELOG.md, api/cpp/docs/types.md, api/node/native/lib.rs, api/rs/slint/lib.rs, docs/langref.md, editors/kate/slint.ksyntaxhighlighter.xml, editors/sublime/Slint.sublime-syntax, editors/tree-sitter-slint/grammar.js, editors/tree-sitter-slint/queries/highlights.scm, internal/compiler/builtin_macros.rs, internal/compiler/expression_tree.rs, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/langtype.rs, internal/compiler/llr/expression.rs, internal/compiler/llr/optim_passes/inline_expressions.rs, internal/compiler/passes/check_expressions.rs, internal/compiler/tests/syntax/lookup/conversion.slint, internal/compiler/typeregister.rs, internal/interpreter/dynamic_component.rs, internal/interpreter/eval.rs, tests/cases/types/rem.slint
This allows specifying font sizes relative to the Window's default-font-size, similar to CSS rem.
=> Introduce a `rem` unit in the type system

CHANGELOG.md, api/rs/slint/lib.rs, internal/backends/qt/qt_window.rs, internal/backends/winit/event_loop.rs, internal/backends/winit/wasm_input_helper.rs, internal/core/api.rs, internal/core/input.rs, internal/core/platform.rs, internal/core/tests.rs, tests/cases/elements/flickable.slint, tests/cases/elements/flickable3.slint, tests/cases/elements/flickable_in_flickable.slint, tests/cases/text/control_keys_input.slint, tests/cases/text/keyboard_modifiers.slint
For `Key` this is a move, as it is a new type. For `WindowEvent` and `PointerEventButton` deprecated aliases are provided.
=> Move `WindowEvent`, `PointerEventButton` and `Key` to the `platform` module

internal/compiler/widgets/material-base/md.slint
The spec at https://m3.material.io/styles/typography/type-scale-tokens defines label-large, label-medium, etc.
relative to 16px.
=> Express material design typographic tokens in relative-font-size

internal/core/items/flickable.rs, tests/cases/elements/flickable3.slint
We need to continue propagating the release event to other element (eg other flickable)
Fix the flickable flicking even though the mouse is released if there are several Flickable in the component.
=> Flickable should not accept the mouse release event if it was not flicking

internal/compiler/passes.rs, internal/compiler/passes/embed_images.rs
When doing builds that require image embedding (such as for WASM), it's crucial to also visit the globals (after they've been collected) to catch all image references.
=> Fix embedding of images referenced in globals

docs/recipes/recipes.md, docs/resources/slint-docs-preview.html
1. Fix the no-preview tag
2. disable some preview in the recipes
This makes the recipes preview work again on chromium.
This is a bakup in the event that we don't make the preview only enable.
That said, the commit 1. should probably be merged anyway in the release.
How about commit 2. ? these preview don't really make sense without the native code.
=> Docs: Disable a few preview 

docs/recipes/recipes.md, docs/resources/slint-docs-highlight.html, docs/resources/slint-docs-preview.html, tests/doctests/build.rs
By using a persistent WebGL context for reach (small) preview, we hit the browser imposed limits on the number of GL contexts quickly.
This change replaces the automatically loaded preview with a click-to-play approach, by using two buttons:
- one to show the preview
- one to launch the example in the online editor (button, instead of link, to avoid highlight on hover)
=> Use click-to-play for preview of examples and recipes

editors/vscode/esbuild.js
This patch has no effect on the currently generated output (apart from a dummy few lines in out/extension.js), but may help to avoid issues in the future like we had last week, where esbuild processed an import from "vscode-languageclient" and due to browser mode it picked the browser version of the languageclient for out/extension.js that's running in the node environment.
=> Specify target platform for esbuild calls for vs code extension

internal/compiler/passes.rs
`visible:false` would't hide the drop shadow
Fixes: #1460
=> Fix visibility on drop shadow

tools/online_editor/src/preview_widget.ts
After checking if the instance field is null, we await the promise that would guarantee DOM attachment.  While we await, the browser processes other microtasks, and we might end up in render() again. This time the instance field is also null, but the ensure_attached_to_dom promise is already resolved, so we would create the first slint component and the associated window. Later we would return from the first await. At this point the instance field is already set, so we should re-use the existing window, but since we're not checking anymore, we'll go ahead and create a second window on the same canvas element.
Fixes #1926
=> online editor: fix previous preview re-appearing unexpectedly

internal/compiler/object_tree.rs, internal/compiler/tests/syntax/elements/listview.slint, internal/compiler/widgets/fluent-base/std-widgets.slint, internal/compiler/widgets/material-base/widget-listview.slint, internal/compiler/widgets/native/std-widgets.slint
This is not supported right now, the other elements will not be part of the layout, and two `for` will be in the same listview, creating bad situation with the scrollbar.
This is a warning since it would be a breaking change to make it an error.
For example, we used a FocusScope in the StandardListView implementation so I had to go trough one level of indirection
CC: #860
=> ListView: Warn when we have other elements than just a `for`

api/rs/build/lib.rs
The compiler reads this variable, so we should rebuild if it changes.
=> janitor: Trigger rebuilds of SLINT_EMBEDD_RESOURCES changes

internal/compiler/passes/lower_popups.rs, internal/compiler/passes/lower_shadows.rs, internal/compiler/passes/lower_tabwidget.rs, internal/compiler/tests/syntax/basic/box_shadow.slint, internal/compiler/typeregister.rs, internal/interpreter/highlight.rs, tests/cases/lookup/renamed_elements.slint
Make sure this is the actual builtin type we are looking at and not a re-defined component
Doesn't work for ListView unfortunately because ListView is not a builtin type
CC #861
=> Don't match builtin type purely on it's base type name

.github/workflows/ci.yaml, CHANGELOG.md, api/cpp/CMakeLists.txt, api/rs/slint/README.md, docs/building.md, docs/tutorial/cpp/src/getting_started.md
The refactoring of the CI broke our check that we test the build with an earlier Rust version. This PR restores that and bumps the MSRV to 1.64 - that's the minimum that the Rust Skia bindings need for the `core::ffi::c_*` types.
=> Bump MSRV to 1.64 and fix CI that checks it

Cargo.toml, api/cpp/Cargo.toml, api/rs/build/Cargo.toml, api/rs/slint/Cargo.toml, examples/7guis/Cargo.toml, internal/backends/winit/Cargo.toml, internal/compiler/Cargo.toml, internal/core/Cargo.toml, internal/interpreter/Cargo.toml, tools/lsp/Cargo.toml
* 1.64 for compiler and winit due to the ffi types
* 1.62 for the interpreter and core for the enum defaults
=> janitor: bump rust-version in Cargo.toml

tools/online_editor/src/preview_widget.ts
A value of "1" for the style property turns into "none" in the computed style, for the canvas element.
=> online editor: Fix preview not being visible with Safari

internal/compiler/expression_tree.rs, internal/compiler/lookup.rs, internal/compiler/passes/resolving.rs, internal/compiler/tests/syntax/new_syntax/input_output2.slint
This is technicly a breking change. But this is also a bug and it was only allowed since 0.3.2, so it is probably fine.
The problem is that any property access to a global was considered as being local.
Now, change that so that property access to a global object is no longer local, and other components can't access private property anymore
=> Fix in/out/private property on global

internal/interpreter/eval_layout.rs, tests/cases/callbacks/init_layout.slint
The repeater code already call the init code, so we shouldn't call it twice.
=> Fix panic in the interpreter when evaluating `init` in a layout

api/cpp/include/slint.h, internal/core/model.rs, tests/cases/models/model.slint, tests/cases/models/repeater_model_change.slint
Re-use the cells but mark them as dirty, instead of re-creating them every time. In the included test-case that provides behavior that's more intuitive.
=> Reduce the amount of re-creation of cells in repeaters when the model changes

internal/backends/winit/Cargo.toml, internal/backends/winit/glcontext.rs, internal/backends/winit/glwindow.rs, internal/backends/winit/lib.rs, internal/backends/winit/renderer/femtovg.rs, internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/skia/d3d_surface.rs, internal/backends/winit/renderer/skia/metal_surface.rs, internal/backends/winit/renderer/skia/opengl_surface.rs, internal/backends/winit/renderer/sw.rs
This prepares for the ability to move renderers into a separate crate and let them have their own API, for advanced embedding of Slint.
=> internal: Remove the winit dependency from the renderers in the winit backend

CHANGELOG.md, docs/langref.md, internal/compiler/lib.rs, internal/compiler/object_tree.rs, internal/compiler/parser.rs, internal/compiler/parser/document.rs, internal/compiler/passes/check_public_api.rs, internal/compiler/passes/collect_globals.rs, internal/compiler/tests/syntax/exports/reexport_duplicate.slint, internal/compiler/tests/syntax/imports/import_errors.slint, internal/compiler/typeloader.rs, internal/compiler/widgets/fluent-dark/std-widgets.slint, internal/compiler/widgets/fluent-light/std-widgets.slint, internal/compiler/widgets/fluent/std-widgets.slint, internal/compiler/widgets/material-dark/std-widgets.slint, internal/compiler/widgets/material-light/std-widgets.slint, internal/compiler/widgets/material/std-widgets.slint, tests/cases/imports/reexport.slint, tests/helper_components/re_export_all.slint, tools/lsp/completion.rs, tools/syntax_updater/main.rs
The `export * from "./other_file.slint"` syntax takes all the exports from that file and re-exports them. This simplifies our style wrapper code.
As a bonus this also cleans up some of the export handling in the compiler.
=> Add support for re-exporting types from other modules

internal/backends/winit/renderer/skia.rs, internal/renderers/skia/lib.rs
Claim a strong reference (ownership or RC) on the value that provides the raw window handle.
=> internal: Improve the safety of the Skia renderer API

.github/workflows/ci.yaml, CMakeLists.txt, api/cpp/CMakeLists.txt
Upgrade to a newer version of Corrosion that implements this and remove our workarounds.
Closes #1025
=> Add support for `CMAKE_*_OUTPUT_DIRECTORY` variables for Slint build artefacts

Cargo.toml, internal/backends/winit/Cargo.toml, internal/backends/winit/renderer/sw.rs
Use softbuffer to bring pixels produced by the software renderer to the screen.
=> Remove the OpenGL dependency for renderer-winit-software

internal/backends/winit/renderer/femtovg/itemrenderer.rs, internal/renderers/skia/itemrenderer.rs
Commit f66a2a577532bccb5db5b35743e2d5613e9357ea and dc048a11dbb4c0b31ef2818ae8444d59f696a6d2 introduced the regression of issue #1985 where in adjust_rect_and_border_for_inner_drawing instead of subtracting the entire border width from the size, only half of it was subtracted,
leaving an inner area of the rectangle visible.
Fixes #1985
=> Fix rendering of border widths with FemtoVG and Skia

internal/compiler/parser/document.rs, internal/compiler/parser/element.rs, internal/compiler/parser/expressions.rs
`consume()` does not advance whitespace, while `peek()` does.  And the `peek()` in the debug_assert meant that the behavior was different in release and debug mode.
Use `expect` instead of consume as it skip over white space
=> Parser: fix parsing of "public function" in release mode

editors/vscode/package.json, editors/vscode/slint.injection.json, editors/vscode/src/browser.ts, editors/vscode/src/extension.ts, tools/lsp/server_loop.rs
So preview, auto-completion, and many features works out of the box within rust files
Colors presentation and syntax coloration don't work, i don't know why.
Properties tab don't work because we don't query the LSP for Rust files.
=> LSP: Support for the `slint!` macro in rust files

api/rs/slint/tests/simple_macro.rs, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs
Fixes #2005
(Unfortunately, we can't make a driver test for this becasue the behavior with the interpreter is different than with the compilers. The interpreter errors out, while the compiler should just generate nothing)
=> Do not panic if the document contains a global but no normal component

editors/vscode/src/browser.ts, editors/vscode/src/common.ts, tools/lsp/server_loop.rs
- Make the browser extention preview work
- Enable the properties tab on rust files
- Only call `offset_to_position_mapper` if the token is valid, otherwise we might get an error visible in the UI.
=> vscode extension: polish the `slint!` macro integration

.github/workflows/ci.yaml, internal/interpreter/ffi.rs
Adjust sizes of opaque value and component compiler wrapper structs.
These have been out of sync for many releases (I stopped at v0.2.0, but it goes further AFAICS).
=> Fix 32-bit C++ build

api/cpp/README.md, api/cpp/docs/cmake.md, api/cpp/docs/getting_started.md, docs/building.md, docs/tutorial/cpp/src/getting_started.md
After commit 3e5aa212d5954ac9b171a043c52088ca292e292a the Slint DLLs aren't placed in the `bin/` directory by default anymore. Since the tutorial builds Slint as an external sub-project, it is entirely isolated and the CMAKE_*_OUTPUT_DIRECTORY variables do not propagate. On macOS and Linux, the program still runs due to rpath. On Windows, the instructions said to put `bin` into `%PATH%`, but that doesn't work anymore, the dll is now in `_deps/slint-build`.
Instead of adjusting `%PATH%`, this change adjusts the documentation to recommend the use of a custom command on Windows using $<TARGET_RUNTIME_DLLS:tgt> to copy the DLL across. This is guarded with WIN32 due to https://gitlab.kitware.com/cmake/cmake/-/issues/23543 , where the proposed solution requires CMake 3.26 (not released yet).
=> Fix C++ memory game tutorial not starting out of the box on Windows

internal/compiler/layout.rs, internal/compiler/passes/lower_layout.rs, internal/compiler/passes/lower_tabwidget.rs
We have that type now, so it should be used when we don't really need a rectangle
=> Compiler: use the empty type more often instead of the Rectangle

api/cpp/include/slint.h, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/interpreter/value_model.rs, tests/cases/models/negative_intmodel.slint
Make sure that we return an unsigned for row_count() in C++ and that we create the usize for the model in Rust capped to zero.
For the interpreter this "worked" by chance as casting a negative floating number to usize automatically caps at zero, and all values are stored as f64. For safety this patch applies the same fix though, to be on the safe side.
=> Fix crash when using an int model in a repeater with a negative value

api/rs/slint/mcu.md
After a while trying to understand why std kept appearing in the output of `cargo +nightly tree -e features -i once_cell -f "{p} {f}"` and why it built within the slint tree but not in my project, I figured out that this is probably because slint is enabling the new feature resolver in its root Cargo.toml.
=> Docs: Suggest enabling the Feature resolver version 2 in the MCU doc

internal/backends/qt/qt_window.rs
Also fix the border radius to be the outer radius of the rectangle
Qt renderer part of #1988  (minus clipping)
=> Qt backend: Fix drawing of the border rectangle with non-opaque borders

internal/compiler/passes/remove_aliases.rs, tests/cases/globals/issue_2064_two_way_default_value.slint
We should not move the expression from a component to a global because there is a two way binding
Fixes #2064
=> Fix two way binding to global getting the wrong value

internal/backends/qt/qt_window.rs
Don't rely on the pen not being set when drawing the background of a rectangle with transparent border. On my machine with the test case the pen has some other color from previous drawing (or Qt internal?).
=> Fix rendering of #1988's testcase with Qt

internal/backends/winit/renderer/femtovg/itemrenderer.rs, internal/core/graphics/brush.rs
Also fix the border radius to be the outer radius of the rectangle
FemtoVG renderer part of #1988 (minus clipping)
#1988's testcase before:
and with this patch:
=> Fix FemtoVG's drawing of the border rectangle with non-opaque borders (#2079)

CHANGELOG.md, internal/compiler/passes/collect_structs.rs, tests/cases/types/structs.slint
=> Always generate the native struct for exported struct

internal/renderers/skia/itemrenderer.rs
Also fix the border radius to be the outer radius of the rectangle
Skia renderer part of #1988 (minus clipping)
Before:
After:
=> Fix Skia's drawing of the border rectangle with non-opaque borders (#2079)

internal/backends/winit/renderer/femtovg/itemrenderer.rs, internal/renderers/skia/itemrenderer.rs
Set the minimum radius of the background to limit the artifact when drawing the border
=> Skia/femtfovg rectangle with transluscent border: set minimum radius

internal/core/window.rs, tests/cases/text/keyboard_modifiers.slint
When a global shortcut, like ^-Cmd-Q on macOS to lock the screen, causes a loss of window focus, we'll receive a key event from the windowing system for the modifier, but we'll never receive the "Q" in this example (as press or release). So later, when we regain focus, we'd assume that our keyboard modifier state is still "pressed ^/Cmd", which is incorrect. Therefore assume that a loss of window focus implies a reset keyboard of keyboard modifier state.
Fixes #2098
=> Fix key input not working after loss of focus due to global shortcut

tools/lsp/server_loop.rs
Currently, the reported range is the range of the root element, which doesn't include the name of the component itself.
While the Name of the component itself is used as the selection range. Vscode assrts that the selection range is within the range:
```
ERR selectionRange must be contained in fullRange: Error: selectionRange must be contained in fullRange
```
So use the full component range for the range instead
=> LSP: fix document outline with vscode

docs/widgets.md, examples/gallery/main.cpp, examples/gallery/main.rs, internal/compiler/builtins.slint, internal/compiler/widgets/fluent-base/widget-table-view.slint, internal/compiler/widgets/material-base/widget-table-view.slint, internal/compiler/widgets/native/std-widgets.slint, internal/core/model.rs, internal/interpreter/api.rs
This commit can be reverted when we want to introduce it again. There is a few bugs with the editable property:
- The text is not in sync with the model if the model changes after an edit. (can be seen by making an edit and then sort)
- The highlight of the current row doesn't work properly
- We should probably only edit on double click or some shortcut instead of just clicking
- The editable field exist but does nothing for the StandardListView
=> StandardTableView: Remove the editable feature for now

docs/tutorial/rust/src/running_in_a_browser.md
Hi, there was an incorrect html  `<canvas id="canvas">>/canvas>`
=> Fix tutorial "running in browser" example html tag typo

internal/compiler/builtins.slint, internal/compiler/passes/lower_tabwidget.rs, tests/cases/elements/tabwidget.slint
The property set by the user was not kept because the binding went the wrong way.
Also remove the undocumented (and equaly not working) TabWidget::current-focused property from the public API
=> Fix TabWidget::current-index bindings

internal/core/layout.rs
There is a possible infinite loop when Coord is i32 in the layout engine if we can't share the pixel properly
=> Layout: don't infinite loop if no pixel was distributed

examples/slide_puzzle/slide_puzzle.slint
With commit b55ec6894aac2ad58a4dbf414ee3c22b25878c19 the preferred size of the background image of the slide puzzle demo propagates to the Window, which causes the web build of the winit backend to use the window's preferred size instead of the 100% viewport width/height set via CSS.
Work around it via manual positioning.
=> Fix slide puzzle not scaling to the browser viewport

internal/compiler/passes/binding_analysis.rs, internal/compiler/tests/syntax/analysis/binding_loop_layout4.slint
The component properties might be accessed through different paths so we may still reach a case where we have to borrow something that is already borrowed
=> Fix panic when the binding loop is caused by accessing the same component twice

editors/vscode/src/common.ts
Turns out you need to compare `X == null` here as `X` may be `null` or `undefined`, even with the linter asking to change `==` to `===`.
=> vscode: Undo some fixes for linter warnings

CHANGELOG.md, internal/core/model.rs, internal/core/model/model_peer.rs
ModelPeer is a short lived object which is just used to register a view to a ModelNotify.
Using a life time allow to save a heap allocation.
closes #1953
=> Add a lifetime to ModelPeer

.github/workflows/ci.yaml, api/cpp/include/slint.h, api/cpp/include/slint_interpreter.h, internal/compiler/generator/cpp.rs
I don't think this is a breaking change actually.
One thing that this doesn't constraint is the return type. But i don't know if there is a standard concept for that.
=> C++: Use concepts for the invokables

CHANGELOG.md, examples/opengl_underlay/main.rs, internal/backends/winit/renderer/femtovg.rs, internal/backends/winit/renderer/femtovg/glcontext.rs, internal/core/api.rs, internal/renderers/skia/opengl_surface.rs
Use a CStr instead of str, to avoid an extra CString allocation. The underlying operating system API for this expects a zero terminated C String.
Fixes #1943
=> Fix signature of get_proc_address in Rust GraphicsAPI

docs/recipes/recipes.md, internal/compiler/object_tree.rs, internal/compiler/tests/syntax/basic/children_placeholder.slint, internal/compiler/tests/syntax/basic/condition_operator.slint, internal/compiler/tests/syntax/basic/rotation.slint, internal/compiler/tests/syntax/basic/states_transitions.slint, internal/compiler/tests/syntax/elements/tabwidget3.slint, internal/compiler/tests/syntax/exports/root_compo_export2.slint, internal/compiler/tests/syntax/exports/unused_compo.slint, internal/compiler/tests/syntax/functions/functions_purity.slint, internal/compiler/tests/syntax/lookup/global.slint, internal/compiler/tests/syntax/new_syntax/input_output2.slint, internal/compiler/tests/syntax/new_syntax/two_way_input_output.slint, tests/cases/bindings/two_way_deep.slint, tests/cases/bindings/two_way_priority.slint, tests/cases/exports/export_root.slint
Commit 24dcef5fed2b53e6d1f65ba0fb5db9de9d657bf2 added a warning for the implicit export of last component. For 1.0, this commit makes it so that the root component is determined by the last export in the file.
=> Second stage of cleaning up the export handling of the slint root component

internal/core/software_renderer.rs, internal/core/textlayout/glyphclusters.rs, internal/core/textlayout/shaping.rs
Two bugs:
- There was an extra `* 4` that caused panic when the Text was clipped
- There was a bug in glyph handling when the text is being split in several runs
=> Fix panics in the software renderer system font

internal/compiler/passes/resolving.rs, internal/compiler/tests/syntax/basic/linear-gradient.slint
If the last position expression is invalid due to an unrelated error, the code that tries to do the interpolation was panicking with the message "The last should never be invalid". (Because it assumed that invalid meant that it was not set, and we added a 100% for that last one if it wasn't set. But if it is set and invalid, this would error.)
=> Fix panic parsing invalid linear grandient

internal/common/key_codes.rs
Don't map Qt meta to Control and Qt control to Meta
=> Fix mapping of the control key when using Qt

.github/workflows/nightly_snapshot.yaml
Don't build on Ubuntu 22.04, use 20.04 instead, to avoid requiring a newer glibc version. Ubuntu 20.04 is based on Bullseye.
cc #2163
=> Prospective fix for VS code extension not working on Debian Bullseye

internal/compiler/passes/binding_analysis.rs, internal/core/properties.rs, tests/cases/bindings/change_sub_property_indirection_issue2185.slint
The const detection for two way binding was not detecting change if one of the property was set to a const value in a component using it.
This would cause the compiler to generate call set_content on one of the property in a two way bindings, and later, the "const sentinel" be present in the dependency list, causing crash.
To avoid segfault for similar bug in the future, added added an assert! in the property system to detect that.
Fixes #2185
=> Fix const detection with two ways binding

internal/backends/winit/Cargo.toml, internal/backends/winit/renderer/femtovg/fonts.rs, internal/backends/winit/renderer/femtovg/itemrenderer.rs, internal/compiler/Cargo.toml, internal/compiler/passes/embed_glyphs.rs, internal/core/Cargo.toml, internal/core/software_renderer/fonts/systemfonts.rs, internal/core/software_renderer/fonts/vectorfont.rs
Mostly bugfix changes upstream with some minor API changes. FemtoVG is no more limited to 24 gradient stops for the paint.
=> Bump femtovg, rustybuzz, ttf-parser, and fontdb dependencies

CHANGELOG.md, api/cpp/include/slint_platform.h, api/cpp/platform.rs, api/rs/slint/mcu.md, examples/mcu-board-support/esp32_s2_kaluga_1.rs, examples/mcu-board-support/esp32_s3_box.rs, examples/mcu-board-support/pico_st7789.rs, examples/mcu-board-support/stm32h735g.rs, internal/backends/winit/lib.rs, internal/backends/winit/renderer/sw.rs, internal/core/software_renderer.rs, tests/screenshots/testing.rs
Having a const generic for that didn't turn to be a good API. Also made the C++ side more difficult
(Also renamed buffer_stride to pixel_stride)
Closes #2135
=> Replace the MAX_BUFFER_AGE const generic with a runtime enum

internal/compiler/object_tree.rs, internal/compiler/passes/collect_custom_fonts.rs, internal/compiler/passes/collect_init_code.rs, internal/compiler/passes/embed_glyphs.rs, internal/compiler/passes/focus_item.rs, internal/compiler/passes/inlining.rs
As outlined in #2199, there may be ways to trigger text layout code through forward-focus before embedded fonts are registered. To fix this, this patch replaces the init_code vector, which had the SetFocusItem code before the font registration, with three explicit vectors for focus setup code, code from init callbacks, and initial focus, and defines the order in one central place in the copmiler (visit_init_code).
Fixes #2199
=> Fix run-time panic when combining forward-focus with text rendering in no_std environments

CHANGELOG.md, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, tests/cases/issues/name_conflicts.slint
So we avoid name conflict between user types and internal types
Fixes #2207
=> Rust: Avoid use statement in the generated code

editors/vscode/package.json, scripts/prepare_vscode_nightly.sh
=> Declare the Slint VS code extension as stable

internal/compiler/passes/embed_glyphs.rs
As discussed with Olivier, fatal diagnostics are better than a panicing compiler.
=> Replace unwraps in compiler glyph embedding with diagnostics

internal/compiler/passes/inlining.rs, tests/cases/subcomponents/no_children.slint
An element with children must be fully inlined or the children array can't be easily computed.
But the code wouldn't work if the base of a component was not inlined
=> Fix compiler panic when an component's base is not inlined

.github/workflows/ci.yaml, CHANGELOG.md, Cargo.toml, api/cpp/CMakeLists.txt, api/rs/slint/README.md, docs/building.md, docs/tutorial/cpp/src/getting_started.md, internal/compiler/Cargo.toml, internal/core/Cargo.toml
- the new version of resvg needs 1.65
- the memoffset crate can do const offset from Rust 1.65, which means we could get rid of our const field offset macro which is probably contributing to slow builds.
- `let else` is in 1.65 and it is good to use that.  (also GAT)
Technically there is not much we need from 1.66 (released 2022-12-15):
- `wrapping_add_signed` is nice, but also simple to do ourselves.
- I thought we could use `Span::source_text` to help with the dashes detection of identifier. But that is actually not helping.
- I don't think we would use any other new feature of 1.66
1.67 Also doesn't have so many interesting feature, and is a bit too recent anyway.
We could just use 1.65, but I think since we want to be conservative with MSRV changes in the future, I think we can simply …
=> Set MSRV to 1.66

internal/backends/winit/renderer/femtovg.rs
It was on the wrong line if not a \n, and on the wrong position if a \n
=> Femtovg backend: fix text_input_cursor_rect_for_byte_offset for the last glyph

internal/backends/winit/Cargo.toml, internal/backends/winit/build.rs, internal/backends/winit/event_loop.rs, internal/backends/winit/glwindow.rs, internal/renderers/skia/Cargo.toml
On macOS and Windows, use winit's `Window::theme()` instead of dark-light, to detect the theme.
Always react to WindowEvent::ThemeChange. It's delivered on macOS, Windows, and the web.
=> Add support for reacting to dark/light mode theme changes with winit

docs/langref/conf.py, docs/langref/index.rst
Use rst references instead of markdown syntax for links. Also enable the extension to generate targets automatically.
=> Fix links on the intro page of the Slint Language Documentation

docs/language/conf.py, docs/language/genindex.rst, docs/language/index.rst, docs/language/src/brushes.md, docs/language/src/builtin_elements.md, docs/language/src/builtin_namespaces.md, docs/language/src/callbacks.md, docs/language/src/properties.md, docs/language/src/widgets.md
This re-organizes the structure a little to what I think makes more sense. There's more to be done I think, but this is a start.
Also this PR fixes a bunch of links, shortens titles, and removes the non-existent index.
=> language doc: Improve structure, fix links

internal/compiler/lib.rs
The logic was inverted: Setting to true should embed everything, while false should be the same as if it's not set: Only embed built-in resources (as always).
=> Fix SLINT_EMBED_RESOURCES environment variable

internal/compiler/generator.rs, internal/core/properties.rs, tests/cases/crashes/issue_2274_const_state_crash.slint
States are never constant because the generated state binding depend on the time as it register the time it was set for the pottential animation
Also adjust the assert so it assert correctly which the right message
Fixes: #2274
=> Fix crash when a state condition is detected as constant

examples/printerdemo/ui/common.slint, examples/printerdemo_mcu/ui/common.slint
=> printerdemo: Improve category labels' visibility in night mode

docs/language/src/builtins/elements.md
As pointed out by Miłosz, users of this property may very likely be also interested in string formatting / interpolation.
=> doc: From `Text`'s `text` property, link to the string handling

examples/energy-monitor/ui/assets/arrow-left.svg
There's a curious bug where with Skia's OpenGL renderer on a Vivante, the colorization using Skia image filters on the left arrow SVG would just not produce any pixels. As a workaround, taking the right arrow SVG and rotating it by 180 degrees around the center fixes it.
=> Work around the left arrow not showing up sometimes in the energy monitor

internal/backends/winit/Cargo.toml, internal/backends/winit/build.rs, internal/renderers/skia/Cargo.toml
winit 0.28.2 was released today, which supports `Window::theme()` on the web.
=> Remove dark-light dependency on the web

internal/backends/winit/event_loop.rs
Adjust the size of the underlying graphics surface to avoid rendering artefacts.
Fixes #2282
=> winit: Fix rendering when moving windows between monitors with different scale factor

internal/compiler/object_tree.rs, tests/cases/callbacks/init.slint
Make sure to visit the named references in the init code, when collecting globals.
Fixes #2312
=> Fix panic when accessing a global from init that's not used otherwise

examples/energy-monitor/ui/small_main.slint, examples/energy-monitor/ui/widgets/menu.slint
* reduce memory usage for the small size view
* use virtualization on navigation items
* generate menu content only if menu is opened
* works now again on the Pico
=> energy monitor: optimize memory usage for small size

api/rs/slint/mcu.md
Rust 1.68 will be released by the time we do the next release
=> Docs: Remove the sentence that say one need to use nightly

docs/language/src/builtins/elements.md, docs/language/src/builtins/widgets.md
- Don't show a literal underscore.
- Close the code fence so that the markdown link turns into a real link.
=> Fix doc rendering of remaining callbacks

internal/backends/winit/event_loop.rs, internal/core/software_renderer.rs
This would cause some of the image to be drawn outside of the clip
region, which may even lead to panics
(Fix changing pages in the energy monitor demo)
=> swrenderer: fix image drawing when the image is not stretched to the geometry

examples/mcu-board-support/Cargo.toml, examples/mcu-board-support/stm32h735g.rs
Use getrandom's way of injecting a custom source for getrandom().
=> stm32h7: Add support for getrandom()

examples/energy-monitor/src/controllers/weather.rs
In case we fail to retrieve a forecast, don't empty the current forecast shown. After all, this is just a demo, not a forecast that anybody should rely on. Therefore it's better to show something than have an empty widget :)
=> Avoid an empty forecast if there's an issue with the weather api

internal/backends/winit/wasm_input_helper.rs
We should only forward keys that are a single character. Other ones are just virtual keys that should't be processed.
This regressed in commit 32d2ba7
Fix #2327
=> Wasm: don't print fake keys in input box

internal/core/items/flickable.rs, tests/cases/elements/flickable_in_flickable.slint
When scrolling the printer demo, I often end up closing or opening element i don't want to because we reached the end and therefore it is not scrolling and forwarding the event
=> Flickable: capture the event if the flickable can flick even if it is at the end

docs/language/conf.py
The navigation sidebar requires jquery, which from Sphinx >= 6.0 needs to be bundled via a separate extension. In the C++ docs Sphinx remains at version 4.5.0 (due to exhale), but the slint language site doesn't need exhale (no C++) and thus Pip ends up picking a newer Sphinx version.
=> Fix missing navigation sidebar in the slint language docs

internal/renderers/femtovg/fonts.rs
Increase the cache font cache size, otherwise, the cache is trashed with already moderate text size causing TextEdit to become quickly very slow (unusable) when the text becomes a bit big.
Also prevent to be O(N²) in the number of new lines while calling break_text.
Big text are still bit slow  slow but at least now it is usable
=> femtovg: Speedup TextEdit with many lines

internal/compiler/generator/rust.rs, tests/cases/expr/return.slint
We cast the result of the body of functions or binding expressions to the target type via `as _`. When the code contains a return expression, that works fine, because `return`'s type is the never type, which can be coerced to a value of any type. However when the return statement is inside a sub-block, the type becomes `()`, for which the `as _` cast fails.
Work around this by attempting to detect the situation (return produces Type::Invalid) and omit the trailing cast.
=> Fix compilation of Rust generated code when the generated code uses a return statement inside a block

CHANGELOG.md, api/cpp/Cargo.toml
Enable all the image formats the image-rs crate enables by default.
=> Make it possible to use more than png and jpeg with Slint C++

internal/backends/winit/Cargo.toml, internal/backends/winit/glwindow.rs, internal/backends/winit/lib.rs, internal/backends/winit/renderer/femtovg.rs, internal/backends/winit/renderer/femtovg/glcontext.rs, internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/sw.rs, internal/renderers/skia/opengl_surface.rs
In order for GLX support to work, we need to create the X11 window with the same visual as in the GLX configuration. That requires delaying the creation of the window.
This is done in four parts:
- The window builder is re-introduced in the winit backend create internal renderer interface.
- The glcontext helper code for wasm was moved into a separate function (less indentation).
- The loop over different display preferences was replaced with a preference to the "window system native GL interface" over EGL, which should achieve the same as the fix for #2162. Upstream glutin defaults to this and so do various downstream projects.
- Use glutin-winit for the actual display selection.
This covers the FemtoVG bits of #2269
=> Fix support on GLX displays with FemtoVG

internal/backends/winit/Cargo.toml
Winit defaults to sctk-adwaita with ab_glyph rendering. Pick the same default when the wayland feature is enabled on our end.
This is a stop-gap. In the future we should try to implement the window decoration rendering ourselves.
Fixes #2188
=> Fix missing window title when using Slint on Wayland

internal/compiler/widgets/common/common.slint
- Don't publicly inherit from Rectangle - let's keep that as an implementation detail
- Provide a minimum height for the image, to avoid that it becomes invisible (for example in `export component Example { VerticalLayout { AboutSlint { } } }`
=> Tweak AboutSlint

internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/llr/item_tree.rs, internal/compiler/llr/lower_to_item_tree.rs, internal/compiler/object_tree.rs, internal/compiler/passes/check_public_api.rs, internal/compiler/passes/inlining.rs
If you declare a `property <int> foo;` in Slint, it will be private by default, and the getter/setter won't be generated, and it may be confusing as to why
With this change, it still generate private getter and setter so this gives a better hint what the problem is.
Replaces #2170
Example of error with C++
Example of error with rust and build.rs
Example of error with Rust  macro (unfortunately a bit less useful)
I'm not sure there is a way to test this
=> Better error message when trying to use private property in native code

internal/core/graphics/boxshadowcache.rs, internal/renderers/femtovg/itemrenderer.rs
Reproducer:
```
export component Test {
width: 200px;
height: 200px;
Rectangle {
clip: true;
background: red;
border-radius: 5px;
height: -12px; //<- negative size
width: 100%;
Rectangle { background: green; }
drop-shadow-color: #8888;
drop-shadow-blur: 5px;
}
}
```
=> Femtovg: fix panic when rendering layer or shadow with negative size

tools/online_editor/src/welcome_widget.ts
The back button doesn't work that well, so it's better to open those links in new windows.
=> Use target="_blank" to avoid destroying editor state when clicking links on the welcome screen

internal/backends/winit/Cargo.toml, internal/backends/winit/build.rs, internal/backends/winit/glwindow.rs
Remove the dark-light dependency, as it significantly slows down the build on Linux. On Windows/Mac/Web it's not needed. On Linux Desktop, folks are likely going to have Qt installed - where this works - and on Embedded Linux the assumption is that it's not running as Linux Desktop.
On Linux the number of dependencies for `-p slint` goes down from 418 to
328. Build time on my machine goes from 1 minute down to ~50 seconds.
=> Speed up Linux builds

CHANGELOG.md, api/rs/slint/Cargo.toml, internal/backends/winit/Cargo.toml, internal/core/Cargo.toml, internal/core/software_renderer.rs, internal/core/software_renderer/fonts.rs
If we have a file system, then we can allow users of the software
renderer to support text rendering by from fonts served by the file
system.
cc #2100
=> Add a feature to enable system fonts with the software renderer

examples/slide_puzzle/Cargo.toml, examples/slide_puzzle/main.rs, internal/backends/winit/glwindow.rs
Since winit can't handle resize from the CSS or JS, work it around in the demo by calling set_size on the slint window.
Also fix slint_size panicking not working on wasm as the map_state was mutably borrowed by the set_size, and this may recurse into other functions (eg, draw) causing a panic. So don't keep the state borrowed when calling winit.
Another fix is fixing the initialization size of the window item when the initial size is set with set_size
Fixes #547
=> Fix the slide_puzzle canvas size on wasm

internal/backends/qt/qt_window.rs, internal/backends/winit/event_loop.rs, internal/backends/winit/glwindow.rs, internal/core/layout.rs
Avoid conveying a maximum size of 0x0, mark a window as explicitly resizable (true or false) only if a min/max constraint is actually set, and do these things consistently between show() and apply_geometry_constraint().
Fixes #2413
=> winit: Fix panic when creating a window with an empty layout

internal/compiler/widgets/native/std-widgets.slint
=> Qt TabWidget: clip the tabbar to fix the breeze style

CHANGELOG.md, internal/compiler/passes/compile_paths.rs, internal/compiler/tests/syntax/basic/path_commands.slint
=> Fix panic when binding Path's commands property to a model entry's field

CHANGELOG.md, CMakeLists.txt, api/cpp/CMakeLists.txt
Thanks to @jschwe, there's a way to instruct corrosion to supply link flags that set the install name and work around cargo/rustc behavior.
Fixes #2075
=> macOS: Fix installed libslint_cpp.dylib containing references to the build directory

internal/backends/winit/event_loop.rs, internal/backends/winit/lib.rs, internal/backends/winit/winitwindowadapter.rs
It's no more an "OpenGL Window", it's the type that adapts winit to our windowing system abstraction.
=> janitor: Rename GLWindow to WinitWindowAdapter

docs/tutorial/rust/src/main_multiple_tiles.rs, docs/tutorial/rust/src/main_polishing_the_tile.rs
Fix mis-rendering and build problems in native code when accessing property that was unintentionally private.
Fixes #2496
=> Fix the memory game tutorial

CHANGELOG.md, tools/lsp/server_loop.rs
I misread the spec that we should return an error if there is nothing to rename. We should just return None instead.
This means that the editor will no longer show an error message when this happens (and also that we can rename stuff in rust code without getting annoying error)
Technicly, we could still return an error if the user tries to rename a property or so, but i don't think its worth it
=> LSP: don't throw a protocol error when a symbol can't be renamed

internal/backends/qt/qt_window.rs
Apply horizontal alignment to the text lines created by QTextLayout.
Fixes #2524
=> Qt: Fix missing support for horizontal alignment in TextInput

internal/compiler/object_tree.rs, internal/compiler/passes/binding_analysis.rs, internal/compiler/passes/inlining.rs, tests/cases/callbacks/init_access_base_compo.slint
This patch merges the changes from #2344 and #2491 and do some cleanup
In particular, this visit the init code expression when visiting the root element expression
Closes #2344
Closes #2491
Fixes #2487
=> Fix visitation of init code

.github/workflows/build_docs.yaml, .github/workflows/ci.yaml, Cargo.toml, examples/uefi-demo/Cargo.toml, examples/uefi-demo/README.md, examples/uefi-demo/build.rs, examples/uefi-demo/demo.slint, examples/uefi-demo/main.rs
This is the UEFI port I wrote some time ago to explorer no_std support in slint. It works fairly well and might be useful to others.
Easy to test with:
```
rustup target install x86_64-unknown-uefi
cargo build --package uefi-demo --target x86_64-unknown-uefi
qemu-system-x86_64 -bios /usr/share/edk2-ovmf/x64/OVMF.fd -kernel target/x86_64-unknown-uefi/debug/uefi-demo.efi
```
In theory, i686 and aarch64 are also supported. In practice there are some rust bugs in the way (https://github.com/rust-lang/rust/issues/62729, https://github.com/rust-lang/rust/issues/98254).
=> examples: Add uefi-demo

CHANGELOG.md, docs/language/src/builtins/elements.md, internal/core/items.rs, tests/cases/focus/event_propagation_3.slint
Don't propagate the input event further. Also document the `enabled` property.
=> Fix `FocusScope` click-to-focus behavior

CHANGELOG.md, internal/backends/winit/winitwindowadapter.rs
When the dark color scheme was queried before the window was mapped, we'd initialize it to false, but never update it to the actual theme value.
Fixes #2533
=> winit: Fix dark color scheme not always being detected correctly

CHANGELOG.md, api/cpp/cbindgen.rs
The ImageCacheKey enum has a gap when not targeting wasm:
```
pub enum ImageCacheKey {
/// This variant indicates that no image cache key can be created for the image.
/// For example this is the case for programmatically created images.
Invalid,
/// The image is identified by its path on the file system.
Path(SharedString),
/// The image is identified by a URL.
#[cfg(target_arch = "wasm32")]
URL(SharedString),
/// The image is identified by the static address of its encoded data.
EmbeddedData(usize),
}
```
In the C++ generated header, that cfg was not mapped, and thus the URL variant was always there, while in a regular slint-cpp build it's not. Consequently tag value 2 in Rust was used to represent the EmbeddedData variant, while in the C++ generated code that become variant 3 and 2 was …
=> Fix memory corruption when loading encoded embedded images in C++

CHANGELOG.md, internal/compiler/widgets/native/std-widgets-impl.slint, internal/core/model.rs
The problem is that we would end up with a division by zero and the NaN value would be cached as the average item height
Fixes #2545
=> Fix resizing a ListView to empty height would make all items invisible even if resized back

internal/core/input.rs, internal/core/tests.rs, tests/cases/input/visible_mouse.slint
We need to take in account that the items might be clipped when sending mouse exit events to items.
Note that the test needed a fix to use the actual windows state.
=> Fix TouchArea::has-hover not becoming false when items become invisible

api/cpp/docs/conf.py
The Furo theme by default generates a "on this page" contents list in the right column. The breathe output for C++ namespace and file pages also includes a ::contents:: RST directive, to summarize the available headings. The duplication of these two is warned about by furo with a big fat red warning.
Solve this by not making breathe generate the contents directive anymore. According to
https://exhale.readthedocs.io/en/latest/reference/configs.html?highlight=contentsspecifier#exhale.configs.kindsWithContentsDirectives
it's by default used for files and namespace, so make it empty in our config.
Fixes #2505
=> C++ docs: Fix red warning in generated HTML for file and namespace listings

CHANGELOG.md, api/cpp/CMakeLists.txt, examples/gallery/CMakeLists.txt, examples/printerdemo/cpp/CMakeLists.txt, examples/printerdemo/cpp_interpreted/CMakeLists.txt, examples/virtual_keyboard/cpp/CMakeLists.txt
Large C++ files generated from .slint files can cause link problems with MSVC. When that happens, MSVC itself suggests /bigobj as remedy.
It's not apparent that there's a downside to using this option, apart from backwaords binary compatibility - which is not a concern for us.
The discussion at https://developercommunity.visualstudio.com/t/Enable-bigobj-by-default/1031214 suggests that perhaps this will become the default one day.
To simplify our examples and avoid users running into this, let's enable it by default.
=> C++: Enable /bigobj by default when building with MSVC

CHANGELOG.md, internal/compiler/passes/lower_layout.rs, tests/cases/issues/issue_2483_access_spacing.slint
The previous code was only re-creating the layout properties for these that had a binding, but that wasn't done if the property was just read, leading to access to non-existing properties later.
Fixes #2483
=> Fixes access to unset layout property

internal/core/api.rs, internal/core/graphics/image.rs, internal/core/input.rs, internal/interpreter/api.rs
Even if there's a cfg gap in an enum (say cfg(feature = "svg")), don't let that break the ABI.
See also 004dce6c0bf3c6f49004d720a0b2ec0626a22962
=> Attempt at making the C/C++ ABI more robust

internal/compiler/parser/expressions.rs, internal/compiler/tests/syntax/basic/assign.slint, internal/compiler/tests/syntax/basic/condition_operator.slint, internal/compiler/tests/syntax/basic/self_assign.slint, internal/compiler/tests/syntax/lookup/for_lookup.slint, internal/compiler/tests/syntax/lookup/if.slint, internal/compiler/tests/syntax/lookup/signal_arg.slint, internal/compiler/tests/syntax/lookup/two_way_binding.slint, internal/compiler/tests/syntax/lookup/two_way_binding_infer.slint, tools/fmt/fmt.rs
That way the error for an expression is at a better location, and this also prevent the formater that removes space in expressions to remove the spaces before the expression that shouldn't be removed
=> Parser: don't have the whitespace as part of an expression

CHANGELOG.md, docs/language/src/builtins/elements.md, internal/backends/qt/qt_window.rs, internal/backends/winit/winitwindowadapter.rs, internal/compiler/builtins.slint, internal/core/items.rs
It's a very simple implementation, which could be made by mostly pattern matching the existing code path for no-frame and no_frame. I've added my own review for things that stood out as potential questions.
=> Add `always-on-top` property to Window element

internal/compiler/parser.rs, internal/compiler/parser/document.rs, internal/compiler/tests/syntax/imports/import_error2.slint, internal/compiler/tests/syntax/imports/import_errors.slint, internal/compiler/tests/syntax/imports/import_parse_error5.slint, internal/compiler/tests/syntax/parse_error/export0.slint, internal/compiler/tests/syntax/parse_error/if0.slint, internal/compiler/tests/syntax/parse_error/state1.slint, internal/compiler/typeloader.rs, tools/fmt/fmt.rs, tools/lsp/completion.rs, tools/lsp/server_loop.rs
this include changes to the parser so auto-completion can work in the top-level even if the document is empty or has errors.
=> LSP: auto-complete at the document root

internal/compiler/parser/document.rs, internal/compiler/tests/syntax/basic/parse_error.slint
Recover from extra semicolon
(As reported on mattermost)
=> Parser: Nicer error when extra top-level semicolon

internal/backends/qt/qt_window.rs, internal/core/layout.rs
Avoid communicating partial window size constraints, where only one component is set.
In the provided example in the cc'ed bug report, when run with material style, it appears that there's a maximum height, but no maximum width.
While for example the wayland protocol allows for partial constraints, i.e. a max height but max width 0 means unlimited, the
winit API takes the Option for the size as a whole.
cc #2562
=> Prospective fix for panic when running material style under Wayland/Gnome

internal/core/graphics/color.rs
Previously, the following assertion would fail:
```rust
// use i_slint_core::graphics::Color;
assert_eq!(Color::from_argba_encoded(0xff804000), Color::from_argba_f32(1.0, 0.5, 0.25, 0.0));
```
This happened because upon converting `RgbaColor<f32>` to `RgbaColor<u8>` the code discarded the fractional part of the calculated value by using `as u8` without calling `round()`. The previous behavior was preventing test cases (to be pushed to #2565) from passing.
=> Round values when converting from `f32` to `u8` in `RgbaColor`

README.md, docs/site/index.html
The old video still use the old syntax and the name SixtyFPS. Used the video that creates a small calculator for Rust
=> Docs: Remove link to old video

internal/compiler/diagnostics.rs, internal/compiler/tests/syntax_tests.rs, tools/slintpad/src/index.ts
Commit 893983e8d320bd248c47f3d57292d432ec4ded69 "fixed" it to be 0 based as it was documented. But that's a change of behavior so restore the previous behavior and document it properly
Alternative to #2584
=> Make Disagnostice::line_colunm 1 based

internal/backends/winit/winitwindowadapter.rs
I misread the spec about the name conversion for the DOMStringMap used in JS for the dataset attribute and the name used in the DOM.
Both, the setting in preview_widget.ts as well as
reading it in windowadapter.rs counts as JavaScript access, so use camel case.
The old variant happened to work in Safari.
Amends 43234dafc50a043ef53b65be635c71cbd1bf490f
=> Fix resizing of the preview in SlintPad after selecting a new demo

internal/compiler/parser.rs, tools/lsp/completion.rs
So this doesn't break the slint! macro (add the import at the beginning of the rust file)
=> LSP: complete the first import right before the first component

api/rs/macros/lib.rs, docs/language/src/reference/types.md
=> Docs: document that `\{...}` is not working in a `slint!` macro

editors/README.md
Replace the non-existent `neovim/lspconfig` plugin by `neovim/nvim-lspconfig`.
=> Update the neovim plugin

internal/compiler/fileaccess.rs, internal/compiler/passes/embed_images.rs, internal/compiler/typeloader.rs, internal/core/graphics/image.rs, internal/core/graphics/image/cache.rs, internal/interpreter/eval.rs, tests/cases/issues/issue_2608_canon_img_path.slint
For .slint files that are included, we canonicalize the path before adding it into the import stack, to avoid duplicates. We didn't do that for images in the global_embedded_resources.
Ensure this by canonicalizing as early as possible.
Fixes #2608
=> Fix duplicated loading/embedding of images

CHANGELOG.md, internal/backends/winit/winitwindowadapter.rs
Like Qt, ensure the window size is in bounds of updated min/max constraints.
Fixes #2581
=> winit: Adjust the window size to satisfy changed min/max constraints

examples/README.md
Changes the current examples README from
to
=> fix(readme): table of virtual keyboard example

internal/backends/selector/lib.rs, internal/backends/winit/Cargo.toml, internal/backends/winit/event_loop.rs, internal/backends/winit/lib.rs, internal/backends/winit/wasm_input_helper.rs, internal/backends/winit/winitwindowadapter.rs
This API requires using the i_slint_backend crate, which won't follow semver. But it's a way out for a couple of use-cases where semver doesn't matter.
=> winit: Add API to access the winit window and event loop

api/cpp/include/slint.h, api/cpp/include/vtable.h, examples/iot-dashboard/dashboard.cpp, examples/qt_viewer/qt_viewer.cpp
- std::optional<T>::value() is not available, use operator * instead
- alignment allocation is also only available in 10.14 or newer
=> Fix build against macOS deployment target 10.10

internal/renderers/femtovg/fonts.rs
When the coverage is complete, the fallback font is not chosen. This causes some minor mis-fallback, for example, incorrect weight for CJK characters.
=> Fix font fallback in femtovg renderer.

editors/vscode/src/common.ts
I somehow ended up in a situation where the Slint LSP logs was open and VSCode was logging data into that. While my cursor was in an editor with a .slint file open, the onDidChangeTextDocument events emitted by the slint log file triggered yet another attempt to `queryProperties` whenever the slint LS log changes due to e.g. reporting that a query properties request incoming.
This patch makes sure to ignore events from documents not containing slint or rust files.
=> vscode: Trigger queryProperties less often

internal/core/graphics/image.rs
Fixes #2624 
I just added `from_svg` when `svg` feature is on, and didn't consider the WASM target. Is that OK?
=> Add `Image::load_from_svg_data`.

internal/backends/qt/qt_window.rs, internal/core/items/text.rs, internal/renderers/femtovg/itemrenderer.rs, internal/renderers/femtovg/lib.rs, internal/renderers/skia/itemrenderer.rs, internal/renderers/skia/lib.rs
Centralize the handling of the password character substitution in corelib, instead of duplicating it in the backends.
=> Clean up password character substitution handling

internal/backends/winit/winitwindowadapter.rs
We must tell winit that we want a transparent surface by default, to avoid that winit sets an opaque region on the wayland surface.
In terms of the surface, we already prefer a GL config with a color buffer that supports transparency.
=> Fix support for transparent Windows on Wayland

internal/backends/winit/lib.rs, internal/backends/winit/renderer/femtovg.rs, internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/sw.rs, internal/backends/winit/winitwindowadapter.rs, internal/interpreter/dynamic_component.rs
Prepare for the situation where creating a renderer may fail.
=> Winit renderer initialisation cleanup

docs/language/src/builtins/functions.md
Additional enhancement might be to have a `stringify(string) -> string` builtin function to make it possible to print values like `3px` easily for debugging animations and math code.
=> docs: Correct debug(string) returns "void"

CHANGELOG.md, cspell.json, internal/compiler/passes/collect_structs.rs, tests/cases/types/functions.slint
Fixed missing items compilation error in the generated code related to public functions (#2655).
I manually "mutation tested" the change against `cargo test test-driver-cpp` and `cargo test test-driver-rust`
`cargo test test-driver-nodejs` shouldn't actually make a difference with this change, though.
=> Fixed missing items compilation error in the generated code related to public functions (#2655).

CHANGELOG.md, internal/compiler/builtin_macros.rs, tests/cases/types/cubic-bezier.slint
Required to support ease in back / bounce kinds of easings.
Tested with mutation testing alongside `cargo test test-driver-interpreter`.
=> Support negative numbers in `cubic-bezier(...)` function

api/cpp/docs/getting_started.md, examples/virtual_keyboard/README.md, tests/doctests/Cargo.toml, tests/doctests/build.rs, tests/doctests/main.rs
We were missing some which had errors
Fixes #2689
(Although the error for 2689 was in C++ and would not have been discovered by the test, better to have it parsed anyway)
=> Tests: look at _all_ markdown files for slint snippets

.prettierignore, .reuse/dep5, cspell.json, xtask/src/license_headers_check.rs
Makes it a bit easier to use pre-commit hook since I'm trying to group the changelog update, the code change, and the test case addition in the same commit for easier reference.
TODO:
=> dev: Ignore CHANGELOG.md from pre-commit hook checks

internal/backends/qt/qt_widgets.rs, internal/backends/qt/qt_window.rs, internal/core/item_rendering.rs, internal/core/items.rs, internal/core/items/flickable.rs, internal/core/items/image.rs, internal/core/items/path.rs, internal/core/items/text.rs, internal/core/lengths.rs, internal/core/software_renderer.rs, internal/renderers/femtovg/itemrenderer.rs, internal/renderers/femtovg/lib.rs, internal/renderers/skia/itemrenderer.rs, internal/renderers/skia/lib.rs
So that we don't need to query the geometry multiple time, and this pave the way to not have the geometry in the items
Part of #1932
As a drive by, fix the clipping of the Path element which incorrectly offseted the clip by (x,y).
Similar fixes happen in the Clip element in some renderer, but that didn't have effect because x and y are always 0 for the Clip element
=> Refactoring: Pass the size to to the render function

internal/renderers/skia/d3d_surface.rs
This isn't quite perfect either, but arguably an improvement and consistent with the error handling elsewhere.
=> D3D: Replace panics with propagated platform errors

internal/core/software_renderer.rs, internal/core/textlayout.rs, internal/core/textlayout/shaping.rs
* implement text_input_byte_offset_for_position for SoftwareRenderer
* add byte_offset_for_position to TextParagraphLayout
Place text cursor by mouse should work now. Navigate with arrow up and down keys is a little bit buggy but can be done in a flowing PR.
=> swr: implement text_input_byte_offset_for_position

internal/backends/qt/qt_window.rs, internal/backends/testing/lib.rs, internal/backends/winit/event_loop.rs, internal/backends/winit/renderer/femtovg.rs, internal/backends/winit/renderer/femtovg/glcontext.rs, internal/core/graphics/rendering_metrics_collector.rs, internal/core/items/text.rs, internal/core/renderer.rs, internal/core/software_renderer.rs, internal/renderers/femtovg/lib.rs, internal/renderers/skia/lib.rs
This series reduces the dependencies of the Renderers on the `Weak<dyn WindowAdapter>`, by adding the necessary state to the core `Renderer` trait functions and making the renderer metrics collector independent from the window adapter.
As a bonus, the wrapper around the FemtoVG renderer in the winit backend becomes much thinner.
=> Internal renderer API cleanups

api/cpp/include/slint_sharedvector.h, api/cpp/tests/datastructures.cpp
Don't detach for every element.
Closes #2737
=> C++: optimize SharedVector's iterator constructor

.github/workflows/ci.yaml
They take lots of room and are not so usefull as we don't debug on CI.
This will remove line number in backtrace. We could set the value to "1" instead if we wanted to to keep the line number information, but it's not so valuable anyway.
=> CI: disable debug symbol on CI

CHANGELOG.md, internal/backends/testing/lib.rs, internal/backends/winit/event_loop.rs, internal/backends/winit/winitwindowadapter.rs, internal/core/api.rs, internal/core/platform.rs, internal/core/window.rs
Add WindowEvent::ScaleFactorChanged and made set_scale_factor on WindowInner private.
This achieves what #2486 tried to do, but using the clean platform window event interface.
=> Add public API to allow platforms to report the window scale factor

api/cpp/include/slint.h, api/cpp/include/slint_platform.h, api/cpp/platform.rs, api/cpp/tests/manual/platform_native/appview.cpp, api/cpp/tests/manual/platform_native/windowadapter_win.h, api/cpp/tests/manual/platform_qt/main.cpp, internal/backends/winit/lib.rs, internal/backends/winit/renderer/femtovg.rs, internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/sw.rs, internal/backends/winit/winitwindowadapter.rs, internal/core/software_renderer.rs, internal/renderers/femtovg/lib.rs, internal/renderers/skia/lib.rs
Make it possible to construct the renderer without the window adapter.
This is a step towards disentangling these a little further. The renderer still must be set when `MyApp::create()` is called, i.e. `WindowAdapter`'s `renderer()` must return a valid reference after the adapter has been created, but this doesn't all have
to happen within `Rc::new_cyclic` anymore.
=> Remove persistent renderer dependency on the WindowAdapter

internal/core/Cargo.toml, internal/core/sharedvector.rs, internal/core/string.rs
fixes: #2660 
Suppose missed some struct and should add serde features to toml but with cycle importing I suppose collabrators could help to solve it  .
=> Serde struct

internal/backends/winit/lib.rs, internal/backends/winit/winitwindowadapter.rs
show() used to create the window, which required access to the event loop (target), which in turn required workarounds like in #1603.  Since the winit window exists now in show(), we don't need this workaround anymore.
The same applies to hide(), we don't need an event loop target, all we need is the event loop proxy to dispatch a WindowHidden event.
=> winit: Clean up implementation of WinitWindowAdapter::show() and hide()

api/cpp/include/slint_platform.h, api/cpp/platform.rs, api/cpp/tests/manual/platform_qt/main.cpp
- Provide a C++ platform event for the scale factor change and send it
- Report the correct logical and physical sizes to Slint
=> Fix rendering of the Qt platform example with high-dpi

api/cpp/include/slint_platform.h, api/cpp/platform.rs, api/cpp/tests/manual/platform_native/windowadapter_win.h, api/cpp/tests/manual/platform_qt/main.cpp, internal/backends/winit/lib.rs, internal/backends/winit/renderer/femtovg.rs, internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/sw.rs, internal/backends/winit/winitwindowadapter.rs, internal/renderers/femtovg/lib.rs, internal/renderers/skia/lib.rs
Remove the redundant size argument from `render()`.
=> FemtoVG and Skia renderer API cleanup

CHANGELOG.md, api/cpp/cbindgen.rs, docs/language/src/builtins/widgets.md, examples/gallery/ui/pages/controls_page.slint, internal/backends/qt/build.rs, internal/backends/qt/lib.rs, internal/backends/qt/qt_widgets.rs, internal/backends/qt/qt_widgets/progress_indicator.rs, internal/compiler/builtins.slint, internal/compiler/widgets/fluent-base/std-widgets-base.slint, internal/compiler/widgets/fluent-base/std-widgets-impl.slint, internal/compiler/widgets/material-base/std-widgets-base.slint, internal/compiler/widgets/material-base/widget-progress-indicator.slint, internal/compiler/widgets/native/std-widgets.slint
* Add material ProgressIndicator
* Add fluent ProgressIndicator
* Add native ProgressIndicator
* Add ProgressIndicator documtentation
=> Add ProgressIndicator widgets

api/rs/slint/lib.rs, internal/core/model.rs
- Mention in the type mapping table as well as in ModelRc that ModelRc is also used for array struct fields.
- Use an itemized list for the different ways of constructing, with the from_slice variant being listed second.
cc #2787
=> Try to improve the documentation for ModelRc

internal/core/software_renderer.rs, internal/core/window.rs, internal/renderers/femtovg/lib.rs
With Qt and eglfs it may happen that when creating a popup, Qt delivers a paint event via show() before we've had a chance to set the component on the slint::Window. In that case unwrapping the component in draw_contents() panics.
This fix is covered by reproducing the same scenario using public MinimalSoftwareWindow API.
Fixes #2799
=> Fix panic when attempting to render window contents without a component

.github/workflows/ci.yaml
Apply `CARGO_PROFILE_DEV_DEBUG: 0` consistently to all our builds.
Amends 4fa1f885a93f826f3266f512d05aa18a43677274
=> Clean up debug info handling in the CI

Cargo.toml, api/wasm-interpreter/Cargo.toml, api/wasm-interpreter/src/lib.rs, docs/resources/slint-docs-preview.html, editors/vscode/src/wasm_preview.ts, internal/backends/winit/Cargo.toml, internal/backends/winit/event_loop.rs, internal/backends/winit/winitwindowadapter.rs, internal/core/api.rs, tools/slintpad/src/lsp.ts
This requires two changes:
- An API change in the wasm interpreter (needs careful review)
- A workaround for winit's delivery of draw events
=> Fix live-preview in docs

.github/workflows/build_docs.yaml, .github/workflows/ci.yaml, Cargo.toml, examples/README.md, examples/ffmpeg/Cargo.toml, examples/ffmpeg/README.md, examples/ffmpeg/build.rs, examples/ffmpeg/main.rs, examples/ffmpeg/pause.svg, examples/ffmpeg/play.svg, examples/ffmpeg/player.rs, examples/ffmpeg/player/audio.rs, examples/ffmpeg/player/video.rs, examples/ffmpeg/scene.slint
This is a minimal example, that can be used as basis to implement hardware acceleration for video playback later.
This is excluded from the CI right now as it would require installing ffmpeg, which may not be worth the hassle.
=> Add an example that shows how to combine ffmpeg with Slint

CHANGELOG.md, api/cpp/cbindgen.rs, api/cpp/include/slint.h, docs/language/src/builtins/elements.md, internal/backends/qt/qt_window.rs, internal/compiler/builtins.slint, internal/compiler/expression_tree.rs, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/llr/lower_expression.rs, internal/compiler/llr/optim_passes/inline_expressions.rs, internal/compiler/object_tree.rs, internal/compiler/passes/collect_init_code.rs, internal/compiler/passes/inlining.rs, internal/compiler/passes/lower_popups.rs, internal/compiler/tests/syntax/elements/popup.slint, internal/compiler/typeregister.rs, internal/core/window.rs, internal/interpreter/dynamic_component.rs, internal/interpreter/eval.rs, tests/cases/callbacks/init_popup.slint, tests/cases/elements/popupwindow_close.slint
This patch adds a `close()` function that can be called to close a popup window, and a `close-to-click` boolean that can be set to false to disable the default behavior.
=> Add support for manually closing PopupWindows

api/cpp/tests/CMakeLists.txt
With the latest Corrosion update test binaries don’t depend on libslint_cpp.so with path anymore that contains a slash. Therefore rpath kicks in and this workaround should not be needed anymore.
Plus, this gives us test coverage for rpath.
=> Remove workaround for running tests on Linux

api/rs/slint/private_unstable_api.rs, internal/backends/testing/lib.rs, internal/core/items/text.rs, tests/cases/focus/focus_change.slint
When the TextInput item is read-only, it should report availability or any other status to the input method via the window adapter.
This also fixes the order of events when clicking on a TextInput: We would send the ime position update request before enabling the ime, because we set the focus _after_ setting the cursor pos.
Fixes #2812
=> Fix read-only TextInput reporting input method access

internal/core/model.rs, tests/cases/issues/issue_2780_listview_crash.slint
.. that has less items and the ListView is scrolled.
We should not have an offset that is higher than the current count otherwise we're going to access invalid item in the model
Fix #2780
=> Fix ListView panic when setting a new model

CHANGELOG.md, internal/compiler/widgets/common/common.slint
Use the same font attributes as for the inner `TextInput`.
Fixes #2829
=> Fix rendering of LineEdit's placeholder text

.github/workflows/ci.yaml
The node tests do need a separate cargo build -p slint-node. Split that out into a separate job, which runs the nodejs tests as well as any unit tests in slint-node (none atm).
Amends 3d5dd2405a2327d49a0bc0854d6abeb07479ca47
=> Fix build_and_test CI test

internal/backends/winit/lib.rs, internal/backends/winit/renderer/femtovg.rs, internal/backends/winit/renderer/femtovg/glcontext.rs, internal/backends/winit/winitwindowadapter.rs, internal/renderers/femtovg/lib.rs
Separate the wasm vs. non-wasm code path on the renderer level, not on the OpenGL context handling. The latter doesn't exist in WebGL.
=> Internal FemtoVG renderer API cleanup

api/cpp/platform.rs, internal/backends/winit/renderer/skia.rs, internal/renderers/skia/d3d_surface.rs, internal/renderers/skia/lib.rs, internal/renderers/skia/metal_surface.rs, internal/renderers/skia/opengl_surface.rs, internal/renderers/skia/vulkan_surface.rs
Accept raw display and window handles, instead of &dyn HasRaw*Handle.
This is consistent with other crates in the Rust ecosystem. Consequently the accepting functions are marked unsafe, as the
API can't guarantee that the handles remain valid.
=> Clean up the Skia renderer API

internal/core/api.rs, internal/core/timers.rs
- in SetRenderingNotifierError using a rustdoc link breaks the C++ docs. Using a qualified backtick'ed slint::Window works perfect with both.
- In TimerMode, the same track unfortunately doesn't work with a function, but we can use [`Foo::bar()`] to make the link work with rustdoc and myst-parser. The look isn't perfect in C++, the square brackets are visible.
=> Fix rendering of links in data structures where docs are shared between C++ and Rust

CHANGELOG.md, internal/compiler/diagnostics.rs, internal/compiler/lexer.rs, internal/interpreter/api.rs, tools/lsp/server_loop.rs, tools/tr-extractor/main.rs
This includes slint-viewer, slint-interpreter (when loading path, not string), slint-compiler.
(This would also include internal things such as
`import { Xxx } from "foo.rs"`, if we didn't check for .slint or .60 extension before)
But that doesn't include anything that's not opening the source by path (so not the lsp which use its own representation coming from the editor, or varius tools like the updater and fmt which also open the files themselves)
=> Make the extraction of `slint!` macro as part of the compiler core

docs/language/src/concepts/translations.md
Provide an intro that outlines the overall steps, and then go into details in each of them.
The C++ bit is marked with TODO, as I think we still have to sort out some details there.
=> Rework the translation documentation

internal/backends/qt/qt_accessible.rs, internal/core/accessibility.rs
With just the Qt accessibility support, this is not impactful. But with accesskit it'll be useful to avoid the intermediate vector of ItemRcs and map directly to a different data structure.
Otherwise, this is a trade-off between the stack allocation of the recursion and instead allocating the stack of pending itemrs
on the heap.
=> Provide a more idiomatic API for accessible_descendents

api/wasm-interpreter/src/lib.rs, docs/resources/slint-docs-preview.html, editors/vscode/src/wasm_preview.ts, tools/slintpad/src/lsp.ts
The interpreter now creates the window typically in show(), so similar to commit a8fcb5acd6d3d1631c2cbaa634086811b249eed5 make show() return a promise and invoke show() from within the event loop.
Amends d98c6773e15664127409a9d2d748cf2ce1caac3b
=> Fix preview in SlintPad and VS code web extension

api/cpp/platform.rs, api/node/native/lib.rs, internal/backends/qt/qt_window.rs, internal/backends/testing/lib.rs, internal/backends/winit/lib.rs, internal/backends/winit/winitwindowadapter.rs, internal/compiler/generator/rust.rs, internal/core/api.rs, internal/core/component.rs, internal/core/item_rendering.rs, internal/core/items.rs, internal/core/items/text.rs, internal/core/lib.rs, internal/core/platform.rs, internal/core/renderer.rs, internal/core/software_renderer.rs, internal/core/window.rs, internal/interpreter/eval.rs, internal/interpreter/ffi.rs, internal/renderers/femtovg/lib.rs, internal/renderers/skia/lib.rs, tests/screenshots/testing.rs
Note: the addition of MinimalSoftwareWindow::set_size is there because it would be a breaking change for user who called set_size on the MinimalSoftwareWindow while also using the WindowAdapter trait. This was the case of a test.
The same problem theorically exist with set_position and position, but is unlikely to be a problem because i don't think people would use the position with a MinimalSoftwareWindow
The renderer() is now public as well. That's because I want to make sure that the scealed trait don't have non-provided method
=> Un-seal the WindowAdaptor trait

internal/backends/winit/accesskit.rs
This is a fix for the problem of unstable node IDs in slint-ui/slint#2865.
=> New scheme for stable node IDs

.clang-format
Update clang format.
One controversial bit is that I downgraded the languiage standard used by clang-format to c++20. We claim that is the one we in our CMakeLists.txt, so I think that's the one we should configure.
The old setting was the legacy Cpp11 setting, which actually aliases to "Latest" in the new syntax. So that would be the "no change" option.
All other changes are AFAICT just syntax update. Latest requires clang-format 3.11, which we should have as ubuntu 22.10 ships with clang-format 14 AFAICT.
=> Clang format config

api/cpp/CMakeLists.txt, api/cpp/Cargo.toml, api/rs/slint/Cargo.toml, internal/backends/selector/Cargo.toml, internal/backends/winit/Cargo.toml, internal/backends/winit/accesskit.rs, internal/backends/winit/build.rs, internal/backends/winit/event_loop.rs, internal/backends/winit/lib.rs, internal/backends/winit/winitwindowadapter.rs, internal/interpreter/Cargo.toml
This change adds initial accessibility support for the winit backend
through use of AccessKit.
cc #32
=> Initial AccessKit support

internal/backends/winit/lib.rs, internal/backends/winit/renderer/femtovg/glcontext.rs, internal/renderers/skia/opengl_surface.rs
=> winit: Fall back to any renderer if the default fails
