api/wasm-interpreter/src/lib.rs, editors/vscode/src/wasm_preview.ts, tools/slintpad/src/lsp.ts
With the following snippet there was a race:
```
if (instance === null) {
instance = await create();
await instance.show();
} else {
instance.create_with_existing_window(...);
}
```
When awaiting for the promise that show() returns to settle, we would re-enter this function (due to a broken recursion guard, that's now removed). When re-entering, create_with_existing_window() is called, which - in order to access the slint::Window to re-use - must create the window adapter. Since that didn't happen from within an event loop invocation, winit would panic.
Consequently, this patch set also makes create_with_existing_window() return a promise, as well as hide() (for the sake of it).
The broken recursion guard is easy to fix (with a .finally() handler setting the boolean back), but that would …
=> Fix race in Slintpad causing preview to panic (esp. in FF)

internal/backends/winit/winitwindowadapter.rs
This fixes keyboard input on mobile
=> Wasm: initialize properly the WinitWindowAdapter::self_weak

internal/backends/qt/qt_widgets/button.rs, internal/core/items.rs, tests/cases/elements/toucharea.slint
eg: releasing the pointer over a button that wasn't pressed shouldn't click it
Fixes #2918
=> Don't emit clicked when the pointer did not press the area

CHANGELOG.md, api/cpp/cbindgen.rs, api/cpp/docs/types.md, api/rs/slint/lib.rs, api/rs/slint/private_unstable_api.rs, docs/language/src/builtins/elements.md, internal/compiler/builtins.slint, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/load_builtins.rs, internal/compiler/passes/lower_absolute_coordinates.rs, internal/compiler/tests/syntax/analysis/binding_loop_mappointtowindow.slint, internal/compiler/typeregister.rs, internal/core/api.rs, internal/core/items.rs, internal/core/lengths.rs, tests/cases/absolute_coords.slint
The type of thep property is `Point`, which existed before. It was mapped to `slint::private_unstable_api::re_exports::Point` (euclid) and is now mapped to slint::LogicalPosition (also in C++).
=> Merge `absolute-x` and `absolute-y` "virtual" properties into `absolute-position`

internal/compiler/passes/lower_absolute_coordinates.rs, internal/compiler/tests/syntax/analysis/binding_loop_mappointtowindow.slint
Since we materialize only one point property, we don't need to cache the parent position in a separate property, but we can just store that in the binding.
=> Simplify implementation of absolute-position

Cargo.toml, internal/common/Cargo.toml, internal/common/sharedfontdb.rs, internal/common/sharedfontdb/fontconfig.rs, internal/core/Cargo.toml
We need only 9 different functions from fontconfig and one data structure.  We can do that interaction with libloading by hand and avoid causing issues like servo/font-kit#212
=> Remove yeslogic-fontconfig dependency

internal/backends/winit/lib.rs, internal/core/api.rs, tools/lsp/main.rs
Two problem:
1. we were calling quit_event_loop from another thread, which didn't work with winit
2. we need to ignore error from the lsp-server when shutdown as it may result in https://github.com/slint-ui/slint-cpp-template/issues/15
Closes https://github.com/slint-ui/slint-cpp-template/issues/15
=> LSP: fix errors or panic when exiting  (Option 2)

internal/backends/winit/Cargo.toml, internal/backends/winit/renderer/sw.rs, internal/renderers/femtovg/Cargo.toml, internal/renderers/skia/Cargo.toml
This bumps softbuffer, cocoa, and core-text. I left out rustybuzz/ttf-parser, as that would introduce rustybuzz as a duplicate. The missing link here is usvg-text-layout that depends on old rustybuzz/ttf-parser and needs a new version.
=> Bump some winit dependencies

examples/printerdemo_mcu/ui/common.slint, examples/printerdemo_mcu/ui/printer_queue.slint
Commit 08e20c858665975f3514eb0bb6defe0686d69692 changed the behavior of clicked being emitted when the area was both pressed and released. But that made it hard to hit button on the devices because the touch screen isn't great.
So activate the button on release instead of click, going effectively back to previous behavior
=> printerdemo_mcu: react on pointer up rather than click

internal/core/Cargo.toml, internal/core/software_renderer/draw_functions.rs
=> Remove embedded_graphics dependency from i-slint-core

CHANGELOG.md, editors/tree-sitter-slint/corpus/lookup.txt, editors/tree-sitter-slint/grammar.js, internal/compiler/expression_tree.rs, internal/compiler/langtype.rs, tests/cases/models/for.slint
Fixes #2977
The problem is that expressions such as "foo * foo" can be optimized by optimization pass to only query the property once, and this is transformed in a Expression::CodeBlock and is no longer a Expression::Cast(Model)
So we need to introspect the expression more.
=> Fix getting type of more complex expressions in model

api/cpp/docs/Pipfile, docs/language/Pipfile
PEP 508 requires a comparator for version_one, so specify some.
=> Prospective fix for pipenv errors about invalid specifiers

internal/renderers/skia/itemrenderer.rs
Interpolate colors as pre-multiplied.
cc #313
Qt reference:
Skia before this patch:
Skia with this patch applied:
=> Skia: align gradient rendering with software renderer and Qt

internal/core/items/text.rs
Otherwise we end up with outdated pre-edit data if we change focus while editing.
Note: Qt doas actually send a "commit" event when the focus change (but of course that does not happen when changing the focus within slint)
But firefox does discard the preedit when loosing the focus.
CC #1925
=> TextEdit: Discard the preedit when focus change or other text is enter

CHANGELOG.md, api/cpp/include/slint.h, api/cpp/tests/window.cpp
=> C++: Add slint::Window::scale_factor() getter

CHANGELOG.md, internal/backends/qt/qt_widgets/slider.rs
The OpenGL Texture import example uses a Slider in the range 0..1. That doesn't work with QStyleOptionSlider out of the box because it's
using integer values.
=> Fix support normalized ranges for Slider with Qt style

Cargo.lock, tools/viewer/Cargo.toml, tools/viewer/main.rs
Fixes for #3011
This uses a hack to serialize enum values in string format, maybe this can be made in a better way.
=> Interpreter: Add support for save/load of enums

internal/renderers/skia/lib.rs, internal/renderers/skia/opengl_surface.rs
Gracefully handle a loss before destruction time and reduce the chance of hide() failing to those applications that use a rendering notifier (only those might actually be interested in this error anyway).
=> Improve robustness of Skia OpenGL renderer in case of GL context loss

internal/backends/qt/lib.rs, internal/backends/winit/accesskit.rs, internal/backends/winit/lib.rs, internal/backends/winit/winitwindowadapter.rs, internal/compiler/expression_tree.rs, internal/core/api.rs, internal/core/input.rs, internal/core/item_tree.rs, internal/core/textlayout/linebreaker.rs, internal/core/textlayout/shaping.rs, internal/core/translations.rs, internal/interpreter/highlight.rs, tools/viewer/main.rs
Contributing to #1874
I made one commit by lint rule, so we can easily drop any of them if you do not care for it.
I did not handle:
- `clippy::match_single_binding`: kind of false-positive due to temporary life prolongation hack (did not add a `allow`)
- `clippy::await_holding_refcell_ref`
- in `compiler/passes.rs`: it could be fixed with some cloning but I hope the panic issue can not be triggered so we do not need to.
- in `lsp` there is two occurrences on `document_cache` (in `main` and `server_loop`), I do not know the code enough to rule out a danger here
=> Reduce clippy warnings

internal/core/properties.rs, tests/cases/crashes/link_two_way_geometry_if.slint
two_way_link shouldn't force the evaluation of the property
=> Fix crash when evaluating two_lay_link too early

examples/gallery/ui/pages/controls_page.slint, internal/compiler/object_tree.rs, internal/compiler/widgets/fluent-base/button.slint, internal/compiler/widgets/material-base/button.slint
Fixes #2900
This is a work in progress:
- the `fluent` change works as expected
- the `material` change does not work as expected: the text does not render even if the `Text` seam to be correctly created. The change is the same as for the `fluent` style, I do not understand why it is broken. As this point, it feels like a bug to me. Any input on this is welcome.
=> Support button with only icon

internal/core/timers.rs
=> Fix timer corruption if a Timer is Drop'ed in the event handler of another Timer

api/cpp/lib.rs, internal/backends/qt/lib.rs, internal/backends/selector/lib.rs, internal/backends/winit/lib.rs, internal/core/lib.rs, internal/interpreter/lib.rs
This doesn't seem to be needed anymore with newer rust version. As long as one symbol from the crate is used, all exported function from the crate are available.
The reason why some symbols in some module were gone was a bug in rust that has been fixed, it seems
=> Get rid of the "use_modules" workaround

api/cpp/CMakeLists.txt, api/cpp/Cargo.toml, api/cpp/include/slint_image.h, api/cpp/lib.rs, api/cpp/platform.rs, internal/core/graphics.rs, internal/core/graphics/image.rs, tests/driver/cpp/Cargo.toml
And make it no_std otherwise
This is a first step towards getting C++ on MCU (#2136)
=> C++: add a "std" feature to the slint-cpp crate

CHANGELOG.md, docs/language/src/builtins/structs.md, internal/compiler/builtins.slint, internal/core/items.rs, internal/interpreter/api.rs, tests/cases/elements/toucharea.slint
=> Add modifiers to PointerEvent

internal/backends/winit/accesskit.rs
On unix, the panic happens since the upgrade from zbus 3.10 to zbus 3.14
```
thread 'test_window_accessor' panicked at 'called `Option::unwrap()` on a `None` value', /home/olivier/.cargo/registry/src/index.crates.io-6f17d22bba15001f/accesskit_consumer-0.15.0/src/tree.rs:274:45
stack backtrace: [...]
3: core::option::Option<T>::unwrap
4: accesskit_consumer::tree::Tree::new
at /home/olivier/.cargo/registry/src/index.crates.io-6f17d22bba15001f/accesskit_consumer-0.15.0/src/tree.rs:274:19
5: accesskit_unix::adapter::Adapter::new
at /home/olivier/.cargo/registry/src/index.crates.io-6f17d22bba15001f/accesskit_unix-0.5.0/src/adapter.rs:53:20
6: accesskit_winit::platform_impl::platform::Adapter::new
at /home/olivier/.cargo/registry/src/index.crates.io-6f17d22bba15001f/accesskit_winit-0.14.1/src/pl …
```
=> Attempt to fix a panic in accesskit

internal/compiler/widgets/fluent-base/listview.slint, internal/compiler/widgets/material-base/listview.slint
In StandardListView, it is currently needed to click an item twice to select it. This fixes the issue.
=> Added zero width to focus scope to StandardListView

api/cpp/docs/conf.py, api/cpp/include/slint.h
Revert da95051 and fix the link in the substitution instead.
Fixes #2992
=> Fix bad red markup in C++ slint::Model docs

xtask/src/cppdocs.rs
The symlink from docs/ is not needed anymore. Its presence meant that sphinx recursively compiled all .md and .rst files and ended up adding them to the searchable index.
Fixes #3033
=> Remove the Slint language docs from the C++ API docs index

internal/compiler/generator/rust.rs, internal/compiler/passes/lower_property_to_element.rs, tests/screenshots/cases/software/basic/linear-gradients.slint
... if they are not set as actual binding before
As reported in #3068
The problem is that the pass will properly create the Rotation or Opacity item, but will not create the two way binding if there is no existing binding. This causes code like `img.rotation-angle = ...` to change the rotation angle of the image, but not its parent Rotation item.
Fix it by making sure there is always a binding.
Since the change only affect visual representation, I abused one of the screenshot test to test this feature. And I also patched another bug that some #[allow(unused_parens)] was not set in the 'init' callback and would cause a warning in the test
=> Fix setting rotation-angle and opacity from a callback

tools/compiler/Cargo.toml, tools/compiler/main.rs
We aldready document in cmake.md that a valid value for `SLINT_EMBED_RESOURCES` is `embed-for-software-renderer`, but this doesn't work since it expect a `software-renderer` feature that don't exist. So create this feature.
This feature brings on all the image and font loading machinery in the compiler. But I still enable it by default since it is a documented cmake option.
=> compiler: add a software-renderer feature

api/cpp/Cargo.toml, api/cpp/lib.rs, api/cpp/platform.rs
Add a experimental-platform feature that doesn't include skia
=> C++: Make the platform support work without the "std" feature

api/cpp/cbindgen.rs, api/cpp/include/slint.h, internal/backends/qt/qt_widgets.rs, internal/backends/qt/qt_widgets/button.rs, internal/backends/qt/qt_widgets/checkbox.rs, internal/backends/qt/qt_widgets/combobox.rs, internal/backends/qt/qt_widgets/groupbox.rs, internal/backends/qt/qt_widgets/lineedit.rs, internal/backends/qt/qt_widgets/listviewitem.rs, internal/backends/qt/qt_widgets/progress_indicator.rs, internal/backends/qt/qt_widgets/scrollview.rs, internal/backends/qt/qt_widgets/slider.rs, internal/backends/qt/qt_widgets/spinbox.rs, internal/backends/qt/qt_widgets/tableheadersection.rs, internal/backends/qt/qt_widgets/tabwidget.rs, internal/backends/qt/qt_window.rs, internal/compiler/generator/cpp.rs, internal/core/component.rs
Allocate a widget per NativeXXX. This way QStyleAnimation objects created by Qt aren't shared among style options.
=> Fix rendering of QStyle animations

internal/compiler/lib.rs, internal/compiler/object_tree.rs, internal/compiler/passes/resolving.rs, internal/compiler/tests/syntax/basic/inline_component.slint, internal/compiler/tests/syntax/basic/item_as_property.slint, internal/compiler/tests/syntax/basic/states_transitions.slint, internal/compiler/tests/syntax/basic/type_declaration.slint, internal/compiler/tests/syntax/basic/unknown_item.slint, internal/compiler/tests/syntax/functions/functions.slint, internal/compiler/tests/syntax/imports/error_in_import.slint, internal/compiler/tests/syntax/lookup/callback_alias2.slint, internal/compiler/tests/syntax/lookup/two_way_binding_infer.slint, internal/compiler/tests/syntax/new_syntax/input_output.slint
The first commit increase the test coverage by running the import pass even in case of error building the object_tree (the LSP does that)
The second commit fixes #3085
=> Don't panic when an unresolved alias has a binding

api/cpp/include/slint_platform.h, api/cpp/platform.rs, api/cpp/tests/manual/platform_qt/main.cpp, internal/renderers/skia/opengl_surface.rs
- Don't try to create a GLX context when we only have an XCB window handle,
XLib is required for that.
- Make it possible to create a NativeWindowHandle from Xlib data types.
Fixes #2978
=> Improve error handling in C++ Skia Renderer API 

internal/core/input.rs, tests/cases/elements/flickable.slint
because the pending press event might be loss if there is a move between the click and the release
This was reported on Mattermost
=> Fix touch in the flickable not resulting in a click

.github/workflows/ci.yaml, examples/mcu-board-support/README.md
Amends bea263a447e354370dcff01f79ed4312e3abb37c
=> doc: Remove the need to use nightly for pico and stm32 builds

api/cpp/docs/index.rst, xtask/src/cppdocs.rs
Amends a11c4c42b091c5b7e7815000818890811ae1eda0
=> Fix disapearing debugging techniques docs from C++ docs

internal/backends/qt/qt_widgets/spinbox.rs, internal/compiler/builtins.slint, internal/compiler/widgets/fluent-base/spinbox.slint, internal/compiler/widgets/material-base/spinbox.slint
This PR is for https://github.com/slint-ui/slint/issues/3054
Add `edited` callback similar to `LineEdit` component, for different three styles: `native`, `fluent` & `material`.
=> Add edited callback for SpinBox

docs/language/src/builtins/widgets.md, internal/compiler/widgets/fluent-base/tableview.slint, internal/compiler/widgets/material-base/tableview.slint, internal/compiler/widgets/native/std-widgets.slint
Adds a `row-pointer-event` callback that bubbles up from `StandardTableView` rows so users can assign events such as menu popups etc.
NOTE: this has only been implemented and tested with fluent
=> add row-pointer-event callback to tableview

internal/compiler/passes/binding_analysis.rs, tests/cases/issues/issue_3107_if_optimized_rect.slint
This is necessary for the `is_used` to be set properly
Fixes #3107
=> Compiler: Visit the model and other "side" named reference in binding_analysis

internal/compiler/generator/rust.rs
This generated a `clippy::clone-on-ref-ptr` warning
=> remove clippy warning in rust code gen

internal/compiler/builtin_macros.rs, internal/compiler/expression_tree.rs, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/llr/expression.rs, internal/compiler/llr/lower_expression.rs, internal/compiler/llr/optim_passes/inline_expressions.rs, internal/compiler/llr/pretty_print.rs, internal/compiler/passes/default_geometry.rs, internal/compiler/passes/flickable.rs, internal/compiler/passes/lower_tabwidget.rs, internal/interpreter/eval.rs
The generated code was itching me, so I'm suggesting this. I won't take it badly if you do not like it :stuck_out_tongue: .
Adds `Expression::MinMax`
- Avoid usage of `Expression::Condition` => cleaner code
- Open optimization possibility => `Expression::MinMax` can be seen as `const` if sub expressions are (see example below)
- Use new enum instead of `char` in compiler code for operation selection
After this we could try to optimize min/max during constant optimization.
<details>
<summary>Slint source file</summary>
<pre><code>
export component App inherits Window {
in property<float> f1;
in property<float> f2;
out property<float> f_max: max(f1, f2);
out property<float> f_min: min(f1, f2);
in property<int> i1;
in property<int> i2;
out property<int> i_max: max(i1, i2);
out property<int> …
=> Add native support for min/max

api/cpp/CMakeLists.txt, api/cpp/Cargo.toml, api/cpp/cmake/SlintConfig.cmake.in
Make it possible to build the slint-cpp crate as a static library
This isn't supported on desktop yet, but on MCU it is.
Cargo is instructed to build a dylib and a staticlib, but corrosion
instructs rustc to build only either dylib or staticlib.
Corrosion listens to the BUILD_SHARED_LIBS option and will change the
default for the Slint::Slint INTERFACE_LINK_LIBRARIES to either
slint-cpp-shared or slint-cpp-static. This way the selection is
transparent to the users.
=> Make it possible to build the slint-cpp crate as a static library

internal/backends/qt/qt_window.rs
SLINT_FULLSCREEN currently only works with the winit backend.
=> Allow Qt windows to run fullscreen with SLINT_FULLSCREEN

api/cpp/include/slint_platform.h, api/cpp/tests/manual/platform_qt/main.cpp
Replace void* with forward-declared NSView/NSWindow in NativeWindowHandle::from_appkit
=> C++: Improve type-safety of NativeWindowHandle API on macOS

api/cpp/include/slint_platform.h, api/cpp/platform.rs, api/cpp/tests/manual/platform_native/windowadapter_win.h, api/cpp/tests/manual/platform_qt/main.cpp, internal/backends/qt/qt_window.rs, internal/backends/testing/lib.rs, internal/backends/winit/renderer/femtovg.rs, internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/sw.rs, internal/core/renderer.rs, internal/core/software_renderer.rs, internal/core/window.rs, internal/renderers/femtovg/lib.rs, internal/renderers/skia/lib.rs
This makes for a slimmer API and instead we can create the renderer <-> window association behind the scenes ourselves,
in set_component.
=> Remove the window parameter from the render() function of all the renderers

api/cpp/include/slint_platform.h, api/cpp/platform.rs, api/cpp/tests/manual/platform_native/windowadapter_win.h, api/cpp/tests/manual/platform_qt/main.cpp, internal/backends/winit/lib.rs, internal/backends/winit/renderer/femtovg.rs, internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/sw.rs, internal/backends/winit/winitwindowadapter.rs, internal/core/api.rs, internal/core/renderer.rs, internal/renderers/femtovg/lib.rs, internal/renderers/skia/lib.rs
We can convey the new physical window size from the run-time through the private renderer API
when a window resize event is dispatched.
=> Simplify FemtoVG and Skia renderer APIs: remove resize()

api/cpp/include/slint_platform.h
Copying the Rust enum instead of using cbindgen because we would need to create a new header just for it for bublic types generated in the platform namespace. I've also put it in the SoftwareRenderer class since the equivalent enum is in the software_renderer module in Rust.
=> C++ platform: make the max_buffer_age an enum

editors/vscode/src/extension.ts
Attempt to detect when we are running in a codespace and force the preview to render in wasm.
Remote view don't make sense as there is no graphical server where the extension runs
=> vscode extension: Use the wasm preview in codespaces

.github/workflows/ci.yaml, CHANGELOG.md, api/cpp/CMakeLists.txt, api/cpp/Cargo.toml, api/cpp/build.rs, api/cpp/cbindgen.rs, api/cpp/include/slint-platform.h, api/cpp/include/slint.h, api/cpp/lib.rs, api/cpp/platform.rs, api/cpp/tests/CMakeLists.txt, xtask/src/cppdocs.rs
The platform namespace is now always enabled.
=> C++, remove the experimental flag

api/cpp/docs/conf.py, api/cpp/include/slint-interpreter.h, api/cpp/include/slint-platform.h
- Fix pre-processor define setup so that the new #ifdef'ed classes API in the API documentation.
- Add missing documentation that caused doxygen errors.
=> c++: Fix missing platform API Docs

editors/vscode/src/extension.ts
Generally, disable the fullscreen rendering. This selection mechanism
needs reworking, as one might want to use the live-preview in a setup
where weston, etc. are running side-by-side.
This could be made configurable in the future, i.e. choosing a backend
like linuxkms, or having the window state as property in Slint.
=> Don't show live-preview in fullscreen when running VS code with WSL

examples/ffmpeg/scene.slint
In general, black background better matches the aesthetics of video playback apps, making the viewing experience more immersive.
=> ffmpeg example: Change background color to black

internal/core/Cargo.toml, internal/core/software_renderer/draw_functions.rs
Implement rgb::Pod/rgb::Zeroable for PremultipliedRgbaColor. This allows for bytemuck::cast_slice(), making it easier to copy software renderer output
into another buffer that's the same format but
Vec<u8> for example.
=> Make it easier to use the software renderer with PremultipliedRgbaColor in "foreign" environments

api/napi/Cargo.toml
Since this file is part of the repository workspace, we should use the common profile in the top-level Cargo.toml.
=> napi: Remove unnecessary cargo build

CHANGELOG.md, tools/lsp/main.rs
Drop the connection before waiting for the io_threads to join, because those require the Connection's
sender to be destroyed so that the stdio writer
thread can terminate cleanly.
=> Fix slint-lsp process zombies

.github/workflows/ci.yaml
- Re-add windows to the tested platforms
- Use the dev-dependencies and build instructions in packages.json instead of duplicating them in ci.yaml (use a debug build because of #3222 )
- use a separate cache key for the rust cache, to avoid sharing cache with the neon artefacts
=> Fix napi CI

api/napi/__test__/js_value_conversion.spec.ts
Instead, resolve the path to resources/rgb.png relative to the test file.
=> napi: In the tests, don't rely on the current process working directory

api/napi/__test__/compiler.spec.ts, api/napi/src/interpreter/diagnostic.rs
Invoking the diagnostics getter would throw an exception because the JsDiagnostic type has no constructor.
There's however no constructor that would allow for the previous laziness, so instead this PR bites the bullet:
- When diagnostics are requested, we convert them all in one go into proper JavaScript objects.
- The vector returned by line_column is replaced with more idiomatic column and lineNumber properties
=> napi: Fix access to diagnostics

docs/language/index.rst
I'd like to propose simplifying the name of the "Slint design markup language" to the "Slint language". This makes it clearer and people who are interested can learn more what it is. But, for the average user, the name of it can be shorter.
=> Change "Slint design markup language" to "Slint language" to make it clearer and catchier.

internal/renderers/skia/cached_image.rs, internal/renderers/skia/itemrenderer.rs
Make sure that the scale factor to compute the target size for an SVG is a property dependency.
=> Skia: Fix re-rendering quality of SVGs when the scale factor changes

api/cpp/esp-idf/slint/README.md, api/cpp/esp-idf/slint/idf_component.yml
Provide a brief introduction into what the component provides and how to use it. This is very brief, but hopefully a good starting point.
We should link to C++ platform docs once we have them, for example.
When the component includes an example, its README will be automatically rendered below this one.
Also make the esp_lcd_touch component a public dependency, since it's included from `esp_slint.h`.
=> Improve the Slint esp-idf component README

internal/core/graphics/boxshadowcache.rs, internal/core/item_rendering.rs, internal/renderers/femtovg/itemrenderer.rs, internal/renderers/femtovg/lib.rs, internal/renderers/skia/cached_image.rs, internal/renderers/skia/itemrenderer.rs, internal/renderers/skia/lib.rs
The path and layer caches were missing. The first three patches try to fix the individual cases, the last patch tries to clean it all up and make it more robust.
=> Invalidate more item caches in the renderers when the window scale factor changes

api/cpp/CMakeLists.txt
Prospective fix for compat features not having the right effect since the std feature was not set
=> C++: re-order cmake feature

api/cpp/CMakeLists.txt
I did not test that, but looking at the cmake code, I think this is required.
=> C++: Use new name for cmake features

docs/reference/src/advanced/debugging_techniques.md
This topic has some really important information that can be simplified to:
* Make it easier for the reader to find what they're looking for
* Make it easier for the reader to skim - remove words and be more concise
=> Simplify the debugging techniques topic for readability

internal/compiler/generator/cpp.rs
When using debug() we generate calls to `std::cout`.
=> C++: Add iostream to the list of included header files

internal/backends/testing/lib.rs, internal/compiler/generator.rs, internal/compiler/llr/pretty_print.rs, internal/compiler/passes/remove_aliases.rs, tests/cases/issues/issue_3318_window_size.slint
In the case of bug #3318, the implicit alias to the window's height or width was removed but the propery was not marked as externaly modified, causing later pass to optimize and inline things that shouldn't
Fixes #3318
=> Fix alias to externaly modified property not being marked as such

internal/compiler/generator/cpp.rs
Place pre-rendered textures into read-only data, instead of the data section.
Amends 3db168d03d457786bb2d17646e91bf5b90b70025
=> Fix data section placement for pre-compiled textures in C++

api/cpp/include/slint-platform.h, internal/backends/linuxkms/fullscreenwindowadapter.rs, internal/backends/qt/qt_window.rs
We already query the size right after the call to set_visible in the WindowInner::show()
=> Backends: don't resize the WindowItem in set_visible

docs/reference/index.rst, docs/reference/src/advanced/backend_linuxkms.md, docs/reference/src/advanced/backend_qt.md, docs/reference/src/advanced/backend_winit.md, docs/reference/src/advanced/backends.md
=> Initial draft for backend documentation

api/cpp/docs/cmake.md, api/cpp/docs/conf.py, api/rs/slint/lib.rs, docs/reference/src/advanced/backends.md
... and adjust the C++ platform backend docs a little to the current
state.
cc #3208
=> Add links from Rust and C++ to the common platform backend docs

internal/backends/selector/Cargo.toml
With C++, we would not forward the opengl/vulkan flags to the skia renderer, so
selecting no backend but just the SKIA_RENDERER_OPENGL would end
up merely selecting Skia, not activating the opengl feature.
The renderer features will continue to be delegated to the backend
selector crate, where they will be activated directly in the renderer.
=> Fix Skia OpenGL/Vulkan feature selection

internal/backends/linuxkms/renderer/femtovg.rs, internal/backends/winit/renderer/femtovg/glcontext.rs, internal/core/platform.rs, internal/renderers/femtovg/lib.rs
At the moment it's only needed there, so let's
have it there and move it to core later if the need arises.
=> Move the OpenGLInterface back to the FemtoVG renderer

CHANGELOG.md, api/cpp/include/slint-platform.h, api/cpp/include/slint_window.h, api/rs/slint/Cargo.toml, api/rs/slint/docs.rs, api/rs/slint/tests/show_strongref.rs, api/rs/slint/tests/spawn_local.rs, internal/backends/testing/lib.rs, internal/core/api.rs, internal/core/window.rs
show() now let's Slint maintain a strong reference to the component, so that it's easy to create new windows without having to do an awkward dance around keeping the component alive.
Closes #3328
=> Keep the component alive when the window is visible

.github/workflows/ci.yaml
A recent MSVC update requires clang 16 when building with clang against the MSVC headers. The Skia build compiles with clang and is thus affected.
This will be reverted once llvm16 becomes available on the GH runners.
=> Temporarily disable the Windows Rust tests in the CI

examples/cpp/platform_qt/main.cpp
- QWindow::hide() don't terminate the application. QWindow::close() does.
- But QWindow::close() also recurse in the closeEvent, so we must prevent the recursion with m_visible
Fixes #3363
=> platform_qt example: fix closing the window

api/wasm-interpreter/Cargo.toml, api/wasm-interpreter/src/lib.rs
We do the highlighting only from the LSP, even in wasm
=> wasm-interpreter: remove the highlight feature

api/cpp/cbindgen.rs, api/cpp/esp-idf/slint/src/slint-esp.cpp, api/cpp/include/slint-platform.h, api/cpp/tests/platform_eventloop.cpp, examples/cpp/platform_native/windowadapter_win.h, examples/cpp/platform_qt/main.cpp
- s/physical_size/size/ (consistant with the slint::Window API)
- remove const of virtual function  (they don't need to be const and make implementation potentially easier)
- Move the WindowProperties in it
- [make Platform::duration_since_start non-const and pure](https://github.com/slint-ui/slint/pull/3381/commits/c1e25959acd0ad4832902e9c0ef9a398560f6609)
- [Move the PhysicalRegion in the SofwtareRenderer](https://github.com/slint-ui/slint/pull/3381/commits/5b0e40f9a1dcc7a5f17246f6578b0675003e8279)
=> C++: Api changes in the WindowAdapter/Platform

internal/core/graphics/image.rs, internal/renderers/femtovg/images.rs, internal/renderers/skia/cached_image.rs
- Make BorrowedOpenGLTextureOrigin non_exhaustive
- Mark BorrowedOpenGLTextureBuilder::new_gl_2d_rgba_texture as unsafe instead of build(). The former takes the arguments that may be garbage, not the latter.
=> API fixes to the OpenGL texture borrowing API

internal/core/model/adapters.rs
- Add missing documentation to various new functions
- Remove unused `inner_model()` function. We don't have an equivalent in the other model classes. C++ has source_model() though, but we can add that if needed.
=> API changes to ReverseModel and doc fixes

api/cpp/cbindgen.rs, internal/core/accessibility.rs, internal/core/api.rs, internal/core/graphics/image.rs, internal/core/input.rs, internal/core/items.rs, internal/core/timers.rs, internal/core/window.rs, internal/interpreter/ffi.rs
Otherwise the ABI may differ between the C++ and the Rust
=> use `#repr(uX)` instead of `repr(C)` for fieldless enums

editors/vscode/src/wasm_preview.ts, tools/lsp/language/semantic_tokens.rs, tools/lsp/wasm_main.rs
- the "preview" command don't contain a "design_mode" arg, but later the generated js for the wasm checked that it is a boolean.
- The url comparison did not work when using the binary lsp and wasm preview. Event though the URL string is the same, the object were not exactly equals.
- Fix rust warnings in the wasm lsp build
=> Fixes to wasm_preview

.github/workflows/nightly_snapshot.yaml
In forks of the slint repo, those secrets are not presented. The cron schedule however implies that the job will be run, and
in every for of the Slint repo the nightly
always fails and produces an email.
Stop that :-)
=> ci: don't run vsix or doc publishing without secrets

docs/resources/slint-docs-preview.html
Place the preview into an item in a flexbox after the source code, so that it wraps around on mobile.
Fixes #3389
=> Improve wasm preview on mobile

internal/core/graphics/color.rs
The `serde` feature enables serde implementations for various structures. I'd like to see them for Color.
=> Derive serde for Color

.github/workflows/ci.yaml, CHANGELOG.md, Cargo.toml, api/cpp/CMakeLists.txt, api/node/README.md, api/node/cover.md, api/rs/slint/README.md, docs/building.md, docs/tutorial/cpp/src/getting_started.md, docs/tutorial/node/src/getting_started.md
Many of our dependencies already made the jump and require a cargo update hack, so make it official
Removed the MSRV from the README since it applies to master branch and people read the readme also for the released version. There is enough documentation of the MSRV in other locations.
=> Upgrade MSRV to 1.70

api/cpp/include/slint.h, internal/compiler/expression_tree.rs, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/llr/expression.rs, internal/compiler/llr/lower_expression.rs, internal/compiler/llr/optim_passes/inline_expressions.rs, internal/compiler/llr/pretty_print.rs, internal/compiler/passes.rs, internal/compiler/passes/remove_return.rs, tests/cases/expr/return2.slint
So it doesn't appear in the LLR and the C++ codegen can be simplified. In particular, this removes the need to throw/catch exception to handle return acrros generated lambdas
=> Make a pass to remove the Expression::Return instruction

internal/backends/winit/renderer/sw.rs
It is possible that softbuf allocate a larger buffer than in needs?
Prospective fix for #3406
=> winit-sw: Loop over the buffer instead of using indices

editors/vscode/src/browser.ts, editors/vscode/src/common.ts, editors/vscode/src/extension.ts, editors/vscode/src/snippets.ts, tools/lsp/language.rs, tools/lsp/language/properties.rs, xtask/src/license_headers_check.rs
A little productivity booster for editing .slint files in VS Code:
https://github.com/slint-ui/slint/assets/140617/5bd66495-bf1c-4f5a-9e55-326098bf3b74
Notice that LSP code actions and workspace edits do not yet natively support snippets or allow specifying the cursor position (https://github.com/microsoft/language-server-protocol/issues/724), which is necessary for pre-selecting "element" for conveniently typing in the desired type name. This limitation is worked around by registering an experimental "snippet text edit" capability for the client, guarding the snippet code action with a capability check on the server side, and finally, detecting and inserting the snippet on the client side (inspired by [rust-analyzer](https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/lsp-exte …
=> vscode: add "wrap in element" code action

CHANGELOG.md, internal/common/enums.rs, internal/core/items/text.rs, tests/cases/text/input_type_decimal.slint, tests/cases/text/input_type_number.slint
This PR is for issue https://github.com/slint-ui/slint/issues/3356
Changes include:
- Update enum `InputType`, add `Number` and `Decimal` field
- Update `key_event` logic
- Add two more test cases
=> Expand InputType to support number type

tools/lsp/language.rs
Somehow the vscode extension started to send an empty string for the showPreview command instead of nothing. Resulting in the showPreview command from the command palette not working anymore.
Fix #3412
=> LSP: handle empty string as component name in the showPreview command

internal/compiler/widgets/fluent-base/tableview.slint, internal/compiler/widgets/material-base/tableview.slint, internal/compiler/widgets/native/internal-scrollview.slint, internal/compiler/widgets/native/std-widgets-impl.slint, internal/compiler/widgets/native/std-widgets.slint, internal/compiler/widgets/native/tableview.slint
By using a `ListView` instead of a `ScrollView` + `VerticalLayout`, we trigger the optimization where only visible children are being instantiated. In my application it makes a very noticeable difference.
For some reason, changing to `ListView` made the existing vertical padding disappear. I don't know where this padding came from before, but I've restored it by adding padding to the `TableViewCell`.
If this optimization is correct I can look into doing the same for other styles.
=> Optimize StandardTableView in Fluent, Material and Native styles

CHANGELOG.md, internal/compiler/parser.rs, tools/lsp/language.rs
A counterpart of #3420 that essentially does the opposite i.e. removes an element from around its sub-element(s). The proposed algorithm substitutes the element with its sub-elements, including repeated and conditional elements, dropping properties, callbacks, and anything else associated with the element being removed.
https://github.com/slint-ui/slint/assets/140617/985b9384-422b-4b3c-b3e6-381c8108eecc
=> VSCode: add "Remove element" code action

api/cpp/include/slint.h, api/cpp/include/slint_window.h, internal/backends/winit/accesskit.rs, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/llr/expression.rs, internal/compiler/llr/item_tree.rs, internal/compiler/llr/lower_expression.rs, internal/compiler/llr/lower_to_item_tree.rs, internal/compiler/llr/optim_passes/count_property_use.rs, internal/compiler/llr/pretty_print.rs, internal/compiler/object_tree.rs, internal/compiler/passes/generate_item_indices.rs, internal/core/component.rs, internal/core/input.rs, internal/core/item_focus.rs, internal/core/item_rendering.rs, internal/core/item_tree.rs, internal/core/items.rs, internal/core/items/component_container.rs, internal/core/items/text.rs, internal/core/model.rs, internal/interpreter/dynamic_component.rs, internal/interpreter/highlight.rs
So that the compiler and run-time can never disagree on the number of bytes the item index can use.
=> Change item indices from usize to u32

internal/compiler/generator/cpp.rs, tests/cases/models/delete_from_clicked.slint
The parent is already deleted when we delete the component that is kept alive by the `grabber` ItemRc in `handle_mouse_grab` When the ItemRc goes out of scope, we delete the component, but the parent was already gone.
This doesn't solve a broader issue that we use the parent in many place and it is not kept alive (for example when using properties of the parent)
=> C++: Fix crash when deleting a component from the click event within a sub component

CHANGELOG.md, internal/renderers/skia/opengl_surface.rs
Apply https://github.com/slint-ui/slint/pull/3179 also to the Skia OpenGL surface.
A zero size is permitted with Metal for example, but we panic'ed.
Fixes #3472
=> Don't panic when the windowing system tries to assign a zero size to a GL surface

internal/renderers/femtovg/fonts.rs
Eliding a single line or long wrapping lines works fine because the ellipsis character is inserted after the last glyph that fits, before the newline character. But when eliding the last visible text line, the FemtoVG renderer would format the elided line like this:
https://github.com/slint-ui/slint/blob/14f7fe4ba295cc93d450a162e13699df657badff/internal/renderers/femtovg/fonts.rs#L657
If the line ended with a trailing newline, it would append the ellipsis after the newline character. For example, an empty line would become `"\n…"`.
https://github.com/slint-ui/slint/assets/140617/1d0d6639-f1c5-44d1-abb1-3a8f90c07cf9
https://github.com/slint-ui/slint/assets/140617/d1a5a807-66fc-4c61-8c1e-df009c5a14ec
```
export component StatusBox inherits Window  {
preferred-width: 400px;
preferred-height: …
```
=> FemtoVG: fix eliding empty lines

internal/renderers/skia/itemrenderer.rs, internal/renderers/skia/lib.rs, internal/renderers/skia/textlayout.rs
A partial fix to #3481. Make sure to specify the maximum amount of lines when eliding text with word wrapping to avoid Skia truncating it to just one line.
https://github.com/slint-ui/slint/assets/140617/5086735d-6d0b-4736-9aab-5851793ccc4a
https://github.com/slint-ui/slint/assets/140617/a86429ee-b129-41be-be88-f2e3963a9dfd
<details><summary>testcase.slint</summary>
```
export component TestWindow inherits Window  {
preferred-width: 640px;
preferred-height: 320px;
HorizontalLayout {
x: 0;
padding: 20px;
for valign in [TextVerticalAlignment.top, TextVerticalAlignment.center, TextVerticalAlignment.bottom]: Rectangle {
border-color: red;
border-width: 2px;
Text {
text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. …
```
=> Skia: fix eliding of multiline text

internal/renderers/femtovg/fonts.rs
A partial fix to #3481. Fixes vertically centered and bottom-aligned elided text for the FemtoVG renderer.
https://github.com/slint-ui/slint/assets/140617/bf7b7ed1-3528-4b1f-83a6-597a4cc4f2a8
https://github.com/slint-ui/slint/assets/140617/238e171e-097a-4231-bca0-1597d00de3c8
<details><summary>testcase.slint</summary>
```
export component TestWindow inherits Window  {
preferred-width: 640px;
preferred-height: 320px;
HorizontalLayout {
x: 0;
padding: 20px;
for valign in [TextVerticalAlignment.top, TextVerticalAlignment.center, TextVerticalAlignment.bottom]: Rectangle {
border-color: red;
border-width: 2px;
Text {
text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud …
```
=> FemtoVG: fix vertical alignment of elided text

api/rs/slint/lib.rs
It was not meant to be public.
Added a deprecated note even if deprecared on `pub use` don't show warnings
=> Hide the ComponentFactory from the docs

internal/compiler/widgets/cupertino-base/tableview.slint, internal/compiler/widgets/fluent-base/tableview.slint, internal/compiler/widgets/material-base/tableview.slint, internal/compiler/widgets/native/tableview.slint
This PR fixes the issue that it was not possible to drag `StandardTableView` scroll bars or resize its headers when initiated from the first mouse press because the internal `FocusScope` ate the first mouse press.
Fixes: #3436
=> StandardTableView: prevent internal FocusScope from eating the first press

CHANGELOG.md, internal/core/graphics/image.rs
After loading an image with `Image::load_from_path` and setting to a source property, upon rendering with Skia, it would get replaced with a Skia renderer specific image representation. When later setting another image that was also using `ImageInner::BackedStorage`, the property would not get set because PartialEq::eq would return true because the image inner types are the same, instead of comparing the vtable pointers.
Fixes #3510
=> Skia renderer: Fixed the `source` property of `Image` elements sometimes not changing when setting dynamically loaded images

internal/backends/qt/qt_widgets/button.rs, internal/backends/qt/qt_widgets/checkbox.rs, internal/backends/qt/qt_widgets/combobox.rs, internal/backends/qt/qt_widgets/groupbox.rs, internal/backends/qt/qt_widgets/lineedit.rs, internal/backends/qt/qt_widgets/progress_indicator.rs, internal/backends/qt/qt_widgets/scrollview.rs, internal/backends/qt/qt_widgets/slider.rs, internal/backends/qt/qt_widgets/spinbox.rs
Instead of setting it to 0 which cause `widget.preferred-width` ti be 0
Fixes #3527
=> Qt Widgets: set the preferred-size to the minimum-size

internal/compiler/widgets/fluent-base/lineedit.slint, internal/compiler/widgets/fluent-base/spinbox.slint, internal/compiler/widgets/fluent-base/textedit.slint
When selecting text, the foreground color is inverted
=> Fluent: fix selection foreground color

examples/todo/ui/todo.slint, internal/compiler/widgets/material-base/checkbox.slint
- Remove extra padding from the todo demo. Box in Box causes the padding to be added twice otherwise. And the Box have extra big padding with the material style.
- Fixup the combobox size to be consistant with fluent wrt sizing
- Use the proper color for the checkbox border, following the style specification
=> material style todo demo polish

tests/cases/elements/component_container.slint, tests/driver/cpp/build.rs, tests/driver/driverlib/lib.rs, tests/driver/interpreter/build.rs, tests/driver/nodejs/build.rs, tests/driver/rust/build.rs
Makes it easy to ignore unsupported test cases for specific drivers (cpp, interpreter, js, rust) at the cost of having to read test case sources at build time.
For example, `tests/cases/elements/component_container.slint` does not support C++ or JS:
```
//ignore: cpp,js
```
See also https://github.com/slint-ui/slint/pull/3523#discussion_r1337664179
=> Tests: add support for `//ignore: <driver(s)>`

internal/backends/winit/Cargo.toml
The new version of winit fixes an important bug for macOS Sonoma, and the bugvix for the workaround won't happen before winit 0.29. The branch that port to winit 0.29 already removed the workaround
Fixes #3559
=> Unpin winit version

internal/compiler/typeregister.rs
This is a fairly large struct and it uses lots of the limited thread local space which is limited on some platform
This also doesn't need to be on a thread local since we only use it once just to register the types.
Should help with #3551
=> compiler: Don't put builtin structs on a thread-local

CHANGELOG.md, docs/reference/src/language/builtins/elements.md, internal/compiler/builtins.slint, internal/compiler/layout.rs, internal/compiler/llr/lower_expression.rs, internal/compiler/passes/lower_layout.rs, internal/compiler/tests/syntax/layout/spacing.slint, internal/interpreter/eval_layout.rs, tests/cases/layout/grid_spacing.slint
Close #3492 
Add `spacing-horizontal` and `spacing-vertical` as specialization of `spacing` in `GridLayout`.
As mention in the issue, this currently also add them to `HorizontalLayput` and `VerticalLayout`. How should I handle this ? forbid it through a compiler step ?
=> Add spacing-horizontal and spacing-vertical to layout

.github/workflows/build_docs.yaml, api/rs/slint/Cargo.toml
rustdoc removes the `no-preview` tag, and we anyway do not have a slint file to preview in the docs anymore
=> Remove the preview from the rust docs

api/cpp/CMakeLists.txt
Since commit 7947f233f1a744f5ce9dfdf44372727d4fefb50b in Corrosion, cmake will default to ${CMAKE_C_COMPILER} for linking a cdylib, which means that C must be enabled as a language in the project.
Previously, it tried C, CXX, and Fortran and picked the first one.
=> Fix cross-compilation with a Yocto SDK

.github/workflows/nightly_snapshot.yaml
This tries to extract the version automatically, and put the files directly in the right location
Also fill the tag and name with the version for the github release
Part of #2995
=> CI: merge the website copy job from the website repo into the release action

api/cpp/CMakeLists.txt, api/cpp/cmake/SlintConfig.cmake.in
Use a FILEPATH to reflect that this is a path to a file and then the cmake configurator will show a file dialog.
=> Improve file type for SLINT_COMPILER cmake cache variable

internal/renderers/femtovg/itemrenderer.rs
A partial fix to #3580.
Calculate the appropriate cursor position according to the horizontal alignment instead of falling back to `PhysicalLength::default()` when there's nothing to layout i.e. the text input is empty.
https://github.com/slint-ui/slint/assets/140617/0787fc01-9db0-4d67-987e-0d0c7c560908
https://github.com/slint-ui/slint/assets/140617/291c6c7e-2b7e-401a-b6fe-f9d02f826fc1
=> FemtoVG: fix empty text input cursor alignment

internal/interpreter/eval.rs, tests/cases/crashes/issue3589_layout_click_deletes_item.slint
What happens is that the item is destroyed and removed from the layout
when clicking. But the send exit event still query the geometry if the
ItemRc which points to position in the layout cache that is not valid.
The Rust and C++ generator already check for the vailidity of the index
and return 0 if it's too large.
Fixes https://github.com/slint-ui/slint/issues/3589
=> Interpreter: fix crash when clicking on a item causes it to be destroyed

CHANGELOG.md, internal/compiler/passes/resolving.rs, internal/compiler/tests/syntax/lookup/conversion.slint, tests/cases/types/array_of_array.slint
When finding the common types for array of array, we must recurse in the inner type
Fixes: #3574
=> Compiler: fix conversion of array of array of structs

internal/renderers/skia/textlayout.rs
`SkParagraph::getRectsForRange()` does not report the text box of a trailing newline correctly: https://fiddle.skia.org/c/8ed057a649687bf916581fe0b8ebfad0. As a workaround, use the last line's metrics to get the correct coordinates.
Close: #3590
=> Skia: workaround for cursor rect at a trailing newline

internal/renderers/skia/itemrenderer.rs, internal/renderers/skia/lib.rs, internal/renderers/skia/textlayout.rs
Same as #3585 but for Skia. Calculate the appropriate cursor position according to the horizontal alignment instead of falling back to `PhysicalLength::default()` when there's nothing to layout i.e. the text input is empty.
https://github.com/slint-ui/slint/assets/140617/bfd94d9b-3c3a-40ae-a566-b076939e8da9
https://github.com/slint-ui/slint/assets/140617/ce858e1e-2da8-46bf-bd0e-e7c2982ba9e1
Close: #3580
=> Skia: fix empty text input cursor alignment

internal/backends/linuxkms/Cargo.toml
We enable libseat's custom_logger feature by default, which redirects log output from libseat into the Rust log facade. That's nice, but as part of the implementation of this feature unfortunately libseat's build.rs unconditionally adds /usr/local/include to the list of the search include paths when compiling the log_handler.c file. That breaks the Yocto build, rightly so:
warning: cc1: error: include location "/usr/local/include" is unsafe for cross-compilation [-Werror=poison-system-directories]
We can do without this feature, so let's not enable it.
=> Fix build of linuxkms backend on Yocto

internal/renderers/skia/textlayout.rs
Second attempt to fix multi-line eliding (#3481) for Skia.
| | Before | After |
|---|---|---|
| Linux | ![image](https://github.com/slint-ui/slint/assets/140617/0d316229-2599-4600-8d9f-e78cfac1e6f3) | ![image](https://github.com/slint-ui/slint/assets/140617/67089ecd-d4c9-4e55-b4a6-f2c1afc0dc41) |
| macOS | <img width="212" alt="Screenshot 2023-10-02 at 19 07 03" src="https://github.com/slint-ui/slint/assets/140617/b6cee6a3-83d7-43ee-a52d-9dc285341e4b"> | <img width="212" alt="Screenshot 2023-10-02 at 19 07 31" src="https://github.com/slint-ui/slint/assets/140617/da66560a-b2dc-432b-bee2-97c740010a17"> |
=> Skia: fix line height calculation for eliding the last line of text

api/cpp/CMakeLists.txt
When building with cmake, buildroot sets PKG_CONFIG_SYSROOT_DIR in its toolchain file, and therefore it's only available at configure time but not build time, which is when our dependencies need it.
=> Fix build of dependencies that use pkg-config when building Slint in buildroot

api/cpp/CMakeLists.txt
Commit 9b62b08ed66aec83b0f5805c1d7484a968d0351f fixed https://github.com/slint-ui/slint/issues/1066 initially, but commit 1036c0d0824788d15b24214ce7b7338f75dcd7d4 erroneously regressed this again, because while Corrosion sets this property, it is only set on the locally generated CMake target. We still need to propagate that also into the installed CMake target, which this patch does.
=> Fix cmake producing absolute DT_NEEDED paths in applications when linking against installed libslint_cpp on Linux

internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/passes/collect_structs_and_enums.rs, tests/cases/exports/export_structs_and_enums_as.slint, tests/cases/exports/named_exports.slint
When components, enums, and structs are exported with names from Slint, generate the respective aliases for Rust and C++.
Fixes: #3599
=> Fix named exports in native code

api/cpp/CMakeLists.txt, api/cpp/cmake/SlintConfig.cmake.in
This reverts commit 0773e51d92928fdeea3dd1c79c899455f8a4000f.
By the SLINT_COMPILER being a `FILEPATH`, cmake will convert any relative path to an absolute path. That's not wanted for the Yocto build, because there we pass
'$ENV{OECORE_NATIVE_SYSROOT}/usr/bin/slint-compiler', so that the path is resolved dynamically against the environment variable that the Yocto SDK sets.
CMake would convert this to an absolute path that points into the build directory, i.e. it would be /home/blah/foo/\$ENV{...}
=> Revert "Improve file type for SLINT_COMPILER cmake cache variable"

internal/backends/linuxkms/display/egldisplay.rs
If the chosen connector doesn't have a current encoder (who's crtc we could use), fall back to the algorithm described in
https://manpages.debian.org/testing/libdrm-dev/drm-kms.7.en.html#CRTC/Encoder_Selection
for selecting the crtc (minus the usage check, since we drive only one connector). This is also the same logic as in kmscube.
=> linuxkms: Prospective fix for failing crtc setup

internal/backends/linuxkms/calloop_backend/input.rs
When using qemu we receive these, for example.
=> linuxkms: Add support for motion pointer events with absolute coordinates

internal/backends/linuxkms/calloop_backend/input.rs
When supplying logical touch coordinates to the slint::Window, scale them to the logical screen size, not the physical one.
=> linuxkms: Prospective fix for touch input when SLINT_SCALE_FACTOR is set

tests/screenshots/testing.rs
For example, with the rotation threshold removed from `linear-gradients.slint` 
```diff
diff --git a/tests/screenshots/cases/software/basic/linear-gradients.slint b/tests/screenshots/cases/software/basic/linear-gradients.slint
index 24c6d0467..eba1fa872 100644
--- a/tests/screenshots/cases/software/basic/linear-gradients.slint
+++ b/tests/screenshots/cases/software/basic/linear-gradients.slint
@@ -1,8 +1,6 @@
// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.1 OR LicenseRef-Slint-commercial
-// ROTATION_THRESHOLD=150  - because gradiants are very impresise in rotation
-
export component TestCase inherits Window {
width:  64px;
height: 64px;
```
```sh
$ SLINT_TEST_FILTER=linear-gradients SLINT_CREATE_SCREENSHOTS=1 …
```
=> test-driver-screenshots: don't generate rotated screenshots

tools/lsp/language.rs
In [package.json](https://github.com/slint-ui/slint/blob/7d7b73107504f267d4f8752c4d8ab7c354c8bae9/editors/vscode/package.json#L110-L116), the config item is spelled `includePaths` not `includePath`.
=> LSP: fix typo in "slint.includePaths" config

internal/compiler/layout.rs, internal/compiler/llr/lower_expression.rs, internal/compiler/passes/default_geometry.rs, internal/interpreter/dynamic_item_tree.rs
Before:
cargo run -p slint-compiler -- examples/printerdemo_mcu/ui/printerdemo.slint -f rust | rustfmt | wc
40014   86643 2010535
cargo run -p slint-compiler -- examples/gallery/gallery.slint -f rust | rustfmt | wc
105715  229009 5434115
After:
cargo run -p slint-compiler -- examples/printerdemo_mcu/ui/printerdemo.slint -f rust | rustfmt | wc
38643   84506 1925846
cargo run -p slint-compiler -- examples/gallery/gallery.slint -f rust | rustfmt | wc
103210  224427 5291034
No measurable changes in compilation time.
=> Some attempts at reducing the generated code size

internal/core/software_renderer.rs, internal/core/textlayout.rs, internal/core/textlayout/linebreaker.rs
#3615 made sure to stop rendering after reaching the last elided line. We can do better and stop breaking lines at all when reaching the max, to avoid unnecessary work and to simplify the subsequent layout and rendering process.
=> SW: stop breaking lines after reaching the max (elided) lines

internal/core/input.rs, internal/core/items.rs, tests/cases/elements/flickable3.slint
The code that was making sure has-hover is kept in sync was no longer working
because of the introduction of the scroll-event.
Sadly, the flickable3.slint test didn't catch that because of another
bug.
Fixes https://github.com/slint-ui/slint/issues/3666
=> Fix has-hover in Flickable with scroll wheel 

CHANGELOG.md, internal/core/model/adapters.rs
As a mean of getting the inner model, useful to be able to push into the underlying model. (This already exists in the CPP API.)
Also implement `as_any()` on adapters model otherwise the `source_model()` is a bit useless.
=> Add source_model() in adapter models

.github/workflows/ci.yaml, api/napi/package.json
We use esbuild to transform index.ts into index.js, but we also need to perform a type check. esbuild doesn't do that, this is left to the typescript compiler. So let's run it with -noEmit as recommended by the esbuild folks, in debug builds as well as in the CI (which doesn't do debug builds).
=> napi: Catch typescript errors in the CI and in debug builds

internal/compiler/llr/lower_to_item_tree.rs, internal/compiler/object_tree.rs, internal/compiler/passes/default_geometry.rs, internal/compiler/passes/lower_component_container.rs, internal/compiler/passes/lower_shadows.rs, internal/compiler/passes/visible.rs, tests/cases/layout/issue_1072_opacity_geometry.slint
Parents surch as Opacity, Clip, and co, used to steal the x and y property of their children, making the property not what they ought to be.
Now that we refactored recently the code so that geometry need not to be always linked to a property of the same name, we can dissociate the x and y property of these generated elements and their content so that the actual "x" property of the former elementstay some value, despite its relative item property is now 0.
Had to change a bit of code that was still assuming a literal "height" or "width" or "y" or "x" property that no longer worked when the geometry is dissociated from its property
Fix #1072
=> Don't steal the x and y properties for dummy parents

api/cpp/include/slint.h, internal/compiler/generator/rust.rs, internal/core/item_tree.rs, internal/core/items/component_container.rs, internal/interpreter/dynamic_item_tree.rs
In `ItemRc::find_sibling` we currently do:
1. get the range
2. check that the next index is within the range
3. call `get_subtree`
The problem is that get_subtree itselg will call 'ensure_updated' which will do the relayout of the ListView and may get a different range of element.
So don't query the range before and just have get_subtree to return an empty ItemWeak if we are out of the actual range.
Couldn't really find a way to make a test since this is called from the accessibility code which is hard to test as is
For #3700
=> Fix panic with very large ListView

internal/renderers/skia/opengl_surface.rs
Sometimes Radon drivers report on Windows erroneously that it supports GL_NV_framebuffer_blit as extension but when looking up glBlitFramebufferNV via getProcAddress it returns a null pointer.
The issue goes away when bumping the GLES version. GLES 2.0 was released in 2003 and 3.0 in 2012. Practically everyone supports it nowadays (even Safari), so that's the easiest solution for the Skia renderer.
=> Fix Skia not rendering with some Radeon drivers on Windows

CHANGELOG.md, Cargo.toml, docs/reference/src/advanced/backend_winit.md, internal/backends/linuxkms/renderer/skia.rs, internal/backends/winit/Cargo.toml, internal/backends/winit/lib.rs, internal/backends/winit/renderer/femtovg.rs, internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/sw.rs, internal/backends/winit/winitwindowadapter.rs, internal/core/Cargo.toml, internal/renderers/skia/Cargo.toml, internal/renderers/skia/d3d_surface.rs, internal/renderers/skia/lib.rs, internal/renderers/skia/metal_surface.rs, internal/renderers/skia/opengl_surface.rs, internal/renderers/skia/software_surface.rs, internal/renderers/skia/vulkan_surface.rs
This provides a fallback in scenarios where the GPU acceleration initialisation fails. It's sub-optimal in performance as it re-renders the entire window, but it's a starting point and better than producing an error. A warning is printed to stderr (actually, routed via our debug_log) when that fallback kicks in.
cc #1636
=> Add support for Skia software rendering with the winit backend

CHANGELOG.md, tools/lsp/language.rs
With named snippet placeholders copied from the docs:
- Repeat element: "`for <name>[index] in <model> : `Element {}"
- Make conditional: "`if <condition> : `Element {}"
https://github.com/slint-ui/slint/assets/140617/250c4b92-a47c-45ba-9bac-76d74597190f
=> LSP: add "Repeat element" and "Make conditional" code actions

internal/backends/qt/qt_window.rs
Silence this warning:
```
warning: i-slint-backend-qt@1.3.0: qt_window.rs:1536:17: warning: ignoring temporary created by a constructor declared with 'nodiscard' attribute [-Wunused-value]
```
=> qt: Silence warning during Slint build

examples/gallery/index.html, examples/imagefilter/index.html, examples/memory/index.html, examples/plotter/index.html, examples/printerdemo/rust/index.html, examples/slide_puzzle/main.rs, internal/backends/winit/lib.rs, internal/backends/winit/winitwindowadapter.rs, internal/core/layout.rs
Following the winit 0.29 merge, a few adjustments are in order:
- Make slint::Window.set_size() before show keep the size
- on wasm, attempt to keep the size of the canvas from CSS
- on wasm, one must set the width and height explicitly on the canvas otherwise there is wierd scaling
- on wasm, we can't set None as maximum or minimum size otherwise winit panics
- It seems that the hack we had to keep the size in range is no longer necessary
- The hack in the slide puzzle can be removed. (but unfortunately it doesn't follow resizes
Unfortunatelly we always call set_inner_size to avoid infinite loop when the css properties are not specificed, so this will override layouts
Also we don't default anymore to the preferred size
=> Winit initial size adjustments and wasm size fixes

internal/backends/selector/lib.rs, internal/backends/winit/README.md, internal/backends/winit/event_loop.rs, internal/backends/winit/lib.rs, internal/backends/winit/renderer/femtovg.rs, internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/sw.rs, internal/compiler/generator/rust.rs
Propagate the winit error when `DISPLAY` or `WAYLAND_DISPLAY` isn't set and fall back to other available backends.
=> Improve winit and backend selector error handling

internal/compiler/passes/lower_shadows.rs
commit 975abf3c42d8c91b36c9a0347f82d6138b52fb47 introduced a regression. Two problem:
- we were taking the geometry from the parent instead of the element that need the shadow
- Element::make_rc override the geometry with its own properties
Unfortunately annot be tested as this only visual, and the software renderer don't support shadow yet
Fixes #3743
=> Fix drop shadow

internal/renderers/skia/Cargo.toml, internal/renderers/skia/opengl_surface.rs
Remove support for GLX. The primary use-case is indirect GPU accelerated
rendering over remote X (say via ssh and X forwarding). That comes at
the expense of an otherwise ugly API (see earlier revisions of this PR)
and issues like #3757, because the GLX error handling requires hooking
into the process-global X error handler. This was already supported only
when using Skia with winit (and thus Rust), not when using the C++ Skia
renderer.
Instead, if GLX is not available, we will fall back to software
rendering as per #3716.
=> Decouple the Skia renderer from winit

internal/backends/qt/qt_widgets.rs
The name passed was always "Slint", which can show up in the task switcher, as seen on Linux/Xfce. Instead, we now use `std::env::args()` to pass the actual first argument.
I think ideally this should use `std::env::args_os()` since we don't need the data to be valid unicode (in which case this will panic). However, stable Rust does not appear to provide a way to get at the bytes of an `OsString` (except on Linux).
=> Qt: Fix executable name passed to QApplication

internal/renderers/skia/Cargo.toml, internal/renderers/skia/cached_image.rs, internal/renderers/skia/d3d_surface.rs, internal/renderers/skia/itemrenderer.rs, internal/renderers/skia/lib.rs, internal/renderers/skia/metal_surface.rs, internal/renderers/skia/opengl_surface.rs, internal/renderers/skia/software_surface.rs, internal/renderers/skia/vulkan_surface.rs
This updates to m118. See
https://github.com/rust-skia/rust-skia/releases/tag/0.67.0 for more details.
=> Bump skia-safe version

CHANGELOG.md, api/rs/macros/lib.rs
We currently use the debug representation of Span to know if they are next touching eachother as there are no stable way currently. But that doesn't work with rust analyzer as it doesn't have a representation we can test.
Also Span::source_text is not implemented with rust analyzer.
So just default to identifier with `-` touching instead of not touching as this happens more often.
One can still use `(foo)-(bar)` when one really need minus
CC #685
=> Improve the slint! macro with rust-analyzer with `-`

.github/workflows/ci.yaml, tests/driver/nodejs/nodejs.rs
In the ci and on workstations the steps are the same:
1. Install (without building, which would build release)
2. Build debug
3. Run tests
Previously only on Windows the tests were run in debug, because the "npm install" step in the nodejs test driver would overwrite a previously created debug build. On windows they are separate DLLs, and thus co-exist. With this patch we always build debug.
=> Build the node package only once in debug

internal/core/Cargo.toml, internal/interpreter/Cargo.toml, tools/lsp/Cargo.toml
Saves 1M in the binary
We use the browser to render the images anyway
Note: i-slint-core still bring image with png and jpeg codecs, as well
as svg deps. We just need the image-decoders feature to load the builtin
images, of these there are only svg.
(also has a cleanup stuff for the interpreter Cargo.toml)
=> wasm: Don't include all image codecs on the lsp

api/node/__test__/api.spec.ts, api/node/__test__/compiler.spec.ts, api/node/__test__/js_value_conversion.spec.ts, api/node/package.json, api/node/tsconfig.json
Share tsconfig.json so that ava runs the typescript compiler also on the tests.
Sadly, the exception that the Slint compiler throws is not type declared, so we have to use any.
Similarly, the object share returned by loadFile() is unknown in terms of properties, callbacks, etc.
=> node: Fix typescript setup for tests

internal/core/string.rs, tests/cases/types/string.slint, tests/cases/types/string_to_float.slint
Converting 12.3 to a string would be "12.30000001907" which is not what one would want
=> C++: fix string conversion from float not being round

internal/renderers/skia/Cargo.toml
For details, see https://github.com/rust-skia/rust-skia/releases/tag/0.68.0
This simplifies cross-compilation and adds risc-v builds.
=> Update skia-safe to 0.69

internal/compiler/lookup.rs, internal/compiler/tests/syntax/lookup/global.slint, internal/compiler/tests/syntax/lookup/property.slint, tools/lsp/language/completion.rs
It only stay accessible in our builtin styles
Fixes #3793
=> Disallow access to internal globals (NativeStyleMetrics and SlintInternal)

api/node/__test__/js_value_conversion.spec.ts, api/node/index.ts, api/node/src/types/image_data.rs, docs/tutorial/node/src/main_game_logic.js, examples/memory/main.js
The rules require comparing if tiles are equal, which used to be a string comparison as we just converted the image to a path. With ImageData this doesn't work anymore, so this patch proposes an optional path property that makes the code also a tad bit more readable.
=> Fix Node.js version of memory game not working properly

Cargo.toml, examples/todo/rust/Cargo.toml, examples/todo/rust/main.rs, internal/backends/android-activity/Cargo.toml, internal/backends/android-activity/LICENSES/GPL-3.0-only.txt, internal/backends/android-activity/LICENSES/LicenseRef-Slint-Royalty-free-1.1.md, internal/backends/android-activity/LICENSES/LicenseRef-Slint-commercial.md, internal/backends/android-activity/README.md, internal/backends/android-activity/lib.rs, internal/backends/selector/Cargo.toml, internal/backends/selector/lib.rs, internal/renderers/skia/Cargo.toml
This is a backend that implement a slint::platform for android-activity
This also adapt the `todo` example so it can be run on android.
In order to run it on android, the `#wasm#` lines in the todo/Cargo.toml need to be removed, and the 
todo example can be run with cargo-apk:   `cargo apk run  -p todo --target aarch64-linux-android --lib` (and the proper env variable needs to be defined for the NDK and the SDK)
This work is sponsored by NLnet
Part of https://github.com/slint-ui/slint/issues/46
=> Introduce android-activity backend

internal/compiler/passes/remove_return.rs, internal/compiler/passes/resolving.rs, tests/cases/expr/return2.slint
If a branch that always return has a "void value" and the side that doesn't return has a value, we need to synthetize a default value so the struct is complete, even if that value is not used.
=> Fix slint compiler panic in chiptrack

api/cpp/include/slint.h, internal/compiler/passes/resolving.rs, internal/compiler/tests/syntax/lookup/conversion.slint, tests/cases/models/array.slint
Regression noticed in this line:
https://github.com/Tricked-dev/stardew-mod-manager/blob/3f97d98bfff8c56161c9f5afcf003a580af34ff6/ui/tabs/downloads.slint#L77
The following used to work:
```slint
import { Button, VerticalBox } from "std-widgets.slint";
export component Demo {
in property <[int]> mods;
VerticalBox {
alignment: start;
for xxx in true ? mods : [] : HorizontalLayout { alignment: center; Button { text: "OK!"; } }
}
}
```
But we fixed array conversion and this caused a regression with empty array
=> Fix regression with empty array

internal/compiler/widgets/cupertino-base/button.slint, internal/compiler/widgets/fluent-base/button.slint
The Material button already has the forward-focus.
=> Make it possible to focus Cupertino and Fluent buttons

internal/backends/linuxkms/fullscreenwindowadapter.rs, internal/core/graphics/image.rs, internal/core/graphics/image/svg.rs, internal/renderers/skia/cached_image.rs
Make the size argument to svg::render optional to mean that it is the default size of the image.
Otherwise, passing None as the size to ImageInner::render_to_buffer would not render the image which is possible in some backend (eg: the button image icon with the qt backend)
And if the image is really rendered on an empty because of layouting or so, we don't need to show a warning anyway.
Fix #3790
=> Silence error when rendering SVG in an 0x0 size

internal/backends/android-activity/README.md
To serve as docs while the backend is still internal
=> Android: add readme for the backend

api/cpp/include/slint.h, examples/gallery/ui/pages/easings_page.slint, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/llr/optim_passes/count_property_use.rs, internal/compiler/llr/optim_passes/inline_expressions.rs, tests/cases/properties/animation_props_depends.slint
resulting in properties being optimized when they shouldn't
=> Fix animation expression not being visited for use count of property

internal/backends/winit/lib.rs, internal/backends/winit/wasm_input_helper.rs
Commit f24014a2ddcd135fb28a1b86167a53d86e878d0f made the insert function private. Let's solve this differently by creating a private WASM clipboard and invoking copy() and paste() on the Text item instead.
The first attempt was implementing a ClipboardProvider just for the wasm build, just like with SilentClipboard, but unfortunately that doesn't work because in the backend's set_clipboard_text()/clipboard_text() functions, there's no currently running winit event loop that we could access, becaused the call stack starts directly at the DOM event handler, not in our winit event handler.
=> Fix copy & paste in wasm builds

internal/backends/winit/winitwindowadapter.rs
Not sure why, but it fixes that applying the constraints is otherwise not working with winit on X11
This is not the first time we do this fix:
723f89d34221e9b243703f8f32d42b82d824b196 and 1891e4489a76ae37165f731aa19a69ec43371f0e
=> Call set_resizable before setting the constraints

internal/backends/winit/Cargo.toml, internal/backends/winit/accesskit.rs, internal/backends/winit/build.rs, internal/backends/winit/event_loop.rs
Port to the latest accesskit and accesskit_winit:
- Temporarily point to the PR that updates accesskit_winit to winit 0.29.
- NodeId is now a u64 instead of u128, so trim the component/item encoding.
- Adjust to some enum renamings.
- TreeUpdate now always requires a focus node, which we set to the root.
=> Re-enable accesskit

examples/gallery/ui/pages/easings_page.slint
Apply some polish to the label text and button sizes.
Before:
After:
=> Minor polish to the earrings page in the widgets gallery

docs/reference/conf.py, docs/reference/src/language/syntax/modules.md
Sadly, this makes it a bit more obvious that this feature is practically only available to Rust devs using build.rs
at the moment.
=> Provide some "bare-bones" documentation for component libraries

internal/compiler/widgets/fluent-base/combobox.slint
Currently it's always the second, but that's not great. Ideally it should be the current active element, but that's hard to compute
This becomes extra-relevent when our preview UI has a combobox on the top and that it is clipped to the window by winit
Fixes https://github.com/slint-ui/slint/issues/3345
=> Fluent combobox: always put the first item on top

internal/core/graphics/image.rs
To make sure there are no binary incompatibilities when features are missing
=> Assign value to ImageInnner enum

.github/workflows/nightly_snapshot.yaml
Make it possible to preview with the software renderer (using the lsp-args settings)
=> VScode extension: include the software renderer in our binary

internal/backends/winit/winitwindowadapter.rs
calling show() on a visible window or hide() on a hidden window shouldn't do anything.
Especially currently it would resize to the preferred size. So that makes the preview UI to alsways resize to the preferred size because we always call show()
=> winit: WindowAdapter::set_visible shouldn't do anything if it is already in that state

tools/lsp/common.rs, tools/lsp/preview.rs, tools/lsp/preview/native.rs, tools/lsp/preview/wasm.rs
If a preview command is issued while we were compiling, we need to recompile.
=> LSP preview: make sure that we always update the preview with the latest state

internal/backends/winit/event_loop.rs
If we set the control flow to Wait, winit will always wait even if we set the control flow later to some smaller timeout in the AboutToWait event.
Wait is the default anyway in winit 0.29 so this is not required
I'd say this is a bug in winit, but we can easily work it around
Fix #3875
=> Fix timer not firing on Windows

internal/core/item_rendering.rs
We used to called borrow_mut twice in a row, that can never work. I suspect we never reached this code path before, but the preview does because the ComponentContainer probably instentiate its contents in places that can cause the geometry cache to be empty while doing the rendering (while it is most likely being filled when computing the dirty regions
=> Fix BorrowMut error showing the preview with the software renderer

internal/backends/linuxkms/Cargo.toml, internal/renderers/skia/Cargo.toml
Activate the kms feature of softbuffer correctly, when building without default features.
=> Fix build with only backend-linuxkms

internal/backends/linuxkms/Cargo.toml, internal/backends/linuxkms/display/vulkandisplay.rs, internal/renderers/skia/Cargo.toml, internal/renderers/skia/vulkan_surface.rs
This might fix the issue with resizing causing swapchain re-creation errors, because "Swapchain creation no longer returns an error when the swapchain extent doesn't match the current surface extent."
cc #3850
=> Port to new vulkano

.github/workflows/ci.yaml, .github/workflows/cpp_package.yaml, .github/workflows/nightly_snapshot.yaml, .github/workflows/slint_tool_binary.yaml
... for all workflos that run macOS jobs.
Latest GH images somehow seem to have "lost" the minimum deployment
target (either setting or maybe the sysroot), so set it explicitly.
That is a good idea for us to do anymore for a more deterministic
deployment.
=> Select macOS 11 as deployment target in central place

api/node/package.json
Now if you run `npm run compile` also a `index.d.ts` file is created. It improves the support for deno. Without it the deno lsp has trouble with type from the slint package e.g. `slint.ImageData`. With the the generated `index.d.ts` it works fine with deno lsp.
=> Improve support for deno lsp

internal/compiler/widgets/fluent-base/scrollview.slint
* Instead of always reserve place for the scrollbars the scrollbars now are overlays the content
* The scrollbars are transparent and in not hovered state very small so I think that is ok for now
Fixes #3830
=> fluent: make scrollbars overlay

internal/compiler/passes/resolving.rs, internal/compiler/tests/syntax/basic/return.slint
Previously we were likely to get error in the compiled code anyway. (although the interpreter worked fine)
Fixes #3962
=> Throw an error when returning no value when one is expected.

.github/workflows/ci.yaml, api/node/.gitignore, api/node/__test__/api.spec.mts, api/node/__test__/compiler.spec.mts, api/node/__test__/eventloop.spec.mts, api/node/__test__/globals.spec.mts, api/node/__test__/js_value_conversion.spec.mts, api/node/__test__/types.spec.mts, api/node/__test__/window.spec.mts, api/node/index.ts, api/node/package.json, api/node/tsconfig.json, xtask/src/license_headers_check.rs
- Instead of building index.js with esbuild and generating types with tsc, use tsc to build index.js and index.d.ts.
- Use ts-node instead of swc for typescript based tests, as that works with es modules.
- Remove "syntax_check" target from package.json as that's now implied with "compile".
- Sadly this requires one "as any" cast as tsc somehow fails to determine the right type info for node-fetch.
Unfortunately index.js can't be an ES module without breaking
compatiblity. It would imply that the Node.js port can't be used with
require() anymore. So even thought that would simplify things further,
it's not part of this PR.
=> Clean up Node.js port build system

internal/compiler/widgets/cupertino-base/button.slint, internal/compiler/widgets/fluent-base/button.slint, internal/compiler/widgets/material-base/button.slint
Add `overflow: elide;` to button texts to prevent buttons from overflowing. Feel free to close this PR if such a behaviour should be implemented in a custom component.
=> Clip button texts

api/node/__test__/api.spec.mts, api/node/index.ts
I wanted to be able to write the `slint DSL` directly in the js file, luckily the `buildFromSource` api is provided, this PR will use `buildFromSource` and export to `loadSource`
=> node/api: export loadSource api

internal/backends/testing/lib.rs, internal/core/input.rs, internal/core/window.rs, tests/cases/elements/popupwindow_cursor.slint, tests/cases/elements/toucharea.slint, tests/cases/focus/focus_change.slint, tests/cases/issues/issue_2717_has-hover.slint
... for non-native PopupWindow.
We first need to handle the grabbed event regardless of popup window.
Then, if we are outside of the popup window, we should send exit events
so that, for example, the has-hover and mouse cursor get properly
updated.
Fixes https://github.com/slint-ui/slint/pull/3934
=> Properly send exit events when mouse is outside of a PopupWindow 

docs/reference/src/language/widgets/tabwidget.md
These were added by commit eec9d31809ab34b7f6f61526a62629f0bc4103cb but they are compiler internal properties that are not available to users, or just don't exist
Discussed in https://github.com/slint-ui/slint/discussions/3995
=> Docs: remove non-existing properties in TabWidget

api/node/__test__/tsconfig.json, api/node/package.json
The nodenext module resolution was only passed to ts-node, but vscode didn't see it. Use a dedicated tsconfig.json for vscode as well as ts-node.
=> Fix typescript errors shown in VS code when editing node test files

internal/compiler/passes/binding_analysis.rs, tests/cases/crashes/issue_4002_width_alias.slint
We need to visit them from there to mark them as used externally, otherwise the remove_alias passes might remove them.
Fixes #4002
=> Visit the geometry property as root from binding_analysis

editors/vscode/package.json, tools/lsp/common.rs, tools/lsp/language.rs, tools/lsp/main.rs, tools/lsp/preview.rs, tools/lsp/preview/native.rs, tools/lsp/preview/ui.rs, tools/lsp/preview/wasm.rs, tools/lsp/ui/main.slint, tools/lsp/wasm_main.rs
- rename the command line option to --no-toolbar
- Make it default to not hide the toolbar (so it is visible by default)
=> LSP: rename and fix the hide toolbar option

internal/compiler/passes/const_propagation.rs
Since we generate a lot of max(min, preferred) in the geometry code, this allow to simplify some expressions in the generated code
=> Const propagation of min and max

CHANGELOG.md, api/cpp/include/slint_string.h, api/cpp/tests/CMakeLists.txt, api/cpp/tests/datastructures.cpp
Don't dereference end() of a string_view.
The test included in this PR will hang in the CI (because a message box pops up), without the fix applied.
=> Fix SharedString::end() throwing an exception when MSVC iterator debugging is enabled

internal/compiler/widgets/fluent-base/scrollview.slint
Fixes #4013 
fluent scrollbar min-size is now 16px instead of 8px. It respects also the min-sizes of the ScrollView.
=> make fluent scrollbar bigger

api/cpp/include/slint_window.h, examples/cpp/platform_qt/main.cpp, internal/backends/android-activity/lib.rs, internal/backends/qt/qt_window.rs, internal/backends/winit/event_loop.rs, internal/backends/winit/wasm_input_helper.rs, internal/common/builtin_structs.rs, internal/core/api.rs, internal/core/platform.rs, internal/core/window.rs, tests/cases/text/key_repeat.slint
Now that winit was upgraded do 0.29 we can use its KeyEvent::repeat field.
Also feed Qt's QKeyEvent::isAutoRepeat() in the Qt backend.
Fixes #3065
=> Implement KeyEvent.repeat

Cargo.toml, internal/compiler/Cargo.toml, internal/compiler/passes/embed_glyphs.rs, internal/core/Cargo.toml, internal/core/software_renderer/fonts/systemfonts.rs
…ontSettings`
--> D:\.env\rust\.cargo\registry\src\index.crates.io-6f17d22bba15001f\i-slint-core-1.3.0\software_renderer\fonts\systemfonts.rs:29:29
|
29 | ...                   fontdue::FontSettings { collection_index: font_index, scale: 40. },
|                       ^^^^^^^^^^^^^^^^^^^^^ missing `load_substitutions`
=> fix bug: error[E0063]: missing field `load_substitutions`

internal/compiler/widgets/fluent-base/lineedit.slint
The `color` is the Rectangle's deprecated alias to background. I wonder why we don't get a warning though. It was meant to change the text-color
=> Fluent: fix disabled LineEdit

tools/lsp/preview.rs, tools/lsp/preview/native.rs
Move the code to close the popup in the function that is common with native and wasm 
Amend af34e4f18213dee73f9b5adb240bb180f6243bab
=> LSP: Also close the popup on wasm

internal/compiler/tests/typeloader/dependency_local.slint, internal/compiler/tests/typeloader/incpath/dependency_from_incpath.slint, internal/compiler/tests/typeloader/incpath/local_helper_type.slint, internal/compiler/typeloader.rs
For the slint! macro, we need to lookup files in the manifest path. The base_directory function regressed in commit 0ff8e2c. This was not cought by the test because it had falled back to the `pwd` with a warning, as we used to load ressources relative to `pwd` as a fallback.
So also check that there are no warning (meaning updating the rest of the test so that there isn't any warnings)
Fix #4045
=> Fix lookup relative to the manifest path in .rs file

internal/renderers/skia/Cargo.toml
This updates Skia to milestone 120. For more details see https://github.com/rust-skia/rust-skia/releases/tag/0.69.0
=> Update to skia-safe 0.69

internal/compiler/passes/remove_return.rs, tests/cases/expr/return2.slint
We were using the has_value of the previous expression of a sequence of expression, instead of using the last expression type to know if there is a value.
Fixes #4070
=> Rust&C++: Fix Return value of complex expression

internal/interpreter/dynamic_item_tree.rs, tests/cases/types/enums.slint
As seen in https://github.com/nununoisy/gb-presenter-rs/blob/v0.6.0/src/gui/slint/main.slint#L6
=> Interpreter: fix panic when a custom enum has the same name as a builtin one

internal/backends/linuxkms/calloop_backend.rs, internal/backends/linuxkms/calloop_backend/input.rs, internal/backends/linuxkms/fullscreenwindowadapter.rs
- Allow for the event loop to run before creating the window adapter
- Keep the loop running if requested
=> linuxkms: decouple event loop from window adapter

internal/compiler/generator/rust.rs, internal/interpreter/dynamic_item_tree.rs, tests/cases/layout/issue_2537_visible_in_listview.slint, tests/driver/rust/build.rs
This doesn't solve the issue #2537, but at least prevent the panic
Drive by change to fix compile when a struct is named `Box`
=> Fix panic in the interpreter when using `visible` in a ListView

CHANGELOG.md, internal/compiler/builtins.slint, internal/compiler/expression_tree.rs, internal/compiler/lookup.rs, internal/compiler/object_tree.rs, internal/compiler/tests/syntax/accessibility/accessible_properties.slint, internal/compiler/tests/syntax/basic/dialog.slint, internal/compiler/tests/syntax/basic/layout2.slint, internal/compiler/tests/syntax/elements/popup.slint, internal/compiler/tests/syntax/lookup/absolute-position.slint, internal/compiler/typeregister.rs, tools/lsp/language/completion.rs, tools/lsp/language/properties.rs
Some property need to be known at compile time. We already had checks that the binding is a compile time constant, but there was no check to prevent, say
self.row = 42;
which wouldn't work or could even cause panic or miscompilation of generated code
Closes #4037
=> Compiler: Error when assigning to compile time properties

CHANGELOG.md, api/cpp/include/slint-interpreter.h, api/cpp/tests/interpreter.cpp, internal/interpreter/ffi.rs
=> C++: Added `ComponentInstance::definition()` getter to retrieve the `ComponentDefinition` for an instance

api/node/index.ts
Commit 84fd6dc08cb71b13d5b8f26a2a83405177e5c8b6 changed the import from "rust-module" to "rust-module.cjs", which unfortunately broke typedoc's visibility into the types. Revert back to using the import without extension. With the given tsconfig files that works now and typedoc publishes the docs for the re-exported types again.
Fixes #4153
=> Fix missing types from Node.js API docs

internal/backends/qt/qt_window.rs
=> Qt backend: use `QObject::deleteLater()` when destroying popup `QWidget`

internal/compiler/llr/lower_to_item_tree.rs, tests/cases/issues/issue_4072_optimized_alias.slint
If we don't see that a native property is modified, it could get inlined and we wouldn't detect changes
Fix #4072
=> Fix wrongly optimized properties with aliases

internal/backends/winit/Cargo.toml
The new release defaults to using rwh 0.6, which implicitly also enables rhw_06 on winit.
=> Use raw-window-handle 0.6 for accesskit

api/cpp/esp-idf/slint/include/slint-esp.h, api/cpp/esp-idf/slint/src/slint-esp.cpp, api/cpp/include/slint-platform.h, api/cpp/platform.rs, internal/core/software_renderer.rs, tests/screenshots/testing.rs
Same term as we're going to use in the linuxkms backend.
=> Rename WindowRotation to RenderingRotation in the software renderer

internal/core/api.rs
Also use `#[track_caller]` as the source location should point to the user's source code as this is where the bug is
=> api: give proper panic message to a function that can panic from bad use

examples/mcu-board-support/README.md, examples/mcu-board-support/esp32_s2_kaluga_1/cargo-config.toml, examples/mcu-board-support/esp32_s3_box/cargo-config.toml
- The `espflash` flashing command was updated after v2.0, you now need to do `espflash flash`
- Use the custom runner instead of using `espflash` on the resulting binary.
=> Use custom runner to flash and update espflash command

internal/core/items/text.rs
So that we don't erase selection or call edited unless there is something typed.
Workaround a bug in which plasma/wayland sends many empty ime event:
```
WindowEvent { window_id: WindowId(WindowId(94309690701616)), event: Ime(Preedit("", None)) }
```
Fixes #4184
=> TextInput: Don't call insert for empty compositing event

internal/backends/linuxkms/calloop_backend.rs, internal/backends/linuxkms/display.rs, internal/backends/linuxkms/display/egldisplay.rs, internal/backends/linuxkms/fullscreenwindowadapter.rs, internal/backends/linuxkms/lib.rs, internal/backends/linuxkms/renderer/femtovg.rs, internal/backends/linuxkms/renderer/skia.rs
When an animation is running, we would
a) block while waiting back buffer we rendered into to become the visible front buffer
b) always schedule a 16 ms time to render again, regardless of whether any other time would expire sooner.
Apart from not expiring timers correctly and costing time, it would also mean that any input events that arrive during the blocking wait would not get processed, which sometimes raises a lib input warning.
The patches in this series address this by using a more modern mechanism:
1. After posting a back buffer for display, return straight to the event loop.
2. The DRM FD is added to the poll/select call, so if we get activity on it, we'll process the page flip events and re-render if needed (animation is running).
3. Meanwhile, any lib input events will still …
=> linuxkms: Improve animation and input handling performance

internal/compiler/parser/expressions.rs, internal/compiler/tests/syntax/expressions/percent2.slint
Was reported several times:
- https://github.com/slint-ui/slint/discussions/4190
- https://github.com/slint-ui/slint/issues/3980
=> Parser: Hint for the mod function when parsing `%`

api/cpp/cbindgen.rs, api/rs/build/lib.rs, internal/compiler/build.rs, tools/compiler/main.rs, tools/fmt/main.rs, tools/updater/main.rs, tools/viewer/main.rs, xtask/src/slintdocs.rs
This PR improves performance by buffering all uses of `std::fs::File` outside tests. Note that files are not buffered by default in Rust.
=> Wrap all non-test uses of  in a BufWriter/BufReader for efficiency

tools/lsp/ui/resizer.slint
If resizing makes the value of is-resizable dirty, we would hit issue #3953 and the handle would be re-created and the drag operation aborted
=> LSP preview: workaround the resize handler not working

internal/compiler/widgets/cupertino-base/switch.slint, internal/compiler/widgets/fluent-base/switch.slint
Take the minimum height of the layout into account, like in the material style implementation.
Fixes #4201
=> Fix Switch element in Cupertino & Fluent style not showing text when font size is large

tools/lsp/preview.rs, tools/lsp/preview/native.rs, tools/lsp/preview/wasm.rs, tools/lsp/ui/main.slint
- make sure that the initial size is proper by calling show() on the preview ui after the factory has been set
- ensure that there is no recursion if the inner layout info depends on the size (Fixes #3989)
- Ensure that the geometry constraints are respected when previewing a component that was already resized
=> LSP preview: fix some issue related to geometry

internal/compiler/passes/embed_glyphs.rs
Add some symbol/emoji fonts for Windows, next to the existing options for macOS and Linux.
=> Fix missing font fallback handling on Windows when pre-rendering glyphs for the software renderer

CHANGELOG.md, internal/backends/winit/event_loop.rs
Upon pressing, event.text is set and all is well. But when the space bar is released, event.text is always empty and we would not dispatch an event.
=> winit: Fix `FocusScope`'s `key-released` not being invoked when releasing the space bar key

.github/workflows/cpp_package.yaml
It's not enabled by default due to complicated build setup but on GitHub Actions it works.
=> Enable Skia renderer for C++ package

internal/backends/winit/event_loop.rs, internal/backends/winit/winitwindowadapter.rs
Calling request_request() during RedrawRequested would not work on Windows and wasm. Commit 372e6b0ffcf847cee6a03f7aab461310ea842154 worked around this, but that can be reverted now, as this is fixed in winit. For windows that was https://github.com/rust-windowing/winit/pull/3165 and for wasm I couldn't find the change, but could verify that it still works.
I checked that #1574 does not regress.
Besides the cleanup, this is also needed for #1695.
=> winit: Remove hack that makes request_redraw() during draw() work

editors/vscode/src/wasm_preview.ts, tools/slintpad/src/preview_widget.ts
Right now, the winit window adaptor will force a px value on the width and height once the ui is up.
We should then override that again with 100% after the UI is shown
=> Slintpad: resize the cansvas after showing the UI

internal/backends/winit/Cargo.toml
This brings lazy initialization of the accesskit adapter on Linux/dbus.
cc #3867
=> Bump AccessKit dependencies

api/cpp/platform.rs, internal/backends/android-activity/lib.rs, internal/backends/winit/renderer/skia.rs, internal/renderers/skia/d3d_surface.rs, internal/renderers/skia/lib.rs, internal/renderers/skia/metal_surface.rs, internal/renderers/skia/opengl_surface.rs, internal/renderers/skia/software_surface.rs, internal/renderers/skia/vulkan_surface.rs
Move this back out of render() again and make it stateful in the renderer. Reduces the amount of book-keeping required and it's always the same callback anyway.
=> Skia: Clean up pre present notify callback API

.github/workflows/ci.yaml
xtansa rust 1.75 toolchain uses ubuntu 22.4, but the docker umage has ubuntu 20.4 Hopefully updating the docker image should fix the problem
=> CI: prospective fix for esp-idf libc version invompatibility

CHANGELOG.md, internal/backends/qt/qt_window.rs, internal/core/window.rs, tests/cases/elements/popupwindow_close.slint, tests/cases/elements/popupwindow_context.slint
Close a PopupWindow on press when the mouse is not on the popup. Close it on release if it's in the popup and it wasn't created on press.
These fixes make it possible to implement basic custom context menus with the mouse.
=> Fix PopupWindow close behavior

internal/core/items/text.rs
I've tried to make sure the behavior match the one of native Window (and Qt on Linux) apps, and android apps.
Windows set the focus on press, but android set the focus on release. Also, the paste selection on middle click happens on release on Linux.
On android, when taping a text edit that currently has the focus, we should show the virtual keyboard again if it was hidden by the user.
Having platform specific behavior like this in i-slint-core is not optimal, but on the other hand, I'm not sure this deserve a new function in the Platform trait
=> TextInput: fix focus and virtual keyboard behavior on press/release

Cargo.toml, docs/building.md, tools/figma_import/Cargo.toml
- Added figma_import bin
- Added readme to help newcomers
With the last update to the workspace version control the figma_import broke the building process. I've added building binaries and instructions to build the entire workspace if anyone wants to. I hope that this will help the community and make slint more user friendly to newcomers like me :)
=> Build workspace build on windows

.github/actions/codesign/action.yaml, .github/workflows/nightly_snapshot.yaml, .github/workflows/slint_tool_binary.yaml
This signs the slint-lsp/slint-viewer binaries as well as the lipo'ed binary for the VS code extension.
cc #4240
=> Add code signing for macOS tool binaries

api/cpp/include/slint-platform.h, api/cpp/platform.rs, internal/backends/qt/qt_window.rs, internal/backends/winit/winitwindowadapter.rs, internal/core/api.rs, internal/core/window.rs
Move the set_fullscreen function added to the WindowAdapter trait in 779aff0b3904db1e882f5f7f5ab3db2e38e2d8e6 to be a function in WindowProperties instead.
That way it'll be easier in the future to extend this with other window states without having to modify or break the WindowAdapter trait API.
=> Reduce WindowAdapter API slightly

internal/backends/linuxkms/calloop_backend.rs, internal/backends/linuxkms/fullscreenwindowadapter.rs
This is now handled in i-slint-core.
Amends 9ff13faee81a4b2165e8a5e49d808b317d3ba63b
=> LinuxKMS: Remove set_event_loop_quit_on_last_window_closed implementation

internal/compiler/passes/inlining.rs, tests/cases/callbacks/init.slint
When a component declares an init callback as well as the element that instantiates it, the init callback of the container would not get invoked if the container was inlined:
```
component InlinedContainer {
init => { ... } // not invoked
@children // force inlining
}
component UseSite {
InlinedContainer {
init => { ... }
}
}
```
That's because the inlining happens very early, before the init callbacks are collected into the init code. And during inlining that would be treated like a property binding and the "binding" at the element site overrides the one at the component site.
One natural approach would be to move the init code collection to an earlier place before inlining, but that isn't possible because the boundaries of the compiler components (Rc<Component>) aren't set up yet …
=> Fix missing invocation of init callbacks due to inlining

.github/workflows/publish_npm_package.yaml, api/node/binaries.json
These are built with the default features of the interpreter crate, as unfortunately napi-rs doesn't allow us to select features on the command line yet. The next version (3.0) will add that, then we can keep the binaries in sync.
So meanwhile, these are basically winit/femtovg/software enabled binaries.
cc #1991
=> Node.js: Add binaries for macOS and Windows

internal/compiler/widgets/common/combobox-base.slint
* I have also change the flag `has-focus` so the focus state is no longer displayed on a disabled `ComboBox`
=> Reject events on disabled ComboBox

internal/backends/winit/Cargo.toml, internal/backends/winit/accesskit.rs, internal/backends/winit/event_loop.rs
Commit 41bfe66447e91a0e5cdd329758c13841848f84bb bumped accesskit dependencies, which introduced a version that uses threads.
That means the action handler as well as the initial tree update source closure are destroyed in a thread that's not the ui thread. That means we destruct a SenderWrapper<Weak<WinitWindowAdapter>> in a thread that is not the same as the one the wrapper was created in, which causes Drop for SendWrapper to panic.
Replace the use of SendWrapper here with safely copyable window ids.
=> Fix panic when shutting down process on Linux

examples/opengl_texture/scene.slint
Provide a reasonable minimum size for the image.
Fixes #4195
=> Don't crash the opengl_texture example when making the window very small

CHANGELOG.md, api/cpp/include/slint.h, api/cpp/tests/models.cpp
This was requested by a customer recently and it seems rather straight-forward to implement and offer. `clear()` mirrors `std::vector::clear()` and `set_vector` mirrors the `set_vec` we have in Rust.
=> C++: Add convenience functions to clear and replace the VectorModel's vector

internal/renderers/skia/Cargo.toml, internal/renderers/skia/d3d_surface.rs
See https://github.com/rust-skia/rust-skia/releases/tag/0.70.0 for a list of changes.
The main change for us is that the D3D API was ported to the modern windows rust crate.
=> Update Skia Rust Bindings

tools/lsp/language/completion.rs
According to the wording in which it is defined
Fixes https://github.com/slint-ui/slint/issues/3935
=> LSP: preserve dashes vs underscore in auto-completion

internal/backends/winit/event_loop.rs, internal/backends/winit/winitwindowadapter.rs
Otherwise there will be a huge queue of request redraw command that accumulate within winit.
This makes operation such as resizing a bit more soomth
Tested on X11
=> winit: avoid to poll or call request_redraw too often

internal/interpreter/dynamic_item_tree.rs, internal/interpreter/eval.rs, internal/interpreter/eval_layout.rs, tests/cases/models/delete_from_clicked.slint
We were having a reference to the parent item tree, assuming the parent
was living longer than the item tree. But this is not the case if
there existed a ItemRc to one item in the inner part.
So use a Weak for the parent instead.
The test is unrelated. I thought it would reproduce the bug but it doesn't
(although the FIXME line in the test probably does)
I was investigating #4300 when noticing this
=> Fix unsound behavior of the interpreter when accessing a deleted parent

internal/compiler/widgets/material-base/scrollview.slint
Other style are more desktop oriented, but this is important on android to pan with the finger
=> Material style: make the ScrollView pan with the finger

docs/reference/src/language/builtins/elements.md
Mention that clicked is limited to the left mouse button, or any finger of course.
Fixes #4213
=> Clarify `TouchArea` docs with regards to clicking and touching

internal/common/Cargo.toml, internal/common/sharedfontdb.rs, internal/core/graphics/image/svg.rs, internal/renderers/femtovg/fonts.rs
It would incoditionally try to load the FONTDB that can't load any font from the system using libloading
Instead, hardcode the path to the font to a known android font
=> Fix svg loading on android after update of resvg

internal/core/platform.rs
As soon as we have a backend, we might as well initialize the timer tick. This fixes animations not starting when run from user init callbacks.
Fixes #2809
=> Fix initial animation tick before the event loop runs

internal/core/items/text.rs, tests/cases/elements/component_container_init.slint
As a side effect this fixes the infinite recursion from #4390 because there is a prevention that focus being sent to the element inside a ComponentContainer (the bug is that this cause the size to be computed which cause recursion)
=> TextInput: Only send the IME if we have the focus

docs/reference/src/advanced/backend_winit.md, internal/backends/winit/lib.rs, internal/backends/winit/renderer/skia.rs, internal/renderers/skia/Cargo.toml, internal/renderers/skia/lib.rs
The Skia OpenGL renderer is portable and sometimes esp. on Windows produces better results, so make it always available as an open if `renderer-skia` is enabled. `renderer-skia-opengl` continues to select the GL renderer as default.
=> winit: Always make `skia-opengl` available

internal/compiler/parser/statements.rs, tests/cases/conditional/stm2.slint, tools/fmt/fmt.rs
resolve #4062 
Not complete, this will break formatter.
It seems like formatter can't identify if without parentheses.
=> Make the parentheses optional in if else statement

internal/compiler/object_tree.rs, internal/compiler/passes/binding_analysis.rs, internal/compiler/passes/clip.rs, internal/compiler/passes/embed_glyphs.rs, internal/compiler/passes/inlining.rs, internal/compiler/passes/optimize_useless_rectangles.rs, internal/interpreter/highlight.rs, tools/lsp/language.rs, tools/lsp/language/goto.rs, tools/lsp/language/properties.rs, tools/lsp/preview/element_selection.rs, tools/lsp/util.rs, tools/updater/main.rs
This allow the preview highlight to work even if the elements have been optimized
the selection doesn't use this information yet though
=> Compiler: Keep all nodes for a given element, even when elements get merged

.github/workflows/ci.yaml
Pin to the previous release, instead of always using the latest.
=> CI: work around tree sitter tests failing with 0.20.9

internal/backends/linuxkms/display.rs, internal/backends/linuxkms/lib.rs
Remove a lot of error in rust-analyzer when opening the slint workspace
=> Fix linuxkms compilation and warnings when no features are enabled

internal/core/items/text.rs, internal/core/window.rs
Otherwise, programatic changes to the text are not told to the input methods.
This is important in the case of the todo example on android. For example if one type
`foo<enter>bar`, the enter will cause foo to be added in the list, and the text will be cleared. But then when typing bar, the input method things "foo" is still in the text and "foo" will be re-added
=> Input method: re-send the text if we notice that the text has changed when rendering

tools/lsp/language.rs, tools/lsp/language/properties.rs
- Make sure that the element id is part of the element range. So that when selecting element in the preview, the right item in the outline is selected
- fixup the selection_range for enum and struct
=> Small tweak to the document outline

internal/compiler/passes/inlining.rs
This avoids inlining Button elements from our widget set.
This is covered by tests/cases/properties/animation_merging.slint
=> Don't require inlining if an animated property is private and local

api/node/cover.md
- We could import from `npm:...` directly, but by using an import map, the import is centrally controlled and all subsequent snippets for Node.js can also be used with Deno
- Use .mjs for the node snippet as we use ES module syntax
Unfortunately our own examples can't be equipped with a deno.json yet as deno does not support yet imports of node modules from a local path.
=> Add deno to the Slint-node cover docs

internal/compiler/passes/focus_handling.rs, internal/compiler/tests/syntax/focus/focus_invalid.slint
Since commit 6fefe75a1c18b79869485961a0690f8844844fe5 the handling of forward-focus bindings happens before the resolve_expressions pass, which means that we cannot rely on type mismatch
error handling yet.
Fixes #4475
=> Fix panic when using foward-focus with non-element binding

examples/iot-dashboard/iot-dashboard.slint
Provide a minimum height for the boxes, so that the graphs are always visible. The graphs are painted on top of the boxes, but the boxes define the geometry.
=> Fix squashed usage graphs in iot dashboard when previewing

tools/lsp/preview/element_selection.rs
Since the added Window no longer have a node, the current code that checks that it has one doesn't work.
Instead, to skip the added window, just take the first element if the root don't have a node
=> Fix preview::element_selection::root_element

api/cpp/include/slint.h, api/cpp/tests/models.cpp
The previous signature would not allow that, but we should allow it for consistency with the constructor.
=> C++: Permit passing a value to VectorModel::set_vector by value

internal/core/software_renderer.rs
we shall never have a geometry that is bigger than the image we want to render
=> Fix panic in the software renderer when rendring Qt widget

examples/carousel/esp-idf/s2-kaluga-kit/main/idf_component.yml, examples/carousel/esp-idf/s3-box/main/idf_component.yml, examples/carousel/esp-idf/s3-usb-otg/main/idf_component.yml, examples/printerdemo_mcu/esp-idf/main/idf_component.yml
esp-box fails to build with 1.5.0/lvgl9. Even thought 1.5 was marked as
yanked, it still shows up. So temporarily pin the examples to 1.4.0.
=> Work around build issues with espressif_lvgl_port >= 1.5.0

tools/lsp/ui/draw-area.slint
The hack to sets the preview area's width and height through the init callback was run _after_ rendering the component container and during evaluation of the dirty tracker. The latter sets itself to dirty = false after evaluation, so it's never dirty despite the width and height having changed.
As a workaround for 1.4.1, move the init callback hack to before render() is called.
=> Fix initial rendering of the live-preview

internal/backends/android-activity/java/SlintAndroidJavaHelper.java, internal/backends/android-activity/javahelper.rs, internal/core/items/text.rs
Also avoid flickering of the input method when inserting text by preventing sending an imput method event right after deleting the selection
=> Android: send the input type to the input method

.github/actions/install-nodejs/action.yaml, .github/actions/test-online-editor/action.yaml, .github/workflows/build_docs.yaml, .github/workflows/ci.yaml, .github/workflows/cpp_package.yaml, .github/workflows/crater.yaml, .github/workflows/embedded_build.yaml, .github/workflows/nightly_snapshot.yaml, .github/workflows/publish_npm_package.yaml, .github/workflows/slint_tool_binary.yaml, .github/workflows/spellcheck.yaml, .github/workflows/torizon_demos.yaml, .github/workflows/translations.yaml, .github/workflows/upgrade_version.yaml, .github/workflows/upload_esp_idf_component.yaml, .github/workflows/wasm_demos.yaml, .github/workflows/wasm_editor_and_interpreter.yaml, .github/workflows/yocto_build.yaml
Looked at warning of actions that still uses old node version and update the onces that had a new release
=> CI: update github action dependencies

internal/backends/android-activity/build.rs
- Use Path/OsStr to avoid directory separator mismatches
- Call d8.bat
Fixes #4524
=> Fix Android build on Windows

tools/lsp/language/completion.rs
If the sortText isn't there, then label is used to do the sorting [1] which results in a poor auto-complete experience.
This patch sets sortText of the completion item in a way such that the sort order is maintained on the client side.
[1]: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItem
=> lsp: set sortText for CompletionItems

internal/compiler/generator/rust.rs
Rust 1.77 added a warning when tuple values are not used.
=> Fix warning in Rust 1.77 with unused exported globals

.github/workflows/cpp_package.yaml, .github/workflows/nightly_snapshot.yaml
upload-artifact v4 requires a unique artifact name, instead of "merging": https://github.com/actions/upload-artifact?tab=readme-ov-file#v4---whats-new
So assign os version independent suffixes and use those in the release step.
=> Prospective fix for C++ package creation

tools/viewer/README.md, tools/viewer/main.rs
The previous help was not useful to document that -L should contain an = 
This is how it looks now:
=> slint-viewer: fix the docs for the `-L` option

api/rs/slint/lib.rs, internal/interpreter/api.rs
Re-export them just like in the slint crate.
=> Permit the use of Image, Brush, and related data types in slint_interpreter from Rust without depending on i_slint_core

internal/backends/linuxkms/display.rs, internal/core/software_renderer.rs, tests/screenshots/testing.rs
As discussed a few days ago, let's define rotation to be always clockwise, as it is done in other graphics frameworks as well as our own image rotation. This means changing the definition for the software renderer. Also fixed docs for the enum in the linuxkms backend that was wrong.
=> Align rotation between software renderer and LinuxKMS backend

.github/workflows/ci.yaml, api/cpp/CMakeLists.txt, api/cpp/Cargo.toml, api/rs/slint/Cargo.toml, internal/backends/qt/Cargo.toml, internal/backends/qt/build.rs, internal/backends/selector/Cargo.toml, internal/interpreter/Cargo.toml, tools/lsp/Cargo.toml, tools/viewer/Cargo.toml
The trick is that the backend selector build by default with the i-slint-backend-qt, but the "enable" feature is only enabled if the qt-backend feature is enabled explicitly, or on linux from the slint or slint-interpreter crate
=> Only enable the Qt backend by default on Linux

api/node/src/interpreter/component_instance.rs, api/node/src/interpreter/value.rs, api/node/src/types/model.rs
There's no need to consume the Type in the value conversion.
=> Node.js: Avoid unnecessary cloning of Type

tools/lsp/fmt/fmt.rs
- states with multiple state element are now formatted properly
- arrays with trailing commas no longer result in error
- large arrays (len=80) and arrays with trailing comma are formatted with new line
- `for` with index no longer errors out and is formatted properly
- property animations are now supported
- object literals are now supported. big literals (len=80) and literals with trailing comma are broken into multiple lines
With these patches I can run `slint-lsp format` on slint files in examples and the result seems to be acceptable.
Closes #3900
=> formatting fixes and improvements

tools/lsp/fmt/fmt.rs
- property animation with 1 binding is now kept on a single line
- empty lines are preserved
- property animation with multiple properties is formatted
- handle empty arrays
- fix length calculation of arrays/obj-literals to figure out if its large
After these changes, the fmt can run on all files in `examples` directory without errors.
=> fmt follow up fixes

.github/workflows/cpp_package.yaml
Commit 4b4a7d6ff2d1927ca53bd5be7fdf4f5bf15a8e63 attempted to remove the Qt from the C++ package on Windows, but infortunately, it removed the setup of Qt on Linux instead of Windows.
As a result, 1.4.x binary packages on Linux are not build with Qt, and on Windows are build with Qt but no longer ship Qt so are broken
In the master branch we no longer use Qt by default already on Windows even if it is installed.
But this patch restore the fact that the binary package are built with Qt on Linux
=> C++ package: use Qt on Linux, not on Windows/Mac

api/rs/slint/Cargo.toml, api/rs/slint/android.rs, api/rs/slint/lib.rs, examples/printerdemo/rust/Cargo.toml, examples/printerdemo/rust/main.rs, examples/todo/rust/Cargo.toml, examples/todo/rust/main.rs
Add a `backend-android-native-acticity` feature that enables the `slint::android_*` re-exports.
This doesn't  expose the game-activity feature because it is harder to use and is not well tested, and I don't think bring much value at this point.
Edit: feature renamed to `backend-android-activity-05` and added `android` module
=> Android: make `slint::android` public

.github/workflows/ci.yaml, helper_crates/vtable/macro/macro.rs, helper_crates/vtable/src/vrc.rs
We can't create references for things that aren't represented by the reference. Even if we never dereference that reference.
Also add a miri test in the CI that runs the test on crate which are error free.
=> vtable: fix UB detected as miri errors

api/cpp/include/slint-platform.h, api/cpp/platform.rs, api/node/index.ts, api/node/src/interpreter/window.rs, internal/backends/android-activity/androidwindowadapter.rs, internal/backends/qt/qt_window.rs, internal/backends/winit/event_loop.rs, internal/backends/winit/winitwindowadapter.rs, internal/core/api.rs, internal/core/window.rs
Update the `Window` api to support programmatically minimizing and maximizing windows on the `Qt` and `winit` backends. The following methods are new:
- `Window::set_minimized`
- `Window::minimized`
- `Window::set_maximized`
- `Window::maximized`
- `Window::fullscreen`
=> Add API for minimize/maximize on Window component

api/cpp/include/slint-interpreter.h, api/cpp/tests/interpreter.cpp, internal/interpreter/ffi.rs
This maps straight to the Rust API.
=> C++ Interpreter: Add support for setting the translation domain

.github/workflows/ci.yaml, .github/workflows/nightly_tree_sitter.yaml, .github/workflows/tree_sitter.yaml
- For the main CI, pin a tree sitter version that's know to work.
- Additionally, schedule a nightly run against the latest version of tree sitter, so that we can find issues before the next release.
=> Restructure tree sitter tests

api/python/errors.rs, api/python/image.rs, api/python/lib.rs, api/python/slint/__init__.py, api/python/tests/test_instance.py, api/python/value.rs
This exposes a slint.Image class, which has a load_from_path class method as well as size/width/height properties.
cc #4202
=> Add support for mapping image properties

api/rs/macros/lib.rs, tests/cases/widgets/spinbox_basic.slint, tests/driver/cpp/build.rs, tests/driver/driverlib/lib.rs, tests/driver/interpreter/build.rs, tests/driver/interpreter/main.rs, tests/driver/nodejs/build.rs, tests/driver/rust/build.rs, tests/screenshots/build.rs
Tests under tests/cases/for_each_style are run with all styles at least in the Rust driver.
Amends 6bb9905191e3ac1e63839ce434be55c1c3940e63 to include a test that using edited works.
=> Add support for writing tests that run with all styles

internal/compiler/object_tree.rs, internal/compiler/passes/resolving.rs, internal/compiler/tests/syntax/lookup/for_lookup.slint
The problem is that we were taking the whole `repeated` field and as a result we wouldn't see that the element was being repeated and that we shouldn't have to lookup id within it
Fix #4683
=> Compiler: fix lookup of the model not seeing that the element is being repeated

docs/reference/src/language/builtins/elements.md, internal/compiler/builtins.slint, internal/core/items/flickable.rs, tests/cases/elements/flickable.slint
Hello,
as requested in #1462, I've added a `scrolled`-Callback that gets triggered when the `viewport_x`- or `viewport_y` -Properties are changed by a mouse drag or mouse wheel movement.
I was only able to test this change on the Rust API (by adding a debug statement to one of the examples), because my current Nix build setup isn't setup for C++, Python or NodeJs.
Thanks,
pfzetto
=> Added `flicked`-Callback on `Flickable`

Cargo.toml, api/rs/slint/Cargo.toml, api/wasm-interpreter/Cargo.toml, helper_crates/vtable/CHANGELOG.md, helper_crates/vtable/Cargo.toml, helper_crates/vtable/macro/Cargo.toml, helper_crates/vtable/src/vrc.rs, internal/backends/qt/Cargo.toml, internal/backends/testing/Cargo.toml, internal/backends/winit/Cargo.toml, internal/core/Cargo.toml, internal/interpreter/Cargo.toml, internal/renderers/femtovg/Cargo.toml, internal/renderers/skia/Cargo.toml, tools/viewer/Cargo.toml
Dyn is currently Send+Sync, so `VRc<WhateverVTable, Dyn>` is also Send+Sync. So we shouldn't really allow conversion between `VRc<WhateverVTable, SomeThingNotSend>` to `VRc<_, Dyn>` that can be sent between threads
This is a breaking change of the vtable crate, but also a soundness fix
=> vtable: Fix soundess issue of VRc::into_dyn for `!Send` types

CHANGELOG.md, api/node/__test__/js_value_conversion.spec.mts, api/node/cover.md, api/node/index.ts, api/node/src/interpreter/value.rs, api/node/src/types/model.rs, tests/cases/crashes/layout_deleted_item.slint, tests/cases/models/write_to_model.slint, tests/cases/models/write_to_model_sub_component.slint, tests/cases/types/array.slint
This series changes two aspects:
Internally, the model mapping is changed so that every time a ModelRc is needed in Rust, we obtain a clone of a shared `Rc<ModelNotify>` and create a `slint::Model` impl around it.
Externally, Model<T> now supports the Iterable protocol, so that one can use for example `Array.from` to turn a model into an array, or use the model in a `for` loop. Additionally, the getter for a model property now _always_ returns an object that provides the same API as `Model<T>`.
These changes are done in preparation for refactoring `MapModel`, so that it can correctly react to changes in the source model (in the future).
=> Cleanups and fixes to the Node.js model mappings

internal/renderers/femtovg/itemrenderer.rs, internal/renderers/skia/cached_image.rs, internal/renderers/skia/itemrenderer.rs
We will render them with the final size in the buffer, so account for that difference when rendering
=> Femtovg&Skia: fix drawing of tiled svg image

api/node/src/types/model.rs
The wrapper returned should behave like Model<T>, which now also a @@iterator key. That key is generated by simulation the evaluation of `Symbol.iterator`, by first looking up `Symbol` in the global object, and then `iterator`. When retrieving `Symbol` we casted it to a `JsObject`, but commit
https://github.com/napi-rs/napi-rs/commit/aeb0b4766d9554519eb4002e02910ebb2b4a0b36 upstream tightened the cast by adding an extract check, which fails. Symbol is not a plain object, it's in fact a function (by use of `Symbol()`).
=> Node.js: Fix exception thrown when converting a Rust model into a Js Model

helper_crates/const-field-offset/macro/macro.rs, helper_crates/const-field-offset/src/lib.rs, internal/compiler/generator/rust.rs, internal/compiler/parser-test-macro/lib.rs, internal/core/item_tree.rs, internal/core/properties/properties_animations.rs, tools/lsp/fmt/fmt.rs, tools/lsp/language/formatting.rs
Fixes #4706
This at least fix it in generated code by us. There are still warning in the code generated by the `scoped_tls_hkt::scoped_thread_local` that we use, but it should be fixed there.
=> Fix the `non_local_definitions` warnings with rust nightly

editors/vscode/slint.tmLanguage.json
The `storage.type`  is for the type keyword such as `class` or `function` or `var`, not for our own types. These are `entity.name.type`
Similarily, `variable.langguage` is for the variable keyword like `this` or `self`
Reference: https://macromates.com/manual/en/language_grammars#naming_conventions
Also the "property"  scope was putting all identifiers in the binding as a variable, which is just highlighting the whole binding
=> tmlanguage: don't make everything a keyword

internal/backends/linuxkms/Cargo.toml, internal/backends/linuxkms/display/gbmdisplay.rs
gbm.rs' lock_front_buffer calls has_free_buffers before calling the underling C lock_front_buffer function on the gbm surface. This has_free_buffers() check succeeds the first time but always fails after that.
However apart from this check, everything else appears to be working perfectly fine. Projects like weston, ksmcube, Qt, or mutter don't do this check beforehand either, so this patch works around gbm.rs by skipping this.
Unfortunately this requires going to gbm-sys directly and implementing the drm traits that require calling the various gbm_bo_get_* functions to retrieve the buffer details for posting to DRM.
=> Work around gbm display not working on Vivante gbm drivers

docker/Dockerfile.aarch64-unknown-linux-gnu, docker/Dockerfile.armv7-unknown-linux-gnueabihf, docker/Dockerfile.riscv64gc-unknown-linux-gnu
Since skia-bindings-0.71.0, bindings.cpp includes SkFontMgr_fontconfig.h, which in turn includes fontconfig/fontconfig.h.
In cross docker containers, the fontconfig headers are installed in /usr/include - there's no sysroot.
For the actual build of bindings.cpp, this is fine - gcc will search in /usr/include and find it.
For the bindgen phase, certain clang versions do not look in -I/usr/include by default when a --target is present - generally a sensible approach probably. However in this very setup, it's okay, so teach bindgen about it by setting BINDGEN_EXTRA_CLANG_ARGS_target. Typically that's used to pass for example `--sysroot=`, but we're using it to explicitly add /usr/include.
=> Fix cross build of rust-skia in cross docker containers

internal/renderers/skia/textlayout.rs
Set a default font manager to avoid that the unconditional dereferencing inside Skia crashes on a null pointer.
Upstream PR: https://github.com/google/skia/pull/162
Fixes #4696
=> Work around crash on macOS when rendering certain emojis

api/rs/slint/type-mappings.md
Fixed foo type for Slint's struct appropriately. Also removed a couple of spaces for better styling.
=> Small doc fix for rust type mappings

CHANGELOG.md, internal/compiler/widgets/cupertino-base/styling.slint, internal/compiler/widgets/cupertino-base/tabwidget.slint
There are two variants of the macOS TabView. But the one that was implemented for the cupertino style is only partial used. Now the TabWidget of the cupertino style is displayed in the variant that is more common used on macOS e.g. on the settings.
=> Cupertino TabWidget: Tweaked visual appearance

api/python/interpreter.rs, api/python/tests/test_gc.py
Make the references to the callbacks visible to the GC to be able to break cycles.
=> Python: Fix GC support for callbacks

api/python/lib.rs, api/python/models.rs, api/python/slint/__init__.py, api/python/slint/models.py, api/python/tests/test_models.py, api/python/value.rs
This provides a Model base class in Python and sub-classes of that can be set as data models in slint.
The ListModel is provided as basic sub-class operating on a list() and allowing mutation and notifying the view on the Slint side.
Similarly, an array declared in Slint is exposed as an object to Python that looks like a Model.
Both support the sequence protocol.
Fixes #4135
=> Python: Initial support for implementing models in Python

editors/vscode/src/wasm_preview.ts
It asserts that the "experimental" argument to create is not set
=> vscode extension: Fix wasm preview in debug

examples/printerdemo/rust/Cargo.toml, examples/printerdemo/rust/main.rs, examples/todo/rust/Cargo.toml, examples/todo/rust/main.rs
```
warning: output filename collision.
The bin target `printerdemo` in package `printerdemo v1.5.0 (C:\dev\slint\examples\printerdemo\rust)` has the same output filename as the lib target `printerdemo` in package `printerdemo v1.5.0 (C:\dev\slint\examples\printerdemo\rust)`.
Colliding filename is: C:\dev\slint\target\debug\deps\printerdemo.pdb
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
```
=> Demos: fix duplicate artifact name in Windows

api/python/slint/__init__.py, api/python/tests/test_instance.py, api/python/tests/test_load_file.py, api/python/tests/test_load_file.slint
Map properties and callbacks to attributes with getters and setters.
cc #4134
=> Python: Create a property type wrapper for component instances

examples/printerdemo/cpp/main.cpp, examples/printerdemo/cpp_interpreted/main.cpp, examples/printerdemo/rust/lib.rs, examples/printerdemo/ui/printer_queue.slint
This reverts commit 060f63ad561e04aab8aeb11668266f0f3d94a0f9, as it broke the C++ interpreted demo and makes it impossible to implement the demo "fully" in JavaScript and Python.
cc #4777
=> Revert the use of enums in the printer demo

api/python/slint/__init__.py
Make sure to capture the global/callback/property name correctly in the closures.
=> Python: Fix setters getters for properties/callacks

api/cpp/cmake/SlintMacro.cmake, api/cpp/docs/cmake_reference.md, examples/todo/cpp/CMakeLists.txt, examples/todo/cpp/main.cpp, internal/compiler/generator.rs, internal/compiler/generator/cpp.rs, internal/compiler/lib.rs, tests/cases/exports/cpp_namespace.slint, tests/driver/cpp/cppdriver.rs, tests/driver/driverlib/lib.rs, tools/compiler/main.rs
As a little exercise, I tried implement support for C++ namespace for c++ code generated from slint-files.
Not entirely sure, if this is the right way, though.
I am also wondering how to change the CMake API to support C++ namespaces.
I would like to change the `slint_target_sources` to:
```cmake
slint_target_sources(${target} my/ui/mainwindow.slint 
NAMESPACE
my::ui)
```
Or, shall the namespace "my::ui" be derived automatically when e.g. "my/ui" when it is given in the sources?
=> Optional C++ namespaces

examples/energy-monitor/Cargo.toml, examples/energy-monitor/README.md, examples/energy-monitor/index.html, examples/energy-monitor/src/lib.rs, examples/energy-monitor/src/main.rs
This demo support both mcus, web, desktop and mobile.
Split in a lib.rs so that there are no warnings even if it means some dummy wrapper in main.
Add instructions in the README
=> Energy-monitor: android build and wasm simplicifation

api/cpp/docs/Pipfile, api/python/slint/__init__.py, api/python/tests/test_import.py, examples/printerdemo/python/Pipfile, examples/printerdemo/python/README.md, examples/printerdemo/python/main.py, xtask/src/license_headers_check.rs
This comes along with the printer demo ported, which uses it.
cc #4134
=> Python: Add support for direct .slint file imports

api/python/slint/__init__.py, api/python/tests/test_callback_decorators.py, api/python/tests/test_load_file.slint, examples/printerdemo/python/main.py
=> Python: Add support for a @slint.callback decorator to conveniently associated callbacks with python methods

internal/compiler/parser/element.rs, tools/lsp/fmt/fmt.rs
~~also test that running slint-lsp format another time don't cause changes~~
Closes #4797
=> fmt: format two way bindings

api/cpp/include/slint_properties.h, internal/core/properties/ffi.rs
The energy monitor declares a transition on an animated int property, for which Property<int>::set_animated_binding_for_transition is called, which in turn calls slint_property_set_animated_binding_helper. The latter is overloaded for various property types, such as float, Color, or Brush, and then calls specialized functions from ffi, such as
slint_property_set_animated_binding_(int|float|etc.).
slint_property_set_animated_binding_int uses i32 in Rust, which cbindgen maps to int32_t, so the
slint_property_set_animated_binding_helper overload also uses int32_t.
Unfortunately, with esp-idf, int32_t is a distinct type from int, and the overload resolution fails.
As remedy, this change uses c_int instead of i32 in the Rust ffi, which maps to int.
This seems easier than changing Property<int> …
=> Fix build of generated C++ code when using transitions on int properties with esp-idf

internal/compiler/generator/rust.rs, internal/core/graphics/image.rs, tests/cases/elements/image.slint
The call to load the image already prints a message to stderr, so don't panic but return a null image instead.
cc #4846
=> Fix panic when loading unsupported images that are embedded in generated code

internal/core/Cargo.toml, internal/core/accessibility.rs
The adds only the enums / structs needed to implement accessibility actions. There is no functionality yet. This is the first step to implement #2872. The enum is a copy of the available accessibility actions provides by accesskit, before merging we need to check what is really needed for Slint and can be already implemented with the current feature set.
=> Acessibility: added AccessibilityAction and SupportedAccessibilityAction

examples/gallery/Cargo.toml
gettext doesn't compile anymore:
```
/var/folders/x6/97fjm0c540s7yn9zlv7fp9k00000gn/T/tc81e-0/gettext/libtextstyle/lib/obstack.c:351:31: error: incompatible function pointer types initializing 'void (*)(void) __attribute__((noreturn))' with an expression of type 'void (void)' [-Wincompatible-function-pointer-types]
__attribute_noreturn__ void (*obstack_alloc_failed_handler) (void)
```
This works around it by not enabling it on macOS in the gallery.
=> Work around gettext-rs not compiling on macOS with latest xcode

internal/compiler/passes/focus_handling.rs, internal/compiler/passes/resolving.rs, internal/compiler/tests/syntax/focus/focus_wrong_args.slint
Just ignore the case where focus has more argument that planed as it has been reported as an error earlier.
Also fix the error message for calling member function with the wrong number of argument to not include the base in the count.
Fix #4883
=> compiler: Don't panic when using `foo.focus(something)`

internal/compiler/passes/move_declarations.rs, tests/cases/issues/issue_4884_show_popup.slint
They can be used in as the Popup's parent_element which we need to get to the parent's enclosing Component.
Since that parent_element is not in a RefCell, we can't change it. parent_element is a Weak so if its optimized item is removed, we will not be able to access it.
Fix #4884
=> Keep the optimized ElementRc around.

api/cpp/esp-idf/slint/CMakeLists.txt, api/cpp/esp-idf/slint/src/slint-esp.cpp
This is implemented by falling back to a polling timer and changing the Slint animation/timer update mechanism to also use a timer. That way we don't have to call update_timers_and_animations() every time the app wakes up to poll for touch.
The use of esp timers also has the advantage of offering better precision. The FreeRTOS timers are as granular as the tick, which is 5ms.
=> esp-idf: poll for touch events if there's no touch interrupt assigned

internal/backends/android-activity/androidwindowadapter.rs, internal/backends/android-activity/java/SlintAndroidJavaHelper.java, internal/backends/android-activity/javahelper.rs, internal/renderers/skia/itemrenderer.rs
On android, the handle is the same as the cursor color and the cursor color is usually the "accent" color.
We can't know the accent color from the native code, but we know the selection color which is the accent color with a lesser opacity.
=> android: fix cursor and handle color

examples/iot-dashboard/main.slint
Align the main content to the start (top) to avoid stretching.
=> Making iot-dashboard more friendly for tall windows

tests/cases/issues/issue_2598_listview_reuse_elem.slint
Looks like with the Qt style, the scrollbar are a bit too big and don't allow for the click to go through.
=> Prospective fix for the CI

internal/compiler/widgets/common/common.slint, internal/compiler/widgets/cosmic-light/std-widgets-impl.slint, internal/compiler/widgets/fluent-light/std-widgets-impl.slint, internal/compiler/widgets/material-base/lineedit.slint
The text color for the text input that has the focus is the normal "on-surface" color according to https://m3.material.io/components/text-fields/specs
Also fix the selection color of the TextEdit
=> Material style: fix text color

.github/workflows/build_docs.yaml, Cargo.toml, api/rs/slint/Cargo.toml, internal/backends/selector/Cargo.toml, internal/backends/winit/Cargo.toml, internal/backends/winit/lib.rs, internal/backends/winit/winitwindowadapter.rs, internal/core/Cargo.toml, internal/core/api.rs, internal/core/translations.rs, internal/core/window.rs, internal/interpreter/Cargo.toml
Add a `rwh_06` feature to the Rust API crates, which adds support for version 0.6 of rwh to slint::Window, by delegation to the backend.
HasDisplayHandle could also be provided on the backend, but that can be done separately if needed.
Fixes #877
=> Add support for raw-window-handle

internal/compiler/builtin_macros.rs, internal/compiler/tests/syntax/lookup/color.slint
This is technically a breaking change if someone was calling it with too many args by mistake, but i think it's fine to do this as a bugfix
=> Fix missing error when calling argb() with too many arguments

examples/energy-monitor/ui/widgets/balance_chart.slint, examples/energy-monitor/ui/widgets/bar_chart.slint, examples/energy-monitor/ui/widgets/page_scroll_view.slint
The use of gradients in the design to implement bar charts prevents Skia from batching, which means that each bar is a separate draw call.
Since we barely change the model data, use a cache-rendering-hint to batch the bar charts by hand into a texture.
Similarly, when scrolling on the main screen, we don't need to re-draw each page individually until we're selecting.
This boosts the scrolling performance from 13fps to 30fps on an stm32mp157.
See #4944 for separate docs about this.
=> Improve rendering performance of the energy monitor

internal/compiler/passes/infer_aliases_types.rs, internal/compiler/tests/syntax/lookup/callback_alias_issue4938.slint
Instead of panicking
Fixes #4938
=> Throw an error when a callback aliases itself

internal/compiler/generator/rust.rs, internal/compiler/llr/expression.rs, tests/cases/issues/issue_4942_no_else_value.slint
=> Fix code generation when the `if` branch has a value and there is no `else` branch

api/cpp/include/slint.h, api/cpp/tests/models.cpp
They were causing infinite recursion because they were calling themselves.
Also add the missing MapModel::reset
Yet another motivation for https://github.com/slint-ui/slint/issues/3888 as the code was mixing the `reset` function on the adapter meaning "please re-apply the adapter filter/map/sort function" with the `reset` function on Model which means "the subclass has changed and we should notify listeners".
Fixes #4968
=> C++: Fix and test the `reset` function on model adapter

internal/interpreter/dynamic_item_tree.rs, internal/interpreter/eval.rs, tests/cases/models/issue_4961_model_index_property.slint
Use a `$` sing in the name of special property so that they do not replace user defined properties
The scale_factor property was unused since 9fd7d35b0d2d81711c8a0c62bc9dd821655e6e8c or even before
Fixes #4961
=> Fix interpreter overwriting index property

api/cpp/include/slint.h, api/cpp/tests/models.cpp
Avoids to invoke filtering function until `slint::FilterModel` and its subclasses are completely constructed, deferring it to first model usage.
See issue #4983 for more details.
A basic program to demonstrate the problem and the fix:
```Slint
// appwindow.slint
import { ListView, VerticalBox, Switch, HorizontalBox, LineEdit, Button } from "std-widgets.slint";
export component AppWindow inherits Window {
in property <[int]> model;
in-out property only-evens <=> only-evens-switch.checked;
in-out property ascending <=> ascending-switch.checked;
callback only-evens-changed <=> only-evens-switch.toggled;
callback ascending-changed <=> ascending-switch.toggled;
callback add-element(int);
callback remove-element(int);
VerticalBox {
only-evens-switch := Switch {
text: "Only evens";
} …
```
=> C++: FilterModel with deferred filtering

examples/printerdemo/rust/index.html
Following the recent changes in #4765, the library name was updated from `printerdemo` to `printerdemo_lib`. This modification has inadvertently affected the naming of the JavaScript file generated by `wasm-pack`, leading to `printerdemo.js` being renamed to `printerdemo_lib.js`. Consequently, the existing reference in the `index.html` file became outdated, causing the WASM module to fail to load correctly.
This PR addresses the issue by updating the reference in `index.html`, ensuring that the page can properly load and execute the WASM module.
Details of the changes:
- Updated the script import in `index.html` from `import init from './pkg/printerdemo.js';` to `import init from './pkg/printerdemo_lib.js';`.
With these adjustments, the resource loading error caused by the library name …
=> Fix WASM Loading Issue Due to Library Name Change

internal/backends/qt/qt_widgets/checkbox.rs
**Changes**
- Implement `has_hover` for NativeCheckBox
Closes #4998
=> Implement `has_hover` for NativeCheckBox

api/cpp/esp-idf/slint/include/slint-esp.h, api/cpp/esp-idf/slint/src/slint-esp.cpp, api/cpp/include/slint-platform.h, api/cpp/platform.rs
Rendering by line into a line buffer that's in IRAM can be faster than accessing framebuffers in slower PSRAM, so offer this by allowing users to omit even the initial framebuffer.
=> esp-idf: Add support for line-by-line rendering

internal/compiler/widgets/common/spinbox-base.slint, tests/cases/widgets/spinbox_basic.slint
Scrolling up should increase the value, not decrease it.
The Qt behaviour was changed in #5010
=> Spinbox: fix and test the behaviour on mousewheel

internal/backends/qt/qt_accessible.rs, internal/backends/winit/accesskit.rs, internal/common/enums.rs, internal/compiler/widgets/cosmic-base/switch.slint, internal/compiler/widgets/cupertino-base/switch.slint, internal/compiler/widgets/fluent-base/switch.slint, internal/compiler/widgets/material-base/switch.slint, internal/compiler/widgets/qt/switch.slint
`Switch` widgets are currently exposed as check boxes in the accessibility tree. Since AccessKit has the `Switch` role, let's use that to better carry the meaning.
Tested by running the gallery example app which contain many.
=> Properly expose `Switch` as such in the accessibility tree

internal/backends/winit/accesskit.rs, internal/compiler/widgets/cosmic-base/button.slint, internal/compiler/widgets/cupertino-base/button.slint, internal/compiler/widgets/fluent-base/button.slint, internal/compiler/widgets/material-base/button.slint
If a button is checkable then it becomes a toggle button. It is probably not necessary to expose this accessible role directly, it can be figured out by looking if `accessible-checkable` is set on the widget.
Since the Qt button already had `accessible-checkable` and `accessible-checked`, I assume the behavior has been validated, I haven't done it myself.
Tested by playing with the OFF/ON toggle button in the gallery example, below the Dark mode switch.
=> Expose toggle buttons as such to AccessKit

api/cpp/build.rs
cargo currently doesn't know that we read this env var, which can lead to caching issues
=> rerun-if-env-changed=SLINT_GENERATED_INCLUDE_DIR

internal/backends/android-activity/androidwindowadapter.rs
Make the code by @matthewjrichey found in issue #5031 into a PR:
> [...] discovered that `AMotionEvent_getActionButton` is only available on
> Android NDK 33 (Android 13) or higher. I came up with a working fix for the
> problem, which is tested and working on Android 12.
Done-by: @matthewjrichey
Closes #5031
=> android: Support Android 12

internal/compiler/passes/lower_states.rs, tests/cases/properties/issue5038_state_in_base.slint
=> Compiler: properly transform property access from base expression in state

CHANGELOG.md, internal/renderers/femtovg/fonts.rs
Make sure the key for the fontdb query -> femtovg font mapping includes the style (and stretch, for good future measure).
Fixes #5056
=> Fix selection of italic font styles with the FemtoVG renderer

Cargo.toml, api/cpp/Cargo.toml, api/rs/slint/Cargo.toml, examples/imagefilter/rust/Cargo.toml, internal/backends/testing/Cargo.toml, internal/compiler/Cargo.toml, internal/core/Cargo.toml, tests/screenshots/Cargo.toml, tools/lsp/Cargo.toml, tools/viewer/Cargo.toml
Note: this could be a breaking change if someone did
```toml
image = { version = "0.24", features = [...] }
```
to enable more features decoder of the image to support more file format in slint
=> Janitor: Update the image crate

.github/workflows/ci.yaml, api/node/Cargo.toml, api/node/index.ts, api/node/package.json, api/node/src/lib.rs, tests/driver/nodejs/nodejs.rs, xtask/src/nodepackage.rs
Add the ability to depend on the testing backend and opt into it when running tests/cases, like we do for the other drivers.
The testing backend dependency is removed in the packaging step, as we don't publish i-slint-backend-testing.
=> Run Node.js tests with the testing backend

internal/core/graphics/color.rs
This PR changes the algorithm used for color interpolation to use `i_slint_core::graphics::color::Color#mix`. 
This would resolve the issue of color transitions having incorrect values when animating color to/from `transparent`
Color#mix accounts for the alpha channel, so a transparent transition is not skewed by changes in transparency.
For example, with the proposed changes, a transition from `transparent` to `lightgray` changes like this .
On the left is the current algorithm, on the right is Color#mix
Motivated by https://github.com/slint-ui/slint/issues/5055
=> Use Color#mix for color interpolation

internal/compiler/generator/cpp.rs, tests/cases/types/functions.slint
and whose expression return something. Otherwise we get an error: `return-statement with a value, in function returning ‘void’`
=> C++: fix code generation of functions that don't return anything

Cargo.toml, api/rs/slint/Cargo.toml, internal/core/Cargo.toml
This reverts commit a159562ea7724909f201491427d581e06ca0f60c and just the version part of commit 1d2201a7ce48b4a61e66cdde6d7eed1a38ab8be0 to downgrade image to 0.24 again.
This is not a straight revert, the workspace unification remains, just the version is down to 0.24.
The update to the new image crate version causes two issues
- With the Xtensa Rust toolchain, a release build of the image crate takes excessively long (cargo +esp build --release in image-rs)
- The image crate version updates to zune-jpeg for JPEG decoding, which uses "cdylib" in crate-type, which in turn breaks the cross-compilation with Corrosion against a Linux sysroot, because the (unnecessary) zune-jpeg cdylib creation doesn't see corrosion's link args that provide the sysroot. (upstream PR at …
=> Revert "Add a "image-default-formats" feature" and "Janitor: Update the image crate"

internal/backends/qt/qt_accessible.rs, internal/backends/winit/accesskit.rs, internal/compiler/typeregister.rs, internal/compiler/widgets/cosmic-base/spinbox.slint, internal/compiler/widgets/cupertino-base/spinbox.slint, internal/compiler/widgets/fluent-base/spinbox.slint, internal/compiler/widgets/material-base/spinbox.slint, internal/compiler/widgets/qt/spinbox.slint, internal/core/accessibility.rs
Because we don't support it in Qt and in our widgets yet.
Also accessible-action-set-value now takes a string because value is a string (for the line edit)
=> Accessibility: Remove the replace-select-text from the slint api

docs/reference/src/language/widgets/textedit.md
=> Typo on TextEdit doc

docs/quickstart/cpp/src/memory_game_logic.slint, docs/quickstart/cpp/src/memory_tiles_from_cpp.slint, docs/quickstart/node/src/memory_game_logic.slint, docs/quickstart/node/src/memory_tiles_from_cpp.slint, docs/quickstart/rust/src/main_game_logic_in_rust.rs, docs/quickstart/rust/src/main_multiple_tiles.rs, docs/quickstart/rust/src/main_tiles_from_rust.rs
Adds `x` value for left Rectangle. Fixes #5090 
EDIT: 
- cpp source had the same issue. Corrected and tested.
- node source had the same `.slint` source files as cpp source. These files were synced to the cpp src, but NOT tested.
=> Quickstart Rust Example Fix: Add x value for left Rectangle.

tools/viewer/main.rs
Some editors may backup a file by renaming it to append ~, then saving the new file contents to a new file. notify-rs/notify#166 explains that a non-recursive watcher on the parent directory is the recommended way to deal with this situation.
Closes: #3641
=> Fix slint-viewer --auto-reload for editors which rename and replace files

api/cpp/include/slint-interpreter.h, api/cpp/tests/interpreter.cpp
Remove send_keyboard_char as it doesn't appear to be used (while send_keyboard_string_sequence is used in a single test)
=> C++: Move internal testing function to the internal namespace

api/python/timer.rs, internal/core/timers.rs
The Timer cannot be moved between threads because the id is only valid as part of the thread local of timers.
This is a breaking change. But if one had move timer between thread before, it would have caused a bug.
=> Rust Timer: Mark as `!Send`

CHANGELOG.md, docs/reference/src/advanced/backends_and_renderers.md, docs/reference/src/language/builtins/elements.md, internal/backends/qt/qt_window.rs, internal/common/enums.rs, internal/compiler/builtins.slint, internal/core/items/text.rs, internal/renderers/femtovg/itemrenderer.rs, internal/renderers/skia/itemrenderer.rs
Closes #4981.
Contains implementations for FemtoVG, Skia, and Qt.
Notes:
- While working on this, I stumbled upon a bug in FemtoVG (femtovg/femtovg#205) which causes outlines to sometimes render incorrectly.
- Using text strokes on Qt causes a noticeable performance dip on my machine. I did my best to optimize it but there may be further room for improvement.
=> Text strokes

editors/vscode/package.json, editors/vscode/slint.markdown-injection.json
Use an injection grammar to achieve this.
=> Add support for slint syntax highlighting in markcode code fences

api/cpp/include/slint_brush.h, internal/compiler/object_tree.rs, internal/compiler/passes.rs, internal/compiler/passes/collect_subcomponents.rs, internal/compiler/passes/inlining.rs, internal/core/properties/ffi.rs, tests/cases/callbacks/init.slint, tests/cases/issues/issue_5146_init_animated.slint
The problem was that the code from #4322 inlined the init code in the parent Component as at that point, the per-repeater component don't exist yet.
Fix it by removing the workaround from #4322, but changing the order of the passes so that the init code are already proccessed before any inlining. This required to change the order of a bunch of passes.
Fixes #5146
As a drive-by, also add the missing C++ implementation of set_animated_value for Brush that was discovered by the test. (Code wouldn't compile)
=> Fix compiler panic with init in a component inlined into a repeater

docs/reference/src/language/widgets/slider.md, docs/reference/src/language/widgets/spinbox.md, internal/compiler/widgets/common/slider-base.slint, internal/compiler/widgets/common/spinbox-base.slint, internal/compiler/widgets/qt/slider.slint, internal/compiler/widgets/qt/spinbox.slint, tests/cases/widgets/slider_default_value.slint, tests/cases/widgets/spinbox_default_value.slint
Currently, the default slider value is 0. This means that setting a positive minimum value causes the slider's value to be incorrect until it is moved.
This is also shown visually in most themes with the slider handle being rendered off the end of the slider body:
And while it is visually correct with Qt, the value itself is still wrong:
This PR sets the default value to that of the minimum.
This is my first PR here and I'm not entirely sure if `internal/compiler/widgets/qt/slider.slint` was the correct place for this fix for Qt. Please let me know if there's a better way to implement this and thank you for your work!
=> Fix a positive minimum causing an incorrect slider/spinbox value

internal/backends/winit/lib.rs
If Skia is available, pick that over FemtoVG. We end up recommending Skia for most customers, so it should be enough to enable the feature and not require additionally setting the `SLINT_BACKEND` environment variable.
This change also means that the live-preview in the language server will default to Skia on desktop installations. On the downside, this means that Slintpad and the VS Code extension for the web will be using a different renderer (FemtoVG).
=> Pick the Skia renderer over FemtoVG

api/node/__test__/js_value_conversion.spec.mts
After the Rust 1.78 release, napi-rs panics on zero-sized array buffers.
Work around it by disabling the debug assertions in the core library that trigger this.
Upstream PR: https://github.com/napi-rs/napi-rs/pull/2083
=> Fix Node.js CI

internal/backends/winit/lib.rs, internal/backends/winit/winitwindowadapter.rs
When the winit backend creates the Skia renderer, there is no associated surface to render into. Only the winit Resume event would cause a call to set_window_handle() and thus surface creation. This was done for the earlier Android backend, and is generally good practice.
When running for example slint-viewer with SLINT_BACKEND=winit-skia, we would create the skia renderer (no surface), then start the winit event loop, get a resume event, initialize the surface, and it all works.
With the live-preview inside the lsp, we'd create the event loop, get a resume event (but there's no window yet), and then we'd create the skia renderer without a surface... ever.
It's not ideal, but for now call resume() explicitly since we _do_ have a winit window, and we're not calling this on Android anymore.
=>  Fix live-preview not working with Skia backend

internal/compiler/object_tree.rs, internal/compiler/passes.rs, internal/compiler/passes/inlining.rs, internal/compiler/passes/lower_popups.rs, internal/compiler/passes/materialize_fake_properties.rs, internal/compiler/tests/syntax/elements/popup2.slint, tests/cases/elements/popupwindow.slint, tests/cases/elements/popupwindow_inherits.slint
This regressed in commit 12d904a71ca31f947bfe983e7dbfe745b2439b74 which changed the order of the pass to get the lower_popup pass before the first inlining pass.
If by chance (which is likely if one have children), the component that inherits from PopupWindow was inlined in that pass, it would be as if it was not a component, and it would be removed from its parent. But since it is no longer inlined, we need to support that case and delay the removal when processing the component that holds that popup.
=> Fix component that inherits from PopupWindow

.github/workflows/build_docs.yaml, CHANGELOG.md, api/rs/slint/Cargo.toml, api/rs/slint/android.rs, api/rs/slint/lib.rs, examples/energy-monitor/Cargo.toml, examples/printerdemo/rust/Cargo.toml, examples/todo/rust/Cargo.toml, internal/backends/android-activity/Cargo.toml, internal/backends/android-activity/lib.rs
The android-activity 0.5 no longer works with Rust 1.78 because it asserts with
> slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
=> Update the android-activity crate by adding a new feature

internal/compiler/object_tree.rs, internal/compiler/tests/syntax/basic/signal.slint, internal/compiler/tests/syntax/lookup/callback_alias3.slint
Do the check for existing property before handling of callback aliases
Fixes #5205
=> Fix declaring callback alias that override a property

editors/vscode/src/wasm_preview.ts
Prospective fix for loading of image when using the vscode extension from the web (eg, via https://github.dev)
URL is different in a local web extension and in a online web extension. In a local web extension, it still use file:// for urls, but online, it uses vscode-vfs:// url. And we wouldn't map it because it doesn't start with file://
I couldn't find a reason looking at the git history why we check for file://, I assumed this might have been because of builtin:/, but I checked and these still work both with the wasm in the native extension, and as a web extension
=> vscode web extension: Fix loading of images

tools/slintpad/src/tsconfig.json, tools/slintpad/src/worker/tsconfig.json
It's not needed for the tsc build but was brought in through an implicit dependency.
=> Slintpad: Fix failing typecsript build by removing unused json-schema type declaration requirement

CHANGELOG.md, internal/compiler/object_tree.rs, internal/compiler/passes/remove_aliases.rs, internal/compiler/passes/remove_unused_properties.rs, internal/compiler/widgets/common/combobox-base.slint, tests/cases/widgets/combobox.slint
=> ComboBox reset current on model changed

.github/workflows/nightly_snapshot.yaml
Fix slintpad publishing and creation of versions.txt, as noticed during the 1.6.0 release process.
=> Fixes for release publishing

.reuse/dep5, espflash.toml, examples/mcu-board-support/partitions.csv
These tend to grow now beyond the 1MB default, so use the same partitions.csv that we use for esp-idf, which provisions a 4MB partition.
Fixes #5252
=> ESP32: Fix flashing examples such as printerdemo_mcu with espflash

docker/Dockerfile.aarch64-unknown-linux-gnu, docker/Dockerfile.armv7-unknown-linux-gnueabihf, docs/building.md
slint needs openssl to build it.
The system library `openssl` required by crate `openssl-sys` was not found. The file `openssl.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory. PKG_CONFIG_PATH contains the following:
- /usr/lib/arm-linux-gnueabihf/pkgconfig
HINT: you may need to install a package such as openssl, openssl-dev or openssl-devel.
=> Fix build for raspberry pi with cross

docs/reference/src/language/syntax/types.md
Don't duplicate the list of easing. Refer to the list in the animation page. The list in types.md was out of date
=> Docs: Fix documentation of easing curve

internal/compiler/lookup.rs, internal/compiler/tests/syntax/lookup/global.slint
User defined component or global named StyleMetrics shouldn't be deprecated
=> Only mark builtin StyleMetrics as deprectated.

internal/core/api.rs, internal/core/platform.rs
Some error already had it, so just add the missing ones
(Found this while trying to use `?` in an example
=> Implement the Error trait for our errors

tools/lsp/language.rs, tools/lsp/language/completion.rs, tools/lsp/language/component_catalog.rs, tools/lsp/util.rs
For example, propose to auto-complete Palette and add the import statements from std-widgets
=> LSP auto-completion: suggests unimported globals in expressions

internal/backends/winit/accesskit.rs, internal/compiler/widgets/cosmic-base/progressindicator.slint, internal/compiler/widgets/cosmic-base/spinner.slint, internal/compiler/widgets/cupertino-base/progressindicator.slint, internal/compiler/widgets/cupertino-base/spinner.slint, internal/compiler/widgets/fluent-base/progressindicator.slint, internal/compiler/widgets/fluent-base/spinner.slint, internal/compiler/widgets/material-base/progressindicator.slint, internal/compiler/widgets/material-base/spinner.slint, internal/compiler/widgets/qt/progressindicator.slint, internal/compiler/widgets/qt/spinner.slint
The default values for minimum and maximum values are 0 and 100. Since Slint's value for progress indicators range from 0 to 1, this needs to be communicated to assistive technologies so they can calculate the correct percentage.
Passing an empty string when the progress is indeterminate feels like a hack, let me know if there is a way to conditionally set a property.
I had to refactor the way minimum, maximum and step properties are set on nodes because having them tied together is not really a great idea. In the case of progress indicators, step doesn't really make sense.
Not directly related to this PR: the numeric value shouldn't be set on a node just because `accessible-value` can be parsed to an f64. If a text entry contains `"42"`, the `value` property should be set, not …
=> Set accessible min/max values on progress indicator widgets

internal/backends/android-activity/java/SlintAndroidJavaHelper.java
The getWindowVisibleDisplayFrame seems to return a rectangle in the screen coordinate and cut the room for the camera. The problem is that the Window is somehow already displaced. The insets seems to be a better way to get that value.
Fixes #5242
=> Android: fix content positioning

internal/renderers/skia/Cargo.toml, internal/renderers/skia/metal_surface.rs, internal/renderers/skia/opengl_surface.rs, internal/renderers/skia/textlayout.rs, internal/renderers/skia/vulkan_surface.rs
This updates Skia to milestone 126 and (among other things) fixes SKIA_DEBUG=1 builds.
See https://github.com/rust-skia/rust-skia/releases/tag/0.75.0 for more details.
=> Bump Skia Rust bindings to 0.75

internal/compiler/layout.rs, internal/compiler/passes/flickable.rs, internal/compiler/passes/lower_layout.rs, internal/compiler/passes/lower_popups.rs, internal/compiler/tests/syntax/elements/popup3.slint, tests/cases/crashes/issue5259_popup_in_row.slint
Don't remove the Row element. 
And add a warning when using PopupWindow in a layout
Fixes #5259
=> Fix PopupMenu in Row

internal/interpreter/eval.rs, tests/cases/models/array.slint
The Rust and C++ code already used row_data_tracked, which do the right thing.
Fixes #5291
=> Interpreter: accessing model index should track model length if the index is out of bounds

CHANGELOG.md, api/cpp/cmake/SlintMacro.cmake, api/cpp/docs/cmake_reference.md, api/cpp/tests/CMakeLists.txt, api/cpp/tests/libraries/CMakeLists.txt, api/cpp/tests/libraries/README.md, api/cpp/tests/libraries/appwindow.slint, api/cpp/tests/libraries/main.cpp
This makes it possible to use component libraries with C++.
=> CMake: Add support for LIBRARY_PATHS to slint_target_sources

internal/compiler/generator/rust.rs
We don't want user to see clippy warnings from our generated code
Relates to #1874
=> Ignore all clippy warnings in generated code

internal/backends/android-activity/androidwindowadapter.rs, internal/backends/winit/renderer/femtovg/glcontext.rs, internal/backends/winit/renderer/skia.rs, internal/renderers/skia/lib.rs, internal/renderers/skia/metal_surface.rs, internal/renderers/skia/opengl_surface.rs
Commit 1e450abc9ca3dce9958ec5c5c6e95021ecb76bf7 originally fixed this. Meanwhile, after many refactorings, this doesn't work anymore for the FemtoVG renderer. That's because the contents placement (or layer's contents gravity) is set before the hidden layer NSOpenGLContext creates is associated with the view.
For the Skia GL surface that already works, but for clarify the code is moved into the same location.
For Skia Metal rendering, apply the same on the metal layer (through the view). For this to work the contents scale also needs to be applied. To avoid further visual effects, the scale needs to be applied as early as possible, so apply it right after creating the surface and latest at rendering time.
Fixes #5258
=> Fix jitter when resizing a window on macOS

.github/workflows/ci.yaml, api/cpp/include/slint-testing.h, examples/todo/cpp/CMakeLists.txt, internal/backends/testing/search_api.rs, internal/compiler/object_tree.rs, tests/cases/testing/find_by_element_id_or_type.slint
This fix the C++ todo test that wasn't run because of a typo
When an element is optimized in another one, only the first one should report the accessible properties. (because element with accessible properties cannot be optimized so they are always the first)
=> Testing: Fix duplicated accessibility element

docs/reference/src/advanced/backend_linuxkms.md, internal/backends/linuxkms/Cargo.toml, internal/backends/linuxkms/calloop_backend.rs, internal/backends/linuxkms/display.rs, internal/backends/linuxkms/display/swdisplay.rs, internal/backends/linuxkms/fullscreenwindowadapter.rs, internal/backends/linuxkms/lib.rs, internal/backends/linuxkms/renderer/skia.rs, internal/backends/linuxkms/renderer/sw.rs, internal/backends/selector/Cargo.toml
=> LinuxKMS: Add support for the Slint software renderer

api/cpp/esp-idf/slint/README.md, api/cpp/esp-idf/slint/include/slint-esp.h, api/cpp/esp-idf/slint/src/slint-esp.cpp, examples/carousel/esp-idf/main.cpp, examples/printerdemo_mcu/esp-idf/main/main.cpp
We can't automatically determine what the display supports, so we need to make this an opt-in - just like it is with LVGL.
Fixes #5332
=> Make it possible to use slint-esp with displays that expect little endian ordered RGB565 pixels

api/cpp/esp-idf/slint/include/slint-esp.h, api/cpp/esp-idf/slint/src/slint-esp.cpp
Commit 88e1a366a305626c5151c5727aa4e29aae71d338 stabilized the rotation support and commit 1378d6e3bc16b4f9ee78d01861fd90190accc79a adds new API to select rotation in the esp-idf integration.
The previous rotation parameter was behind the experimental flag. Now that we have a "cleaner" API, we might as well remove the old experiment in favor of the newer API.
=> slint-esp: Remove rotation parameter from older slint_esp_init overload

CHANGELOG.md, api/rs/slint/lib.rs, internal/core/graphics/image.rs, internal/interpreter/api.rs
This change exposes functionality of already existing internal API that all renderers use to obtain pixels for upload to the screen - so it's rather well tested.
This also exposes the `SharedImageBuffer` API, an enum that represents different SharedPixelBuffer encodings.
=> Make it possible to retrieve a SharedImageBuffer for a slint::Image in Rust

docs/reference/conf.py, docs/resources/slint-docs-highlight.html, internal/common/enums.rs
The relative links don't work, so use slint-reference: custom schemes that works with sphinx and is rewritten with JavaScript through injections.
=> Fix links to widgets in AccessibleRole docs embedded in i-slint-backend-testing docs

api/cpp/cbindgen.rs, api/cpp/include/slint_window.h, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/core/window.rs
Planning for multi-component support
=> Rust: Don't get the default font size through the root component

internal/backends/testing/Cargo.toml, scripts/publish.sh
(also add std to the required features of core, so it compiles out of the box)
=> Add i-slint-backend-testing to the list of published crates

api/cpp/include/slint_window.h, internal/compiler/generator/cpp.rs
So that subcomponent don't depend on the root component name which will hallow to have several root components
=> C++: move globals in a different struct

internal/compiler/generator.rs, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/llr.rs, internal/compiler/llr/expression.rs, internal/compiler/llr/item_tree.rs, internal/compiler/llr/lower_to_item_tree.rs, internal/compiler/llr/optim_passes/count_property_use.rs, internal/compiler/llr/optim_passes/inline_expressions.rs, internal/compiler/llr/pretty_print.rs
There currently still can only be one because the passes expect that, but now the LLR and generator should be ready to accept multiple public component later
=> LLR: primilary support for multiple public components

internal/compiler/generator/rust.rs
Workaround from https://github.com/rust-lang/rust/issues/53827
=> Rust: Attempt to fix the stack overflow when constructing the item array

.github/workflows/ci.yaml, .github/workflows/nightly_snapshot.yaml
macos-11 will be removed end of June as per https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/
=> CI: Bump macos-11 to macos-12 images

internal/backends/qt/qt_window.rs, internal/backends/testing/testing_backend.rs, internal/common/enums.rs, internal/compiler/widgets/common/textedit-base.slint, internal/compiler/widgets/cupertino-base/textedit.slint, internal/core/items/text.rs, internal/core/renderer.rs, internal/core/software_renderer.rs, internal/core/software_renderer/fonts.rs, internal/core/textlayout.rs, internal/core/textlayout/linebreaker.rs, internal/renderers/femtovg/fonts.rs, internal/renderers/femtovg/lib.rs, internal/renderers/skia/lib.rs, internal/renderers/skia/textlayout.rs
As discussed in here https://github.com/slint-ui/slint/issues/5374, this PR adds the possibility of using character wrapping (aka wrap anywhere) with text. Prior to this, it was only possible to wrap at word boundaries.
This commit adds this functionality to both Qt and software renderer, with skia and femtovg missing it for now (falling back to word-wrap).
The trait RendererSealed  had to be changed to pass to text_size if using this new kind of wrapping.
This was based on GTK wrap mode which has the following options:
- GTK_WRAP_NONE -> Matches `no-wrap` on slint
- GTK_WRAP_CHAR -> Matches `char-wrap` with this PR (on Qt and software renderer for now)
- GTK_WRAP_WORD -> Matches `word-wrap` with Qt renderer (Qt supports WrapAtWordBoundaryOrAnywhere but would need Qt 6.3 as we use …
=> Add char-wrap functionality to text wrapping

internal/backends/qt/qt_window.rs
When the popup window is destroyed, the hack we did to close the app on the last window was too aggressive with Qt6 and closed the application when it shouldn't have.
Fixes #4803
=> Qt backend: fix combobox quiting the application with Qt6

internal/compiler/widgets/common/spinner-base.slint, internal/compiler/widgets/cosmic-base/spinner.slint, internal/compiler/widgets/cupertino-base/spinner.slint, internal/compiler/widgets/fluent-base/spinner.slint, internal/compiler/widgets/material-base/spinner.slint
Since we use the stroke and stroke with, then a single arc is enough instead of two connected by lines
=> Spinner: simplify the arc path

docs/reference/src/quickstart/getting_started.md
The quickstart use the slint macro which doesn't use build.rs. The template is conter-productive as it uses the slint-build and build.rs to compile Slint file. If we're not using that, it is much easier to start with a fresh clean project.
=> Rust quickstart: don't use the template if we're not using build.rs

internal/compiler/passes.rs, tests/cases/expr/return.slint
Otherwise we end up inlining "returns" in the wrong property
Fixes #5430
=> compiler: perform remove return pass before const propagation

internal/backends/linuxkms/display.rs, internal/backends/linuxkms/lib.rs
I went with an #[allow] rather than #[cfg] because catching the exact right expression is complicated (any renderer, and none should be forgotten)
=> linuxkms: ignore warning when no renderer are active

Cargo.toml, internal/common/sharedfontdb.rs, internal/compiler/passes/embed_glyphs.rs, internal/compiler/passes/embed_images.rs, internal/core/Cargo.toml, internal/core/graphics/image/svg.rs, internal/core/software_renderer/fonts/systemfonts.rs, internal/renderers/femtovg/Cargo.toml, internal/renderers/femtovg/fonts.rs
Bigger change is cause by resvg/usvg which now takes the font database in a Arc, so we must store it in a Arc ourself to cheaply lend it to usvg
=> Update a bunch of dependencies

internal/compiler/generator.rs, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/llr/lower_to_item_tree.rs, internal/compiler/object_tree.rs, internal/compiler/passes.rs, internal/compiler/passes/check_public_api.rs, internal/compiler/passes/collect_custom_fonts.rs, internal/compiler/passes/collect_globals.rs, internal/compiler/passes/collect_subcomponents.rs, internal/compiler/passes/const_propagation.rs, internal/compiler/passes/embed_glyphs.rs, internal/compiler/passes/inlining.rs, internal/compiler/passes/repeater_component.rs, internal/compiler/passes/unique_id.rs, internal/compiler/typeloader.rs, internal/interpreter/dynamic_item_tree.rs, tests/cases/exports/multiple_components.slint
When lowering to the LLR, generate one PublicComponent for each exported component in the main file
Closes #784
=> Generate multiple components in Rust and C++

api/cpp/docs/generated_code.md, api/rs/slint/lib.rs, api/rs/slint/tests/simple_macro.rs, internal/compiler/lib.rs, internal/compiler/object_tree.rs, internal/compiler/passes.rs, internal/compiler/passes/check_public_api.rs, internal/compiler/passes/ensure_window.rs, internal/compiler/tests/syntax/exports/export_non_window.slint, internal/compiler/tests/syntax_tests.rs, internal/compiler/typeloader.rs, internal/interpreter/dynamic_item_tree.rs, tests/cases/exports/multiple_components.slint
Have a warning when a component is exported from the main file and doesn't inherit Window.
Unless it's the last component, for compatibility with Slint 1.6
Also don't warn in the interpreter
=> Only generate code for the exported Window

docs/reference/src/language/syntax/functions.md
While learning slint, I noticed that a lot of behaviors (in this case about functions) aren't clearly stated in the documentation. So I'm trying to document what I've learned and hopefully make it easier for the next person.
**I've tested this mostly by experiment**, meaning I'm not sure what's Working as Intended / by-design and what's Working as Implemented / by-chance. Actually that's a problem I'm hoping to address by documenting things more explicitly, but I need the core developers to tell me if something I've documented is not actually supposed to work that way.
Also, I don't know if you have specific standards/style regarding documentation that I should be following. If you do, let me know, I'm happy to read/apply them :)
There are more things I'd like to see in this file, in …
=> Improve docs on functions

internal/renderers/skia/itemrenderer.rs
**Notes**
This overcomplicates `brush_to_shader()` a bit more than necessary to avoid duplicating two lines of code, but it made sense to me to pair shader-specific paint settings with shader-instantiation. One consideration is that `brush_to_paint()` already exists and has several callers in the renderer, but produces a `Paint` object that isn't compatible with `colorize_image()`. `brush_to_shader()` only has these two callers(one being `brush_to_paint()`, the other being `colorize_image()` so the complexity is mostly tucked away from the rest of the module.
Also, when trying this out with the energy monitor example, it seems to have traded _banding_ in the background radial gradient for _jitter_ in the background radial gradient. This doesn't make sense to me because [dithering in skia …
=> Support dithering gradients in the skia renderer

api/python/tests/test_timers.py
It seems that with the latest winit, quit_event_loop() might take a little longer and the timer fires once more. We don't really care how long quit_event_loop() takes in this test, merely that the timer firest and that we can terminate the loop.
Fixes #5484
=> Python: Make the timer test more robust

internal/backends/qt/qt_window.rs, internal/backends/winit/winitwindowadapter.rs
Fixes #5489
We shouldn't resize the window to the size of the WindowItem after start. This happens when set_size is called before show. The the resize event didn't yet propagate the size to the WindowItem properties.
=> winit: Fix setting the size with set_size before showing the window

api/node/src/lib.rs, api/rs/slint/tests/show_strongref.rs, api/rs/slint/tests/spawn_local.rs, internal/backends/testing/README.md, internal/backends/testing/ffi.rs, internal/backends/testing/internal_tests.rs, internal/backends/testing/lib.rs, internal/backends/testing/search_api.rs, internal/backends/testing/testing_backend.rs, internal/backends/testing/tests/click.rs, internal/core/future.rs, internal/core/item_tree.rs
This patch adds async click functions to ElementHandle and adds timer support to the testing backend's event loop.
=> Add support for async unit testing and element handle click events

internal/interpreter/dynamic_item_tree.rs, tests/cases/issues/issue_5500_panics_uninitialized_animation.slint
This way it also start initialized with a value of the proper type, and this will "fix" #5500 by not panicking anymore.
Fixes #5500
=> Interpreter: give the right type to the model property instead of Value

CHANGELOG.md, internal/core/timers.rs
When stopping a timer, the removal from the timer list requires a mutable borrow. If during that borrow the timer's closure is dropped and a `Drop` impl starts another time, then the attempt of acquiring a mutable borrow for the timers list to insert the new timer fails.
=> Fix panic in slint::Timer due to double mutable borrow

internal/backends/winit/build.rs, internal/core/Cargo.toml, internal/core/build.rs, internal/renderers/skia/build.rs
- The cfg_aliases crate does it out of the box already
- Don't create a build.rs for this only purpose when it can be added in Cargo.toml lints group. (This wasn't possible when the warning was first introduced in nightly)
=> Remove some `cargo:rustc-check-cfg` output:

internal/compiler/passes/check_rotation.rs, internal/compiler/tests/syntax/basic/rotation.slint, tests/cases/examples/rotate.slint
This works with Skia, Qt, and FemtoVG.
cc #1481
=> Permit rotation properties on Text elements without children

api/cpp/docs/generated_code.md, api/node/README.md, api/rs/slint/docs.rs, tests/cases/examples/sample_component.slint
Tested for Rust and C++, wasn't able to test JS but it should work.
I found a `sample_component.slint` file that seems to be intended to be the same code as the SampleComponent in Rust and C++ docs, so I updated it to be in sync with the code in those language docs. Let me know if that is not what it's supposed to be.
=> Update language-specific docs to document that public functions can be called from the backend code

internal/backends/winit/event_loop.rs, internal/backends/winit/lib.rs
Valgrind would report invalid reads on the wayland clipboard shutdown code, suggesting that the wayland display has already been destroyed.
Since the display handle isn't refcounted, we must make sure that the wayland clipboard is around as long as the wayland display handle, provided by the winit event loop.
=> Fix crash on app shutdown on Wayland

Cargo.toml, internal/backends/winit/accesskit.rs, internal/backends/winit/event_loop.rs, internal/backends/winit/lib.rs, internal/backends/winit/renderer/femtovg.rs, internal/backends/winit/renderer/skia.rs, internal/backends/winit/renderer/sw.rs, internal/backends/winit/winitwindowadapter.rs, internal/core/api.rs, internal/core/item_rendering.rs, internal/core/window.rs, internal/renderers/femtovg/lib.rs, internal/renderers/skia/lib.rs, tests/manual/windowattributes/Cargo.toml, tests/manual/windowattributes/main.rs
On Wayland hiding a window requires destroying the surface, which
means destroying the winit window as well as the underlying graphics
surface. The latter is tricky as we have to keep the renderer around,
as our WindowAdapter trait's `renderer()` function returns a `&dyn
Renderer` and that also has to work without a window (to obtain text
metrics).
Fixes [#4225](https://github.com/slint-ui/slint/issues/4225)
=> Fix slint::Window::hide() on Wayland with winit

internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/llr/item_tree.rs, internal/compiler/llr/lower_to_item_tree.rs
A `Rectangle { clip: true; }` will generate an intermediate `Clip` rectangle, which certainly has no debug info.
The check whether debug info is present or not should not be done on a per-element level but it can be done on the level of the compilation unit.
=> testing api: Avoid bogus warnings about missing debug info

internal/compiler/passes/inlining.rs, tests/cases/children/children_placeholder_three_levels.slint
If a component doesn't have a @children, but inherit from a builtin element, we shouldn't take the @children from the children
=> Fix insersion into a child `@children` when it shouldn't

api/cpp/CMakeLists.txt, api/cpp/Cargo.toml, api/cpp/cbindgen.rs, api/cpp/cmake/SlintMacro.cmake, api/cpp/docs/cmake.md, xtask/src/cppdocs.rs
While we haven't settled on the debug info feature and are merely controlling it via environment variable, setting that can be very hard - especially when using Yocto.
To make life easier, let's do in C++ what we can't easily do for Rust but would like to:
When enabling system testing, automatically emit the necessary debug info, by setting the environment variable when calling the compiler.
This is done by adding SLINT_ENABLED_FEATURES and SLINT_DISABLED_FEATURES properties
on the Slint::Slint target that - as lists - export the list of features and their status.
This way we can compile Slint in once place and safely in the CMake code running in application
scope check about the available features.
=> C++: Make the system testing feature automatically enable debug info

internal/compiler/passes/inlining.rs, internal/compiler/passes/lower_layout.rs
There is no longer a reason to prevent it.
=> Allow not inlining components that inherit from layout

internal/compiler/llr/lower_to_item_tree.rs
(eg: NativeStyleMetrics)
We would consider the property constant and inline them as their default value
Fix regression from 6687995c36692fa3743ef71d5e460ec4e1928aae
=> Fix appliying property from a builtin global

CHANGELOG.md, internal/backends/winit/event_loop.rs, internal/backends/winit/lib.rs, internal/backends/winit/winitwindowadapter.rs
I noticed that #3066 has been a long-standing issue and fixing it would grant some functionality I want to implement in my current project (file drag-and-drop handling), so I decided to implement it.
I initially considered adding a hook element to the `Backend` but I found it very inconvenient to work with that way, mostly because I could only get it working if the closure had to be `Clone` which limits what you can do. It could still be provided this way if that's desired.
Instead, I added a method to the `WinitWindowAccessor` trait that allows you to install a filter callback. Right now, the callback only gets a `&winit::event::WindowEvent`. I've considered providing a `&winit::window::Window` or `&slint::Window` also, but I'm not sure if either would be useful. The callback can then …
=> Winit window event filter

CHANGELOG.md, api/rs/slint/lib.rs, internal/backends/qt/qt_window.rs, internal/backends/testing/slint_systest.proto, internal/backends/testing/systest.rs, internal/core/api.rs, internal/core/graphics/image.rs, internal/core/renderer.rs, internal/core/software_renderer.rs, internal/renderers/femtovg/lib.rs, internal/renderers/skia/lib.rs
Use SharedPixelBuffer as return value for take_snapshot() and provide counter-parts to from_rgb* in Image as to_rgb*
=> API Review: Remove SharedImageBuffer from public API and rename Window::grab_window() to take_snapshot()

internal/backends/testing/Cargo.toml, internal/backends/testing/systest.rs, internal/core/items.rs
Deriving strum::EnumIter on a publicly exposed enum (like PointerEventButton) implies visibility into types that strum declares. This was added just for testing in systest and can be solved differently.
Amends a1857e6154c8a8aae569564e7c5f5151aa8c08dc
=> API review: Remove accidental public strum dependency

internal/backends/winit/renderer/femtovg.rs, internal/renderers/femtovg/lib.rs
This could've been `set_opengl_context` taking an `Option`, but it turns out that makes for an awkward interface when wanting to pass None, because that also then requires a dummy type for the OpenGL context even though none is wanted.
=> API Review: Remove suspend/resume related functions from FemtoVG renderer

api/cpp/esp-idf/slint/README.md, api/cpp/esp-idf/slint/include/slint-esp.h, api/cpp/esp-idf/slint/src/slint-esp.cpp, examples/carousel/esp-idf/main.cpp, examples/printerdemo_mcu/esp-idf/main/main.cpp
esp_lcd_touch_handle_t is a pointer, so might as well treat it like one.
Also default initialize the panel pointer.
=> API review (esp-idf): Replace the use of std::optional<esp_lcd_touch_handle_t> with esp_lcd_touch_handle_t directly

api/cpp/include/slint_window.h, examples/gallery/ui/pages/controls_page.slint, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/llr/item_tree.rs, internal/compiler/llr/lower_expression.rs, internal/compiler/llr/lower_to_item_tree.rs, internal/compiler/llr/optim_passes/count_property_use.rs, internal/compiler/llr/pretty_print.rs, internal/compiler/passes/lower_popups.rs, internal/compiler/passes/materialize_fake_properties.rs, internal/compiler/widgets/cosmic-base/time-picker.slint, internal/compiler/widgets/cupertino-base/time-picker.slint, internal/compiler/widgets/fluent-base/time-picker.slint, internal/compiler/widgets/material-base/time-picker.slint, internal/compiler/widgets/qt/time-picker.slint, internal/interpreter/dynamic_item_tree.rs, internal/interpreter/eval.rs, tests/cases/elements/popupwindow_context.slint
This allows positioning popup windows in a way that takes their width/height into account.
=> Add support for using own properties in PopupWindow's x and y properties

docs/_templates/embedded-tutorials.md
A draft template to reuse when rolling out tutorials for using Slint on Embedded devices.
=> Start a draft of an embedded tutorial template

docs/reference/src/language/widgets/datepicker.md, docs/reference/src/language/widgets/timepicker.md
- Remove `struct Date` and `struct Time` from the widgets side bar
- Move it to the bottom of each page
- Link to it from the respective properties
=> API review: clean up Time/Date struct docs

internal/interpreter/dynamic_item_tree.rs
It turns out that for repeated elements, we set root_weak to self_weak, instead of the root we obtain from the parent instance. Fix this by moving the code to initialize parent_item_tree_offset to before we try to use it (via parent_instance) to initialize root_weak.
=> Fix dynamic accessibility tree updates not working in the interpreter

.github/workflows/ci.yaml, .github/workflows/nightly_snapshot.yaml, .github/workflows/wasm_demos.yaml
Build only the gallery for WASM for the CI, to fan out wasm related issues. Build the remaining demos and artefacts in the nightly snapshot.
=> Speed up regular CI runs

api/python/README.md, api/python/lib.rs, api/python/slint/__init__.py, api/python/tests/test_instance.py, api/python/value.rs, examples/memory/main.py, examples/printerdemo/python/main.py
When reading, create the local equivalent of a dataclass, so that access doesn't require ["foo"] key syntax.
Also implement the copy protocol, so that we can safely make clones of the references returned by the ListModel.
=> Python: Improve Struct mapping

tools/lsp/ui/components/expandable-listview.slint
Since the category items have different heights, the extrapolation of the listview to compute the correct scrollbar height will always be off, unless listview instantiated all items.
So let's do that by hand and use a ScrollView.
=> Fix flicker in the component list in design mode

api/cpp/docs/conf.py, api/cpp/docs/generated_code.md, api/node/cover.md, api/python/README.md, api/rs/slint/lib.rs
=> Document behaviour of globals when exporting multiple components

docs/reference/src/language/builtins/callbacks.md
Based on [this chat discussion](https://chat.slint.dev/public/pl/pmqbb5k8gb85jr64o8z8uieg1r) I wanted to clarify that `init` is a bit special as a callback.
Please take a look!
=> Clarify that init callback can't be used from backend code and why

docs/reference/src/language/syntax/modules.md
A reference to C++ was missing and the default example with `mylibrary` would erroneously mix a file import with a directory mapping.
=> Improve library docs

api/node/__test__/api.spec.mts, api/node/index.ts
before
```
error: Uncaught (in promise) Error: Could not compile ui/appwindow.slint
at loadSlint (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/slint-ui/1.7.0/index.js:464:19)
at Module.loadFile (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/slint-ui/1.7.0/index.js:644:12)
at file:///home/mrcool/dev/deno/lab/memory/src/main.ts:3:23
```
after
```
error: Uncaught (in promise) Error: Could not compile ui/appwindow.slint
Diagnostics:
[ui/appwindow.slint:4:5] Unknown type MemoryTile
at loadSlint (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/slint-ui/1.7.0/index.js:468:19)
at Module.loadFile (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/slint-ui/1.7.0/index.js:648:12)
at file:///home/mrcool/dev/deno/lab/memory/src/main.ts:3:23
```
=> js: show diagnostics when erroring

internal/compiler/parser.rs, tools/lsp/preview/drop_location.rs
We were trying to convert a node to a wrong kind of node. Then of course it didn't have the expected children
In debug mode you'd have
```
assertion `left == right` failed
left: SubElement
right: Component
```
from the debug_assert! in `$Node::from`
I changed the call to `.into` to a call to `$Node::new` that return an option.
Also made the debug_assert into an assert and added track_caller so such problem are easier to debug in the future. (Retrospectively, we probably shouldn't have derived From for $Node)
Fix #5642
The change contains no tests because the is_recursive_inclusion function is currently not tested and would need some effort to create a test
=> Live-preview: Prospective fix for panic when moving a component

internal/backends/winit/event_loop.rs
This is a workaround for the compositor on WSL tending to crash. Unfortunately we can't just try to create an event loop with x11 first and then re-try with wayland, winit doesn't allow that. So just avoid wayland for now.
The long term solution #5667
Fixes #5657
=> winit: Prefer X11 over Wayland when running in WSL

internal/compiler/generator/rust.rs
Strangely I wasn't able to reproduce the problem in a test, and we already have tests that have enums which are not fully used.
Fix #5661
=> Rust: Ignore dead code warning for unused enums

internal/compiler/widgets/cosmic-base/combobox.slint, internal/compiler/widgets/cupertino-base/combobox.slint, internal/compiler/widgets/fluent-base/combobox.slint, internal/compiler/widgets/material-base/combobox.slint, internal/compiler/widgets/qt/combobox.slint
Fix #5646
Qt is a bit more involved since it always put scrollbar if there is a ScrollArea and we can't easily know the size to which make the popup. That's why it needs two popups
=> Combobox: Fix ComboBox having a too big popup when it has less than 6 items

tools/lsp/common.rs, tools/lsp/language.rs, tools/lsp/main.rs, tools/lsp/wasm_main.rs
This ensure there is no typo in the method name
=> LSP: refactor send_notification to use the Notification trait

docs/reference/src/language/syntax/types.md, internal/compiler/builtin_macros.rs, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, tests/cases/types/int_conversion.slint
Fix conversion to from float to int
Round the value.
The previous behavior is that
- For the interpreter, we were rounding (same as new behavior)
- for Rust and C++ we were truncating, unless the properties were
inlined and then we were keeping it as float
=> Fix conversion to int

api/cpp/esp-idf/slint/README.md
- `touch_handle` can't be initialized with an optional anymore, it is a pointer.
- Take the opportunity to actually initialize the touch handle.
- `bsp/display.h` for the box3 fails to compiled if it is included before `bsp/esp-bsp.h`
=> esp-idf README: fix compilation of the code sample

tools/lsp/common/component_catalog.rs, tools/lsp/common/rename_component.rs, tools/lsp/common/test.rs, tools/lsp/language/completion.rs
(Noticed that the LSP tried to auto-complete the `toggle-checked` function from the `Switch` while making a presentation, but that function shouldn't have been in the auto-completion list)
=> LSP: don't auto-complete functions or private properties for bindings

.github/workflows/nightly_snapshot.yaml, examples/weather-demo/Cargo.toml, examples/weather-demo/README.md, examples/weather-demo/index.html, examples/weather-demo/src/app_main.rs
I compared my `Cargo.toml` file with the working `todo` app's `Cargo.toml` file, and it seems changing `crate-type = ["cdylib"]` to `crate-type = ["lib", "cdylib"]` fixes the problem. At least on my side :wink:
I also renamed the package and internal names from rusty-weather to weather-demo. I think it's better to keep the name the same as the directory name to avoid further confusion. Sorry for the initial confusion and issues it caused!
=> Fix Weather Demo apk

internal/backends/linuxkms/display/gbmdisplay.rs, internal/backends/linuxkms/renderer/femtovg.rs, internal/backends/linuxkms/renderer/skia.rs, internal/renderers/skia/opengl_surface.rs
Combining an EGL config with EGL_ALPHA_SIZE == 8 with an Xrgb8888 surface yields a bad match on eglCreateWindowSurface. That's fair, and we should accomodate for that by avoiding such EGL configs.
=> Fix GBM rendering on mali EGL drivers

docs/reference/src/quickstart/getting_started.md
Fixed a couple minor typos within the getting started docs. (Not much, but honest work haha)
=> Typos-Fix: Getting Started Docs

docs/reference/src/language/builtins/elements.md
My assumption from reading the docs was that the `StandardButton`s delegated to the root and that the generated callbacks in the root were to facilitate that behavior.
=> Clarify that generated <kind>_clicked callbacks are aliases

internal/core/api.rs
We implemented it for the required public FnMut signature.
=> doc: hide internal RenderingNotifier trait

examples/printerdemo_mcu/zephyr/README.md, examples/printerdemo_mcu/zephyr/src/slint-zephyr.cpp
The Zephyr POSIX architecture used by the native simulator is unable to interrupt a busy thread [1]. Therefore we must sleep even when there are active animations to allow other threads to progress, otherwise we end up in an infinite loop. This limitation does not apply to real hardware, where we can simply continue the event loop.
[1] https://docs.zephyrproject.org/3.7.0/boards/native/doc/arch_soc.html#important-limitations
=> Zephyr: active animations only cause a sleep on the native simulator

internal/compiler/generator/rust.rs, internal/core/item_tree.rs, internal/renderers/skia/textlayout.rs
Replaces usage of `core::{usize, f32}::*` constants with the equivalent associated constants to resolve lints from `#![warn(deprecated_in_future)]`.
=> Use associated constants on number types

api/rs/slint/docs.rs
The actual generated components aren't Send/Sync either.
Fixes #5742
=> Mark SampleComponent in rust docs as !Send and !Sync

internal/backends/testing/search_api.rs
The compiler normalizes `the_element` to `the-element`, so we also need to normalize that behind our API.
=> Testing: Fix querying for elements by id when using `_`

docs/reference/src/language/syntax/types.md
Just copy the sentences from the rust docs for slint::Color
Closes #5753
=> brighter/darker: Add docs that specify that we go in the HSV color space

examples/printerdemo/ui/common.slint, examples/printerdemo/ui/images/page_selection.svg, examples/printerdemo/ui/printerdemo.slint
- The general page change animation is more subtle. It's now a combo of fade in and move. As opposed to a full page slide.
- Fixes the position of the sidebar selection SVG to remove a broken curve.
- The SVG also has been tweaked to make it symmetrical and remove the lopsided bulge it had. 
- The sidebar buttons touch area covers the whole space they represent, as opposed to just being the same size as the icon.
- The code has been simplified a bit. Layout values are moved to DemoPalette and animation values are based on reusable variables to make changing the timings easier.
=> UX enhance the Printerdemo primary screen

internal/backends/android-activity/androidwindowadapter.rs
We observe, in issue #5699 that the call to `AndroidAppWaker::wake` doesn't always result in a `PollEvent::Wake` event. So to work around that, always process event from any event we receive so that any timeout or input event would make sure event gets processed.
Closes #5699
Note: I have no idea why we don't receive the event. the bug is not fixed as there may not be any other event for a long time, but it makes it less likely to cause problems.
=> Android: workaround PollEvent::Wake not being received

tools/lsp/common.rs, tools/lsp/language.rs, tools/lsp/main.rs, tools/lsp/preview.rs, tools/lsp/preview/native.rs, tools/lsp/preview/wasm.rs, tools/lsp/wasm_main.rs
Instead of panicking the whole server
Fixes https://github.com/slint-ui/slint/issues/204
(Note that this issue is also talking about fallback to the wasm UI in this case, but we don't do that in this patch yet)
The two commit are independent. At first i thought i'd need the first commit, but it turns out it is difficult to send the error back to the LSP thread before answering the request, so I made it with a notification instead.
=> LSP: Report error through the LSP when the preview can't open 

examples/printerdemo/ui/common.slint, examples/printerdemo/ui/home_page.slint, examples/printerdemo/ui/printer_queue.slint, examples/printerdemo/ui/printerdemo.slint, examples/printerdemo_mcu/ui/printer_queue.slint
There are many different ways this could be done.
Designers work with a limited and reusable color palette. There is no 100% standard, but pretty much of it has become common convention. 
The same colors are hardcoded or duplicated across the demo. So this pr also attempts to reuse as much of the core palette as possible.
=> Give printerdemo a clear palette

.github/workflows/ci.yaml, internal/compiler/generator/rust.rs, internal/interpreter/api.rs
In rust, use f32 instead of f64 for arithmetic comparison. In the interpreter, use approx_eq
The test is failling in nightly because of precision change in `log`. By using f32, it actually should work
Also Revert "Disable builds with nightly Rust temporarily" This reverts commit 4afc3a2e84d422ced978368cb2654d7fc19b1615.
Fixes #5722
=> Use less precision when comparing vaue in slint language

tools/lsp/preview/native.rs
This makes the entire thing so much more responsive as most events are just ignored when the window is closed.
=> live-preview: Take note that the UI was opened

api/rs/slint/Cargo.toml, api/rs/slint/tests/tokio.rs, api/rs/slint/tests/tokio_block_in_place.rs, internal/core/Cargo.toml, internal/core/future.rs
Improve documented workaround for Tokio integration
Document the two constraints of using Tokio futures in Slint, and how to work around them.
Fixes #5733
=> Improve documented workaround for Tokio integration

internal/compiler/parser.rs, tools/lsp/common.rs, tools/lsp/preview.rs, tools/lsp/preview/drop_location.rs, tools/lsp/preview/properties.rs
Now that the properties are only used in the live preview, we can simplify the code a bit.
This gets rid of some sanity checks in the code path as well, which in turn should fix #5696.
Fixes: #5696
=> live-preview: Simplify code setting properties

internal/compiler/generator/rust.rs, tests/cases/models/delete_from_clicked.slint
This can happen if somehow the parent get destroyed while a binding is running. This is issue #3464
This is enough to fix #5698
=> Rust generated code: handle the case if the parent is destroyed in a binding

.github/workflows/nightly_tests.yaml
Fixes #5812 
The simulator build requires the nightly rust toolchain, and occasionally fails due to upstream changes to the nightly toolchain.
The hardware build does not require the nightly rust toolchain, but still fails due to upstream nightly toolchain changes.
Move the hardware build to the stable toolchain so that it is not broken unnecessarily.
Additionally, turn off `fail-fast` so that the nightly failures don't affect the stable builds.
The hardware build now passes: https://github.com/0x6e/slint/actions/runs/10322553438
=> Zephyr: CI uses appropriate toolchain for the target

internal/compiler/passes/embed_glyphs.rs
The code at https://github.com/slint-ui/slint/blob/bcc5327052c75b9b3e1dcb3571657b9b802c9d80/internal/common/sharedfontdb.rs#L14-L21
prevents the field `fontconfig_fallback_families` from being created on Android. But the code in `embed_glyphs.rs` attempts to access this field even on Android. This leads to a build failure.
=> Fix broken Android build caused by missing font field

docs/reference/src/language/syntax/types.md, internal/compiler/builtin_macros.rs, internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/interpreter/eval.rs, tests/cases/types/int_conversion.slint
- Make sure that in Rust and C++ we also truncate if the properties are inlined
- Change the interpreter to truncate
This is a redo of commit f5d003d but truncate instead of round
fixes #5689
=> Make conversion from float to int property truncate

editors/vscode/package.json, editors/vscode/src/browser-lsp-worker.ts, editors/vscode/src/common.ts, editors/vscode/src/lsp_commands.ts, editors/vscode/src/tsconfig.json, editors/vscode/tsconfig.default.json, editors/vscode/tsconfig.json, tools/slintpad/src/tsconfig.json
Theyre are no more shared files, so move the files into vscode and set up a syntax check over there.
That was not possible before as the typescript
compiler would error out on the shared files being outside its root directory.
Fix the errors and warnings the typescript compiler noticed while at it.
=> slintpad/vscode: Get rid of the shared files

internal/core/window.rs, tests/cases/focus/focus_change_event.slint, tests/cases/focus/keyboard_focus.slint
(eg: alt+tab or control+tab)
Failed attempt at fixing #5823
This doesn't fixes it because the problem is that the key event are forwareded as syntetic events when we gain focus, and they are not in a order that allow to detect alt+tab
=> Tab with modifier shouldn't change focus

api/python/Cargo.toml, api/python/README.md, api/python/interpreter.rs, api/python/slint/__init__.py, api/python/tests/test_load_file.py, api/python/tests/test_load_file.slint, api/python/value.rs, examples/printerdemo/python/main.py, internal/compiler/object_tree.rs, internal/interpreter/Cargo.toml, internal/interpreter/api.rs, internal/interpreter/dynamic_item_tree.rs
Structs declared and exported in Slint are now available in the module namespace with a constructor.
Fixes #5708
=> Python: Expose Slint structs

internal/core/item_tree.rs
Popups may have normal `Item`s as parrent, while all the other
components always have a `DynamicTree` as a parent. So do not
panic when some component ends up with an `Item` as a parent.
Just return `None` instead of panicing.
We probably need to make the focus-handling more aware of
popups eventually, but this stops the panics.
Fixes: #5826, #5830
=> core: Do not panic when popups try to find their parent

tools/lsp/preview.rs, tools/lsp/preview/ui.rs, tools/lsp/ui/api.slint
We apparently do not want history-based navigation, so remove the code supporting that again.
=> live-preview: Remove history navigation

CHANGELOG.md, internal/compiler/widgets/cosmic-base/textedit.slint, internal/compiler/widgets/fluent-base/textedit.slint, internal/compiler/widgets/material-base/textedit.slint, internal/compiler/widgets/qt/textedit.slint, tests/cases/widgets/textedit.slint
=> Fix `TextEdit` not invoking `edited` callbacks

tools/lsp/preview.rs, tools/lsp/ui/api.slint, tools/lsp/ui/views/preview-view.slint
Force the preview to preferred size when explicitly asking to preview something.
=> live-preview: Use preferred size when requesting preview

docs/resources/slint-docs-highlight.html
- the `pre` that needs the `rust` class is not the parent anymore
- remove the hljs class bacause it adds a background that we don't want (Fixes #5787)
- add a few missing keywords
=> rust docs: fix syntax highlighting of slint code

internal/compiler/typeloader.rs
This allow to preview/edit the widgets with the lsp's preview when the experimental mode is enabled
=> compiler: enable use of internal features when the experimental flag is set

internal/compiler/generator/rust.rs
code like so:
```slint
callback foo();
if true : Button {
clicked => {
true ? foo() : foo();
}
}
```
the code like foo() use the `option.map()`  to get to the parent, but then it needs to still be wrapped in a `{...}` to convert that to a `()` expression
Fixes #5883
=> Fixes rust generated code when taking expression of void callback

api/rs/slint/lib.rs, api/rs/slint/tests/spawn_local.rs, internal/backends/selector/lib.rs, internal/backends/testing/search_api.rs, internal/backends/testing/systest.rs, internal/core/animations.rs, internal/core/context.rs, internal/core/future.rs, internal/core/items/text.rs, internal/core/lib.rs, internal/core/platform.rs, internal/core/tests.rs, internal/core/window.rs, internal/interpreter/api.rs, tools/lsp/preview/native.rs, tools/lsp/preview/wasm.rs, tools/viewer/main.rs
Take the opportunity to refactor a bit the way the global platform or context is accessed
Fixes: #5871
=> spawn_local: initialize the platform if not initialized before the call

editors/vscode/.npmrc
PNPM symlinks the node_modules and this is probably what confuses VSIX. This fixes the issue by letting PNPM install the npm dependencies by copying the files.
I will look a bit deeper as a separate task as the error message suggests all the dev dependencies are being packaged into the VSCode extension and probably contribute a non significant amount to the package size?
=> Fix Vscode publish failing due to PNPM

.github/workflows/cpp_package.yaml, .github/workflows/nightly_snapshot.yaml, api/cpp/CMakeLists.txt
This includes xtensa for s3, esp riscv targets, as well as thumbv7 for STM32.
=> Build binary MCU packages as tarballs

editors/vscode/src/browser-lsp-worker.ts
We need to load slint_lsp_wasm_bg.wasm for it to load the LSP webassembly
This was removed by mistake in commit 1639274486e5540b394c7bdb1c76ab3a99045ce6
=> Fix web vscode extension

examples/printerdemo_mcu/esp-idf/main/CMakeLists.txt
Depending on just the bsp in the yaml file is sufficient for linkage. (we use the same in the other esp-idf projects)
=> Remove unnecesary esp-idf component dependency

editors/vscode/src/browser.ts, editors/vscode/src/extension.ts
It is used to show the output of `debug()`.
User don't find this output if it doesn't exist before there is any debug output. So make sure it always exist.
(Note: this is not for the browser version, since then we use console.log instead of the "Slint LSP" output from stderr)
=> vscode extension: make sure the "Slint LSP" output always exist

api/cpp/CMakeLists.txt
Freestanding implies the lack of windowing system presence and therefore the choice of say Cupertino when building on macOS is not good.
Fluent isn't quite a great choice right now either, as it's not very touch friendly, but it's a compromise :)
=> C++: For freestanding builds, default to the fluent style

tools/lsp/preview/native.rs
... without looking at the value in any way.
This is how everything else does it as well in Slint.
=> lsp: Turn on experimental features when env var exists

api/rs/slint/private_unstable_api.rs, internal/compiler/generator/rust.rs, internal/interpreter/eval.rs, tests/cases/types/string.slint
Because f64 has too much precision, so limit to f32 so that we don't have extra precision we don't need and would be wrong as all our float as in f32
=> Use f32 for float-to-string conversion

internal/compiler/generator/cpp.rs, internal/compiler/generator/rust.rs, internal/compiler/llr.rs, internal/compiler/llr/expression.rs, internal/compiler/llr/item_tree.rs, internal/compiler/llr/optim_passes/count_property_use.rs, internal/compiler/llr/optim_passes/inline_expressions.rs
If a property is only used once, we can inline it with a bigger threshold.
But this require to first compute the use, and then do the inlining while adjusting the usages
=> Optimization: improve expression inlining

tools/lsp/common/component_catalog.rs, tools/lsp/common/document_cache.rs, tools/lsp/common/rename_component.rs, tools/lsp/language.rs, tools/lsp/language/completion.rs, tools/lsp/language/formatting.rs, tools/lsp/language/goto.rs, tools/lsp/main.rs, tools/lsp/preview.rs, tools/lsp/preview/drop_location.rs, tools/lsp/preview/properties.rs, tools/lsp/preview/ui.rs, tools/lsp/preview/wasm.rs, tools/lsp/ui/api.slint, tools/lsp/util.rs
The Properties are no longer sent out straight to the editor, so we do not need to convert our internal `TextRange` and `TextSize` to `lsp_types::Range` and `lsp_types::Position`.
We are noweadys turning that straight back into offsets -- which is just another name for `TextSize` (or pairs of offsets).
=> live-preview: Use TextRange and TextSize in property information

editors/vscode/src/quick_picks.ts
This always asks for the user to select a location for the project.
If VScode is already in a folder it will default to that location.
Then at the end the user is asked if they wish to open the project in a new window, the current window or current window, but new workspace.
Finally I tweaked the Typescript to be less hardcoded strings with potential errors from typos.
=> vscode: Better options on project location

.github/dependabot.yml
The latest node types will always be a future beta or version that is not under LTS. According to this [issue](https://github.com/dependabot/dependabot-core/issues/2247) there is no solution. So the simplest one is to ignore it and just manually update the types as and when needed.
=> Dependabot should ignore @types/node

editors/vscode/esbuild.js, editors/vscode/package.json
Follow basically the steps of https://code.visualstudio.com/api/working-with-extensions/bundling-extension#using-esbuild to minify the JS and omit source maps.
=> Reduce size of VS code extension production builds

.github/workflows/ci.yaml
Also synergises with Dependabot so any PR's the bot creates will be tested by this. Currently the PR will look okay even if it breaks the project.
=> Lint and build the VScode extension as a CI check

editors/vscode/src/extension.ts, editors/vscode/telemetry.json, tools/lsp/main.rs
We write the panic message in a file to communicate with the vscode extension
=> vscode: report LSP panic as telemetry error

tools/lsp/language/completion.rs
Fixes https://github.com/slint-ui/slint/issues/5966
The previous behavior, as described in the issue is: (where `|` is the cursor)
```slint
Rectangle {
back|
}
```
and autocomplete background, it will insert
```slint
Rectangle {
background: |;
}
```
This commit changes to not add the semicolon, so the result will be
```slint
Rectangle {
background: |
}
```
=> LSP: don't insert semicolon after completing a property

tools/lsp/ui/views/property-view.slint
Just remove a bit of code that needs to go later anyway to get it out of the way.
=> live-preview: Remove splitter from PropertyEditor

tools/lsp/preview.rs, tools/lsp/preview/ui.rs
We need an ElementRcNode (based on the AST from the document cache!), so that we can look up types in the Document's local type registry (LATER!)
=> live-preview: Pass a element node to ui when converting property info

.github/workflows/ci.yaml
Don't build slint-lsp.
(there's still the wasm build though)
=> Speed up vsce CI step

internal/compiler/passes/inlining.rs, internal/compiler/passes/unique_id.rs, tests/cases/elements/timer.slint
We need to give unique name to optimized item as well, otherwise the properties ends up the same.
Also fix the optimized element and timer when inlining
Fixes #5977
Fixes #5976
=> Timer: fix timer when two timers have the same id

internal/compiler/parser.rs, tools/lsp/preview.rs, tools/lsp/preview/properties.rs, tools/lsp/preview/ui.rs, tools/lsp/ui/api.slint, tools/lsp/ui/views/property-view.slint
A big PR, but a lot of this is testing :-)
* More type-safe API (although it is still not *nice*)
* Also accept locally defined enums. This used to work only with "our" enums...
* Tests!!!
This PR also does *babysteps* towards changing the UI of the property editor, but it is 98% about the backend, and only the parts we had covered before. I still need to add in length, angle, ...  That's next.
The idea is to have something in place for Florian to play with tomorrow.
=> Improve conversion of property info for the UI

internal/core/api.rs
Unfortunately, we can't link because it is defined in a different crate
Fixes #5988
=> Reference slint::spawn_local from the invoke_from_event_loop docs

tools/lsp/Cargo.toml, tools/lsp/main.rs, tools/lsp/preview/native.rs
We need to do the platform init only when we intend to soon thereafter show a window.
Re-added a Quit item that merely hides the UI, so CMD+Q kind of works for convenience.
=> live-preview on macOS: Fix ever bouncing icon and re-add a quit item

internal/compiler/builtin_macros.rs
=> Change `debug()` separator from `, ` to ` `.

internal/compiler/langtype.rs, internal/compiler/object_tree.rs, internal/compiler/tests/syntax/basic/unknown_item.slint, internal/compiler/tests/syntax/elements/tabwidget3.slint, internal/compiler/tests/syntax/imports/bug_2719.slint, internal/compiler/tests/syntax/imports/cyclic_import.slint, internal/compiler/tests/syntax/imports/invalid_export.slint, internal/compiler/tests/typeloader/incpath/should_fail.slint, internal/compiler/tests/typeloader/incpath/should_fail2.slint, internal/compiler/typeregister.rs
eg, don't report an error for each callback or animation or changed event that the the property doesn't exist or such.
Also reword the message when an element doesn't exist. Use "element" rather than "type" as it is more accurate.
=> Avid reporting further error when an element is misspelled

tools/lsp/ui/views/property-view.slint
For beauty-reasons we no longer report `Empty` though and replace that with `""`. This prevents the property editor from showing a UI: The `type-name` field being empty was abused to indicate that no data is available -- we do not have options in Slint :-/
Replace that test with the length of the model holding the properties.
We assume we got no data when that model is empty... which is probably a safer bet for "no property data availabel" than the `type-name` field.
=> live-preview: Show properties for `Empty`

tools/lsp/preview.rs, tools/lsp/preview/ui.rs, tools/lsp/ui/api.slint, tools/lsp/ui/views/property-view.slint
* Remove commented out code
* Add setter for color property changes
* Remove setters again that are not too helpful (where it is trivial to generate the code on the slint side). I wanted to have one setter per type, but that is getting out of hand ;-)
* Improve the test functionality to always test the same property `test1` in case there are several.
* Make @tr editable from the UI by making sure we can pass the data intact to the UI and generate correct code when we come back.
=> property editor: Query property related fixes

.github/workflows/ci.yaml
Place all CI runs into groups (ideally one per PR), and cancel in-progress runs if a new one is triggered.
=> CI: cancel earlier CI runs when a new version for a PR is pushed

internal/renderers/skia/Cargo.toml, internal/renderers/skia/metal_surface.rs, internal/renderers/skia/vulkan_surface.rs
The logic for creating the `CAMetalLayer` if it doesn't exist is complex, and currently Slint is doing it wrong and prevents Winit from scheduling redraw events at the correct time. I have abstracted this away into [`raw-window-metal`](https://docs.rs/raw-window-metal/), it works by creating a layer, and inserting that as a sublayer. The bounds and scale factor are then kept in-sync with an observer, ensuring smooth resizing. This is also important for iOS support, since overwriting the layer, as currently done, isn't possible there.
See also corresponding [PR to `wgpu`](https://github.com/gfx-rs/wgpu/pull/6210), [PR to `ash`](https://github.com/ash-rs/ash/pull/939) and [PR to `vulkano`](https://github.com/vulkano-rs/vulkano/pull/2561) for more details and reasoning.
I'm pretty sure that …
=> Use `raw-window-metal` to do layer creation

internal/compiler/passes/compile_paths.rs, tests/cases/elements/path.slint
We need to keep the ElementRc around with its properties so that accessing them doesn't panic later
=> Path: fix panic when accessing properties on sub commands

tools/lsp/common.rs, tools/lsp/common/document_cache.rs, tools/lsp/common/text_edit.rs, tools/lsp/language.rs, tools/lsp/language/completion.rs, tools/lsp/language/goto.rs, tools/lsp/language/hover.rs, tools/lsp/preview.rs, tools/lsp/preview/drop_location.rs, tools/lsp/preview/element_selection.rs, tools/lsp/preview/ui.rs
... in the second patch, which is pretty small.
The first one got out of hand: I wanted to change one occurance of u32 to TextSize and then ended doing that all over the place. No behavior change is intended in that first change :-)
=> live-preview: Fix layouts being shown in the wrong color when selecting something in the editor

tools/lsp/preview.rs, tools/lsp/preview/properties.rs, tools/lsp/preview/ui.rs, tools/lsp/ui/api.slint, tools/lsp/ui/views/header-view.slint
So printerdemo is without the dropdown (as it is useless there), while people working on the desktop using the standard widgets can still easily switch and check their work in different styles.
=> live-preview: Only show style dropdown when using std-widgets

internal/renderers/skia/Cargo.toml, internal/renderers/skia/d3d_surface.rs
This updates Skia to Milestone 129. See
https://github.com/rust-skia/rust-skia/releases/tag/0.78.0 for additional details.
=> Update Skia to 0.78

internal/compiler/llr/lower_to_item_tree.rs, internal/compiler/llr/pretty_print.rs, tests/cases/bindings/two_way_global.slint
We need to skip the generation of the local property so it directly forward to the alias in the public property
Fixes #5855
ChangeLog: Fixed generated getter and setter of alias properties in globals
=> Fix generated setter and getter of public property alias in globals

tools/lsp/preview/drop_location.rs, tools/lsp/preview/element_selection.rs
We want to disable the auto-selection of the main node, so we can no longer leave that out.
=> live-preview: Element selection polish/unnecessary code removal

tools/lsp/ui/components/resizer.slint, tools/lsp/ui/views/preview-view.slint
... by rendering the elements as transparent. They are still there and work, so you can still resize, but you still get a better view of your UI.
We still draw a border around the UI, just to show where it ends and the background begins, but that is purely decorative :-)
I am not totally happy with this: It still sets mouse cursors in the area that should actually be controlled by the UI and overlays its own touchareas around the border of the UI, stealing a few pixels from the interactive area of the UI.
=> live-preview: Hide resize elements in interactive mode

.github/workflows/nightly_snapshot.yaml, .github/workflows/nightly_tests.yaml, .github/workflows/upgrade_version.yaml, .github/workflows/upload_esp_idf_component.yaml, api/cpp/esp-idf/slint/CMakeLists.txt, api/cpp/esp-idf/slint/README.md, api/cpp/esp-idf/slint/cmake/FindSlint.cmake, examples/carousel/esp-idf/s2-kaluga-kit/CMakeLists.txt, examples/carousel/esp-idf/s3-box/CMakeLists.txt, examples/carousel/esp-idf/s3-usb-otg/CMakeLists.txt, examples/printerdemo_mcu/esp-idf/CMakeLists.txt
Run the nightly esp-idf test against the esp-idf slint nightly binaries, after creating them. The snapshot is run earlier as well then, so that the tests don't "leak" into the morning working hours.
cc #6057
=> esp-idf: Add support for using pre-built binaries

.github/workflows/nightly_snapshot.yaml
This should be done before the release and the job that tries to download the binaries from the untagged release won't work anyway.
=> CI: don't run the nightly tests when creating a release

internal/compiler/passes/default_geometry.rs, tests/cases/issues/issue_4163_flickable_parent_percent.slint
The viewport of a flickable is of ElementType::Native, and `lookup_property` don't query the builtin reserved properties in that case.
This commit fix the assert by allowing Type::Invalid as well.
Fixes #4163
=> Fix compiler panic when using `%` size in a flickable

.github/workflows/ci.yaml
With Rust 1.81 the test harness somehow requires a bigger stack than with earlier versions, which is a problem as threads besides the main thread default to a smaller stack on Windows. This is worked around by running the harness in release. The node.js bindings are still built as debug build, this harness merely runs nodejs as a binary.
=> Re-enable Node.js tests on Windows

tools/lsp/Cargo.toml, tools/lsp/preview/ui.rs, tools/lsp/ui/api.slint, tools/lsp/ui/views/preview-view.slint
=> Use command instead of control for the status text when running on macOS

tools/lsp/preview/drop_location.rs
Otherwise we end up with values such as
```slint
SpinBox {
minimum: 0;
value: 42;
maximum: 100;
x: 94.44821px;
y: 108.07013px;
}
```
Which doesn't make much sense
=> live-preview: round the x and y properties when dropping

tools/lsp/common/component_catalog.rs
Timer is not really a visual element and it doesn't really make sense to put it on the library at this point
=> live-preview: Hide "Timer" from the component library

tools/lsp/ui/views/preview-view.slint
Always unselect the currently selected item when clicking onto the background around the previewed UI.
=> live-preview: Always unselect when clicking onto background

docs/_templates/nightly-release-notes.md, docs/_templates/release-artifacts.md
Loosely based on what was written for https://github.com/slint-ui/slint/discussions/5165
Notably python is missing.
=> Nightly template: add instruction on how to use "nightly" slint

tools/lsp/common.rs, tools/lsp/common/component_catalog.rs, tools/lsp/preview/drop_location.rs
This means that, when the parent is not a layout, the widgets are always dropped in the middle of the parent, and then one can place place it to the right position.
In particular, for widget that expends to the size of their parent by default, this does the right thing
Fixes #6098
=> live-preview: don't set `x` and `y` When dropping an element

tools/lsp/ui/views/preview-view.slint
Clip anything the previewed UI wants to draw outside of the area the previewed component claims to be using.
There are several reasons to do this:
* A window will clip the contained component
* Selection outside of the area taken up by the root component can not be selected or interacted with
* It is more obvious that you are doing something wrong when your UI is clipped. Before we happily showed the right thing in the preview and then failed hard when using that component.
=> live-preview: Clip drawing outside of ComponentContainer

tools/lsp/ui/views/preview-view.slint
Use the entire screen-space (minus borders) when the preferred size of a UI is 0 and we are asking to reset to the preferred size.
I was reluctant to implement this before as I think it is surprising to start with a huge size when the size info is most likely wrong... People typically render outside the component's area in that case.
Now that we clip away anything that is not inside the UI area, I think this is discoverable enough now: When resizing you will see the UI getting clipped after all.
The big size also avoids confusion when nothing shows up :-)
=> live-preview: Use the entire screen when preferred-size of a UI is 0

docs/reference/src/language/concepts/translations.md
While support for translations via gettext is currently not supported on Windows #3307 , it should be mentioned in the document.
Respect for [the comment](https://github.com/slint-ui/slint/issues/3307#issuecomment-2282195298)
=> docs: translation is not supported on Windows

examples/bash/sysinfo.slint, examples/energy-monitor/ui/widgets/list_view.slint, examples/todo-mvc/ui/widgets/selection_list_view.slint, internal/backends/qt/qt_accessible.rs, internal/backends/testing/slint_systest.proto, internal/backends/testing/systest.rs, internal/backends/winit/accesskit.rs, internal/common/enums.rs, internal/compiler/widgets/cosmic/components.slint, internal/compiler/widgets/cupertino/components.slint, internal/compiler/widgets/fluent/components.slint, internal/compiler/widgets/material/components.slint
Adds a new accessible role to expose list view items to assistive technologies. The standard list view is modified to take advantage of this. Some examples were also updated.
Fixes incorrect mapping of the list role for the AccessKit accessibility backend, as discussed a while back.
=> Introduce `AccessibleRole::ListItem`

internal/backends/winit/lib.rs, tools/lsp/preview/native.rs
Use a builder pattern, which also allows configuring the event loop builder.
Fixes #6103
=> winit: Clean up backend creation API

tools/lsp/ui/assets/background.svg, tools/lsp/ui/main.slint, tools/lsp/ui/views/preview-view.slint
Also have a slightly bigger preferred size by default when the previewed component is very small
What do you think?
=> live-preview: Use a checkerboard as the background

tools/lsp/fmt/fmt.rs
Don't change any whitespace before or after a comment. We were already preserving whitespaces after comment, do the same for whitespaces before comments
ChangeLog: formatter: don't change whitespaces or newlines before comments
=> fmt: Fix moving comments on the next line

api/rs/slint/tests/spawn_local.rs, internal/core/future.rs
Adds `is_finished` method to JoinHandle, the same functionality as here: https://docs.tvix.dev/rust/tokio/task/struct.JoinHandle.html#method.is_finished
=> Add `is_finished` to JoinHandle

tools/lsp/ui/views/preview-view.slint
Stop abusing the init callback, abuse the changed callback instead ;-)
Also merge the initial size calculation into one place. This fixes the preview showing the wrong sizes. It does introduce a bit of flicker though as the UI is rendered in the wrong state once and then immediently corrects itself.
That is annoying, but strictly better than staying in the wrong state till the user does something.
Closes: #5954
=> live-preview: Fix size being displayed wrongly
