slint-ui/slint

internal/backends/qt/qt_window.rs

Fixes #4500
When the WindowAdaptor is dropped, deleteLater is used on the C++ QWidget. On wayland, we still recieve a mouse exit event when the widget is about to be deleted. This calls a callback into the deleted Rust WindowAdaptor.

Qt: fix crash when closing the popup window on wayland

---

docs/reference/src/recipes/recipes.md

Fix language for the JavaScript callback example

Fix mentioned lang in docs

---

api/rs/build/lib.rs

If the generated code contains `"\""` and `format!("{}", ..)`, the latter would be corrupted because the code formatter rewrites `"{}"` as if it were a code block.

Fix rust codegen to skip over backslash-escaped character

---

api/python/tests/test_instance.py
api/python/value.rs

They map to Python dicts.
cc #4202

Python: Add support for converting structs

---

docs/reference/src/advanced/style.md

Document how to set the style from Node.js

---

internal/backends/winit/wasm_input_helper.rs
internal/core/items/text.rs

Amends fadcbdf726297418d19cf7f9d2573460435239f1

Fix build with --cfg=web_sys_unstable_apis

---

internal/core/window.rs

For native PopupWindow (qt backend) instead of relying on the destructor to close the popup (usually in the next event loop, if no one had a hold on any ComponentRc from the popup) do call set_visible(false) so the popup can be hidden immediatly
CC: https://github.com/slint-ui/slint/discussions/4532#discussioncomment-8366080

PopupWindow: explicitly call set_visible(false)

---

api/rs/slint/tests/partial_renderer.rs
internal/core/model.rs

Amend 48180919da69ea1991902f58de85f6e08344c3f4
That commit added the dependency, but did not reset the dirty flag, so it only worked once.
Fixes: #4538

ListView: Fix redraw when model changes

---

internal/core/software_renderer.rs

To reproduce, run the slide_puzzle with a SLINT_SCALE_FACTOR of 1.5 with the software renderer.
The bug is that some text are rendered at some location, with an offset of, say, 400.499999. And then the left and right side of the bounding rectangle may be rounded differently and we may get to draw images that are bigger than the glyph which cause panic. Fix that by ensuring we never do that.

Fix a panic in the software renderer when rendering text

---

api/node/__test__/js_value_conversion.spec.mts
api/node/index.ts

Also fix the function signature, which was wrong.

Node.js: Fix MapModel rowData() calling map function even if the source model returned undefined

---

CHANGELOG.md
internal/compiler/widgets/cupertino-base/spinbox.slint
internal/compiler/widgets/material-base/spinbox.slint

Fixed edited callback for SpinBox material and cupertino style

---

internal/core/items/text.rs
internal/core/sharedvector.rs
tests/cases/text/undo_redo.slint

TextInput: Add undo/redo support

---

api/node/src/interpreter/component_definition.rs

* Return a result with an error message instead of an option

node: ComponentDefinition::create return Result

---

internal/compiler/generator/cpp.rs
tests/cases/types/enums.slint
tests/cases/types/structs.slint

C++: fix compilation when class name has an underscore

---

.github/workflows/ci.yaml

Latest tree-sitter changes behaviour. Pin until changes are applied on our side.

Make the CI green

---

.github/workflows/ci.yaml
tools/lsp/common.rs
tools/lsp/language.rs
tools/lsp/language/completion.rs
tools/lsp/language/properties.rs
tools/lsp/main.rs
tools/lsp/preview.rs
tools/lsp/preview/drop_location.rs
tools/lsp/preview/element_selection.rs

Use the format test to test this compilation

LSP: fix compilation without the preview features

---

internal/backends/winit/event_loop.rs
internal/backends/winit/winitwindowadapter.rs

Tested with kwin on X11 and on wayland

winit: Make sure to keep the minimized state in sync

---

internal/renderers/skia/Cargo.toml
internal/renderers/skia/opengl_surface.rs

Release notes at https://github.com/rust-skia/rust-skia/releases/tag/0.71.0

Update to Skia 0.71

---

tools/lsp/language/completion.rs
tools/lsp/util.rs

Also add completion for the inherits keyword

LSP: fix auto-completion in two ways bindings

---

internal/backends/winit/winitwindowadapter.rs

Workaround for https://github.com/slint-ui/slint/issues/4678 Ubuntu's window manager using XWayland would raise the window when calling set_minimized(false) even it was not minimized
Fixes #4678

winit: Cache locally the last value of the minimize/maximize/fullscreen state

---

api/python/Cargo.toml
api/python/brush.rs
api/python/errors.rs
api/python/lib.rs
api/python/slint/__init__.py
api/python/tests/test_brush.py
api/python/tests/test_instance.py
api/python/value.rs

Python: Add bindings for Brush and Color

---

tools/lsp/language.rs

To ensure cache keys are always the same.
The problem is especially be on windows where editor such as vscode can send `file:///c%3A/` while Url::from_path would be `file:///C:/`, which compare differently
Fixes: #4721

LSP: normalize URL beofre sending to the preview

---

api/python/interpreter.rs

Instead, log a message and return.

Python: Don't panic when invoking a python callback fails

---

examples/energy-monitor/ui/widgets/bar_tiles.slint

Should be much better now. Tweaking in a specific direction (easing, duration) should be easy now if necessary.

Embedded Monitor: improved bar animation

---

api/python/models.rs
api/python/tests/test_models.py
examples/memory/Pipfile
examples/memory/main.py

... and add a port of the memory game while we're at it :)

Python: Add support for writing back models

---

Cargo.toml
api/rs/build/lib.rs
xtask/src/license_headers_check.rs
xtask/src/nodepackage.rs

The toml_edit dependency is required for reading board_config.toml

Fix use of deprecated symbols

---

tests/cases/widgets/combobox.slint

This tends to regress, so test the basics
Unfortunately, since each style places the popup at different places, it is hard to click on the popup.
Also the enter and space keys are not really working fine right now, so don't test that for now 😳

ComboBox test

---

tools/lsp/fmt/fmt.rs

Fixes https://github.com/slint-ui/slint/issues/4833
Fixes https://github.com/slint-ui/slint/issues/4834
Fixes https://github.com/slint-ui/slint/issues/4832

Format transitions

---

internal/compiler/builtins.slint
internal/compiler/passes/border_radius.rs
internal/compiler/passes/clip.rs
internal/core/items.rs

Fix clipping and border-radius

---

tools/lsp/fmt/fmt.rs

Fix https://github.com/slint-ui/slint/issues/4850
Fix #4857

fmt: more fixes to states identation

---

docs/torizon.md

chore: update torizon.md

---

internal/compiler/parser/element.rs
tools/lsp/fmt/fmt.rs

fmt: Fix formatting of function argument declaration

---

internal/backends/android-activity/java/SlintAndroidJavaHelper.java
internal/backends/android-activity/javahelper.rs
internal/core/items/text.rs
internal/core/window.rs

Have two selection handle when there is selected text

Android: selection handle

---

internal/backends/android-activity/build.rs

Also support Java 8 that did not support the --release argument yet.
Fix #4904

android: show a proper error when the version is java is too old

---

docs/reference/src/language/widgets/slider.md
internal/backends/qt/qt_widgets/slider.rs
internal/compiler/builtins.slint
internal/compiler/widgets/common/slider-base.slint
internal/compiler/widgets/cosmic-base/slider.slint
internal/compiler/widgets/cupertino-base/slider.slint
internal/compiler/widgets/fluent-base/slider.slint
internal/compiler/widgets/material-base/slider.slint
internal/compiler/widgets/qt/slider.slint
tests/cases/widgets/slider_basic.slint

This callback is invoked when the user finished selecting a new value.
This is the continuation of #4682

Add a released callback to Slider

---

internal/backends/android-activity/androidwindowadapter.rs
internal/backends/android-activity/build.rs
internal/backends/android-activity/java/SlintAndroidJavaHelper.java
internal/backends/android-activity/javahelper.rs
internal/backends/android-activity/lib.rs
internal/core/items/text.rs

android: long press selects word and show menu

---

internal/compiler/lib.rs
internal/compiler/object_tree.rs
internal/compiler/passes/inlining.rs
tests/cases/children/children_placeholder.slint
tests/cases/children/children_placeholder_two_levels.slint

Don't always appends at the end
Fixes #4935

Fix insertion point of `@children`

---

internal/compiler/widgets/cosmic-base/components.slint
internal/compiler/widgets/cosmic-base/styling.slint
internal/compiler/widgets/cosmic-base/tabwidget.slint

This updates the style / design of the comsic `TabWidget `to the latest cosmic style guidelines.

Cosmic: updated TabWidget style

---

api/cpp/cbindgen.rs
api/rs/slint/private_unstable_api.rs
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/llr/lower_to_item_tree.rs
internal/compiler/passes/lower_accessibility.rs
internal/compiler/typeregister.rs
internal/core/accessibility.rs
internal/core/item_tree.rs
internal/interpreter/dynamic_item_tree.rs
tests/cases/accessibility/actions.slint
tools/lsp/language/properties.rs

I haven't tested this other than "it compiles"
Remaining work is
- Add tests for accessible action
- Implement it in the backend (accesskit and Qt)

WIP: Accessibility action support in the compiler

---

docs/tutorial/node/src/main_game_logic.js
docs/tutorial/node/src/main_tiles_from_js.js

Otherwise I get this error  TypeError: initial_tiles.map is not a function

doc: fix js error

---

.github/workflows/ci.yaml

Otherwise Qt segfault as it's not thread safe to have widgets in different threads

Prospective CI fix: Run the Qt widget tests with `--test-threads=1`

---

internal/backends/qt/qt_widgets/button.rs
internal/backends/qt/qt_widgets/checkbox.rs
internal/backends/qt/qt_widgets/spinbox.rs
internal/backends/qt/qt_widgets/tabwidget.rs

**Changes**
- Fix scroll direction of spinbox for qt backend
- Check mouse button for qt widgets in input_event
Closes #4975

Check mouse button for qt widgets in `input_event`

---

api/cpp/include/slint_color.h
api/node/src/types/brush.rs
docs/reference/src/language/syntax/types.md
internal/core/graphics/color.rs

Attempt to clarify how the factor is applied to the two colors.

Improve docs of color's mix() function

---

internal/core/model.rs
tests/cases/models/model.slint

Fix panic when the model row_data returns None

---

internal/compiler/widgets/common/tabwidget-base.slint
internal/compiler/widgets/cosmic-base/tabwidget.slint
internal/compiler/widgets/cupertino-base/tabwidget.slint
internal/compiler/widgets/fluent-base/tabwidget.slint
internal/compiler/widgets/material-base/tabwidget.slint
internal/compiler/widgets/qt/tabwidget.slint

**Changes**
- Introduce `TabBarBase` that implements scrolling through tabs functionality
- Update `TabBarImpl` for all styles to inherit from `TabBarBase`
Closes #5002

Allow scrolling through tabs for all backends

---

internal/backends/qt/qt_widgets/combobox.rs
internal/compiler/builtins.slint
internal/compiler/widgets/qt/combobox.slint

Implement has_focus for NativeComboBox  (Was #5007)

---

internal/backends/qt/qt_accessible.rs
internal/backends/winit/accesskit.rs
internal/core/item_tree.rs

Accesibility: Implement the action in the backend

---

examples/todo/rust/lib.rs
internal/backends/qt/qt_accessible.rs
internal/backends/testing/search_api.rs
internal/backends/winit/accesskit.rs
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/core/item_tree.rs
internal/interpreter/dynamic_item_tree.rs

So we can know whether the item had the property set at all or not

accessibility: return an Option for accessible string values

---

api/cpp/cbindgen.rs
api/cpp/esp-idf/slint/src/slint-esp.cpp
api/cpp/include/slint-platform.h
api/cpp/include/slint_size.h
api/cpp/platform.rs
api/rs/slint/tests/partial_renderer.rs
internal/core/graphics.rs
internal/core/item_rendering.rs
internal/core/software_renderer.rs
internal/core/software_renderer/draw_functions.rs
internal/core/window.rs
tests/screenshots/testing.rs

This allow to be much faster in the case two small area of the screen changes.

swrenderer: Support multiple rectangles for the dirty regions

---

tools/lsp/main.rs

You can pass `-L foo=/path/to/foo` to add `@foo` as a library when starting the LSP server.
The change was pretty much just lifted from the viewer tool. I tested this in a real project with a real library.
Closes #5144

Implement -L flag for the LSP tool, similar to the viewer

---

internal/backends/qt/build.rs
internal/backends/selector/Cargo.toml
internal/backends/selector/build.rs
internal/backends/winit/build.rs
internal/compiler/build.rs
internal/core/Cargo.toml
internal/core/build.rs
internal/renderers/skia/build.rs

Let cargo know about our internal cfgs.

Prospective fix for rustdoc warnings about unknown cfg's

---

tools/lsp/preview/drop_location.rs

LSP preview: make sure to move the entire sub-element (including the id)

---

CHANGELOG.md
internal/compiler/widgets/common/spinbox-base.slint
tests/cases/widgets/spinbox_basic.slint

Fix text update of SpinBox

---

internal/compiler/object_tree.rs
internal/compiler/tests/syntax/lookup/issue_5246_states_function.slint

Fix compiler panic when trying to set a function in a state

---

internal/compiler/passes/purity_check.rs
internal/compiler/tests/syntax/functions/functions_purity_recursive_5220.slint

Fix stack overflow in purity check

---

internal/backends/qt/qt_widgets/spinbox.rs
internal/compiler/builtins.slint
internal/compiler/widgets/qt/spinbox.slint

Add support for step-size to SpinBox rendered by the Qt style

---

examples/carousel/esp-idf/s3-box/main/idf_component.yml
examples/printerdemo_mcu/esp-idf/main/CMakeLists.txt
examples/printerdemo_mcu/esp-idf/main/idf_component.yml

The original box isn't produced anymore.

Switch the esp-idf based s3 box examples to use the s3 box 3

---

internal/backends/winit/accesskit.rs

When a widget advertises a default action that can be performed by ATs, it is necessary to indicate what this action does. We are aware that this API is confusing and we plan to simplify it in the near future.
Should fix the issue described in https://github.com/slint-ui/slint/pull/5357#issuecomment-2150838177. Unfortunately the MacBook I used to test this is apparently too old to effectively run Slint applications. @tronical please check if you can see the action on checkboxes inside Accessibility Inspector now.

Add `DefaultActionVerb` to AccessKit nodes

---

internal/compiler/widgets/cosmic-base/switch.slint
internal/compiler/widgets/cupertino-base/switch.slint
internal/compiler/widgets/fluent-base/switch.slint
internal/compiler/widgets/material-base/switch.slint
internal/compiler/widgets/qt/switch.slint
tests/cases/widgets/switch.slint

... and fix Switch defaults to match the docs for all styles.

Add missing accessible-action-default for Switch

---

.github/workflows/build_docs.yaml
api/cpp/include/slint-interpreter.h
api/cpp/include/slint-platform.h
api/cpp/include/slint.h
api/cpp/include/slint_color.h
api/cpp/include/slint_image.h
api/cpp/include/slint_sharedvector.h
api/cpp/include/slint_string.h
api/cpp/include/slint_timer.h
api/cpp/include/vtable.h
examples/opengl_texture/main.cpp
xtask/src/reuse_compliance_check.rs

This might bring in a newer version of clang-format.

Attempt to upgrade the docs build to latest Ubuntu 24.04 in GH Actions

---

api/cpp/Cargo.toml
api/cpp/esp-idf/slint/include/slint-esp.h
api/cpp/esp-idf/slint/src/slint-esp.cpp
api/cpp/include/slint-platform.h
api/cpp/platform.rs
internal/core/Cargo.toml
internal/core/software_renderer.rs
tests/screenshots/Cargo.toml

Make rendering rotation a public feature of the software renderer

---

internal/compiler/generator/rust.rs
internal/compiler/passes.rs
internal/compiler/passes/inlining.rs
internal/compiler/tests/syntax/basic/popup.slint
tests/cases/issues/issue_5375_children_in_popup.slint

Fix `@children` in a PopupWindow

---

internal/backends/qt/qt_accessible.rs
internal/backends/testing/lib.rs
internal/backends/testing/search_api.rs
internal/backends/winit/accesskit.rs
internal/common/enums.rs
internal/interpreter/dynamic_item_tree.rs

This allows querying for elements by their role/type.

Add ElementHandle::accessible_role()

---

Cargo.toml
examples/README.md
examples/maps/Cargo.toml
examples/maps/main.rs

This example shows how to tiled rendering and async image loading

Map example. Loading tiles from OpenStreetMap

---

examples/gallery/gallery.slint
examples/printerdemo/ui/printerdemo.slint
examples/printerdemo_mcu/ui/printerdemo.slint
examples/todo/ui/todo.slint
internal/compiler/object_tree.rs
internal/compiler/tests/syntax/exports/root_compo_export3.slint
internal/interpreter/api.rs

... for last component when globals are exported

fix missing warning of missing export

---

internal/compiler/generator/rust.rs

Some project on github were reaching into that module so it cannot be renamed

Rust: Rename the slint_generated module to its old name

---

internal/backends/winit/winitwindowadapter.rs

Work around sometimes missing resize event on macOS with winit

---

.github/workflows/build_docs.yaml
.github/workflows/ci.yaml
examples/mcu-board-support/lib.rs

Usefull to know in advance what warnings our users might get early enough

Improve coverage of Rust nightly in CI

---

internal/compiler/lib.rs
internal/compiler/passes/check_public_api.rs
internal/compiler/tests/syntax_tests.rs
internal/interpreter/api.rs
tools/lsp/preview.rs

Add a feature to only generate a specified component.

Port LSP to slint_interpreter::Compiler

---

internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/llr/expression.rs
internal/compiler/llr/item_tree.rs
internal/compiler/llr/lower_to_item_tree.rs
internal/compiler/llr/optim_passes/inline_expressions.rs
internal/compiler/llr/pretty_print.rs

This allow to optimize away many property like the materialized x and y
properties.
Also contain minor change in computing the inlining cost for condition

llr: ensure const property without bindings are recognize as such by expression inlining

---

internal/core/input.rs
internal/core/window.rs
tests/cases/elements/flickable.slint

Fix double click within a Flicakble

---

api/cpp/include/slint.h
api/cpp/include/slint_image.h
xtask/src/cppdocs.rs

And make sure that functions excluded when freestanding is enabled are included in the docs.

API review: enable all features in the C++ docs

---

examples/fancy_demo/main.slint
examples/ffmpeg/scene.slint
examples/gallery/gallery.slint
examples/gstreamer-player/scene.slint
tools/lsp/ui/components/group.slint

Remove stray imports of StyleMetrics

---

.github/workflows/build_docs.yaml

Run the www copy steps only if the PR originates from within the slint repo.

Prospective fix for PR runs outside the repo

---

internal/backends/android-activity/build.rs

According to https://github.com/slint-ui/slint/discussions/5662 , this might be necessary

Android: create output directory for .class

---

tools/lsp/common/properties.rs

Callbacks can't be in the property list anyway, and setting their values assert later in the checking code.
Fix #5652

LSP: properties: filter accessible-action-* callbacks from the property list

---

internal/renderers/skia/itemrenderer.rs

Replace uses of skia_safe::Paint::default() with calls to self.default_paint(), to apply the current global alpha.
Fixes #5706

Skia: Make sure to consistently apply the global alpha

---

.github/workflows/nightly_snapshot.yaml
.github/workflows/slint_tool_binary.yaml

Add support for building armv7 and aarch64 viewer/lsp binaries

---

api/cpp/include/slint_window.h

Some have it some don't. Just add it everywhere.
See https://github.com/slint-ui/slint/discussions/5762

C++: add assert_main_thread to public functions in the Window

---

editors/vscode/package.json
editors/vscode/slint-file-icon.svg

Vscode extension: add Slint icon to .slint file

---

tools/lsp/common/properties.rs
tools/lsp/ui/views/property-view.slint

... instead of chekcing for "Empty" in the Slint code
Do the suggestion from https://github.com/slint-ui/slint/pull/5625#issuecomment-2228976684

LSP: don't answer "Empty" for component that do not inherit

---

tools/lsp/language/goto.rs

drive by fix goto definition of properties with underscores noticed while writing the test.

LSP: goto definition for re-exports

---

tools/lsp/preview.rs

This fixes #4872 and probably more similar issues.
Fixes: #4872

live-preview: Compile-test all edits before sending them out

---

tools/lsp/util.rs

lsp: Treat EoF as whitespace when looking for non-ws

---

examples/cpp/platform_qt/main.cpp

Fix typo in example

---

internal/backends/winit/event_loop.rs

winit: Don't forward synthetic event to the application

---

internal/interpreter/api.rs
tools/lsp/common.rs
tools/lsp/preview.rs
tools/lsp/preview/properties.rs

This is just the uncontested cleanups that are part of #5820.

The cleanups from #5820

---

internal/compiler/lookup.rs
internal/compiler/passes/check_expressions.rs
internal/compiler/passes/resolving.rs
internal/compiler/tests/syntax/expressions/clamp.slint
internal/compiler/tests/syntax/expressions/math-macro.slint
internal/compiler/tests/syntax/lookup/conversion.slint
tests/cases/expr/clamp.slint
tests/cases/expr/cos.slint
tests/cases/expr/math.slint
tests/cases/expr/minmax.slint
tests/cases/expr/round.slint
tools/lsp/fmt/fmt.rs

Closes #5328
(Also fix some missing error (and panics) when member functions were not called for example `"hello".to-float`)

Math postfix member functions on numbers

---

api/rs/macros/lib.rs

Use same rules for .slint and macro.
The test is `cargo test -p test-driver-rust` without the `build-time` feature (but that feature is enabled in the CI and that's why CI didn't catch this)

Macro: Fix lexing of `4..log`

---

tools/lsp/ui/api.slint

Sometimes I am surprised my code works.
Reformat the entire thing while at it.

live-preview: Fix syntax errors in api.slint

---

internal/compiler/llr/lower_to_item_tree.rs
internal/compiler/llr/optim_passes/count_property_use.rs
internal/compiler/llr/optim_passes/inline_expressions.rs
internal/compiler/lookup.rs
internal/compiler/object_tree.rs
internal/compiler/passes/check_public_api.rs
internal/compiler/passes/inlining.rs

Nothing major, nothing controversial, just killing time while waiting on CI.

compiler: Fix a couple of clippy issues

---

.github/dependabot.yml

Weekly check for new github-actions and vscode extension npm updates

Use dependabot to create update PR's

---

editors/vscode/src/extension.ts
editors/vscode/src/telemetry.ts

Otherwise report to staging.slint.dev

Only report telemetry to slint.dev if we're running in production mode

---

internal/backends/winit/event_loop.rs
internal/backends/winit/lib.rs
tools/lsp/Cargo.toml
tools/lsp/main.rs

Disable the macOS system menu bar for the Slint Live-Preview

---

internal/core/items.rs
internal/core/items/input_items.rs

items.rs is getting big and i'm about to add another item there

refactor: move FocusScope and TouchArea to a new input_items.rs module

---

CHANGELOG.md
docs/reference/src/language/builtins/namespaces.md
internal/compiler/expression_tree.rs
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/llr/optim_passes/inline_expressions.rs
internal/compiler/lookup.rs
internal/interpreter/eval.rs
tests/cases/expr/atan2.slint
tests/cases/expr/trigo.slint

[x] Add builtin.
[x] Update docs.
[x] Add test.

Attempt to add Math.atan2 to the inbuilt math function

---

api/cpp/Cargo.toml
examples/mcu-board-support/Cargo.toml

Bump esp-println version

---

CHANGELOG.md

fixed typos and spelling errors

Fix Typos and Spelling in Changelog

---

docs/reference/src/language/syntax/properties.md
examples/weather-demo/build.rs
internal/compiler/object_tree.rs

unmark changed callback as experimental

---

tools/lsp/preview/native.rs

lsp preview: set `ui_is_visible` to true also when re-opening the preview

---

docs/reference/src/language/builtins/elements.md
internal/compiler/builtins.slint
internal/compiler/object_tree.rs
internal/compiler/passes/resolving.rs
internal/compiler/tests/syntax/basic/path_commands.slint
internal/compiler/typeregister.rs

Fix compiler panic when accessing path.commands in expressions

---

editors/vscode/src/browser.ts
editors/vscode/src/common.ts
editors/vscode/src/extension.ts
editors/vscode/telemetry.json

VS Code Telemetry: Attempt to detect the programming languages used

---

api/rs/slint/README.md
api/rs/slint/lib.rs
docs/reference/src/quickstart/getting_started.md
editors/vscode/src/quick_picks.ts

- Simplify quick start guide
- Remove substitution in vscode project quick pick

Simplify Rust Quickstart

---

tools/viewer/main.rs

For example, running the viewer with a DISPLAY wrongly set:
Before the patch:
```
thread 'main' panicked at tools/viewer/main.rs:123:32:
called `Result::unwrap()` on an `Err` value: Other("Could not initialize backend.\nError from Winit backend: Error initializing winit event loop: the requested operation is not supported by Winit\nError from LinuxKMS backend: Timeout while waiting to activate session\nNo backends configured.")
stack backtrace:
[...]
```
If just using `?` instead of `.unwrap()`:
```
Error: Other("Could not initialize backend.\nError from Winit backend: Error initializing winit event loop: the requested operation is not supported by Winit\nError from LinuxKMS backend: Timeout while waiting to activate session\nNo backends configured.")
```
If using an wrapper that uses …

Viewer: use Display to print the error message

---

editors/vscode/esbuild.js
editors/vscode/src/browser.ts
editors/vscode/src/common.ts
editors/vscode/src/extension.ts

No manual change in this PR at all, just the result of `npm run lint:fix`.

vscode: Apply biome fixes

---

tools/slintpad/biome.json
tools/slintpad/src/github.ts

Add configuration excluding generated JS files for biome in slintpad.
Let biome fix lints and format of everything.

slintpad: Biome fixes

---

tools/lsp/preview.rs
tools/lsp/preview/drop_location.rs

We did not have the compile-test infrastructure when implementing the addition of new components into a UI. Use that infrastructure, it catches some places where we can not actually drop into that the previous heuristic missed.

live-preview: Compile-test adding components

---

api/rs/slint/android.rs

chore: fix symbol error

---

tools/lsp/ui/main.slint
tools/lsp/ui/views/header-view.slint

moved some of icons around to feel a little more reasonably grouped for function

live-preview: Prettify the HeaderView

---

internal/backends/linuxkms/Cargo.toml
internal/backends/linuxkms/display/gbmdisplay.rs
internal/backends/linuxkms/drmoutput.rs

Update drm/gbm dependencies

---

internal/backends/linuxkms/Cargo.toml

linuxkms: bump more dependencies

---

internal/core/model.rs

This PR implements the `FromIterator` trait for `VecModel` as requested in #5879.
Closes #5879

core: implement FromIterator for VecModel

---

docs/_templates/release-artifacts.md

Add STM32 "SDKs" to the releaes artifacts table

---

examples/dial/dial.slint

Suspect some of the simplification could have been done with the original. But this wasn't so obvious at the time when the math was a bit more fussy.

Simplify dial to use atan2

---

internal/core/layout.rs
tests/cases/layout/grid_span.slint

Fixes #6181
ChangeLog: Fixed panic when rowspan or colspan is 0. (#6181)

GridLayout: fix panic when rowspan or colspan is 0

---

internal/renderers/skia/itemrenderer.rs

Layers and cached pixmaps should be "invisible" in terms of quality,
and they're "designed" to be pixel aligned.

Skia: Improve rendering quality of layers and qt style with fractional translations

---

examples/cpp/platform_native/windowadapter_win.h
internal/backends/android-activity/androidwindowadapter.rs
internal/backends/linuxkms/calloop_backend/input.rs
internal/backends/qt/qt_window.rs
internal/backends/winit/event_loop.rs
internal/common/enums.rs
tests/cases/elements/toucharea.slint
tests/cases/elements/toucharea_doubleclick.slint

common: add support for fourth and fifth pointing-device buttons

---

internal/core/timers.rs

Fixes: #6141
ChangeLog: Fixed Timer::set_interval() doesn't work in timer callback (#6141)

Fixed Timer::set_interval() doesn't work in timer callback

---

tools/lsp/ui/views/property-view.slint

new look to create some space for labels and content.

Cleanup columns

---

tools/lsp/ui/api.slint
tools/lsp/ui/components/styling.slint
tools/lsp/ui/views/property-view.slint

made adjustments using the awesome new data in api

---

api/cpp/docs/mcu/stm32/generic.md

This includes removal of the SLINT_STYLE setting, as a default is set there for FEATURE_FREESTANDING.

Polish the generic STM32 instructions

---

.github/workflows/upload_esp_idf_component.yaml
api/cpp/cmake/SlintConfig.cmake.in
api/cpp/esp-idf/slint/cmake/FindSlint.cmake

Prospective fix for builds against binary packages for MCU

---

docs/reference/Pipfile
docs/reference/_static/theme_tweak.css
docs/reference/conf.py

ChangeLog: Updates the Slint documentation to Sphinx Book Theme

Change to Sphinx Book Theme

---

editors/README.md

Add doc for Helix editor

---

tools/slintpad/package.json
tools/slintpad/src/editor_widget.ts

... and add more key bindings.
This makes for a much better language integration, incl. better word selection, auto-closing braces and commenting.
Closes: #6316

slintpad: Include slint language configuration

---

internal/compiler/passes/binding_analysis.rs
tests/cases/properties/changes.slint

Visit expressions of changed callback during binding analysis

---

tools/lsp/preview/native.rs

We already catch other sort of error, we should also catch run_event_loop and report the error to the LSP

LSP preview: don't panic if run_event_loop returns an error

---

tools/lsp/common.rs

Ignore elements that were optimized out when looking for a `ElementRcNode`s parent.
This is important e.g. when looking at `GridLayout`s: The `Row` Elements will be optimized out.

lsp: Ignore optimized out elements when looking for parent

---

tools/slintpad/src/editor_widget.ts

This is visually clearer, common, and relieves the user of doing it themselves.

SlintPad: Separate imports from rest with empty line.

---

editors/vscode/README.md
editors/vscode/package-lock.json
editors/vscode/package.json
editors/vscode/slint.tmLanguage.json
editors/vscode/tests/grammar/printerdemo.slint

... and fix the grammar to make the test pass.

WIP: vscode: Add tmGrammar test

---

.github/workflows/ci.yaml
api/node/biome.json

Run it after building the entire project.

Make biome invocation in the CI match dev workflow

---

examples/mcu-board-support/README.md

The `run` command was missing.

docs: Fix probe-rs command

---

docs/reference/src/language/builtins/elements.md

Improved `GridLayout` docs.

---

.github/workflows/cpp_package.yaml

Add generic xtensa-esp32-none-elf MCU packages

---

tools/lsp/preview/ui.rs

live-preview: Sort styles in style combobox

---

examples/ffmpeg/Cargo.toml
examples/ffmpeg/player/audio.rs

fix for 7.1.0

---

tools/lsp/language.rs

When writting
```slint
export component Foo inherits Bar { }
```
then highlight this element when the cursor is on Foo, not on Bar.
Fixes: #6409

lsp: Make live-preview preview on the type, not the base type

---

docs/reference/src/language/widgets/scrollview.md
examples/gallery/ui/pages/list_view_page.slint
internal/backends/qt/qt_widgets/scrollview.rs
internal/common/enums.rs
internal/compiler/builtins.slint
internal/compiler/widgets/cosmic/scrollview.slint
internal/compiler/widgets/cupertino/scrollview.slint
internal/compiler/widgets/fluent/scrollview.slint
internal/compiler/widgets/material/scrollview.slint
internal/compiler/widgets/qt/internal-scrollview.slint
internal/compiler/widgets/qt/scrollview.slint

Added a new property on Scrollbar to allow configuring its visibility
Fixes: #3552, #5578

Implement ScrollBarPolicy property for ScrollView

---

internal/core/model.rs

While technically allowed and sort of serving as a test to see if the model is well implemented, this is unnecessary behaviour. The model iterator should not serve as a testing ground :)

Rust: Stop ModelIterator from calling row_data() with out of bounds row

---

tools/lsp/preview.rs

Delay updating the live preview to prevent a
thundering herd effect when e.g. a git update changes a lot of files at once.

live-preview: Delay updaing the preview

---

.github/workflows/build_docs.yaml

CI: Run biome on its own config file

---

tools/lsp/preview.rs

A follow up, renaming `dependency` to `dependencies`.

live-preview: Rename ContentCache member

---

internal/compiler/passes/purity_check.rs
internal/compiler/tests/syntax/fuzzing/6518.slint

Fix panic with invalid code

---

tools/lsp/main.rs

lsp: Remove some unnecessay lines

---

internal/compiler/typeloader.rs

Fixes #4265
Not easy to test since this is platform dependent

Emit a warning when the case of the import file differ from the case of the file that was imported

---

internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/llr/item_tree.rs
internal/compiler/llr/lower_to_item_tree.rs
internal/compiler/llr/pretty_print.rs
internal/interpreter/dynamic_item_tree.rs
internal/interpreter/global_component.rs
tests/cases/properties/changes.slint

Fixes #6599
ChangeLog: Support property changed callbacks in globals

Support for changed callback in global

---

internal/interpreter/dynamic_item_tree.rs

This removes a lot of temporary allocations, note e.g. how this was called once per component previously yet the data contained in the map was always the same!
Before:
```
Benchmark 1: ./target/release/slint-viewer ../slint-perf/app.slint
Time (mean ± σ):     636.2 ms ±  20.0 ms    [User: 563.4 ms, System: 71.8 ms]
Range (min … max):   615.2 ms … 657.9 ms    10 runs
allocations:            3371939
```
After:
```
Benchmark 1: ./target/release/slint-viewer ../slint-perf/app.slint
Time (mean ± σ):     600.6 ms ±   2.9 ms    [User: 522.0 ms, System: 74.4 ms]
Range (min … max):   596.3 ms … 605.2 ms    10 runs
allocations:            2917930
```

Only build the RTTI hashmap once per thread

---

internal/backends/android-activity/build.rs
internal/backends/android-activity/javahelper.rs

modified:   internal/backends/android-activity/javahelper.rs
Detailed description: <https://github.com/wuwbobo2021/android-rust-java-test>
Please tell me if any improvement is required, such as obtaining the current OS API version in a better way.
PS: Tauri 2.0 supports Android 7.0.

Fixes #4936 for older Android versions (6.0 to 9.0)

---

Cargo.toml
internal/compiler/Cargo.toml
internal/compiler/embedded_resources.rs
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/lib.rs
internal/compiler/passes/embed_glyphs.rs
internal/core/graphics/bitmapfont.rs
internal/core/graphics/image.rs
internal/core/software_renderer.rs
internal/core/software_renderer/draw_functions.rs
internal/core/software_renderer/fixed.rs
internal/core/software_renderer/fonts.rs
internal/core/software_renderer/fonts/pixelfont.rs
internal/core/software_renderer/fonts/vectorfont.rs
internal/core/software_renderer/scene.rs
tools/compiler/Cargo.toml

Note that this is still disabled in the compiler with no way to enable
it with public API

Signed distance field in the software renderer

---

Cargo.toml
examples/opengl_texture/Cargo.toml
examples/opengl_underlay/Cargo.toml
internal/core/Cargo.toml
internal/renderers/femtovg/Cargo.toml

Bump various dependencies

---

internal/compiler/object_tree.rs
tests/cases/issues/issue_6651_export_sort.slint
tests/helper_components/issue_6651_implicit_export.slint

Fix order of exports when adding implicit export

---

internal/compiler/passes/resolving.rs
internal/compiler/tests/syntax/fuzzing/6632.slint
internal/compiler/tests/syntax/new_syntax/two_way_input_output.slint

Fix assertion failed: lhs_lookup.is_local_to_component

---

api/node/rust/interpreter/component_instance.rs
internal/compiler/expression_tree.rs
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/langtype.rs
internal/compiler/llr/expression.rs
internal/compiler/load_builtins.rs
internal/compiler/lookup.rs
internal/compiler/object_tree.rs
internal/compiler/passes/collect_structs_and_enums.rs
internal/compiler/passes/resolving.rs
internal/compiler/typeregister.rs
internal/interpreter/eval.rs
tools/lsp/language/hover.rs
tools/updater/experiments/purity.rs

There is no need for two of these
This simplify some code
Amend efdecf0a13131a9be856163c0b9ed0b52529bdf0

Merge the Callback and Function type

---

internal/compiler/passes/resolving.rs

Instead of cloning the vector on every iteration level, pass the scope in and out of the visitation function and push/pop the element there as needed. This way we can operate on a single vector that gets moved around, which removes a few thousand memory allocations. The speed impact is not measurable, as the code also triggers rowan API that is much more allocation happy.
Still, I believe this patch is still merge-worthy as it also reduces the code duplication a bit and is subjectively better, esp. from a performance pov.

Optimize resolve_expression to operate on a single scope vector

---

internal/compiler/langtype.rs
internal/compiler/passes/materialize_fake_properties.rs
internal/compiler/tests/consistent_styles.rs
internal/compiler/tests/syntax/elements/text.slint
internal/compiler/typeregister.rs
internal/compiler/widgets/common/combobox-base.slint
internal/compiler/widgets/common/datepicker_base.slint
internal/compiler/widgets/common/lineedit-base.slint
internal/compiler/widgets/common/listview.slint
internal/compiler/widgets/common/slider-base.slint
internal/compiler/widgets/common/spinbox-base.slint
internal/compiler/widgets/common/textedit-base.slint
internal/compiler/widgets/common/time-picker-base.slint
internal/compiler/widgets/cosmic/datepicker.slint
internal/compiler/widgets/cosmic/tableview.slint
internal/compiler/widgets/cupertino/datepicker.slint
internal/compiler/widgets/cupertino/tableview.slint
internal/compiler/widgets/cupertino/textedit.slint
internal/compiler/widgets/fluent/datepicker.slint
internal/compiler/widgets/fluent/tableview.slint
internal/compiler/widgets/material/datepicker.slint
internal/compiler/widgets/material/tableview.slint
internal/compiler/widgets/qt/datepicker.slint
internal/compiler/widgets/qt/tableview.slint
tools/lsp/language/hover.rs
tools/lsp/language/token_info.rs

Progress towards callback argument name support in LSP

---

tools/slintpad/src/editor_widget.ts

... by implementing it manually again :-/ And by
not using the EditorService that I thought was handling that.
And of course a TS map silently falls when your key is a Url, so that needed fixing, too.
Fixes: #6706

slintpad: Fix goto definition again

---

internal/compiler/passes/resolving.rs
internal/compiler/tests/syntax/fuzzing/6650.slint

Fix panic when calling expression containing un-called macro

---

demos/home-automation/README.md
demos/home-automation/ui/components/alarm.slint
demos/home-automation/ui/components/general/doors.slint

Fix for incorrect sized SVG on web.
Fix for incorrect gradient on HVAC for web.
Fix for opacity animation not being triggered.
Fix for README having incorrect copy paste info.

Home Automation fixes

---

api/cpp/cbindgen.rs
api/cpp/include/slint_image.h
api/cpp/include/slint_window.h
internal/core/graphics/image.rs
internal/core/window.rs

Changelog: C++: Add slint::Window::take_snapshot()

---

internal/compiler/diagnostics.rs
internal/compiler/lib.rs
internal/compiler/object_tree.rs
internal/compiler/passes/check_public_api.rs
internal/compiler/typeloader.rs
tools/lsp/common/document_cache.rs
tools/lsp/common/rename_component.rs
tools/lsp/language.rs
tools/lsp/language/test.rs

Did some refactoring on the typeloader. See individual commits.
Fixes https://github.com/slint-ui/slint/issues/5797

LSP: record dependencies

---

api/cpp/include/slint.h
api/rs/slint/lib.rs
api/rs/slint/private_unstable_api.rs
demos/printerdemo/lang/fr/LC_MESSAGES/printerdemo.po
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/core/context.rs
internal/core/translations.rs
tests/cases/translations/bundle.slint

Change API to set the language with bundle translation

---

pnpm-lock.yaml

Fixes https://github.com/slint-ui/slint/security/dependabot/17

Fix npm security warning

---

.github/workflows/build_docs.yaml

Try to install comic sans via MS corefonts for the docs build

---

internal/core/string.rs

Implements AsRef<Path>, AsRef<OsStr> for SharedString (#6810)

---

internal/interpreter/api.rs

This test is a bit simplistic... but it does test the basic functionality.

interpreter: Add test for `element_node_at_source_position`

---

docs/src/content/docs/concepts/callbacks.md
internal/compiler/builtins.slint
internal/compiler/expression_tree.rs
internal/compiler/langtype.rs
internal/compiler/load_builtins.rs
internal/compiler/object_tree.rs
internal/compiler/passes/focus_handling.rs
internal/compiler/tests/consistent_styles.rs
internal/compiler/typeregister.rs
internal/compiler/widgets/cupertino/textedit.slint
tools/lsp/language/completion.rs
tools/lsp/language/hover.rs
tools/lsp/language/signature_help.rs

Close https://github.com/slint-ui/slint/issues/6527

Stabilize named callback arguments

---

package.json
pnpm-lock.yaml

The rollup patchlevel bump fixes slintpad for me.

slintpad: Upgrade rollup to unbreak slintpad

---

tools/lsp/preview/ui.rs
tools/lsp/ui/api.slint
tools/lsp/ui/components/selection-popup.slint

this ux works really well but ideally goes back to what was selected before right click OR the selection actually moves rather than the hover color

experiment for highlighting UX

---

internal/backends/winit/Cargo.toml
internal/backends/winit/accesskit.rs

The core of AccessKit is no-std compatible now.

Update accesskit to 0.17 and accesskit_winit to 0.23

---

.github/workflows/publish_npm_package.yaml
api/node/binaries.json

Add arm64 node packages 

---

.github/workflows/ci.yaml
examples/mcu-board-support/Cargo.toml
examples/mcu-board-support/README.md
examples/mcu-board-support/build.rs
examples/mcu-board-support/lib.rs
examples/mcu-board-support/pico2_st7789.rs
examples/mcu-board-support/pico2_st7789/board_config.toml
examples/mcu-board-support/pico2_st7789/memory.x
examples/mcu-board-support/pico2_st7789/rp_pico2.rs
xtask/src/license_headers_check.rs

ChangeLog: MCU board support for Raspberry Pi Pico 2
This pull request is not related to any issue. 
Tested on real hardware.
There are two files copied from other projects:
```
examples/mcu-board-support/pico2_st7789/memory.x
examples/mcu-board-support/pico2_st7789/rp_pico2.rs
```
Inside you can find comments where it was copied from. How should i proceed to do everything legally right?

MCU board support for Raspberry Pi Pico 2

---

tools/docsnapper/main.rs

... and report an error if reading an entry in a directory failed

docsnapper: Sort files to make output more reproducible

---

docs/astro.config.mjs
docs/src/content/docs/guide/language/positioning-and-layouts.mdx

Integrate the positioning and layout guide

---

internal/backends/winit/Cargo.toml
internal/backends/winit/renderer/femtovg/glcontext.rs
internal/renderers/skia/Cargo.toml
internal/renderers/skia/metal_surface.rs
internal/renderers/skia/opengl_surface.rs

macOS: Replace use of old apple creates with modern objc2 replacements

---

docs/src/content/docs/misc/backends_and_renderers.md

Mention the current issue with cc-rs/skia-safe and Yocto

---

docs/astro/src/content/docs/reference/gestures/swipegesturehandler.mdx
docs/astro/src/content/docs/reference/gestures/toucharea.mdx

doc: Fix heading depth for callbacks

---

docs/astro/ec.config.mjs
docs/astro/package.json
docs/astro/src/content/docs/guide/language/concepts/slint-language.mdx
docs/astro/src/utils/link-data.json
pnpm-lock.yaml

@tronical This is like a bad first draft. Aim is to kick of a discussion on how to refine this into something we are happy with. I will carry on with the next couple of sections and come back to this tomorrow. Might also be easier for us both to sort it out tomorrow after a sleep :D
p.s. Also adds line number support to the expressive-code snippets. I will use this in a couple of places to make it clearer how to learn Slint

1.9 docs: Slint language philosophy

---

pnpm-lock.yaml

https://github.com/slint-ui/slint/security/dependabot/18

Update NPM dependencies after Nanoid security issue

---

internal/compiler/passes/materialize_fake_properties.rs
tests/cases/text/metrics.slint

compiler: fix materialize_fake_property for properties in base class

---

docs/astro/astro.config.mjs
docs/astro/src/content/docs/guide/backends-and-renderers/backend_qt.mdx
docs/astro/src/content/docs/guide/backends-and-renderers/backends_and_renderers.mdx
docs/astro/src/content/docs/guide/language/coding/animation.mdx
docs/astro/src/content/docs/guide/language/coding/file.mdx
docs/astro/src/content/docs/guide/language/coding/functions-and-callbacks.mdx
docs/astro/src/content/docs/guide/language/coding/globals.mdx
docs/astro/src/content/docs/guide/language/coding/properties.mdx
docs/astro/src/content/docs/guide/language/coding/repetition-and-data-models.mdx
docs/astro/src/content/docs/guide/language/concepts/component-property.mdx
docs/astro/src/content/docs/index.mdx
docs/astro/src/content/docs/reference/colors-and-brushes.mdx
docs/astro/src/content/docs/reference/common.mdx
docs/astro/src/content/docs/reference/elements/textinput.mdx
docs/astro/src/content/docs/reference/gestures/focusscope.mdx
docs/astro/src/content/docs/reference/gestures/key.mdx
docs/astro/src/content/docs/reference/slint-language.mdx
docs/astro/src/content/docs/reference/std-widgets/lineedit.mdx
docs/astro/src/utils/link-data.json
docs/astro/tests/smoke-test.spec.ts
internal/common/enums.rs

This fixes the broken links. Sadly in a few cases this was done by removing the links. But at least we can put out beta docs for feedback knowing the links that are there work and they can be added back later.

1.9 Turn on link validator

---

internal/backends/winit/build.rs
internal/backends/winit/event_loop.rs
internal/backends/winit/lib.rs
internal/backends/winit/renderer/skia.rs
internal/backends/winit/winitwindowadapter.rs
internal/renderers/skia/Cargo.toml
internal/renderers/skia/build.rs
internal/renderers/skia/lib.rs

Use target_vendor = "apple" where to cover all Apple OS, and exclude ios for event pumping.

Clean up Apple cfg's

---

internal/compiler/passes/resolving.rs
internal/compiler/tests/syntax/fuzzing/7095.slint
internal/compiler/tests/syntax/new_syntax/two_way_input_output.slint

Fix panic in legacy component with out property

---

tools/lsp/preview/ui.rs

The enum extraction code used to handle values in the form `EnunName.EnumValue` just fine, but igonred
`EnumValue`. Fix this.

live-preview: Fix handling of enums

---

internal/core/items/text.rs
tests/cases/text/input_type_decimal.slint

Fix TextInput decimal entry to add the minus in the middle

---

internal/compiler/builtin_macros.rs
internal/compiler/tests/syntax/expressions/minmax.slint
tests/cases/types/percent.slint

We were not properly convering the first argument
Fixes #7118

Fix min/max/clamp in presence of percentages

---

docs/astro/astro.config.mjs
docs/astro/src/components/VersionSelector.astro
docs/astro/src/content.config.ts
docs/astro/src/styles/custom.css

Adds 1.9.0 to the title header so people can know which docs they are looking at.
Also fixes some warnings due to updating to Astro 5.x and Starlight 0.30.x

1.9 Doc fix

---

.github/workflows/build_docs.yaml
about.toml
api/cpp/docs/index.rst
api/cpp/docs/thirdparty.hbs
api/node/cover.md
api/node/package.json
api/node/thirdparty.hbs
scripts/prepare_binary_package.sh
xtask/src/cppdocs.rs
xtask/src/license_headers_check.rs

C++/Node.js: Mention third-party licenses

---

examples/mcu-board-support/Cargo.toml
examples/mcu-board-support/esp32_s2_kaluga_1.rs
examples/mcu-board-support/esp32_s3_box.rs

Update esp-hal dependency

---

internal/backends/winit/Cargo.toml
internal/backends/winit/build.rs
internal/backends/winit/winitwindowadapter.rs
internal/core/window.rs

On Linux, react to dark-light color scheme changes

---

CHANGELOG.md

See individual commits for details.

Various ChangeLog edits

---

api/node/README.md
api/node/cover.md

Node.js: Fix links to Slint Language Docs

---

docs/astro/src/content/docs/index.mdx

Avoid hard coded LinkCard links

---

internal/backends/winit/lib.rs

Fix build with merely renderer-software enabled for the winit backend

---

.github/workflows/build_docs.yaml
docs/astro/src/utils/site-config.ts

Make astro site config base url/path config more robust

---

.github/workflows/build_docs.yaml
.github/workflows/fmt_lint_typecheck.yaml

Move license and reuse check from docs build to fmt_lint_typecheck

---

tools/lsp/ui/components/selection-popup.slint

live-preview: Remember filter settings in selection popup

---

examples/dial/dial.slint

- Eliminated `in` qualifier from properties not used as inputs for clarity.
- Removed the default lightOff state as it served no purpose.
- Removed Rectangles used as containers for simplification.

dial example: simplify source code

---

examples/dial/README.md
examples/dial/dial.slint

Added two checks for new angle before applying it
- if it is within start and end angles
- if it is not far from current angle

dial example: Prevent rotation between start and end angles.

---

docs/testing.md

Docs: improve what interpreter test does

---

tools/viewer/main.rs

Viewer: convert struct to json in callback args

---

internal/compiler/widgets/common/standardbutton.slint
internal/compiler/widgets/qt/button.slint
tests/cases/elements/dialog.slint

Fixes #7230
ChangleLog: Fixed StandardButton not focusable

Make StandardButton focusable

---

docs/astro/src/content/docs/guide/language/concepts/slint-language.mdx

The documentation has a bunch of grammatical errors, so I am fixing the obvious ones. The text is also worded quite awkwardly, so I may also rephrase it in some places.

Fix English errors in docs

---

xtask/src/license_headers_check.rs

Let LicenseHeader merely store the license and replace only that part, while preserving any existing copyright (when fixing).

Fix license header check to permit non-SixtyFPS Copyright

---

internal/compiler/build.rs

Improve Bazel support for I-slint-compiler build

---

api/rs/build/Cargo.toml
api/rs/build/lib.rs
examples/ffmpeg/Cargo.toml
internal/compiler/Cargo.toml
internal/interpreter/Cargo.toml
internal/interpreter/api.rs
tests/driver/nodejs/Cargo.toml
tools/viewer/Cargo.toml
xtask/Cargo.toml

Note: thiserror was replaced by derive_more

Dependency updates

---

tools/lsp/preview.rs
tools/lsp/preview/native.rs

lsp: Fix error reporting when opening the live-preview fails

---

docs/release-artifacts.md

Add armhf/arm64 Linux packages to release artifacts table docs

---

api/cpp/cbindgen.rs
api/cpp/include/slint_window.h
api/rs/slint/private_unstable_api.rs
internal/backends/winit/muda.rs
internal/compiler/expression_tree.rs
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/llr/optim_passes/count_property_use.rs
internal/compiler/llr/optim_passes/inline_expressions.rs
internal/compiler/object_tree.rs
internal/compiler/passes/inlining.rs
internal/compiler/passes/lower_menus.rs
internal/compiler/passes/move_declarations.rs
internal/compiler/typeloader.rs
internal/compiler/typeregister.rs
internal/core/window.rs
internal/interpreter/dynamic_item_tree.rs
internal/interpreter/eval.rs

introduce a SetupMenuBar builtin function to ease C++/Rust lowering

MenuBar: C++/Rust native menubar implementation

---

api/rs/slint/mcu.md
examples/mcu-board-support/esp32_s3_box.rs
examples/mcu-board-support/pico2_st7789.rs
examples/mcu-board-support/pico_st7789.rs
examples/mcu-board-support/stm32h735g.rs
examples/uefi-demo/main.rs
internal/backends/android-activity/androidwindowadapter.rs
internal/backends/linuxkms/calloop_backend/input.rs
internal/backends/linuxkms/fullscreenwindowadapter.rs
internal/backends/winit/event_loop.rs
internal/backends/winit/winitwindowadapter.rs
internal/compiler/generator/rust.rs
internal/core/api.rs
internal/core/platform.rs
internal/core/window.rs

That is the same as Window::dispatch_event, but it reports an error instead of panicking

Introdue Window::try_dispatch_event

---

internal/backends/qt/qt_window.rs
internal/core/window.rs
tests/cases/elements/popupwindow_nested_close-on-click.slint

Fix closing PopupWindow when the click opens another PopupWindow

---

examples/gstreamer-player/Cargo.toml
examples/gstreamer-player/main.rs

Bump gstreamer dependencies

---

internal/core/window.rs

With the Qt backend, the PopupWindow has it's own Window, so we need to make sure we close the popup on the right Window
Fixes #7332

PopupWindow: Fix escape with the Qt backend

---

.github/workflows/ci.yaml
CHANGELOG.md
Cargo.toml
api/cpp/CMakeLists.txt
api/cpp/docs/cmake.md
api/cpp/docs/mcu/generic.md
api/node/README.md
api/node/cover.md
docs/building.md

Bump MSRV to 1.82

---

Cargo.toml
examples/opengl_texture/Cargo.toml
examples/opengl_texture/main.rs
examples/opengl_underlay/Cargo.toml
internal/renderers/femtovg/Cargo.toml
internal/renderers/skia/Cargo.toml

Bump glow and femtovg versions

---

docs/astro/src/content/docs/reference/elements/image.mdx
docs/astro/src/content/docs/reference/primitive-types.mdx
internal/core/graphics/image.rs

Link to the API docs from the image type.

Docs: Update docs for image

---

tools/lsp/preview/native.rs
tools/lsp/ui/api.slint
tools/lsp/ui/main.slint

live-preview(macOs): Add a Window menu with keep on top item

---

internal/backends/android-activity/build.rs

The version of the JDK 24 constains a `-`
Fixes #4973
That issue can be closed as it works with newer android SDK
ChangeLog: fix build with newer JDK

Android: fix parsing of version output

---

internal/compiler/builtins.slint
internal/compiler/passes/lower_menus.rs
internal/compiler/typeregister.rs
internal/compiler/widgets/common/menus.slint
internal/core/items.rs
internal/core/items/input_items.rs
internal/core/items/text.rs
tests/cases/widgets/contextmenu.slint

- Add the `entries` property in the ContextMenu
- Make right click on the ContextMenu show the menu

Work on the ContextMenu

---

examples/gstreamer-player/README.md
examples/gstreamer-player/main.rs

Hey, new to open source contributing so I thought I would start simple and implemented Play/Pause in GStreamer example.

Implemented Play/Pause for gstreamer example

---

examples/gstreamer-player/Cargo.toml
examples/gstreamer-player/egl_integration.rs
examples/gstreamer-player/main.rs
examples/gstreamer-player/software_rendering.rs

- Play a real video, not just the test source.
- Provide an egl integration on Linux. Based on commit c3596baa0c50a976ee9b2377c90ae70ec5e475c4, further fixed up by Sebastian Dröge <sebastian@centricular.com>

Rework the gstreamer example

---

.github/workflows/publish_npm_package.yaml

CI: Build aarch64 npm packages on GH actions arm64 runners

---

api/rs/slint/private_unstable_api.rs
internal/compiler/generator/rust.rs
internal/core/string.rs
internal/interpreter/eval.rs
tests/cases/expr/math.slint
tests/cases/types/string.slint

Comparison and string conversions

Fix operations on big integers

---

tools/lsp/common/rename_component.rs

Thank god for all the unit tests:-)
I could add more tests for the export module covering components, structs and enums, but I think the code itself does not care for those, so one set of examples should be enough. Well, famous last words...

lsp: Support export modules when renaming

---

internal/compiler/builtins.slint
internal/compiler/langtype.rs
internal/compiler/load_builtins.rs
internal/compiler/passes/compile_paths.rs
internal/compiler/passes/lower_menus.rs
internal/compiler/tests/syntax/elements/menubar2.slint
internal/compiler/typeregister.rs
tests/cases/widgets/contextmenu.slint
tests/cases/widgets/menubar.slint

Doesn't implement `if` and `for` yet.
Doesn't make the `entries` property inaccessible yet.

Lower `MenuItem` to entries

---

demos/printerdemo_mcu/esp-idf/main/idf_component.yml
examples/carousel/esp-idf/s3-box/main/idf_component.yml
examples/carousel/esp-idf/s3-usb-otg/main/idf_component.yml

Pin espressif/button to a version that compiles.

CI: Fix esp-idf build

---

docs/astro/src/content/docs/guide/language/concepts/reactivity.mdx

This change simply adds common search terms, so this paragraph will be a result for them.

Add search terms for two-way bindings

---

internal/renderers/skia/lib.rs

If we want to enable partial rendering by default in the future, then we need to do this instead of disabling rendering notifiers. We don't know where the application renders to.

Disable partial rendering when the application uses a rendering notifier

---

internal/backends/winit/Cargo.toml
internal/renderers/skia/Cargo.toml
internal/renderers/skia/metal_surface.rs
tools/lsp/Cargo.toml

Update to new objc2 versions

---

internal/backends/qt/qt_widgets/slider.rs
internal/compiler/widgets/common/slider-base.slint
tests/cases/widgets/slider_basic.slint

Slider widget: react to Home and End keys

---

internal/compiler/widgets/common/listview.slint
internal/compiler/widgets/qt/std-widgets-impl.slint
tests/cases/widgets/listview.slint

Set `accessible-action-default` on `ListView` items

---

demos/energy-monitor/README.md
demos/printerdemo_mcu/README.md

Demo: fix documentation link to mcu-board-support

---

internal/renderers/skia/metal_surface.rs

If CAMetalLayer decides to do double buffering for a long time, we'll keep increasing the age of the third buffer that we may have seen. We store that as u8, and this can overflow. Handle that case gracefully.
(This was introduced with commit d9404d4063eed0d60d8c3ca9b28b1a33f3ba2fd8)

Fix panic when rendering with Skia and Metal for a long time

---

examples/mcu-board-support/pico_st7789.rs

pico_st7789: Initialize display with black before enabling backlight

---

api/cpp/include/slint.h
internal/compiler/generator/rust.rs
internal/core/menus.rs
internal/interpreter/dynamic_item_tree.rs
internal/interpreter/eval.rs

Install a PropertyTracker to update the shadow tree if something changes

Refrersh the menubar when one of the property get changed

---

internal/interpreter/Cargo.toml
internal/interpreter/api.rs
internal/interpreter/dynamic_item_tree.rs
internal/interpreter/lib.rs
tools/lsp/Cargo.toml

interpreter: Rename `highlight` feature

---

tools/lsp/language/completion.rs

Eg: MenuItem or Tab or Path's components

LSP: fix completion of extra component specific builtin

---

internal/interpreter/api.rs
internal/interpreter/dynamic_item_tree.rs
internal/interpreter/dynamic_type.rs
internal/interpreter/eval.rs
internal/interpreter/global_component.rs

I was just looking whether my change introduced clippy warnings, but took the opportunity to polish the codebase a bit.

interpreter: Fix clippy warnings

---

docs/astro/src/content/docs/reference/keyboard-input/textinput.mdx
internal/backends/testing/testing_backend.rs
internal/compiler/builtins.slint
internal/compiler/widgets/common/textedit-base.slint
internal/compiler/widgets/cupertino/textedit.slint
internal/core/items/text.rs
tests/cases/widgets/textedit.slint

TextInput: implement page up/down

---

api/cpp/include/slint_window.h
internal/compiler/generator/rust.rs
internal/compiler/passes.rs
internal/compiler/passes/focus_handling.rs
internal/compiler/widgets/common/menus.slint
internal/core/window.rs
internal/interpreter/eval.rs
tests/cases/elements/menubar_for.slint
tests/cases/widgets/menubar.slint

Closing the menus is still not implemented

Rudimentary key navigation of the popup menu

---

examples/gallery/gallery.slint

I thought to just have a dummy menu bar in the gallery since the gallery should ideally show all widgets, including a menu bar

Gallery: Dummy menu bar

---

.github/workflows/build_docs.yaml
.github/workflows/nightly_snapshot.yaml
api/python/.gitignore
api/python/brush.rs
api/python/image.rs
api/python/pyproject.toml
api/python/slint/__init__.py
api/python/tests/test_brush.py
api/python/tests/test_instance.py

Python: Begin API docs

---

internal/backends/winit/accesskit.rs

Generates an AccessKit tree update when the `DelegateFocus` accessible property change on the item with focus. This allows assistive technologies to be notified when the focused item of a "set" change even if the item tree is otherwise unchanged. We don't need to check the whole tree in this particular case, so I created a dedicated property tracker which only calls `handle_focus_item_change`. I think it would be less efficient to reuse the property tracker for the node with focus, as we would have to iterate through all the cached nodes to find it back, and it would rebuild the node.
The motivation for this is to fix the `SideBar` widget of the Gallery app.
Thanks Simon for the hints!

Track the `accessible-delegate-focus` property of the focused item

---

internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/llr/item_tree.rs
internal/compiler/llr/lower_to_item_tree.rs
internal/compiler/widgets/common/menus.slint
internal/core/window.rs
internal/interpreter/eval.rs
tests/cases/widgets/contextmenu.slint
tests/driver/cpp/cppdriver.rs

Now it kind of work as expected with the winit backend.
The Qt backend still will need work for the mouse event with the native popup

Implement closing of popup menus

---

internal/compiler/widgets/common/lineedit-base.slint
internal/compiler/widgets/common/textedit-base.slint
internal/compiler/widgets/cupertino/textedit.slint
internal/core/input.rs
internal/core/items/text.rs
internal/core/window.rs
tests/cases/widgets/textedit.slint

With usual copy/paste entries
We need to make sure that showing the popup window don't clear the selection in the TextInput which happens if the TextInput gets a FocusOut event.

ContextMenu on the LineEdit and TextEdit

---

.github/actions/test-online-editor/action.yaml
.github/workflows/autofix.yaml
.github/workflows/build_docs.yaml
.github/workflows/ci.yaml
.github/workflows/nightly_snapshot.yaml
.github/workflows/wasm_editor_and_interpreter.yaml
editors/vscode/package.json
package.json
pnpm-lock.yaml

This also recreates the lock file in an attempt to clear out the old version of esbuild that is causing alerts.

Upgrade PNPM 9.x to 10.3

---

docs/astro/src/content/docs/guide/language/concepts/slint-language.mdx

Use intro video in the docs

---

api/python/slint/__init__.py
api/python/slint/__init__.pyi

(Docs to be written)
- Also fix eq signature and avoid Self to fix links and mypy

Python: Include @slint.callback in the doc reference

---

.github/workflows/autofix.yaml
api/cpp/docs/conf.py
demos/printerdemo/python/main.py
examples/memory/main.py

Format all Python code

---

.github/workflows/nightly_snapshot.yaml

Ensure figma-plugin.zip has correct name

---

api/cpp/esp-idf/slint/src/slint-esp.cpp

... or byte swapped.
We need to take the right stride which might be the height if it is rotated
https://github.com/slint-ui/slint/issues/7597#issuecomment-2661975754

esp-idf: Fix rendering of rotated and single buffering

---

internal/interpreter/json.rs
tools/lsp/Cargo.toml
tools/lsp/preview.rs
tools/lsp/preview/preview_data.rs
tools/lsp/preview/ui.rs
tools/lsp/ui/api.slint
tools/lsp/ui/components/property-widgets.slint
tools/lsp/ui/main.slint
tools/lsp/ui/views/preview-data-view.slint
tools/lsp/ui/views/property-view.slint

Simple Runtime properties

---

tools/lsp/preview.rs
tools/lsp/preview/ui.rs
tools/lsp/ui/api.slint
tools/lsp/ui/views/preview-data-view.slint

Nothing live changing in here, just a bit of polish to get out of the way of unrelated changes ;-)

polish live data

---

.github/workflows/upload_esp_idf_component.yaml
api/cpp/esp-idf/slint/CMakeLists.txt

Add support for nightly esp-idf builds

---

tools/lsp/preview/ui.rs

... were shown as JSON, fix this!

live-preview: Enums in preview data mode

---

internal/backends/qt/qt_window.rs

We really need to dispatch the release event otherwise the wrong item keeps the drag and this breaks the behavior.
This is not perfect yet as if the release is done on the wrong popup, then we'll still not get the release event.
We should probably remove the grab when a popup open. But that's slightly more complicated

Qt: Fix processing of the mouse release event in popup menu

---

internal/backends/winit/muda.rs
internal/backends/winit/winitwindowadapter.rs

Fixes https://github.com/slint-ui/slint/issues/7708

Add a property tracker for the Muda Menu

---

tools/figma-inspector/PUBLISH.md
tools/figma-inspector/backend/code.ts
tools/figma-inspector/backend/utils/code-utils.ts
tools/figma-inspector/backend/utils/property-parsing.ts
tools/figma-inspector/figma.config.ts
tools/figma-inspector/src/main.tsx
tools/figma-inspector/src/snippet/CodeSnippet.tsx

This fixes the project so it can be published.
This documents the publishing process.
This fixes a few bugs in the plugin, especially for the non dev mode where things would fail to refresh as the Figma file is edited.

Publish Figma Plugin to store

---

internal/backends/winit/Cargo.toml
tools/lsp/Cargo.toml

Upgrade muda

---

api/cpp/include/slint-platform.h

Minor C++ cleanups

---

tools/lsp/ui/components/property-widgets.slint
tools/lsp/ui/views/preview-data-view.slint
tools/lsp/ui/views/property-view.slint

This also makes spacing a bit more consistent for me and stops some widgets from being cut off on Linux.

live-preview: Remove bottons and then fix the fallout caused by all the layouts around us f-ing up all of a sudden

---

tools/lsp/ui/components/property-widgets.slint

At least it does set values again in Property Editor mode and seems to work fine in general for me. But then I think I said the same about 10 times today...

live-preview: Try to improve the Color Widget further

---

tools/slintpad/src/editor_widget.ts

* Remove the IOT Dashboard. It does not work too well for me in slintpad
* Remove the Todo demo, it needs too much business logic to work and is not looking very impressive either.
* Add all the fancy things @NigelBreslaw made

slintpad: Update demo list

---

api/cpp/esp-idf/slint/src/slint-esp.cpp

This allocates quite a lot of memory and is likely to fail. Make it easier to debug

esp-idf: assert that malloc succeeds when allocating line buffer

---

tools/lsp/preview/ui.rs
tools/lsp/ui/api.slint
tools/lsp/ui/components/property-widgets.slint

live-preview: Report errors when setting preview data

---

tools/lsp/preview/ui.rs

... to actually use the code that is also used by
the tests :-)

live-preview: Fix get_property_value_table

---

tools/lsp/preview.rs
tools/lsp/preview/ui.rs

... when that data is available ... which should be basically all the time ;-)

live-preview: Show name of component instead of <MAIN>

---

tools/lsp/ui/components/property-widgets.slint

Use a GridLayout, that seems simpler and add a bit of extra padding.

live-preview: Polish the property widgets a bit

---

xtask/src/license_headers_check.rs

I use jj as a VCS and found it annoying that I could not run the license header check xtask due to that.
It's a small enough change, so I do not feel too bad about complicating things for everyone;-)

xtask: Make license header check work with jj

---

api/python/slint/__init__.py
api/python/slint/slint.pyi

... and fixed library_paths type signature while at it.

Quick pass at some Python API docs

---

Cargo.toml

SVG: Enable support for raster images by default

---

api/python/brush.rs
api/python/slint/models.py

Python: Incrementally add some more API docs

---

internal/core/timers.rs

doc: minor polish to the timer docs

---

internal/compiler/generator/rust.rs
internal/compiler/llr/lower_expression.rs
internal/compiler/passes/remove_return.rs
tests/cases/issues/issue_7864_condition_return_void.slint

Fix panic or warning in the generated code
Fixes #7864

Compiler: Fix when one branch of a void condition is not void

---

internal/compiler/passes/lower_popups.rs
internal/compiler/passes/lower_timers.rs
tests/cases/children/children_placeholder_two_levels.slint
tests/cases/children/timer_next_to_children.slint

Fix `@children` next to `Timer` or `PopupWindow`

---

editors/vscode/slint.tmLanguage.json
editors/vscode/tests/grammar/basic.slint
editors/vscode/tests/grammar/expressions.slint
editors/vscode/tests/grammar/printerdemo.slint
editors/vscode/tests/grammar/states.slint

Make the textmate grammar match better and test that it actually works as intended.

vscode: Redo TextMate grammar

---

internal/compiler/passes/const_propagation.rs

We should simplify the false branch even if the true branch can't be inlined
Fixes #7827

Compiler: fix const propagation in condition

---

.github/workflows/build_docs.yaml
api/python/.gitignore
api/python/build_docs.py
api/python/slint/__init__.py
api/python/slint/models.py

Various improvements to the Python docs

---

internal/renderers/skia/vulkan_surface.rs

This fixes the first validation error from #7850

Fixes vulkan validation error

---

api/python/build_docs.py

Python: fix doc building

---

docs/astro/astro.config.mjs
docs/astro/src/content/docs/language-integrations/index.mdx
docs/astro/src/utils/site-config.ts

docs: Add Python to the links for language integrations

---

examples/ffmpeg/README.md

Untested, but according to #4621
Closes #4621

Update instructions for ffmpeg on Windows

---

internal/core/window.rs

Not sure how we can get to this situation, but this is the most frequent panic in 1.10 according to the crash reporter

Don't panic when forwarding mouse event to a window without item_tree

---

docs/astro/src/content/docs/guide/backends-and-renderers/backend_linuxkms.md
docs/astro/src/content/docs/guide/backends-and-renderers/backend_winit.md

Document the linux dependencies

---

tools/lsp/ui/components/spreadsheet.slint

live-preview: Use context menu

---

editors/vscode/src/quick_picks.ts

Add Python to the templates for the VS code extension quick picker

---

api/cpp/include/slint_models.h
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/llr/item_tree.rs
internal/core/model.rs
internal/interpreter/dynamic_item_tree.rs
internal/interpreter/value_model.rs
tests/cases/models/if_dirty.slint

Fix re-instentiating `if` elements when the condition is dirty

---

tools/lsp/preview/ui.rs
tools/lsp/ui/api.slint

This is just the backend side, no UI changes were done.

live-preview: Implement backend code to handle tables of live data

---

.github/ci_path_filters.yaml
.github/workflows/ci.yaml

... and use the figma-inspector as an initial test case.

Introduce a CI file filter

---

api/python/README.md
api/python/build_docs.py
api/python/thirdparty.hbs

Python: Add third-party licenses page to the docs

---

README.md

doc: Add Python to the top-level README

---

internal/compiler/builtins.slint
internal/compiler/expression_tree.rs
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/langtype.rs
internal/compiler/llr/expression.rs
internal/compiler/llr/lower_expression.rs
internal/compiler/llr/optim_passes/inline_expressions.rs
internal/compiler/llr/pretty_print.rs
internal/compiler/load_builtins.rs
internal/compiler/object_tree.rs
internal/compiler/passes/ensure_window.rs
internal/compiler/passes/resolving.rs
internal/compiler/typeregister.rs
internal/compiler/widgets/common/menu-base.slint
internal/compiler/widgets/common/menus.slint
internal/compiler/widgets/cosmic/menu.slint
internal/compiler/widgets/cupertino/menu.slint
internal/compiler/widgets/fluent/menu.slint
internal/compiler/widgets/material/menu.slint
internal/compiler/widgets/qt/menu.slint
internal/core/input.rs
internal/core/items.rs
internal/core/window.rs
internal/interpreter/eval.rs

Fixes https://github.com/slint-ui/slint/issues/7822
The first commit is a fairly intrusive refactor to allow `is-open` to return bool.

Fix hover on menu bar

---

api/cpp/include/slint_models.h

C++: add code sample form model adapters

---

api/rs/slint/android.rs
demos/energy-monitor/src/lib.rs
demos/printerdemo/rust/lib.rs
demos/usecases/rust/src/lib.rs
demos/weather-demo/src/lib.rs
examples/mcu-board-support/pico2_st7789/rp_pico2.rs
examples/mcu-board-support/stm32h735g.rs
examples/todo/rust/lib.rs
internal/backends/android-activity/javahelper.rs
internal/backends/android-activity/lib.rs
internal/compiler/generator/rust.rs

The ones that needs unsafe in the 2024 edition
Fix #7998

Mark some attribtes as unsafe

---

internal/core/items/text.rs

Apply the text input's type check also to the commit string from input

---

tools/lsp/preview/ui.rs
tools/lsp/ui/api.slint

It's just the backend work, not UI for it yet, so it can not get triggered at all. So it should be save to pull in;-)
I am doing more work on the ui/business logic interaction layer and would love to avoid resolving conflicts.

Pull in the Feature/live data tables

---

docs/astro/src/content/docs/reference/window/contextmenuarea.mdx
docs/astro/src/content/docs/reference/window/menubar.mdx
examples/gallery/gallery.slint
internal/backends/winit/muda.rs
internal/common/builtin_structs.rs
internal/common/lib.rs
internal/compiler/builtins.slint
internal/compiler/passes/lower_menus.rs
internal/compiler/tests/syntax/elements/contextmenu2.slint
internal/compiler/tests/syntax/elements/menubar2.slint
internal/compiler/widgets/common/menu-base.slint
internal/compiler/widgets/common/menus.slint
internal/compiler/widgets/cosmic/menu.slint
internal/compiler/widgets/cupertino/menu.slint
internal/compiler/widgets/fluent/menu.slint
internal/compiler/widgets/material/menu.slint
internal/compiler/widgets/qt/menu.slint
internal/core/menus.rs
tests/cases/elements/contextmenu_for.slint
tests/cases/elements/menubar_for.slint
tests/cases/widgets/contextmenu.slint
tests/cases/widgets/menubar.slint

Introduce MenuSeparator

---

internal/core/model.rs

Document how to update a model from a thread

---

api/python/Cargo.toml
api/python/brush.rs
api/python/interpreter.rs
api/python/models.rs
api/python/slint/__init__.py
api/python/slint/slint.pyi
api/python/tests/test_callback_decorators.py
api/python/tests/test_compiler.py
api/python/tests/test_gc.py
api/python/tests/test_instance.py
api/python/tests/test_load_file.py
api/python/tests/test_models.py
api/python/timer.rs
api/python/value.rs

Python: Upgrade to latest PyO3 release

---

examples/mcu-board-support/Cargo.toml
examples/mcu-embassy/Cargo.toml

0.3.100 has been published and is effectively 1.0

Upgrade defmt to Version 1.0

---

.github/workflows/ci.yaml
editors/vscode/slint.tmLanguage.json
editors/vscode/tests/grammar/basic.slint
editors/vscode/tests/grammar/expressions.slint
editors/vscode/tests/grammar/invalid.slint
editors/vscode/tests/grammar/printerdemo.slint
editors/vscode/tests/grammar/snippets.slint
editors/vscode/tests/grammar/states.slint

See individual commits:
- make sure properties get highlighted also at top level for the purpose of snippets
- don't highlight every possible identifiers in expressions 
- improve tests and put them in CI

tmLanguage fixups

---

REUSE.toml
tools/lsp/ui/api.slint
tools/lsp/ui/assets/background-tiny.svg
tools/lsp/ui/assets/plus.svg
tools/lsp/ui/components/property-widgets.slint
tools/lsp/ui/components/styling.slint
tools/lsp/ui/components/widgets/brush-widget.slint
tools/lsp/ui/components/widgets/color-widget.slint
tools/lsp/ui/components/widgets/floating-color-picker-widget.slint
tools/lsp/ui/properties-state.slint
tools/lsp/ui/windowglobal.slint

This is not complete, but ready to be merged to master.
It provides a gradient picker that should be useful in the data tab even though it is not feature complete.
Stops cannot be added or removed.
Stops do not re-sort themselves.
You cannot edit the gradient angle.
All of these issues and more will be addressed in later PR's.

New Brush widget

---

internal/compiler/passes/resolving.rs
tools/lsp/preview/ui/property_view.rs

Parse the gradient data from source code and pass it on to the UI side to do its magic.

live-preview: Add gradient support to the property editor

---

tools/figma-inspector/backend/utils/export-variables.ts

abstracted some functions to make others more understandable

---

tools/lsp/preview/ui.rs
tools/lsp/preview/ui/gradient.rs
tools/lsp/ui/api.slint
tools/lsp/ui/components/widgets/gradient-basics.slint

... add unit tests and fix the bugs those discovered.

live-preview: Move more code out of ui.rs

---

internal/compiler/typeloader.rs
tools/lsp/language/test.rs

We will need these if loading from cache
Fixes https://github.com/slint-ui/slint/issues/8064

typeloader: Cache parse error for loaded document

---

tools/figma-inspector/backend/utils/export-variables.ts

swapped current-scheme with current-mode for usability. also removed a bunch of console.log messages

---

tools/lsp/ui/components/widgets/floating-color-picker-widget.slint
tools/lsp/ui/properties-state.slint

Also fixes Gradient editor should always show with 90deg

Show which gradient stop has focus

---

tools/lsp/ui/components/widgets/floating-color-picker-widget.slint
tools/lsp/ui/components/widgets/inline-brush-widget.slint
tools/lsp/ui/windowglobal.slint

Better align color and gradient indicators.
Fix pixel jump in hue slider.
Allow deleting of gradient stops.
Stop json error showing all the time.

Gradient fixes

---

tools/figma-inspector/backend/utils/export-variables.ts

Re-use existing slint color generation function

---

examples/iot-dashboard/CMakeLists.txt

Add missing include(FetchContent)

---

demos/home-automation/ui/components/graph.slint

Home Automation: fix graph vertical grid lines

---

internal/compiler/widgets/common/lineedit-base.slint

Disable cut/paste action in lineedit when disabled

---

tools/lsp/ui/components/draggable-panel.slint
tools/lsp/ui/components/widgets/brush-helpers.slint
tools/lsp/ui/components/widgets/floating-color-picker-widget.slint
tools/lsp/ui/components/widgets/inline-brush-widget.slint
tools/lsp/ui/windowglobal.slint

This also includes some minor bug fixes:
- Floating panels block scroll wheel events to stop the underlying canvas being scrolled.
- Hex color value should be applied when defocusing the TextEdit,

Teach new brush pickers to handle radial gradients

---

internal/compiler/parser/expressions.rs
internal/compiler/passes/resolving.rs
internal/compiler/tests/syntax/basic/for.slint
internal/compiler/tests/syntax/basic/for_range.slint

Several users have been asking if it is possible to use range expression.
Detect this and have a meaningful error message

diagnostic: try to detect use of range expression and recommand to use number

---

internal/core/software_renderer.rs
tests/screenshots/cases/software/basic/images.slint

swrenderer: Fix panic when scaling an image so much that it cannot be seen

---

internal/interpreter/api.rs
internal/interpreter/eval.rs

interpreter: don't panic trying to access callback alias

---

api/python/README.md
api/python/brush.rs
api/python/image.rs
api/python/slint/__init__.py

Minor updates to the documentation for readability and polish

---

.github/workflows/ci.yaml

Janitor: update tree-sitter

---

tools/figma-inspector/backend/code.ts
tools/figma-inspector/backend/utils/code-utils.ts
tools/figma-inspector/backend/utils/property-parsing.ts
tools/figma-inspector/shared/universals.d.ts
tools/figma-inspector/src/globals.d.ts
tools/figma-inspector/src/main.tsx
tools/figma-inspector/src/utils/bolt-utils.ts

split up recursive dev from useVariables and added some ux to enable switch between original resolve inspector and inspector of variables as exported.

finalize useVariables checkbox for ux

---

api/cpp/CMakeLists.txt

Janitor: Bump corrosion version

---

tools/figma-inspector/backend/utils/property-parsing.ts
tools/figma-inspector/shared/universals.d.ts

figma-inspector: added horizontal-alignment to textsnippet

---

tools/figma-inspector/backend/code.ts
tools/figma-inspector/backend/utils/code-utils.ts
tools/figma-inspector/backend/utils/export-variables.ts
tools/figma-inspector/backend/utils/property-parsing.ts
tools/figma-inspector/src/main.tsx
tools/figma-inspector/src/utils/bolt-utils.ts

figma-inspector: reduce console.log and integerate warnings into README

---

examples/gallery/ui/pages/controls_page.slint

Disable button widget too

---

pnpm-lock.yaml
tools/figma-inspector/backend/code.ts
tools/figma-inspector/backend/utils/code-utils.ts
tools/figma-inspector/backend/utils/export-variables.ts
tools/figma-inspector/backend/utils/property-parsing.ts
tools/figma-inspector/figma.config.ts
tools/figma-inspector/package.json
tools/figma-inspector/shared/universals.d.ts
tools/figma-inspector/src/globals.d.ts
tools/figma-inspector/src/main.tsx
tools/figma-inspector/src/snippet/dark-theme.json
tools/figma-inspector/src/snippet/light-theme.json
tools/figma-inspector/src/utils/bolt-utils.ts
tools/figma-inspector/src/utils/utils.ts
tools/figma-inspector/tests/property-parsing.test.ts

including a new mode for the inspector to turn it form resolved values to use variables wherever available
* supports dot notation by creating structs to support thierarchy
* exposes variables menu for exporting figma variables as library file of design tokens 
* single file and multi-file export available
* reverts to single file if multi-file has cyclic references
* error checking for binding loops
* variable name sanitizers

adding figma variables to the inspector

---

api/node/__test__/eventloop.spec.mts
biome.json
docs/astro/ec.config.mjs
docs/astro/src/components/editor/codemirror.js
editors/vscode/src/browser-lsp-worker.ts
editors/vscode/src/common.ts
editors/vscode/src/lsp_commands.ts
editors/vscode/src/wasm_preview.ts
tools/figma-inspector/backend/code.ts
tools/figma-inspector/backend/utils/property-parsing.ts
tools/figma-inspector/src/utils/utils.ts
tools/slintpad/src/editor_widget.ts
tools/slintpad/src/github.ts

biome: Enable lint to check for missing await statements

---

tools/figma-inspector/backend/utils/code-utils.ts
tools/figma-inspector/src/main.tsx
tools/figma-inspector/src/snippet/CodeSnippet.tsx
tools/figma-inspector/src/utils/bolt-utils.ts
tools/figma-inspector/src/utils/store.ts
tools/figma-inspector/src/utils/utils.ts

Just a last couple of items moved to Zustand. Next is to use Figma styled UI components.
---
This is **part 2 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #8309 👈 
- <kbd>&nbsp;1&nbsp;</kbd> #8307

Figma Plugin: Move final items into Zustand

---

examples/gallery/ui/pages/table_view_page.slint

Provide a default unfiltered/unsorted view of the table, so that editing the data in the data tab changes.

Gallery Example: Make the data tab work

---

tools/figma-inspector/.gitignore
tools/figma-inspector/postcss.config.js
tools/figma-inspector/tailwind.config.js

The config *.js files should not be ignored.

Fix tailwind config issues due to .gitignore

---

docs/astro/src/content/docs/reference/window/contextmenuarea.mdx
examples/gallery/ui/gallery_settings.slint
examples/gallery/ui/pages/controls_page.slint
examples/gallery/ui/pages/page.slint
examples/gallery/ui/pages/text_edit_page.slint
internal/compiler/builtins.slint
internal/compiler/widgets/common/lineedit-base.slint
internal/compiler/widgets/common/textedit-base.slint
internal/core/items.rs

Hide action when widget is disabled

---

tools/figma-inspector/src/main.css
tools/figma-inspector/src/main.tsx

(figma) Add line numbers to the design mode snippet view

---

tools/figma-inspector/backend/utils/export-variables.ts

now checking for cross-collection references correctly

figma-inspector: fix regression when exporting separate files

---

tools/figma-inspector/src/main.tsx

figma-inspector: text color variable now also working in dark mode

---

cspell.json
docs/astro/astro.config.mjs
docs/astro/src/content/docs/guide/platforms/web.mdx

In particular, this also document how to enable the clipboard to close #8338

docs: Add a web section

---

demos/home-automation/ui/components/mainView/mainScreen.slint

Home Automation: fix color of month

---

.mise/config.toml
.mise/tasks.toml

Mise keeps freezing. One suggestion was to list specific versions and not use "latest" https://github.com/jdx/mise/issues/4302

Use specific versions with Mise

---

demos/home-automation/node/main.js
demos/home-automation/rust/Cargo.toml
demos/home-automation/rust/lib.rs
demos/home-automation/ui/api.slint

Add real-time clock to home automation demo

---

demos/home-automation/ui/components/musicPlayer.slint
demos/home-automation/ui/images/play.svg

Home Automation: Improve player's play button

---

demos/home-automation/ui/components/alarm.slint
demos/home-automation/ui/components/appliance.slint
demos/home-automation/ui/components/camera.slint
demos/home-automation/ui/components/control.slint
demos/home-automation/ui/components/dishwasher.slint
demos/home-automation/ui/components/general/fancySlider.slint
demos/home-automation/ui/components/general/innerShadowRectangle.slint
demos/home-automation/ui/components/graph.slint
demos/home-automation/ui/components/hvac.slint
demos/home-automation/ui/components/info.slint
demos/home-automation/ui/components/lamp.slint
demos/home-automation/ui/components/mainView/fullScreenWidgetLoader.slint
demos/home-automation/ui/components/mainView/fullScreenWidgetLoaderSW.slint
demos/home-automation/ui/components/mainView/mainScreen.slint
demos/home-automation/ui/components/mainView/sidebar.slint
demos/home-automation/ui/components/mainView/widgetLoader.slint
demos/home-automation/ui/components/mainView/widgetLoaderSoftwareRenderer.slint
demos/home-automation/ui/components/microwave.slint
demos/home-automation/ui/components/musicPlayer.slint
demos/home-automation/ui/components/overhead.slint
demos/home-automation/ui/components/timeInfo.slint
demos/home-automation/ui/components/weatherInfo.slint

Home Automation: clean up imports

---

api/cpp/cbindgen.rs
api/node/rust/interpreter/component_compiler.rs
api/node/rust/interpreter/component_instance.rs
api/node/rust/interpreter/value.rs
api/node/rust/lib.rs
api/node/rust/types/model.rs
tests/doctests/build.rs
tests/driver/driverlib/lib.rs
tests/driver/nodejs/nodejs.rs
tools/lsp/fmt/tool.rs
tools/lsp/language/completion.rs
tools/lsp/preview/drop_location.rs
tools/lsp/preview/element_selection.rs
tools/lsp/preview/properties.rs
tools/lsp/util.rs
tools/tr-extractor/main.rs
tools/updater/experiments/purity.rs
tools/updater/main.rs
tools/viewer/main.rs

Nothing systeamatic, just a bunch of fixes I stumbled over during unrelated work.
No behavior change is intended in here...

chore: A few clippy fixes

---

internal/backends/linuxkms/calloop_backend.rs
internal/backends/winit/Cargo.toml
internal/backends/winit/build.rs
internal/backends/winit/clipboard.rs
internal/backends/winit/event_loop.rs
internal/backends/winit/lib.rs
internal/backends/winit/renderer/skia.rs
internal/backends/winit/winitwindowadapter.rs
internal/common/Cargo.toml
internal/common/sharedfontdb.rs
internal/compiler/passes/embed_glyphs.rs
internal/core/items/text.rs
internal/renderers/femtovg/Cargo.toml
internal/renderers/femtovg/fonts.rs
internal/renderers/skia/Cargo.toml
internal/renderers/skia/lib.rs

This PR cleans up the cfg landscape a little and fixes initial window sizing.

Various cleanups for iOS

---

internal/backends/selector/api.rs
internal/backends/selector/lib.rs

... if the backend is not explicitly selected

BackendSelector: respect the SLINT_BACKEND env variable

---

internal/backends/winit/winitwindowadapter.rs

winit backend: Don't update the window icon unnecessarily

---

internal/backends/winit/winitwindowadapter.rs

Use the render_to_buffer function to handle not just loaded pixel images.

winit: Add support for SVG icons in the window title

---

docs/astro/src/content/docs/tutorial/getting_started.mdx

So people don't have to download and extract the zip to see what's in it

Docs: have a link directly to the template

---

docs/astro/src/styles/custom.css

Fix docs <code> elements having a black background

---

cspell.json
docs/astro/src/content/docs/reference/std-widgets/style.mdx

I this PR, I add a guide to show how to select style in Python. 
---
> in the past: 
> ![image](https://github.com/user-attachments/assets/daccca08-cfa2-4115-9ead-c8f943602e77)
---
> now
> ![image](https://github.com/user-attachments/assets/caf0a2db-0e51-42fd-8b52-ab66039cbed4)

docs(style):  show how to select style in Python.

---

docs/astro/src/content/docs/guide/platforms/ios.mdx

docs: Polish iOS instructions

---

api/rs/slint/lib.rs

I'm not sure if this is the best way to do this, but since musl can't be used with Slint due to https://github.com/slint-ui/slint/issues/7586 , I would love to run into a compile time issue rather than see my app crash at runtime.

feat: raise compiler error if musl is used

---

internal/compiler/widgets/common/menus.slint

Can be usefull for separator
(Required for #8339)
Note, this doesn't fix the issue, just would allow for it to be fixed later

Menus: make it possible to have items with different height

---

.github/workflows/ci.yaml
Cargo.toml
examples/README.md
examples/bevy/Cargo.toml
examples/bevy/README.md
examples/bevy/main.rs
examples/bevy/slint_bevy_adapter.rs
examples/bevy/web_asset.rs
internal/core/graphics/image.rs

This demonstrates how to integrate Bevy into a Slint UI.
Screenshot:

Add example of rendering a Bevy scene into Slint

---

tools/figma-inspector/README.md
tools/figma-inspector/backend/code.ts
tools/figma-inspector/backend/utils/code-utils.ts
tools/figma-inspector/backend/utils/export-variables.ts
tools/figma-inspector/backend/utils/property-parsing.ts
tools/figma-inspector/src/main.tsx
tools/figma-inspector/tests/figma_output.json
tools/figma-inspector/tests/property-parsing.test.ts
tools/figma-inspector/tsconfig.json

This tidies up some dead code and turns on a more stricter tsconfig to automate keeping the project this way.

Make figma project stricter

---

api/python/pyproject.toml

Python: Remove unnecessary maturin run-time dependency

---

tools/lsp/Cargo.toml
tools/lsp/preview/ui.rs
tools/lsp/preview/ui/palette.rs
tools/lsp/ui/api.slint
tools/lsp/ui/components/widgets/floating-brush-sections/palettes.slint

Add a fuzzy matcher and a helper function for the UI to use it.

live_preview: Fuzzy-match palette entries

---

examples/mcu-board-support/README.md

muc-board-support: doc - fix tasks.json

---

api/cpp/platform.rs

This is still experimental API, but just have a copy of all arguments in a plain struct that the C++ code can operate on.
(Because previous refactor of the interface had made it hidden from C++)

C++: expose the DrawRectangleArgs and DrawTextureArgs

---

docs/testing.md

Docs: fix typo in testing.md

---

tools/lsp/ui/components/widgets/floating-brush-picker-widget.slint
tools/lsp/ui/components/widgets/floating-brush-sections/gradient-ui.slint
tools/lsp/ui/components/widgets/floating-brush-sections/palettes.slint
tools/lsp/ui/components/widgets/floating-brush-sections/svg-color-ui.slint
tools/lsp/ui/windowglobal.slint

This makes the WindowManager simpler and know less about the Pickers internals.
This logic is now handled via the PickerData global.

Simplify the brush picker

---

.github/workflows/build_docs.yaml
.github/workflows/ci.yaml
.github/workflows/nightly_snapshot.yaml
.github/workflows/wasm_editor_and_interpreter.yaml
package.json

It had been updated in mise, but not the rest of the CI

Update pnpm to 10.11.0

---

tools/lsp/preview/native.rs
tools/lsp/preview/ui/recent_colors.rs

... being potentially run from the wrong thread.

live-preview: Fix Mac menu commands

---

api/cpp/include/slint_timer.h
api/cpp/include/slint_window.h
internal/compiler/generator/cpp.rs

- In the timer functions
- in the generated getter/setters and callback invocation

C++: add asserts that we are in the main thread

---

docs/astro/src/content/docs/guide/tooling/figma-inspector.mdx
tools/figma-inspector/backend/utils/export-variables.ts

and replace the whole thing simply with *current*

figma-inspector: optimize out a second struct for current that duplicates current-scheme

---

docs/astro/src/content/docs/reference/keyboard-input/textinput.mdx

Document that one should use LineEdit or TextEdit widget instead And have the example scroll the widget
CC #8567

documentation for TextInput

---

.mise/config.toml

The listed version coredumps for me...

chore: Update pnpm

---

.github/workflows/build_docs.yaml
api/rs/build/Cargo.toml
api/rs/macros/Cargo.toml
api/rs/slint/Cargo.toml
api/rs/slint/android.rs
internal/backends/android-activity/Cargo.toml
internal/backends/linuxkms/Cargo.toml
internal/backends/qt/Cargo.toml
internal/backends/selector/Cargo.toml
internal/backends/testing/Cargo.toml
internal/backends/winit/Cargo.toml
internal/common/Cargo.toml
internal/compiler/Cargo.toml
internal/core-macros/Cargo.toml
internal/core/Cargo.toml
internal/interpreter/Cargo.toml
internal/renderers/femtovg/Cargo.toml
internal/renderers/skia/Cargo.toml

This is a nice nightly rustdoc feature and we should make use of it

Add `--generate-link-to-definition` in the docs of all our published crate

---

internal/backends/linuxkms/Cargo.toml
internal/backends/linuxkms/calloop_backend.rs
internal/backends/linuxkms/calloop_backend/input.rs

LinuxKMS: Bump nix dependency

---

.github/workflows/build_docs.yaml
api/rs/slint/lib.rs
internal/backends/selector/api.rs
internal/backends/winit/lib.rs

CC https://github.com/slint-ui/slint/issues/8631#issuecomment-2957986384

winit: Rename some function and add docs cross reference

---

internal/backends/winit/event_loop.rs
internal/backends/winit/lib.rs

This PR doesn't yet expose it in the public API.

winit: introduce CustomApplicationHandler trait

---

internal/core/items/text.rs

On desktop, the preedit gets discarded when the focus changes. But on android, we must apply it.
Fixes #8275

Android: commit the preedit text when focus change

---

docs/nightly-release-notes.md
docs/release-notes.md

Python: Add instructions how to build from git or upgrade the lock file

---

CHANGELOG.md

There are spelling mistakes in the changelog.

---

internal/compiler/passes/remove_return.rs
tests/cases/expr/return3.slint

Compiler: Fix invalid code gen with return statements

---

internal/compiler/passes/resolving.rs
tests/cases/expr/arithmetic.slint
tests/cases/expr/round.slint
tests/cases/types/int_conversion.slint

We should not cast to int
Fixes #8778
ChangeLog: Fix comparison of int and float

Fix comparison between int and float

---

internal/renderers/skia/Cargo.toml

For details, see https://github.com/rust-skia/rust-skia/releases/tag/0.87.0

Update to skia-safe 0.87

---

internal/backends/winit/frame_throttle.rs
internal/backends/winit/lib.rs
internal/backends/winit/winitwindowadapter.rs

winit: Add support for timer based frame throttling

---

tools/lsp/preview.rs
tools/lsp/preview/eval.rs
tools/lsp/preview/ui/property_view.rs

lsp: Clippy fixes

---

internal/backends/winit/Cargo.toml

winit: Bump AccessKit versions

---

internal/core/timers.rs

Timer: Don't panic if starting timers while drop'ing thread_locals

---

docs/astro/src/content/docs/reference/colors-and-brushes.mdx

https://docs.slint.dev/latest/docs/slint/reference/colors-and-brushes/#linear-gradients

docs: Fix header level of Linear Gradients on Colors & Brushes

---

internal/core/software_renderer/scene.rs

swrenderer: fix typo

---

examples/gstreamer-player/egl_integration.rs
examples/gstreamer-player/main.rs
examples/gstreamer-player/software_rendering.rs

How to do this is not straightforward, so it is helpful to have in the example.

GStreamer example: handle messages from pipeline bus

---

examples/gstreamer-player/egl_integration.rs
examples/gstreamer-player/main.rs
examples/gstreamer-player/software_rendering.rs

gstreamer example: Move the bus sender instead of cloning

---

tools/lsp/ui/views/outline-view.slint

gonna work on same style for the rest of the headers. 
will eventually change the style from ConsoleStyle to something more about the whole application for the header at least

live-preview outline: added console styled header

---

internal/compiler/object_tree.rs
internal/compiler/parser.rs
internal/compiler/passes/check_public_api.rs
internal/compiler/passes/lower_component_container.rs
internal/compiler/passes/lower_menus.rs
tools/lsp/common.rs
tools/lsp/common/rename_component.rs
tools/lsp/preview.rs
tools/lsp/preview/drop_location.rs
tools/lsp/preview/outline.rs
tools/lsp/preview/properties.rs
tools/lsp/preview/ui.rs
tools/lsp/preview/ui/property_view.rs
tools/lsp/ui/api.slint
tools/lsp/ui/components/property-widgets.slint
tools/lsp/ui/main.slint
tools/lsp/ui/views/outline-view.slint
tools/lsp/ui/windowglobal.slint

Add an "outline" panel in the bottom of the property editor.

Live-preview: Outline

---

tools/lsp/ui/views/outline-view.slint

visual editor: display hierarchy more clearly

---

tools/lsp/ui/components/expandable-group.slint
tools/lsp/ui/components/styling.slint
tools/lsp/ui/components/widgets/basics.slint
tools/lsp/ui/components/widgets/boolean-widget.slint
tools/lsp/ui/components/widgets/enum-widget.slint
tools/lsp/ui/components/widgets/float-widget.slint
tools/lsp/ui/components/widgets/inline-brush-widget.slint
tools/lsp/ui/components/widgets/integer-widget.slint
tools/lsp/ui/components/widgets/json-widget.slint
tools/lsp/ui/components/widgets/multi-value-widget.slint
tools/lsp/ui/components/widgets/string-widget.slint
tools/lsp/ui/views/preview-data-view.slint
tools/lsp/ui/views/property-view.slint

visual-editor: clean up property and data  display

---

internal/compiler/llr/expression.rs
tests/cases/properties/animation_from_click_in_repeated_4741.slint

Compiler: Fix visiting assignement on animated properties in parent

---

docs/astro/src/content/docs/guide/language/coding/properties.mdx
docs/astro/src/content/docs/guide/language/concepts/reactivity.mdx

- Document that binding can be broken (Closes #5990)
- Document that binding can contains statements (Closes #8982)

Docs: improvement to property bindings

---

tools/lsp/common/token_info.rs
tools/lsp/language/goto.rs
tools/lsp/language/hover.rs

LSP: adds the comments in the hover/tooltip

---

.github/workflows/build_docs.yaml
CHANGELOG.md
Cargo.toml
api/cpp/cbindgen.rs
api/rs/slint/Cargo.toml
api/rs/slint/lib.rs
examples/bevy/Cargo.toml
examples/bevy/main.rs
examples/bevy/slint_bevy_adapter.rs
examples/wgpu_texture/Cargo.toml
examples/wgpu_texture/main.rs
internal/backends/selector/Cargo.toml
internal/backends/selector/api.rs
internal/backends/winit/Cargo.toml
internal/backends/winit/lib.rs
internal/backends/winit/renderer/skia.rs
internal/core/Cargo.toml
internal/core/api.rs
internal/core/graphics.rs
internal/core/graphics/image.rs
internal/core/graphics/image/cache.rs
internal/core/graphics/wgpu_26.rs
internal/core/window.rs
internal/renderers/femtovg/Cargo.toml
internal/renderers/femtovg/images.rs
internal/renderers/femtovg/lib.rs
internal/renderers/femtovg/wgpu.rs
internal/renderers/skia/Cargo.toml
internal/renderers/skia/cached_image.rs

wgpu: Switch to WGPU 26

---

tools/lsp/common/rename_component.rs
tools/lsp/common/test.rs
tools/lsp/common/text_edit.rs
tools/lsp/preview.rs
tools/lsp/preview/drop_location.rs
tools/lsp/preview/ui.rs
tools/lsp/preview/undo_redo.rs
tools/lsp/ui/api.slint
tools/lsp/ui/views/header-view.slint

The interface needs more work.

live-preview: implement undo-redo

---

docs/astro/src/content/docs/guide/language/concepts/reactivity.mdx

Docs: Further improvments to docs about broken bindings

---

docs/common/src/utils/slint.tmLanguage.json
editors/vscode/tests/grammar/strings.slint

grammar: Fix parsing of expressions injected into strings

---

editors/zed/src/slint.rs
tools/lsp/README.md

Zed extension: fix windows package name

---

internal/core/model/adapters.rs

For the filter model: filter these element out.
For the sort model: put them at the end.
Closes #9093

Rust adapter model: don't panic over broken model returning None from row_data

---

tools/lsp/language.rs

- Don't have a code action to preview global
- Include the `export` and `component` keyword in the range for both the lens and the action.

LSP: fixup the range of code lenses and code action for "Show Preview"

---

examples/bevy/Cargo.toml
examples/bevy/README.md
examples/bevy/slint_bevy_adapter.rs

Improvements to the Bevy example

---

examples/dial/dial.slint

Dial Example: Use local variables instead of temporary properties

---

examples/opengl_underlay/main.rs

When toggling 'rotation' the demo would reset. This now pauses it and lets it gracefully continue.

Handle pausing the openGL underlay demo

---

tools/lsp/preview/ui.rs
tools/lsp/preview/ui/search_model.rs
tools/lsp/ui/api.slint
tools/lsp/ui/components/styling.slint
tools/lsp/ui/components/widgets/basics.slint
tools/lsp/ui/views/library-view.slint
tools/lsp/ui/views/property-view.slint

This commit attempt to add a line edit and a search model to search in the library.
The same concept can be used in the properties as well.
Todo: make the LineEdit a bit more pretty

live-preview: search within the library

---

editors/vscode/src/extension.ts

The rust process will use several `writeln!` on the file to write out the panic information. This may take some time and vscode could be reading these files before. So add a small timer in vscode to make sure we do not try to send the telemetry before we have all the info

vscode: fix the crash reporter

---

tools/lsp/common.rs
tools/lsp/language.rs
tools/lsp/main.rs
tools/lsp/preview/connector/native.rs
tools/lsp/preview/connector/wasm.rs
tools/lsp/wasm_main.rs

Just reposrt an error, just like we do in the surrounding code.
Not sure if that will keep the LSP up and running, but at least it should fix the panic a couple of people have run into already.

lsp: Do not panic when no data can be sent to the Preview

---

tools/lsp/preview/properties.rs

When we have a property such as
`property <int> foo: 45;`
And the live-preview user wants to reset the value of that property, we should keep the property there.
So the result should be
`property <int> foo;`
and not remove the property completely as the old code was doing, otherwise it is likely that this wouldn't compile if the property was used anyway.

lsp: fix removing binding of declared property

---

internal/common/Cargo.toml
internal/common/sharedfontique.rs
internal/compiler/passes/embed_images.rs
internal/core/graphics.rs
internal/core/graphics/image/svg.rs
internal/renderers/femtovg/Cargo.toml
internal/renderers/femtovg/fonts.rs
internal/renderers/femtovg/lib.rs

Haven't exhaustively tested this.

feature/fontique - switch femtovg over and use a default fontdb for usvg

---

api/rs/build/Cargo.toml
api/rs/build/lib.rs

Docs: Make explicit that the experimental-module-builds is unstable

---

tools/lsp/ui/components/resizer.slint

Not sure why commit 004ade9d446bd66c86a9baff169cf0fb465a3ea9 removed that code

live-preview: Fix resizing of elements

---

internal/compiler/tests/syntax/imports/library.slint
internal/compiler/tests/syntax_tests.rs

Just testing existing behavior.

syntax tests: add test for importing from non-existing files in libraries

---

internal/compiler/widgets/qt/lineedit.slint

Use the same code as for the fluent style

Qt: fix show/hide password icon

---

docs/astro/src/content/docs/reference/global-functions/math.mdx
internal/compiler/expression_tree.rs
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/llr/optim_passes/inline_expressions.rs
internal/compiler/lookup.rs
internal/interpreter/eval.rs
pnpm-lock.yaml
tests/cases/expr/sign.slint

Add `Math.sign(x)`

---

.github/workflows/ci.yaml
.github/workflows/nightly_tests.yaml

1.89 and later have difficulties compiling

esp-idf: Fix build by pinning to Rust 1.88

---

.github/workflows/material.yaml
ui-libraries/material/docs/src/components/widgets/Announcement.astro

It can then be downloaded from 
https://material.slint.dev/zip/material-1.0.zip

Zip up the Material src and deploy it to cloudflare

---

.github/workflows/autofix.yaml

... in hope that that fixes the missing cargo fmt

CI: pin mise to a newer version

---

.github/workflows/cpp_package.yaml

Use the older toolchain to build the Slint binaries used in the test

CI: Fix esp-idf nightly tests

---

ui-libraries/material/src/ui/components/slider.slint

Fixes the thumb jumping when drag starts.
Fixes the thumb not dragging in a smooth way.
Fixes extra misaligned stop indicator.

Material: Fix Slider UX

---

docs/common/src/utils/utils.ts

Revert "Docs: Fix missing enums and structs"

---

internal/compiler/widgets/cosmic/lineedit.slint
internal/compiler/widgets/fluent/lineedit.slint
internal/compiler/widgets/material/lineedit.slint
internal/compiler/widgets/qt/lineedit.slint

As reported in https://github.com/slint-ui/slint/discussions/9624

LineEdit: call edited callback when the "x" button is pressed

---

internal/backends/qt/qt_window.rs

This fixes a regression seen with 0910024aebe613993d31a451083d5acfbbc0faba
where text outlines no longer rendered with Qt and the text color
was wrong in general.
It turns out drawGlyphRun doesn't work when drawing outlines. It
only uses the current QPen color and that's it - so not a built-in
way to draw the outlines separately. There was also another bug
where we weren't setting the correct QPen color, which regressed
any dark themes. (Presumably because no one expected it to fill
text with the QPen!)
We can fix this by only using drawGlyphRun for filling in glyphs.
For drawing the glyph outlines, we can skip the built-in QPainter
functions altogether and use QRawFont's ability to create
QPainterPaths for us. This restores the text to its previous
appearance while keeping the nicer text …

Qt: Fix outline rendering with Parley

---

internal/compiler/widgets/qt/button.slint

qt: Fix Button.icon-size name

---

.github/workflows/build_docs.yaml
api/rs/slint/lib.rs
internal/interpreter/lib.rs

This reverts commit e952d74e7c5ea7ef1b4748046050cede63e04fb9.
The issue should be fixed

Ci: Revert nightly pin

---

internal/compiler/generator/rust.rs
internal/core/item_tree.rs
internal/core/window.rs
internal/renderers/skia/lib.rs

No intended change of behavior :-)

internal: Cargo + typo fixes
