slint-ui/slint

tools/slintpad/src/dialogs.ts
tools/slintpad/src/index.ts

Back in Slint 1.6, slintpad had a "welcome" page that explained what it is. But the welcome page was removed in commit 588ee3e4740eda68b36ff2f55323b2f2522a42b2 Now it's hard for someone who click on a link to slintpad.com to know what it is and get a link to Slint.
Add an "about" entry in the menu that shows the previous welcome page as a dialog
ChangeLog: Slintpad: add "about" entry in the menu.

Slintpad: add an about dialog

---

tools/lsp/preview.rs
tools/lsp/preview/ui.rs
tools/lsp/ui/api.slint
tools/lsp/ui/views/property-view.slint

Move the model into an extra property and move information irrelevant for the UI behind a callback, so that changing that info will not invalidate the UI.

live-preview: Less model updates for property editor

---

api/rs/slint/private_unstable_api.rs
docs/reference/src/language/builtins/namespaces.md
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/interpreter/eval.rs
tests/cases/expr/mod.slint

Closes #6178
ChangeLog: The mod function was changed to always return a positive value (#6178)

Change `mod()` to always return positive number

---

tools/lsp/common.rs
tools/lsp/main.rs
tools/lsp/preview.rs
tools/lsp/preview/element_selection.rs
tools/lsp/preview/native.rs
tools/lsp/preview/properties.rs
tools/lsp/preview/ui.rs
tools/lsp/preview/wasm.rs
tools/lsp/ui/api.slint
tools/lsp/ui/components/expandable-listview.slint
tools/lsp/ui/components/state-layer.slint
tools/lsp/ui/components/styling.slint
tools/lsp/ui/views/property-view.slint
tools/lsp/wasm_main.rs

This tries to make the property editor nicer.
There are still a lot of limitations though:
* No gradients support at all
* Colors are shown but are not editable at this time. We need more functionality in Slint to work with those (and gradients later!), e.g. conversion from/to string and back.
* When having a property of type `code` (== I have no special handler implemented) that is not listed in the Element, I have no idea how to create one that is syntactically correct. So that is listed as `unset` instead of having an `Add` button like we originally planed.
* Editing values is somewhat limited
* You can start to edit in one LineEdit and then continue in another and that will keep state. That can be confusing, but at least we do keep state of widgets now when updating property data ;-)

live-preview: Work on the property editor

---

api/cpp/include/slint_timer.h
docs/reference/src/language/builtins/elements.md
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/passes/lower_timers.rs
internal/compiler/tests/syntax/elements/timer2.slint
internal/core/timers.rs
internal/interpreter/dynamic_item_tree.rs

Make the `interval` property mandatory in Slint.
A default of 0 is not a great default because that's way too often
In the C++/Rust API, 
don't return an Option, just return 0 when the timer is not started.
As discussed in the API review, the rational is that the interval is
just like a field in a struct and when the struct is default
constructed, it is initialized to 0

Timer: API changes after API review.

---

tools/lsp/preview/properties.rs

.. and put opacity and visibility with the Element that defines them.
I started to sort to make sure those two do not end up in a separate section separate from everything else. But we do want to keep the sequence of groups we encoded, so sorting was not the best idea I had yesterday.

live-preview: Don't list accessibility first

---

tools/lsp/ui/views/property-view.slint

Apply changes from @szecket.
Also add a widget that resets to the property value when loosing focus. Edited fields used to stay around now that our model does not force everything to be redrawn all the time, which was very confusing.
Add back in a highlight when the code is broken and thus not applicable.
Fix the FloatWidget not passing the unit to the backend, thus breaking build all the time.

Widget polish

---

CHANGELOG.md
api/cpp/cbindgen.rs
docs/reference/src/language/builtins/elements.md
examples/carousel/ui/carousel.slint
internal/compiler/builtins.slint
internal/core/items.rs
internal/core/items/input_items.rs
internal/interpreter/dynamic_item_tree.rs
tests/cases/elements/swipegesturehandler.slint

The origin of this proposal is the name of the `swipe-left`, etc. directional, boolean properties. They're missing another verb in their name. In principle the right choice would be "recognize". That is what the type name suggests, that's the term the documentation uses, so the code should read `recognize-swipe-left: true;`. However that is a long word. "Handle" is a verb that's simpler. It's also more generic (that's a downside), but it's otherwise short enough to make things look "right":
```
SwipeGestureHandler {
handle-swipe-left: true;
swiped => { something.naviate-left(); }
}
```
Therefore this patch proposes to rename the type to SwipeGestureHandler and prefixes the boolean directional properties with "handle".

Rename SwipeGestureRecognizer to SwipeGestureHandler

---

tools/lsp/common/document_cache.rs
tools/lsp/preview/properties.rs
tools/lsp/preview/ui.rs

When no bindings exist on the component, the value that is shown in the property editor should be the default value for that property as defined in the base component or in the builtin element. Not just the default value of the type

property editor: Show the default value from base component when no binding exist

---

internal/backends/winit/lib.rs

I am getting this warning:
```
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
warning: missing documentation for a function
--> internal/backends/winit/lib.rs:83:1
|
83 | / pub fn create_gl_window_with_canvas_id(
84 | |     canvas_id: &str,
85 | | ) -> Result<Rc<dyn WindowAdapter>, PlatformError> {
| |_________________________________________________^
|
note: the lint level is defined here
--> internal/backends/winit/lib.rs:6:9
|
6  | #![warn(missing_docs)]
|         ^^^^^^^^^^^^
```
Fix this by adding a tiny bit of documentation

winit: Quieten warning

---

internal/backends/testing/search_api.rs
internal/backends/testing/slint_systest.proto
internal/backends/testing/systest.rs

This is useful when the UI shows for example labels that appear and the screenshot for referenceing is meant to be taken when the opacity animation is complete and the value is (near) 1.0.

ui-testing: Add support for reading the computed opacity of elements

---

tools/lsp/ui/api.slint
tools/lsp/ui/views/property-view.slint

Provide some dummy property data, and provide a preferred height that makes the preview show the properties.
The data is imperfect. But this is how it looks like then:

Make it easier to preview the properties view

---

tools/lsp/ui/components/group.slint

Remove stray horizontal line in library view

---

tools/lsp/ui/components/resizer.slint
tools/lsp/ui/main.slint
tools/lsp/ui/views/preview-view.slint
tools/lsp/ui/views/property-view.slint

It does not work too well and it breaks switching between LineEdits in the property editor. Downside: We have no more way to delete the selected element anymore. We could have it in a tool button, but IMHO we should have Undo before we make it that obvious.
We do have fans of the `Del` key handling... I should probably try to come up with something else. The problem is that the FocusScope loses focus as soon as somebody hits `Tab` and then the key will not be recognized anymore.

live-preview: Remove failed attempt to have global shortcuts

---

tools/lsp/ui/views/preview-view.slint

If the height is contreained but not the width, we should still be able to resize

live-preview: Allow resizing if only one of the dimention is contrained

---

tools/viewer/main.rs

This assumes any string value for an image property is a path. This could be expanded in the future to support loading raw pixel values by e.g. parsing a data URI.
ChangeLog: viewer: `--save-data`/`--load-data`: support for images with paths
Closes #6169.

Support saving/loading images via their path

---

tools/lsp/preview/properties.rs
tools/lsp/preview/ui.rs
tools/lsp/ui/api.slint

All other tools have custom widgets for x/y, width/height, etc., let's try to come close by at least presenting the properties in in a logical order that lends itself to data input.
This reorders geometry to show `x`, `y`, `width` and `height` followed by `z`.
It also orders layout as `min-width`, `min-height`, `preferred-width/-height', and `max-width/height` followed by horizontal and vertical stretch.

live-preview: Re-ordering of properties in property editor

---

internal/compiler/widgets/fluent/checkbox.slint

ChangeLog: Checkbox: fix text color in fluent style 
Fixes #6239

Fluent CheckBox: text should be using the normal text color

---

.github/workflows/ci.yaml
CHANGELOG.md
Cargo.toml
api/cpp/CMakeLists.txt
api/cpp/docs/cmake.md
api/cpp/docs/mcu/generic.md
api/node/README.md
api/node/cover.md
docs/building.md
internal/compiler/generator/rust.rs
internal/compiler/parser.rs
internal/compiler/typeloader.rs

That's the version from March.

Update MSRV to 1.77

---

helper_crates/vtable/macro/macro.rs

```
warning: non-local `macro_rules!` definition, `#[macro_export]` macro should be written at top level module
--> helper_crates/vtable/tests/test_vtable.rs:159:5
|
159 |     #[vtable]
|     ^^^^^^^^^ in this procedural macro expansion
|
= help: remove the `#[macro_export]` or move this `macro_rules!` outside the of the current function `test3`
```
Put the macro in the module with everything else, so it is re-exported with the same visibility

vtable: Prospective fix for warning with the nightly rust compiler

---

tools/lsp/preview/native.rs

This makes it a little clearer that this hides.
You can still quit the process via cmd+q when cmd+tab is shown, as well as via the context menu in the dock.

macOS: Rename "Quit" to "Close" in the system menu bar

---

internal/compiler/namedreference.rs
internal/compiler/passes/binding_analysis.rs
tests/cases/properties/changes.slint

If the property was not used, it was optimized out and the compiler would panic
Fixes #6331
ChangeLog: compiler: Fix changed callback of an unused property

Fix changed callback of an unused property

---

tools/slintpad/src/dialogs.ts
tools/slintpad/styles/content.css

.. and only print the URL after it: That way the button stays visible at all times.
Closes: #6318

slintpad: Move the copy URL button to the front

---

internal/core/textlayout/fragments.rs
internal/core/textlayout/linebreaker.rs

Fixes #6346
ChangeLog: Software renderer: fixed `char-wrap` not braking between lines

Text layout: fix `char-wrap` doesn't wrap between lines

---

tools/lsp/preview/drop_location.rs

Fix panic when dragging objects onto layouts that have an x/y coordinate set. The hit rect was miscalculated, taking the origin of the layout into account when calculating its size.

live-preview: Fix panic when dragging elements onto layouts

---

tools/slintpad/src/dialogs.ts
tools/slintpad/styles/content.css

This backs out commit 10139a26adbd7b4fd71ad98d48ee84d30a818499
... and then changes the original code to wrap anywhere instead as suggested in #6333.
Fixes: #6333

slintpad: Move the copy URL button to the the back again

---

api/rs/slint/private_unstable_api.rs
tests/cases/focus/text-input-focused-parent-deleted.slint
tests/cases/models/delete_from_clicked.slint

Note that i was unable to reproduce the panic.
Even when actually trying to produce it in the tests.
I've changed the test to add a few property, this shouldn't reduce the coverage of what they were testing before.
Closes #6262

Rust: attempt to gracefully handle situation where the property depends on a binding from a destroyed component

---

examples/weather-demo/ui/about-box.slint
internal/compiler/layout.rs
internal/compiler/passes/default_geometry.rs
tests/cases/layout/issue6285_auto_explicit_restrictions.slint

Fixes #6285
ChangeLog: Fixed geometry constraints when they are partially infered from the content, and partially infered from the explicit constraints

Layouting: Take in account explicit constraints when generating layout info base on content

---

api/node/rust/lib.rs
api/node/rust/types/model.rs

At this point the exception _was_ thrown.

Node.js: Fix tense in error messages produced when exceptions are throw

---

examples/mcu-board-support/README.md

Probe-run is deprecated in favour of probe-rs:
https://ferrous-systems.com/blog/probe-run-deprecation/
Update the docs to use probe-rs. Tested directly with a Raspberry Pi Pico and STM32H735G-DK.

doc: Prefer probe-rs

---

internal/core/items/input_items.rs
tests/cases/elements/swipegesturehandler.slint

- Remove the duration threshold
- Always register the swipe even if the pointer went in another direction before
- set the current position on the release event (in case there was no mouve to that position before)
ChangeLog: adjusted threshold in the SwipeGestureHandler
Closes #6344
Probably also helps for #6350

SwipeGestureHandler: improve behavior

---

api/cpp/include/slint_string.h
api/cpp/tests/datastructures.cpp

The length is an important property of a string and should be available as a getter IMO. The new `size()` method is consistent with `std::string`.
This is my first contribution and I didn't open an issue for it :see_no_evil: Don't hesitate to ask me for adjusting anything or close the PR if a `size()` method is not desired.
I suspect the API documentation will be auto-generated from the code(?).

C++: Add size() method to SharedString

---

docs/reference/src/language/syntax/properties.md
internal/compiler/passes/resolving.rs
internal/compiler/tests/syntax/new_syntax/two_way_input_output.slint
internal/compiler/typeregister.rs
internal/compiler/widgets/common/lineedit-base.slint
tools/lsp/ui/views/preview-view.slint
tools/lsp/ui/views/property-view.slint

ChangeLog: deprecated two way binding between `in` and `in-out` property
Fixes #6400

Binding between a read only property to input-output is deprecated

---

internal/core/items/input_items.rs
tests/cases/elements/toucharea.slint

ChangeLog: TouchArea: Send cancel event and update `pressed` and `has-hover` property when `enabled` is set to false while pressed.
Fixes: #6422

TouchArea: send cancel event when disabled while pressed

---

internal/renderers/skia/itemrenderer.rs

When a box shadow is the only child of an opacity item, we don't create an intermediate opacity layer (good). Without the opacity layer, it's mandatory to apply the current opacity though, which commit b5c61fb2f5198389995a9e7f812f2b2cfeb51c24 did, except it missed this one draw_image call for the box shadow itself.
Fixes #6359

Skia: Fix opacity not being applied to box shadows correctly

---

api/cpp/cmake/SlintMacro.cmake

Use case:
For the higher compilation speed, we hope to use `as-absolute-path` in Debug but `embed-files` in Release.
```cmake
set_property(TARGET ${PROJECT_NAME} PROPERTY SLINT_EMBED_RESOURCES $<IF:$<CONFIG:Debug>,as-absolute-path,embed-files>)
```

feat(cpp): support generator expression for `SLINT_EMBED_RESOURCES` & `SLINT_SCALE_FACTOR`

---

tools/lsp/Cargo.toml

`cargo-machete` suggests unused dependencies, follow up on its report.
Let's see what Ci thinks of it...

lsp: Follow up `cargo-machete`

---

internal/core/Cargo.toml
internal/core/graphics/image.rs
internal/core/window.rs

Just disable the clippy warning about unnecessary cast: All current occurrences are due to `Coord` being an alias to f32 almost all the time and the cast is necessary when it is not.
Just fallout to not have too many issues pop up in my editor :-)

core: Fix some clippy warnings

---

internal/core/window.rs
internal/core/window/popup.rs

This is the smallest possible improvement we can do for popup placement: Do not render popups outside the surface they can paint on!

core: A small step to better popup placement

---

internal/core/software_renderer.rs
internal/core/software_renderer/draw_functions.rs

We were assuming that the extra clip was always on a unrotated image, the rendering code didn't account for rotated screens

Software renderer: fix drawing partialy clipped texture with rotation

---

api/rs/build/lib.rs

The `compile_with_config` function has a dependency on environment variables. It would be better if I could run a function that doesn't depend on these variables, so I can also run it inside a build system such as Bazel. I introduced a new function `compile_input_output_with_config` that doesn't need environment variables. If necessary I can also still add some tests.

Remove dependency on Cargo variables in a helper function for the Slint to Rust compiler

---

internal/backends/winit/winitwindowadapter.rs

Under Windows, the big icon is shown at least in the ancient Alt+Tab dialog, which can be restored via registry tweak.
Previously, Slint windows including the VS Code preview window only had a stock icon in the [old Alt+Tab dialog](https://www.thewindowsclub.com/how-to-change-alttab-settings-in-windows-10) on Windows (which is needed for Alt+Esc to work), because Slint only called winit's [`set_window_icon()`](https://docs.rs/winit/latest/winit/window/struct.Window.html#method.set_window_icon), and not also [`set_taskbar_icon()`](https://docs.rs/winit/latest/winit/platform/windows/trait.WindowExtWindows.html#tymethod.set_taskbar_icon). See also [`WM_SETICON`](https://learn.microsoft.com/en-us/windows/win32/winmsg/wm-seticon).
This PR makes Slint now also call `set_taskbar_icon()` with an …

Set icon also as big winit window icon for increased compatibility.

---

internal/compiler/generator/rust.rs
tests/cases/callbacks/init_popup.slint

Don't run the `init=>` callback in popup twice
ChangeLog: rust: Fixed `init=>` callback on PopupWindow ran twice.

Rust generator: don't run the init code twice for popups

---

internal/interpreter/eval.rs

When calling `popup.show()` the parent itemtree of the popup should be the one from the parent in which the PopupWindow is declared in the source, and not the one of the context in which the `popup.show()` code appears.
Part of issue #6426.
This happens to fix the issue as presented there.
But there is another issue in which we still crash when trying to access global from a popup who's parent has been deleted because the interpreter needs access to the root item tree to access the globals

interpreter: Fix wrong parent item tree of the PopupWindow

---

api/rs/slint/docs.rs

This makes it clear that you can expect that the Slint code isn't called in the next event loop run or so, but immediately.
Is this factual?

Clarify that components' `invoke_...()` calls through synchronously.

---

internal/core/items/text.rs
tests/cases/widgets/textedit.slint

ChangeLog: Fixed TextInput mouse cursor after left click
Fixes #6444

TextInput: don't reset mouse cursor when left-clicking

---

tools/lsp/ui/views/preview-view.slint

Consider changes to min/max size of the preview whenever they change and extract some common lines into a function.
Fixes: #6377

live-preview: Always consider min/max size of the preview

---

tools/lsp/ui/views/preview-view.slint

This covers one case where the selection rectangles are wrong: When the window size changes.
Fixes: #6438

live-preview: Reselect element after preview area changed size

---

editors/vscode/src/browser.ts
editors/vscode/src/common.ts
editors/vscode/src/extension.ts

Since we work on file paths in the compiler but get URLs from the editor, we end up normalizing URLs down to paths.
In #6375 we open a git diff view, which VSCode considers to be `slint` language to highlight it properly. So it will also sends data to the LSP, using `git:/file/path?lots&of&meta&data` as the buffers URL. We normalize that to /file/path and then update that files contents with (parts of) the diff view. Not too surprising: This triggers errors.
The normalization does not happen in the same way in WASM, so slintpad should be immune to the problem.
I considered to just reject "old" versions, but that can go wrong if you open a diff view first and only then the actual file. It will take a couple of changes to the file to be "newer" than the diff and it will be ignored till …

lsp: Ignore url schemes

---

examples/imagefilter/node/main.ts
examples/imagefilter/node/package.json
examples/imagefilter/node/tsconfig.json
pnpm-lock.yaml

Jimp have updated their api after hitting 1.0. This PR:
Updates Jimp to 1.6.
Updates the example to use Jimp.toBitmap().
Turns on the typescript incremental compiler (faster start).

Update node imagefilter for latest 'jimp'

---

tools/lsp/language/completion.rs

So that it preserves `-` vs. `_` in element id and global names
Fixes #6479
ChangeLog: LSP: preserve `_` when auto-completing element identifiers

LSP: autocompletion: de-normalize the element id

---

internal/core/items/input_items.rs
internal/interpreter/eval.rs
tests/cases/elements/swipegesturehandler.slint

It was documented and implemented in the compiler, but not in the runtime

SwipeGestureRecognizer: fix cancel() function

---

internal/compiler/lib.rs
internal/compiler/passes/embed_images.rs
tools/lsp/preview.rs

... which will list all resources that are not going to get embedded as `None` in the Document's `embedded_file_reosurces`.
The idea is to use that field to find all used resources in the live preview so that we know what we can watch.
This is at this point a demo to show what using the `Document::embedded_file_resources` for resource listing in the live preview would entail for the compiler.
I'd suggest to rename the field itself to `resources` and to collect this information even when no embedding is requested (most users won't see it anyway) to not have this `ListAllResources` enum value...

WIP: compiler: Add a `ListResources` option for resource embedding

---

tools/lsp/language.rs
tools/lsp/preview.rs

These are two patches:
1. Store the absolute image path to the `Expression::ImageReference`
2. Use that data in the live-preview
I am a bit uncertain whether 1. is actually needed: The "normal" images I expect to see in the Live Preview have a `resource_ref` of `Absolute(String)`, which contains the absolute path to the image already. I just wanted to make sure this will continue to work, even if we start to embed images (or decide to add some other way to access image data).
Something else I am not too happy about is that I am back to watching `**/*`. I *suspect* that VSCode watches everything anyway and the pattern I pass to VSCode is just filtering what gets sent to my LS (which reduces the amount of data to serialize/sent/deserialize by a bit).

live-preview: Reload when images change on disc

---

internal/core/api.rs

Fixes #6534
ChangeLog: [Rust] Derive serde traits for `PhysicalPosition`, `LogicalPosition`, `PhysicalSize` and `LogicalSize`

Derive serde for `PhysicalPosition`, `LogicalSize` etc.

---

internal/core/timers.rs

- When stopping a running but not yet expired timer from within the activation callback of an expired timer, the stopping would fail to find the timer in the active_timers list because it was built on the fly. Similarly, restarting a future timer form within the same kind of callback would end up registering the active timer twice. Fix this by doing all the active_timer re-setup before activating any callbacks, so that by the time of activation the data structure is in a good state.
- When two timers expire at the same time and from the callback of the first, the second timer would be dropped/deleted, the timer's `being_activated` was overwritten and the timer was deleted too early, causing a panic. Fix this by preserving the removal state.
Fixes #6187
Fixes #6505

Fix two issues with the timer handling

---

.github/workflows/build_docs.yaml
.github/workflows/ci.yaml
.github/workflows/fmt_lint_typecheck.yaml
.github/workflows/wasm_editor_and_interpreter.yaml
docs/editor/codemirror.js
docs/editor/language-facets.js
docs/editor/package.json
docs/editor/rollup.config.js
pnpm-lock.yaml
pnpm-workspace.yaml

Centralize formatting/lint checks for npm projects, Rust, and C++

---

tools/lsp/language.rs
tools/lsp/language/goto.rs
tools/lsp/language/test.rs

Just a small cleanup I ran into over the WE.

lsp: Consitently use the `DocumentCache` from `common`

---

internal/compiler/parser.rs
internal/compiler/parser/expressions.rs
internal/compiler/tests/syntax/fuzzing/6512.slint

Fixes #6512
The TrPlural must always have an expression otherwise it panics later. (Also adjust the panic message when nodes are missing)
(edit: in the first push of this PR, i had the wrong issue number)

Fix invalid node generated while parsing invalid `@tr`

---

.github/workflows/ci.yaml
.github/workflows/nightly_snapshot.yaml
.github/workflows/publish_npm_package.yaml
.github/workflows/slint_tool_binary.yaml
api/rs/slint/private_unstable_api.rs
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs

macOS 12 will be phased out later this year and start failing randomly:
https://github.com/actions/runner-images/issues/10721
macOS-13 runners are still on x86-64, so this should be a no-op.

CI: switch from macOS-12 runners to macOS-13

---

tools/lsp/language.rs
tools/lsp/main.rs

lsp: Use constant instead of repeating a `slint/showPreview`

---

Cargo.toml
api/wasm-interpreter/Cargo.toml
internal/backends/winit/Cargo.toml
internal/core/Cargo.toml
internal/renderers/femtovg/Cargo.toml
internal/renderers/femtovg/lib.rs

Use set_fill_style_str instead, it avoids constructing a JSValue from a str.

femtovg: Fix warning about deprecated web_sys::set_fill_style

---

api/cpp/include/slint-testing.h
docs/reference/src/language/builtins/elements.md
examples/energy-monitor/ui/widgets/list_view.slint
internal/backends/testing/search_api.rs
internal/backends/winit/accesskit.rs
internal/compiler/typeregister.rs
internal/compiler/widgets/cosmic/components.slint
internal/compiler/widgets/cupertino/components.slint
internal/compiler/widgets/fluent/components.slint
internal/compiler/widgets/material/components.slint
internal/core/accessibility.rs

Adds the `accessible-selectable` and `accessible-selected` properties which applies to list items. Uses them in the standard list view and in examples where appropriate. Implements them in the AccessKit backend.

Add `accessible-selectable` and `accessible-selected` properties

---

internal/compiler/passes/resolving.rs
internal/compiler/tests/syntax/fuzzing/6519.slint
internal/compiler/tests/syntax/new_syntax/two_way_input_output.slint

Fix compiler panic binding to property with syntax error

---

tools/lsp/preview/native.rs

macOS: Add support for reloading the preview via cmd+r

---

tests/cases/layout/materialized_minmax.slint

Don't cast FLT_MAX to int, that's undefined behaviour.

Fix materialized_minmax test failing on aarch64-apple-darwin

---

internal/core/Cargo.toml
internal/core/software_renderer.rs
internal/core/software_renderer/fonts.rs
internal/core/software_renderer/fonts/systemfonts.rs

Everything is already working, just had to play around with a few cfgs. The sharedfontdb module already takes care of including DejaVuSans as default fallback font.
The rest is plug and play. This works if the project is compiled with Rust directly, rendere-femtovg is excluded but renderer-software is included. Then it gets selected as default renderer and this all works. I'll create a separate PR for allowing selecting the software renderer for the wasm-interpreter.

Enable support for WASM builds with the software renderer

---

internal/backends/qt/qt_window.rs

Commit 5718b1589904ef8b2666e4cfc0bbb661a6eaa5c4 regressed this by issuing the update on the window, which breaks when the widget is embedded in a hierarchy (like a QGraphicsView). We really need to mark the widget as dirty, even if that means we don't get frame throttling then.

Fix missing redraws when embedding Slint into QWidget hierarchy

---

internal/interpreter/Cargo.toml
internal/interpreter/dynamic_item_tree.rs
tools/lsp/Cargo.toml

This impact everything that use the interpreter with wasm:
- docs preview
- slintpad
- vscode wasm preview

Interpreter: on wasm, check the user agent to resolve the native style

---

internal/backends/winit/accesskit.rs
internal/compiler/widgets/cosmic/components.slint
internal/compiler/widgets/cupertino/components.slint
internal/compiler/widgets/fluent/components.slint
internal/compiler/widgets/material/components.slint

We need to explicitly set the `accessible-label` property on the `ListItem` for the label to appear in the accessibility tree. I decided to move all accessibility related properties in the same place to be consistent and to ease maintenance.
Also tell AccessKit that `ListItem` components can receive keyboard focus, as described in #6554.

Fix `ListItem` accessible tree representation

---

docs/reference/src/language/concepts/translations.md

When the score is not one, plural form should be used

doc: Fix typo in plurals example

---

internal/compiler/embedded_resources.rs
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/passes/embed_images.rs
internal/compiler/typeloader.rs

Fix loading of additional slint source files as well as of urls in `@image-url`.
This makes the current slintpad render the printerdemo just as slintpad.com does... which still looks like it is missing the tab below the icons. Was that changed?

Slintpad fixes

---

internal/compiler/parser/document.rs
internal/compiler/tests/syntax/fuzzing/6588.slint
internal/compiler/tests/syntax_tests.rs

Fix #6588
Note for the test: parse error at the end of the file are actually reported at offset 0. Use a trick to add more `^` at the beginning to mean that.
(Offset 0 is actually offset 1 as the column starts at 1)

Fix parsing of unfinished `import` statement

---

internal/backends/winit/accesskit.rs
internal/compiler/widgets/common/listview.slint

Fixes #6554 
Considers the `accessible-delegate-focus` property when building tree updates for AccessKit.
This fixes accessibility of both the `StandardListView` and the `TabList`.
The only issue is that it breaks when items are off-screen. In the case of the 7GUIs/CRUD example, only the two first items are shown and arrowing down to the third seem to not trigger a rebuild of the tree, which leads to the "AccessKit focus" being placed on the root window. I suspect a bigger issue here as using the keyboard inside the list view seem to not trigger repaints as well, and seem to interfer with the mouse too.

Implement `accessible-delegate-focus` for the AccessKit backend

---

tools/lsp/preview/ui.rs

"native used to be the first. That is no longer the case as we sort the list.
So look for native, or take the first if that is not in the list or default to a default constructed string.
The "use first" is unnecessary at this time as "native" is always in the list, but I thought I'll keep that just in case we remove native at some point.

live-preview: Default to "native" as expected (if that is available!)

---

examples/uefi-demo/Cargo.toml
examples/uefi-demo/main.rs

Also disable the compilation if not targetting uefi to avoid error about duplicated panic handler in rust analyzer

uefi-demo: update dependencies

---

.github/workflows/cpp_package.yaml
.github/workflows/nightly_snapshot.yaml
.github/workflows/publish_npm_package.yaml

The Python version installed on the GH runners via homebrew removes the pipes module, which the Skia build needs until https://github.com/slint-ui/slint/issues/6615 is fixed.

Pin Python version for Skia builds on macOS

---

api/rs/slint/lib.rs
internal/backends/android-activity/androidwindowadapter.rs
internal/backends/linuxkms/renderer/skia.rs
internal/backends/selector/lib.rs
internal/backends/winit/lib.rs
internal/backends/winit/renderer/femtovg.rs
internal/backends/winit/renderer/femtovg/glcontext.rs
internal/backends/winit/renderer/skia.rs
internal/backends/winit/renderer/sw.rs
internal/backends/winit/winitwindowadapter.rs
internal/core/api.rs
internal/core/lib.rs
internal/renderers/skia/d3d_surface.rs
internal/renderers/skia/lib.rs
internal/renderers/skia/metal_surface.rs
internal/renderers/skia/opengl_surface.rs
internal/renderers/skia/software_surface.rs
internal/renderers/skia/vulkan_surface.rs

For now, allow the API consumer to request an OpenGL API (OpenGL or OpenGL ES) and a backend (Skia, femtovg, or software).
This is a rough draft:
- Currently only implemented for winit.
- I'm not a fan of how I threaded `OpenGLApi` everywhere (especially in functions that have nothing to do with OpenGL like `SoftwareSurface::new()` but share a trait with OpenGL functions), but I wanted to get a rough initial implementation up to start the conversation.
- Specifically, it feels awkward passing it through `WinitCompatibleRenderer::resume` but that seemed to be the common point between Skia and femtovg where the OpenGL context is created.
Related discussion: https://github.com/slint-ui/slint/discussions/6482
ChangeLog: Add PlatformBuilder API for requesting backend features

Add PlatformBuilder API for requesting backend features

---

internal/backends/android-activity/androidwindowadapter.rs
internal/backends/android-activity/lib.rs
internal/core/api.rs
internal/core/platform.rs
internal/core/timers.rs

Destroy means we need to exit the event loop.
And android_main will be called again from another thread, so we need to support reseting the proxy
There is also a bug in the timer when exiting the app that this worked around
Fix #6626

Android: handle properly the Destroy event

---

internal/interpreter/dynamic_item_tree.rs

Copying potentially thousands of properties for no reason is something that can be easily optimized away to save a bit of time:
Before:
```
Benchmark 1: ./target/release/slint-viewer ../slint-perf/app.slint
Time (mean ± σ):      1.108 s ±  0.015 s    [User: 0.792 s, System: 0.231 s]
Range (min … max):    1.085 s …  1.133 s    10 runs
```
After:
```
Benchmark 1: ./target/release/slint-viewer ../slint-perf/app.slint
Time (mean ± σ):      1.082 s ±  0.019 s    [User: 0.773 s, System: 0.214 s]
Range (min … max):    1.054 s …  1.117 s    10 runs
```

Only clone the public properties for the exported component

---

internal/compiler/passes/embed_glyphs.rs
internal/core/software_renderer.rs

- include the ' ' char that doesn't have a bounding box but need to be included for the advance_x
- Fix an off by one in rendering where the last pixel was missing

swrenderer: Small fixup in distance field

---

internal/compiler/passes/resolving.rs

Instead of doing potentially multiple calls in the chained calls, each of which would allocate in rowan, we now only call the iterator function once and then leverage `find_map`. This is arguably even more readable and it removes ~300k allocations and speeds up parsing.
Before:
```
Time (mean ± σ):     930.7 ms ±  15.1 ms    [User: 678.7 ms, System: 165.5 ms]
Range (min … max):   906.4 ms … 956.3 ms    10 runs
allocations: 2339130
```
After:
```
Time (mean ± σ):     914.6 ms ±  22.7 ms    [User: 649.6 ms, System: 174.5 ms]
Range (min … max):   874.8 ms … 946.3 ms    10 runs
allocations: 2017915
```
**NOTE:** The absolute numbers above are not correct as I measured this on top of my other changes. The relative impact should be still applicable though.

Optimize: Filter/map rowan nodes instead of doing multiple lookups

---

internal/core/software_renderer.rs

Instead of using the trick of taking a sub-slice and pretending the image was smaller than it is.
Then this is more uniforpm with all the other rendering path. And this should prevent the panic in #6643
fixes #6643

swrenderer: Always use an offset in the image when rednering glyphs

---

api/cpp/include/slint.h
api/rs/slint/private_unstable_api.rs
internal/compiler/Cargo.toml
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/lib.rs
internal/compiler/llr.rs
internal/compiler/llr/expression.rs
internal/compiler/llr/item_tree.rs
internal/compiler/llr/lower_expression.rs
internal/compiler/llr/lower_to_item_tree.rs
internal/compiler/llr/optim_passes/inline_expressions.rs
internal/compiler/llr/pretty_print.rs
internal/compiler/llr/translations.rs
internal/core/context.rs
internal/core/translations.rs
tests/cases/translations/bundle.slint
tests/cases/translations/fr/LC_MESSAGES/bundle.po
tests/cases/translations/up/LC_MESSAGES/bundle.po
tests/driver/cpp/Cargo.toml
tests/driver/cpp/cppdriver.rs
tests/driver/rust/Cargo.toml
tests/driver/rust/build.rs

Add a way for the compiler to bundle translations in the generated code.
So it can work with MCU and wasm
Part of #3715
TODO:

bundle translations

---

api/cpp/include/slint-testing.h
api/cpp/lib.rs
docs/reference/src/language/builtins/elements.md
internal/backends/qt/qt_widgets/listviewitem.rs
internal/backends/testing/search_api.rs
internal/backends/winit/accesskit.rs
internal/compiler/builtins.slint
internal/compiler/typeregister.rs
internal/compiler/widgets/common/listview.slint
internal/compiler/widgets/cosmic/components.slint
internal/compiler/widgets/cupertino/components.slint
internal/compiler/widgets/fluent/components.slint
internal/compiler/widgets/material/components.slint
internal/core/accessibility.rs

These two properties aren't yet implemented by AccessKit's platform adapters but I have tested that they indeed work as expected on my work-in-progress branch to add listbox support to AccessKit.
They allow assistive technologies to provide hints to users about where they are inside group widgets, to quickly tell how many choices are available (radio buttons) or their location in a potentially large list (list views, equivalent to the visual indication given by the scroll bar). They are especially useful if not elements are currently present in the tree. They correspond to ARIA's `aria-posinset` and `aria-setsize` properties.
Changelog: Add `accessible-position-in-set` and `accessible-size-of-set` properties

Add set-related accessible properties

---

internal/core/software_renderer.rs
internal/core/software_renderer/fonts.rs
internal/core/software_renderer/fonts/pixelfont.rs
internal/core/software_renderer/fonts/vectorfont.rs

The trick is that we should have a constant delta, regardless of the size of the individual glyphs.

Small polish of the appearence of small glyph with sdf

---

docs/reference/src/language/widgets/textedit.md
internal/compiler/widgets/common/textedit-base.slint
internal/compiler/widgets/cosmic/textedit.slint
internal/compiler/widgets/cupertino/textedit.slint
internal/compiler/widgets/fluent/textedit.slint
internal/compiler/widgets/material/textedit.slint
internal/compiler/widgets/qt/textedit.slint

I thought there was only `LineEdit` and `TextInput`, I didn't realize there was also a `TextEdit` in my first pr #6649. This adds the `rejected` callback to `TextEdit` as well.

Added rejected to TextEdit

---

internal/backends/qt/qt_window.rs
internal/core/window.rs
tests/cases/elements/popupwindow_nested.slint

Fixes https://github.com/slint-ui/slint/issues/4356
Still not perfect:
- Calling several times `popup.show()` on the same popup, will open
that popup multiple times (instead of being a noop once opened)
- Calling `some-popup.close()` will always close the top of the stack,
without considering if it is the `some-popup` or another popup.
Both problems are because we don't remember whether a particular popup
is open and we don't associate `close()` with a particular popup

Support for multiple PopupWindow

---

api/cpp/include/slint_window.h
internal/backends/qt/qt_window.rs
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/llr/lower_expression.rs
internal/core/window.rs
internal/interpreter/dynamic_item_tree.rs
internal/interpreter/eval.rs
tests/cases/elements/popupwindow_nested.slint
tests/cases/elements/popupwindow_open_twice.slint
tools/lsp/preview.rs

Each PopupWindow stores an ID for the active popup associated with it so `popup.close();` closes the correct popup, and so a single PopupWindow cannot be opened multiple times.

Associate `PopupWindow`s with an ID for their active popup

---

.github/workflows/ci.yaml
.github/workflows/cpp_package.yaml
.github/workflows/slint_tool_binary.yaml
internal/backends/qt/build.rs

Closes #6586
ChangeLog: binary package build with Qt now uses Qt6

CI: update Qt, defaults to Qt6 for the linux binaries

---

internal/core/items/input_items.rs
tests/cases/elements/swipegesturehandler.slint
tests/cases/elements/swipegesturehandler2.slint

SwipeGestureHandler: currectly grab the mouse

---

tools/lsp/ui/main.slint
tools/lsp/ui/views/header-view.slint

the toggle that existed is the same as toggling a button - whcih can sit next to the closed library and properties.  
properties should be editable while selection is active so those should be openable / visible whether in edit mode or not.  
STILL TODO: 
- make dragging from library automatically into edit mode
- add settings to either single select 'inspect' button or toggle on off
- change display of active icon OR add icon for toggled mode for clearer display than blue icon for inspect

attempting a header change to optimize usability

---

tools/lsp/preview/element_selection.rs

Unconfuse selecting something with a drop shadow. That is a extra compiler-generated element that gets added before the actual element we are looking for.

live-preview: Unconfuse selection with a drop shadow

---

tools/lsp/language.rs

Version 3.17 of the spec added a `position_encoding` field in the ServerCapabilities, so use that.
Note that the spec says that UTF-16 is mendatory, and vscode only support utf-16, meaning we currently have a bug when having non-ascii in the source (#5669)

LSP: report that we use UTF-8 to client that supports it

---

internal/compiler/langtype.rs
internal/compiler/tests/syntax/lookup/for_lookup.slint

Instead of panicking.
Attempt to fix it in #6765 didn't work for C++.
Code generation might be hard for C++, so I thought it's better to error out.
Fix #6760

Error when making a `for` over an empty array

---

internal/compiler/passes/deduplicate_property_read.rs
tests/cases/issues/issue_6616_optimized_property_read.slint

the deduplicate_property_read was bailing out the replacement if one part of the coinditional branch do assignment. But the other part might already have partial assignment, so we must continue
Fixes #6616

Fix wrong optimization trying to merge common properties around assignments

---

tools/lsp/ui/api.slint
tools/lsp/ui/main.slint
tools/lsp/ui/views/preview-view.slint

That mode can no longer get enabled, so get rid of the entire thing.

live-preview: Remove dead code related to design mode

---

tools/lsp/ui/views/preview-view.slint

@szecket brought this up as part of a bigger patch set. I just extracted this out.

live-preview: Stay in select-mode after selecting something

---

internal/core/model.rs
tests/cases/models/init_recursion.slint

Don't call init() while mutably borrowing the repeater's inner.
Fixes #3214

Fix panic when code in init callback of conditional/repeater re-triggers repeater traversal

---

api/rs/build/Cargo.toml
api/rs/build/lib.rs
demos/printerdemo/rust/Cargo.toml
demos/printerdemo/rust/build.rs
demos/printerdemo/rust/lib.rs

slint-build: Add config option to set the path for bundled translations

---

tools/lsp/preview/ui.rs
tools/lsp/ui/api.slint
tools/lsp/ui/views/property-view.slint

made some finesse tweaks to the pre-existing layering and display layout for the preview pane

Sub attributes2

---

api/node/build.rs

```
error: unexpected `cfg` condition value: `noop`
--> api/node/rust/lib.rs:17:1
|
17 | #[napi]
| ^^^^^^^
|
= note: expected values for `feature` are: `accessibility`, `backend-linuxkms`, `backend-linuxkms-noseat`, `backend-qt`, `backend-winit`, `backend-winit-wayland`, `backend-winit-x11`, `default`, `renderer-femtovg`, `renderer-skia`, `renderer-skia-opengl`, `renderer-skia-vulkan`, `renderer-software`, and `testing`
= help: consider adding `noop` as a feature in `Cargo.toml`
= note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
= note: `-D unexpected-cfgs` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(unexpected_cfgs)]`
= note: this error originates in the attribute …
```

Prospective CI fix for warnings about unexpected cfg

---

internal/core/model.rs
tests/cases/callbacks/init_listview.slint

This also fix changed event not working as they rely on the init to the setup
Fixes #6836
ChangeLog: fix init and changed callback not always being called in ListView

Fix calling init to all the items on a ListView

---

.github/dependabot.yml

Dependabot will no longer group the npm PR's into 2 huge patch and major PR's. Instead it will now create about 15 small pr's for each of the seperate dependancies. Some things are grouped such as the vscode engine libs and we can group more.
The thinking here is that when this PR lands dependabot will close the old PR's and open 10-20 new ones. Pretty much most of which we can approve right away and will not see again. But now the troublesome ones such as the node api test framework which we don't want to upate for now can be closed. Dependabot will then ignore that framework till a new update comes out.

Stop dependabot grouping large PR's

---

internal/backends/winit/accesskit.rs
internal/backends/winit/event_loop.rs
internal/backends/winit/winitwindowadapter.rs

Fix AccessKit adapter life cycle and clean up winit window creation code

---

api/cpp/include/slint.h
api/cpp/lib.rs
api/node/rust/lib.rs
api/node/typescript/index.ts
api/python/lib.rs
api/python/slint/__init__.py
internal/backends/qt/qt_window.rs
internal/backends/winit/winitwindowadapter.rs
internal/core/api.rs
internal/core/context.rs
internal/core/window.rs

ChangeLog: Added function to set the XDG app id on Wayland/X11. This needs to be added with respective function names in the language sections.
Fixes #1332

Add API to set the XDG app id

---

.github/dependabot.yml

The previous limit was 5 and this is now raised to 20

Allow dependabot to raise more PR's

---

tools/lsp/ui/components/selection-popup.slint

Just add eliding to all texts in the Selection Popup. I have not managed to reproduce the horizontal scaling issue yet, but this should fix it :-)

live-preview: Elide text in the selection popup

---

tools/lsp/preview/element_selection.rs

The component was mentioned when it was used in the code, so filter out the frame for the component definition itself.
Since one element in the test case is filtered out, I had to remove a couple of steps in the relevant test.

live-preview: Do not show components in selection popup

---

internal/compiler/typeloader.rs
tools/lsp/common/document_cache.rs
tools/lsp/language.rs
tools/lsp/language/test.rs
tools/lsp/main.rs

The change in https://github.com/slint-ui/slint/pull/6747 invalidated the cache, but it was only reloaded when one of the dependent was reloaded. We need to reload the cache for all open file so that LSP feature continue to work on open document even if they get no changes

LSP: fix reloading loaded dependencies

---

tools/lsp/preview.rs
tools/lsp/preview/element_selection.rs
tools/lsp/preview/ui.rs

Have the selection popup actually highlight the hovered object in the editor.
We did not have this use case before: We used to either highlight after an update or never at all. Neither semantic matches what we are doing in the selection popup, so I added a highlight-now flag.

live-preview: Have the selection popup highlight locations

---

tools/lsp/language/goto.rs
tools/lsp/language/hover.rs
tools/lsp/language/token_info.rs

Do not show the file name when hovering the string constant inside a @image-url, show the image instead.

LSP: Show the image when hovering an @image-url

---

api/rs/slint/tests/partial_renderer.rs
internal/core/software_renderer.rs

When rounded out, the dirty region might end up bigger than the size of the screen, which would then result in panic while trying to draw a pixel out of the screen.
Fixes #6932

swrenderer: intersect the dirty region with the screen rectangle

---

docs/src/content/docs/platforms/desktop.mdx

Closes #3235. I left the Node.js example with TODO while I am not familiar with it.

docs:handle the console on Windows

---

docs/astro.config.mjs
docs/src/content/docs/platforms/index.mdx

- Remove Python as we don't have API docs yet
- Add the beta label to the JS integration (see #4471)

Tweak API references links

---

internal/compiler/expression_tree.rs
internal/compiler/tests/syntax/basic/linear-gradient.slint
internal/compiler/tests/syntax/basic/radial-gradient.slint

compiler: Warn user when immediately converting gradient macro to color

---

internal/compiler/typeregister.rs

`MenuBar` is a special child of `Window` but it shouldn't be accepted since it is experimental.

Don't allow internal elements that are special child

---

docs/src/components/SlintProperty.astro
docs/src/content/docs/reference/gestures/swipegestrurehandler.mdx
docs/src/content/docs/reference/std-widgets/datepicker.mdx
docs/src/content/docs/reference/window/popupwindow.mdx
docs/src/utils/utils.ts

This puts in the start of struct supports in the docs.
It also now generates warnings for missing structs.

1.9 docs: Support common structs

---

docs/ec.config.mjs
docs/src/content/docs/guide/development/localization.md
docs/src/content/docs/tutorial/from_one_to_multiple_tiles.mdx
docs/src/content/docs/tutorial/memory_tile.mdx

The docs don't just have Slint language files. They have Rust, Cpp, Javascript, bash, etc files. This change shows a little language hint to make it clear what the language is.
It fades away on hover to be replaced by the copy/paste or slint pad icons.

1.9 docs: Show snippet language

---

internal/compiler/passes.rs
internal/compiler/passes/focus_handling.rs
internal/compiler/tests/syntax/fuzzing/6979.slint

Do the purity check before doing the transformation of the `focus()` function, so the source location of the error is the most accurate
Fixes #6979

Fix purity check for `focus()` on custom component

---

internal/core/items/text.rs
tests/cases/text/cursor_move.slint

When a TextInput has a selection and a forward or backward movement is performed (i.e. pressing Left or Right) without keeping the anchor (i.e. Shift is not pressed), the selection collapses either to the beginning or end of the selection based on the movement direction.
ChangeLog: Improved deselection behavior when pressing Left/Right in TextInput
Fixes #6511

core: Improve forward/backward cursor movement in TextInput

---

docs/astro/src/content/docs/reference/gestures/toucharea.mdx

I'm surprised this wasn't documented...

Document `TouchArea`'s `enabled` property

---

internal/compiler/generator/cpp.rs
tests/cases/types/gradients.slint

To avoid the error `error: narrowing conversion of`

C++: explicitly cast to float when generating gradiant stop

---

internal/compiler/layout.rs
internal/compiler/passes/default_geometry.rs
internal/compiler/passes/lower_layout.rs
internal/compiler/tests/syntax/layout/min_max_conflict.slint

To keep compatibility with existing Slint code
Commit 53e79000a4abe73749e5930c46a3a1afe3963313 added a call to LayoutConstraints::new which is shown to produce error in the crater run.

Compiler: Change a new error from 1.9 to a warning

---

tools/lsp/preview.rs
tools/lsp/preview/ui.rs
tools/lsp/ui/api.slint
tools/lsp/ui/components/expandable-listview.slint
tools/lsp/ui/components/out-of-date-box.slint
tools/lsp/ui/main.slint
tools/lsp/ui/views/library-view.slint
tools/lsp/ui/views/preview-view.slint
tools/lsp/ui/views/property-view.slint

This leaves the previous state visible.
* The diagnostics are removed. You need to fix those in your editor anyway, so we report them there.
* Use the statusbar to point to the editor in case of errors or warnings.
* Have a small popup to show the preview is outdated
* Disable dropping things into an outdated preview
* Disable the property editor when the preview is outdated
* Disable selection/editing when the preview is outdated

live-preview: Do not update the preview when build fails

---

internal/compiler/widgets/common/listview.slint
tests/cases/widgets/listview.slint

Implements keyboard navigation inside `StandardListView` widgets. The reference is [here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/listbox_role). The only deviation is around this:
> When a list is tabbed to, the first item in the list will be selected if nothing else already is.
Native platforms typically don't select the first item when a list view is tabbed into if no item was previously selected, and use of the down arrow won't move the focus and selection down on first key press.
`PageUp` and `PageDown` will have to be implemented at some point. They are used to move the focus and select the first or last item currently visible, and will scroll until bounds are reached if pressed multiple times.
I am also aware that Slint widgets are activated when the …

Improve keyboard navigation of `StandardListView`

---

tools/lsp/language/hover.rs

Whow the path when the editor can not render the image itself.

lsp: Better hover information for images in text only editors

---

tools/lsp/ui/main.slint
tools/lsp/ui/views/library-view.slint

with the addition of the 'render out of date' it felt like things should feel more disabled when they actually _were_ disabled

added faded sidebars on out-of-date preview

---

xtask/src/slintdocs.rs

This is expected e.g. on Fedora :-/

docs: Do not fail fatally when playwright can not install its browsers

---

internal/compiler/lexer.rs
tools/lsp/common.rs
tools/lsp/language.rs
tools/lsp/language/test.rs
tools/lsp/main.rs
tools/lsp/preview.rs

So when snippets do not work: Let's try something else to get started from scratch:-)

lsp: Offer to populate empty documents

---

tools/lsp/preview/element_selection.rs
tools/lsp/ui/api.slint
tools/lsp/ui/components/selection-popup.slint

* Hide layouts,
* Hide interactive elements

live-preview: More filter options in Selection Popup

---

docs/astro/src/content/docs/reference/window/window.mdx
internal/backends/winit/winitwindowadapter.rs
internal/compiler/builtins.slint
internal/core/items.rs
internal/core/window.rs

Make it possible to programatically to switch to full-screen mode via a new property in the Windows item.
The SLINT_FULLSCREEN environment variable will default set this property to true. However settings this property in the slint code will override the SLINT_FULLSCREEN.
Fixes #6665

Implement full-screen property for slint Window item

---

api/rs/slint/lib.rs
examples/opengl_texture/main.rs
examples/opengl_underlay/main.rs
internal/backends/selector/api.rs
internal/backends/selector/lib.rs
internal/backends/winit/lib.rs
internal/backends/winit/renderer/femtovg.rs
internal/backends/winit/renderer/femtovg/glcontext.rs
internal/backends/winit/renderer/skia.rs
internal/backends/winit/renderer/sw.rs
internal/backends/winit/winitwindowadapter.rs
internal/core/api.rs
internal/core/graphics.rs
internal/core/lib.rs
internal/interpreter/api.rs
internal/renderers/skia/d3d_surface.rs
internal/renderers/skia/lib.rs
internal/renderers/skia/metal_surface.rs
internal/renderers/skia/opengl_surface.rs
internal/renderers/skia/software_surface.rs
internal/renderers/skia/vulkan_surface.rs

Updated BackendSelector API

---

CHANGELOG.md
docs/astro/src/content/docs/reference/std-widgets/overview.mdx
examples/gallery/ui/pages/table_view_page.slint
internal/compiler/lookup.rs
internal/compiler/passes/resolving.rs
internal/compiler/tests/syntax/lookup/deprecated_property.slint
internal/compiler/widgets/common/layout.slint
internal/compiler/widgets/cosmic/std-widgets-impl.slint
internal/compiler/widgets/cosmic/std-widgets.slint
internal/compiler/widgets/cosmic/styling.slint
internal/compiler/widgets/cupertino/std-widgets-impl.slint
internal/compiler/widgets/cupertino/std-widgets.slint
internal/compiler/widgets/fluent/std-widgets-impl.slint
internal/compiler/widgets/fluent/std-widgets.slint
internal/compiler/widgets/material/std-widgets-impl.slint
internal/compiler/widgets/material/std-widgets.slint
internal/compiler/widgets/qt/std-widgets-impl.slint
internal/compiler/widgets/qt/std-widgets.slint

StyleMetrics is the right name for these

Remove `LayoutSpec` and undeprecate `StyleMetrics.layout-*` properties

---

internal/core/window.rs
tests/cases/focus/7058_scrolled_clip.slint

If a clipped item has a child outside of its bounds that is not clipped, we shouldn't remove the focus.
Fixes #7058

Keep focus of child of clipped item that are themselves not clipped

---

api/node/cover.md
api/node/package.json
api/node/typescript/index.ts
pnpm-lock.yaml

Typedoc complains about the links from the reference to the cover.md. I couldn't find a way to make those warnings go away, but the links work. As a remedy, `treatWarningsAsErrors` is removed temporarily.
Similarly, the relative links aren't supported either, so link to the latest Slint docs.
Fixes #6488

Node.js: Upgrade TypeDoc

---

tools/lsp/common/component_catalog.rs
tools/lsp/preview/ui.rs

I can not exactly mirror the Reference manual as the library is hard-coded to one level of depth, while the docs use two levels.
This patch takes the "lower" level of the docs ("Basic Layouts", ...), but groups all widgets below "Std Widgets" (the "upper" level of the docs layout). This is because we see many projects that avoid our widgets, so I wanted those users to be able to collapse all widgets with one click.
One additional refinement in this patch is that all widgets will always be sorted after all builtin categories and that none of the builtin Windows will get shown in the library as those are not really editable in the live preview anyway.

live-preview: Move library closer to the 1.9 Reference docs

---

api/cpp/docs/cmake.md
api/cpp/docs/cmake_reference.md
api/cpp/docs/conf.py
api/cpp/docs/generated_code.md
api/cpp/include/slint.h
internal/core-macros/link-data.json

Introduce link-data.json in the C++ docs to reduce risk of dead links

---

.github/workflows/build_docs.yaml
docs/astro/astro.config.mjs
docs/astro/playwright.config.ts
docs/astro/src/utils/site-config.ts
docs/astro/tests/link-test.spec.ts
docs/astro/tests/smoke-test.spec.ts

The CI should edit the base_url in site-config file. This way the playwright tests won't break as after this change both Astro/Starlight and Playwright use the same single BASE_URL variable.
We should update the CI too? Also tweak the way playwright reports issues in CI. At least upload the report as an archive so there is something to look at to give a clue what happens after a total test run fail.

More robust BASE_URL support for docs

---

docs/astro/src/content/docs/reference/global-functions/math.mdx

Reported in https://github.com/slint-ui/slint/issues/7146#issuecomment-2551004220

Docs: Fix `abs` examples

---

api/node/package.json

tsc is already invoked during the CI compile step, where it checks type.
For the tsc invocation to work, we need to build the Rust module first, which slows down the fmt_lint_typecheck CI job.

Remove type-check from api/node

---

examples/dial/dial.slint

Add a boundary check to ensure that rotation only occurs when the first pointer contact is inside the circular dial area. If the initial touch is outside, the dial remains stationary.

dial example: rotate dial only if initial touch is within its bounds

---

demos/printerdemo/zephyr/src/slint-zephyr.cpp

When this driver is using the DMA API, we cannot do partial updates. Previously, this code would perform a full-screen DMA transfer for each region the renderer changes. Now we make modifications to the pixel data of the dirty regions, if required, and then do one full-screen DMA transfer of the final render buffer.
This means the time spent writing the pixel buffer to the display peaks at 38ms, rather than up-to-hundreds of ms before.

Zephyr: improve render performance when using the NXP ELCDIF driver

---

tools/lsp/ui/components/selection-popup.slint

... till the filter button is pressed for the first time.

live-preview: Fix filter in selection popup being init to empty

---

internal/renderers/skia/d3d_surface.rs
internal/renderers/skia/metal_surface.rs
internal/renderers/skia/vulkan_surface.rs

On macOS we should default to the Meta renderer, similar `renderer-skia` defaults to D3D on Windows. Unfortunately commit 0d36f88152a8eb7f1eaa24f8599a68e6cea4b233 broke this by forgetting that None with the requested graphics API means: Go for with what we have, nothing special requested.
This also fixes the terminal output "Failed to initialize Skia GPU renderer: Requested non-Metal rendering with Metal renderer . Falling back to software rendering" (and similar on Windows).

Skia: Don't render with software by default on macOS/Windows

---

api/rs/slint/Cargo.toml

There is only very few Slint snippet and it causes problems generating the docs on docs.rs

docs.rs: remove the highlight of slint snippets

---

docs/astro/README.md
docs/building.md

- Updated Quickstart and DSL docs in building.md to redirect to astro/README.md due to outdated information
- Fixed issues in astro/README.md that prevented it from working out of the box

Improve documentation for building slintdocs

---

docs/testing.md

Docs: fix the path for the `syntax tests`

---

internal/compiler/object_tree.rs
internal/compiler/tests/syntax/basic/property_declaration.slint

It said `Cannot override property 'background'` because color is defined as below
```slint
property <color> color <=> background;
```
For the warning, the name should not be resolved.
Fixes #6324

Fix error message when a property named color is override

---

docs/building.md

When `cargo doc` generates multiple docs, it reports the last one(carousel) and --open opens it.
```
Generated .../target/doc/carousel/index.html and 26 other files
```
Specifing the package solves the issue and improves developer experience.

Doc: specify package to build Rust API

---

internal/compiler/object_tree.rs
internal/compiler/tests/syntax/functions/functions.slint

Fix warning message for a property that name is used for function

---

tools/lsp/language.rs
tools/lsp/language/completion.rs

(As seen in the crash reporter)
Eg:
```
thread 'LanguageServer' panicked at tools/lsp/language/completion.rs:731:17:
byte index 4 is not a char boundary; it is inside '🍒' (bytes 2..6) of `./🍒🍓🍇"`
```
This can happen because offset might not be on a char boundary because of the utf-16 / utf-8 mismatch.

Workaround panic of autocompletion of import with unicode

---

docs/release-artifacts.md

The {download_version} variable is either "nightly" or "vX.Y.Z", but the C++ binary packages dont have the "v" prefix. So use the plain version variable for the file name infix in the link.
Fixes #7242

Fix for download links for C++ binary packages in release notes

---

internal/backends/winit/lib.rs

In `winit`, it is not possible to instantiate a new window without access to the `winit` event loop, which Slint manages.  With this change, there is now a `create_winit_window` call on Slint's winit` back end that will enable creating `winit` windows using existing functionality.
Of course, the utility of these windows is limited without access to `winit` event handling, but there are applications for which simply creating a window and instructing an external program to write into it (by passing the `HWND` on Windows or the `XId` on X11) is useful.

API to enable creating winit Windows with Slint's event loop

---

demos/printerdemo/zephyr/CMakeLists.txt
demos/printerdemo/zephyr/boards/native_sim_64.overlay
demos/printerdemo/zephyr/boards/shields/rk055hdmipi4ma0/rk055hdmipi4ma0.overlay
demos/printerdemo/zephyr/src/slint-zephyr.cpp
demos/printerdemo/zephyr/west.yaml

This removes the need for a custom shield overlay, as the touch device supported by Zephyr (if one exists) is now chosen with a standard name in the device tree. This simplifies adding Slint/Zephyr support for other boards.

Update to Zephyr v4.0.0 so we can use the `zephyr,touch` chosen device tree entry

---

demos/printerdemo_mcu/esp-idf/main/main.cpp
demos/printerdemo_mcu/main.rs
demos/printerdemo_mcu/ui/printer_queue.slint

printerdemo_mcu PrinterQueueItem uses a status string instead of the JobStatus enum.
This makes the PrinterQueue code compatible with the printerdemo code, allowing us to switch between mcu and non-mcu versions of this demo, depending on what will fit on a device.
A string is used, rather than porting the non-mcu demo to an enum, because the non-mcu demo needs to work with the cpp_interpreted demo. Currently, the interpreter does not have support for enumerations (#4777).

Make the printerdemo and printerdemo_mcu PrinterQueueItem compatible with each other

---

.github/workflows/slint_tool_binary.yaml

Don't link against Qt in our binary because it might not be binary compatible with all distributions.
Eg, archlinux shows this error:
`error due to GNU_PROPERTY_1_NEEDED_INDIRECT_EXTERN_ACCESS`
We also don't enable the Qt backend in our vscode extension
Fixes #7174

Tool packages: Don't enable the Qt backend

---

internal/core/items/flickable.rs
tests/cases/elements/flickable.slint

We shouldn't ungrab the mouse when the mouse distance is smaller than the threshold
Fixes #7152
ChangeLog: Fixed Flickable hard to scroll when starting slow

Fix flickable hard to scroll when starting slow

---

internal/compiler/object_tree.rs
internal/compiler/passes/inlining.rs
internal/compiler/tests/syntax/lookup/name_reuse.slint
internal/compiler/typeloader.rs
internal/compiler/typeregister.rs

Also fix the unused component warning when that happens Fixes #7176
ChangeLog: Warning when a type name overwrite another

Add a warning when a component/type name overwrite another

---

docs/astro/src/content/docs/guide/language/coding/file.mdx

Fix broken links to cpp and rust docs

---

internal/backends/android-activity/androidwindowadapter.rs
internal/backends/android-activity/build.rs
internal/backends/android-activity/java/SlintAndroidJavaHelper.java
internal/backends/android-activity/javahelper.rs
internal/renderers/skia/textlayout.rs

Fixes <https://github.com/slint-ui/slint/issues/7182> and part of <https://github.com/slint-ui/slint/issues/7203>.
Note: <https://github.com/slint-ui/slint/issues/4973> may be closed by checking this version of Android build tools: <https://github.com/slint-ui/slint/issues/6695>.

Fixed text input on Android, fixed for older Android versions

---

internal/core-macros/slint_doc.rs

Include link-data.json as core-macros build time, so that later at run-time the extracted sources don't have to be around anymore.

Fix Bazel build

---

internal/backends/winit/accesskit.rs
internal/core/window.rs

Initial support for popups with the AccessKit backend

---

examples/gallery/ui/pages/page.slint
examples/gallery/ui/side_bar.slint
internal/backends/qt/qt_accessible.rs
internal/backends/testing/slint_systest.proto
internal/backends/testing/systest.rs
internal/backends/winit/accesskit.rs
internal/common/enums.rs
internal/compiler/passes/lower_tabwidget.rs
internal/compiler/tests/syntax/elements/tabwidget2.slint
internal/compiler/widgets/cosmic/tabwidget.slint
internal/compiler/widgets/cupertino/tabwidget.slint
internal/compiler/widgets/fluent/tabwidget.slint
internal/compiler/widgets/material/tabwidget.slint
internal/compiler/widgets/qt/tabwidget.slint
tests/cases/widgets/tabwidget.slint

This PR greatly improve the accessibility of the `TabWidget` as well as the other tab widget implementation in the gallery example.
There is one annoying issue left with the gallery example: since the sidebar also contain a label at the top, this label is the first element to get focus as far as AccessKit is concerned. I think this is due to the fact that `accessible-delegate-focus` does not ignore non-focusable items when building AccessKit tree updates. It is not strictly linked to tab widgets so I'm not including the fix in this PR.
Suggested Changelog entries:
- Improve overall accessibility of tab widgets
- Add `AccessibleRole::TabPanel`

Improve accessibility of tab widgets

---

internal/compiler/parser/element.rs
internal/compiler/tests/syntax/parse_error/sub.slint
tools/lsp/language.rs
tools/lsp/util.rs

Otherwise we get a lot of error in vscode such as:
```
Error: selectionRange must be contained in fullRange
at Gd.validate (file:///snap/code/178/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:109:33728)
at new Gd (file:///snap/code/178/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:109:33936)
at Ke (/home/olivier/.vscode/extensions/slint.slint-nightly-2025.1.109/out/extension.js:35:72279)
at Ke (/home/olivier/.vscode/extensions/slint.slint-nightly-2025.1.109/out/extension.js:35:72456)
at o (/home/olivier/.vscode/extensions/slint.slint-nightly-2025.1.109/out/extension.js:35:46654)
at Object.$P [as map] (/home/olivier/.vscode/extensions/slint.slint-nightly-2025.1.109/out/extension.js:35:46740)
at Object.Se [as …
```

LSP: Document symbol: make sure the selectionRange is contained in the full range

---

internal/core/graphics/boxshadowcache.rs
internal/renderers/femtovg/itemrenderer.rs
internal/renderers/skia/itemrenderer.rs

If the effectively drop shadow size would be zero, the FemtoVG and Skia item renderers would panic. The following test-case reproduces this:
```slint
export component Test inherits Window {
Rectangle {
drop-shadow-color: black;
drop-shadow-offset-x: 1px;
drop-shadow-blur: -0.5px;
width: 0.5px;
height: 0.5px;
background: blue;
}
}
```
ChangeLog: [Renderers] Fix panic with FemtoVG and Skia renderers for certain drop shadows.

Fix panic in FemtoVG and Skia renderers with certain drop shadows

---

.github/workflows/cpp_package.yaml
api/cpp/CMakeLists.txt

Build them in the same container(*) as we're building Rust binaries with cross.
(*) It's not exactly the same container, it's the cross one _plus_ cmake added.

Experimental support for Linux ARMv7/ARMv8 binary C++ packages

---

internal/compiler/lexer.rs
internal/compiler/tests/syntax/basic/bom-simple.slint
internal/compiler/tests/syntax_tests.rs

Skip the byte order mark.
BOM is also allowed in .rs or Cargo.toml file.
Fixes #7291

Parser: skip UTF-8 BOM

---

internal/compiler/parser.rs
tools/lsp/common/rename_component.rs
tools/lsp/common/test.rs
tools/lsp/language.rs
tools/lsp/preview.rs

This adds renaming of structs... in a limited fashion though: You have to be in the declaration of the component/struct or enum you want to rename.
This PR handles significantly more corner cases than the old component renaming code we used to have and comes with a few more tests to cover those.
Up next and building on this code: Trigger renaming based on any use of any of these types.

Rename structs, enums and components

---

internal/compiler/passes/inlining.rs
tests/cases/children/children_in_row.slint

The first inlining pass should inline any element that has children. Row is going to be optimized out before the second inlining pass. In that pass, we shouldn't care if there is no children while inlining in a `@children`
Fixes #7284

Fix panic when inlining 0 children in a `Row`

---

internal/backends/linuxkms/calloop_backend.rs
internal/backends/linuxkms/display.rs
internal/backends/linuxkms/display/gbmdisplay.rs
internal/backends/linuxkms/display/swdisplay/dumbbuffer.rs
internal/backends/linuxkms/display/swdisplay/linuxfb.rs
internal/backends/linuxkms/display/vulkandisplay.rs
internal/backends/linuxkms/drmoutput.rs
internal/backends/linuxkms/fullscreenwindowadapter.rs
internal/backends/linuxkms/renderer/femtovg.rs
internal/backends/linuxkms/renderer/skia.rs
internal/backends/linuxkms/renderer/sw.rs

This simplifies code and (more importantly) avoids getting accidentally frame-locked into 30 FPS when rendering takes slightly longer than 16ms.
Fixes #6951

LinuxKMS: Fix support for triple buffering with DRM

---

api/rs/slint/lib.rs

The slint VS Code plugin is otherwise reporting the warning: Exported component 'HelloWorld' doesn't inherit Window. This is deprecated

Fix the hello world slint macro example

---

demos/printerdemo/ui/common.slint
demos/printerdemo/ui/printerdemo.slint

Fix a couple of TouchAreas that were difficult to interact with.
1. The back button arrow TouchArea was a bit on the small side;
2. The night-mode button was especially hard to hit compared to the other sidebar buttons:
The old touch areas, highlighted in red:
The new touch areas:

Printer demo touch improvements

---

Cargo.toml
internal/core/Cargo.toml
internal/renderers/femtovg/Cargo.toml
internal/renderers/skia/Cargo.toml

Clean up unicode-segmentation dependency

---

docs/astro/src/content/docs/reference/elements/path.mdx
internal/backends/qt/qt_window.rs
internal/compiler/builtins.slint
internal/core/items/path.rs
internal/renderers/femtovg/itemrenderer.rs
internal/renderers/skia/itemrenderer.rs

This enables working around bugs in GPU drivers. Especially the GC7000UL
plus its driver on imx8mp has been observed to sometimes horribly degrade in performance when Skia renders anti-aliased paths (when a function like `gcoSURF_BlitCPU` shows up at the top of `perf` that's a bad sign).

Add property to toggle anti-aliasing on Path elements

---

internal/backends/winit/event_loop.rs
internal/backends/winit/lib.rs
internal/backends/winit/muda.rs
internal/backends/winit/winitwindowadapter.rs

Hide the winit menu bar and provide a fallback if the app doesn't provide one. Also, activate per window to fix support for multiple windows.

Enable muda macOS menubar on macOS

---

.github/actions/install-linux-dependencies/action.yaml
.github/workflows/ci.yaml
internal/interpreter/eval.rs
tests/cases/elements/popupwindow_close.slint
tests/cases/elements/popupwindow_close_policy.slint
tests/cases/elements/popupwindow_close_policy_inherited.slint

The instance passed to close_popup() was not the same as the one passed to show_popup(), when called from another component. Fix this by determining the instance in BuiltinFunction::ClosePopupWindow the same way as in BuiltinFunction::ShowPopupWindow.
This issue was covered by popup_window_close.slint's JS test, but it was commented out because we used to run the Node.js tests on Linux with Qt, for which the popup testing doesn't work the same way in terms of synthetic event delivery.
We decided to change that, also in light of the nodejs binaries we upload to the NPM registry also being built without Qt support anyway.
This permits running additional popup window tests, providing test coverage for the interpreter, some of which needed light syntax fixes.
Co-authored-by: Olivier Goffart …

Fix popupwindow.close() not working for the interpreter when called from other component

---

internal/backends/winit/winitwindowadapter.rs

I don't know why this warning was not caught by the CI, but it has been bothering me for quite a while.

Remove an unused import to fix a warning

---

api/cpp/include/slint.h
api/cpp/include/slint_properties.h
internal/core/model.rs
internal/core/properties.rs
internal/interpreter/dynamic_item_tree.rs
tests/cases/models/dirty_model.slint

Being dirty is not enough
Fixes #7245
ChangeLog: Elements of a `for` now only get re-created if the model is changed, not if it is only dirty

Only re-create elements if the model actually changed

---

tools/lsp/common/document_cache.rs
tools/lsp/language.rs
tools/lsp/language/goto.rs
tools/lsp/language/test.rs
tools/lsp/preview.rs

We got reports that you need to tweak the configuration for it to become applied right after starting VSCode. This effects mostly the library_path and Include_path options that need to get applied to the code when building in LS or live-preview.
I ran into several issues:
* The content cache was not initialized yet when the LSP sent the configuration
* The LSP did not invalidate any files on configuration changes, so it never noticed that the include/library paths were changed (and thus did not send the new files on to the live preview.
* The live preview raced against itself trying to render with the updated configuration but the old data. I added an explicit "commit configuration" step now to avoid that.
This greatly improves the reliability of configuration with the live preview and LS …

Make configuration more reliable right after starting VSCode

---

internal/compiler/passes/binding_analysis.rs
internal/compiler/tests/syntax/analysis/binding_loop_layout_if.slint

Detect binding loops when it involve the condition of a `if` in a layout

---

.github/workflows/upgrade_version.yaml
docs/astro/astro.config.mjs
docs/astro/src/styles/custom.css

The version was being set not just as a visual title, but also as part of the meta tag for every page on the docs site. Which will then change for each release as the version number changes.
Other sites have a static label here that is indepedent of the version e.g. Slint UI or Slint docs. 'Slint Docs' is now used.

Docs: Fix <title> tag having docs version

---

tools/lsp/common/rename_component.rs
tools/lsp/preview.rs

Simplify the testing of the renaming and some more small patches that should be pretty uncontroversial.

lsp: Simplify tests for renaming

---

internal/core/item_tree.rs
internal/core/model.rs
tests/cases/focus/listview-hidden.slint

- Fix StandardListView not always getting the focus. Because the geometry of the FocusScope might be empty but its position is still in the non-clipped area, but not its center.
- Fix panic when accessing "negative" items if there are hidden elements in the ListView (#7341)
Fixes #7341

ListView focus fixes

---

docs/astro/src/content/docs/index.mdx

This is attempt to make it easier to read by using less words and by starting each card with a verb (to make it actionable). Also removed the backticks for std-widgets, as it seems that LinkCard doesn't support inline markdown formatting.

doc: Shorten and edit the main page button text

---

internal/compiler/langtype.rs
tools/lsp/language/completion.rs

I noticed that when playing the StandardListView that the auto-completion would try to complete all the private property and found that confusing

LSP: don't auto-compete private properties

---

Cargo.toml
api/cpp/Cargo.toml
api/rs/slint/Cargo.toml
api/rs/slint/lib.rs
api/rs/slint/mcu.md
api/wasm-interpreter/Cargo.toml
demos/energy-monitor/Cargo.toml
demos/printerdemo_mcu/Cargo.toml
examples/bazel_build/MODULE.bazel
examples/carousel/rust/Cargo.toml
examples/mcu-board-support/Cargo.toml
examples/uefi-demo/Cargo.toml
internal/backends/testing/Cargo.toml
internal/backends/testing/systest.rs
internal/backends/winit/Cargo.toml
internal/compiler/Cargo.toml
internal/compiler/passes/embed_glyphs.rs
internal/core/Cargo.toml
internal/interpreter/Cargo.toml
internal/interpreter/lib.rs
tests/driver/interpreter/Cargo.toml
tests/driver/rust/Cargo.toml
tests/screenshots/Cargo.toml
tools/docsnapper/Cargo.toml
tools/lsp/Cargo.toml
tools/viewer/Cargo.toml

Added image-default-formats with all the format supported by image by default, and enable that feature by default.
Also put that feature in compat-1-2 for compatibility with user that have used image 0.24 with enabled features.
Make a new compat-1-10 feature that does not enable default format by default
ChangeLog: upgraded image crate to 0.25, added a new cargo feature to enable all image formats. (that feature is enabled by default with compat-1-2, added compat-1-10 to disable it
Fixes https://github.com/slint-ui/slint/issues/7251

Update to Image 0.25

---

api/cpp/Cargo.toml
api/cpp/lib.rs
api/rs/slint/Cargo.toml
api/rs/slint/private_unstable_api.rs
docs/astro/src/content/docs/reference/primitive-types.mdx
internal/compiler/expression_tree.rs
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/llr/optim_passes/inline_expressions.rs
internal/compiler/lookup.rs
internal/interpreter/Cargo.toml
internal/interpreter/eval.rs
tests/cases/types/string_character_count.slint

Introduce two new methods for string properties in .slint:
- .is_empty(): Checks if a string is empty.
- .length(): Retrieves the length of the string.
These additions enhance functionality and improve convenience when working with string properties.

String: Add .is-empty and .character-count properties

---

internal/backends/winit/Cargo.toml
internal/backends/winit/lib.rs
internal/backends/winit/winitwindowadapter.rs
internal/backends/winit/xdg_color_scheme.rs

This makes our dependency tree lighter and zbus is an already existing dependency (through accesskit).
cc #7276

Replace ashpd dependency with just zbus

---

internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/interpreter/api.rs

It can panic if lazily constructing the window adapter. Make sure it is actually not lazily constructed, we don't need lazy constructor when not embedding anyway.

Don't panic in the generated rust `ComponentHandle::window()`

---

internal/core/layout.rs
tests/cases/layout/grid_span.slint

Fix panic:
```
panicked at internal/core/layout.rs:459:33:
index out of bounds: the len is 2 but the index is 2
```

Fix runtime panic with colpan or rowspan set to zero

---

internal/compiler/passes/materialize_fake_properties.rs
internal/compiler/passes/remove_unused_properties.rs
tests/cases/crashes/issue_7316_changed_visibility.slint

Fix panic in the compiler when having a changed callback over a property that is not materlialized

---

examples/gstreamer-player/Cargo.toml
examples/gstreamer-player/build.rs
examples/gstreamer-player/egl_integration.rs
examples/gstreamer-player/main.rs
examples/gstreamer-player/software_rendering.rs

By not requiring a pipeline and having a lower-level SlintOpenGLSink type, it's easier to re-use this code in application code that for example doesn't use playbin.

gstreamer-player: Make the EGL integration easier to re-use

---

examples/gstreamer-player/README.md

- I tested this on windows and added instructions,
- removed now implemented things from README.md as well
Installation instructions were made by following: https://crates.io/crates/gstreamer
Proof that it works on windows:

Tested gstreamer example on Windows and updated README.md

---

api/cpp/include/slint.h
internal/compiler/passes/flickable.rs
internal/compiler/passes/repeater_component.rs
internal/core/model.rs
tests/cases/elements/listview-millions.slint

The problem is that the precision of f32 for coordinate wouldn't be accurate enough with such big viewport to put the elements so that they are next to eachother.
So put the elements relative to the Flickable instead of relative to the created moving viewport Rectangle.
Fixes #3700
Note that the ListView still use f32 for the scrollbar value, meaning that at some point, the wheel stops working as the wheel increment is smaller than the f32 increment, and scrolling becomes somehow fuzzy. But this only happens after one more billions pixels now, so one can have more than 50 millions of elements without much problems

Fix layouting of huge ListView with millions of items

---

docs/astro/src/content/docs/reference/elements/path.mdx
internal/backends/qt/qt_window.rs
internal/common/enums.rs
internal/compiler/builtins.slint
internal/core/items/path.rs
internal/renderers/femtovg/itemrenderer.rs
internal/renderers/skia/itemrenderer.rs
tests/manual/path-stroke-cap.slint

ChangeLog: Added `Path::stroke-line-cap` property.
Fixes #4676

Add support for line caps in Path Strokes

---

docs/astro/src/content/docs/guide/development/custom-controls.mdx
docs/astro/src/content/docs/guide/language/coding/globals.mdx
docs/astro/src/content/docs/reference/std-widgets/style.mdx

Docs: Apply usage of language tabs everywhere

---

api/cpp/include/slint.h
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/llr/item_tree.rs
internal/compiler/llr/lower_to_item_tree.rs
internal/compiler/llr/optim_passes/count_property_use.rs
internal/core/model.rs
internal/interpreter/dynamic_item_tree.rs
tests/cases/elements/listview.slint

Because we set the viewport-width several time to different value during the layouting of the ListView, it will cause this property to always be dirty. In particular, this causes permanent restart of the fluent's scrollbar animation on the size of the handle, causing continuous repaints.
Edit: Also fix the viewport width to be based on the minimum width of the content.

ListView: fix continuous redraw with fluent style and adjust the viewport-width to the min-width of the content

---

internal/renderers/skia/Cargo.toml
internal/renderers/skia/metal_surface.rs

This makes it possible to debug partial rendering with macOS easily.

Skia: Report the buffer age when rendering with metal

---

internal/renderers/skia/Cargo.toml

The next version of the `objc2` framework crates will have a bunch of default features enabled, see https://github.com/madsmtm/objc2/issues/627, so this PR pre-emptively disables them, so that your compile times down blow up once you upgrade to the next version (which is yet to be released, but will be soon).

Prepare for `objc2` frameworks v0.3

---

api/cpp/include/slint.h
internal/compiler/widgets/cupertino/scrollview.slint
tests/cases/elements/listview.slint

Regressed in commit 4da79ac69a5ad5f0b8e5544a9adb5b4ebf042d83

Fix ListView implementation in C++

---

internal/compiler/generator/rust.rs

Extends the pull request #5352 and relates to issue #1874

Ignore pedantic and nursery clippy warnings in generated code

---

internal/compiler/langtype.rs
internal/compiler/tests/syntax/elements/menubar-lookup.slint
tests/cases/children/children_placeholder_three_levels.slint

Consider
```slint
// Some code in the wild actually have made their own menubar before
component MenuBar { /* ... */ }
component Row { /* ... */ }
export component Main inherits Window {
// This should find the declared component and not the builtin component
MenuBar { }
GridLayout {
Row {}
}
}
```
Previously, `MenuBar` and `Row` were first resolved against `additional_accepted_child_types` and so it would always find the builtin one.
But this patch changes that to find the builtin one only if it hasn't been replaced by another component with the name name. (So we'd use the cusom MenuBar and the custom Row)
Another change is that we also lookup the
`additional_accepted_child_types` if they are in a `@children`.
```slint
component MyGrid {
GridLayout { @children }
}
export component Main { …
```

Rework lookup of sub-elements with regard to special accepted elements

---

api/rs/slint/tests/partial_renderer.rs
internal/core/item_rendering.rs
internal/core/software_renderer.rs
internal/renderers/skia/lib.rs
internal/renderers/skia/metal_surface.rs

Add support for triple buffered partial rendering with Skia

---

internal/core/api.rs
internal/core/sharedvector.rs

Note that this also make sure that a SharedVector for something that isn't Sync isn't send. Otherwise we could send a `SharedVector<Cell<i32>>` between threads, and because it is shared, different thread could modify the same Cell at the same time, which is unsound.
Since SharedString is a wrapper to ShareVector, this will also add the Sync impl there
ChangeLog: Fixed Sync and Send bound on SharedVector, SharedString, and Weak

Implement Sync for SharedVector and Weak

---

internal/renderers/femtovg/itemrenderer.rs
internal/renderers/skia/itemrenderer.rs

This regressed with commit 3cb4bd174d0eae0ec7bf1517580980524962c43e, which introduced the draw_rect() hook in ItemRenderer, but unfortunately it wasn't in the `impl ItemRenderer` section
in the FemtoVG and Skia renderers.
ChangeLog: Fix panic when using gradient backgrounds with `Window`.

Fix panic when using gradient backgrounds on Window

---

internal/compiler/builtins.slint
internal/compiler/passes/lower_menus.rs
internal/compiler/tests/syntax/elements/contextmenu.slint
internal/compiler/tests/syntax/elements/contextmenu2.slint
internal/compiler/tests/syntax/elements/menubar.slint
internal/compiler/tests/syntax/elements/menubar2.slint
internal/compiler/widgets/common/menus.slint
tests/cases/widgets/contextmenu.slint

This can only be used internally by the style to implement the actual ContextMenu
Only the declarative `MenuItem` interface is exposed.

MenuBar/ContextMenu: hide the `entries` interface

---

Cargo.toml
tools/compiler/Cargo.toml
tools/compiler/main.rs
tools/lsp/Cargo.toml
tools/lsp/main.rs
tools/viewer/Cargo.toml
tools/viewer/main.rs

Gives us a ~15% speed improvement basically for free (minimal code changes)

Use jemalloc for slint-viewer and slint-compiler

---

internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/llr/expression.rs
internal/compiler/llr/item_tree.rs
internal/compiler/llr/lower_expression.rs
internal/compiler/llr/lower_to_item_tree.rs
internal/compiler/llr/optim_passes/count_property_use.rs
internal/compiler/llr/pretty_print.rs
internal/compiler/llr/translations.rs

I'd like to go in a direction when we can do more pass on the LLR by mutating it. So we can transform earlier in the compilation process to LLR and interpret the LLR.

LLR Refactor: Try to make the LLR easier to work with

---

internal/compiler/Cargo.toml
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/llr/expression.rs
internal/compiler/llr/item_tree.rs
internal/compiler/llr/lower_expression.rs
internal/compiler/llr/lower_to_item_tree.rs
internal/compiler/llr/optim_passes/count_property_use.rs
internal/compiler/llr/pretty_print.rs
internal/compiler/llr/translations.rs

type-safety+=1
This would avoid for example using a sub-component index in an array of instances or items.
It also self-document what the index is for.
There are still a couple of cast from repeater-index to u32 because we do some hack with the repeater-index number for component containers We also cast back to numbers in order to convert it to string in the generated code.

LLR: used typed index for vectors in the LLR

---

internal/compiler/generator/rust.rs
tests/cases/expr/arithmetic.slint

New warning introduced in nightly rust
```
error: use of a double negation
--> /home/runner/work/slint/slint/target/debug/build/test-driver-rust-805d926ab786688f/out/expr_arithmetic.rs:10:55
|
10 |     assert_eq!(instance.get_t4(), 3 + - 5 - 8 - -9 * --- 120);
|                                                       ^^^^^^
|
= note: the prefix `--` could be misinterpreted as a decrement operator which exists in other languages
= note: use `-= 1` if you meant to decrement the value
help: add parentheses for clarity
|
10 |     assert_eq!(instance.get_t4(), 3 + - 5 - 8 - -9 * --(- 120));
|
```
In addition, add a check for 2024 edition warnings so we make sure user can use Slint in a crate using the 2024 edition when it gets released  (there were no warnings according to my tests)

Prospective CI fix with Rust nightly

---

internal/compiler/generator/rust.rs
tests/driver/rust/main.rs

Add a check for 2024 edition warnings so we make sure users can use Slint in a crate using the 2024 edition when it gets released.
The warnings can be silenced as we don't handle types in Slint that have Drop with side effects other than memory allocations

Silence 2024 edition warnings

---

.github/workflows/build_docs.yaml
docs/astro/src/components/ReleaseLink.astro
docs/astro/src/content/docs/guide/platforms/embedded.mdx
docs/astro/src/utils/site-config.ts

I suspect I am not updating the CI correctly. This PR won't work till we do an actual release as this has to point to actual release artefacts. As in the links in the snapshot will be broken?

The links to the STM templates are broken.

---

internal/backends/qt/qt_window.rs
internal/core/item_rendering.rs
internal/core/items.rs
internal/core/items/component_container.rs
internal/core/software_renderer.rs
internal/renderers/femtovg/itemrenderer.rs
internal/renderers/skia/itemrenderer.rs

Instead of creating a dummy Rectangle with background property, implement a RenderRectangle trait.

Clean up rendering of component container

---

internal/core/item_rendering.rs

swap_remove() on a slice needs to operate on len - 1 as index of the last element, not len.
Reproducible with linuxkms-skia-software and partial rendering enabled, when moving the mouse cursor outside of the screen.

Fix panic in DirtyRegion::intersection when there's no intersection

---

api/rs/slint/tests/partial_renderer.rs
internal/backends/qt/qt_widgets/button.rs
internal/backends/qt/qt_widgets/checkbox.rs
internal/backends/qt/qt_widgets/combobox.rs
internal/backends/qt/qt_widgets/groupbox.rs
internal/backends/qt/qt_widgets/lineedit.rs
internal/backends/qt/qt_widgets/listviewitem.rs
internal/backends/qt/qt_widgets/progress_indicator.rs
internal/backends/qt/qt_widgets/scrollview.rs
internal/backends/qt/qt_widgets/slider.rs
internal/backends/qt/qt_widgets/spinbox.rs
internal/backends/qt/qt_widgets/tableheadersection.rs
internal/backends/qt/qt_widgets/tabwidget.rs
internal/backends/qt/qt_window.rs
internal/core/item_rendering.rs
internal/core/item_tree.rs
internal/core/items.rs
internal/core/items/component_container.rs
internal/core/items/flickable.rs
internal/core/items/image.rs
internal/core/items/input_items.rs
internal/core/items/path.rs
internal/core/items/text.rs
internal/core/menus.rs
internal/core/software_renderer.rs
internal/renderers/femtovg/itemrenderer.rs
internal/renderers/femtovg/lib.rs
internal/renderers/skia/itemrenderer.rs
internal/renderers/skia/lib.rs
tests/manual/partial-rendering-circus.slint

Add support for box shadows and out-of-geometry text items with the partial renderer

---

api/rs/slint/tests/partial_renderer.rs
internal/renderers/skia/lib.rs
internal/renderers/skia/software_surface.rs

Enable partial rendering with Skia's software renderer by default

---

docs/astro/src/content/docs/reference/window/contextmenu.mdx
docs/astro/src/content/docs/reference/window/window.mdx
internal/backends/selector/Cargo.toml
internal/compiler/typeregister.rs
internal/core-macros/link-data.json

And don't mark them as experimental.
Which also enable the muda dependency by default on mac and windows

Document MenuBar and ContextMenu

---

internal/backends/winit/lib.rs
internal/backends/winit/winitwindowadapter.rs
tools/lsp/preview/native.rs

We said that when the app provides an event loop builder, we assume it also provides a menu bar.
Fixes the lsp's Window -> Keep on top menu on macOS.

Fix support for menu bars provided by native code

---

internal/compiler/generator/cpp.rs

Otherwise initializing the translation won't work.
This can't be tested because the testing backend is always initialized before. And also hasn't been a problem on MCU where the feature is the most usefull because it also uses custom backend there initialized before

C++: initialize the backend before the translations

---

api/cpp/include/slint-testing.h
docs/astro/src/content/docs/reference/common.mdx
internal/backends/qt/qt_accessible.rs
internal/backends/testing/search_api.rs
internal/backends/testing/slint_systest.proto
internal/backends/testing/systest.rs
internal/backends/winit/accesskit.rs
internal/compiler/typeregister.rs
internal/compiler/widgets/cosmic/combobox.slint
internal/compiler/widgets/cupertino/combobox.slint
internal/compiler/widgets/fluent/combobox.slint
internal/compiler/widgets/material/combobox.slint
internal/compiler/widgets/qt/combobox.slint
internal/core/accessibility.rs
internal/interpreter/dynamic_item_tree.rs
tests/cases/widgets/combobox.slint

This improves how ComboBox widgets are represented in the accessibility tree so that they can be interacted with using assistive technologies. The "expanded state" is still unusable for now but since the value is properly reported, arrow keys can already be used to pick a choice without opening the popup.
The AccessKit platform adapters currently don't expose the `Node::is_expanded` property to the various accessibility layers, but this is expected to ship in the next release or so. Testing was performed with a branch of mine.
- Improved accessibility of ComboBox widgets
- Added `accessible-expandable` and `accessible-expanded` properties, as well as `accessible-action-expand`.

Improve accessibility of ComboBox widgets

---

internal/core/window.rs

With the Qt backend, the PopupWindow has its own Window and the focus item is not always set to that window. Resulting in the focus appearance, but the keyboard event wouldn't be taken by that item
Fixes #7529

Forward the focus item also to the window of the popup

---

internal/core/model.rs

ChangeLog: Rust: Removed the requirement that for VecModel<T> T has to implement Default.

VecModel<T>: Don't require that T implements Default

---

internal/core/model.rs

Fixes #7381 
If an item can just fit above the viewport while scrolling, it is now not instanciated anymore as it is fully hidden. The issue occurs frequently when using the arrow keys to jump through the items, since the scroll delta will usually be the height of exactly one item. This previously meant that an extra node would be added at the start of `ListView`s accessibility tree.

Don't instanciate ListView items that are just above the viewport when scrolling down

---

internal/backends/winit/muda.rs
internal/backends/winit/winitwindowadapter.rs

This is the discussed stop-gap for macOS for the 1.10 release.

Always create an app menu for the menubar

---

tools/lsp/ui/components/property-widgets.slint
tools/lsp/ui/views/property-view.slint

Make the property widgets work with less information avaiable to them. I hope I can reuse them for runtime widget state as well that way.
Unexport the individual widgets and wrap them into a `PropertyValueWidget` that switches between them as needed -- and fills in the extra information needed to keep the existing functionality in place.
This makes the PropertyView so much cleaner ;-)

live-preview: Make property widgets use less information

---

api/cpp/cbindgen.rs
api/cpp/platform.rs
api/node/rust/interpreter/component_instance.rs
api/node/rust/interpreter/value.rs
api/node/rust/types/model.rs
api/python/models.rs
api/python/value.rs
api/rs/macros/lib.rs
demos/weather-demo/src/weather/dummyweathercontroller.rs
demos/weather-demo/src/weather/openweathercontroller.rs
demos/weather-demo/src/weather/weatherdisplaycontroller.rs
examples/maps/main.rs
helper_crates/const-field-offset/macro/macro.rs
helper_crates/vtable/macro/macro.rs
internal/backends/android-activity/build.rs
internal/common/sharedfontdb.rs
internal/compiler/parser-test-macro/lib.rs
internal/core-macros/slint_doc.rs
internal/core/model/adapters.rs
internal/renderers/femtovg/fonts.rs
internal/renderers/skia/software_surface.rs
tests/driver/cpp/cppdriver.rs
tests/driver/interpreter/interpreter.rs
tests/driver/nodejs/nodejs.rs
xtask/src/license_headers_check.rs
xtask/src/reuse_compliance_check.rs

Used these commands and some manual searching
```
cargo clippy --fix  --all-targets --workspace --exclude gstreamer-player --exclude i-slint-backend-linuxkms --exclude uefi-demo --exclude ffmpeg -- -A clippy::all -W clippy::uninlined_format_args
cargo clippy --all-targets -- -A clippy::all -W clippy::uninlined_format_args
cargo clippy --fix -- -A clippy::all -W clippy::uninlined_format_args
```

A few more format arg inlining

---

api/cpp/build.rs
api/node/rust/interpreter/component_instance.rs
api/node/rust/interpreter/value.rs
demos/printerdemo_mcu/bench.rs
internal/backends/testing/ffi.rs
internal/compiler/expression_tree.rs
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/llr/lower_to_item_tree.rs
internal/compiler/llr/optim_passes/count_property_use.rs
internal/compiler/lookup.rs
internal/compiler/passes/default_geometry.rs
internal/compiler/passes/embed_glyphs.rs
internal/compiler/passes/focus_handling.rs
internal/compiler/passes/lower_menus.rs
internal/compiler/passes/lower_property_to_element.rs
internal/compiler/passes/unique_id.rs
internal/compiler/pathutils.rs
internal/compiler/typeloader.rs
internal/core/translations.rs
internal/renderers/skia/itemrenderer.rs
internal/renderers/skia/lib.rs
internal/renderers/skia/opengl_surface.rs
tools/docsnapper/main.rs
tools/updater/experiments/lookup_changes.rs
xtask/src/reuse_compliance_check.rs

`__CARGO_FIX_YOLO=1` is a hack, but it does help a lot with the tedious fixes where the result is fairly clear.
See https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
```
__CARGO_FIX_YOLO=1 cargo clippy --fix --all-targets --workspace --exclude gstreamer-player --exclude i-slint-backend-linuxkms --exclude uefi-demo --exclude ffmpeg -- -A clippy::all -W clippy::needless_borrow
cargo fmt --all
```

Auto-fixed `clippy::needless_borrow`

---

examples/gallery/ui/side_bar.slint

The `accessible-delegate-focus` property is currently confused by the presence of the label at the top, since it expects an index in the accessible children list. Therefore the focused item would be off by one as far as assistive technologies are concerned.
I also had to move the `FocusScope` because `accessible-delegate-focus` is searched for in the ancestors of the element which is focused.
The tablist is now properly reported. Unfortunately these changes raise a more confusing bug: focus changes inside the tablist (using the arrow keys) don't seem to trigger a rebuild of the tree. When a tab is selected it is properly reported though. Even stranger: the focus changes are triggered if the focus is on the sidebar, when the toplevel window gains focus. Tabbing out of the sidebar and back …

Fix Gallery example sidebar accessibility

---

api/python/value.rs
demos/printerdemo_mcu/bench.rs
helper_crates/const-field-offset/src/lib.rs
helper_crates/vtable/src/lib.rs
helper_crates/vtable/src/vrc.rs
internal/compiler/langtype.rs
internal/compiler/lexer.rs
internal/compiler/llr/expression.rs
internal/compiler/llr/pretty_print.rs
internal/compiler/lookup.rs
internal/compiler/parser.rs
internal/compiler/passes/deduplicate_property_read.rs
internal/renderers/femtovg/itemrenderer.rs
internal/renderers/skia/itemrenderer.rs
xtask/src/license_headers_check.rs
xtask/src/reuse_compliance_check.rs

See https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes
```
__CARGO_FIX_YOLO=1 cargo clippy --fix --all-targets --workspace --exclude gstreamer-player --exclude i-slint-backend-linuxkms --exclude uefi-demo --exclude ffmpeg -- -A clippy::all -W clippy::needless_lifetimes
cargo fmt --all
```
`__CARGO_FIX_YOLO=1` is a hack, but it does help a lot with the tedious fixes where the result is fairly clear.

Auto-fixed `clippy::needless_lifetimes`

---

api/node/rust/interpreter/component_compiler.rs
api/node/rust/interpreter/value.rs
api/node/rust/types/brush.rs
api/node/rust/types/model.rs
internal/compiler/langtype.rs
internal/compiler/llr/expression.rs
internal/compiler/llr/lower_to_item_tree.rs
internal/core/graphics/image.rs
internal/core/translations.rs
internal/core/window.rs
tools/updater/experiments/geometry_changes.rs
tools/updater/main.rs
xtask/src/license_headers_check.rs
xtask/src/slintdocs.rs

See https://rust-lang.github.io/rust-clippy/master/index.html#needless_return
```
__CARGO_FIX_YOLO=1 cargo clippy --fix --all-targets --workspace --exclude gstreamer-player --exclude i-slint-backend-linuxkms --exclude uefi-demo --exclude ffmpeg -- -A clippy::all -W clippy::needless_return
cargo fmt --all
```
`__CARGO_FIX_YOLO=1` is a hack, but it does help a lot with the tedious fixes where the result is fairly clear.

Auto-fixed `clippy::needless_return`

---

internal/compiler/generator/cpp.rs
internal/compiler/passes/resolving.rs
internal/renderers/femtovg/lib.rs
internal/renderers/skia/lib.rs
internal/renderers/skia/opengl_surface.rs
internal/renderers/skia/software_surface.rs

See https://rust-lang.github.io/rust-clippy/master/index.html#useless_format
```
__CARGO_FIX_YOLO=1 cargo clippy --fix --all-targets --workspace --exclude gstreamer-player --exclude i-slint-backend-linuxkms --exclude uefi-demo --exclude ffmpeg -- -A clippy::all -W clippy::useless_format
cargo fmt --all
```
`__CARGO_FIX_YOLO=1` is a hack, but it does help a lot with the tedious fixes where the result is fairly clear.

Auto-fixed `clippy::useless_format`

---

api/cpp/include/slint_window.h
docs/astro/src/content/docs/reference/window/contextmenu.mdx
internal/compiler/builtins.slint
internal/compiler/expression_tree.rs
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/widgets/common/menus.slint
internal/core/items.rs
internal/core/window.rs
internal/interpreter/dynamic_item_tree.rs
internal/interpreter/eval.rs

This means that the parent menu still get the mouse events
Also add the ability to close the menu programmatically

ContextMenu: show submenu on hover after a timeout

---

internal/compiler/lib.rs
internal/core/graphics/color.rs
internal/core/graphics/image.rs

Fix `clippy::empty_line_after_doc_comments`

---

internal/compiler/widgets/material/spinbox.slint

Having the width depending on the height is asking for trouble because usually it is the height that depends on the width, so if the SpinBox is getting in a complex layout, it causes a binding loop. Workaround the problem by using the computed height.
This should fix the gallery build with the material style (which is currently making the nightly build fail)

Material SpinBox: Fix binding loop in some layout

---

internal/interpreter/api.rs
internal/interpreter/highlight.rs
tools/lsp/preview/element_selection.rs

Filter out elements that are clipped out (invisible or other pages) from the selection popup

Preview: filter invisible items out from the selection popup

---

internal/backends/qt/qt_widgets/button.rs
internal/backends/qt/qt_widgets/checkbox.rs
internal/backends/qt/qt_widgets/combobox.rs
internal/backends/qt/qt_widgets/groupbox.rs
internal/backends/qt/qt_widgets/lineedit.rs
internal/backends/qt/qt_widgets/listviewitem.rs
internal/backends/qt/qt_widgets/progress_indicator.rs
internal/backends/qt/qt_widgets/scrollview.rs
internal/backends/qt/qt_widgets/slider.rs
internal/backends/qt/qt_widgets/spinbox.rs
internal/backends/qt/qt_widgets/tableheadersection.rs
internal/backends/qt/qt_widgets/tabwidget.rs
internal/backends/winit/accesskit.rs
internal/core/input.rs
internal/core/item_rendering.rs
internal/core/item_tree.rs
internal/core/items.rs
internal/core/items/component_container.rs
internal/core/items/flickable.rs
internal/core/items/image.rs
internal/core/items/input_items.rs
internal/core/items/path.rs
internal/core/items/text.rs
internal/core/menus.rs

and while at it, move is_clipping_item() that casts a function of the ItemVTable.
Fixes #2341
Fixes #7382

Convey clipping of children to accesskit

---

internal/backends/qt/qt_window.rs

Otherwise we crash at exit
Fixes #7570

Qt: don't call deleteLater on the main widget

---

api/cpp/esp-idf/slint/include/slint-esp.h
api/cpp/esp-idf/slint/src/slint-esp.cpp

Only support the one that take a configuration
CC #7597

esp-idf: deprecate the old `slint_esp_init` variant

---

editors/vscode/package.json
package.json
pnpm-lock.yaml

0.24 causes security warnings.

PNPM 'override' old esbuild versions.

---

internal/backends/qt/qt_window.rs
internal/core/window.rs

So that popup menus can handle hover events.
This also remove some of the code in the qt backend that used the private API

Qt: Fix event forwarding for native popups

---

.github/workflows/cpp_package.yaml
.github/workflows/nightly_snapshot.yaml
.github/workflows/publish_npm_package.yaml
.github/workflows/slint_tool_binary.yaml

Ubuntu 20.04 container is being discontinued, so use the 22.04 instead. This is mostly used to generate binary packages

CI: Update ubuntu version

---

api/cpp/include/slint-platform.h
api/cpp/platform.rs
internal/core/software_renderer.rs

See this thread for context: https://chat.slint.dev/public/pl/shzj7t7ps7d1tnq1t8cyocufpw
This PR builds on Simon's work on the C++ API for implementing synchronous hardware acceleration within the Software Renderer.  It adds an API for texture drawing acceleration.  As well, it uses the new process_rectangle API for doing the initial background fill when rendering.
For performance, with our UI on a STM32U5G9 and implementing DMA2D with these APIs, I see our worst case render times reduced from 33.6ms to 18.1ms. That's a nearly 50% improvement!
A couple notes:
- The texture API is quite verbose with a lot of variables. These could maybe be bundled up, but technically all could contain relevant info for the C++ side
- The dx/dy/off_x/off_y types are all Fixed<...> with integers backing …

C++ hwaccel: textures and background fill

---

docs/astro/src/content/docs/guide/platforms/embedded.mdx

This was surprisingly easy to get working. But our instructions for Mac are not clear enough. This tries to fix that. Is the Pico 2 really so different as the docs show?

Better instructions for Pico Pi on Mac

---

tools/lsp/ui/components/property-widgets.slint

... instead of using the mock up data we used while designing the UI and then passing back whatever the business logic gave us for the translations.
Daniel and me discovered this yesterday working on the runtime properties. It's too embarrassing to only fix in that branch though ;-)
I am not too happy with the ergonomics yet: We apply the changes in several places, which always makes the tr-settings collapse, but at least it works now.

live-preview: Make translations reflect actual data

---

docs/astro/src/content/docs/guide/language/concepts/slint-language.mdx

Indentation was wrong. Custom example wasn't clear enough. i.e. Dialog now becomes MyDialog.

Make Slint intro clearer and formatted correctly

---

internal/compiler/llr/expression.rs
internal/compiler/llr/lower_expression.rs
internal/compiler/llr/lower_to_item_tree.rs
internal/compiler/object_tree.rs
internal/compiler/passes/deduplicate_property_read.rs
internal/compiler/passes/embed_images.rs

Use BTreeMap instead of HashMap when possible.
I wanted to make a test for it by running the compiler twice in the cpp driver test, but that's failing because we use `static COUNT` atomic variable in several places to get unique ids.
We should find another way to get unique ID that's more deterministic. This should still be deterministic when using different processes.
Although there are still some source of non determinism so this doesn't close the issue #7642

compiler: Try to keep the generated code more deterministic 

---

docs/astro/src/content/docs/reference/elements/image.mdx
internal/backends/qt/qt_accessible.rs
internal/backends/testing/slint_systest.proto
internal/backends/testing/systest.rs
internal/backends/winit/accesskit.rs
internal/common/enums.rs
internal/compiler/passes/lower_accessibility.rs
internal/compiler/widgets/common/about-slint.slint
internal/compiler/widgets/common/menus.slint
internal/compiler/widgets/cosmic/checkbox.slint
internal/compiler/widgets/cosmic/combobox.slint
internal/compiler/widgets/cosmic/components.slint
internal/compiler/widgets/cosmic/tableview.slint
internal/compiler/widgets/cupertino/checkbox.slint
internal/compiler/widgets/cupertino/combobox.slint
internal/compiler/widgets/cupertino/components.slint
internal/compiler/widgets/cupertino/spinbox.slint
internal/compiler/widgets/cupertino/tableview.slint
internal/compiler/widgets/fluent/checkbox.slint
internal/compiler/widgets/fluent/combobox.slint
internal/compiler/widgets/fluent/scrollview.slint
internal/compiler/widgets/fluent/spinbox.slint
internal/compiler/widgets/fluent/tableview.slint
internal/compiler/widgets/material/checkbox.slint
internal/compiler/widgets/material/combobox.slint
internal/compiler/widgets/material/spinbox.slint
internal/compiler/widgets/material/tableview.slint
tests/cases/elements/image.slint
tests/cases/widgets/about.slint

Introduces a new `AccessibleRole` to represent images and maps it to the appropriate role for each accessibility backend. The role could be set by default but (1) it would probably have to be done in a compiler pass and (2) the `Image` widget is already used extensively to represent icons and other visual elements that really should not be part of the accessibility tree, so it would be annoying to set `accessible-role: none` everywhere.
I took this opportunity to improve the `AboutSlint` widget. I chose "#MadeWithSlint" as the label because I think this is the most important piece of information carried out by the image, but this is your branding so feel free to suggest something else.

Add `AccessibleRole::Image` and use it in the `AboutSlint` widget

---

.github/workflows/nightly_snapshot.yaml
tools/figma-inspector/README.md
tools/figma-inspector/public-zip/readme.txt

Plugin will then be downloadable via https://github.com/slint-ui/slint/releases/download/nightly/figma-plugin.zip

Make the Figma plugin available via the nightly snapshot tag page

---

tools/lsp/ui/components/property-widgets.slint

@ogoffart relorts those do not fully work yet, so
let's just disable those for the time being.

live-preview: Do not offer plural forms in UI

---

api/cpp/cbindgen.rs
api/cpp/esp-idf/slint/src/slint-esp.cpp
api/cpp/include/slint-platform.h
api/cpp/platform.rs

Note: this adds a mendatory template parametter to the (experimental) `render_by_line` function.
I tried to get the PixelType auto-detected from the callback but i didn't manage

C++: support for RGB8 in the line by line rendering

---

api/cpp/include/slint-testing.h
docs/astro/src/content/docs/reference/common.mdx
internal/backends/qt/qt_accessible.rs
internal/backends/testing/search_api.rs
internal/backends/winit/accesskit.rs
internal/compiler/typeregister.rs
internal/compiler/widgets/cosmic/lineedit.slint
internal/compiler/widgets/cosmic/textedit.slint
internal/compiler/widgets/cupertino/lineedit.slint
internal/compiler/widgets/cupertino/textedit.slint
internal/compiler/widgets/fluent/lineedit.slint
internal/compiler/widgets/fluent/textedit.slint
internal/compiler/widgets/material/lineedit.slint
internal/compiler/widgets/material/textedit.slint
internal/compiler/widgets/qt/lineedit.slint
internal/compiler/widgets/qt/textedit.slint
internal/core/accessibility.rs
tests/cases/widgets/textedit.slint

Add the `accessible-read-only` property

---

api/node/rust/lib.rs

Reverts slint-ui/slint#7550
As discussed in #7657
Closes https://github.com/slint-ui/slint/issues/7657

Revert "fix(node): prevent 100% CPU usage on Wayland by enforcing minimum event timeout"

---

tools/lsp/ui/components/property-widgets.slint

There is no information on code we might jump to,
so do not show that button.

live-preview: Do not show "Code" button in Data preview

---

tools/figma-inspector/backend/utils/property-parsing.ts
tools/figma-inspector/figma.config.ts
tools/figma-inspector/tests/property-parsing.test.ts

Frames can be converted as if they are Rectangles.
This also adds a unique ID so the plugin can be plublished.

figma-plugin: Render properties for Figma 'FrameNodes'

---

CHANGELOG.md
api/cpp/Cargo.toml
api/rs/slint/Cargo.toml
api/rs/slint/lib.rs
api/rs/slint/mcu.md
api/wasm-interpreter/Cargo.toml
demos/energy-monitor/Cargo.toml
demos/printerdemo_mcu/Cargo.toml
examples/carousel/rust/Cargo.toml
examples/mcu-board-support/Cargo.toml
examples/uefi-demo/Cargo.toml
internal/backends/testing/Cargo.toml
internal/backends/winit/Cargo.toml
internal/core/Cargo.toml
internal/interpreter/Cargo.toml
internal/interpreter/lib.rs
tests/driver/interpreter/Cargo.toml
tests/driver/rust/Cargo.toml
tests/screenshots/Cargo.toml
tools/docsnapper/Cargo.toml
tools/lsp/Cargo.toml
tools/viewer/Cargo.toml

We decided that the compatibility with people having enabled the extra format in image 0.24 [1] is not worth it compared to the extra compilation time most people gets by default when they don't need this feature. (Which is less than 10% slower when the feature is enabled)
Since then there is no need for compat-1-10, remove it
[1] by depending directly on image 0.24 in their Cargo.toml and enabling the features, which will not work with Slint 1.10 that now use image 0.25

Don't enable image-default-formats by default, remove compat-1-10 feature

---

.github/actions/install-skia-dependencies/action.yaml
.github/actions/setup-rust/action.yaml
.github/workflows/ci.yaml
.github/workflows/cpp_package.yaml
.github/workflows/nightly_snapshot.yaml
.github/workflows/publish_npm_package.yaml
.github/workflows/slint_tool_binary.yaml
docker/Dockerfile.torizon-demos
internal/renderers/skia/Cargo.toml

This allows reverting 18db3210d6609828436408fb9f8e05b41b7f89d0 and
Fixes #6615

Update Skia Bindings

---

REUSE.toml
editors/vscode/.vscodeignore
editors/vscode/package.json
xtask/src/license_headers_check.rs

The CI has been using the deprecated vsce package to test .vsix creation, while it was renamed to @vscode/vsce a while ago. Last night, the vsce publish action we're using switched to @vscode/vsce and now the vsce build is failing, because of a bug that was hidden:
In vsce 2.25 support for `files` in `package.json` was introduced, which was just `bin/slint-lsp-*` in our package. That would omit the extension entry point and many other files, causing the vsce package creation step to fail.
Fix this by fixing the CI to use the same vsce version as the action is using, and replace the files with the default and the ignore setting of files we definitely want to exclude from the package.
With this, the package now contains these files:
```
slint-1.10.0.vsix
├─ [Content_Types].xml
├─ …
```

Fix VSCE build

---

.github/workflows/ci.yaml
internal/compiler/passes/inlining.rs
tests/cases/children/children_in_clip.slint
tests/cases/elements/flickable.slint
tests/driver/interpreter/main.rs

During the second phase, anything that involve `@children` should already
have been processed, so there shouldn't be anything left to inline.
But the children insertion point may be pointing to the wrong location
if some items were moved around (eg because of the `clip`).
So work it around by not accessing the children array at that indax that
might be out of range.
Fixes https://github.com/slint-ui/slint/issues/7724

Fix panic when inlining into clip during the second phase of inlining

---

tools/lsp/preview/ui.rs
tools/lsp/ui/components/property-widgets.slint

We have several types that all support a range of units. Internally all those units match back to one "base unit" that the type is measured in.
In the spirit of simplicity: Support only that base unit for now.
We need a more elaborate JSON scheme to pass units around with those numbers :-/

live-preview: "Fix" types with units

---

tools/lsp/preview/ui.rs

... on reloads. That is needed to make the UI aware of the new data.
I tried to be clever and not update widgets on model changes, but that is not a problem anymore as all
the property values are no longer passed through
the model. So the only reason to update the model now is because the code was loaded fresh and we *need* to refresh the entire UI in that case.

live-preview: Update the live-preview data model

---

api/cpp/include/slint-testing.h

Share the code to convert the string to a boolean.

C++: Clean up boolean accessible property getters

---

api/rs/slint/lib.rs
docs/astro/src/content/docs/reference/window/menubar.mdx
docs/astro/src/content/docs/reference/window/window.mdx
internal/core-macros/link-data.json

- Separate out `MenuBar` into an item of its own
- Fix missing links to `slint-build` crate.

Various doc fixes

---

tools/lsp/ui/components/property-widgets.slint

We can not transfer translation data over JSOn at this time, so setting the trnaslation related flags breaks the UI.
It also makes little sense to set translatable strings at the level of live data: That is the data in the application after the translations were already applied.

live-preview: No translation for strings in Preview Data mode

---

internal/compiler/generator/cpp.rs
internal/core/window.rs

This is required to fix closing popup with the Qt backend, as we use the window_adapter as a hack to get the root window_adapter (as opposed to the popup one)
(That function was only used for the ComponentContainer and was not implemented for C++ before)
Note that this reinterpret a
`Option<slint::private_api::WindowAdapterRc>` to just a `WindowAdapterRc` This is because `Option` is only forward declared in C++ as it is not generaly `#[repr(C)]`,  but we assume (and assert) the usage of a niche.
As reported in https://chat.slint.dev/public/pl/ihnwtdgp7fb75k4aj5ou3p4idc

C++: implement the ItemTreeVTable::window_adapter

---

api/cpp/include/slint_properties.h
internal/compiler/generator/cpp.rs
internal/core/properties/ffi.rs

Save some heap allocations for the dependency nodes

Implement Property::set_constant in C++

---

tools/lsp/preview/ui.rs
tools/lsp/ui/views/preview-data-view.slint

Always list all elements that *could* have live
data, add a Text about "no properties" into empty
ones.

live-preview: Show why no live data is present

---

internal/compiler/generator/cpp.rs
tests/cases/elements/image.slint

There was an image like this:
```slint
height: 40px
Image {
width: parent.width;
height: self.source.height * 1px;
source: @image-url("....");
}
```
The `y` propery ended inlined like so:
`(40 - the_image.source.get().size().height)/float(2)` but since height was `unsigned` the C++ rules means that the operation happens as unsigned and we have an overflow. and `y` turned out to be very big instead of slightly negative (for image whose height was larger than 40)

C++: fix a bug in which a substraction could overflow

---

api/cpp/esp-idf/slint/include/slint-esp.h
api/cpp/esp-idf/slint/src/slint-esp.cpp

This changes the default if the user has selected
`CONFIG_BSP_LCD_COLOR_FORMAT_RGB888` in their sdkconfig, (which will result in build error if the buffer were passed as Rgb565Pixel, or in garbage of the screen if the screen was configured programatically to use rgb565 without calling `bsp_display_new` which is unlikely if they set CONFIG_BSP_LCD_COLOR_FORMAT_RGB888)

esp-idf: Be smarter about RGB888 and RGB565

---

internal/interpreter/Cargo.toml

when compiling, for example, the viewer with
`--no-default-features --features=backend-qt` in order to avoid compiling winit, we would still not enable the qt backend because it didn't enable the backed-qt feature in the selector that toggle the `enable` feature in i-slint-backend-qt

Interpreter: Fix enabling only the Qt backend

---

tools/compiler/Cargo.toml
tools/compiler/main.rs
tools/lsp/Cargo.toml
tools/lsp/main.rs
tools/viewer/Cargo.toml
tools/viewer/main.rs

Upstream isn't even compile-testing on Windows ( https://github.com/tikv/jemallocator/blob/main/.github/workflows/main.yml ), so we should disable it as well.
This should fix the build failing with mingw.

Disable jemalloc on Windows

---

api/cpp/CMakeLists.txt

This PR adds a cmake module search for corrosion via find_package. This is to enable Nix which requires downloading of dependencies prior to build time.
I've also created a proof-of-concept fork of the stm32 C++ template which shows a nix derivation for Slint:
https://github.com/scristall-bennu/slint-cpp-templates-stm32-nix

Use find_package to search for Corrosion

---

tools/lsp/ui/components/property-widgets.slint
tools/lsp/ui/views/preview-data-view.slint

Those contain only one element informing about there not being any properties to show. While I think it is important to show that information so users have a chance to figure out how to actually use the live data tab, it is not that important that we need to always show it.

live-preview: Polish: Do not expand empty Property Groups

---

internal/compiler/passes/const_propagation.rs
tests/cases/issues/issue_7811_inline_stack_overflow.slint

We can't use `body.visit_recursive_mut` because it will recurse on the newly replaced argument. Implement recursion manually instead.
Fixes #7811

compiler: Fix infinite recursion trying to inline function argument

---

internal/backends/winit/accesskit.rs
internal/compiler/widgets/common/lineedit-base.slint
internal/compiler/widgets/common/spinbox-base.slint
internal/compiler/widgets/common/textedit-base.slint
internal/compiler/widgets/cupertino/textedit.slint
internal/core/accessibility.rs
tests/cases/widgets/spinbox_basic.slint

Relates to #2895 
Which value is allowed in a text input should be communicated to assistive technologies. In AccessKit this means setting different roles when possible, instead of the generic `Role::TextInput`. I chose to not introduce a new accessibility property for this:
- it would only make sense on `LineEdit` widgets, and a multiline property would only be valid on `TextEdit`,
- building a text edit from scratch without the built-in components doesn't seem feasible,
- more importantly, we will need to access the built-in `TextInput` item from the AccessKit backend anyway to expose text runs and I now believe that doing some compiler magic is going to be very tricky if possible at all.
Fixes the Spinbox widget while at it.

Expose more kinds of text edit widgets to AccessKit

---

.gitignore

Project wide use of mise dopes not seem popular, so just update .gitignore to allow for local use.

janitor: Update .gitignore to make local use of mise possible

---

api/rs/slint/private_unstable_api.rs
docs/astro/src/content/docs/reference/primitive-types.mdx
internal/compiler/expression_tree.rs
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/llr/optim_passes/inline_expressions.rs
internal/compiler/lookup.rs
internal/core/string.rs
internal/interpreter/eval.rs
tests/cases/expr/to-fixed.slint
tests/cases/expr/to-precision.slint

Add two new float to string conversion methods that mimic JavaScript's Number.toFixed() and Number.toPrecision().
They are implemented as no_mangle functions similar to the already existing float to shared string conversion.
Closes #5822

Add float.to-fixed and float.to-precision

---

demos/usecases/ui/app.slint
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/lib.rs
internal/compiler/llr.rs
internal/compiler/llr/item_tree.rs
internal/compiler/llr/lower_to_item_tree.rs
internal/compiler/object_tree.rs
internal/compiler/passes.rs
internal/compiler/translations.rs
internal/compiler/typeloader.rs

Include messages from bundled translations into the character set used for deciding which glyphs to embed.

Improve font embedding for MCUs when bundling translations

---

.github/workflows/autofix.yaml
package.json

Autofix is installing an extra version of Biome just to check a single file, the biome.json in the root. This responsibility is moved to the root package.json.

No need for biome CLI

---

tools/lsp/ui/views/preview-view.slint

The previous behaviour meant when in normal mode for live-preview you could click outside the bounds of your running slint UI and it would unselect the current selection. e.g. some Rect would be unseletedand the root element would gain selection.
However if your Slint app had areas with no TouchAreas if you clicked in these areas of the running UI it would also cause the current selection to become unselected.
This change adds an additional TouchArea the same size as the running UI that blocks these stray clicks and makes select/unselect feel more predictable. Any user with a semi complex UI would probably never hit this issue, but anyone starting out with a simple UI would experience this.

live-preview: Don't let unselect work when clicking on live content

---

.github/workflows/autofix.yaml
.gitignore
.mise/config.toml
.mise/tasks.toml
.mise/tasks/fix/text/trailing_spaces
.mise/tasks/lint/legal/reuse
CONTRIBUTING.md
api/cpp/include/slint-platform.h
api/cpp/include/slint-testing.h
api/cpp/include/slint_point.h
api/cpp/tests/platform_eventloop.cpp
docs/development.md
pnpm-lock.yaml
xtask/src/license_headers_check.rs

I found `mise` a tool to help manage development projects. https://mise.jdx.dev/
It basically can manage ENV vars based on the directory you are in, manages tools you need (and makes thoser available based on the directory you are in), and allows to define simple tasks that can then be shared between developers.
Tools can be found in npm, pipx, aqua, binaries on github, ... and it tries to verify signatures and all that (if supported by the repo the data comes from).
I replaces the entire autofix workflow with mise tooling and tasks, just to give it a try :-)
`mise install` should be enough to get most tools into place. That makes things so much simpler!
I can run at least the autofix thing locally now, which takes < 10s. That's much more convenient than pushing and waiting for CI.
Mid …

infra: Test out mise

---

internal/compiler/passes/remove_aliases.rs
tests/cases/properties/changes_alias.slint

Don't merge a property with a global property if it has a change handler as we can't mobe the change handler in the global
Fixes #7784
If two property are merged that each have a change handler, we must merge the change handler. (Note that the order in which they are being called is not deterministic)
Fixes #7747

Fix change handler with callback

---

internal/backends/qt/qt_window.rs
internal/renderers/femtovg/itemrenderer.rs
internal/renderers/skia/itemrenderer.rs

matching the math for skia and femtovg renders for radial gradient

---

internal/interpreter/json.rs

Add gradients to the list of types that can be read from JSON and serialized to JSON.

interpreter: Support gradients in JSON conversion

---

internal/interpreter/dynamic_item_tree.rs
tests/cases/issues/issue_7848_timer_depends_model_data.slint

This is also how we do it in Rust and C++ generated code
Fixes #7848

Interpreter: start timer after the initialization of properties

---

tools/lsp/ui/views/preview-view.slint

This tiny change stops the background checkerboard shifting everytime anything resizes the content of the live-preview.

Stop live-preview checkerboard shifting as window resizes

---

internal/compiler/passes/lower_layout.rs
internal/interpreter/dynamic_item_tree.rs
tests/cases/layout/issue_7761_animated_pc_size.slint

Should register the Type::Percent as animated
Also avoid duplicating the binding for both min and max, and just make one use the other.
Fixes #7761

Interpreter: Fix panic when animating a `%` property

---

internal/compiler/passes/infer_aliases_types.rs
internal/compiler/passes/resolving.rs
internal/compiler/tests/syntax/lookup/callback_alias3.slint
internal/compiler/tests/syntax/lookup/callback_alias_global.slint

Also properly error out when the number of arguments to a callback alias is not correct
Fixes #7806

Deprecate alias to global callback and error out when setting such callback

---

cspell.json
docs/astro/src/content/docs/reference/primitive-types.mdx
internal/compiler/expression_tree.rs
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/llr/optim_passes/inline_expressions.rs
internal/compiler/lookup.rs
internal/interpreter/eval.rs
tests/cases/types/string_to_lowercase.slint
tests/cases/types/string_to_uppercase.slint

Adds methods to change a `string`'s case to lowercase or uppercase. They use Rust's `to_lowercase` and `to_uppercase` `String` methods.
Closes #7860

Add string.to-lowercase and string.to-uppercase

---

internal/renderers/skia/build.rs
internal/renderers/skia/lib.rs

We've had some reports like #7641 . Now that we enable partial rendering by default, let's default to software rendering for Skia on Windows, until perhaps the Skia dawn backend arrives.
Closes #7641

Skia: Use software rendering by default on Windows

---

docs/astro/src/content/docs/reference/primitive-types.mdx
internal/core/graphics/image.rs

Shortly before 1.10, we decided not to enable most format by default. But the documentation was not updated to reflect that
Closes #6574

Fix documentation of image formats

---

tools/figma-inspector/backend/tsconfig.json

Technically the Figma plugin is two typescript projects. A backend and a frontend. While typechecking via `pnpm type-check` works correctly, you would see no inline errors in VScode for the backend project. This lead to surpirses latert on when the CI runs the type-check script.
This fixes the issue so the experience inside VScode and from the type-check script match up.

Fix typescript errors not showing in-line for VScode

---

editors/vscode/README.md

These small changes make developing the vscode extension more productive.
1. The lsp is compiled for Skia which on the Mac ensures the fonts render correctly and the UI will run at 120fps on dispalys that support high frame rates.
2. The compiled plugin will open with an actual project. This saves at least 2 extra clicks to open some project everytime you compile the extension and want to see it.

Better dev commands for VScode development

---

tools/lsp/ui/components/property-widgets.slint

This stops e.g. the color widget filling in default values for empty strings.

live-preview: Do not pass on signals from "invisible" widgets

---

internal/compiler/generator/cpp.rs
tests/cases/expr/mod.slint

`mod(-42, 2)` would return 2 instead of 0

C++: fix `mod` with negative number again

---

internal/core/software_renderer.rs

This is to fix up #7794 so I can get off my fork. Confirmed it fixes my issues on my STM32U5G9-DK2, though I'm not confident the lines regarding `(rect.origin.<x/y> - geometry.origin.<x/y>)` are safe.

Software Renderer: fix texture offset for partial draws with hwaccel

---

api/cpp/include/vtable.h
internal/compiler/generator/cpp.rs
tests/cases/widgets/menubar.slint

Right now we always `lock().value()` it which is the equivalent of `upgrade().unwrap()` in rust, this helps because it keeps the parent alive when we are calling function in it.
Ideally we should also check that it wasn't deleted, but that's another issue.
Fixes #7880

C++: put the parent in a weak pointer

---

.github/actions/install-skia-dependencies/action.yaml

This reverts commit 4fef985fbc717f9939bdf9be6b2b16a1c788bd12.
As per https://github.com/rust-skia/rust-skia/pull/1114 this shouldn't be needed anymore.

Revert "Attempt to work around llvm / clang-cl bug for Skia build"

---

pnpm-lock.yaml

Should stop the security warning.

Dedupe lock file to remove old versions of Vite

---

tools/lsp/ui/components/property-widgets.slint

Takes advantage of a recent fix where conditional elements don't get recreated if the result of the condition stays the same. Previously they would be recreated every time the condition was re-evaluated.

Simplify the live-preview widget layouts

---

tools/lsp/common.rs
tools/lsp/preview/element_selection.rs
tools/lsp/preview/ext.rs

Trivial change to get it out of the way...

lsp: Update ElementRcNode to return the full debug info

---

docs/astro/src/content/docs/tutorial/creating_the_tiles.mdx
docs/astro/src/content/docs/tutorial/polishing_the_tile.mdx

The wording was quite confusing before. To talk about declaring items 'below' to then draw in 'above'. So the thinking here is that 'before' and 'after' is just for talking about the text in the file. Then 'above' and 'below' is just used when talking about how items are drawn? Maybe even remove the text and just show the slint snipet?

docs: Tweak the tutorial

---

api/cpp/include/slint_models.h
tests/cases/models/model.slint

C++: Fix segfault when calling Model::row_changed() after Model::reset()

---

internal/core/api.rs

Docs: add a note about event processing for `quit_event_loop`

---

api/cpp/include/slint_models.h
tests/cases/models/model.slint

The `notify_*` function are used by the model to notify the view. As opposed to the function without the prefix, which are used to get notified when a source model change
Fixes #3888
CC #3945 (for the docs about thread safety)

C++: add `notify_` prefix to the Model functions and add docs

---

tools/lsp/ui/components/widgets/floating-color-picker-widget.slint

The previous solution meant a hidden TouchArea the size of the live-preview handled dragging the color picker. This won't scale as now multiple pickers need to show for the brush picker gradient editor.
This change means the picker now handles the drag logic itself with it's own internal TouchArea.
This change also fixes an issue where moving the window very quickly showed a bug in the code that stops the window moving out side the bounds of the live-preview. It would stop, but too early with a few pixels to spare. Now the picker stops at the actual window bounds.

Simplify the color picker window dragging

---

.github/workflows/publish_npm_package.yaml
.github/workflows/upload_pypi.yaml

Make the Cargo.toml patching process work independent of the actual formatting and formatter settings by using taplo.
Use mise to grep a copy of taplo.

ci: Fix packaging breaking due to taplo formatiing

---

docs/astro/src/content/docs/reference/std-widgets/style.mdx
internal/compiler/builtins.slint
internal/compiler/widgets/cosmic/std-widgets-impl.slint
internal/compiler/widgets/cupertino/std-widgets-impl.slint
internal/compiler/widgets/fluent/std-widgets-impl.slint
internal/compiler/widgets/material/std-widgets-impl.slint

Although std-widgets provides many properties that adapt to the current theme users who would like to go beyond these properties and do theme dependent changes are limited. One option would be to add even more properties to the Palette, however this would potentially bloat the object, it's not obvious what properties users care about and this approach doesn't scale. In many cases developers could simply create their own properties if they knew what the current runtime theme was.
This simple change allows an app to know what the current theme is and present theme appropriate UI's.

Allow checking at runtime about the current theme

---

internal/renderers/skia/software_surface.rs

Same algotithm as in SkiaRenderer::render_components_to_canvas
Fixes https://github.com/slint-ui/slint/issues/8066

Skia: round_out the physical dirty region before presenting

---

api/wasm-interpreter/Cargo.toml
api/wasm-interpreter/src/lib.rs
docs/astro/src/utils/slint-docs-preview.html
editors/vscode/src/wasm_preview.ts
internal/backends/winit/event_loop.rs
internal/backends/winit/lib.rs
internal/backends/winit/wasm_input_helper.rs
internal/backends/winit/winitwindowadapter.rs
internal/interpreter/api.rs
internal/interpreter/dynamic_item_tree.rs
tools/lsp/Cargo.toml
tools/lsp/preview/wasm.rs
tools/slintpad/src/lsp.ts

Replace various private APIs needed for the wasm builds with "public" APIs
This way, all window adapters are created through `create_window_adapter()` and all event loops are spawned through `Backend::run_event_loop()`.
Now we can replace the thread-local windows registry with reference-counted data that's shared between the backend and the window adapters.

Clean up wasm-interpreter / winit interface

---

internal/compiler/builtins.slint
tools/lsp/preview.rs
tools/lsp/ui/api.slint
tools/lsp/ui/views/preview-view.slint

So that we can pass the focus into the container when it first shows.
I thought this would be super complex to do property! What a nice surprise:-)
Fixes: #4055

component-container: Accept focus

---

demos/printerdemo/ui/printerdemo.slint
tools/lsp/preview.rs
tools/lsp/preview/preview_data.rs
tools/lsp/preview/ui.rs

Set all values that are changed compared to the initial set of values right after loading a new component.
This also includes a small change to the printerdemo, so that it exposes more data to the business logic, so that we have something to demonstrate;-)
Some unrelated cleanups ended up in here as well... Sorry for that.

live-preview: Explicitly set live-data values on reload

---

internal/core/graphics/color.rs

Internally a hue could be in negative degrees. The resulting color was fine, however using to-hsv() would then expose this negative value. This ensure the internal value is positive.
Some tweaks were needed to help tests pass but a real fix would be proper color comparisons. Floating point issues turn up when converting from hex to floats.

fix: to-hsv() should not return a negative hue value

---

internal/compiler/expression_tree.rs
internal/compiler/lib.rs
internal/compiler/llr/lower_expression.rs
internal/compiler/object_tree.rs
internal/compiler/passes.rs
internal/compiler/passes/const_propagation.rs
internal/compiler/passes/focus_handling.rs
internal/compiler/passes/infer_aliases_types.rs
internal/compiler/passes/inject_debug_hooks.rs
internal/compiler/passes/lower_accessibility.rs
internal/compiler/passes/lower_layout.rs
internal/compiler/passes/lower_popups.rs
internal/compiler/passes/remove_return.rs
internal/compiler/passes/resolving.rs
internal/compiler/passes/z_order.rs
internal/interpreter/eval.rs

You can not create this expression manually, but there is a pass in the compiler that adds it to all set
properties in a compilation run.
All it does is basically associate an id with an expression, so that we can then in a later step have the interpreter do something with that information. Apart from that, it tries to be as transparent as possible.
The LLR lowering removes that expression again, just so we can be sure it does not end up in the generated live code.

compiler: Add a DebugHook expression

---

internal/compiler/object_tree.rs
tests/cases/elements/menubar_for.slint

We were not visiting properly the MenuItem from
`recurse_elem_including_sub_components_no_borrow`
(`recurse_elem_including_sub_components` was correctly modified before)
Fixes #8090

Fix accessing properties within the `MenuItem`

---

tools/lsp/common/document_cache.rs
tools/lsp/preview.rs

... so we do not hide the Style combobox when std-widgets get used by imported components, even if they are not used by the previewed component.
Fixes: #7172

live-preview: Improve std-widget use detection

---

internal/backends/qt/lib.rs
internal/backends/qt/qt_window.rs

This fixes the preview window not showing with the Qt backend, because the preview uses a timer to show the window, but we would not start the Qt timer and so the window was never shown

Qt: re-arm the timer after callback from `invoke_from_event_loop`

---

internal/backends/winit/event_loop.rs
internal/backends/winit/muda.rs
internal/backends/winit/winitwindowadapter.rs

The latter's life time is tied to the winit window and should live in WinitWindowOrNone.

winit: separate menubar vbox from muda adapter

---

internal/interpreter/eval.rs
internal/interpreter/eval_layout.rs

Replace the enum with the only variant that is actually used: The one taking an `InstanceRef`.

interpreter: Simplify `EvalLocalContext`

---

internal/core/software_renderer/minimal_software_window.rs

(This causes the combobox popup in the printerdemo_mcu to be shown in the wrong place when using a scale factor, as it tries to fit them into the window which reports a size smaller than it is)

MinimalSoftwareWindow: fix sizing with scale factor

---

tools/lsp/ui/components/widgets/floating-color-picker-widget.slint

If the # hex value gets longer than 8 characters it will reset to the previous valid value.
Fixes an issue where gradient stops could not be fully keyboard edited.

Brush Picker limit hex input length

---

docs/astro/src/content/docs/reference/window/contextmenuarea.mdx
internal/common/builtin_structs.rs
internal/compiler/builtins.slint
internal/compiler/passes/lower_menus.rs
internal/compiler/widgets/common/menu-base.slint
internal/compiler/widgets/common/menus.slint
internal/core/menus.rs
tests/cases/elements/menubar_for.slint

By default it's enabled, of course. This property is not only added to `MenuItem`, but `Menu` as well - since they can be nested. It's also possible to select a disabled item, but it's hard to modify that since it's logic is written in Slint. You should be prevented from activating it with a tap or key press at least.
See #7791

Menu: Add enabled property

---

tools/lsp/preview/ui.rs
tools/lsp/ui/api.slint
tools/lsp/ui/components/widgets/floating-color-picker-widget.slint

... when reading them from code and when inserting new stops.

live-preview: Keep gradient stops sorted

---

tools/lsp/preview/ui/property_view.rs

... otherwise gradients without positions will fail to evaluate all their GradientStops, leading to the wrong gradients being previewed.

live-preview: Go deeper when evaluating gradients

---

tools/lsp/common/text_edit.rs
tools/lsp/preview.rs
tools/lsp/preview/drop_location.rs

They get ignored by the editor (rightfully so), while the live preview will wait for the new source code, blocking all further edits.
Not a regression, as this has been in for a while now, but definitely a brown paper bag issue.
Thanks to @NigelBreslaw for figuring this out.

live-preview: Do not send TextEdits that do not change anything

---

tools/figma-inspector/backend/utils/property-parsing.ts

Re-use the color types that figma provides and accept both of them.

figma-inspector: Generalize rgbToHex helper function

---

.mise/tasks.toml

Forgetting to push an updated pnpm lock file is a common issue when working with any of the npm package based projects. This teaches autofix to update it and allow the rest of the CI run to proceed.

Teach autofix CI to update an outdated PNPM lockfile

---

internal/compiler/widgets/common/textedit-base.slint

(Too bad that we can't hide these actions)

Disable cut/paste action when textedit is disabled

---

CHANGELOG.md
docs/astro/src/content/docs/reference/std-widgets/style.mdx
internal/backends/qt/qt_widgets/palette.rs
internal/backends/qt/qt_widgets/stylemetrics.rs
internal/compiler/builtins.slint
internal/compiler/lookup.rs
internal/compiler/passes/resolving.rs
internal/compiler/tests/syntax/lookup/deprecated_property.slint
internal/compiler/widgets/cosmic/std-widgets-impl.slint
internal/compiler/widgets/cupertino/std-widgets-impl.slint
internal/compiler/widgets/fluent/std-widgets-impl.slint
internal/compiler/widgets/material/std-widgets-impl.slint
tools/lsp/ui/components/widgets/inline-brush-widget.slint

This is only exposed when internal types are exposed (such as in the lsp).
The plan is to make this public under a new name/global after the release.

Move Palette.style-name to internal protected StyleMetrics.style-name

---

tools/lsp/ui/components/widgets/floating-color-picker-widget.slint

Potential fix for a set of complex gradient stop re-ordering interactions.
Previously when dragging a gradient stop past other stops the items did not re-order as expcected. The current focused stop did not update. Stops could stick to the dragging stop. Stop sliders could disapear from view. These should be fixed but need more manual testing.

Fixes for gradient stop re-ordering

---

docs/astro/src/content/docs/guide/language/coding/file.mdx
internal/compiler/parser/document.rs
internal/compiler/tests/syntax/imports/import_parse_error6.slint
internal/compiler/tests/syntax/imports/import_parse_error7.slint
tests/cases/imports/external_globals_nameclash.slint
tests/cases/imports/external_structs.slint
tests/cases/imports/external_type.slint

Adding support for (optional) trailing commas like this:
```slint
import {
Foo,
Bar,
} from "foobar.slint";
```
This way it's more convenient to keep component imports nicely formatted and leads to smaller diffs when adding more components to the end of the import statement. See feature request #4922.
I've added an example to the documentation so one can see trailing commas are officially supported. But I renamed the imported types (e.g. `export1`) for consistency with other examples (e.g. `MyButton`). IMHO that makes the examples more expressive, but no strong opinion here...
Just let me know if anything (code, tests, docs) should be adjusted.

Allow trailing comma in import statements

---

tools/lsp/ui/components/widgets/inline-brush-widget.slint
tools/lsp/ui/windowglobal.slint

Brush and color property widgets no longer show the default value of 'transparent' when a value has not been set. Instead the common symbol for no set color from other tools (a red diagonal line on a white background) is used. 
When clicked the color picker is then shown and is populated with a default color that is 100% opaque.

Better handling of unset colors and brush properties

---

tools/lsp/ui/components/widgets/floating-color-picker-widget.slint
tools/lsp/ui/components/widgets/inline-brush-widget.slint

Although technically Slint hex colors are #RGBA values, it's common to not see the alpha when its 100% i.e. FF. So a color in code would look like #d1d1d1 and not #d1d1d1ff. However any hex color created by the live-preview components always shows the alpha even if it's 100%.
This change clips the FF from the values create via Slint code. However brush stops are created via Rust and need a separate fix.

Clip FF from hex colors

---

api/cpp/include/slint_models.h
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/interpreter/eval.rs
tests/cases/models/array.slint
tests/cases/models/assign_equal_model.slint

Conversion from negative float to unsigned is saturating to 0 in rust and undefined behavior in C++, we should therefore handle the case properly
Fixes #8222

Fix array index access at negative index

---

api/node/__test__/api.spec.mts
api/node/typescript/index.ts

We recommend the use of `loadFile(new URL("...", import.metal.url))`,
but this never worked on Windows, because we're not using the API
the Node.js docs even recommend to correctly covert to a local path on Windows.
Fixes #8209

Node.js: Fix support for loadFile() with an URL on Windows

---

internal/compiler/layout.rs
internal/compiler/passes/flickable.rs
internal/compiler/passes/inlining.rs
tests/cases/layout/issue8091_overriden_padding.slint

The layout pass needs to see when going over the layout, that these properties are set. So inline the element that sets these properties if they are not set in the base.
Fixes #8091

Fix layout property set in when deriving components

---

api/cpp/platform.rs
internal/backends/android-activity/androidwindowadapter.rs
internal/backends/linuxkms/display.rs
internal/backends/linuxkms/display/swdisplay.rs
internal/backends/linuxkms/display/swdisplay/dumbbuffer.rs
internal/backends/linuxkms/display/swdisplay/linuxfb.rs
internal/backends/linuxkms/display/vulkandisplay.rs
internal/backends/linuxkms/renderer/skia.rs
internal/backends/linuxkms/renderer/sw.rs
internal/backends/winit/lib.rs
internal/backends/winit/renderer/femtovg.rs
internal/backends/winit/renderer/femtovg/glcontext.rs
internal/backends/winit/renderer/skia.rs
internal/backends/winit/renderer/sw.rs
internal/backends/winit/winitwindowadapter.rs
internal/core/api.rs
internal/core/window.rs
internal/renderers/skia/d3d_surface.rs
internal/renderers/skia/lib.rs
internal/renderers/skia/metal_surface.rs
internal/renderers/skia/opengl_surface.rs
internal/renderers/skia/software_surface.rs
internal/renderers/skia/vulkan_surface.rs

In preparation for wgpu usage, where the wgpu API requires the window handle to be send, i.e. Arc<dyn HasWindowHandle>.

Replace use of Rc<winit::window::Window> with Arc

---

tools/figma-inspector/backend/utils/export-variables.ts

there was a discrepancy between variable names and struct names because they were using different sanitizers

figma-inspector: sanitizer was broken for some characters

---

tools/figma-inspector/backend/utils/export-variables.ts
tools/figma-inspector/shared/universals.d.ts

There were a few clear instances that could be consolidated and extra helper functions removed

figma-inspector: consolidating sanitizers

---

tools/figma-inspector/backend/utils/export-variables.ts

also resolve any variables not in current file

figma-inspector: resolve variables in binding loops that reference their own struct

---

docs/astro/src/content/docs/reference/global-functions/math.mdx
internal/compiler/expression_tree.rs
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/llr/optim_passes/inline_expressions.rs
internal/compiler/lookup.rs
internal/interpreter/eval.rs
tests/cases/expr/exp.slint
tests/cases/expr/ln.slint

I felt these should be added, as they are already implemented in all used std math libraries, and it avoids developers defining e in their Slint code.
[exp_m1](https://doc.rust-lang.org/std/primitive.f64.html#method.exp_m1) and [ln_p1](https://doc.rust-lang.org/std/primitive.f64.html#method.ln_1p) would also be good addition for optimization, but I'll leave that up to the reviewers.
ChangeLog:
Added `Exp` function to Slint
Added `Ln` function to Slint
Added tests for `Exp` and `Ln`

Added Exp and Ln functions to Slint

---

tools/figma-inspector/backend/utils/export-variables.ts

broke variable values due to separator inconsistency

regression when reducing sanitizers

---

.github/workflows/autofix.yaml

The mise tasks sometimes hang and hog an action runner for 90 minutes

Add timeouts to the Autofix task

---

examples/todo/rust/lib.rs

... when `SLINT_EMIT_DEBUG_INFO` is not set.

examples: Do not fail `todo` example test

---

tools/figma-inspector/backend/utils/property-parsing.ts

figma-inspector: x and y sometimes return null and until we have layout logic, make these 0

---

internal/backends/qt/lib.rs
internal/backends/qt/qt_window.rs

This is a hook for the Qt backend that provides the ability to access the `QWidget` for a window, similar to how the `winit` back end supports accessing the `winit` `Window` object

Created an accessor for the Qt backend to access a window's `QWidget`

---

tools/figma-inspector/backend/code.ts
tools/figma-inspector/src/main.tsx
tools/figma-inspector/src/utils/bolt-utils.ts

listenTS's callback should only receive the data structures that match the event.
Also tidy up a few other event listener callbacks.

figma-inspector: Restore type safety for message interface

---

tools/figma-inspector/backend/utils/export-variables.ts

when combining collections, mode3_brush was too ambiguous.  
now using <collection>_mode3_brush

figma-inspector: corrected overwrite of reused modes 

---

tools/figma-inspector/figma.config.ts
tools/figma-inspector/src/main.tsx
tools/figma-inspector/tests/property-parsing.test.ts
tools/figma-inspector/tsconfig.json

Ensures the unit tests are type checked. 
Removes unused cloudflare network access permission.
Removes a condition that always returned 'Design Tokens' string.

Tiny Figma fixes

---

pnpm-lock.yaml
tools/figma-inspector/package.json
tools/figma-inspector/src/main.tsx
tools/figma-inspector/src/utils/store.ts
tools/figma-inspector/src/utils/utils.ts

This adds the Zustand state library to simplify react state handling.
It allows all the listening to the Figma side of the plugin to be moved inside it. This inturn allows quite a bit of logic to also move over to the store.ts file and start to leave Main.tsx to only describe the UI.

Use Zustand to handle state and simplify Main.tsx

---

api/cpp/platform.rs
api/rs/slint/tests/partial_renderer.rs
internal/backends/android-activity/androidwindowadapter.rs
internal/backends/linuxkms/renderer/skia.rs
internal/backends/winit/lib.rs
internal/backends/winit/renderer/femtovg.rs
internal/backends/winit/renderer/skia.rs
internal/backends/winit/renderer/sw.rs
internal/renderers/skia/d3d_surface.rs
internal/renderers/skia/lib.rs
internal/renderers/skia/metal_surface.rs
internal/renderers/skia/opengl_surface.rs
internal/renderers/skia/software_surface.rs
internal/renderers/skia/vulkan_surface.rs
tools/docsnapper/headless.rs

Share Vulkan instance as well as Metal device and command queue across windows.

Skia: Improve multi-window rendering resource consumption

---

.github/workflows/build_docs.yaml
.github/workflows/ci.yaml
.github/workflows/nightly_snapshot.yaml
.github/workflows/wasm_editor_and_interpreter.yaml
package.json
pnpm-lock.yaml

Bump to the newest pnpm.
Add some missing script permissions for Biome and Sharp.
Remove some old security override fix that is no longer needed as the packages were properly fixed.

Fix pnpm missing script permissions

---

.github/workflows/autofix.yaml

Some mise tasks never complete. Today the following warning showed up: 
mise WARN  GitHub API returned a 403 Forbidden error. This likely means you have exceeded the rate limit.
mise WARN  GITHUB_TOKEN is not set. This means mise is making unauthenticated requests to GitHub which have a lower rate limit.
To increase the rate limit, set the GITHUB_TOKEN environment variable to a GitHub personal access token.
Create a token at https://github.com/settings/tokens and set it as GITHUB_TOKEN in your environment.
You do not need to give this token any scopes.
Maybe this will fix the CI errors?

Try to fix Mise rate limiting

---

api/rs/slint/Cargo.toml
api/rs/slint/lib.rs
examples/wgpu_texture/Cargo.toml
examples/wgpu_texture/main.rs
internal/backends/selector/api.rs
internal/core/api.rs
internal/core/graphics.rs
internal/core/graphics/wgpu_24.rs
internal/renderers/femtovg/wgpu.rs

- Create a `slint::wgpu_24` module
- Re-export `wgpu` in it
- Place the WGPU config types used by the `BackendSelector::require_wgpu_24` function in it, and remove the 24 infix.
As an upside, this also adds the feature guard to the docs at least for the `wgpu_24` module.

WGPU: Clean up public API

---

tools/figma-inspector/backend/utils/export-variables.ts
tools/figma-inspector/src/main.tsx

figma-inspector: added em dash to the sanitizers

---

api/rs/slint/Cargo.toml
api/rs/slint/lib.rs
internal/backends/selector/Cargo.toml
internal/backends/selector/api.rs
internal/backends/winit/accesskit.rs
internal/backends/winit/event_loop.rs
internal/backends/winit/lib.rs
internal/backends/winit/muda.rs
internal/backends/winit/winitwindowadapter.rs

Similar to the wgpu access, the `unstable-winit-030` feature exposes a `slint::winit_030` module, which in turn re-exports `winit` but also provides access to the `WinitWindowAccessor` trait. The `BackendSelector` is extended to provide a way to hook into window attribute creation as well as providing a custom event loop builder, similar to what `i_slint_backend_winit::BackendBuilder` provides.

slint crate: Expose parts of the winit backend's previously private API

---

tools/figma-inspector/backend/code.ts
tools/figma-inspector/backend/utils/property-parsing.ts
tools/figma-inspector/shared/universals.d.ts
tools/figma-inspector/src/utils/store.ts

In Figma dev-mode once you select an item in Figma it shows the slint snippet. If you then change any properties on the selected item the snippet updates. This is because the dev-mode automatically detects those changes and requests an update.
In the design view the api is different. The 'selection changed' event is used to show the initial snippet but subsequent changes will not be detected untill the user selects another item and then reselects the changed one. This PR adds a listener to the currently selected item to react to the NodeChanged event and update the snippet.
This PR also tidies up some dead async code. There were try catch blocks on code that according to the figma api docs never throw exceptions. Plus a few awaits on non async functions.

(Figma-plugin) Editing a property should update the snippet in design view

---

internal/backends/android-activity/Cargo.toml
internal/backends/android-activity/build.rs
internal/backends/android-activity/javahelper.rs

Closes <https://github.com/slint-ui/slint/issues/7829>; solves <https://github.com/slint-ui/slint/issues/7203#issuecomment-2616113738>; simplifies dex loading procedure for older Android versions.

Android: use `android-build` dev dependency; small fixes

---

internal/backends/qt/qt_window.rs

Detect if a button is still pressed before deciding that no button is down.
Fixes #8335

qt backend: Fix mouse up not being sent when pressing multiple buttons

---

tools/figma-inspector/src/main.css

This fixes an issue where the code snippet was drawing horizontaly outside its bounds.

(figma) Fix for design mode snippet clipping badly

---

internal/renderers/skia/cached_image.rs
internal/renderers/skia/itemrenderer.rs
internal/renderers/skia/lib.rs
internal/renderers/skia/opengl_surface.rs

This makes it easier to keep cfg'ed code in the cfg' surfaces than cfg'ing in cached_image.rs :)

Skia: Delegate texture import to the surface trait

---

internal/compiler/generator/rust.rs
tests/cases/globals/global_binding_const.slint

We must take care that all access to property that we consider constant in global are accessed after the global has been initialized.
So initialize the global before the properties.
Fixes #8375 , #8337

Rust generated: fix constant non-inlined global

---

api/cpp/include/slint.h
api/cpp/lib.rs
api/rs/slint/private_unstable_api.rs
docs/astro/astro.config.mjs
docs/astro/src/content/docs/reference/global-namespaces/platform.mdx
docs/astro/src/content/docs/reference/std-widgets/style.mdx
internal/compiler/builtins.slint
internal/compiler/expression_tree.rs
internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/compiler/llr/optim_passes/inline_expressions.rs
internal/compiler/lookup.rs
internal/compiler/passes.rs
internal/compiler/passes/lower_platform.rs
internal/compiler/passes/resolving.rs
internal/compiler/tests/syntax/lookup/deprecated_property.slint
internal/compiler/typeloader.rs
internal/compiler/widgets/cosmic/std-widgets-impl.slint
internal/compiler/widgets/cupertino/std-widgets-impl.slint
internal/compiler/widgets/fluent/std-widgets-impl.slint
internal/compiler/widgets/material/std-widgets-impl.slint
internal/core-macros/link-data.json
internal/core/Cargo.toml
internal/core/lib.rs
internal/interpreter/eval.rs
tests/cases/platform.slint
tools/lsp/ui/components/widgets/widget-helpers.slint

This replaces the previously hidden `StyleMetrics.style-name` that was only accessible for internal use, introduced in #8200.
Additionally, this introduces `Platform.os`.

Introduce `Platform.style-name` and `Platform.os`

---

tools/lsp/preview.rs

Do not apply the live data after hitting the reload button in live preview.

live_preview: Do not apply live data changes after "Reload"

---

internal/compiler/generator/rust.rs

From the v1.11.0 crash reporter:
There is a panic in
`target/x86_64-unknown-linux-gnu/release/build/slint-lsp-8494405be069a534/out/main.rs:115729:64`
```
called `Result::unwrap()` on an `Err` value: Other("Could not initialize any renderer for LinuxKMS <REDACTED: user-file-path> from Skia renderer: Error opening device <REDACTED: user-file-path>: No such file or directory (os error 2)\\nError from FemtoVG renderer: Error reading DRM resource handles: Permission denied (os error 13)\\nError from Software renderer: Error opening device <REDACTED: user-file-path>: No such file or directory (os error 2)\\nNo renderers configured.")
```
That line in the generated file is in
```rs
115728   │          fn window_adapter_impl (& self) -> sp :: Rc < dyn sp :: WindowAdapter > {
115729   │ …
```

Prospective panic fix in the rust generated code

---

demos/home-automation/ui/components/mainView/mainScreen.slint

Show 12 instead of 0 for noon/midnight and fix AM/PM logic

Fix time display in home automation demo

---

internal/compiler/passes/resolving.rs
internal/compiler/tests/syntax/expressions/comparison_operator2.slint
tests/cases/expr/comparison.slint

The compiler was accepting the comparison of types such as color, or struct, and then later we'd get rust compilation error or interpreter panic.
Example seen in the crash reporter:
`internal/interpreter/eval.rs:257:35`
```
unsupported Value::Brush(SolidColor(Color { red: 0, green: 0, blue: 0, alpha: 0 })) ≤ Value::Brush(SolidColor(Color { red: 255, green: 0, blue: 0, alpha: 255 }))
```
Note that some code hapenned to compile with rust or C++. For example, comparison of bool, or anonymous struct (represented as tuples), or color represeted as int)
So technically this is a breaking change.
But this should be fine as this was not working in the interpreter and this is a bug fix.
ChangeLog: Slint compilation error for comparison of types that can't be compared with less or greater operator.

compiler: Reject comparison on unsupported types

---

api/cpp/cbindgen.rs
api/cpp/include/slint-platform.h
internal/core/graphics.rs

It was used in the previous TargetPixelBuffer interface, but this is no longer the case

Remove CompositionMode enum

---

internal/compiler/widgets/common/menus.slint

The ContextMenuArea on android intercepts clicks to trigger on long clicks and this prevent the MenuBar's TouchArea to work properly
Fixes #8353

Fix MenuBar on android

---

internal/backends/winit/event_loop.rs
internal/backends/winit/lib.rs
internal/backends/winit/winitwindowadapter.rs

Process pending inactive windows to create at the end of each event loop cycle.

winit: Remove ACTIVE_EVENT_LOOP thread-local

---

internal/backends/winit/accesskit.rs

Was missing from #8152 
As discussed in #6975

Set size of set on AccessKit container nodes

---

tools/lsp/common.rs
tools/lsp/main.rs
tools/lsp/preview.rs
tools/lsp/preview/native.rs
tools/lsp/wasm_main.rs

Send telemetry data from the live-preview to vscode.
It will process that data according to telemetry settings in VScode
This covers the part of getting the telemetry events to VSCode... We still need to get it recorded from there (which it may or may not do automatically).

live-preview: Send telemetry to VSCode

---

demos/home-automation/ui/components/mainView/mainScreen.slint

Colored logo provides better visual appeal during demonstrations.
This also addresses an issue where the first touch in kiosk mode (which deactivates it) appeared unresponsive due to no immediate visual feedback.

Home Automation: adjust logo appearance

---

demos/home-automation/ui/components/mainView/mainScreen.slint

It was highlighted with yellow underline. Does this rounded rect background work for current UI?

Home Automation: Highlight current tab

---

demos/home-automation/ui/components/alarm.slint

Remove unnecessary indirect-passcode property.
Change max length of passcode to 4.

Home Automation: Refactor alarm passcode logic

---

internal/renderers/femtovg/fonts.rs

Femtovg text renderer: avoid leaving space for the `\n` when considering alignment

---

.mise/tasks.toml

Many dependencies in turn install their own copies of various npm packages such as esbuild and vite. This can cause issues where an exact version is needed but the wrong one gets used or a security fix fails to replace all versions of a certain package. 'pnpm dedupe' removes all the copies and just leaves the latest versions.

mise: Teach autofix to dedupe pnpm lock file

---

tools/figma-inspector/backend/utils/property-parsing.ts
tools/figma-inspector/tests/property-parsing.test.ts

(group, vector) and fixed rgb2hex support of alpha

figma-inspector: adding some support for other object types

---

api/python/Cargo.toml
api/python/models.rs
api/python/value.rs

- Upgrade to latest PyO3 release
- Remove dead code
- Rename helper function for clarity

Python: Smaller cleanups

---

.github/workflows/cpp_package.yaml

Build from source is broken after zip-rs dependency having been yanked. Try with binstall instead.

CI: Fix espup install

---

internal/compiler/typeloader.rs

Fixes https://github.com/slint-ui/slint/issues/8445

compiler: Fix compilation if SLINT_DEFAULT_STYLE.txt gets deleted

---

examples/mcu-board-support/pico2_st7789.rs

400 kB would be alright because pico 2 has 520 KB on-chip SRAM
See https://github.com/slint-ui/slint/discussions/8477

MCU pico2: increase heap size

---

api/rs/build/lib.rs
internal/backends/testing/search_api.rs

Using `i-slint-backend-testing` requires the environment variable `SLINT_EMIT_DEBUG_INFO=1` to be set when building the slint components.
When the components are created with the `slint!` macro this can be easily achieved via build.rs:
```rust
fn main() {
// Set SLINT_EMIT_DEBUG_INFO=1 for tests, rust-analyzer, etc.
if std::env::var("DEBUG") == Ok("true".to_string()) {
println!("cargo:rustc-env=SLINT_EMIT_DEBUG_INFO=1");
}
}
```
If the components are in dedicated `.slint` modules this becomes a lot tricker.
This PR adds the ability to build modules with debug info via build.rs:
```rust
fn main() {
// Set SLINT_EMIT_DEBUG_INFO=1 for tests, rust-analyzer, etc.
if std::env::var("DEBUG") == Ok("true".to_string()) {
let config = slint_build::CompilerConfiguration::new().with_debug_info(); …
```

add option to create CompilerConfiguration with_debug_info

---

demos/usecases/ui/app.slint
demos/usecases/ui/views/main_view.slint
internal/compiler/passes/binding_analysis.rs
internal/compiler/tests/syntax/analysis/binding_loop_layout.slint
internal/compiler/tests/syntax/analysis/binding_loop_layout2.slint
internal/compiler/tests/syntax/analysis/binding_loop_layout_if.slint
internal/compiler/tests/syntax/analysis/binding_loop_window.slint
internal/compiler/tests/syntax/analysis/binding_loop_window2.slint

The Window geometry depends on its constraints, so its constraints cannot depends on its geometry
This fixes Infinitely growing layout, and other panics
Fixes #3989
Fixes #2902

Detect binding loops that applies to the Window itself

---

api/node/typescript/index.ts
internal/compiler/parser.rs
internal/interpreter/api.rs
internal/interpreter/dynamic_item_tree.rs
internal/interpreter/ffi.rs
internal/interpreter/json.rs
tests/cases/properties/dashes.slint

`__1` is a valid identifier, which we normalized to `--1`, which is invalid.
This changes the normalization function to leave a `_` in the first position.
This is probably a bit slower than what we had before:-/

compiler: Fix identifier normalization function

---

api/rs/build/lib.rs

[edited based on comments from @ogoffart below ...]
This derives `Clone` for `CompilerConfiguration`.
The underlying inner `i_slint_compiler::CompilerConfiguration` is already Clone and this change does no harm.
My initial motivation was to allow for compiling multiple modules separately for the purpose of unit testing them individually. After taking a further look at how the compiler works and the generated output, this is "not simple".
Having Clone implemented in the upstream would make it much easier for me to work on this challenge within my own project and maybe provide a generic solution for optional consideration later, in case it is of value to others.

Make `CompilerConfiguration` `Clone`

---

tools/lsp/common.rs
tools/lsp/preview.rs
tools/lsp/preview/drop_location.rs

.. to clean up `preview.rs` a bit.
The functionality is generic and could be used in both LSP and preview, so common with the other helper code seems appropriate.

lsp: Move `poll_once` into common

---

internal/core/items/flickable.rs
internal/core/properties/change_tracker.rs
tests/cases/elements/flickable_stay_in_bounds.slint

When either the viewport gets smaller or the Flickable gets bigger, we should move the viewport position to keep it within the bounds.
Fixes #7487
Fixes #2227
(Also workaround #8147 as the ScrollView will automatically go back in bounds)

Flickable: add a change event handler to keep it in bound when geometry changes

---

internal/compiler/passes/remove_return.rs
tests/cases/expr/return3.slint

... when the two branch of a if/else return, and one of the branch has also non-terminator return in sub conditions
Fixes #8485

Compiler: Fix generated invalid expressions in remove_return pass

---

.mise/config.toml
tools/lsp/preview.rs
tools/lsp/preview/native.rs
tools/lsp/preview/wasm.rs

Make sure all code in preview is actually running in the UI thread. For WASM this is a NOOP, as we have just one thread there anyway.
For the native side, we need to handle all lsp to preview messages in the UI thread. This is a bit trickier than it sounds: We do not want to bring up the UI thread fully till the UI needs to be shown.
So we reuse the machanism used to switch between WASM preview and native preview in VSCode:
We listen for a `ShowPreview` message and if the event loop is not up, we bring it up and send a `RequestState` to the LSP. That will respond with all the data we need and repeat its `ShowPreview` rerquest afterwards.

live-preview: Disentangle threads

---

Cargo.toml
api/cpp/lib.rs
api/cpp/platform.rs
internal/backends/qt/lib.rs
internal/backends/qt/qt_widgets/palette.rs
internal/backends/qt/qt_widgets/stylemetrics.rs
internal/backends/qt/qt_window.rs
internal/backends/testing/ffi.rs
internal/core/callbacks.rs
internal/core/date_time.rs
internal/core/graphics/color.rs
internal/core/graphics/image.rs
internal/core/graphics/path.rs
internal/core/item_tree.rs
internal/core/items.rs
internal/core/items/flickable.rs
internal/core/items/input_items.rs
internal/core/items/text.rs
internal/core/layout.rs
internal/core/menus.rs
internal/core/properties/ffi.rs
internal/core/sharedvector.rs
internal/core/string.rs
internal/core/tests.rs
internal/core/timers.rs
internal/core/translations.rs
internal/core/window.rs
internal/interpreter/ffi.rs

To be compatible with the 2024 edition, we need to wrap the `no_mangle` attribute in `unsafe()`.
The parsing for that in cbindgen was only added in the version 0.28, but we couldn't upgrade cbindgen before because of a regression in cbindgen 0.27 that prevented us from upgrading.
Now that cbindgen 0.29 is released with a fix, we can prepare for the 2024 edition

Upgrade cbindgen and use `unsafe(no_mangle)` attributes

---

tools/lsp/preview.rs
tools/lsp/preview/native.rs
tools/lsp/preview/wasm.rs

The first patch makes the shutdown case run more code in the UI thread. This is necessary so that I can merge the ContentsCache and the PreviewState in the second patch.
There is more here that could be done as some of the merged state seems redundant now, but I will leave that for later.
Mid term I would love to get to a state where both the LSP and the live preview run in separate processes -- each (basically) single threaded. That should enable me to remove quite a bit of he startup synchronization code.

live-preview: Cleanup and simplify preview.rs

---

tools/lsp/ui/assets/search.svg
tools/lsp/ui/components/widgets/floating-brush-picker-widget.slint
tools/lsp/ui/components/widgets/floating-brush-sections/svg-color-ui.slint

Filter out brush globals if the property only supports <color>.
Show a search icon in the search bar.

live-preview: Improve filter UX

---

examples/uefi-demo/demo.slint

After 80de96488af07f4f0f1cb85b3ee3d53249cc1689 we now detect binding loop if the window's layout depends on itself

uefi demo: Fix compilation in master

---

.github/workflows/nightly_tests.yaml
internal/renderers/skia/Cargo.toml

This version syncs with Skia's milestone 137. See also https://github.com/rust-skia/rust-skia/releases/tag/0.86.0
Most relevant for us, this version compiles again with the latest cc crate when cross-compiling.
Fixes #6875

renderer-skia: Update to skia-safe 0.86

---

docs/astro/src/content/docs/reference/std-widgets/views/scrollview.mdx
internal/compiler/widgets/cosmic/scrollview.slint
internal/compiler/widgets/cupertino/scrollview.slint
internal/compiler/widgets/fluent/scrollview.slint
internal/compiler/widgets/material/scrollview.slint
internal/compiler/widgets/qt/internal-scrollview.slint
internal/compiler/widgets/qt/scrollview.slint

Adds a `draggable` property to ScrollView that binds to the `interactive` property of the internal Flickable. Should close #2260.

added draggable property to ScrollView, closes #2260

---

.mise/config.toml

That seems to work more reliable at this time.

ci: Use ubi over aqua for `fd` in .mise/config.toml

---

internal/core/input.rs
tests/cases/elements/toucharea_doubleclick.slint

corelib: Fix overflow when spamming the TouchArea with clicks

---

tools/lsp/preview/wasm.rs

The lsp_to_preview_message is being sent from the JS runtime and this is not called from the event loop.
When the preview is starting the 50ms timer to refresh itself, since this is not called from the event loop, there is nothing to wake the event loop up to fire this timer until a mouse event or some other event wakes the event loop.
To make sure this works, call lsp_to_preview_message from the event loop to make sure that the timer is already started when the event loop goes to sleep and only sleep for the duration of that timer

wasm prevew: Make sure the call to show preview work

---

api/cpp/include/slint_models.h
tests/cases/models/model.slint

Rust had a test for it, but C++ not yet
Reported on https://chat.slint.dev/public/pl/pcqefc3fbff3xfuio3uhp58ate

C++: make sure we do not crash if a `Model::row_data` returns `nullopt`

---

internal/compiler/passes/resolving.rs
tools/lsp/preview/eval.rs
tools/lsp/preview/properties.rs
tools/lsp/preview/ui.rs
tools/lsp/preview/ui/palette.rs
tools/lsp/preview/ui/property_view.rs
tools/lsp/ui/api.slint

Reuse the new eval code when collecting values, removing about 200 lines of code in total and bringing the property editor onto the same base as the palette. This gives somewhat better values and handles use of palette elements, too.
Fixes quite a few issues we had in the UI for brushes and palettes when used from the Property Editor.

live-preview: Get better basic values for the property editor

---

editors/vscode/src/common.ts

This allows the user to CTRL/CMD click on a basic element like 'Rectangle' or 'Text' and have the browser be opened to the correct help page.
There are many other ways this type of functionality could be done and probably in ways any editor using the Slint LSP can take advantage of. VScode also has multiple types of help, including the on-hover inline help system. But these all require more effort to support, including generating the right markdown files or teaching the LSP about the help. While this simple tweak gives a bit of extra help access to VScode users right away.

POC for letting VScode open the browser help for basic elements

---

tools/lsp/preview/ui/palette.rs
tools/lsp/ui/api.slint
tools/lsp/ui/components/widgets/floating-brush-picker-widget.slint
tools/lsp/ui/components/widgets/floating-brush-sections/color-mode-and-apply.slint
tools/lsp/ui/components/widgets/floating-brush-sections/css-color-ui.slint
tools/lsp/ui/components/widgets/floating-brush-sections/palettes.slint
tools/lsp/ui/windowglobal.slint

Rename svg color to css.
Ensure 'Apply' is at the bottom in all modes.
Give empty recent colors a frame so there isn't a huge empty space when there are no recents.
Tweak the layout based on these changes.

Polish picker for release

---

tools/lsp/preview.rs
tools/lsp/preview/ui/palette.rs
tools/lsp/ui/components/widgets/floating-brush-picker-widget.slint

A couple of small changes to address the issues raised in #8596.
This filters out non-brushes and refreshes palettes to those visible to the actual selected object.

live-preview: Palette polish

---

tools/lsp/fmt/tool.rs
tools/lsp/preview/element_selection.rs
tools/lsp/preview/eval.rs

That is supposed to help catch some cases where functions panic, but it missed the two `expect(...)` calls, so it is definitely not a complete solution.
I'd love to fuzz this, but AFAICT `rowan` does not support the `arbitrary` crate, so I can not have the fuzzer create random Expressions as input.
Fix the few clippy warnings in the LSP.

live-preview: Add warning about missing panics doc to eval.rs

---

tools/lsp/ui/components/console-panel.slint
tools/lsp/ui/main.slint

Now the console can be put anywhere in the live-preview this PR moves it under the main preview.
It also tweaks some values so the console shows a little bit more content.

Move the console under the live-preview

---

Cargo.toml
helper_crates/vtable/CHANGELOG.md
helper_crates/vtable/Cargo.toml
helper_crates/vtable/macro/Cargo.toml
helper_crates/vtable/macro/macro.rs
helper_crates/vtable/src/lib.rs
helper_crates/vtable/tests/test_vtable.rs
internal/core-macros/lib.rs
internal/core/graphics/image.rs
internal/core/item_tree.rs
internal/core/items.rs
internal/core/menus.rs
internal/interpreter/Cargo.toml
internal/interpreter/dynamic_item_tree.rs

When using rust, allow panics to cross the boundaries of our vtable traits. This avoids panic producing two backtrace with panic=unwind
This patch doesn't touch the ABI of out FFI interface, they stay extern "C", because if a panic or exception crosses these boundaries, we are in trouble. (Also, we have a panic=abort in our Cargo.toml anyway)

Use "C-unwind" API in our vtable

---

tools/lsp/preview.rs
tools/lsp/preview/native.rs
tools/lsp/preview/wasm.rs

Get rid of the `ui_is_visible` flag. That made more sense when it was in the contents cache wich allowed for multi-threaded access. When that changed, the flag moved next to `ui`, so it makes no sense to keep anymore.

live-preview: Simplify hide/show handling

---

api/cpp/CMakeLists.txt
api/cpp/docs/cmake.md
api/cpp/docs/mcu/generic.md

Because some crate in our examples are using the edition2024 resolver with no way to remove them without removing the exmaples from the workspace, this means that effectively the C++ build which needs to run the cargo metadata on the workspace, doens't build anymore with the rust MSRV
ChangeLog: C++: requires Rust 1.85

Update C++ MSRV

---

internal/interpreter/api.rs
internal/interpreter/dynamic_item_tree.rs
internal/interpreter/eval.rs

This unbreaks things like this:
```slint
component Test {
init => {
debug("This shows up in the console");
}
if true: Rectangle {
init() => {
debug("This does *NOT* show up");
}
}
}
```

interpreter: Recursively set the debug_handler on all components

---

tools/lsp/preview.rs
tools/lsp/ui/api.slint
tools/lsp/ui/components/console-panel.slint
tools/lsp/ui/windowglobal.slint

... instead of after the view was updated.
So that we don't see the errors prom a previous parse, and we don't miss the debug from init callback

live-preview: auto-clear log message after parsing

---

internal/renderers/femtovg/wgpu.rs

Description:  
This pull request corrects a minor typo in the comments within the `femtovg/wgpu.rs` file. The word "support" was previously misspelled as "suport" in three locations. The comments clarify that async usage in wgpu is not currently supported except on WASM platforms. No functional code changes are included; this is a documentation/comment-only update to improve code clarity.

Fix Typo in Support Comment for Async Usage in WGPU Renderer

---

tools/lsp/preview/eval.rs

We are evaluating recursively all properties. If properties are structs that have many fields, all the fields are evaluated. This patch tries to only evaluate the relevant fields, assuming no side effect.
This improve a lot the evaluation of large files containing many struct such as the exported figma design token. However there is still some progress to do because even with this change, there are still way too many evaluation.

live-preview: optimize evaluation

---

api/rs/slint/lib.rs
internal/core/api.rs
internal/core/graphics.rs
internal/core/graphics/wgpu_24.rs
internal/renderers/femtovg/wgpu.rs

This way we can add the surface texture in a future release without breaking compatibility.

WGPU: Make WGPU24 variant of GraphicsAPI non-exhaustive

---

docs/astro/src/content/docs/guide/platforms/desktop.mdx

Source: My windows dev environment is Windows ARM64, and after the release we're going to add ARM64 binaries.

doc: Mention aarch64 as supported platform for Windows

---

internal/backends/winit/event_loop.rs

This was fatal in previous released and still should be fatal. Otherwise failure will result in a silent perceived hang, as the event loop continues to spin.

winit: Abort the event loop if creating a window failed

---

internal/compiler/generator/cpp.rs
tests/cases/issues/issue_8710_popup_show_from_changed.slint

The window is dependent of an lambda `auto` parameter, so the `template` keyword is required in order to call show_popup
Fixes #8710

C++ Fix compilation of PopupWindow::show in changed callback

---

internal/compiler/passes.rs
tests/driver/rust/build.rs

This fixes a warning in nightly rust which has been better at detecting unused struct
```
error: struct `TextStyle` is never constructed
--> /home/runner/work/slint/slint/target/debug/build/slint-lsp-da851cbad8b87459/out/main.rs:78:66
|
78 |      # [derive (Default , PartialEq , Debug , Clone)] pub struct r#TextStyle {
|                                                                  ^^^^^^^^^^^
|
= note: `-D dead-code` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(dead_code)]`
```
Where TextStyle is only used in some globals whose properties are fully inlined. So first do the pass that removed unused global, and then the pass that remove unused struct

codegen: Don't generate unused struct

---

internal/core/properties.rs
internal/core/properties/change_tracker.rs

Don't drop the ChangeTracker's BindingHolder if it is currently being evaluated as we still need it later.
There was also a bug in DependencyListHead::clear as it was not properly updating all the field, and the use of for_each was problematic if nodes gets delete as we iterate.
Fixes #8741

Fix UB when a change tracker gets deleted as a result of that change tracker evaluation

---

internal/core/properties.rs
internal/core/properties/change_tracker.rs

The dependency nodes would be leaked.
(This was particularly bad for the ones from the Flickable's bounds change tracker since that one has many dependencies, while most change tracker only have one)
Fixes #8768

Fix memory leak with change handler

---

internal/core/properties.rs
internal/core/properties/change_tracker.rs

Revert part of fd993d0b5233d8cc67e6784bea71298669be0a2f Only keep the change in `evaluate` to fix the leak. We can't destroy the nodes in mark_dirty as destroying them while iterating lead to crash

Fix crash in change callback evaluation

---

internal/backends/testing/slint_systest.proto
internal/backends/testing/systest.rs

Let the image crate pick an encoder by mime-type, otherwise fall back to png.
Renaming the field in the response is compatible, as only the tag numbers are encoded. Adding a field to the request is also compatible as every field is optional.

system-testing: Make the image format for snapshots configurable

---

CHANGELOG.md

I was reading the CHANGELOG and was confused about the current year for a second, and then realized this needed to be updated 😂

correct 1.12.0 CHANGELOG release date year

---

api/cpp/cbindgen.rs
api/cpp/include/slint_color.h
api/cpp/include/slint_properties.h
docs/astro/src/content/docs/reference/window/contextmenuarea.mdx
examples/gallery/gallery.slint
internal/backends/winit/muda.rs
internal/common/builtin_structs.rs
internal/compiler/builtins.slint
internal/compiler/widgets/common/menu-base.slint
internal/core/graphics/image.rs
internal/core/items.rs
internal/core/menus.rs

This adds an icon that is displayed to the left of the title, and is also shown for Menus are inside of a parent menu.
Closes #7791

Menu: Add icon property

---

docs/astro/src/content/docs/guide/language/coding/file.mdx
editors/vscode/package.json

Vscode extension: document that relative library path are relative to the workspace

---

docs/astro/src/content/docs/reference/gestures/flickable.mdx
internal/core/items/flickable.rs
tests/cases/elements/flickable_in_flickable.slint

Fixes #8798
ChangeLog: Flickable forward wheel event in a orthogonal direction to their parent

Flickable: reject Wheel events in the orthogonal direction

---

tools/slintpad/src/editor_widget.ts
tools/slintpad/src/index.ts
tools/slintpad/src/preview_widget.ts

We don't want to wait for these function calls.

Replace some biome async linter supressions with an explicit fix

---

tools/lsp/preview.rs
tools/lsp/preview/native.rs

A mechanical cleanup to get this out of the way

live-preview: s/PREVIEW_STATE.with(/PREVIEW_STATE.with_borrow(/

---

internal/compiler/passes/lower_layout.rs
internal/compiler/tests/syntax/layout/padding.slint

The padding property is accepted but doesn't have an effect. It was meant for future use but didn't get any use. And people get confuse when they set it. (See #8829)
Closes: #8829
Closes: #6288

Add a compiler warning when using `padding` outside of layout

---

internal/compiler/generator/rust.rs

Some hardware acceleration routine needs it to be aligned. 
(Eg, Otherwise, we get artifacts when drawing RGBA images with nema-gfx)

Rust codegen: ensure alignment of `Texture`

---

.github/workflows/ci.yaml
api/rs/build/lib.rs
api/rs/slint/Cargo.toml
api/rs/slint/docs.rs
api/rs/slint/private_unstable_api.rs
internal/compiler/generator.rs
internal/compiler/generator/rust.rs
internal/compiler/generator/rust_live_reload.rs
internal/core/api.rs
internal/core/component_factory.rs
internal/interpreter/Cargo.toml
internal/interpreter/api.rs
internal/interpreter/eval.rs
internal/interpreter/lib.rs
internal/interpreter/live_reload.rs
tests/driver/rust/build.rs

This will generate API that calls the interpreter behind the scene.
And it will set a file system watcher so reload automatically
Can be tested by running an app like so:
```
SLINT_LIVE_RELOAD=1 cargo run -p gallery --features=slint/live-reload
```
`SLINT_LIVE_RELOAD=1` is needed at build time so the rust compiler generate the right thing, the `slint/live-reload` feature will be used to enable the runtime for the live-reloading
- Since only the public API needs to be compiled by the rust compiler, the rust compilation is faster.
- The automatic reloading feature works Ok, but can lead to unexpected states. But the application can still be restarted without compiling.
- If the interface changes in an incompatible way (deleted properties or callback or to incompatible types) then the app …

live-reload of .slint file for rust compiled app

---

internal/core/items/flickable.rs
tests/cases/elements/flickable3.slint

Otherwise the inner elements stops receiving event once the mouse gets outside of the flickable.
As discussed here: https://chat.slint.dev/public/pl/doetihff3f8wd8przne9zc75oc
> If your slider is inside a Flickable, the pointer events stop when you drag outside the flickable:  [Demo](https://slintpad.com/?snippet=import+%7B+Slider+%7D+from+%22std-widgets.slint%22%3B%0A%0Aexport+component+Demo+inherits+Window+%7B%0A++++width%3A+400px%3B%0A++++height%3A+300px%3B%0A%0A++++background%3A+%23eee%3B%0A%0A++++Flickable+%7B%0A++++++++width%3A+300px%3B%0A++++++++height%3A+150px%3B%0A%0A++++++++Rectangle+%7B%0A++++++++++++background%3A+%23999%3B%0A++++++++%7D%0A%0A++++++++Slider+%7B%0A++++++++++++width%3A+150px%3B%0A++++++++++++minimum%3A+0%3B%0A++++++++++++maximum%3A+100%3B%0A++++++++%7D%0A++++%7D%0 …

Flickable: the clip detection shouldn't activate when something holds the grab

---

internal/compiler/widgets/common/menu-base.slint
internal/compiler/widgets/cosmic/menu.slint
internal/compiler/widgets/cupertino/menu.slint
internal/compiler/widgets/fluent/menu.slint
internal/compiler/widgets/material/menu.slint
internal/compiler/widgets/qt/menu.slint
tests/cases/widgets/menubar.slint

Padding properties exists as reserved properties but don't have effect. But the menu code was using them to store values.
This is now a warning because people got confused by setting padding and wondering why it has not effect.
This also had some bug in the code were properties were padding was set on a layout, as well as all the padding-* properties, so the padding was not taking in account

Menu: avoid using padding properties

---

api/cpp/tests/CMakeLists.txt
api/cpp/tests/datastructures.cpp
api/cpp/tests/eventloop.cpp
api/cpp/tests/interpreter.cpp
api/cpp/tests/models.cpp
api/cpp/tests/platform_eventloop.cpp
api/cpp/tests/properties.cpp
api/cpp/tests/testing.cpp
api/cpp/tests/window.cpp
examples/todo/cpp/CMakeLists.txt
examples/todo/cpp/tests/test_todo_basic.cpp

Catch2 old version still depend against cmake 3.0 + deprecated method.
Necessary to increase version otherwise when we try to compile
example with cmake 4.0 it will failed to configure it

CMake 4.0 remove some deprecated code < 3.5

---

internal/interpreter/live_reload.rs

Otherwise that doesn't work when the editor renames the files and then remove it, such as what vim or helix are doing
Fixes #8857

live-reload: watch the parent directory instead of the files

---

api/cpp/CMakeLists.txt
api/cpp/Cargo.toml
api/cpp/cbindgen.rs
api/cpp/include/slint-interpreter.h
api/cpp/include/slint_live_reload.h
api/cpp/include/vtable.h
internal/compiler/generator.rs
internal/compiler/generator/cpp.rs
internal/compiler/generator/cpp_live_reload.rs
internal/interpreter/api.rs
internal/interpreter/ffi.rs
internal/interpreter/live_reload.rs
xtask/src/cppdocs.rs

Missing feature:
- conversion between Value and enums
- conversion from value to Model
- Compatibility with the testing framework (get the `VRc<ItemTreeTable>` from an instance)

Live-reload for C++

---

internal/backends/qt/qt_window.rs
internal/backends/testing/testing_backend.rs
internal/core/renderer.rs
internal/core/software_renderer.rs
internal/core/window.rs
internal/renderers/femtovg/lib.rs
internal/renderers/skia/lib.rs

We had code on the window to reset the default-font-size property to the default from the renderer.
For the Qt backend, the PopupWindow being their own Window, this code was activated also for the PopupWindow's hidden default-font-size property, which caused all PopupWindow's font to not follow the default-font-size
Fixes #8855

Fix default-font-size not working with PopupWindow with the Qt backend

---

internal/compiler/passes/binding_analysis.rs
internal/compiler/tests/syntax/analysis/binding_loop_popupwindow.slint

In this case, there is an explicit binding in the PopupWindow::width, so we shouldn't continue and find loop based on the implicit bindings
Fixes #8889

Binding analysis: We shouldn't report binding loop based on base bindings

---

api/cpp/CMakeLists.txt
examples/opengl_texture/main.cpp
examples/opengl_underlay/main.cpp

- Fix the erroneously default of enabling the WPGU FemtoVG renderer for C++
- Improve advice for C++ OpenGL examples to explicitly select the FemtoVG GL renderer
Fixes #8901

C++: Fix opengl_texture example

---

editors/vscode/package.json
editors/vscode/slint.tmLanguage.json

A relative path to outside the node package means the grammar file isn't accessible after packaging. Fortunately vsce resolves symlinks, so the use of a symlink files it.

VS Code Extension: Fix syntax highlighting

---

docs/astro/src/content/docs/reference/std-widgets/views/lineedit.mdx

Copying text in a disabled LineEdit isn't possible, that part of the sentence came from the docu for the read-only property.
In TextEdit, the docu for enabled only says this.

Docs: fix copy/pasted string in docu for LineEdit's enabled property

---

tools/lsp/ui/views/preview-view.slint

Live-Preview: Show "<click> unselect" only when selection exists

---

docs/astro/src/content/docs/guide/development/translations.mdx

1. Move section ```Convert `.po` Files to `.mo` Files``` to the next level below section ```Runtime Translations with Gettext```, because it has no relation to the "Bundled Translations" method.
2. Add `slint_build::compile_with_config()` function to "Bundling" section.

docs: improve "Bundled Translations"

---

docs/astro/src/content/docs/reference/global-structs-enums.mdx
docs/astro/src/content/docs/reference/keyboard-input/focusscope.mdx
internal/common/enums.rs
internal/compiler/builtins.slint
internal/core-macros/link-data.json
internal/core/items/input_items.rs
tests/cases/focus/focus_policy.slint

Adds a new enum `FocusPolicy` for a property `focus-policy` on `FocusScope`, with variants for `TabOnly`, `ClickOnly` and `TabAndClick`. Notably, I did not add a policy for denying focus, as we already have the `enabled` property on `FocusScope`... maybe this should be deprecated in favor of a `Deny` variant?
Should close #3503.
The names I chose for the variants are not great in my opinion, definitely open to suggestions for changing these :sweat_smile:.

Add `focus-policy` property to FocusScope

---

internal/backends/linuxkms/display/swdisplay/linuxfb.rs

LinuxKMS: Set graphics mode on tty to hide cursor and improve 16bpp framebuffer support

---

api/cpp/include/slint_brush.h

Fixed a bug where transparentize() was using linear_gradient instead of radial_gradient when processing RadialGradient brushes.

Fix incorrect gradient type reference in RadialGradient transparentize

---

internal/compiler/generator/rust.rs

Recently we noticed a slowdown of our build times of our relatively large slint files when we started using many many conditionals in functions.
Even incremental builds where we only changed a single string literal in an unrelated rust source file takes a minute to build, when a few months ago it took only seconds.
I checked what `rustc` was spending its time on, and it turns out it was busy generating tons and tons of `unused_paren` lints. Now this lint is `#[allow]`-ed in the module, but I assume that `allow` only comes into play when printing the lints, they are still generated during compilation.
(The callstack is roughly `rustc_lint::unused::UnusedDelimLint::emit_unused_delims` <= `rustc_interface::passes::**early_lint_checks**` <= `rustc_ast_lowering::lower_to_hir`)
Another symptom …

Fix most of "unnecessary parentheses", "unnecessary trailing semicolon" and "unused `std::result::Result`" lints in the generated code

---

internal/compiler/parser.rs

Rust 1.88 produced a compilation error on a piece of code that previous Rust versions accepted. This is a trivial fix that does exactly what `rustc` suggests in the error message.
Update: I tried to roll back both Rust and Slint, but I couldn't find a working combination for Slint >=1.10, when the relevant piece of code was added. This is very curious, because these combinations worked just fine the day before, so it was neither a Rust update nor a Slint change that broke it, but then what?
```
error[E0700]: hidden type for `impl Iterator<Item = parser::SyntaxNode>` captures lifetime that does not appear in bounds
--> internal\compiler\parser.rs:832:9
|
830 |       pub fn descendants(&self) -> impl Iterator<Item = SyntaxNode> {
|                          ----- …
```

compiler: fix compilation error when using Rust 1.88

---

internal/backends/linuxkms/display/swdisplay.rs
internal/backends/linuxkms/display/swdisplay/dumbbuffer.rs
internal/backends/linuxkms/display/swdisplay/linuxfb.rs
internal/backends/linuxkms/drmoutput.rs
internal/backends/linuxkms/renderer/skia.rs
internal/backends/linuxkms/renderer/sw.rs

Introduces initial support for surface format negotiation between the Linux KMS display backends (dumbbuffer, linuxfb) and the software renderers (Skia and Software). The negotiation logic prioritizes selecting a pixel format that is supported by both the renderer and the framebuffer, based on lists of supported DrmFourcc formats.

LinuxKMS: Implement initial format negotiation for software display and renderer.

---

editors/vscode/package.json
editors/vscode/src/extension.ts

... which is disabled by default.
This might help with issues similar to #2577

vscode: Offer an option to set the Slint-lsp binary

---

api/cpp/CMakeLists.txt

clang++.exe doesn't understand the `/bigjob` flag. So use generator expression to only pass the flag with MSVC and pass the correct flag with other compiler (I did mingw as well just in case)
Fixes #8981

Fix for building with clang/msvc2022 (`/bigjob`)

---

internal/compiler/widgets/cosmic/lineedit.slint
internal/compiler/widgets/cupertino/lineedit.slint
internal/compiler/widgets/fluent/lineedit.slint
internal/compiler/widgets/material/lineedit.slint
tests/cases/widgets/lineedit.slint

There is a binding loop that cause a failure in the property editor of the live preview.
Previous version of the LineEdit didn't have a dependency between the height and the width.
Apply an explicit width binding on the recently added image to prevent that.
For the fluent style, also change the size of the `x` to something closer to the actual fluent style (picked the value from fluent's figma design)
(cc @dfaure )

LineEdit: fix height for width dependency

---

internal/backends/qt/qt_window.rs
tests/cases/examples/colored_image.slint

When applying colorize with gradients to images, use the actual pixmap dimensions for the gradient brush instead of the destination rectangle dimensions. This ensures gradients are properly applied to the source image before any transformations.
https://github.com/slint-ui/slint/blob/master/tests/cases/examples/colored_image.slint
skia:
Qt:

Qt: Fix gradient colorize by using pixmap size instead of dest rect

---

internal/core/software_renderer.rs

In order to be able to draw the Qt style with the software renderer and a scale factor
This regressed when DrawTextureArgs was introduced
Fixes #9006

swrenderer: Fix draw_cached_pixmap with a scale factor

---

internal/compiler/passes/lower_menus.rs
tests/cases/widgets/menubar.slint

Fixes #9005
Both `is-separator` and `is_separator` were on the HashMap of the value struct for the MenuEntry. When lowered to actual struct, the `_` is normalized, but then it depends on the order of t

Compiler: Fix menu separator not always being visible

---

api/python/slint/Cargo.toml
api/python/slint/image.rs
api/python/slint/pyproject.toml
api/python/slint/slint/slint.pyi
api/python/slint/tests/test_image.py

ChangeLog: [Python] Add support for creating slint.Image objects from arrays
Fixes #9014

Python: Add support for importing foreign image buffers

---

.github/workflows/build_docs.yaml
Cargo.toml
api/rs/slint/Cargo.toml
api/rs/slint/lib.rs
internal/backends/linuxkms/Cargo.toml
internal/backends/linuxkms/calloop_backend.rs
internal/backends/linuxkms/calloop_backend/input.rs
internal/backends/linuxkms/lib.rs
internal/backends/linuxkms/noop_backend.rs
internal/backends/selector/Cargo.toml
internal/backends/selector/api.rs
internal/backends/selector/lib.rs
internal/backends/winit/lib.rs

This PR extends the BackendSelector with APIs to permit hooking into the event processing of the winit and linuxkms backend.
This will be used in an application to implement detection of user-inactivity.

LinuxKMS / winit: Add support for custom event processing

---

internal/compiler/widgets/cupertino/lineedit.slint

The latest iteration of mac OS doesn't seem to have an x anywhere other than search fields.   I don't know if I'm allowed to just not have it for cupertino (like if something breaks in code if I don't include it in there) so I've altered it so it doesn't look so intensely ungood

live-preview: fixed x for cupertino input fields

---

tools/lsp/preview/connector/native.rs
tools/lsp/ui/main.slint
tools/lsp/ui/views/header-view.slint

as per a conversation with Simon, I've left the reload button in the UI

live-preview: implement MenuBar so we have undo/redo and move the rest over

---

.github/dependabot.yml

Make it run 3 hours early so CI has finished by the time people login on
monday.
Ignore more vscode extensions (coding game).
Better group vite and vitest updates.

chore: Improve dependabot

---

internal/backends/linuxkms/renderer/skia.rs
internal/backends/linuxkms/renderer/sw.rs

We used to just map 32-bpp to XRGB before commit 6f3cd8763bbbd13833c607007af4dd3a0f22489d and that was also fine. We don't really support transparency right now, but we should keep rendering.
Fixes #9126

LinuxKMS: Restore support for rendering to AR24 framebuffers

---

examples/mcu-board-support/Cargo.toml
examples/mcu-board-support/waveshare_esp32_s3_touch_amoled_1_8.rs

Add touch support to examples/mcu-board-support.
The current version is using custom forks of display and touch drivers:
- https://github.com/georgik/sh8601-rs
- https://github.com/georgik/ft3x68-rs
Once those changes get merged, those crate version could be switched to official release at crates.io.
PRs:
- https://github.com/theembeddedrustacean/ft3x68-rs/pull/1
- https://github.com/theembeddedrustacean/sh8601-rs/pull/1

Waveshare S3 Touch AMOLED - add touch

---

internal/compiler/langtype.rs

This is a very common case. Any conversion from float to int will trigger this function with empty vecs, for instance. When building a tiny example app, this is called 304 times with empty vecs (while parsing all the builtin .slint files)
The main motivation for this is readability / debugging more than performance though.

unit_product_length_conversion: early return for ([], [])

---

internal/compiler/langtype.rs
internal/compiler/llr/optim_passes/count_property_use.rs
internal/compiler/passes/apply_default_properties_from_style.rs
internal/compiler/passes/collect_custom_fonts.rs
internal/compiler/passes/collect_globals.rs
internal/compiler/passes/collect_init_code.rs
internal/compiler/passes/collect_structs_and_enums.rs
internal/compiler/passes/collect_subcomponents.rs
internal/compiler/passes/infer_aliases_types.rs
internal/compiler/passes/lower_layout.rs
internal/compiler/passes/lower_menus.rs
internal/compiler/passes/lower_platform.rs
internal/compiler/passes/lower_popups.rs
internal/compiler/passes/lower_tabwidget.rs
internal/compiler/passes/lower_text_input_interface.rs
internal/compiler/passes/lower_timers.rs
internal/compiler/passes/resolving.rs

Fix grammar and typos in comments (in the compiler passes)

---

docs/astro/src/content/docs/guide/language/coding/functions-and-callbacks.mdx

- Don't render text and button on top of each other.
- Let something happen when clicking the button.
Fixes #9088

doc: Fix up function calling example

---

tools/lsp/ui/main.slint

Some fixes from #9096:
- Enable the undo/redo entries only if it is available
- Use binding on the title of the "Keep on Top" entry

live-preview: Fixup the menu implementation

---

editors/vscode/src/wasm_preview.ts
tools/lsp/Cargo.toml
tools/lsp/preview/connector/wasm.rs
tools/lsp/ui/api.slint
tools/lsp/ui/main.slint
tools/slintpad/src/editor_widget.ts
tools/slintpad/src/index.ts
tools/slintpad/src/lsp.ts
tools/slintpad/src/preview_widget.ts
tools/slintpad/tests/smoke-test.spec.ts

This swaps the text editor to the right and thus makes room for the Slint built-in menu bar. In Slintpad, the menu bar shows two additional entries in the File menu:
- The "Open Demo" sub-menu originates from the earlier web menubar and forwards to the editor.
- The share menu item is also quite useful from the web menu, but is now implemented by means of directly copying to the clipboard.

SlintPad: Replace web menubar with Slint menubar

---

internal/backends/winit/winitwindowadapter.rs

Don't pass zero min/max sizes to winit, as from there on it might get
back to us, and we'll try to create zero sized rendering surfaces. But
even if we bailed out then, it would be unusable for the user.
For example, this avoid panics or crashes in the live-preview when
editing window/layout code that ends up with a zero min/max height.
Fixes #8926

winit: Avoid panics due to zero width/height windows

---

internal/backends/winit/Cargo.toml
internal/backends/winit/build.rs
internal/backends/winit/lib.rs
internal/backends/winit/renderer/femtovg.rs
internal/renderers/femtovg/Cargo.toml
internal/renderers/femtovg/lib.rs

Building with --no-default-features --features compat-1-2,backend-winit,renderer-femtovg-wgpu should not require glutin.

FemtoVG: Support compiling without OpenGL

---

internal/backends/qt/qt_window.rs

Avoid the warning
```
QGraphicsEffectSource::draw: Can only begin as a result of QGraphicsEffect::draw
```
Should fix #4008

Qt: fix drawing of blur

---

internal/compiler/passes/compile_paths.rs
internal/compiler/tests/syntax/elements/path.slint

After commit ef2e6491cddd619fa00af321d379b77071635b0a we end up processing Paths multiple times, and thus we might end up attempting to replace an elements binding. Don't do that if no new elements are declared, but yield an error if attempting to do so. We could support this in the future (appending), but for now it's better to produce an error.
Fixes #9170

Fix regression in the Path element when used with inheritance

---

internal/compiler/generator/cpp.rs
internal/compiler/generator/rust.rs
internal/core/items.rs
internal/core/window.rs
tests/cases/text/componentcontainer_font_size_propagation.slint
tests/cases/text/font_size_propagation.slint

With thanks to Simon for the guidance on how to fix this.
Fixes #8855
Please review carefully, I'm not sure about the assumption that if there's a context but no repeater index then it must be a PopupWindow (which is based on how ˋgenerate_item_treeˋ is currently called, but could be surprising if that changes in the future). Should I pass an extra argument to ˋgenerate_item_treeˋ instead, like it already has for ˋis_popup_menuˋ? (if so, maybe an enum then, to avoid 2 bools?)
Also, this showed that autotests could pass with the interpreter and fail with the compiler - should the test framework be extended to also run these test cases with the compiler?

Fix default font size not being propagated to popup windows

---

internal/backends/winit/lib.rs
internal/backends/winit/renderer/femtovg.rs
internal/backends/winit/renderer/skia.rs
internal/backends/winit/renderer/sw.rs
internal/backends/winit/winitwindowadapter.rs
internal/core/graphics.rs
internal/core/graphics/wgpu_26.rs
internal/renderers/skia/opengl_surface.rs

wgpu: Fall back to software rendering if there are no GPU-backed WGPU adapters

---

api/cpp/cbindgen.rs
api/cpp/include/slint-interpreter.h
api/cpp/include/slint-testing.h
api/cpp/include/slint.h
api/cpp/include/slint_image.h
api/cpp/include/slint_string.h
api/cpp/include/slint_window.h
internal/compiler/generator/cpp.rs

The second constructor of `Slice` causes the Slice to be passed differently (in different register) as a return value.
So remove that constructor and use a helper function to construct a Slice

C++: Fix ABI mismatch with `Slice` on MSVC AArch64

---

api/cpp/cbindgen.rs
api/rs/build/lib.rs
internal/compiler/build.rs
internal/compiler/generator/cpp.rs
internal/compiler/generator/cpp_live_reload.rs
tests/doctests/build.rs
tests/driver/cpp/build.rs
tests/driver/rust/build.rs
tests/screenshots/build.rs
tools/compiler/main.rs
tools/lsp/fmt/tool.rs
tools/updater/main.rs
xtask/src/slintdocs.rs

Quoting from the BufWriter docs:
>It is critical to call flush before BufWriter<W> is dropped. Though
>dropping will attempt to flush the contents of the buffer, any errors
>that happen in the process of dropping will be ignored. Calling flush
>ensures that the buffer is empty and thus dropping will not even
>attempt file operations.

Ensure error reporting when using buffered file writes

---

tools/lsp/ui/components/console-panel.slint
tools/lsp/ui/main.slint

as per request added a control to scale console
left the right expand button persistent to make scaling to preferred size (and shut) easy
in future would prefer that last console message that shows up in the header to be in the instruction message area
and have an affordance there to expand console - otherwise no other useful messages show up other than console ones - and instructions on what keys to press when on a particular tool do not belong in the console log...
removed highlight for console as nothing else highlights the header and there are not multiple tabs next to console yet. we can cross that bridge when we get to it

live-preview: console scale control

---

internal/compiler/passes/resolving.rs
tests/cases/issues/issue_9209_array_in_struct_conversion.slint

This fixes the issue #9209 only for the case of `?:` operator, but not for the case of array.
(See the FIXME in the test)
I propose to keep the issue #9209 open, but re-purpose it for the inference in array.

Fix inference of array literal in struct within the ternary operator

---

internal/compiler/widgets/cosmic/switch.slint
internal/compiler/widgets/cupertino/switch.slint
internal/compiler/widgets/fluent/switch.slint

Currently, the min-with don't account for the text. That means that, for example, the switch on the top bar of the gallery, get the text to overflow which doesn't look good by default

Switch: ensure that the min-width contains the text

---

internal/compiler/widgets/common/lineedit-base.slint
internal/compiler/widgets/cosmic/lineedit.slint
internal/compiler/widgets/cupertino/lineedit.slint
internal/compiler/widgets/fluent/lineedit.slint
internal/compiler/widgets/material/lineedit.slint

The problem was that the `LineEditPasswordIcon` had an internal property that would get out of sync when the component is re-created. The component does get re-created in fluent depeding on the focus, and this is the case especially with wasm because of the hidden input that takes the focus.
Fixes #9225

LineEdit: Fix show password icon being out of sync with fluent

---

api/cpp/platform.rs
internal/backends/android-activity/androidwindowadapter.rs
internal/backends/winit/lib.rs
internal/backends/winit/renderer/skia.rs
internal/core/graphics/wgpu_26.rs
internal/renderers/femtovg/wgpu.rs
internal/renderers/skia/Cargo.toml
internal/renderers/skia/cached_image.rs
internal/renderers/skia/d3d_surface.rs
internal/renderers/skia/lib.rs
internal/renderers/skia/metal_surface.rs
internal/renderers/skia/opengl_surface.rs
internal/renderers/skia/software_surface.rs
internal/renderers/skia/vulkan_surface.rs
internal/renderers/skia/wgpu_26_surface.rs
internal/renderers/skia/wgpu_26_surface/dx12.rs
internal/renderers/skia/wgpu_26_surface/metal.rs
internal/renderers/skia/wgpu_26_surface/vulkan.rs

This enables using Skia for GUI rendering but combining it with application-provided WGPU textures, by transparently making `require_wgpu_25` work also with the skia renderer.

Skia: Add support for rendering with WGPU

---

internal/common/enums.rs

`Programmatic` makes more sense as a default value for that enum
Technically a breaking change, but since that enum was introduced recently and it is unlikely that people have used it in property so far, it makes sense to get a decent default now.

FocusReason: change the default value

---

tools/docsnapper/Cargo.toml
tools/docsnapper/main.rs

Highlight errors in red when running docsnapper when running in a terminal.
Print "[error]" in all cases as apparently Github will highlight that in red in CI run logs (which are not considered to be in a terminal).

docsnapper: Print erros in red

---

CHANGELOG.md
docs/astro/src/content/docs/reference/global-structs-enums.mdx
docs/astro/src/content/docs/reference/keyboard-input/focusscope.mdx
internal/common/enums.rs
internal/compiler/builtins.slint
internal/core-macros/link-data.json
internal/core/items/input_items.rs
tests/cases/focus/focus_policy.slint
tests/cases/focus/keyboard_focus_capture.slint

As discussed in API review, we thought that as we don't have bitflag, it makes more sense to have two boolean properties.
Also change the behavior as the focus out event should always be forwarded regardless of the policy.

FocusScope: Remove FocusPolicy and adds two bool state instead

---

api/rs/slint/lib.rs

This reverts commit 14483a6e32f782d98eeb71848cd48c6041e1e70c. musl works fine with slint and making it a fatal error instead of warning prevents usage of slint.

Revert "feat: raise compiler error if musl is used (#8450)"

---

api/cpp/docs/index.rst
api/cpp/docs/live_preview.md

So that it can be linked to from the blog post :)

cmake: Add the live-preview feature to the CMake reference

---

internal/compiler/parser.rs
internal/compiler/parser/element.rs
internal/compiler/passes/resolving.rs
tests/cases/bindings/change_sub_property.slint
tests/cases/properties/changes_loop.slint
tools/lsp/util.rs

For consistency with the normal callbacks

Parse: accept changed callback without brace

---

internal/core/items/text.rs

Add `edited` callback on undo/redo fixes #9205

---

internal/compiler/generator/rust_live_preview.rs

Put the absolute path in the binary.

live-preview for rust: Fix loading from `slint!` macro

---

internal/backends/qt/qt_accessible.rs
internal/backends/qt/qt_widgets.rs

So it doesn't need to include GL/gl.h which cannot be found on some systems
Fixes #9309

Qt: don't include the full of QtWidgets

---

internal/backends/winit/Cargo.toml
internal/backends/winit/muda.rs

When the state of menus are changed, the `muda` representation of menus is completely torn down and rebuilt.  On Windows, this can create a slight flicker unless the act of redrawing the window is disabled.  With this change, we use `WM_SETREDRAW` to disable redrawing while the menus are being reconstructed.
It isn't clear to me if other platforms have a similar problem.

Windows: Use `WM_SETREDRAW` to disable redraw when rebuilding `muda` menus

---

editors/zed/README.md

The binary field is not a string but a struct:
```rust
/// The settings for a command.
#[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct CommandSettings {
/// The path to the command.
pub path: Option<String>,
/// The arguments to pass to the command.
pub arguments: Option<Vec<String>>,
/// The environment variables.
pub env: Option<HashMap<String, String>>,
}
```

zed extension: Fix "documented" syntax for configuring slint-lsp path

---

internal/compiler/object_tree.rs
tests/cases/elements/contextmenu_in_repeater.slint

Same as in `recurse_elem_including_sub_components`
This happens for example in `lower_menus` which resulted in the pass being done twice in some component which would cause errors.
Fixes #9319

Compiler: Fix `recurse_elem_including_sub_components_no_borrow` when called before `process_repeater_components`

---

examples/opengl_underlay/main.rs

`mediump` limits uniforms to an `f16` which limits `effect_time` to `65504` milliseconds and so once we reach 66 seconds the shader crashes.

Fix opengl underlay example shader crash after 65s

---

internal/renderers/femtovg/lib.rs
internal/renderers/femtovg/opengl.rs

In earlier refactorings, passing through the id of the HTML canvas element got "lost". Restore this by handling it in the place where we also have access to the element.
This restores rendering as part #9345 , but the size of the canvas is still wrong. But if resized manually you can see rendering now :)
cc #9345

FemtoVG: Fix panic when used with WebGL

---

internal/backends/winit/Cargo.toml
internal/backends/winit/build.rs

The new release rustix 1.1.1 fails to compile on android when it's feature "process" is activated. This is enabled by the zbus crate
We do not need zbus from i-slint-backend-winit on android (actually we do not usually use that backend on android, but we just compile it there on the CI for the internal docs)

Prospective CI fix

---

examples/mcu-board-support/pico2_st7789.rs

43ede0b1c3570f20bc9f4d3f4392c379c4c565f7 was for pico

pico2_st7789: Turn on backlight after first frame is drawn (#7482)

---

api/cpp/cbindgen.rs
api/rs/slint/private_unstable_api.rs
docs/astro/src/content/docs/guide/backends-and-renderers/backends_and_renderers.mdx
docs/astro/src/content/docs/reference/common.mdx
docs/astro/src/content/docs/reference/elements/image.mdx
docs/astro/src/content/docs/reference/elements/text.mdx
internal/backends/qt/qt_window.rs
internal/compiler/builtins.slint
internal/compiler/passes.rs
internal/compiler/passes/lower_property_to_element.rs
internal/compiler/typeregister.rs
internal/core/item_rendering.rs
internal/core/item_tree.rs
internal/core/items.rs
internal/core/software_renderer.rs
internal/interpreter/dynamic_item_tree.rs
internal/renderers/femtovg/itemrenderer.rs
internal/renderers/skia/itemrenderer.rs
tests/cases/elements/event_scaling.slint
tools/lsp/preview/properties.rs

Takes over from https://github.com/slint-ui/slint/pull/9382. @tronical @NigelBreslaw.
I think we're going to need some equivalent of this compiler pass: https://github.com/slint-ui/slint/blob/d16d531709bde23c447788503be16dbc9cf08220/internal/compiler/passes.rs#L168-L191 that checks for `rotation-angle` or `scale-x` or `scale-y` (or even a uniform `scale` in the future).

Change the `Rotate` item to a `Transform` that supports scaling

---

api/python/slint/interpreter.rs
api/python/slint/lib.rs
api/python/slint/models.rs
api/python/slint/tests/test_loop.py
api/python/slint/timer.rs

Instead of printing exceptions in callbacks to stderr, let's raise them as unraisable exceptions, but catch SystemExit and forward it through the event loop.
Fixes #9416

Python: Add support for sys.exit() from callbacks/timers/etc.

---

examples/mcu-board-support/Cargo.toml
examples/mcu-board-support/m5stack_cores3.rs

* The `esp-bootloader-esp-idf` dependency requires `esp32s3` as feature. Not sure if this works with all ESP devices.
* The `esp_bootloader_esp_idf::esp_app_desc!` macro is broken when there are no arguments. I added a few dummy arguments.

Fix m5stack_cores3 build

---

internal/core/window.rs
tests/cases/elements/popupwindow_nested.slint

This PR ensures all active popups are closed before creating a new one.
Fixes #8891

Close active popups before creating a new one

---

internal/renderers/skia/wgpu_26_surface.rs

Apply commit ae204bda251489191b2d6bfd0014e791f8a831ce also to the wgpu surface of the skia renderer.
cc #8693

Skia/WGPU: Enable vsync by default

---

internal/compiler/tests/syntax/imports/library.slint
internal/compiler/typeloader.rs
tools/slintpad/README.md
tools/slintpad/src/editor_widget.ts
tools/slintpad/src/lsp.ts

Also allow `https://` URL to be mapped directly for libraries (without loading them in a editor tab)

Slintpad: allow to load libraries with `?lib=foo=https://...`

---

api/python/slint/slint/__init__.py
api/python/slint/tests/test_async.py

Python: Fix event loop terminating too early when the main coro finishes

---

.github/workflows/ci.yaml
.github/workflows/cpp_package.yaml
.github/workflows/nightly_snapshot.yaml
.github/workflows/nightly_tests.yaml
.github/workflows/publish_npm_package.yaml
.github/workflows/slint_tool_binary.yaml
.github/workflows/upload_pypi.yaml
api/node/binaries.json
docs/astro/src/content/docs/guide/platforms/desktop.mdx

GitHub is going to remove the free x86-64 macos runners, as per https://github.blog/changelog/2025-07-11-upcoming-changes-to-macos-hosted-runners-macos-latest-migration-and-xcode-support-policy-updates/

Remove support for x86-64 macOS binaries

---

internal/compiler/passes/lower_layout.rs
internal/compiler/passes/materialize_fake_properties.rs
internal/compiler/tests/syntax/basic/layout2.slint
tests/cases/layout/grid.slint
tests/cases/layout/grid_span.slint

ChangeLog: implicit properties row, col, rowspan, colspan for items in a GridLayout are now accessible to bindings expressions

Gridlayout: make implicit properties row, col, rowspan, colspan accessible for bindings

---

.github/workflows/material.yaml

The Material CI would run for all PR's. This change allows the earlier 
limits based on which files have changed to apply. It also stops a 
duplicate run happening for any material PR's.
Name of action tweaked to make it easier to spot in the list of actions.

Stop the Material CI running when not needed

---

.github/workflows/material.yaml

Turns out it wasn't running twice. It was running 3 times. This finally 
fixes the duplicate runs.

Stop duplicate Material CI run

---

docs/astro/src/content/docs/guide/language/coding/globals.mdx

As reported in #6877 and #9501

Docs: document that the globals are not shared accreoss windows

---

internal/core/animations.rs
internal/core/platform.rs

It may not exactly be the solution requested in #3491, but after looking around the code I found the clock monotonicity is an invariant and `Duration` (base type `u64`) arithmetic may panic if new tick is lower than old one. It makes sense to assert the new value is higher than the current one. I'm not sure about risks on embedded targets, however.
I'm open to suggestions.
On the topic of warnings, I found only `debug_log!()` macro in `internal/core/tests.rs` - is this only logging available for Slint's internals?

Add assertions for clocks monotonicity

---

internal/core/textlayout/sharedparley.rs
internal/renderers/femtovg/itemrenderer.rs

When breaking multiples lines of text and the last line can't be broken anymore but exceeds the available width *and* overflow handling is set to elide, *then* apply the elision glyph substitution.
Also, centralize more of this inside just one glyph iterator, so that re-use in the other renderers will be trivial. This also avoids one extra vec allocation when collecting the glyphs.

parley: Apply elision only on the last line

---

api/rs/build/lib.rs

I don't know if that'd help, but might have prevented https://github.com/slint-ui/slint/discussions/9563

Docs for slint-build: add note that one must use `include_modules`

---

internal/common/enums.rs
internal/core/layout.rs
ui-libraries/material/docs/src/content/collections/enums/LayoutAlignment.md

Add `space-evenly` to the layout options. These already included `space-around`, `space-between`, `start`, `end`, etc.
Also rewords the definition of `SpaceAround`, which now mentions that the spaces at the beginning and end are half spaces.
As for documentation, I included the definition inside [LayoutAlignment.md](https://github.com/slint-ui/slint/tree/master/ui-libraries/material/docs/src/content/collections/enums/LayoutAlignment.md), but I'm aware this would require future additions, such as in the official [docs](https://github.com/slint-ui/slint/tree/master/docs/astro/src/content/docs/guide/language/coding/positioning-and-layouts.mdx), where I found this missing feature in the first place.
These are fairly straightforward changes and should not break anything. I'd be happy to run …

feat: add space-evenly alignment to layout

---

internal/compiler/generator/rust.rs
tests/cases/issues/issue_4942_no_else_value.slint
tests/cases/issues/issue_9546.slint
tests/driver/cpp/cppdriver.rs

A cast to void in an expression sometimes added a `;` at the wrong place.
Fixes #9546

compiler: Fix rust generated code adding a `;` in parentheses

---

internal/core/item_rendering.rs
internal/core/textlayout/sharedparley.rs
internal/renderers/femtovg/itemrenderer.rs
internal/renderers/femtovg/lib.rs

This PR minimises the code in the FemtoVG renderer for text rendering and fixes two bugs with the text cursor and selection rendering.
cc #9559

parley: Various cleanups and fixes

---

tools/lsp/ui/components/widgets/basics.slint

When clicking a property the value was not being highlighted. So as you 
would type the value or '0' would be left and you would end up seeing 
`x: 030`. This now adds the expected behaviour where the value is 
highlighted on focus and typing replaces the whole value.

live-preview: Auto highlight property on focus

---

.github/workflows/material.yaml

Currently PR's that trigger the Material CI to run will fail for 
external PR's due to how the APK signing key needs to be secured. This 
PR skips the APK build for external PR's as we build it in a manual run 
only when we publish a new Material update.

Material: Stop the APK building for external PR's

---

internal/compiler/widgets/qt/menu.slint

This makes it much more readable for more on my KDE Plasma system. These colors are also meant for highlights/selection too, especially compared to the QPalette::Highlight/Accent which doesn't have enough contrast for text.
I also changed it for MenuBarItem.
| Before | After |
|--------|--------|
| <img width="325" height="321" alt="Screenshot_20251003_131943" src="https://github.com/user-attachments/assets/59729550-5bf1-4f1e-8fe3-91cd3a7082f0" /> | <img width="325" height="321" alt="Screenshot_20251003_131906" src="https://github.com/user-attachments/assets/4fe2fc5b-2689-442e-9210-53764e15898a" /> |

Qt: Use selection colors from NativePalette for MenuItem/MenuBar

---

docs/astro/src/content/docs/reference/global-namespaces/platform.mdx

Since the properties didn't specify a defaultValue, it would say technically incorrect things like the "first enum value". But we don't know the actual value of these properties until runtime.
I also changed the "new platform support" message to refer it to as an enum, not a table.

Improve Platform properties default value documentation

---

docs/astro/src/content/docs/reference/std-widgets/views/scrollview.mdx

Instead of writing it as a literal documentation comment, we can specify
defaultValue on the SlintProperty itself like other items do.
---
It's now a separate note block, so it doesn't blend in with the rest of
the paragraph. I also turned the issue number into a real link, like we
do elsewhere already.

Some small ScrollView documentation changes

---

internal/backends/qt/qt_widgets/scrollview.rs
internal/compiler/builtins.slint
internal/compiler/widgets/qt/internal-scrollview.slint

This is supposed to be emitted whenever the user performs an intentional interaction, which works whenever you scroll the Slint Flickable with the scrollwheel. Dragging the scrollbar on the Qt style didn't do anything, since that was never hooked up to this callback.
I only implemented this in the Qt style, because that's the only one that uses the NativeScrollView element.
See #9574.

Qt: Emit scrolled callback when dragging scrollbar

---

Cargo.toml
internal/backends/qt/qt_window.rs
internal/core/Cargo.toml
internal/core/textlayout/sharedparley.rs
internal/renderers/femtovg/font_cache.rs
internal/renderers/femtovg/itemrenderer.rs
internal/renderers/skia/font_cache.rs
internal/renderers/skia/itemrenderer.rs

parley: Upgrade to parley and fontique 0.6

---

examples/bevy/Cargo.toml
internal/backends/winit/Cargo.toml
internal/backends/winit/lib.rs
internal/backends/winit/renderer/femtovg.rs
internal/renderers/femtovg/Cargo.toml
internal/renderers/femtovg/font_cache.rs
internal/renderers/femtovg/images.rs
internal/renderers/femtovg/lib.rs
internal/renderers/femtovg/wgpu.rs

Also:
- The newer version of femtovg permits disabling text layouting, so this means less dependencies
- Skia is the only renderer left to support wgpu 26, so unstable-wgpu-26 now implies a dependency to renderer-skia
Closes #9605

femtovg: Upgrade to wgpu 27

---

demos/home-automation/ui/components/mainView/widgetLoader.slint
demos/home-automation/ui/components/mainView/widgetLoaderSoftwareRenderer.slint
docs/astro/src/content/docs/reference/common.mdx
examples/fancy-switches/DarkModeSwitch.slint
internal/compiler/builtins.slint
internal/compiler/passes.rs
internal/compiler/passes/lower_property_to_element.rs
internal/compiler/typeregister.rs
internal/core/item_tree.rs
internal/core/items.rs
tests/cases/elements/event_scaling.slint
tests/cases/elements/scaling2.slint

- Rename `scale-*` to `transform-scale-*` (second commit)
- Add a `transform-scale` property, make it the default for the `-x` and `-y` variant (first commit)
- Also update the examples to use the transform-scale

Add a `transform-scale` property to all elements and rename `scale-x` and `scale-y`

---

docs/common/src/components/SlintProperty.astro

Previously, we sent users to the top of the page whenever they click on a property that refers to a global enum/struct in our documentation. However the page is already filled with permalinks we can use, so I made it so we assume there's a permalink.
If the permalink doesn't exist, it would just send them back to the top of the page anyway which was the previous status quo.

Link directly to individual global enums/structs in documentation

---

.github/workflows/ci.yaml
.github/workflows/nightly_tests.yaml

Work around a regression in pydantic until a new patch release is available. For details, see https://github.com/espressif/idf-component-manager/issues/97#issuecomment-3380777944

esp-idf: Fix build failure

---

tests/cases/widgets/scrollview.slint

As brought up in 7d038eb9e293b243880269e65f6799bb69998d83, the bug I was fixing should really have a test for it - so I added one. Testing the scrolled callback is a bit odd to handle because not only does each style have a different scroll handle but it's a bit dubious when/how many scrolled callback emissions there should be.
I was able to find a sweet spot for both of these problems, and although the test case is a bit vague it does catch when a style doesn't emit the callback.

Add new widget test for ScrollView, test the scrolled callback
